data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkRetryStrategy.java

OpenSearch Sink: Add log messages when there is no exception.
OpenSearch Sink BulkOperation failure logs messages only if there is an exception. It is possible that it fails without exception, it is good to log the error reasons for each operation in those cases as well.
Resolves #3508 
Resolves #3508 

OpenSearch Sink: Add log messages when there is no exception

---

.github/workflows/data-prepper-log-analytics-basic-grok-e2e-tests.yml
.github/workflows/data-prepper-peer-forwarder-local-node-e2e-tests.yml
.github/workflows/data-prepper-peer-forwarder-static-e2e-tests.yml
.github/workflows/data-prepper-trace-analytics-raw-span-compatibility-e2e-tests.yml
.github/workflows/data-prepper-trace-analytics-raw-span-e2e-tests.yml
.github/workflows/data-prepper-trace-analytics-raw-span-peer-forwarder-e2e-tests.yml
.github/workflows/data-prepper-trace-analytics-service-map-e2e-tests.yml
buildSrc/build.gradle
buildSrc/src/main/java/org/opensearch/dataprepper/gradle/end_to_end/DockerProviderTask.java
e2e-test/build.gradle
e2e-test/log/build.gradle
e2e-test/peerforwarder/build.gradle
e2e-test/peerforwarder/src/integrationTest/resources/data_prepper_static.yml
e2e-test/trace/build.gradle
e2e-test/trace/src/integrationTest/resources/data_prepper_static.yml

This PR updates the end-to-end tests to make use release artifacts. This moves toward replacing the existing smoke tests with our end-to-end tests instead, though it doesn't complete that transition.
With this PR, our end-to-end test will use release artifacts. This means that our PRs will run tests against actual artifacts instead of test-specific artifacts.
This PR:
* Adds a new `endToEndJavaVersion` option named `docker` which runs using the release Docker image.
* Updates the custom end-to-end Docker image to use the release tar.gz instead of building custom packaging.
* Run end-to-end tests using the release Docker image by default.
* Adds a `buildSrc` to start sharing more logic between classes.
* Makes more use of `tasks.register()` which allows Gradle to evaluate the tasks when …

Update end-to-end tests to use the release Docker image or release archive

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/acknowledgements/AcknowledgementSet.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/acknowledgements/ProgressCheck.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/acknowledgements/AcknowledgementAppConfig.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/acknowledgements/DefaultAcknowledgementSet.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/acknowledgements/DefaultAcknowledgementSetManager.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/acknowledgements/DefaultProgressCheck.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/acknowledgements/DefaultAcknowledgementSetManagerTests.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/acknowledgements/DefaultAcknowledgementSetTests.java
data-prepper-plugins/kafka-plugins/src/integrationTest/java/org/opensearch/dataprepper/plugins/kafka/source/KafkaSourceJsonTypeIT.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaCustomConsumerTest.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSink.java
data-prepper-plugins/s3-source/src/integrationTest/java/org/opensearch/dataprepper/plugins/source/s3/S3ScanObjectWorkerIT.java
data-prepper-plugins/s3-source/src/integrationTest/java/org/opensearch/dataprepper/plugins/source/s3/SqsWorkerIT.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/SqsWorker.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/configuration/SqsOptions.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/s3/SqsWorkerTest.java

Add ProgressCheck callbacks to end-to-end acknowledgements
Adds optional progress check callbacks the acknowledgement set create api

Add ProgressCheck callbacks to end-to-end acknowledgements

---

data-prepper-plugins/opensearch/build.gradle
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/DynamicIndexManager.java
data-prepper-plugins/otel-trace-raw-processor/build.gradle
data-prepper-plugins/otel-trace-raw-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/oteltrace/OTelTraceRawProcessor.java

This PR replaces the usages of the legacy Guava Cache in favor of Caffeine — Guava maintainers themselves [recommend it](https://guava.dev/releases/31.0-jre/api/docs/com/google/common/cache/CacheBuilder.html). 
> Prefer [Caffeine](https://github.com/ben-manes/caffeine/wiki) over Guava's caching API
The successor to Guava's caching API is [Caffeine](https://github.com/ben-manes/caffeine/wiki). Its API is designed to make it a nearly drop-in replacement -- though it requires Java 8 APIs and is not available for Android or GWT/j2cl. Its equivalent to CacheBuilder is its [Caffeine](https://www.javadoc.io/doc/com.github.ben-manes.caffeine/caffeine/latest/com.github.benmanes.caffeine/com/github/benmanes/caffeine/cache/Caffeine.html) class. Caffeine offers better performance, more features …

Replace Guava Cache with Caffeine for OpenSearch integration

---

data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/converter/MetadataKeyAttributes.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/converter/RecordConverter.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/converter/ExportRecordConverterTest.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/converter/StreamRecordConverterTest.java

This change uses the `index` bulk action for `INSERT` and `MODIFY` events for the `op` (renamed to `opensearch_action` metadata attribute instead of the `create` and `upsert` actions. This change also adds another metadata attribute `dynamodb_event_name`, which will be one of `INSERT`, `MODIFY`, or `REMOVE`.
This change also renames the `ts` metadata attribute to `dynamodb_timestamp`, to more clearly indicate that it is coming from the dynamodb source

Add dynamodb_event_name metadata attribute, change mapping for Ddb INSERT and MODIFY to be index bulk action

---

data-prepper-plugins/dynamodb-source/README.md
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/DynamoDBService.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/configuration/ExportConfig.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/coordination/state/ExportProgressState.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/export/DataFileLoader.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/export/ExportScheduler.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/export/ExportTaskManager.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/export/ManifestFileReader.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/model/TableMetadata.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/export/DataFileLoaderTest.java

Add KMS CMK support to DynamoDB source when for encrypt the export output files using customer managed key.
Resolves #3564 #3470 

Add CMK encryption support to DynamoDB export

---

data-prepper-plugins/opensearch/src/integrationTest/java/org/opensearch/dataprepper/plugins/sink/opensearch/DeclaredOpenSearchVersion.java
data-prepper-plugins/opensearch/src/integrationTest/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSinkIT.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/ComposableIndexTemplate.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/ComposableTemplateAPIWrapper.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/LegacyIndexTemplate.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/ComposableIndexTemplateStrategyTest.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/ComposableTemplateAPIWrapperTest.java

The goal of this PR is to support ISM correctly when using composable index templates. There were two problems causing this.
1. The `ComposableIndexTemplate` class was not setting properties. This was easily resolved.
2. The opensearch-java client does not serialize custom properties. Thus, I had to write it as a `Map` instead of using the higher-level constructs.
There are a few other changes here as well.
1. The end-to-end tests can run without defining the OpenSearch version by using the default if it is an empty string.
2. Updates to imports in the `OpenSearchIT` test.
3. Made some classes package private.
Resolves #3506  …

Support ISM correctly when using composable index templates

---

data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/configuration/SqsOptions.java

This makes a few changes to the new visibility timeout extension feature:
* Rename the configuration to `maximum_visibility_timeout_extension`. This remains consistent with other names such as `maximum_messages`.
* Increase the default maximum extension timeout to 2 hours.
* Increase the largest extension timeout allowed to 24 hours.
N/A
Changes to the #3565 PR to help finish up #2485.

Visibility timeout extension configuration changes

---

data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/buffer/KafkaBuffer.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaCustomConsumer.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaCustomConsumerFactory.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/TopicEmptinessMetadata.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/source/KafkaSource.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/buffer/KafkaBufferTest.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaCustomConsumerTest.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/consumer/TopicEmptinessMetadataTest.java

Adds logic to check that all partitions on the topic associated with a consumer are fully processed before shutdown. Wires this into the isEmpty method of the KafkaBuffer

Check topic for emptiness during KafkaBuffer shutdown

---

data-prepper-plugins/s3-source/src/integrationTest/java/org/opensearch/dataprepper/plugins/source/s3/SqsWorkerIT.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/SqsWorker.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/configuration/SqsOptions.java

Update `maximum_visibility_timeout_extension` to`visibility_duplicate_protection_timeout`

Updated visibility protection timeout option

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/breaker/CircuitBreaker.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/buffer/DelegatingBuffer.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/buffer/DelegatingBufferTest.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/breaker/CircuitBreakerAppConfig.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/breaker/CircuitBreakerManager.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/breaker/HeapCircuitBreaker.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/breaker/InnerCircuitBreaker.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/parser/CircuitBreakingBuffer.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/plugin/ComponentPluginArgumentsContext.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/plugin/DefaultPluginFactory.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/breaker/CircuitBreakerIT.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/breaker/CircuitBreakerManagerTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/parser/CircuitBreakingBufferTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/parser/PipelineTransformerTests.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/plugin/DefaultPluginFactoryTest.java
data-prepper-plugins/kafka-plugins/src/integrationTest/java/org/opensearch/dataprepper/plugins/kafka/buffer/KafkaBufferIT.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/buffer/KafkaBuffer.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaCustomConsumer.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaCustomConsumerFactory.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/PauseConsumePredicate.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/source/KafkaSource.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/buffer/KafkaBufferTest.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaCustomConsumerTest.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/consumer/PauseConsumePredicateTest.java

This PR supports using the circuit breaker in the Kafka source to delay reading from the Kafka topic. It has the following significant changes:
* Moves the `CircuitBreaker` interface to data-prepper-api and renames the package to match existing conventions.
* Adds a `DelegatingBuffer` implementation to help with decorator buffers. We don't strictly need this, but I made the change for one variation I worked toward, so I included it.
* Support getting a `CircuitBreaker` object in an `@DataPrepperPluginConstructor`.
* Pause reading from the Kafka buffer when the circuit breaker is open.
Resolves #3578
For more information on following Developer Certificate of Origin and signing …

Pause reading from Kafka in the Kafka buffer when the circuit breaker is open

---

data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/producer/KafkaCustomProducer.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/producer/KafkaCustomProducerFactory.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/util/KafkaTopicProducerMetrics.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/producer/KafkaCustomProducerTest.java

Add Kafka Producer metrics for send record failures

Add Kafka Producer metrics for send record failures

---

.github/workflows/gradle.yml
.github/workflows/performance-test-compile.yml
build.gradle

Add Java 11/17/21 matrix for build, test and performance test checks
Part of https://github.com/opensearch-project/OpenSearch/issues/10334, closes https://github.com/opensearch-project/data-prepper/issues/3329

Add Java 11/17/21 matrix for build, test and performance test checks

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/metric/JacksonExponentialHistogram.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/metric/JacksonHistogram.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/metric/JacksonMetric.java
data-prepper-plugins/otel-metrics-raw-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/otelmetrics/OTelMetricsRawProcessor.java
data-prepper-plugins/otel-metrics-raw-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/otelmetrics/OtelMetricsRawProcessorConfig.java
data-prepper-plugins/otel-metrics-raw-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/otelmetrics/MetricsPluginSumTest.java
data-prepper-plugins/otel-metrics-raw-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/otelmetrics/MetricsPluginSummaryTest.java
data-prepper-plugins/otel-metrics-source/build.gradle
data-prepper-plugins/otel-metrics-source/src/main/java/org/opensearch/dataprepper/plugins/source/otelmetrics/OTelMetricsGrpcService.java
data-prepper-plugins/otel-metrics-source/src/main/java/org/opensearch/dataprepper/plugins/source/otelmetrics/OTelMetricsSource.java
data-prepper-plugins/otel-proto-common/src/main/java/org/opensearch/dataprepper/plugins/otel/codec/OTelMetricDecoder.java
data-prepper-plugins/otel-proto-common/src/main/java/org/opensearch/dataprepper/plugins/otel/codec/OTelProtoCodec.java
data-prepper-plugins/otel-proto-common/src/test/java/org/opensearch/dataprepper/plugins/otel/codec/OTelProtoCodecTest.java
data-prepper-plugins/otel-proto-common/src/test/resources/test-gauge-metrics.json
data-prepper-plugins/otel-proto-common/src/test/resources/test-histogram-metrics.json
data-prepper-plugins/otel-proto-common/src/test/resources/test-sum-metrics.json

Add support for OTEL metrics source to use Kafka buffer
Added OTEL Proto Decoder that is instantiated by OTEL metrics source. 

Add support for OTEL metrics source to use Kafka buffer

---

data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/integration/Router_ThreeRoutesIT.java

This has two changes:
* Updates the timeout for reaching a condition. This condition uses Awaitility, so it doesn't need to take that long, but this gives it more time. Hopefully this helps with some flaky tests.
* Use Awaitility's [`during()` method](https://github.com/awaitility/awaitility/wiki/Usage#assert-that-a-value-is-maintained) to assert that a condition is true over time rather than sleeping.
None, but contributes toward some flaky tests in #3481.

Flaky test work: Updated the Router_ThreeRoutesIT test with a longer timeout.

---

data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/common/opensearch/ServerlessNetworkPolicyUpdater.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/common/opensearch/ServerlessNetworkPolicyUpdaterFactory.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/common/opensearch/ServerlessOptionsFactory.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/ConnectionConfiguration.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSink.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/OpenSearchService.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/OpenSearchSource.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/configuration/AwsAuthenticationConfiguration.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/configuration/ServerlessOptions.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/common/opensearch/ServerlessNetworkPolicyUpdaterFactoryTest.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/common/opensearch/ServerlessNetworkPolicyUpdaterTest.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/common/opensearch/ServerlessOptionsFactoryTest.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/OpenSearchSourceTest.java

Allow AOSS source to create/update a network policy during initialization
Tested with:
```
version: "2"
log-pipeline:
source:
opensearch:
hosts: [ "https://cw4c6ujthlys4gf4qp7c.us-east-1.aoss.amazonaws.com" ]
indices:
include:
- index_name_regex: ".*"      
aws:
sts_role_arn: "arn:aws:iam::841692598829:role/FizzyE2ETestPipelineExecutionRole"
serverless: true
serverless_options:
network_policy_name: …
```

Create network policy for aoss source.

---

data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/converter/MetadataKeyAttributes.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/converter/RecordConverter.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/converter/ExportRecordConverterTest.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/converter/StreamRecordConverterTest.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/DynamicIndexManager.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/IndexConfiguration.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/DynamicIndexManagerTests.java

* Adds a `normalize_index` flag, that defaults to false, to the `opensearch` sink. this makes it so invalid dynamic indices will be made valid according to these rules (https://opensearch.org/docs/1.0/opensearch/rest-api/create-index/#index-naming-restrictions). Any invalid characters will be removed
* Renames a metadata parameter for `dynamodb_item_version` to just `document_version` (Related to #3630)
Resolves #3487 

Add normalize_index flag to normalize invalid dynamic indices

---

data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/OpenSearchSourceConfiguration.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/SearchAccessorStrategy.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/model/DistributionVersion.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/OpenSearchSourceConfigurationTest.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/SearchAccessStrategyTest.java

Adds a `distribution_version` option to the OpenSearch source, which can be either `es7` or `opensearch`. When set, the client can be forced to use the `OpenSearch` client. This fixes an issue where Amazon OpenSearch Service domains with compatibility mode enabled do not hit exceptions when making an `info` API call with the OpenSearch client.
This was tested with Amazon OpenSearch Service domains that were upgraded from ES 7.10 to OS 1.3 and OS 2.9 with compatibility mode enabled, and the data migration was successfull …

Add distribution_version flag to opensearch source

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/JacksonEvent.java

this DEBUG log would show up every time someone uses a Data Prepper expression, which is unnecessary and verbose

Remove verbose debug log from JacksonEvent

---

data-prepper-plugins/kafka-plugins/src/integrationTest/java/org/opensearch/dataprepper/plugins/kafka/buffer/KafkaBufferIT.java
data-prepper-plugins/kafka-plugins/src/integrationTest/java/org/opensearch/dataprepper/plugins/kafka/buffer/KafkaBufferOTelIT.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/buffer/KafkaBuffer.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/buffer/KafkaBufferTest.java

Pass custom metric prefix if present to AbstractBuffer when using KafkaBuffer
Pass custom metric prefix if present to AbstractBuffer when using KafkaBuffer. All the AbstractBuffer metrics should have customPrefix with KafkaBuffer. Also using consumer metrics for emptyCheckingConsumers.

Pass custom metric prefix if present to AbstractBuffer when using KafkaBuffer

---

data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/admin/KafkaAdminAccessor.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/buffer/KafkaBuffer.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaCustomConsumer.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaCustomConsumerFactory.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/source/KafkaSource.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/admin/KafkaAdminAccessorTest.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/buffer/KafkaBufferTest.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaCustomConsumerTest.java

Followup from #3545 to use the admin client instead of a duplicate consumer set hack

Refactor to use Admin client instead of second set of consumers for empty check

---

data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/converter/ExportRecordConverter.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/converter/StreamRecordConverter.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/converter/ExportRecordConverterTest.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/converter/StreamRecordConverterTest.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/ShardConsumerTest.java

This PR adds bytesReceived and bytesProcessed into dynamoDB source

MAINT: add bytes metrics into dynamo source

---

data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/OpenSearchService.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/metrics/OpenSearchSourcePluginMetrics.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/NoSearchContextWorker.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/PitWorker.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/ScrollWorker.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/NoSearchContextWorkerTest.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/PitWorkerTest.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/ScrollWorkerTest.java

This PR adds bytesReceived and bytesProcessed metrics into opensearch source.

MAINT: add bytes metrics into opensearch source

---

data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/leader/LeaderScheduler.java

I've seen exceptions in `LeaderScheduler` that look like:
```
2023-11-13T14:22:14.631 [pool-15-thread-1] ERROR org.opensearch.dataprepper.plugins.source.dynamodb.leader.LeaderScheduler - Exception occurred: null
```
This PR changes this exception handling to include the full stack trace. As this is an unexpected error, that is most appropriate.
N/A

DynamoDB source: Full exception and stack trace for unexpected exceptions

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/sink/SinkLatencyMetrics.java

Rename latency metrics to follow the convention
Renamed `PipelineLatency` to `pipelineLatency` and `EndToEndLatency` to `endToEndLatency`

Change latency metric names

---

data-prepper-plugins/common/src/main/java/org/opensearch/dataprepper/plugins/source/RandomStringSource.java
data-prepper-plugins/common/src/main/java/org/opensearch/dataprepper/plugins/source/RandomStringSourceConfig.java
data-prepper-plugins/common/src/test/java/org/opensearch/dataprepper/plugins/source/RandomStringSourceTests.java

Adds the `wait_delay` configuration to the `random` source. Also, uses a single thread rather than an executor and increases test coverage in that class.
Resolves #3601

Configurable wait delay in the random string source

---

data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/SqsWorker.java

Catch failure to change visibility timeout and maintain a counter
Increments a counter `sqsVisibilityTimeoutChangeFailedCount` when fails to change visibility timeout

Catch failure to change visibility timeout and maintain a counter

---

data-prepper-plugins/kafka-plugins/src/integrationTest/java/org/opensearch/dataprepper/plugins/kafka/buffer/KafkaBufferIT.java

This PR follows on after #3635 with some integration test improvements.
* Adds a test case to verify that raw bytes are wrapped in the Protobuf message.
* Adds a test case to verify that raw bytes are wrapped in the Protobuf message and encrypted when encryption is configured.
* Verifies the Event received after calling writeBytes. This adds a verification to an existing test case that should have been there.
* Some test naming improvements
* Adding `final` modifiers.
N/A

KafkaBufferIT tests for writeBytes

---

build.gradle
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/converter/StreamRecordConverter.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/converter/StreamRecordConverterTest.java

This PR adds unit tests which replicate the behavior in #3664 of single quotes causing data loss. It fixes this by updating the AWS SDK to 2.21.23. We probably should update the version anyway to keep up with the latest.
This PR also adds different error handling when failures occur from parsing data that cannot work. Now the failure is logged and the error metric is incremented.
Resolves #3664

Correct single quote escape character in DynamoDB [#3664]

---

data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/converter/ExportRecordConverter.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/converter/RecordConverter.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/converter/StreamRecordConverter.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/coordination/partition/DataFilePartition.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/coordination/state/DataFileProgressState.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/export/DataFileLoader.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/export/DataFileLoaderFactory.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/export/DataFileScheduler.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/export/ExportScheduler.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/leader/LeaderScheduler.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/StreamScheduler.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/converter/ExportRecordConverterTest.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/export/DataFileLoaderFactoryTest.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/export/DataFileLoaderTest.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/export/DataFileSchedulerTest.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/export/ExportSchedulerTest.java

Changes the export version from being `0` to the `exportTime - 5 minutes`. This is so stream events still get priority over export Events, but new exports to the same index will not get version conflicts with OpenSearch with this change. 
Tested with export and streams, where updates/deletes were made after starting the pipeline, and the result was this in OpenSearch
```
Export version
1700033214421000
Update item
1700033604000000
```

Uses export time minus 5 minutes for export document version

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/plugin/ApplicationContextToTypedSuppliers.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/plugin/ComponentPluginArgumentsContext.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/plugin/DefaultPluginFactory.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/plugin/ApplicationContextToTypedSuppliersTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/plugin/ComponentPluginArgumentsContextTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/plugin/DefaultPluginFactoryTest.java

When working on #3595, I found that adding a new type directly from the Application Context into a Data Prepper plugin constructor requires quite a few code touches. Not only that, but it becomes hard to test new types like `CircuitBreaker` that are optional and can be `null`.
This PR splits the work for getting instances from the Application Context into a new class - `ApplicationContextToTypedSuppliers`. Any type that is just passed directly can use this mechanisms. 
Some classes remain in `DefaultPluginFactory` because there is additional logic within the plugin framework for them. For example, they are special arguments per-plugin, or additional work is performed from them (e.g. BeanFactory and PluginConfigurationObservableFactory).
N/A
By submitting this pull request, I confirm that …

Split loading plugin arguments from the Application Context

---

data-prepper-plugins/dynamodb-source-coordination-store/src/main/java/org/opensearch/dataprepper/plugins/sourcecoordinator/dynamodb/DynamoDbClientWrapper.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/DynamoDBService.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/DynamoDBSourceConfig.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/export/DataFileLoader.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/export/DataFileScheduler.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/export/ExportScheduler.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/ShardConsumer.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/ShardConsumerFactory.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/StreamScheduler.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/utils/BackoffCalculator.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/StreamSchedulerTest.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/utils/BackoffCalculatorTest.java

This change contains a couple fixes / improvements to the `dynamodb` source
1. Fixes a bug where empty acknowledgment sets for shards would be marked as complete on shutdown, which triggered the acknowledgment callback and attempted to mark the shard as completed in the coordination store
2. Fixes a bug where shutdown with `acknowledgments` enabled would not give up the partition (for both the shard and data file), which resulted in those partitions to not be available to other nodes until the `partitionOwnershipTimeout` expired, rather than immediately making those partitions available.
3. Fixes a potential NullPointerException in the `DynamoDbClientWrapper` for the coordination store
4. Increase default `shard_acknowledgment_timeout` from 3 minutes to 10 minutes. This is to encourage …

Add ddb source fixes/improvements

---

release/docker/Dockerfile
release/docker/adoptium.repo
release/docker/build.gradle

This updates the base image for Data Prepper to Amazon Linux 2023.
As this image does not have Java installed, it also installs Temurin using the Adoptium repository. It specifies the Amazon Linux 2 repository for this.
Resolves #3505

Use Amazon Linux 2023 as the base Docker image for Data Prepper

---

data-prepper-plugins/opensearch/src/integrationTest/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSinkIT.java

This PR validates special and extreme values in opensearch sink
Resolves #3678 

TST: validate special data in opensearch sink

---

examples/trace-analytics-sample-app/sample-app/requirements.txt

The goal is to resolve CVE-2023-46136 by updating werkzeug to 3.0.1. In order to update this version though, I also needed to update dash to 2.14.1.
Resolves #3552.

Updates werkzeug to 3.0.1 fixing CVE-2023-46136

---

build.gradle

Require Apache Avro 1.11.3 to fix CVE-2023-39410. 
Resolves #3430.

Require Apache Avro 1.11.3 to fix CVE-2023-39410

---

data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/SqsWorker.java

Saw these log messages in customer pipeline logs:
```
ERROR org.opensearch.dataprepper.plugins.source.s3.SqsWorker - Failed to delete 0 messages from SQS with errors: [].
```
This doesn't actually indicate any error. This change checks if failedDeleteCount is positive before logging
N/A

Check if failedDeleteCount is positive before logging

---

.github/workflows/gradle.yml
.github/workflows/release.yml

Limits the number of workers to 2 when building the main build and release builds on GitHub Actions.
I found that this increases the time to run from 10-11 minutes to 14-15 minutes. However, each test passed on the first run. So this might reduce flakiness significantly.
N/A

Gradle parallel max

---

gradle.properties

Sets the Data Prepper version to 2.6.0 (no SNAPSHOT)
N/A

Set Data Prepper version to 2.6.0.

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/source/SourceCoordinationStore.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/sourcecoordination/LeaseBasedSourceCoordinator.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/sourcecoordination/enhanced/EnhancedLeaseBasedSourceCoordinator.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/sourcecoordination/LeaseBasedSourceCoordinatorTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/sourcecoordination/enhanced/EnhancedLeaseBasedSourceCoordinatorTest.java
data-prepper-plugins/dynamodb-source-coordination-store/src/main/java/org/opensearch/dataprepper/plugins/sourcecoordinator/dynamodb/DynamoDbSourceCoordinationStore.java
data-prepper-plugins/dynamodb-source-coordination-store/src/test/java/org/opensearch/dataprepper/plugins/sourcecoordinator/dynamodb/DynamoDbSourceCoordinationStoreTest.java
data-prepper-plugins/in-memory-source-coordination-store/src/main/java/org/opensearch/dataprepper/plugins/sourcecoordinator/inmemory/InMemorySourceCoordinationStore.java
data-prepper-plugins/in-memory-source-coordination-store/src/test/java/org/opensearch/dataprepper/plugins/sourcecoordinator/inmemory/InMemorySourceCoordinationStoreTest.java

Currently, the dynamodb source coordination store using `ttl` will update the `ttl` whenever items are updated to keep them preserved. However, there are some cases where items in the table may be read-only, which means they will never be updated and will expire after the `ttl` no matter what. This would affect `dynamodb` source pipelines, as there are 3 GLOBAL read-only items (1 for table details, 1 for export details, 1 for stream details). 
Tested that the GLOBAL items do not receive an `expirationTime` as TTL with the dynamodb source …

Fix bug so GLOBAL read-only items do not expire from TTL in ddb source coordination store

---

examples/jaeger-hotrod/docker-compose.yml

There have been some updates in the images pulled for the Jaeger Hotrod demo's docker-compose which have broken the functionality, for example: https://github.com/opensearch-project/data-prepper/issues/2273#issuecomment-1827662450
I propose pinning versions which are working now and later explicitly changing the versions in the docker-compose when necessary.
Related to https://github.com/opensearch-project/data-prepper/issues/2273

Pin versions for jaeger-hotrod docker-compose

---

data-prepper-api/build.gradle
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/CheckpointStateTest.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/buffer/AbstractBufferTest.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/codec/HasByteDecoderTest.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/codec/JsonDecoderTest.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/codec/OutputCodecTest.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/configuration/PluginSettingsTests.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/event/JacksonEventTest.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/record/RecordTests.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/sink/AbstractSinkTest.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/source/SourceTest.java

Updates the last tests in `data-prepper-api` using JUnit 4 to JUnit 5. Removes JUnit Vintage from the project. Some related code improvements.
N/A

Updates data-prepper-api fully to JUnit 5

---

config/checkstyle/checkstyle.xml
config/checkstyle/import-control.xml

With #3586 updating to the Caffeine cache, we may still end up with Guava's cache being used. This PR adds a Checkstyle violation to prevent importing the Guava cache.
It's not perfect. I found you can work-around it by qualifying the class:
```
com.google.common.cache.Cache cache
```
But, that is more likely to be noticed during a code review.
N/A

Adds a Checkstyle validation to ensure that the Guava cache is not used.

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/metrics/PluginMetrics.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/metrics/PluginMetricsTest.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/DynamoDBService.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/export/DataFileScheduler.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/export/ExportScheduler.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/export/ExportTaskManager.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/leader/ShardManager.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/ShardConsumer.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/ShardConsumerFactory.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/utils/DynamoDBSourceAggregateMetrics.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/export/ExportSchedulerTest.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/leader/ShardManagerTest.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/ShardConsumerFactoryTest.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/ShardConsumerTest.java

This change adds the following aggregate metrics (metrics without a `sub-pipeline` prefix) to dynamoDB source pipelines
* `stream5xxErrors` - The number of errors encountered when calling stream APIs (`getRecords`, `getShardIterator`)
* `streamApiInvocations` - The number of invocations of stream APIs
* `export5xxErrors` - The number of errors encountered when calling export APIs (`exportTableToPointInTime`, `describeExport`)
* `exportApiInvocations` - The number of invocations of export APIs
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTI …

Add aggregate metrics for ddb source export and stream

---

data-prepper-plugins/parquet-codecs/build.gradle
data-prepper-plugins/s3-sink/build.gradle

Require `nimbus-jose-jwt` 9.37.1. This version fixes CVE-2021-31684 and CVE-2023-1370 by using a newer shaded version of json-smart.
See:
* https://bitbucket.org/connect2id/nimbus-jose-jwt/commits/c000d5245614e43eccfaaa07cdf0cfa87b471f4a
N/A

Require nimbus-jose-jwt 9.37.1 to fix CVE-2021-31684 and CVE-2023-1370

---

data-prepper-plugins/opensearch/src/integrationTest/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSinkIT.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSink.java

Fixes a bug where the update/upsert bulk actions were not applying filters from `include_keys`, `exclude_keys`, `tags_target_key`, and `document_root_key`
Resolves #3745 

Fix bug where update/upsert bulk action did not filter exclude/include keys, document_root_key, etc

---

data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/SqsWorker.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/parser/ParsedMessage.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/s3/SqsWorkerTest.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/s3/parser/ParsedMessageTest.java

This PR fixes parsing on empty folder creation S3 event in s3 source by skipping the zero size object processing.
Resolves #3727 

FIX: deal with event with object size zero

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/buffer/AbstractBuffer.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/buffer/KafkaBuffer.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/buffer/KafkaBufferTest.java

Fix Kafka Buffer metrics
While reading from Kafka inner buffer `doRead` API was used. This skips updating the metrics. modified to use `read` API which calls `doRead` and also updates metrics.

Fix kafka buffer metrics

---

examples/trace-analytics-sample-app/sample-app/analytics-service/build.gradle
performance-test/build.gradle

Use Logback 1.4.12 in the performance test project to fix CVE-2023-6378.
Also uses Logback 1.4.12 in the example Spring Boot application.
Resolves #3729

Logback 1.4.12 in performance test project to fix CVE-2023-6378

---

build.gradle
data-prepper-api/build.gradle
data-prepper-plugins/avro-codecs/build.gradle
data-prepper-plugins/buffer-common/build.gradle
data-prepper-plugins/cloudwatch-logs/build.gradle
data-prepper-plugins/dissect-processor/build.gradle
data-prepper-plugins/dynamodb-source-coordination-store/build.gradle
data-prepper-plugins/dynamodb-source/build.gradle
data-prepper-plugins/in-memory-source-coordination-store/build.gradle
data-prepper-plugins/kafka-connect-plugins/build.gradle
data-prepper-plugins/kafka-plugins/build.gradle
data-prepper-plugins/mapdb-processor-state/build.gradle
data-prepper-plugins/opensearch/build.gradle
data-prepper-plugins/s3-source/build.gradle
data-prepper-plugins/sqs-source/build.gradle
data-prepper-plugins/translate-processor/build.gradle

Gradle project maintenance: Jackson 2.15.3, use the Jackson version from the BOM consistently, use the JUnit and Mockito from the version catalog consistently.
N/A

Jackson 2.15.3; consistent Jackson, JUnit, Mockito usage

---

data-prepper-plugins/parse-json-processor/README.md
data-prepper-plugins/parse-json-processor/build.gradle
data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parse/AbstractParseProcessor.java
data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parse/CommonParseConfig.java
data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parse/ion/IonTimestampConverterModule.java
data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parse/ion/ParseIonProcessor.java
data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parse/ion/ParseIonProcessorConfig.java
data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parse/json/ParseJsonProcessor.java
data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parse/json/ParseJsonProcessorConfig.java
data-prepper-plugins/parse-json-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/parse/ion/IonTimestampConverterModuleTest.java
data-prepper-plugins/parse-json-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/parse/ion/ParseIonProcessorConfigTest.java
data-prepper-plugins/parse-json-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/parse/ion/ParseIonProcessorTest.java
data-prepper-plugins/parse-json-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/parse/json/ParseJsonProcessorConfigTest.java
data-prepper-plugins/parse-json-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/parse/json/ParseJsonProcessorTest.java

Add parse_ion processor.
This collects most of the logic based on the common config options into an abstract class AbstractParseProcessor.
Since Ion is a superset of JSON, I inherited the JSON test suite for the Ion processor, and added an additional test to ensure that the Ion specific features work correctly.
Note: Since eventually the parsed objects need to be converted to JSON, Ion Timestamps are parsed into ISO-8601 Z strings. Ion Blobs are parsed into base64 encoded strings as per default Jackson behavior. Annotations are currently stripped entirely; in the future we could possibly add config options to support exposing them as extra fields (e.g. `{foo: bar::"baz"}` => `{"foo": "baz", "foo$annotations": ["bar"]}`).
Documentation Issue: …

Add parse_ion processor

---

release/release-notes/data-prepper.release-notes-2.6.1.md

Adds release notes for Data Prepper 2.6.1.
See the following milestone for the list of changes.
https://github.com/opensearch-project/data-prepper/milestone/25?closed=1
N/A

Release notes for Data Prepper 2.6.1.

---

data-prepper-plugins/common/src/test/java/org/opensearch/dataprepper/plugins/hasher/IdentificationKeysHasherTest.java

The common library for plugins is frequently failing with coverage ratio.
```
Execution failed for task ':data-prepper-plugins:common:jacocoTestCoverageVerification'.
> Rule violated for bundle common: instructions covered ratio is 0.89, but expected minimum is 0.90
```
This PR adds some additional coverage to this library to avoid this error.
N/A

Increase test coverage in the plugin common library

---

data-prepper-plugins/kafka-plugins/build.gradle

Require Mozilla Rhino 1.7.12 in the Kafka plugins library.
https://security.snyk.io/vuln/SNYK-JAVA-ORGMOZILLA-1314295

Require Mozilla Rhino 1.7.12 to fix SNYK-JAVA-ORGMOZILLA-1314295.

---

data-prepper-plugins/failures-common/src/main/java/org/opensearch/dataprepper/plugins/dlq/s3/S3DlqWriterConfig.java
data-prepper-plugins/failures-common/src/test/java/org/opensearch/dataprepper/plugins/dlq/s3/S3DlqWriterConfigTest.java

Adds support for passing a map of `sts_header_overrides` to the s3 dlq, and applies it to the `AssumeRoleRequest` to assume the `sts_role_arn`

Add sts_header_overrides to s3 dlq configuration

---

.github/workflows/opensearch-sink-opensearch-integration-tests.yml
settings.gradle

Updates the opensearch library version to 1.3.14.
Run integration test against 2.11.1 and 1.3.14.
https://github.com/advisories/GHSA-6g3j-p5g6-992f
Resolves #3837.

Updates opensearch library to 1.3.14. 

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/codec/InputCodec.java
data-prepper-plugins/date-processor/README.md
data-prepper-plugins/date-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/date/DateProcessor.java
data-prepper-plugins/date-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/date/DateProcessorConfig.java
data-prepper-plugins/date-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/date/DateProcessorConfigTest.java
data-prepper-plugins/date-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/date/DateProcessorTests.java

Supports input timestamp to be of `epoch_second`, `epoch_milli` or `epoch_nano`.
Also added support to configure output timestamp format. It can be also epoch timestamp or any of the formats allowed by DateTimeFormatter.
Resolves #2929 
Resolves #2929 
- [X ] New functionality has a documentation issue. Please link to it in this PR.

Add support for epoch timestamps and configurable output format

---

data-prepper-plugins/date-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/date/DateProcessorTests.java

I ran the `DateProcessorTests` and they began to fail. There appears to be a disconnect between the timezone used in the tested code and the expected timezone in the expected string.
While I was working it, I also removed an unnecessary condition in the tests. It is generally better to avoid conditions in tests, especially in the assertions.
N/A

Date processor test corrections for other timezones

---

data-prepper-plugins/otel-logs-source/build.gradle
data-prepper-plugins/otel-metrics-source/build.gradle
data-prepper-plugins/otel-trace-source/build.gradle
settings.gradle

Updates Armeria to 1.26.4.
This version of Armeria moves to `io.grpc` 1.58.0. This version split some class from the core library into a new library `grpc-inprocess`. Armeria does not depend on this, but Data Prepper uses some classes from this new library. So this PR also adds that dependency via the version catalog.
One goal is to remove possible memory leaks in Armeria per #3912.
Unsure; maybe helps toward #3912

Updates Armeria to 1.26.4

---

data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/export/ExportTaskManager.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/leader/ShardManager.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/ShardConsumer.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/ShardConsumerFactory.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/utils/DynamoDBSourceAggregateMetrics.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/leader/ShardManagerTest.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/ShardConsumerFactoryTest.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/ShardConsumerTest.java

This change adds 3 new metrics to the DynamoDB source
* `stream4xxErrors` - aggregate metric for stream 4xx errors
* `export4xxErrors` - aggregate metric for export 4xx errors
* `shardProgress` - Tracks that the pipeline is still processing shards correctly 

Add 4xx aggregate metric and shard progress metric for dynamodb source

---

data-prepper-plugins/kafka-plugins/src/integrationTest/java/org/opensearch/dataprepper/plugins/kafka/buffer/KafkaBufferIT.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/buffer/BufferTopicConfig.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/configuration/KafkaProducerProperties.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/configuration/TopicProducerConfig.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/producer/KafkaCustomProducerFactory.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/service/TopicService.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/sink/KafkaSink.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/sink/SinkTopicConfig.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/buffer/BufferTopicConfigTest.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/configuration/KafkaProducerPropertiesTest.java

Support larger message sizes in Kafka Buffer.
Supports setting max message size both in Kafka Buffer producer properties (for client side support) and setting max message size when topic is created by the buffer (for server side support). When server side support for a topic is enabled, it automatically enables client side support too. Kafka buffer config with new config options looks like this -
```
buffer:                                                                                                                                              
kafka:                                                                                                                                             
bootstrap_servers: ["localhost:9092"]   
producer_properties:
max_request_size:  4194304 …
```

Support larger message sizes in Kafka Buffer

---

data-prepper-plugins/key-value-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/keyvalue/KeyValueProcessor.java
data-prepper-plugins/key-value-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/keyvalue/KeyValueProcessorTests.java

Fix Null Pointer Exception in KeyValue Processor which is occurring when the input event does not have the "source" field
Resolves #3928 
Resolves #3928

Fix Null Pointer Exception in KeyValue Processor

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/buffer/AbstractBuffer.java
data-prepper-plugins/blocking-buffer/src/main/java/org/opensearch/dataprepper/plugins/buffer/blockingbuffer/BlockingBuffer.java
data-prepper-plugins/blocking-buffer/src/test/java/org/opensearch/dataprepper/plugins/buffer/blockingbuffer/BlockingBufferTests.java

This PR has two changes for the `bounded_blocking` buffer:
1. Adds a new `capacityUsed` metric which tracks the capacity used within the buffer as determined by the semaphore which controls admission to the buffer.
2. Corrects the `bufferUsage` metric to track the percentage of the capacity used against the total capacity. This is done by tracking the semaphore. But, it is also logically equivalent to tracking the sum of `recordsInBuffer` and `recordsInFlight`. Previously, this metric only tracked `recordsInBuffer`.
I configured a tight buffer to fill it quickly and test the changes.
```
buffer:
bounded_blocking:
buffer_size: 1000
batch_size: 20
```
The following CloudWatch graphs show the metrics in action. 
This graph shows the metrics and how the values correspond to each other …

Corrects BlockingBuffer's bufferUsage metric and adds capacityUsed metric

---

data-prepper-plugins/common/src/main/java/org/opensearch/dataprepper/plugins/processor/DelayProcessor.java
data-prepper-plugins/common/src/test/java/org/opensearch/dataprepper/plugins/processor/DelayProcessorTest.java

I have wanted to delay the processor for testing and debugging before. So I added a new `delay` processor to perform this delay.
Resolves #3938

Adds delay processor for adding delays in the processor chain

---

data-prepper-plugins/mutate-event-processors/README.md
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/MapToListProcessor.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/MapToListProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/test/java/org/opensearch/dataprepper/plugins/processor/mutateevent/MapToListProcessorTest.java

This PR adds a new `map_to_list` processor. 
The config options are:
`source`(required): the source map to perform the operation
`target`(required): the target list
`key_name`: the key name of the field to hold the original key, default is "key"
`value_name`: the key name of the field to hold the original value, default is "value"
`exclude_keys`: the keys in source map that will be excluded from processing, default is empty list
`remove_processed_fields`: default is false; if true, will remove processed fields from source map
`map_to_list_when`: used to configure a condition for event processing based on certain property of the incoming event. Default is null (all events will be processed).
Resolves #3935
By submitting this pull request, I confirm that my contribution is made under the …

Add map_to_list processor

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/types/ByteCount.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/types/ByteCountTest.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/plugin/ObjectMapperConfiguration.java
data-prepper-plugins/armeria-common/src/main/java/org/opensearch/dataprepper/HttpRequestExceptionHandler.java
data-prepper-plugins/armeria-common/src/test/java/org/opensearch/dataprepper/HttpRequestExceptionHandlerTest.java
data-prepper-plugins/http-source/src/main/java/org/opensearch/dataprepper/plugins/source/loghttp/HTTPSource.java
data-prepper-plugins/http-source/src/main/java/org/opensearch/dataprepper/plugins/source/loghttp/HTTPSourceConfig.java
data-prepper-plugins/http-source/src/test/java/org/opensearch/dataprepper/plugins/source/loghttp/HTTPSourceTest.java
data-prepper-plugins/otel-logs-source/src/main/java/org/opensearch/dataprepper/plugins/source/otellogs/OTelLogsSource.java
data-prepper-plugins/otel-logs-source/src/main/java/org/opensearch/dataprepper/plugins/source/otellogs/OTelLogsSourceConfig.java
data-prepper-plugins/otel-logs-source/src/test/java/org/opensearch/dataprepper/plugins/source/otellogs/OTelLogsSourceTest.java
data-prepper-plugins/otel-metrics-source/src/main/java/org/opensearch/dataprepper/plugins/source/otelmetrics/OTelMetricsSource.java
data-prepper-plugins/otel-metrics-source/src/main/java/org/opensearch/dataprepper/plugins/source/otelmetrics/OTelMetricsSourceConfig.java
data-prepper-plugins/otel-metrics-source/src/test/java/org/opensearch/dataprepper/plugins/source/otelmetrics/OTelMetricsSourceTest.java
data-prepper-plugins/otel-trace-source/src/main/java/org/opensearch/dataprepper/plugins/source/oteltrace/OTelTraceSource.java
data-prepper-plugins/otel-trace-source/src/main/java/org/opensearch/dataprepper/plugins/source/oteltrace/OTelTraceSourceConfig.java
data-prepper-plugins/otel-trace-source/src/test/java/org/opensearch/dataprepper/plugins/source/oteltrace/OTelTraceSourceTest.java

Adds a new configuration `max_request_length` to the HTTP/gRPC sources (OTel). If the size of a request exceeds that size these sources will return a `413 Request Entity Too Large`.
This also adds support for parsing `ByteCount` to the plugin object mapper.
There is also a new method on `ByteCount` to create an instance of a given size to help with testing.
Resolves #3931

Adds max_request_length as a configuration for the http and OTel sources

---

data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/integration/PipelinesWithAcksIT.java
data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/acknowledgements/three-pipeline-route-default-test.yaml
data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/acknowledgements/three-pipeline-route-test.yaml
data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/acknowledgements/three-pipeline-unrouted-test.yaml
data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/router/Router.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/router/RouterFactory.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/router/RouterFactoryTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/router/RouterTest.java

Release events that are not routed to any sinks.
When an event is not routed any sink, acknowledgement is sent so that the events are dropped.
Resolves #3866 
Resolves #3866 

Release events that are not routed to any sinks

---

data-prepper-plugins/s3-source/build.gradle

* Updates wiremock to 3.3.1
* Fixes CVE-2023-41329
* Change the Maven groupId to `org.wiremock` which is the new groupId as of 3.0.0. See the [release notes for the 3.0.0](https://github.com/wiremock/wiremock/releases/tag/3.0.0) release.
Resolves #3954

Updates wiremock to 3.3.1 to fix CVE-2023-41329

---

data-prepper-plugins/s3-source/build.gradle

Manual backport of https://github.com/opensearch-project/data-prepper/pull/3969
N/A

[Backport 2.6 - Manual] Updates wiremock to 3.3.1.

---

data-prepper-plugins/kafka-plugins/build.gradle
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/sink/KafkaSink.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/sink/KafkaSinkConfigTest.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/sink/KafkaSinkTest.java

Greatly reduce the time that the `KafkaSinkTest` takes by mocking the constructor. Update the unit tests to JUnit 5. Only the integration tests need JUnit 4 now, but these use quite a few JUnit 4 features.
The `KafkaSinkTest` was taking about 2 minutes 30 seconds because it was trying to connect to an actual Kafka bootstrap server. Now it takes under 3 seconds.
N/A

Reduce kafka-plugin test time; some JUnit 5 migrations

---

data-prepper-plugins/kafka-plugins/src/integrationTest/java/org/opensearch/dataprepper/plugins/kafka/buffer/KafkaBufferIT.java
data-prepper-plugins/kafka-plugins/src/integrationTest/java/org/opensearch/dataprepper/plugins/kafka/util/TestProducer.java

Adds a new integration test for the Kafka buffer which verifies that data written is correctly read and decrypted. This work will be used to verify upcoming changes to the Protobuf model.
None, but this is preparing to help ensure that changes for #3655 are backward compatible.

Kafka buffer integration test to verify that data in the buffer is correctly read

---

performance-test/README.md
performance-test/build.gradle
performance-test/src/gatling/java/org/opensearch/dataprepper/test/performance/tools/AwsRequestSigner.java
performance-test/src/gatling/java/org/opensearch/dataprepper/test/performance/tools/SignerProvider.java

Updates the Gatling version in the performance-test to 3.10.3. The 3.10 release includes a breaking change that required updating a Consumer to a Function. Added some additional instructions for running the performance tests against Amazon OpenSearch Ingestion.
Upgrade guide: https://gatling.io/docs/gatling/reference/current/upgrading/3.9-to-3.10/#http-signaturecalculator-change
N/A

Updates the Gatling version in the performance-test to 3.10.3.

---

data-prepper-plugins/aws-plugin/build.gradle
data-prepper-plugins/aws-plugin/src/main/java/org/opensearch/dataprepper/plugins/aws/AwsSecretPlugin.java
data-prepper-plugins/aws-plugin/src/main/java/org/opensearch/dataprepper/plugins/aws/SecretsRefreshJob.java
data-prepper-plugins/aws-plugin/src/test/java/org/opensearch/dataprepper/plugins/aws/SecretsRefreshJobTest.java

This PR adds metrics on AWS secrets extension plugin

ENH: metrics in secret extension

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/JacksonEvent.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/event/JacksonEvent_JavaSerializationTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/codec/JavaPeerForwarderCodecTest.java

This PR marks the `eventHandle` field in `JacksonEvent` as `transient`. Re-create it by adding a `readObject()` method.
I added two different tests. Each one failed before making the change.
Resolves #3981

Mark the EventHandle as transient to fix serialization

---

data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/buffer/KafkaBuffer.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/producer/KafkaCustomProducer.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/producer/KafkaCustomProducerFactory.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/producer/ProducerWorker.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/sink/DLQSink.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/sink/KafkaSink.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/buffer/KafkaBufferTest.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/producer/KafkaCustomProducerTest.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/sink/KafkaSinkTest.java

Kafka error handling in KafkaBuffer.
Errors occurred while storing in kafka are mapped to Source specific (HTTP source) errors and sent back.
Removed capability to configure DLQ  when Kafka used as Buffer

Kafka error handling in KafkaBuffer

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/types/ByteCount.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/types/ByteCountTest.java

Improves the `ByteCount` class by implementing `equals()`, `hashCode()`, and `toString()`.
N/A

ByteCount equals(), hashCode(), toString()

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/types/ByteCount.java

Use the single source of truth for the byte unit in `ByteCount`.
Responding to a PR comment:
https://github.com/opensearch-project/data-prepper/pull/3960/files#r1459600545
N/A

Use the official unit string for the 'b' in ByteCount::toString()

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/server/ShutdownHandler.java

Right now, it can be unclear why Data Prepper is shutting down. This adds a log when the `POST /shutdown` API begins shutting down Data Prepper.
Related to: #3986

Log when Data Prepper is shutdown via the HTTP shutdown endpoint.

---

data-prepper-plugins/common/build.gradle
data-prepper-plugins/common/src/test/java/org/opensearch/dataprepper/plugins/certificate/acm/ACMCertificateProviderTest.java
data-prepper-plugins/common/src/test/java/org/opensearch/dataprepper/plugins/processor/state/ProcessorStateTest.java
data-prepper-plugins/common/src/test/java/org/opensearch/dataprepper/plugins/s3keyindex/S3ObjectIndexUtilityTest.java
data-prepper-plugins/common/src/test/java/org/opensearch/dataprepper/plugins/source/StdInSourceTests.java
data-prepper-plugins/mapdb-processor-state/build.gradle
data-prepper-plugins/mapdb-processor-state/src/test/java/org/opensearch/dataprepper/plugins/processor/state/MapDbProcessorStateTest.java

As part of a longer-term goal of removing JUnit 4, this updates two of our projects to JUnit 5:
* `data-prepper-plugins/common`
* `data-prepper-plugins/mapdb-processor-state`
N/A

Updates the common plugin and mapdb-processor-state projects to JUnit 5.

---

data-prepper-plugins/otel-proto-common/src/main/java/org/opensearch/dataprepper/plugins/otel/codec/OTelProtoCodec.java
data-prepper-plugins/otel-proto-common/src/test/java/org/opensearch/dataprepper/plugins/otel/codec/OTelProtoCodecTest.java
data-prepper-plugins/otel-proto-common/src/test/resources/test-histogram-metrics-no-explicit-bounds.json

OTEL histograms may contain  bucket counts list with just one entry with no explicit bounds specified. This can cause the current code to not handle it correctly. When the explicit bounds array is empty, -infinity and +infinity should be used as bounds.

Otel metrics fix

---

data-prepper-plugins/geoip-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/databasedownload/LocalDBDownloadServiceTest.java

The `main` build is failing because we have an un-handled checked exception. This adds this method to one of the tests' method signatures.
N/A

Fixes a build failure related to geoip.

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/plugin/ObjectMapperConfiguration.java

Support ByteCount in plugin parser.
No tests were required because jacoco shows that this is covered.
Resolves https://github.com/opensearch-project/data-prepper/issues/3191

Added ByteCount to plugin parser

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/peerforwarder/RequiresPeerForwarding.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/peerforwarder/RequiresPeerForwardingTest.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/PeerForwardingProcessorDecorator.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/ProcessWorker.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/PeerForwardingProcessingDecoratorTest.java
data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateProcessor.java
data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateProcessorTest.java

Aggregate processor support `aggregate_when` option which may evaluate to false to some events. But the current remote forwarder interface evaluates this condition after an event is forwarded to a remote peer which is unnecessary. The condition can be evaluated locally on a forwarding node before actually forwarding the event.
Modified the remote forwarding interface to allow local evaluation of events before forwarding events to remote peer.
For more information on following Developer Certificate of Origin and signing …

Aggregator processor should evaluate aggregate_when condition before forwarding events to remote peer

---

data-prepper-plugins/grok-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/grok/GrokProcessor.java
data-prepper-plugins/grok-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/grok/GrokProcessorTests.java

Cancel the existing grok task when a timeout occurs by catching a TimeoutException.
Resolves #4026

Cancel the existing grok task when a timeout occurs

---

build.gradle
performance-test/build.gradle

Updates jline to 3.25.0 to resolve CVE-2023-50572.
Resolves #3871

Updates jline to 3.25.0 to resolve CVE-2023-50572.

---

.github/workflows/kafka-plugin-integration-tests.yml
data-prepper-plugins/kafka-plugins/README.md
data-prepper-plugins/kafka-plugins/build.gradle
data-prepper-plugins/kafka-plugins/src/integrationTest/java/org/opensearch/dataprepper/plugins/kafka/buffer/KafkaBuffer_KmsIT.java
testing/aws-testing-cdk/bin/aws-testing-cdk.ts
testing/aws-testing-cdk/lib/common/GitHubAccessStack.ts
testing/aws-testing-cdk/lib/common/KmsStack.ts

The goal of this PR is to add integration tests to verify the `kafka` buffer uses the KMS key correctly.
There are a few changes:
* This adds a new CDK stack for a common KMS key.
* Improves the existing `GitHubAccessStack` by granting the current account access to assume the GitHub role.
* Improves the existing `GitHubAccessStack` by allowing to skip the GitHub OIDC provider for users that already have it defined. For example, it may be defined by the release staging stack.
* Adds a new integration test for KMS.
Resolves #3980 …

Integration tests for using the Kafka buffer with KMS encryption

---

data-prepper-plugins/grok-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/grok/GrokProcessor.java
data-prepper-plugins/grok-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/grok/GrokProcessorConfig.java
data-prepper-plugins/grok-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/grok/GrokProcessorConfigTests.java
data-prepper-plugins/grok-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/grok/GrokProcessorTests.java

This PR tags events for all exceptions in the grok processor. This includes timeout exceptions and other runtime exceptions that the processor catches as it will still send those events further through the pipeline.
I also consolidated the exception handling. The error messages for exceptions other than timeouts do not seem to need different wording as they all will include the actual exception. Also, an "unknown exception" might seem confusing to a user, especially since it is handled the same as the "known" exceptions.
Resolves #4031 …

Tag events that fail for all exceptions in the grok processor. Resolves #4031

---

data-prepper-plugins/kafka-plugins/build.gradle

Updates Apache Kafka client library to 3.6.1.
Updates the MSK IAM authentication library to 2.0.3.
Removes the AWS SDK v1 Glue package
N/A

Updates the Kafka client libraries to the latest

---

data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/ClientRefresher.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/OpenSearchSource.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/metrics/OpenSearchSourcePluginMetrics.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/SearchAccessorStrategy.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/ClientRefresherTest.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/OpenSearchSourceTest.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/SearchAccessStrategyTest.java

This PR 
* handles runtime exception in creating new client (connection) in ClientRefresher
* adds metrics to track auth change as well as client refreshment failure

ENH: error handling in opensearch client refreshment and metrics

---

data-prepper-expression/src/main/java/org/opensearch/dataprepper/expression/JoinExpressionFunction.java
data-prepper-expression/src/main/java/org/opensearch/dataprepper/expression/ParseTreeCoercionService.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/GenericExpressionEvaluator_MultiTypeIT.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/JoinExpressionFunctionTest.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/ParseTreeCoercionServiceTest.java

Adds a join function that takes a source key to a list or a map where values are all of list type, and joins list to string with the given delimiter (optional). 
It can be used in processors that support value_expression such as `add_entries`:
```yaml
processor:
- add_entries:
entries:
- key: result
value_expression: join(/source)
```
With input `{"source": [1, 2, 3]}`, it will get you `{"result": "1,2,3"}`
With input 
```json
{"source": {"key1": [1, 2, 3], "key2": ["a", "b", "c"]}}
```
, it will get you 
```json
{"result": {"key1": "1,2,3", "key2": "a,b,c"}}
```
Contributes to #3965 …

Add join function

---

data-prepper-plugins/mutate-event-processors/README.md
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/ListToMapProcessor.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/ListToMapProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/test/java/org/opensearch/dataprepper/plugins/processor/mutateevent/ListToMapProcessorTest.java

Adds some enhancements to to list_to_map processor:
- adds `use_source_key` and `extract_value` option to dynamically extract values and put them in a list under the source key
- adds `tags_on_failure` option to add tags when events failed to process
- simplifies existing code that uses JsonNode unnecessarily (see this [comment](https://github.com/opensearch-project/data-prepper/pull/2453#discussion_r1160015928) on original PR)
Resolves #3867 

Enhancements to list_to_map processor

---

data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/configuration/S3ScanSchedulingOptions.java

This change lowers the minimum interval value to wait between scheduled scans from 30 seconds to 1 second. This means that when there are a small number of objects to scan, the scans will happen more quickly if the objects are completed before the interval is reached. There is no great reason to require 30 seconds in between scans.

Lower min duration validation for scheduled s3 scan interval from 30 seconds to 1 second

---

data-prepper-plugins/kafka-plugins/src/integrationTest/java/org/opensearch/dataprepper/plugins/kafka/buffer/KafkaBufferIT.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/buffer/serialization/BufferMessageSerializer.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/buffer/serialization/BufferSerializationFactory.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/common/KafkaDataConfig.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/common/KafkaDataConfigAdapter.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/common/PlaintextKafkaDataConfig.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/common/key/InnerKeyProvider.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/common/key/KeyFactory.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/common/key/KmsKeyProvider.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/common/key/UnencryptedKeyProvider.java
data-prepper-plugins/kafka-plugins/src/main/proto/org/opensearch/dataprepper/plugins/kafka/KafkaBufferMessage.proto
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/buffer/serialization/BufferMessageSerializerTest.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/common/KafkaDataConfigAdapterTest.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/common/PlaintextKafkaDataConfigTest.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/common/key/KeyFactoryTest.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/common/key/KmsKeyProviderTest.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/common/key/UnencryptedKeyProviderTest.java

When writing Kafka buffer events, save additional information about the encryption in the protobuf record.
This adds two new fields to the Protobuf message:
* `encrypted`
* `encrypted_data_key`
This work does not include using that data when reading. I plan to do that in a follow-on PR, but want to keep the PRs from getting too large.
Contributes toward #3655.

Write encryption data to the Kafka protobuf messages

---

data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/CopyValueProcessor.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/CopyValueProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/test/java/org/opensearch/dataprepper/plugins/processor/mutateevent/CopyValueProcessorTests.java

The configurations are like this:
```yaml
processor:
- copy_values:
from_list: mylist
to_list: newlist
entries:
- from_key: name
to_key: fruit_name
```
Example input:
```json
{
"mylist": [
{"name": "apple", "color": "red"},
{"name": "orange", "color": "orange"}
]
}
```
Example output:
```json
{
"newlist": [
{"fruit_name": "apple"},
{"fruit_name": "orange"}
]
}
```
Resolves #3962

Enhance copy_values processor to selectively copy entries from lists

---

data-prepper-plugins/common/src/main/java/org/opensearch/dataprepper/plugins/source/file/FileSource.java
data-prepper-plugins/common/src/main/java/org/opensearch/dataprepper/plugins/source/file/FileSourceConfig.java
data-prepper-plugins/common/src/test/java/org/opensearch/dataprepper/plugins/source/file/FileSourceConfigTest.java
data-prepper-plugins/common/src/test/java/org/opensearch/dataprepper/plugins/source/file/FileSourceTests.java

Support input codecs in the `file` source.
Resolves #4018.

Support input codecs in the file source. 

---

.github/workflows/kafka-plugin-integration-tests.yml

Runs the Kafka buffer KMS tests using the DataPrepperTesting KMS key.
Resolves #4040

Runs the Kafka buffer KMS tests as part of the GitHub Actions

---

data-prepper-plugins/date-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/date/DateProcessor.java
data-prepper-plugins/date-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/date/DateProcessorTests.java

(cherry picked from commit 0841ac17ae18a76610842be3c0ff3b0b0dc1e453)
Backport for #4108 

Catch exception instead of shutting down in date processor (#4108)

---

data-prepper-plugins/kafka-plugins/src/integrationTest/java/org/opensearch/dataprepper/plugins/kafka/buffer/KafkaBufferIT.java
data-prepper-plugins/kafka-plugins/src/integrationTest/java/org/opensearch/dataprepper/plugins/kafka/buffer/KafkaBufferOTelIT.java
data-prepper-plugins/kafka-plugins/src/integrationTest/java/org/opensearch/dataprepper/plugins/kafka/buffer/KafkaBuffer_KmsIT.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/buffer/KafkaBuffer.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/producer/KafkaCustomProducerFactory.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/service/TopicService.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/service/TopicServiceFactory.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/sink/KafkaSink.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/buffer/KafkaBufferTest.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/producer/KafkaCustomProducerFactoryTest.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/sink/KafkaSinkTest.java

The core of this PR is to fix an inverted boolean check for the `create_topic` configuration.
Additionally, I wanted to add unit tests. To do this well, I did some refactoring to add a `TopicServiceFactory` and then hide the constructor for `TopicService`.
Resolves #4111

Fixes a bug where the Kafka buffer inverted the relationship for the create_topic configuration

---

.github/workflows/kafka-plugin-integration-tests.yml

Fix 1:
Replaces missing tests in the Kafka integration tests: 
* `KafkaSourceJsonTypeIT`
* `KafkaBufferOTelIT`
These were incorrectly removed in #4041
Fix 2:
The tests now run using `pull_request_target`. This will cause GitHub to run against the target repository and thus access the necessary secrets.
N/A

Corrections to Kafka integration tests in GitHub

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/JacksonEvent.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/event/JacksonEventTest.java
data-prepper-plugins/mutate-event-processors/README.md
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/MapToListProcessor.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/MapToListProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/test/java/org/opensearch/dataprepper/plugins/processor/mutateevent/MapToListProcessorTest.java

Adds some enhancements to to map_to_list processor:
- adds a `convert_field_to_list` option. If true, will convert fields to lists (`[key, value]`) instead of objects (`{key: value}`)
- allows source to be root when `source` is not specified
- adds `tags_on_failure` option to add tags when events failed to process
Contributes to #3965 

Enhancements to map_to_list processor

---

build.gradle

Require json-path 2.9.0 to fix CVE-2023-51074. 
Resolves #3919

Require json-path 2.9.0 to fix CVE-2023-51074. Resolves #3919

---

data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/buffer/KafkaBuffer.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/common/KafkaMdc.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/common/thread/KafkaPluginThreadFactory.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/buffer/KafkaBufferTest.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/common/thread/KafkaPluginThreadFactoryTest.java

This adds logging MDC to the `kafka` buffer to disambiguate it against the `kafka` sink. Entry points into the `Buffer` interface set the MDC value. Also, the threads which the `kafka` buffer directly creates will have MDC and also have a useful thread name.
This MDC is now available for both Data Prepper loggers and Apache Kafka loggers.
One limitation is that the MDC is not available for the `KafkaProducer`. This is because the internal Apache Kafka libraries create that thread and appear to have no way to influence it.
First part of #4126
I plan to follow up with more changes for the `kafka` sink in a subsequent PR.
I changed the Log4j configuration to include the `kafkaPluginType` MDC value.
```
appender.console.layout.pattern = %d{ISO8601} [%t] [%X{kafkaPluginType}] %-5p %40C - %m%n …
```

Support for logging MDC in the Kafka buffer

---

release/build-resources.gradle

Updates the JDK in the released artifacts to jdk-17.0.10+7.
https://github.com/adoptium/temurin17-binaries/releases/tag/jdk-17.0.10%2B7
N/A

JDK 17 release update

---

data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaCustomConsumer.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaCustomConsumerTest.java

KafkaConsumer should continue to poll while waiting for buffer.
KafkaConsumer waits for buffer to become available in a busy loop if it fails to get a buffer. The consumer thread may be in this busy loop for long time and this can result in kafka server not getting any heartbeats from the consumer.
To avoid this, the consumer must keep calling `poll()` while waiting for the buffer to be available. But since `poll()` fetches new records from the server, consumer should do `pause()` before doing `poll()` until buffer becomes available and do `resume()` once its get the buffer and resumes normal processing. 
By submitting this pull request, I confirm that my contribution is …

KafkaConsumer should continue to poll while waiting for buffer

---

data-prepper-plugins/cloudwatch-logs/build.gradle
data-prepper-plugins/dynamodb-source/build.gradle
data-prepper-plugins/mapdb-processor-state/build.gradle
data-prepper-plugins/newline-codecs/build.gradle
data-prepper-plugins/parse-json-processor/build.gradle
data-prepper-plugins/rss-source/build.gradle
data-prepper-plugins/s3-source/build.gradle
data-prepper-plugins/service-map-stateful/build.gradle
data-prepper-test-common/build.gradle
performance-test/build.gradle

The root Gradle project declares the `mavenCentral()` repository. These `repositories` declarations are all unnecessary, so this PR removes them.
N/A

Removes unnecessary mavenCentral() declarations in Gradle sub-projects.

---

data-prepper-expression/src/main/java/org/opensearch/dataprepper/expression/JoinExpressionFunction.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/JoinExpressionFunctionTest.java

`join` function supports joining either a list or a map containing lists. Currently it will log an error message ("ERROR org.opensearch.dataprepper.model.event.JacksonEvent - Unable to map /source to interface java.util.List") with a long trackback when the source field is a map, which is expected but can confuse users to think it's not working properly.
This PR replaces the try-catch with a conditional to avoid the confusing error message.
N/A

Replace a try-catch with conditional in join function

---

data-prepper-expression/build.gradle
data-prepper-expression/src/main/antlr/DataPrepperExpression.g4
data-prepper-expression/src/main/java/org/opensearch/dataprepper/expression/LiteralTypeConversionsConfiguration.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/GenericExpressionEvaluator_ConditionalIT.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/ParseTreeCoercionServiceTest.java

Fixes a bug where the Data Prepper expression language would throw exceptions if the value of a json pointer was a List or Map, for instance if the expression is `/my_field == null' and my_field is a List, an exception is thrown instead of evaluating whether my_field is null 
Resolves #4109 

Make expressions evaluating on keys with List or Map values not throw an exception

---

data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/producer/KafkaCustomProducerFactory.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/util/KafkaProducerMetrics.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/util/KafkaProducerMetricsTest.java

This PR adds three new metrics for the `kafka` buffer:
* recordQueueTimeAvg
* recordQueueTimeMax
* bufferExhaustedRate
* bufferAvailableBytes
These are not topic-related, so I connected it to the `KafkaProducer` itself.
N/A

Adds Kafka producer metrics for buffer usage

---

gradle.properties

Updates the Data Prepper version to 2.6.3 if we have another release here.
N/A

Bumps Data Prepper to 2.6.3

---

data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/AddEntryProcessor.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/AddEntryProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/test/java/org/opensearch/dataprepper/plugins/processor/mutateevent/AddEntryProcessorTests.java

Adds an `append_if_key_exists` option to `add_entries` processor as described in #4129 
Resolves #4129 

Add append option to add_entries processor

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/ProcessWorker.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/ProcessWorkerTest.java

This change makes it so exceptions thrown from `Processors` in `ProcessWorker` to not shut down the thread.
Instead of shutting down, we will just pass the batch of Events that resulted in the exception to the next processor in the chain
Resolves #4103 

Catch processor exceptions instead of shutting down

---

data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaCustomConsumer.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/PauseConsumePredicate.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/consumer/PauseConsumePredicateTest.java

The `kafka` buffer was pausing 10 seconds to wait for the circuit breaker to close. However, it would then consume after that. This change will keep holding until the circuit breaker closes again. This is similar to how inputs into buffers work.
N/A

Delay reading from the Kafka buffer as long as the circuit breaker is open

---

data-prepper-plugins/csv-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/csv/CsvProcessor.java
data-prepper-plugins/dissect-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/dissect/DissectProcessor.java
data-prepper-plugins/key-value-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/keyvalue/KeyValueProcessor.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/AddEntryProcessor.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/ConvertEntryTypeProcessor.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/CopyValueProcessor.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/DeleteEntryProcessor.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/ListToMapProcessor.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/MapToListProcessor.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/RenameKeyProcessor.java
data-prepper-plugins/mutate-string-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutatestring/AbstractStringProcessor.java
data-prepper-plugins/obfuscate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/obfuscation/ObfuscationProcessor.java
data-prepper-plugins/truncate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/truncate/TruncateProcessor.java

This change makes it so any processors (other than stateful processors) will catch runtime exceptions for individual Events, and then log the error and tag the Event, before continuing on to the next Event.
This included the following processors
* csv
* dissect
* key_value
* convert_entry_type
* mutate events processors
* mutate string processors
* map_to_list
* obfuscate
* truncate
Related to #4103

Catch exceptions instead of throwing for processors that can handle Events event by event

---

build.gradle
settings.gradle

This PR moves the Maven repository declarations to the `settings.gradle` file. This consolidates all usage there.
Additionally, this PR adds a limit the groups used by the JitPack Maven repository. This repository is only needed for the `com.github.fge:json-schema-validator` dependency in the Kafka plugins. Now, Data Prepper will not pull anything other than that Maven group from JitPack.
N/A

Moves the repository declarations to the settings.gradle file

---

data-prepper-plugins/kafka-plugins/build.gradle
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaCustomConsumerFactory.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/source/KafkaSource.java

1. Integration test dependencies were being pulled in when compiling source code and unit tests.
2. The wrong namespace for json-schema-validator was being used.

Fix kafka plugin dependencies.

---

data-prepper-plugins/opensearch/src/integrationTest/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSinkIT.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSink.java

Upsert operation code incorrectly uses "==" to compare two string. It should use equals()
Resolves #4036 #3934 
Resolves #4036  #3934

Fix OpenSearchSink upsert operation

---

data-prepper-plugins/csv-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/csv/CsvProcessor.java
data-prepper-plugins/csv-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/csv/CsvProcessorConfig.java
data-prepper-plugins/csv-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/csv/CsvProcessorIT.java
data-prepper-plugins/csv-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/csv/CsvProcessorTest.java

Adds the `csv_when` parameter to the csv processor

Add csv_when parameter to the csv processor

---

data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/AddEntryProcessor.java
data-prepper-plugins/mutate-event-processors/src/test/java/org/opensearch/dataprepper/plugins/processor/mutateevent/AddEntryProcessorTests.java

Allow format expression in keys in add_entries processor
Resolves #4175

Allow format expression in keys in add_entries processor

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/AbstractContextManager.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/DataPrepper.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/DataPrepperShutdownListener.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/AbstractContextManagerTest.java

* Modify data prepper core to accept a List of shutdownListeners that will all be run after shutdown.
Following from https://github.com/opensearch-project/data-prepper/pull/4185

Modify shutdown listeners to support a List of listeners

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/metric/JacksonMetric.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/metric/JacksonExponentialHistogramTest.java
data-prepper-plugins/otel-metrics-raw-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/otelmetrics/OTelMetricsRawProcessor.java

Set default value of flattenAttributes to true in Otel metrics source.
Modify the OTEL metrics source to create events/records with flatten attributes set to true.
If OTEL processor config changes the flatten attributes to flase, then change it false in the processor.
OTEL metrics always have been implemented with flattening the attributes(ie fields inside "attributes" field are moved to the root). We have added option to not flatten some time back. But that's not used by anyone (that I know of). When the previous PR which moved the creation of OTEL metrics records to OTEL source (instead of otel processor) I picked the default to false and it is changed to true in the processor. But that was unnecessary also hit a bug due to valid characters in a key. This new approach will avoid it. …

Set default value of flattenAttributes to true in Otel metrics source

---

build.gradle
data-prepper-plugins/avro-codecs/src/test/java/org/opensearch/dataprepper/plugins/codec/avro/AvroOutputCodecTest.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/codec/parquet/ParquetOutputCodecTest.java

Updates Jackson to 2.16.1. Jackson 2.16 now redacts input data in exceptions. So a couple tests needed modifications. 
Additionally, this uses ion-java 1.10.5 which has a fix for  CVE-2024-21634.
Resolves #3926 

Jackson to 2.16.1

---

data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/util/KafkaSecurityConfigurer.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/util/KafkaSecurityConfigurerTest.java
data-prepper-plugins/kafka-plugins/src/test/resources/kafka-pipeline-sasl-ssl-no-cert-content-no-truststore.yaml

Fix to set kafka source truststore path and password only when they are not null value

Fix to set kafka source truststore path and password only when they are not null value

---

data-prepper-plugins/grok-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/grok/GrokProcessor.java
data-prepper-plugins/grok-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/grok/GrokProcessorConfig.java
data-prepper-plugins/grok-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/grok/GrokProcessorConfigTests.java
data-prepper-plugins/grok-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/grok/GrokProcessorTests.java

This change adds an `include_performance_metadata` flag to the grok processor, which defaults to true. When enabled, static metadata fields will be added to Events to track the total number of patterns this Event has attempted to match on.
Partially resolves #4196. Tracking the total time spent in grok is still needed.

Add include_performance_metadata parameter and track total grok patterns attempted in the grok processor

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/buffer/AbstractBuffer.java
data-prepper-plugins/kafka-plugins/src/integrationTest/java/org/opensearch/dataprepper/plugins/kafka/buffer/KafkaBufferIT.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/buffer/KafkaBuffer.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/buffer/KafkaBufferTest.java

Fix KafkaBuffer isEmpty.
KafkaBuffer isEmpty depends on innerBuffer recordsInFlight to be zero. But innerBuffer recordsInFlight is not zero because when `checkpoint` is done on KafkaBuffer, it is directly invoking `doCheckpoint` on the innerBuffer instead of invoking `checkpoint` which actually updates the metrics.

Fix KafkaBuffer isEmpty

---

data-prepper-plugins/grok-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/grok/GrokProcessor.java
data-prepper-plugins/grok-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/grok/GrokProcessorConfig.java
data-prepper-plugins/grok-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/grok/GrokProcessorTests.java

Renames `include_performance_metadata` to `performance_metadata`
* Add support for tracking the total_grok_processing_time for each Event as metadata on that Event
Completes #4197 

Add support for metadata in Events for the total time spent in grok

---

data-prepper-plugins/parse-json-processor/build.gradle
data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parse/AbstractParseProcessor.java
data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parse/xml/ParseXmlProcessor.java
data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parse/xml/ParseXmlProcessorConfig.java
data-prepper-plugins/parse-json-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/parse/xml/ParseXmlProcessorConfigTest.java
data-prepper-plugins/parse-json-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/parse/xml/ParseXmlProcessorTest.java

This creates a new processor, `parse_xml`, to go along with the `parse_json` and `parse_ion` processors. This change does not yet handle any encodings such as base64.
Resolves #4165 

Create parse xml processor

---

data-prepper-plugins/grok-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/grok/GrokProcessorConfig.java
data-prepper-plugins/grok-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/grok/GrokProcessorConfigTests.java

Changes the default value of `performance_metadata` to false

Change grok performance_metadata to be disabled by default

---

data-prepper-plugins/grok-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/grok/GrokProcessor.java
data-prepper-plugins/grok-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/grok/GrokProcessorTests.java

This was a miss from the previous PR (https://github.com/opensearch-project/data-prepper/commit/ebd2d470a84228170f2a4f6978e88419a8f653da) which did not consider the flag before writing the metadata for the total time spent in grok

Add check for if performance_metadata is enabled before adding metadata for grok processing time to Events

---

data-prepper-plugins/flatten-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/flatten/FlattenProcessor.java
data-prepper-plugins/flatten-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/flatten/FlattenProcessorConfig.java
data-prepper-plugins/flatten-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/flatten/FlattenProcessorConfigTest.java
data-prepper-plugins/flatten-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/flatten/FlattenProcessorTest.java

Add exclude_keys option to flatten processor, those keys will be excluded from the flattening operation.
N/A

Add exclude_keys option to flatten processor

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/sink/SinkLatencyMetrics.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/sink/SinkLatencyMetricsTest.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSinkTest.java

This PR enhances latency measurement with timer to replace distributionSummary

ENH: use timer for latency

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/metrics/MetricNames.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/buffer/AbstractBuffer.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/buffer/AbstractBufferTest.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/PeerForwarderReceiveBuffer.java
data-prepper-plugins/blocking-buffer/src/main/java/org/opensearch/dataprepper/plugins/buffer/blockingbuffer/BlockingBuffer.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/buffer/KafkaBuffer.java

Add Buffer Latency Metric

---

data-prepper-plugins/key-value-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/keyvalue/KeyValueProcessor.java
data-prepper-plugins/key-value-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/keyvalue/KeyValueProcessorConfig.java
data-prepper-plugins/key-value-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/keyvalue/KeyValueProcessorTests.java

This adds a `key_value_when` condition to the `key_value` processor

Add key_value_when conditional to key_value processor

---

data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSink.java

Fixes an issue that prevents users from using custom index type in vpc AOSS collection sink due to 401 errors.
Tests done:
- Existing OpenSearchSinkIT tests still pass
- Manually tested with a vpc collection with the following config to reproduce the issue and confirm the fix:
```yaml
log-pipeline:
source:
http:
path: "/log/ingest"
processor:
- date:
from_time_received: true
sink:
- stdout:
- opensearch:
hosts: [ "https://xxxx.us-east-1.aoss.amazonaws.com" ]
aws:
sts_role_arn: "arn:aws:iam::123456789012:role/OpenSearchServerlessPipelineRole"
serverless: true
serverless_options:
network_policy_name: auto-my-vpc-collection
collection_name: my-vpc-collection
vpce_id: vpce-01bd2921c3bcc0423
index: vpc-aoss-test-000001
index_type: custom
template_type: index-template …
```

Set up serverless network policy before setting up index

---

build-resources.gradle

Fixes the release task to build all jars since https://github.com/opensearch-project/data-prepper/pull/4247 broke the task by adding a new top level subproject but not registering in core projects

Fix release task after broken by #4247.

---

data-prepper-plugins/geoip-processor/src/integrationTest/java/org/opensearch/dataprepper/plugins/processor/GeoIPProcessorUrlServiceIT.java
data-prepper-plugins/geoip-processor/src/main/java/org/opensearch/dataprepper/plugins/geoip/extension/databasedownload/GeoIPDatabaseManager.java
data-prepper-plugins/geoip-processor/src/test/java/org/opensearch/dataprepper/plugins/geoip/extension/databasedownload/HttpDBDownloadServiceTest.java
data-prepper-plugins/geoip-processor/src/test/java/org/opensearch/dataprepper/plugins/geoip/extension/databasedownload/S3DBServiceTest.java

The `geoip` processors creates directories named `first_database` and `second_database`. This can be confusing over time. So I renamed them to `blue_database` and `green_database`.
N/A

Rename first and second database directories to blue and green

---

data-prepper-plugins/http-common/build.gradle
data-prepper-plugins/http-common/src/main/java/org/opensearch/dataprepper/plugins/truststore/TrustStoreProvider.java
data-prepper-plugins/http-common/src/test/java/org/opensearch/dataprepper/plugins/truststore/TrustStoreProviderTest.java
settings.gradle

Add support for creating SSLContext for trustStore file path

Add support for creating SSLContext for trustStore file path

---

.github/workflows/testing-resources-cdk-check.yml
testing/aws-testing-cdk/bin/aws-testing-cdk.ts
testing/aws-testing-cdk/lib/common/GitHubAccessStack.ts
testing/aws-testing-cdk/lib/common/KmsStack.ts
testing/aws-testing-cdk/lib/s3/S3SinkStack.ts
testing/aws-testing-cdk/test/common/GitHubAccessStack.test.ts

The `aws-testing-cdk` project has no verification. This PR:
* Adds a GitHub Action to verify the project by running the tests and the linter.
* Corrects the formatting to match the linter so that it passes.
* Adds a unit test for one of the stacks.
N/A

GitHub Action to verify the aws-testing-cdk project

---

data-prepper-plugins/common/src/main/java/org/opensearch/dataprepper/plugins/source/file/FileSource.java
data-prepper-plugins/common/src/test/java/org/opensearch/dataprepper/plugins/source/RandomStringSourceTests.java
data-prepper-plugins/common/src/test/java/org/opensearch/dataprepper/plugins/source/file/FileSourceTests.java

Data Prepper currently fails when reading large files that exhaust the buffer. This is because the file is read in the start-up thread. If the buffer fills, the processors are not running and the buffer is stuck.
The fix is to start a new thread for reading from files. Now I've been able to read a 160MB file that did previously exhaust the buffer.
Resolves #707

Support large files in file source by using a thread

---

data-prepper-plugins/geoip-processor/build.gradle
data-prepper-plugins/geoip-processor/src/main/java/org/opensearch/dataprepper/plugins/geoip/extension/databasedownload/S3DBService.java
data-prepper-plugins/s3-sink/build.gradle
data-prepper-plugins/s3-sink/src/integrationTest/java/org/opensearch/dataprepper/plugins/sink/s3/S3SinkIT.java

A couple of projects use the AWS Transfer Manager for some simple download scenarios. This project requires `aws-crt` which adds 11MB. The downloads from S3 are straightforward, so we can use the S3 client directly.
Contributes toward #3356

Remove the S3 transfer manager in favor of using the S3 client directly

---

data-prepper-plugins/geoip-processor/src/main/java/org/opensearch/dataprepper/plugins/geoip/utils/IPValidationCheck.java
data-prepper-plugins/geoip-processor/src/test/java/org/opensearch/dataprepper/plugins/geoip/utils/IPValidationCheckTest.java

Fix a small issue in geoip where a string like "123" would pass the IP validation on [this line](https://github.com/opensearch-project/data-prepper/blob/794a6f64c691a2d39a8c3581dc7e0ea24e417749/data-prepper-plugins/geoip-processor/src/main/java/org/opensearch/dataprepper/plugins/geoip/processor/GeoIPProcessor.java#L130) and cause IllegalArgumentException on `InetAddresses.forString(ipAddress)`[here](https://github.com/opensearch-project/data-prepper/blob/794a6f64c691a2d39a8c3581dc7e0ea24e417749/data-prepper-plugins/geoip-processor/src/main/java/org/opensearch/dataprepper/plugins/geoip/processor/GeoIPProcessor.java#L131). It affects ip_not_found tagging and metric as far as I can see.
N/A
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …

Fix ip check and add more tests

---

data-prepper-plugins/common/src/main/java/org/opensearch/dataprepper/common/concurrent/BackgroundThreadFactory.java
data-prepper-plugins/common/src/test/java/org/opensearch/dataprepper/common/concurrent/BackgroundThreadFactoryTest.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/SqsService.java

The goal of this PR is to name the threads created by the SQS worker threads for the `s3` source.
It does this with a common class that any other plugin can use to create background threads.
N/A

Name the S3 source's SQS worker threads

---

data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/export/ExportSchedulerTest.java
data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/export/ExportWorkerTest.java

Improves some unit tests by using Awaitility instead of `Thread.sleep()`. Similar to #4287.
N/A

Use Awaitility in two of the mongodb unit tests

---

data-prepper-plugins/dynamodb-source/build.gradle
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/DynamoDBService.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/configuration/StreamConfig.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/converter/StreamRecordConverter.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/ShardConsumer.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/ShardConsumerFactory.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/DynamoDBServiceTest.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/converter/StreamRecordConverterTest.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/ShardConsumerFactoryTest.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/ShardConsumerTest.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/dlq/FailedBulkOperationConverter.java

Adds an option in the to `view_on_remove: OLD_IMAGE` (defaults to NEW_IMAGE), which will construct an Event from the view type for REMOVE stream events, if old image exists. If it does not exist, the new image will still be used for the Event. 
This follows from DynamoDB streams documentation 
```
StreamViewType — Specifies the information that will be written to the stream whenever data in the table is modified:
KEYS_ONLY — Only the key attributes of the modified item.
NEW_IMAGE — The entire item, as it appears after it was modified.
OLD_IMAGE — The entire item, as it appeared before it was modified.
NEW_AND_OLD_IMAGES — Both the new and the old images of the item
```
Resolves #4261 
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …

Add support to use old ddb stream image for REMOVE events

---

data-prepper-plugins/geoip-processor/src/main/java/org/opensearch/dataprepper/plugins/geoip/GeoIPDatabase.java
data-prepper-plugins/geoip-processor/src/main/java/org/opensearch/dataprepper/plugins/geoip/GeoIPField.java
data-prepper-plugins/geoip-processor/src/main/java/org/opensearch/dataprepper/plugins/geoip/extension/AutoCountingDatabaseReader.java
data-prepper-plugins/geoip-processor/src/main/java/org/opensearch/dataprepper/plugins/geoip/extension/GeoIP2DatabaseReader.java
data-prepper-plugins/geoip-processor/src/main/java/org/opensearch/dataprepper/plugins/geoip/extension/GeoLite2DatabaseReader.java
data-prepper-plugins/geoip-processor/src/main/java/org/opensearch/dataprepper/plugins/geoip/extension/api/GeoIPDatabaseReader.java
data-prepper-plugins/geoip-processor/src/main/java/org/opensearch/dataprepper/plugins/geoip/processor/BatchGeoIPDatabaseReader.java
data-prepper-plugins/geoip-processor/src/main/java/org/opensearch/dataprepper/plugins/geoip/processor/GeoIPProcessor.java
data-prepper-plugins/geoip-processor/src/test/java/org/opensearch/dataprepper/plugins/geoip/GeoIPDatabaseTest.java
data-prepper-plugins/geoip-processor/src/test/java/org/opensearch/dataprepper/plugins/geoip/GeoIPFieldTest.java

The GeoLite2 Country database is a subset of the GeoLite2 City database. Prior to this change, the `geoip` processor was performing a lookup in both databases. These look ups are a substantial part of the processor time.
This PR makes a couple of significant changes.
1. If both city and country fields are needed, then only lookup the data in the city database. This prevents an unnecessary lookup in the country database.
2. If only country fields are needed, then lookup the data only in the country database. This database looks up data faster (presumably because it has less data). 
To accomplish these goals, I refactored the code to move this logic into the `GeoIPDatabase` enum and updated the `GeoIPField` to have the correct database associations.
N/A
By submitting this pull request, I …

Improve geoip performance by reducing database lookups

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/parser/config/PipelineParserConfiguration.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/parser/PipelineTransformerTests.java
data-prepper-pipeline-parser/src/main/java/org/opensearch/dataprepper/pipeline/parser/PipelineConfigurationFileReader.java
data-prepper-pipeline-parser/src/main/java/org/opensearch/dataprepper/pipeline/parser/PipelineConfigurationReader.java
data-prepper-pipeline-parser/src/main/java/org/opensearch/dataprepper/pipeline/parser/PipelinesDataflowModelParser.java
data-prepper-pipeline-parser/src/test/java/org/opensearch/dataprepper/pipeline/parser/PipelineConfigurationFileReaderTest.java
data-prepper-pipeline-parser/src/test/java/org/opensearch/dataprepper/pipeline/parser/PipelinesDataflowModelParserTest.java

This change refactors the `PipelinesDataFlowModelParser` to not be dependent on files, but to be dependent on `InputStreams`. 
This is done with
* An interface `PipelineConfigurationReader` that is passed to the `PipelinesDataFlowModelParser`. 
* An implementation `PipelineConfigurationFileReader` that is created via dependency injection, and contains the former chunk s of `PipelinesDataFlowModelParser` that was relevant to reading the files

Refactor PipelinesDataFlowModelParser to take in an InputStream instead of a file path

---

data-prepper-plugins/aggregate-processor/README.md
data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateProcessor.java
data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateProcessorConfig.java
data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateProcessorConfigTest.java
data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateProcessorTest.java

Provide a config option to do node local aggregation
Added new `local_only` config option to `aggregate` processor to do local aggregation. No events are forwarded to remote peers when this option is used.

Provide a config option to do node local aggregation

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/buffer/Buffer.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/buffer/DelegatingBuffer.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/buffer/BufferTest.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/buffer/DelegatingBufferTest.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/parser/PipelineTransformer.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/RemotePeerForwarder.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/Pipeline.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/ProcessWorker.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/TestDataProvider.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/parser/CircuitBreakingBufferTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/parser/PipelineTransformerTests.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/plugins/TestOffHeapBuffer.java
data-prepper-core/src/test/resources/multiple_disconnected_pipeline_valid_off_heap_buffer_with_acks.yml
data-prepper-core/src/test/resources/multiple_pipeline_valid_off_heap_buffer_with_acks.yml
data-prepper-plugins/aggregate-processor/README.md
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/buffer/KafkaBuffer.java

Send acknowledgements to source when events are forwarded to remote peer
Also, propagate the acknowledgements enabled flag in pipeline correctly when ByteBuffer is used.

Send acknowledgements to source when events are forwarded to remote peer

---

build.gradle
data-prepper-plugins/kafka-plugins/build.gradle
data-prepper-plugins/parquet-codecs/build.gradle
data-prepper-plugins/s3-sink/build.gradle

This PR updates some transitive dependencies to resolve some CVEs:
* CVE-2023-51775
* CVE-2024-23944
* CVE-2023-52428
I also moved some of the dependency constraints such that they are only in the projects needing them. 
This is the last set of CVEs known to resolve for releasing 2.7.0.
Resolves #4282, #4290, #4296.

Resolves transitive dependencies for 2.7.0

---

data-prepper-plugins/geoip-processor/src/main/java/org/opensearch/dataprepper/plugins/geoip/processor/GeoIPProcessor.java
data-prepper-plugins/geoip-processor/src/main/java/org/opensearch/dataprepper/plugins/geoip/processor/GeoIPProcessorConfig.java
data-prepper-plugins/geoip-processor/src/test/java/org/opensearch/dataprepper/plugins/geoip/processor/GeoIPProcessorTest.java

This PR changes the behavior of `tags_on_ip_not_found`. This configuration now only tags when the source has an IP address, but it is not found in the database.
It also adds the `tags_on_no_valid_ip` configuration. This will tag events that do not have any IP address at all.
N/A

Adds a new tags_on_no_valid_ip configuration to geoip

---

data-prepper-plugins/geoip-processor/src/main/java/org/opensearch/dataprepper/plugins/geoip/extension/GeoIpServiceConfig.java
examples/config/example-data-prepper-config.yaml

This configures Data Prepper with the default `geoip_service` configuration. Additionally, it allows the user to configure this minimal and still get the default value by skipping explicit null values.
Resolves #3942

Configure the MaxMind database by default and use correct defaults

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/configuration/DataPrepperVersion.java
gradle.properties

Updates the next Data Prepper version to 2.8.
N/A

Updates the next Data Prepper version to 2.8.

---

build.gradle
data-prepper-core/build.gradle
data-prepper-event/build.gradle
data-prepper-expression/build.gradle
data-prepper-logstash-configuration/build.gradle
data-prepper-main/build.gradle
data-prepper-pipeline-parser/build.gradle
data-prepper-plugin-framework/build.gradle
data-prepper-plugins/build.gradle
data-prepper-test-common/build.gradle
data-prepper-test-event/build.gradle

Starting in Data Prepper 2.7.0, Data Prepper will deploy all artifacts to Maven. This PR splits those groupIds:
* `org.opensearch.dataprepper.core`
* `org.opensearch.dataprepper.plugins`
* `org.opensearch.dataprepper.test`
N/A

Split up the Maven groupIds for core, plugins, and test

---

data-prepper-plugins/truncate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/truncate/TruncateProcessor.java
data-prepper-plugins/truncate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/truncate/TruncateProcessorConfig.java
data-prepper-plugins/truncate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/truncate/TruncateProcessorTests.java

Supports truncating all fields in an event when `source_keys` is not specified or null. 
The config would look like this to truncate all fields to a length of 5 characters.
```
processor:
- truncate:
entries:
- length: 5
```
Also, added support to do truncation recursively in case of nested objects with config option
```
do_recursively: true
```
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/C …

Truncate Processor: Add support to truncate all fields in an event

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/router/Router.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/router/RouterTest.java

Fix Router performance issue.
PR #3959 added `removeAll` to Router code. This method is very expensive in cases with ArrayLists(). Replacing it with for loop that removes individual records.
Also, added a performance optimization to avoid populating `recordsUnRouted` if there is at least one sink to which all records are routed.

Fix Router performance issue

---

data-prepper-plugins/http-source/src/main/java/org/opensearch/dataprepper/plugins/source/loghttp/HTTPSource.java
data-prepper-plugins/http-source/src/main/java/org/opensearch/dataprepper/plugins/source/loghttp/LogHTTPService.java

Revert HTTP data chunking changes for kafka buffer done in PR 4266
Only the relevant changes are reverted, The JsonObjectDecoder added in that PR is not removed as it be useful in future.
HTTP source is modified to use `JsonDecoder` like it was before and LogHTTPService is modified to send the entire data (without chunking) to Kafka.

Revert HTTP data chunking changes for kafka buffer done in PR 4266

---

.github/workflows/release.yml

The release flag has not been needed for a while and now conflicts with the `release` task. This PR removes it from our release GitHub Actions workflow.
We need this to release 2.7.0.
N/A

Removes the release flag from the release GitHub Action

---

data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkRetryStrategy.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkRetryStrategyTests.java

It appears that for some situations, Amazon OpenSearch Serverless is not including the `error` field in bulk response errors. This PR includes a check on the `status` field as well. 
N/A

Handle errors from OpenSearch by checking status field as well as error

---

build.gradle

The release build is failing on the `publish` step:
```
> Task :release:docker:processResources NO-SOURCE
> Invalid publication 'mavenJava': version cannot be empty.
```
The reason is that the current Gradle configuration is trying to publish all projects. This includes projects such as performance-test, e2e-test, and the release projects. 
The current fix for now is to look for projects by name. Either:
* The name starts with `data-prepper` - this covers core projects; or
* The parent project is `data-prepper-plugins` - this covers all plugins
This is needed for the 2.7.0 release.
N/A …

Fix the release build by only applying the Maven publish task to our actual Java artifacts

---

data-prepper-plugins/mapdb-processor-state/build.gradle

We saw the following error log:
```
2024-03-27T05:05:32.331 [pool-10-thread-1] ERROR org.opensearch.dataprepper.plugins.kafka.consumer.KafkaCustomConsumer - Error while reading the records from the topic XYZ. Retry after 10 seconds
...
Caused by: org.apache.kafka.common.KafkaException: java.lang.RuntimeException: Kafka has detected detected a buggy lz4-java library (< 1.4.x) on the classpath. If you are using Kafka client libraries, make sure your application does not accidentally override the version provided by Kafka or include multiple versions of the library on the classpath. The lz4-java version on the classpath should match the version the Kafka client libraries depend on. Adding -verbose:class to your JVM arguments may help understand which lz4-java version is getting loaded.
``` …

Fixes a bug with lz4

---

data-prepper-plugins/opensearch/src/integrationTest/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSinkIT.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchClientRefresher.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSink.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/bulk/BulkApiWrapperFactory.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/bulk/Es6BulkApiWrapper.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/bulk/OpenSearchDefaultBulkApiWrapper.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchClientRefresherTest.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSinkTest.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/bulk/BulkApiWrapperFactoryTest.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/bulk/Es6BulkApiWrapperTest.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/bulk/OpenSearchDefaultBulkApiWrapperTest.java

This PR adds automatic credential refresher for opensearch sink.

ENH: automatic credential refresher opensearch sink

---

data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/CountAggregateAction.java
data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/CountAggregateActionTest.java

Count aggregation incorrectly maintains a global value for exemplars. Exemplars should be maintained per `groupState`.
This change fixes it and maintains a different exemplar for different aggregate groups.

Fix count aggregation exemplar data

---

data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateProcessor.java
data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateProcessorTest.java

Aggregate Processor: local mode should work when there is no when condition.
`local_mode` introduced in PR #4306 should do local aggregation when the condition is not specified too. 

Aggregate Processor: local mode should work when there is no when condition

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/expression/ExpressionEvaluator.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/expression/ExpressionEvaluatorTest.java
data-prepper-expression/src/main/java/org/opensearch/dataprepper/expression/GenericExpressionEvaluator.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/GenericExpressionEvaluatorTest.java
data-prepper-plugins/common/src/main/java/org/opensearch/dataprepper/plugins/s3keyindex/S3ObjectIndexUtility.java
data-prepper-plugins/s3-sink/src/integrationTest/java/org/opensearch/dataprepper/plugins/sink/s3/NdjsonOutputScenario.java
data-prepper-plugins/s3-sink/src/integrationTest/java/org/opensearch/dataprepper/plugins/sink/s3/S3SinkIT.java
data-prepper-plugins/s3-sink/src/integrationTest/java/org/opensearch/dataprepper/plugins/sink/s3/S3SinkServiceIT.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/KeyGenerator.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/S3Sink.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/S3SinkConfig.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/S3SinkService.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/accumulator/InMemoryBuffer.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/accumulator/ObjectKey.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/grouping/S3Group.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/grouping/S3GroupIdentifier.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/grouping/S3GroupIdentifierFactory.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/grouping/S3GroupManager.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/s3/KeyGeneratorTest.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/s3/S3SinkServiceTest.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/s3/S3SinkTest.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/s3/accumulator/ObjectKeyTest.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/s3/grouping/S3GroupIdentifierFactoryTest.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/s3/grouping/S3GroupIdentifierTest.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/s3/grouping/S3GroupManagerTest.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/s3/grouping/S3GroupTest.java

This change adds a concept of `S3Groups` to the S3 Sink. Groups will be created dynamically based on the Events that come into the sink, and will be sent to S3 as a single object when the thresholds are reached for that group.
This PR only adds support for a dynamic `path_prefix`. The support for exposing `object_name` as a dynamic expression will be added in a future PR
Future Planned PRs
* Refactor the buffer tracking of thresholds to the S3Group tracking this to reduce deduplication
* Support `aggregate_threshold` for flushing the largest groups when the threshold is reached
* Support injection of `getEpochNanos()` and `getRandomUUID()` into the dynamic expressions
Related to #4345 
Ran the s3 sink integration tests successfully
By submitting this pull request, I confirm that my …

Add creation and aggregation of dynamic S3 groups based on events

---

data-prepper-plugins/mongodb/build.gradle
data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/configuration/CollectionConfig.java
data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/converter/RecordConverter.java
data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/documentdb/DocumentDBService.java
data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/leader/LeaderScheduler.java
data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/model/CheckpointStatus.java
data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/stream/DataStreamPartitionCheckpoint.java
data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamAcknowledgementManager.java
data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamScheduler.java
data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamWorker.java
data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/export/ExportPartitionWorkerTest.java
data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/leader/LeaderSchedulerTest.java
data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamAcknowledgementManagerTest.java
data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamSchedulerTest.java
data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamWorkerTest.java

Add AcknowledgementSet support to DocumentDB/MongoDB streams

Add AcknowledgementSet support to DocumentDB/MongoDB streams

---

data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/export/ExportPartitionWorker.java
data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/stream/CheckpointStatus.java
data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamAcknowledgementManager.java
data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamAcknowledgementManagerTest.java

Update Stream Ack Manager unit test and code refactor

Update Stream Ack Manager unit test and code refactor

---

data-prepper-plugins/key-value-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/keyvalue/KeyValueProcessorConfig.java

Currently, one cannot configure both the `field_split_characters` and `field_delimiter_regex` for the key_value processor. However, the `field_split_characters` has a default. Even setting both like this fails because field_split_characters is required to not be empty, which means there is currently no way to set `field_delimiter_regex`
```
field_split_characters: null
field_delimiter_regex: ','
```
To allow this, this PR removes the `@NotEmpty` annotation from the `field_split_characters`
Resolves #2946 
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/ma …

Do not require field_split_characters to not be empty for key_value processor

---

data-prepper-pipeline-parser/src/test/java/org/opensearch/dataprepper/pipeline/parser/PipelineConfigurationFileReaderTest.java

I have noticed the builds failings sometimes in github actions with 
```
PipelineConfigurationFileReaderTest > getPipelineConfigurationInput_streams_from_existing_directory() FAILED
java.lang.AssertionError at PipelineConfigurationFileReaderTest.java:106
```
This appears to be due to no guarantee that the List<InputStreams> is in a predictable order, which the test assumes. This makes it so that the order of the expected InputStreams does not matter in the test

Fix flaky PipelineConfigurationFileReaderTest

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/server/ShutdownHandler.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/server/ShutdownHandlerTest.java

To help track down the cause of a Data Prepper shutdown, log the `User-Agent` header. If it is not present, this will output `null`.
Example log from this PR:
```
2024-04-03T16:37:01,937 [pool-6-thread-2] INFO  org.opensearch.dataprepper.pipeline.server.ShutdownHandler - Received HTTP shutdown request to shutdown Data Prepper. Shutdown pipelines and server. User-Agent='curl/8.4.0'
```
N/A

Log the User-Agent when Data Prepper shuts down from POST /shutdown

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/acknowledgements/DefaultAcknowledgementSet.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/acknowledgements/DefaultAcknowledgementSetTests.java

Remove unexpected event handle message.
This message was added initially because duplicate release was not expected. But with remote peer and aggregate processor support, this can happen now. So, removing the message and the metric.

Remove unexpected event handle message

---

.github/CODEOWNERS
MAINTAINERS.md

Adding @KarstenSchnitter as voted upon by the existing Data Prepper maintainers per the [maintainer guidelines](https://github.com/opensearch-project/.github/blob/main/RESPONSIBILITIES.md#becoming-a-maintainer).
Karsten has lead efforts at SAP to introduce new features into Data Prepper. In particular, his contributions provided support for OTel Metrics and OTel Logs.
Some PRs where he is listed as an author or co-author:
* #1507
* #1372
* #1335
* #1154
* #3560
* #3281

Adds KarstenSchnitter as a maintainer to the Data Prepper project

---

data-prepper-plugins/geoip-processor/src/main/java/org/opensearch/dataprepper/plugins/geoip/processor/BatchGeoIPDatabaseReader.java
data-prepper-plugins/geoip-processor/src/test/java/org/opensearch/dataprepper/plugins/geoip/processor/BatchGeoIPDatabaseReaderTest.java

This PR creates a batch-level cache for getting geolocation data. In some local testing I performed with a small processor, I found that this reduced the total memory allocations within the geoip processor from 29% to 25% of the total allocations.
As this cache works for only a given batch, it avoids holding data for a long period of time. And the data itself (IP address and geolocation data) would need to be in memory anyway. So the only overhead is the Map and the references therein.
N/A
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING. …

Cache geolocation data during a batch of events

---

data-prepper-plugins/opensearch/README.md

Document how to perform integration tests for the opensearch-plugin.
This is only documentation
Aligned with Kafka example
https://github.com/opensearch-project/data-prepper/blob/51ee0df595aaad1b921c888394bf3e110ffc74e9/data-prepper-plugins/kafka-plugins/README.md#developer-guide
I am not aware of an issue, but it would have saved time for https://github.com/opensearch-project/data-prepper/pull/3929 and future contributions

Add developer guide/integration test section

---

data-prepper-event/src/main/java/org/opensearch/dataprepper/core/event/DefaultBaseEventBuilder.java
data-prepper-event/src/main/java/org/opensearch/dataprepper/core/event/DefaultEventBuilderFactory.java
data-prepper-event/src/main/java/org/opensearch/dataprepper/core/event/DefaultLogEventBuilderFactory.java
data-prepper-event/src/test/java/org/opensearch/dataprepper/core/event/DefaultBaseEventBuilderTests.java
data-prepper-event/src/test/java/org/opensearch/dataprepper/core/event/DefaultEventBuilderFactoryTests.java
data-prepper-plugins/avro-codecs/build.gradle
data-prepper-plugins/avro-codecs/src/main/java/org/opensearch/dataprepper/plugins/codec/avro/AvroInputCodec.java
data-prepper-plugins/avro-codecs/src/test/java/org/opensearch/dataprepper/plugins/codec/avro/AvroCodecsIT.java
data-prepper-plugins/avro-codecs/src/test/java/org/opensearch/dataprepper/plugins/codec/avro/AvroInputCodecTest.java
data-prepper-plugins/avro-codecs/src/test/java/org/opensearch/dataprepper/plugins/codec/avro/AvroOutputCodecTest.java
data-prepper-plugins/csv-processor/build.gradle
data-prepper-plugins/csv-processor/src/main/java/org/opensearch/dataprepper/plugins/codec/csv/CsvInputCodec.java
data-prepper-plugins/csv-processor/src/test/java/org/opensearch/dataprepper/plugins/codec/csv/CsvCodecTest.java
data-prepper-plugins/csv-processor/src/test/java/org/opensearch/dataprepper/plugins/codec/csv/CsvCodecsIT.java
data-prepper-plugins/newline-codecs/build.gradle
data-prepper-plugins/newline-codecs/src/main/java/org/opensearch/dataprepper/plugins/codec/newline/NewlineDelimitedInputCodec.java
data-prepper-plugins/newline-codecs/src/test/java/org/opensearch/dataprepper/plugins/codec/newline/NewlineDelimitedCodecTest.java
data-prepper-plugins/parquet-codecs/build.gradle
data-prepper-plugins/parquet-codecs/src/main/java/org/opensearch/dataprepper/plugins/codec/parquet/ParquetInputCodec.java
data-prepper-plugins/parquet-codecs/src/test/java/org/opensearch/dataprepper/plugins/codec/parquet/ParquetInputCodecTest.java
data-prepper-plugins/s3-source/build.gradle
data-prepper-plugins/s3-source/src/integrationTest/java/org/opensearch/dataprepper/plugins/source/s3/AvroRecordsGenerator.java
data-prepper-plugins/s3-source/src/integrationTest/java/org/opensearch/dataprepper/plugins/source/s3/CsvRecordsGenerator.java
data-prepper-plugins/s3-source/src/integrationTest/java/org/opensearch/dataprepper/plugins/source/s3/NewlineDelimitedRecordsGenerator.java
data-prepper-plugins/s3-source/src/integrationTest/java/org/opensearch/dataprepper/plugins/source/s3/ParquetRecordsGenerator.java

This PR continues some of the work from #2378 and #4110 by updating the codecs to use the `EventFactory`.
N/A

Updates the S3/file codecs to use the EventFactory

---

data-prepper-plugins/dynamodb-source-coordination-store/src/main/java/org/opensearch/dataprepper/plugins/sourcecoordinator/dynamodb/DynamoDbClientWrapper.java
data-prepper-plugins/dynamodb-source-coordination-store/src/test/java/org/opensearch/dataprepper/plugins/sourcecoordinator/dynamodb/DynamoDbClientWrapperTest.java

Float up exception from sourceCoordinationStore createPartition as PartitionUpdateException as discussed offline. This will help fix the partition creation loop in DDB and DocumentDB.

MAINT: float up exception from createPartition

---

data-prepper-plugins/s3-sink/src/integrationTest/java/org/opensearch/dataprepper/plugins/sink/s3/S3SinkServiceIT.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/S3Sink.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/S3SinkService.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/codec/CodecFactory.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/grouping/S3Group.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/grouping/S3GroupManager.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/s3/S3SinkServiceTest.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/s3/grouping/S3GroupManagerTest.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/s3/grouping/S3GroupTest.java

This change fixes a bug where with codecs in the s3 sink where each codec instantiation expects to only track a single output stream by moving the codec instantiation within each S3 group
This only occurs for the Json output codec, which I will add an integration test for in a follow up

Create new codec for each s3 group in s3 sink

---

data-prepper-plugins/aws-plugin-api/build.gradle
data-prepper-plugins/aws-plugin-api/src/main/java/org/opensearch/dataprepper/aws/validator/AwsAccountId.java
data-prepper-plugins/aws-plugin-api/src/main/java/org/opensearch/dataprepper/aws/validator/AwsAccountIdConstraintValidator.java
data-prepper-plugins/aws-plugin-api/src/test/java/org/opensearch/dataprepper/aws/validator/AwsAccountIdConstraintValidatorTest.java
data-prepper-plugins/aws-plugin-api/src/test/java/org/opensearch/dataprepper/aws/validator/AwsAccountIdTest.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/S3SourceConfig.java

The goal of this PR is to validate two configurations in the S3 source:
* `default_bucket_owner`
* `bucket_owners`
Additionally, it adds a new JSR-380 bean validation - `@AwsAccountId`. Any other component using the `aws-plugin-api` can use this now. It also sets a new pattern than we can use for other generic AWS validations.
Here are some sample error messages:
For `default_bucket_owner`:
> Plugin s3 in pipeline vpc-flow-log-pipeline is configured incorrectly: defaultBucketOwner The value provided for an AWS account Id must be a valid AWS account Id with 12 digits.
For `bucket_owners`:
> Plugin s3 in pipeline vpc-flow-log-pipeline is configured incorrectly: bucketOwners[my-bucket].<map value> The value provided for an AWS account Id must be a valid AWS account Id with 12 digits. …

Validate the AWS account Id in the S3 source using a new annotation

---

data-prepper-plugins/failures-common/src/main/java/org/opensearch/dataprepper/plugins/dlq/s3/S3DlqWriter.java
data-prepper-plugins/failures-common/src/test/java/org/opensearch/dataprepper/plugins/dlq/s3/S3DlqWriterTest.java

The DLQ was writing empty objects for some scenarios. This PR does not write empty lists to S3.
Resolves #4301

Do not write empty lists of DlqObject to the DLQ

---

data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/accumulator/BufferUtilities.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/grouping/S3GroupManager.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/s3/accumulator/BufferUtilitiesTest.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/s3/grouping/S3GroupManagerTest.java

This bug happened on rebase of the previous PR (https://github.com/opensearch-project/data-prepper/pull/4402) which passes static bucket name from config to the buffer rather than the dynamic bucket. This led to a finding that we should catch errors for invalid bucket message

Fix bug in s3 sink dynamic bucket and catch invalid bucket message

---

data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/DynamoDBSource.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/export/DataFileLoader.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/DynamoDBSourceTest.java

Fix acknowledgements in DynamoDB. Each source supporting acknowledgments must override `areAcknowledgementsEnabled`. That was missing in DynamoDB. Fixed the issue by adding that API.
Resolves #4420 

Fix acknowledgements in DynamoDB

---

build.gradle
buildSrc/build.gradle
buildSrc/src/main/groovy/data-prepper.publish.gradle
data-prepper-api/build.gradle
data-prepper-core/build.gradle
data-prepper-event/build.gradle
data-prepper-main/build.gradle
data-prepper-pipeline-parser/build.gradle
data-prepper-plugin-framework/build.gradle
data-prepper-plugins/build.gradle
data-prepper-test-common/build.gradle
data-prepper-test-event/build.gradle

This PR moves the Maven publication steps into a [Gradle convention plugin](https://docs.gradle.org/current/userguide/sharing_build_logic_between_subprojects.html#sec:convention_plugins).
There are a few of motivations for this.
1. The decision for which projects to publish was made in the root `build.gradle` rather than in the projects themselves. Now, projects decide by adding the plugin.
2. This is easier to change dynamically when running builds that are not part of the standard open-source release.
3. The projects would set the `group`, but it was not clear why from reading the project Gradle since the publication was inherited.
4. Gradle recommends using convention plugins over `subprojects`/`allprojects`. This may be a good thing to do going forward.
N/A
By submitting this pull …

Adds a Gradle convention plugin for Maven publication

---

data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/client/MongoDBConnection.java
data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/client/MongoDBConnectionTest.java

Encode MongoDB/DocumentDB username and password while constructing connection string

Encode MongoDB/DocumentDB username and password while constructing connection string

---

data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/documentdb/DocumentDBService.java
data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/export/DataQueryPartitionCheckpoint.java
data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/export/ExportPartitionWorker.java
data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/s3partition/S3FolderPartitionCoordinator.java
data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/s3partition/S3PartitionCreator.java
data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/s3partition/S3PartitionCreatorScheduler.java
data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/stream/DataStreamPartitionCheckpoint.java
data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamWorker.java
data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/export/ExportPartitionWorkerTest.java
data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamWorkerTest.java

Remove creating S3 prefix path partition upfront. This will be done when S3 sink writes data with path prefix.

Remove creating S3 prefix path partition upfront

---

data-prepper-plugins/s3-sink/src/integrationTest/java/org/opensearch/dataprepper/plugins/sink/s3/S3SinkServiceIT.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/codec/parquet/S3OutputStream.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/ClientFactory.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/S3Sink.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/S3SinkService.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/accumulator/Buffer.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/accumulator/BufferFactory.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/accumulator/BufferUtilities.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/accumulator/CodecBuffer.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/accumulator/CodecBufferFactory.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/accumulator/CompressionBuffer.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/accumulator/CompressionBufferFactory.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/accumulator/InMemoryBuffer.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/accumulator/InMemoryBufferFactory.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/accumulator/LocalFileBuffer.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/accumulator/LocalFileBufferFactory.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/accumulator/MultipartBuffer.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/accumulator/MultipartBufferFactory.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/grouping/S3GroupManager.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/codec/parquet/S3OutputStreamTest.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/s3/S3SinkServiceTest.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/s3/accumulator/BufferUtilitiesTest.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/s3/accumulator/CodecBufferTest.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/s3/accumulator/CompressionBufferFactoryTest.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/s3/accumulator/CompressionBufferTest.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/s3/accumulator/InMemoryBufferTest.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/s3/accumulator/LocalFileBufferTest.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/s3/grouping/S3GroupManagerTest.java

This change modifies the clients in the s3 sink to use the async client instead of the synchronous client to improve performance when writing many objects from different groups with dynamic path_prefix

Change s3 sink client to async client

---

data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/configuration/CollectionConfig.java
data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/coordination/partition/S3FolderPartition.java
data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/leader/LeaderScheduler.java
data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/s3partition/S3PartitionCreator.java
data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/s3partition/S3PartitionCreatorScheduler.java
data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/leader/LeaderSchedulerTest.java
data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/s3partition/S3FolderPartitionCoordinatorTest.java
data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/s3partition/S3PartitionCreatorSchedulerTest.java
data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/s3partition/S3PartitionCreatorTest.java

Make s3 partition size configurable and add unit test for S3 partition creator classes

Make s3 partition size configurable and add unit test for S3 partition creator classes

---

build.gradle
data-prepper-plugins/armeria-common/src/test/java/org/opensearch/dataprepper/plugins/GrpcBasicAuthenticationProviderTest.java
data-prepper-plugins/armeria-common/src/test/java/org/opensearch/dataprepper/plugins/UnauthenticatedGrpcAuthenticationProviderTest.java
settings.gradle

The goal of this PR is to update Armeria to 1.28.2. This fixes a bug that affects Data Prepper - https://github.com/line/armeria/issues/5572.
This change also required updating a couple other dependencies: gRPC to 1.63.0 and Netty to 4.1.108.
Also, a couple unit tests started failing with this update. Armeria had fixed a bug to return Bad Request instead of Service Unavailable when the request was bad. The test was asserting for this failure because it was not sending the correct request body. I corrected this by sending the necessary body.
N/A …

Updates Ameria to 1.28.2

---

data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/configuration/AuthConfig.java

This PR deprecate plaintext with plain under sasl since plain is the correct auth mechanism

MAINT: deprecate plaintext with plain under sasl in kafka

---

data-prepper-plugins/failures-common/src/test/java/org/opensearch/dataprepper/plugins/dlq/s3/S3DlqWriterTest.java

With the recent change in #4403, the DLQ write does not write for empty objects. The unit tests use a random value which would sometimes generate 0 entries. This is causing test failures and flakiness.
This change always uses a value of at least 2. I chose 2 so that all tests run with multiple values.
N/A

Use positive numbers in S3DlqWriterTest for consistent test success.

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/source/coordinator/SourceCoordinator.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/sourcecoordination/LeaseBasedSourceCoordinator.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/sourcecoordination/SourceCoordinatorFactory.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/sourcecoordination/LeaseBasedSourceCoordinatorTest.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/NoSearchContextWorker.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/PitWorker.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/ScrollWorker.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/WorkerCommonUtils.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/PitWorkerTest.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/ScrollWorkerTest.java
data-prepper-plugins/s3-source/src/integrationTest/java/org/opensearch/dataprepper/plugins/source/s3/S3ScanObjectWorkerIT.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/S3ScanService.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/S3Source.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/S3SourceConfig.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/ScanObjectWorker.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/s3/S3ScanObjectWorkerTest.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/s3/S3ScanServiceTest.java

Added support for multiple workers in S3 Scan Source

Added support for multiple workers in S3 Scan Source

---

data-prepper-plugins/kafka-plugins/src/integrationTest/java/org/opensearch/dataprepper/plugins/kafka/source/ConfluentKafkaProducerConsumerWithSchemaRegistryIT.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/configuration/SchemaConfig.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaCustomConsumerFactory.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/source/KafkaSource.java

This PR fixes the requirement to specify schema version in confluent schema type:
current
```
kafka:
topics:
- name: "topic_4"
group_id: "groupdID1"
bootstrap_servers:
- ...
schema:
type: confluent
registry_url: https://psrc-m5k9x.us-west-2.aws.confluent.cloud
version: 1 # <- required previously
```
after this change:
```
kafka:
topics:
- name: "topic_4"
group_id: "groupdID1"
bootstrap_servers:
- ...
schema:
type: confluent
registry_url: https://psrc-m5k9x.us-west-2.aws.confluent.cloud
```
Run confluent integration tests manually to verify the change
For more information on following Developer Certificate of Origin …

MAINT: allow latest schema version if not specified in confluent schema

---

data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/client/MongoDBConnection.java
data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/configuration/MongoDBSourceConfig.java
data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/client/MongoDBConnectionTest.java
data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/leader/LeaderSchedulerTest.java

Revert DocumentDB Source String array host to String host

 Revert DocumentDB Source String array host to String host

---

data-prepper-plugins/opensearch/src/integrationTest/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSinkIT.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/ConnectionConfiguration.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchClientRefresher.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/configuration/AuthConfig.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/ConnectionConfigurationTests.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchClientRefresherTest.java

This PR deprecates username and password with authentication in opensearch sink.
```
sink:
- opensearch:
authentication:
username:
password:
```

MAINT: use authentication block in opensearch sink

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/source/SourceCoordinationStore.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/source/coordinator/PartitionIdentifier.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/source/coordinator/SourceCoordinator.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/source/coordinator/PartitionIdentifierTest.java
data-prepper-core/build.gradle
data-prepper-core/src/main/java/org/opensearch/dataprepper/sourcecoordination/LeaseBasedSourceCoordinator.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/sourcecoordination/LeaseBasedSourceCoordinatorTest.java
data-prepper-plugins/dynamodb-source-coordination-store/src/main/java/org/opensearch/dataprepper/plugins/sourcecoordinator/dynamodb/DynamoDbClientWrapper.java
data-prepper-plugins/dynamodb-source-coordination-store/src/main/java/org/opensearch/dataprepper/plugins/sourcecoordinator/dynamodb/DynamoDbSourceCoordinationStore.java
data-prepper-plugins/dynamodb-source-coordination-store/src/test/java/org/opensearch/dataprepper/plugins/sourcecoordinator/dynamodb/DynamoDbClientWrapperTest.java
data-prepper-plugins/dynamodb-source-coordination-store/src/test/java/org/opensearch/dataprepper/plugins/sourcecoordinator/dynamodb/DynamoDbSourceCoordinationStoreTest.java
data-prepper-plugins/in-memory-source-coordination-store/src/main/java/org/opensearch/dataprepper/plugins/sourcecoordinator/inmemory/InMemorySourceCoordinationStore.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/S3ObjectReference.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/S3ScanPartitionCreationSupplier.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/S3SourceConfig.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/S3SourceProgressState.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/ScanObjectWorker.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/configuration/FolderPartitioningOptions.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/configuration/S3ScanScanOptions.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/s3/S3ScanObjectWorkerTest.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/s3/S3ScanPartitionCreationSupplierTest.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/s3/S3SourceConfigTest.java

This change adds support for the s3 scan source to partition based on folders instead of objects. This means that, unlike object partitions, folder partitions will never be marked as complete, and each node / worker that grabs a folder partition will list and process objects in that folder, then give it up. The use case for this is order guarantee within S3 folders, as well as aggregations within S3 folders, as the same worker / node will process objects from the same S3 folder. To enable this mode, one must set the following configuration. 
```
source:
s3:
scan:
folder_partitions:
depth: 2 # Defaults to 1
max_objects_per_ownership: 10 # Defaults to 50
```
For more …

Add folder-based partitioning for s3 scan source

---

data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/documentdb/DocumentDBSource.java

Makes sure data-prepper-core knows when acknowledgments are enabled for the docdb source

Let data-prepper-core know if docdb has acknowledgments enabled

---

data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamWorker.java
data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamWorkerTest.java

Move MongoDB/DocDB stream checkpoint to separate thread

Move MongoDB/DocDB stream checkpoint to separate thread

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/JacksonEvent.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/event/JacksonEventTest.java
data-prepper-plugins/event-json-codecs/src/test/java/org/opensearch/dataprepper/plugins/codec/event_json/EventJsonInputOutputCodecTest.java

Fix JacksonEvent to propagate ExternalOriginalTime if its set at the time of construction.
With eventjson codec, it is possible for an event to have external origination time at the time of event construction. If it exists, propagate it to event handle.

Fix JacksonEvent to propagate ExternalOriginalTime if its set at the time of construction

---

data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/configuration/ConnectionConfiguration.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/configuration/ConnectionConfigurationTest.java

When `certificate` is null, it should be identified as valid in jakarta validation. Added a regression test
- [ x ] New functionality includes testing.

FIX: null certificate value should be valid in opensearch connection

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/source/s3/S3ScanEnvironmentVariables.java
data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/configuration/MongoDBSourceConfig.java
data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/leader/LeaderScheduler.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/ScanObjectWorker.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/s3/S3ScanObjectWorkerTest.java

Sets a system property from DocumentDB source when the Leader ownership is acquired by the same node. This system property will stop S3 Scan pipelines from processing objects. 

Add system property to allow pausing and resuming s3 scan worker thread processing, set this property to pause on documentdb leader

---

data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/stream/DataStreamPartitionCheckpoint.java
data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamWorker.java
data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/stream/DataStreamPartitionCheckpointTest.java
data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamWorkerTest.java

Support Mongo/DocDB stream Delete and other Operation types

Support Mongo/DocDB stream Delete and other Operation types

---

data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamWorker.java
data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamWorkerTest.java

Support default mapping for Mongo/DocumentDB data types

Support default mapping for Mongo/DocumentDB data types 

---

data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/leader/LeaderScheduler.java
data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamScheduler.java

Follow up from https://github.com/opensearch-project/data-prepper/pull/4495, StreamScheduler is the node that will work on reading from DocumentDB streams, so the owner of this job should be the one to stop s3 scan processing

Move stopping of s3 scan from docdb leader scheduler to stream scheduler

---

data-prepper-pipeline-parser/src/main/resources/templates/documentdb-template.yaml
data-prepper-plugins/s3-source/src/integrationTest/java/org/opensearch/dataprepper/plugins/source/s3/S3ObjectWorkerIT.java
data-prepper-plugins/s3-source/src/integrationTest/java/org/opensearch/dataprepper/plugins/source/s3/S3ScanObjectWorkerIT.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/EventMetadataModifier.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/S3Source.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/S3SourceConfig.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/s3/EventMetadataModifierTest.java

- Add new S3 source option
`disable_s3_metadata_in_event: true` option will not add bucket name and key to event.
- Modify docdb template
Added `disable_s3_metadata_in_event` and `folder_partitions` options in s3 scan of doc db template

Add new S3 source option and modify docdb template

---

data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/client/BsonHelper.java
data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/converter/MetadataKeyAttributes.java
data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/converter/RecordConverter.java
data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/export/ExportPartitionWorker.java
data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/export/MongoDBExportPartitionSupplier.java
data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamWorker.java
data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/client/BsonHelperTest.java
data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/converter/RecordConverterTest.java
data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/export/ExportPartitionWorkerTest.java
data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/export/MongoDBExportPartitionSupplierTest.java
data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamWorkerTest.java

Add support to export/full load MongoDB/DocumentDB collection with `_id` field of different data type

Add support to export/full load MongoDB/DocumentDB collection with `_id` field of different data type

---

data-prepper-pipeline-parser/src/main/resources/templates/documentdb-template.yaml

Fix depth field in docDB template. It should be just an object type and not an array type.

Fix depth field in template

---

data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaCustomConsumer.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaCustomConsumerTest.java

For the purpose of tracking pipelineEndToEndLatency metric.

MAINT: inject external origination timestamp

---

data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/converter/PartitionKeyRecordConverter.java
data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/converter/RecordConverter.java
data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/export/ExportPartitionWorker.java
data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamWorker.java
data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamWorkerTest.java

Fix document version for DocDB/Mongo Stream events

Fix document version for DocDB/Mongo Stream events

---

data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamWorker.java
data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamWorkerTest.java

Exclude updateDescription field from Mongo/DocDB change stream. The watch steam uses FullDocument lookup, so updateDescription is redundant and is not used. It also contributes to stream document size, so removing this field to not hit the stream document size limit of 16MB.

Exclude updateDescription field from Mongo/DocDB change stream

---

data-prepper-api/build.gradle
data-prepper-plugins/avro-codecs/build.gradle
data-prepper-plugins/common/build.gradle
data-prepper-plugins/csv-processor/build.gradle
data-prepper-plugins/event-json-codecs/build.gradle
data-prepper-plugins/newline-codecs/build.gradle
data-prepper-plugins/parquet-codecs/build.gradle
data-prepper-plugins/parse-json-processor/build.gradle
data-prepper-plugins/s3-sink/build.gradle
data-prepper-plugins/s3-source/build.gradle

1.14.0 has critical bug fixes for parquet files written in OCSF 1.1 schema.

Bump parquet version to 1.14.0.

---

data-prepper-pipeline-parser/src/main/resources/templates/documentdb-template.yaml
data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamWorker.java

Clears the system property to re-enable s3 scan pipeline when documentdb stream worker exits

Clear system property to disable s3 scan when stream worker exits, set s3 sink threshold to 15 seconds for docdb streams

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/DataType.java
data-prepper-expression/src/main/antlr/DataPrepperExpression.g4
data-prepper-expression/src/main/java/org/opensearch/dataprepper/expression/ParseTreeCoercionService.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/ParseTreeCoercionServiceTest.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/TypeOfOperatorTest.java

Modify typeof operator to accept the types without double quotes.
For example, after this change the expression with typeof operator will be like this
`/field typeof "integer"` to `/field typeof integer`
Also, modified to support check for "array" to return true for ArrayList too

Modify typeof operator grammar and add support for ArrayList

---

data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/stream/DataStreamPartitionCheckpoint.java
data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamAcknowledgementManager.java
data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamScheduler.java
data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamWorker.java
data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/stream/DataStreamPartitionCheckpointTest.java
data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamWorkerTest.java

Write stream events that timeout to write to internal buffer in separate thread

Write stream events that timeout to write to internal buffer in separate thread

---

data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/client/BsonHelper.java
data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamAcknowledgementManager.java
data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamScheduler.java
data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamWorker.java
data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/client/BsonHelperTest.java
data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamWorkerTest.java

* Complete AcknowledgementSet for checkpoint thread when Ack is enabled
* Use time in seconds for BsonTimeStamp field when converting to record

Complete AcknowledgementSet for checkpoint thread & fix BsonTimeStamp field conversion

---

data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamAcknowledgementManager.java

Checkpoint records at an interval for high TPS case when AckSet is enabled

Checkpoint records at an interval for TPS case when AckSet is enabled 

---

data-prepper-plugins/key-value-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/keyvalue/KeyValueProcessor.java
data-prepper-plugins/key-value-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/keyvalue/KeyValueProcessorConfig.java
data-prepper-plugins/key-value-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/keyvalue/KeyValueProcessorTests.java

Two new config options are added
1. `value_grouping: true/false`
This option groups the values when values start with "(" "[" "<" "{" , single quote, double quote and "http://" and "https://"
When a value starts with one of the above mentioned strings, all the characters after that are considered part of the value until the corresponding end character is found (ie no keyvalue or field value parsing happens). If the corresponding end character is not found, an error is displayed. When this option is enabled, `field_delimiter_regex` option is not allowed. All other existing options are valid with this config option.
2. `drop_keys_with_no_value:true/false`
This option drops keys that do not have a value associated with them. This is done after `default_values` option is processed. Even after …

Key value processor enhancements

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/peerforwarder/RequiresPeerForwarding.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/peerforwarder/RequiresPeerForwardingTest.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/PeerForwardingProcessorDecorator.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/PeerForwardingProcessingDecoratorTest.java
data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateProcessor.java
data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateProcessorTest.java

Local mode option added to aggregate processor in PR #4306 has a bug that when local mode is turned on the events are not passed to the remote peer but also skipped from passing it to the local inner processor. This change fixes the issue so that local mode works as expected.
Resolves #

Fix aggregate processor local mode

---

data-prepper-plugins/failures-common/src/main/java/org/opensearch/dataprepper/plugins/dlq/s3/S3DlqWriter.java

Show exception messages instead of masking them through the SENSITIVE marker.
I checked all usages of SENSITIVE and EVENT in the repo and seems that all issues are in this S3DlqWriter.java file. 
Resolves #3375 

Fix an issue that exception messages are masked

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/configuration/PipelineModel.java
data-prepper-api/src/test/resources/pipelines_data_flow_route.yaml
data-prepper-pipeline-parser/src/main/java/org/opensearch/dataprepper/pipeline/parser/rule/RuleEvaluator.java
data-prepper-pipeline-parser/src/main/java/org/opensearch/dataprepper/pipeline/parser/transformer/DynamicConfigTransformer.java
data-prepper-pipeline-parser/src/main/resources/templates/documentdb-template.yaml
data-prepper-pipeline-parser/src/test/java/org/opensearch/dataprepper/pipeline/parser/TestConfigurationProvider.java
data-prepper-pipeline-parser/src/test/java/org/opensearch/dataprepper/pipeline/parser/transformer/DynamicConfigTransformerTest.java
data-prepper-pipeline-parser/src/test/resources/transformation/expected/documentdb-expected.yaml
data-prepper-pipeline-parser/src/test/resources/transformation/expected/documentdb-route-expected.yaml
data-prepper-pipeline-parser/src/test/resources/transformation/expected/documentdb-routes-expected.yaml
data-prepper-pipeline-parser/src/test/resources/transformation/expected/documentdb-subpipelines-routes-expected.yaml
data-prepper-pipeline-parser/src/test/resources/transformation/expected/documentdb2-expected.yaml
data-prepper-pipeline-parser/src/test/resources/transformation/templates/testSource/documentdb-template-final.yaml
data-prepper-pipeline-parser/src/test/resources/transformation/templates/testSource/documentdb-template.yaml
data-prepper-pipeline-parser/src/test/resources/transformation/userConfig/documentdb-route-userconfig.yaml
data-prepper-pipeline-parser/src/test/resources/transformation/userConfig/documentdb-routes-userconfig.yaml
data-prepper-pipeline-parser/src/test/resources/transformation/userConfig/documentdb-subpipelines-routes-userconfig.yaml
docs/pipeline_configuration_transformation.md

Address route and subpipeline for pipeline tranformation.
1. PipelineModel uses route and routes as alias, which needs to be addressed in the transformation. 
Routes or route (defined as alias in Pipeline Model) will be always be transformed to route in json , as route will be primarily picked in pipelineModel when converting model to json or the other way round.
2. Subpipelines within one pipeline was addressed in the transformation.
Earlier, subpipelines were using the untransformed pipeline name. Made changes to make it pick the transformed pipeline name. …

Address route and subpipeline for pipeline tranformation

---

data-prepper-plugins/parse-json-processor/build.gradle
data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/codec/json/NdjsonInputCodec.java
data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/codec/json/NdjsonInputConfig.java
data-prepper-plugins/parse-json-processor/src/test/java/org/opensearch/dataprepper/plugins/codec/json/NdjsonInputCodecTest.java

Adds the `ndjson` codec. This also supports lenient formats where there are not newlines.
Resolves #2700
Tested with:
```
{"name" :  "one", "value":  1}
{"name" :  "two", "value":  2}{"name" :  "three", "value":  3}
{"name" :  "four", "value":  4}
{}
{"name" :  "five", "value":  5}
{}{"name" :  "six", "value":  6}
{"name" :  "seven", "value":  7}
```
With `stdout` sink:
```
data-prepper  | {"name":"one","value":1}
data-prepper  | {"name":"two","value":2}
data-prepper  | {"name":"three","value":3}
data-prepper  | {"name":"seven","value":7}
data-prepper  | {"name":"four","value":4}
data-prepper  | {"name":"five","value":5}
data-prepper  | {"name":"six","value":6}
```
For more …

Adds an ndjson input codec for reading ND-JSON and lenient formats

---

data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/documentdb/DocumentDBService.java
data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/documentdb/MongoTasksRefresher.java
data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/export/ExportPartitionWorker.java
data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/export/ExportWorker.java
data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/export/MongoDBExportPartitionSupplier.java
data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamScheduler.java
data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamWorker.java
data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/utils/DocumentDBSourceAggregateMetrics.java
data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/documentdb/MongoTasksRefresherTest.java
data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/export/ExportPartitionWorkerTest.java
data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/export/ExportWorkerTest.java
data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/export/MongoDBExportPartitionSupplierTest.java
data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamSchedulerTest.java
data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamWorkerTest.java

Add DocDB source aggregate metrics - 4xxErrors, 5xxErrors, ApiInvocations for both export and stream.
The metrics are used to track errors across pipelines when connecting to and querying DocDB.
The metrics are incremented in ExportPartitionWorker, MongoDBExportPartitionSupplier and StreamWorker.
N/A

Add DocDB source aggregate metrics

---

examples/trace-analytics-sample-app/sample-app/requirements.txt

Updates werkzeug to 3.0.3 in examples to fix CVE-2024-34069. 
Resolves #4515

Updates werkzeug to 3.0.3 in examples to fix CVE-2024-34069. 

---

data-prepper-plugins/obfuscate-processor/README.md
data-prepper-plugins/obfuscate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/obfuscation/ObfuscationProcessor.java
data-prepper-plugins/obfuscate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/obfuscation/ObfuscationProcessorConfig.java
data-prepper-plugins/obfuscate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/obfuscation/ObfuscationProcessorTest.java

Adding `single_word_only` configuration option to obfuscate processor. When set to `true` a word boundary `\b` is added to the pattern, due to which obfuscation would be applied only to words that are standalone in the input text. By default, it is `false`, meaning obfuscation patterns are applied to all occurrences.
Resolves #4340 

Adding 'single_word_only' option to obfuscate processor

---

data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/export/ExportScheduler.java
data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/export/ExportSchedulerTest.java

Fix DocDB export and stream processing self recovery with invalid database or collection name
Creating Stream global status when there are no records to export. This should unblock processing stream records.
Resolves #[[4544](https://github.com/opensearch-project/data-prepper/issues/4544)]

Fix DocDB export and stream processing self recovery with invalid database or collection name

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/DefaultEventMetadata.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/event/DefaultEventMetadataTest.java
data-prepper-plugins/kafka-plugins/src/integrationTest/java/org/opensearch/dataprepper/plugins/kafka/source/KafkaSourceJsonTypeIT.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaCustomConsumer.java

Add support for Kafka headers and timestamp in the Kafka Source.
If the consumer Record has any headers, they are included in the event. Similarly, timestamp is included in the event.
Resolves #4565 

Add support for Kafka headers and timestamp in the Kafka Source

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/DataType.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/JacksonEvent.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/source/coordinator/SourceCoordinator.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/typeconverter/BigDecimalConverter.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/typeconverter/BooleanConverter.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/typeconverter/ConverterArguments.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/typeconverter/DoubleConverter.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/typeconverter/IntegerConverter.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/typeconverter/LongConverter.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/typeconverter/StringConverter.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/typeconverter/TypeConverter.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/event/DataTypeTest.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/event/DefaultEventMetadataTest.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/event/JacksonEventTest.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/typeconverter/BigDecimalConverterTests.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/typeconverter/BooleanConverterTests.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/typeconverter/DoubleConverterTests.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/typeconverter/IntegerConverterTests.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/typeconverter/LongConverterTests.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/typeconverter/StringConverterTests.java
data-prepper-plugin-framework/src/test/java/org/opensearch/dataprepper/plugin/DataPrepperScalarTypeDeserializerTest.java
data-prepper-plugin-framework/src/test/java/org/opensearch/dataprepper/plugin/VariableExpanderTest.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/ConvertEntryTypeProcessor.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/ConvertEntryTypeProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/TargetType.java
data-prepper-plugins/mutate-event-processors/src/test/java/org/opensearch/dataprepper/plugins/processor/mutateevent/ConvertEntryTypeProcessorTests.java
data-prepper-plugins/mutate-event-processors/src/test/java/org/opensearch/dataprepper/plugins/processor/mutateevent/TargetTypeTest.java

Introduced BigDecimal Converter that users can use as part of convert_entry_type processor that currently exists. Optionally, users can also specify required scaling needed while converting to BigDecimal. If scale value is given by the user then we apply [HALF_EVEN](https://docs.oracle.com/javase/8/docs/api/java/math/RoundingMode.html) rounding strategy if the original number has more decimal digits than the scale value given.
Fix for the issue described at => https://github.com/opensearch-project/data-prepper/issues/3840
IMPORTANT Note: This PR is disabling [STRIP_TRAILING_BIGDECIMAL_ZEROES](https://www.javadoc.io/doc/com.fasterxml.jackson.core/jackson-databind/latest/com/fasterxml/jackson/databind/cfg/JsonNodeFeature.html#STRIP_TRAILING_BIGDECIMAL_ZEROES) by default. In other words, we …

Introduced BigDecimalConverter 

---

data-prepper-plugins/key-value-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/keyvalue/KeyValueProcessor.java
data-prepper-plugins/key-value-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/keyvalue/KeyValueProcessorConfig.java
data-prepper-plugins/key-value-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/keyvalue/KeyValueProcessorTests.java

Adds the following new features
1. Supports string literal grouping when valueGrouping option is enabled. String literal grouping allows text inside double quotes OR single quotes to be treated as one entity. When combined with `drop_keys_with_no_value` such text can be dropped from the output
2. Support `strict_grouping` option where a group with the starting group character and missing  end group character does not throw error and instead considered as the group till the end of the text
3. Fix `value_grouping` to strictly apply grouping to values and not to keys and other parts of input.
By submitting this pull request, I confirm …

Modify Key Value processor to support string literal grouping

---

data-prepper-plugins/key-value-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/keyvalue/KeyValueProcessor.java
data-prepper-plugins/key-value-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/keyvalue/KeyValueProcessorTests.java

Fix KeyValue Processor with value grouping enabled causes exception when string literal character is null. Fix is to check if the string literal character is null.

Fix KeyValue Processor value grouping bug

---

release/smoke-tests/otel-span-exporter/requirements.txt

Resolves CVE-2024-35195 by updating Python reqests to 2.32.3.
Resolves #4562

Updates Python requests to 2.32.3 in smoke tests project to address CVE-2024-35195

---

data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateProcessor.java
data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateProcessorConfig.java
data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateProcessorIT.java
data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateProcessorTest.java

Aggrerate processor : add option to allow raw events.
Aggregate processor only sends aggregated events by default. This option allows sending the raw events in addition to the aggregated events.  The aggregated events are tagged to be identify the events separately from the raw events.

Aggrerate processor : add option to allow raw events

---

data-prepper-plugins/opensearch/build.gradle
data-prepper-plugins/otel-trace-raw-processor/build.gradle
data-prepper-plugins/user-agent-processor/build.gradle
data-prepper-plugins/user-agent-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/useragent/CaffeineCachingParser.java
data-prepper-plugins/user-agent-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/useragent/UserAgentProcessor.java
data-prepper-plugins/user-agent-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/useragent/CaffeineCachingParserTest.java
settings.gradle

Adds and uses a Caffeine-based caching parser for the `user_agent` processor. Also, adds a Gradle version catalog for Caffeine since we now use it in three projects.
Resolves #4618

Caffeine-based caching parser for the user_agent processor

---

data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateProcessor.java
data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/CountAggregateAction.java
data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/CountAggregateActionConfig.java
data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/HistogramAggregateAction.java
data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateProcessorStaticFunctionsTest.java
data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/CountAggregateActionTest.java
data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/HistogramAggregateActionTests.java

Add support for start and end times in count and histogram aggregate actions.
Count and Histogram aggregate actions include start and end times based on the real time of aggregation. Adding support to include start and end times based on the times in the event.

Add support for start and end times in count and histogram aggregate actions

---

performance-test/src/gatling/java/org/opensearch/dataprepper/test/performance/tools/Templates.java
performance-test/src/main/java/org/opensearch/dataprepper/test/data/generation/UserAgent.java
performance-test/src/test/java/org/opensearch/dataprepper/test/data/generation/UserAgentTest.java

Adds tools to the performance-test project to generate random User Agent strings. I created this to reproduce #4618 and then verify that the solution I provided in #4619 solved the problem.
Change `Chain::sendApacheCommonLogPostRequest` to:
```
public static ChainBuilder sendApacheCommonLogPostRequest(final String name, final int batchSize) {
return CoreDsl.exec(
HttpDsl.http(name)
.post(PathTarget.getPath())
.body(CoreDsl.StringBody(Templates.userAgent(batchSize))));
}
```
Run:
```
./gradlew :performance-test:gatlingRun-org.opensearch.dataprepper.test.performance.TargetRpsSimulation
```
N/A
For more information on following Developer Certificate of Origin and signing off …

Tools to generate User Agent strings in the performance-test project

---

settings.gradle

Updates to Armeria 1.29.0. This release fixes a bug that is related to #4080.
See https://github.com/line/armeria/issues/5637
N/A

Updates to Armeria 1.29.0 which fixes a bug that may help with #4080.

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/acknowledgements/AcknowledgementSetManager.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/AbstractEventHandle.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/AggregateEventHandle.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/DefaultEventHandle.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/EventHandle.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/InternalEventHandle.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/event/AggregateEventHandleTests.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/event/DefaultEventHandleTests.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/event/JacksonEvent_JavaSerializationTest.java
data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/plugins/InMemorySink.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/acknowledgements/AcknowledgementSetMonitor.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/acknowledgements/DefaultAcknowledgementSet.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/acknowledgements/DefaultAcknowledgementSetManager.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/acknowledgements/InactiveAcknowledgementSetManager.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/ProcessWorker.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/router/RouterCopyRecordStrategy.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/acknowledgements/AcknowledgementSetMonitorTests.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/acknowledgements/DefaultAcknowledgementSetManagerTests.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/acknowledgements/DefaultAcknowledgementSetTests.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/acknowledgements/InactiveAcknowledgementSetManagerTests.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/codec/JavaPeerForwarderCodecTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/PipelineTests.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/ProcessWorkerTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/router/RouterCopyRecordStrategyTests.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/s3/S3SinkServiceTest.java
data-prepper-plugins/split-event-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/splitevent/SplitEventProcessorTest.java

Add Aggregate event handle, for supporting e2e acks for aggregated events (in future)
Cleaned up a lot of API in AcknowledgementSetManager as part of this to simplify the code

Add Aggregate event handle

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/configuration/PluginSetting.java

In #469, we added a POJO-based approach for getting plugin settings. This is more compatible with validations and should be used by all plugins. To help promote this, I submitted this PR to deprecate the `PluginSetting` class. In Data Prepper 3.0, we can move it into data-prepper-core.
N/A

Deprecates PluginSetting which should not be used for plugins anymore.

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/JacksonEventKey.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/event/JacksonEventKeyTest.java

Implements the `equals()`, `hashCode()`, and `toString()` methods for `JacksonEventKey`.
N/A

Implements equals, hashCode, and toString for JacksonEventKey.

---

data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/S3ScanPartitionCreationSupplier.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/s3/S3ScanPartitionCreationSupplierTest.java

This change makes it so that the filtering done between scans for last modified objects, which is used to reduce lookups to the coordination store, is tracked based on the time before the listObjects call to scan for each bucket is made. This will make it impossible to miss items that are uploaded in the middle or end of a scan
Previously attempted to fix with https://github.com/opensearch-project/data-prepper/pull/4124
Original issue: https://github.com/opensearch-project/data-prepper/issues/4123
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTR …

Track last scan time from before scan starts instead of based on last Modified of objects

---

data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/documentdb/DocumentDBService.java
data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/documentdb/MongoTasksRefresher.java
data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/export/MongoDBExportPartitionSupplier.java
data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/stream/CheckpointStatus.java
data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamAcknowledgementManager.java
data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/utils/DocumentDBSourceAggregateMetrics.java
data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/documentdb/MongoTasksRefresherTest.java
data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/export/MongoDBExportPartitionSupplierTest.java
data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamAcknowledgementManagerTest.java

1. Extend the export partition ownership during query partition creation
2. Add support to shutdown task refresher that starts export, stream scheduler and worker
3. Add AcknowledgmentStatus enum and code refactor to fail negative ack right away

DocumentDB Source improvements

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/EventKeyConfiguration.java
data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/integration/ProcessorPipelineIT.java
data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/plugins/SimpleCopyProcessor.java
data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/plugins/SimpleCopyProcessorConfig.java
data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/processor-pipeline.yaml
data-prepper-pipeline-parser/build.gradle
data-prepper-pipeline-parser/src/main/java/org/opensearch/dataprepper/core/validators/NotEmptyValidatorForEventKey.java
data-prepper-pipeline-parser/src/main/java/org/opensearch/dataprepper/pipeline/parser/EventKeyDeserializer.java
data-prepper-pipeline-parser/src/main/resources/META-INF/services/jakarta.validation.ConstraintValidator
data-prepper-pipeline-parser/src/test/java/org/opensearch/dataprepper/core/validators/NotEmptyValidatorForEventKeyTest.java
data-prepper-pipeline-parser/src/test/java/org/opensearch/dataprepper/pipeline/parser/EventKeyDeserializerTest.java
data-prepper-plugin-framework/src/main/java/org/opensearch/dataprepper/plugin/ObjectMapperConfiguration.java
data-prepper-plugin-framework/src/test/java/org/opensearch/dataprepper/plugin/ObjectMapperConfigurationTest.java

Data Prepper core can now parse `EventKey` objects for plugin configurations. Additionally, validation using `@NotEmpty` also works.
Specific changes:
* Adds a deserializer for `EventKey`
* Adds a custom validator for the `@NotEmpty` annotation with `EventKey`.
* Adds a `EventKeyConfiguration` annotation that allows plugin authors to configure how they will use the `EventKey`.
* Integration test updates.
N/A, but this enhances the work done for #1916.

Support plugins defining the EventKey in plugin configurations

---

data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/CountAggregateAction.java
data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/CountAggregateActionConfig.java
data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/HistogramAggregateAction.java
data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/HistogramAggregateActionConfig.java
data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateProcessorIT.java
data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/CountAggregateActionConfigTests.java
data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/CountAggregateActionTest.java
data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/HistogramAggregateActionConfigTests.java
data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/HistogramAggregateActionTests.java

Add support to configure metric name for count and histogram actions

Add support to configure metric name for count and histogram actions

---

data-prepper-plugins/flatten-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/flatten/FlattenProcessor.java
data-prepper-plugins/flatten-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/flatten/FlattenProcessorConfig.java
data-prepper-plugins/flatten-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/flatten/FlattenProcessorConfigTest.java
data-prepper-plugins/flatten-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/flatten/FlattenProcessorTest.java

adds a new option `remove_brackets` to the flatten processor.
```json
{
"key1": {
"key2": [
{
"key3": "value1",
"key4": "value2"
},
{
"key3": "value3",
"key4": "value4"
}
]
}
}
```
transforms to
```json
{
"key1.key2.key3": ["value1", "value3"],
"key1.key2.key4": ["value2", "value4"]
}
```
Resolves #4616

add remove_brackets option to flatten-processor (#4616)

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/JacksonEvent.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/JacksonEventKey.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/event/JacksonEventKeyTest.java

With the addition of the `EventKey` (see #1916), `JacksonEvent` always creates a `JacksonEventKey` in order to use the same code for all paths. However, when put/delete calls are made with a String key, `JacksonEvent` does not need the JSON Pointer. But, it is created anyway. This adds more work to the put/delete calls that have not yet migrated to the String version. 
This fixes regression by adding a lazy initialization option when used in `JacksonEvent`. We should not be lazy when used with the `EventKeyFactory` since we may lose some up-front validations.
N/A …

Fixes performance regression with JacksonEvent put/delete operations.

---

data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/source/KafkaSource.java

Fix the log level for printing out consumer properties in kafka source

MAINT: change log level for consumer properties in kafka source

---

data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/CountAggregateAction.java
data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/CountAggregateActionConfig.java
data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/CountAggregateActionConfigTests.java
data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/CountAggregateActionTest.java

Add an option to count unique values of specified key(s) to CountAggregateAction
Resolves #4644
Resolves #4644 

Add an option to count unique values of specified key(s) to CountAggregateAction

---

data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaCustomConsumerFactory.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/source/KafkaSource.java

Follow up on #4658 , to prevent accidental leakage, we completely remove the logs that include consumer properties in kafka

FIX: remove logging that includes credential info on kafka

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/PeerForwardingProcessorDecorator.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/PeerForwardingProcessingDecoratorTest.java

Running a trace analytics pipeline with the `service_map` processor was not working when the pipeline has multiple workers. This PR fixes that bug.
The approach here is to revert the following change to go back to what we had before.
https://github.com/opensearch-project/data-prepper/pull/4574/files#diff-82ab126c928e8f6c33e33fcdca6015c436d7df3870b9b420880f669cce2c8681R71-R76
However, now the `register` API takes in a processor. Upon inspection of the code, the `List<Processor>` in the decorate method are all the same plugin - it is just that we may have multiple instances due to the `@SingleThread` annotation. This results in multiple instances of the same thing. 
This code already gets the first instance as an exemplar. See this line: …

Fixes the loading of peer-forwarders when using multiple workers

---

data-prepper-plugins/http-source-common/src/main/java/org/opensearch/dataprepper/http/codec/JsonCodec.java
data-prepper-plugins/http-source-common/src/test/java/org/opensearch/dataprepper/http/codec/JsonCodecTest.java

The `JsonCodec` has code to split input requests to keep under a certain size. However, this chunking currently counts character length, not byte size. This PR corrects that behavior by comparing the byte size.
I added a unit test to verify this:
Before changing the code, I was able to verify that this failed with Unicode input.
```
JsonCodecTest > parse_should_return_lists_smaller_than_provided_length(String, String) > [1] [{"ὊὊὊ1":"ὊὊὊ1"}, {"ὊὊὊ2":"ὊὊὊ2"}, {"a3":"b3"}, {"ὊὊὊ4":"ὊὊὊ4"}], {"ὊὊὊ1":"ὊὊὊ1"} FAILED
java.lang.AssertionError at JsonCodecTest.java:81
```
N/A …

Updates the chunking algorithm for http source to account for Unicode

---

data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/integration/Router_ThreeRoutesDefaultIT.java
data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/route/three-route-with-default-route.yaml
data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/router/DataFlowComponentRouter.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/router/DataFlowComponentRouterTest.java

Support default route option for Events that match no other route.
Currently DataPrepper doesn't have a away to forward event when none of the routes match. Users are expected to explicitly write a route for negation of all the other routes. This feature would allow events not matching any routes to be routed using "_default" route in sink config.
Resolves #4615 

Support default route option for Events that match no other route

---

TRIAGING.md

This PR adds the `TRIAGING.md` file which we will use to guide our existing triage meetings. This is part of our goal of making our triage meetings open to the community.
N/A

Adds the TRIAGING.md file to outline our triaging process

---

data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/RdsService.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/RdsSource.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/coordination/PartitionFactory.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/coordination/partition/ExportPartition.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/coordination/partition/GlobalState.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/coordination/partition/LeaderPartition.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/coordination/state/ExportProgressState.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/coordination/state/LeaderProgressState.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/export/ExportScheduler.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/export/ExportTaskManager.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/export/SnapshotManager.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/leader/LeaderScheduler.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/model/ExportStatus.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/model/SnapshotInfo.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/model/SnapshotStatus.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/RdsServiceTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/coordination/PartitionFactoryTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/export/ExportSchedulerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/export/ExportTaskManagerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/export/SnapshotManagerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/leader/LeaderSchedulerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/model/ExportStatusTest.java
shared-config/log4j2.properties

Adds the basic ability to export tables from RDS to S3. Follows a similar pattern to DynamoDB/DocumentDB source that the leader node creates ExportPartition in coordination store and the node that picks up the ExportPartition will call RDS APIs to take snapshot and export it to S3.
There will be a follow-up PR to process the S3 files in the rds source. This PR only targets RDS instances, will add support for RDS/Aurora clusters in separate PRs (the RDS APIs for instances and clusters are different). 
Created RDS MySQL instance as source and created a DDB table as coordination store and tested with the following pipeline config and verified that the data is exported to S3.
```
rds-mysql-pipeline:
source:
rds:
db_identifier: "mysql-instance"
table_names:
- "my_db.cars"
- "my_db.houses" …
```

Export to S3 in RDS source

---

data-prepper-api/build.gradle
data-prepper-plugins/avro-codecs/build.gradle
data-prepper-plugins/common/build.gradle
data-prepper-plugins/csv-processor/build.gradle
data-prepper-plugins/event-json-codecs/build.gradle
data-prepper-plugins/newline-codecs/build.gradle
data-prepper-plugins/parquet-codecs/build.gradle
data-prepper-plugins/parse-json-processor/build.gradle
data-prepper-plugins/s3-sink/build.gradle
data-prepper-plugins/s3-source/build.gradle
settings.gradle

Updates Parquet to 1.14.1 and Hadoop to 3.4.0. Use the Gradle version catalogue for Parquet to simplify future version updates.
This also updates the shaded jar versions.
```
|    |    |    +--- org.apache.hadoop.thirdparty:hadoop-shaded-protobuf_3_21:1.2.0
|    |    |    +--- org.apache.hadoop.thirdparty:hadoop-shaded-guava:1.2.0
```
Protobuf 3.21 resolves CVE-2022-3510.
None. But, this is related to #4612.

Parquet 1.14.1 and Hadoop 3.4.0

---

data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parse/AbstractParseProcessor.java
data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parse/CommonParseConfig.java
data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parse/ion/ParseIonProcessorConfig.java
data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parse/json/ParseJsonProcessorConfig.java
data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parse/xml/ParseXmlProcessorConfig.java
data-prepper-plugins/parse-json-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/parse/ion/ParseIonProcessorConfigTest.java
data-prepper-plugins/parse-json-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/parse/ion/ParseIonProcessorTest.java
data-prepper-plugins/parse-json-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/parse/json/ParseJsonProcessorConfigTest.java
data-prepper-plugins/parse-json-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/parse/json/ParseJsonProcessorTest.java
data-prepper-plugins/parse-json-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/parse/xml/ParseXmlProcessorConfigTest.java
data-prepper-plugins/parse-json-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/parse/xml/ParseXmlProcessorTest.java

Introducing delete input configuration option for some parsers
Read about this fix [here](https://github.com/opensearch-project/data-prepper/issues/3968)
Example pipeline yaml configuration will be 
```
simple-sample-pipeline:
source:
file:
path: /tmp/input-file
record_type: event
processor:
- parse_json:
delete_source: false
- convert_entry_type:
key: "my_number_ending_in_0"
type: "big_decimal"
scale: 1
sink:
- stdout:
```
Resolves #3968 

Introducing delete input configuration option for some parsers

---

data-prepper-plugins/user-agent-processor/build.gradle
data-prepper-plugins/user-agent-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/useragent/UserAgentProcessor.java
data-prepper-plugins/user-agent-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/useragent/UserAgentProcessorConfig.java
data-prepper-plugins/user-agent-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/useragent/UserAgentProcessorTest.java

This draft PR updates the `user_agent` processor to use the `EventKey`. It depends on changes from #4627, so this is a draft PR for now.
N/A

Updates the user_agent processor to use the EventKey.

---

data-prepper-plugins/parquet-codecs/build.gradle
data-prepper-plugins/s3-sink/build.gradle
data-prepper-plugins/s3-source/build.gradle

Excludes the Zookeeper dependency from Hadoop. This removes it from Data Prepper entirely. Also, exclude Jetty from Hadoop as a transitive dependency. We still rely on Jetty for other projects, but it is no longer being pulled from Hadoop.
N/A

Removes Zookeeper from Data Prepper

---

data-prepper-plugins/mutate-event-processors/build.gradle
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/DeleteEntryProcessor.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/DeleteEntryProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/RenameKeyProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/test/java/org/opensearch/dataprepper/plugins/processor/mutateevent/DeleteEntryProcessorTests.java
data-prepper-plugins/mutate-event-processors/src/test/java/org/opensearch/dataprepper/plugins/processor/mutateevent/RenameKeyProcessorTests.java

This PR builds on the work in #4627 and #4635 to support the `EventKey` in the `rename_keys` and `delete_entries` processors.
Additionally, it checks for not empty and not null on entries in the `delete_entries` processor. This was probably intended, but not actually verified.
This depends on #4635 to be merged first. I'm creating this as a draft PR for now.
N/A

Update the rename_keys and delete_entries processors to use EventKey

---

data-prepper-plugins/common/src/main/java/org/opensearch/dataprepper/plugins/processor/StringProcessor.java

This PR serves as the starter for backfill [plugin setting config table](https://opensearch.org/docs/latest/data-prepper/pipelines/configuration/processors/string-converter/) into @JsonPropertyDescription so that a complete json schema can be generated.

MAINT: backfill documentation into json description for string_converter

---

data-prepper-plugins/otel-trace-raw-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/oteltrace/OtelTraceRawProcessorConfig.java

This PR serves as the starter for backfill [plugin setting config table](https://opensearch.org/docs/latest/data-prepper/pipelines/configuration/processors/otel-trace-raw/#configuration) into @JsonPropertyDescription so that a complete json schema can be generated.

MAINT: backfill documentation in json description for otel_traces

---

data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/DeleteEntryProcessorConfig.java
settings.gradle

This PR serves as the starter for backfill [plugin setting config table](https://opensearch.org/docs/latest/data-prepper/pipelines/configuration/processors/delete_entries) into @JsonPropertyDescription so that a complete json schema can be generated.

MAINT: backfill documentation into json description for delete_entries

---

data-prepper-plugins/mutate-string-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutatestring/SubstituteStringProcessorConfig.java

This PR serves as the starter for backfill [plugin setting config table](https://opensearch.org/docs/latest/data-prepper/pipelines/configuration/processors/substitute-string/#configuration) into @JsonPropertyDescription so that a complete json schema can be generated.

MAINT: backfill documentation into json property for substitute_string

---

data-prepper-plugins/truncate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/truncate/TruncateProcessorConfig.java

This PR serves as the starter for backfill [plugin setting config table](https://opensearch.org/docs/latest/data-prepper/pipelines/configuration/processors/truncate/#configuration) into @JsonPropertyDescription so that a complete json schema can be generated.

MAINT: backfill documentation into json description for truncate processor

---

build.gradle
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/sink/AbstractSink.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/sink/SinkThread.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/sink/AbstractSinkTest.java
data-prepper-core/build.gradle
data-prepper-plugins/avro-codecs/src/test/java/org/opensearch/dataprepper/avro/AvroAutoSchemaGeneratorTest.java
data-prepper-plugins/blocking-buffer/src/test/java/org/opensearch/dataprepper/plugins/buffer/blockingbuffer/BlockingBufferTests.java
data-prepper-plugins/event-json-codecs/src/test/java/org/opensearch/dataprepper/plugins/codec/event_json/EventJsonInputCodecTest.java
data-prepper-plugins/event-json-codecs/src/test/java/org/opensearch/dataprepper/plugins/codec/event_json/EventJsonInputOutputCodecTest.java
data-prepper-plugins/event-json-codecs/src/test/java/org/opensearch/dataprepper/plugins/codec/event_json/EventJsonOutputCodecTest.java
gradle/wrapper/gradle-wrapper.properties
gradlew

While debugging a test recently, I noticed that the Java 17 test reports a basic `java.lang.NullPointerException`. Java 17 provides better NPE information that Java 11. It turns out that the tests are actually running against Java 11 entirely. Even in our matrix tests, these run on Java 11.
This PR uses the current JVM versions (ie. what Gradle is running on) to execute the Java tests. This way, our tests will test actually test against other Java versions.
Also, I updated the Gradle 8.8 because `JavaLanguageVersion.current()` was added in 8.8.
I created a simple test to prove this:
```
public class QuickFail {
@Test
void fails() {
A a = new A();
B b = new B();
a.b.c.doSomething();
}
static class A {
B b;
}
static class B {
C c;
}
static class C {
void doSomething() {}
}
}
```
Running on …

Run tests on the current JVM / Gradle 8.8

---

data-prepper-plugins/otel-metrics-raw-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/otelmetrics/OtelMetricsRawProcessorConfig.java

This PR serves as the starter for backfill [plugin setting config table](https://opensearch.org/docs/latest/data-prepper/pipelines/configuration/processors/otel-metrics/#configuration) into @JsonPropertyDescription so that a complete json schema can be generated.

MAINT: backfill doc in json property description for otel_metrics

---

data-prepper-plugins/mutate-string-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutatestring/SplitStringProcessorConfig.java

This PR serves as the starter for backfill [plugin setting config table](https://opensearch.org/docs/latest/data-prepper/pipelines/configuration/processors/split-string) into @JsonPropertyDescription so that a complete json schema can be generated.

MAINT: backfill documentation in JsonPropertyDescription for split_string

---

data-prepper-plugins/mutate-string-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutatestring/WithKeysConfig.java

This PR serves as the starter for backfill [plugin setting config table](https://opensearch.org/docs/latest/data-prepper/pipelines/configuration/processors/trim-string/) into @JsonPropertyDescription so that a complete json schema can be generated.

MAINT: backfill doc into json property for trim_string

---

data-prepper-plugins/rds-source/build.gradle
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/ClientFactory.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/RdsService.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/RdsSource.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/converter/ExportRecordConverter.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/converter/MetadataKeyAttributes.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/coordination/PartitionFactory.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/coordination/partition/DataFilePartition.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/coordination/state/DataFileProgressState.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/export/DataFileLoader.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/export/DataFileScheduler.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/export/ExportScheduler.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/export/S3ObjectReader.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/model/ExportObjectKey.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/model/LoadStatus.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/RdsServiceTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/RdsSourceTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/converter/ExportRecordConverterTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/export/DataFileLoaderTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/export/DataFileSchedulerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/export/ExportSchedulerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/export/S3ObjectReaderTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/model/ExportObjectKeyTest.java
shared-config/log4j2.properties

Following #4664, process the parquet files exported to S3, create events and send to buffer.
Created RDS MySQL instance as source and created a DDB table as coordination store and tested with the following pipeline config and verified the data written to the file sink.
```
rds-mysql-pipeline:
source:
rds:
db_identifier: "mysql-instance"
table_names:
- "my_db.cars"
- "my_db.houses"
s3_bucket: "rds-data-oeyh"
s3_region: "us-east-1"
s3_prefix: "rds-source-test"
export:
kms_key_id: xxxxxx
aws:
sts_role_arn: "arn:aws:iam::xxxxxxxxxxxxx:role/rdsSourcePipelineRole"
sink:
- file:
path: .../.../results.txt
```
Contributes to https://github.com/opensearch-project/data-prepper/issues/4561
By submitting this pull request, I confirm that my contribution is made under the terms of …

Load exported S3 files in RDS source

---

data-prepper-plugins/grok-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/grok/GrokProcessor.java
data-prepper-plugins/grok-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/grok/GrokProcessorConfig.java
data-prepper-plugins/grok-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/grok/GrokProcessorConfigTests.java
data-prepper-plugins/grok-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/grok/GrokProcessorIT.java
data-prepper-plugins/grok-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/grok/GrokProcessorTests.java

This PR 
* refactors grok processor to use latest config model
* backfill plugin config table in the documentation into @JsonPropertyDescription in GrokProcessorConfig

REF: grok processor with the latest config model

---

data-prepper-plugins/date-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/date/DateProcessorConfig.java

This PR serves as the starter for backfill [plugin setting config table](https://opensearch.org/docs/latest/data-prepper/pipelines/configuration/processors/date/#configuration) into @JsonPropertyDescription so that a complete json schema can be generated.

MAINT: add documentation in json property description for date processor

---

data-prepper-plugins/service-map-stateful/build.gradle
data-prepper-plugins/service-map-stateful/src/main/java/org/opensearch/dataprepper/plugins/processor/ServiceMapProcessorConfig.java
data-prepper-plugins/service-map-stateful/src/main/java/org/opensearch/dataprepper/plugins/processor/ServiceMapStatefulProcessor.java
data-prepper-plugins/service-map-stateful/src/test/java/org/opensearch/dataprepper/plugins/processor/ServiceMapProcessorConfigTest.java
data-prepper-plugins/service-map-stateful/src/test/java/org/opensearch/dataprepper/plugins/processor/ServiceMapStatefulProcessorTest.java

This PR
* refactors service-map processor to use latest config model
* backfill plugin config table in the documentation into @JsonPropertyDescription in ServiceMapProcessorConfig

REF: service-map processor with the latest config model

---

build.gradle

Updates Jackson to 2.17.2. This is motivated by consistency. See the discussion in #4729.
Related to #4729.

Updates Jackson to 2.17.2. Related to #4729.

---

data-prepper-plugins/key-value-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/keyvalue/KeyValueProcessorConfig.java

This PR serves as the starter for [plugin config table](https://opensearch.org/docs/latest/data-prepper/pipelines/configuration/processors/key-value/) into @JsonPropertyDescription so that a complete JSON schema can be generated for the Key-Value Processor.

MAINT: add json property descriptions for kv configs

---

data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/SqsService.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/SqsWorker.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/parser/ParsedMessage.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/parser/SqsMessageParser.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/s3/SqsWorkerTest.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/s3/parser/ParsedMessageTest.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/s3/parser/S3EventBridgeNotificationParserTest.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/s3/parser/S3EventNotificationParserTest.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/s3/parser/SqsMessageParserTest.java

Improve the SQS shutdown process such that it does not prevent the pipeline from shutting down and no longer results in failures. 
The previous approach to shutting down the SQS thread closed the SqsClient. However, with acknowledgments enabled, asynchronous callbacks would result in further attempts to either ChangeVisibilityTimeout or DeleteMessages. These were failing because the client was closed. Also, the threads would remain and prevent Data Prepper from correctly shutting down. With this change, we correctly stop each processing thread. Then we close the client. Additionally, the SqsWorker now checks that it is not stopped before attempting to change the message visibility or delete messages.
Additionally, I found some missing test cases. Also, modifying this code and especially …

Correct SQS shutdown to avoid crashes

---

data-prepper-plugins/csv-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/csv/CsvProcessorConfig.java

This PR serves as the starter for [plugin config table](https://opensearch.org/docs/latest/data-prepper/pipelines/configuration/processors/csv/) into @JsonPropertyDescription so that a complete JSON schema can be generated for the CSV Processor. Also added documentation for `csv_when` config.

MAINT: Add json property descriptions for csv processor

---

data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/AddEntryProcessorConfig.java

Add json description to AddEntry processor
N/A

MAINT: Add json description to AddEntry processor

---

data-prepper-plugins/rds-source/build.gradle
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/RdsService.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/RdsSource.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/RdsSourceConfig.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/configuration/StreamConfig.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/converter/MetadataKeyAttributes.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/converter/S3PartitionCreator.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/converter/StreamRecordConverter.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/coordination/PartitionFactory.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/coordination/partition/GlobalState.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/coordination/partition/StreamPartition.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/coordination/state/StreamProgressState.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/export/DataFileScheduler.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/leader/LeaderScheduler.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/model/BinlogCoordinate.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/model/TableMetadata.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/BinlogClientFactory.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/BinlogEventListener.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/StreamScheduler.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/StreamWorker.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/converter/S3PartitionCreatorTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/converter/StreamRecordConverterTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/stream/BinlogClientFactoryTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/stream/BinlogEventListenerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/stream/StreamSchedulerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/stream/StreamWorkerTest.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/ScanObjectWorker.java

Add stream processing for rds source:
- Uses `BinaryLogClient` to get change events and process the events based on insert/update/delete types
- The binlog events are then converted to JacksonEvents and attached with metadata before sending to buffer
Smoked tested in some Data Prepper pipelines and verified it's working as expected.
<details>
<summary>Test pipeline config example</summary>
```yaml
rds-mysql-pipeline:
source:
rds:
db_identifier: "mysql-multiaz-instance"
table_names:
- "my_db.cars"
s3_bucket: "aurora-datasets-oeyh"
s3_region: "us-east-1"
s3_prefix: "rds-stream-test"
export:
kms_key_id: xxx
stream:
partition_count: 8
aws:
sts_role_arn: "arn:aws:iam::xxx:role/rdsSourcePipelineRole"
authentication:
username: ${{aws_secrets:secret:username}}
password: …
```

Add stream processing for rds source

---

data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/RdsService.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/RdsSourceConfig.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/export/ClusterSnapshotStrategy.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/export/ExportScheduler.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/export/InstanceSnapshotStrategy.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/export/SnapshotManager.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/export/SnapshotStrategy.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/export/ClusterSnapshotStrategyTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/export/ExportSchedulerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/export/InstanceSnapshotStrategyTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/export/SnapshotManagerTest.java

There are 2 sets of RDS APIs for snapshots:
- For RDS instances: `CreateDBSnapshot` and `DescribeDBSnapshots`
- For RDS/Aurora clusters: `CreateDBClusterSnapshot` and `DescribeDBClusterSnapshots`
This PR adds support for the clusters:
- Adds strategy interface and implementations for both APIs
- Refactors SnapshotManager to use SnapshotStrategy
- Refactors ExportSchedulerTest to make it simpler
Tested pipelines against RDS instance and Aurora cluster, both worked.
Contributes to https://github.com/opensearch-project/data-prepper/issues/4561 …

Add support for RDS/Aurora clusters in rds source

---

data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/HistogramAggregateAction.java
data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/HistogramAggregateActionTests.java

Fixes a bug with `HistogramAggregateAction` where the startTime may be incorrect. This was discovered by a [flaky test](https://github.com/opensearch-project/data-prepper/issues/3481#issuecomment-2207244965).
The `HistogramAggregateAction` was incorrectly using the current time as the start time for the aggregation when creating the group. The very first event's time was overridden by the current system time. If this event had the earliest time, then the overall histogram would never get the correct start time. This is fixed by removing an errant line. I also added a unit test to directly test this failure scenario.
Additionally, I cleaned up some code in the tests and main source.
N/A
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …

Fixes HistogramAggregateAction startTime

---

TRIAGING.md

The current text says "Zoom meeting," but we actually use Chime. I changed this to "video meeting" so that we don't have to keep changing it. We'll have the meeting information in the Meetup.
N/A

Corrects the TRIAGING.md with a video meeting text

---

build.gradle
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/sink/AbstractSink.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/sink/SinkThread.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/sink/AbstractSinkTest.java
data-prepper-core/build.gradle
data-prepper-plugins/avro-codecs/src/test/java/org/opensearch/dataprepper/avro/AvroAutoSchemaGeneratorTest.java
data-prepper-plugins/blocking-buffer/src/test/java/org/opensearch/dataprepper/plugins/buffer/blockingbuffer/BlockingBufferTests.java
data-prepper-plugins/event-json-codecs/src/test/java/org/opensearch/dataprepper/plugins/codec/event_json/EventJsonInputCodecTest.java
data-prepper-plugins/event-json-codecs/src/test/java/org/opensearch/dataprepper/plugins/codec/event_json/EventJsonInputOutputCodecTest.java
data-prepper-plugins/event-json-codecs/src/test/java/org/opensearch/dataprepper/plugins/codec/event_json/EventJsonOutputCodecTest.java
gradle/wrapper/gradle-wrapper.properties
gradlew

This reapplies a commit needed to run tests on Java 17 and 21.
Original PR: #4730
PR which reverted: #4762
N/A

Reapply "Run tests on the current JVM for Java 17 & 21 / Gradle 8.8

---

data-prepper-plugins/rds-source/build.gradle
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/RdsService.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/RdsSourceConfig.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/export/DataFileLoader.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/export/DataFileScheduler.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/export/ExportScheduler.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/BinlogEventListener.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/StreamScheduler.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/export/DataFileLoaderTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/export/DataFileSchedulerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/export/ExportSchedulerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/stream/BinlogEventListenerTest.java

Adds the following rds source metrics, named to be consistent with dynamodb and documentdb source metrics:
* exportJobSuccess
* exportJobFailure
* exportS3ObjectsTotal
* exportS3ObjectsProcessed
* exportRecordsTotal 
* exportRecordsProcessed
* exportRecordsProcessingErrors
* activeExportS3ObjectConsumers
* changeEventsProcessed
* changeEventsProcessingErrors
* bytesReceived
* bytesProcessed

Add rds source metrics

---

.github/CODEOWNERS

The release is blocked because @asifsmohammed is not currently in the team. We can add him back after he accepts an invitation. For now, I'm removing him to allow us to release.
N/A

Removes @asifsmohammed from the CODEOWNERS

---

data-prepper-plugins/log-generator-source/src/test/java/org/opensearch/dataprepper/plugins/source/loggenerator/LogGeneratorSourceTest.java

We had a test failure in `LogGeneratorSourceTest`. This is probably a timing issue as I see it relies on sleeping.
See: https://github.com/opensearch-project/data-prepper/issues/3481#issuecomment-2231886745
This PR attempts to avoid this primarily by using Awaitility. This generally allows better reliability as we can increase values to allow for delays when running, especially on GitHub. Additionally, this test was using a spy for the `Buffer` when no logic was needed. So I simplified it a bit to use a normal mock.
N/A …

Using Awaitility and mocks in the LogGeneratorSourceTest

---

data-prepper-plugins/rds-source/build.gradle
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/RdsService.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/coordination/state/DataFileProgressState.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/coordination/state/ExportProgressState.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/export/DataFileLoader.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/export/ExportScheduler.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/export/SnapshotManager.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/leader/ClusterApiStrategy.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/leader/InstanceApiStrategy.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/leader/LeaderScheduler.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/leader/RdsApiStrategy.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/model/DbMetadata.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/schema/ConnectionManager.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/schema/SchemaManager.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/BinlogClientFactory.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/StreamWorker.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/RdsServiceTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/export/ClusterSnapshotStrategyTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/export/InstanceSnapshotStrategyTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/export/SnapshotManagerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/leader/ClusterApiStrategyTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/leader/InstanceApiStrategyTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/leader/LeaderSchedulerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/schema/ConnectionManagerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/schema/SchemaManagerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/stream/BinlogClientFactoryTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/stream/StreamWorkerTest.java

This PR implements a few follow-up items from previous PRs:
- Get host/port from RDS when source starts and use it in mysql client and binlog client.
- Add SchemaManage to query MySQL to:
- get primary keys from MySQL and save it in ExportPartition for export record converter to use
- get binlog position at the beginning, save it in StreamPartition, and use it as the starting position for streaming
- Refactor SnapshotStrategy to a more general RdsApiStrategy to include describeDb APIs (describeDBInstances and describeDBClusters)
Tested Data Prepper against RDS instance and verified that both export and stream work as expected. Particularly, new data changes to RDS while export is in progress were captured when stream started.
By submitting this pull request, I …

Several improvements to RDS source

---

data-prepper-plugin-schema-cli/README.md
data-prepper-plugin-schema-cli/src/main/java/org/opensearch/dataprepper/schemas/DataPrepperPluginSchemaExecute.java

This PR allows folder path as output for schema generation

ENH: add folder path as output for schema generation

---

data-prepper-plugins/service-map-stateful/src/main/java/org/opensearch/dataprepper/plugins/processor/ServiceMapStatefulProcessor.java
data-prepper-plugins/service-map-stateful/src/test/java/org/opensearch/dataprepper/plugins/processor/ServiceMapStatefulProcessorTest.java

This PR fixes service-map on building relationship even when traceGroupName is missing so that user can still find service relations when the upstream service instrumentation info is missing
Resolves #4821 

FIX: build service map relationship even when trace group is missing

---

data-prepper-plugins/csv-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/csv/CsvProcessor.java
data-prepper-plugins/csv-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/csv/CsvProcessorConfig.java
data-prepper-plugins/csv-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/csv/CsvProcessorTest.java

Similar to https://github.com/opensearch-project/data-prepper/pull/4702, this change adds the `delete_source` option to remove the `source` from the Event after it is processed with the csv processor

Add delete_source parameter to the csv processor

---

data-prepper-plugins/parse-json-processor/build.gradle
data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parse/ion/ParseIonProcessor.java
data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parse/json/ParseJsonProcessor.java
data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parse/xml/ParseXmlProcessor.java

Do not include the stack trace since it doesn't provide any value with these exceptions which are expected when the JSON is invalid. Log the input string rather than the Event which was not readable.
N/A

Logging improvements when failing to parse JSON/XML/ION. 

---

data-prepper-expression/src/main/java/org/opensearch/dataprepper/expression/StartsWithExpressionFunction.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/ContainsExpressionFunctionTest.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/GenericExpressionEvaluator_ConditionalIT.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/StartsWithExpressionFunctionTest.java

Adds a `startsWith` function to Data Prepper expressions, similar to the `contains` function, but for checking if a String has a prefix of some other String.

Add startsWith expression function

---

data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parse/AbstractParseProcessor.java
data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parse/ion/ParseIonProcessor.java
data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parse/json/ParseJsonProcessor.java
data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parse/xml/ParseXmlProcessor.java
data-prepper-plugins/parse-json-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/parse/ion/ParseIonProcessorTest.java
data-prepper-plugins/parse-json-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/parse/json/ParseJsonProcessorTest.java
data-prepper-plugins/parse-json-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/parse/xml/ParseXmlProcessorTest.java

Updates the `parse_json`, `parse_ion`, and `parse_xml` processors to use `EventKey`.
I also pushed #4843 that adds a caching `EventKeyFactory`. With those changes, I'm seeing better performance in the `parse_json` processor.
**Before using Event Key**
**After using Event Key**
N/A

Update the parse JSON/XML/ION processors to use EventKey.

---

data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/ScanObjectWorker.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/s3/S3ScanObjectWorkerTest.java

There is a potential race condition where an S3 source folder partition can receive an acknowledgment callback at the same time as the partition is being updated for the acknowledgment wait, leading to failure to give up the folder partition. This results in objects not being processed from this folder until the acknowledgment timeout is hit, which is currently set to 2 hours

Fix bug where race condition on ack callback could cause S3 folder partition to not be given up

---

data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/leader/LeaderScheduler.java

If the source coordination store has a dependency failure (i.e. 5xx from DynamoDB), then the `LeaderScheduler` thread crashes and will not continue shard discovery on the node, causing single-node pipelines to stop processing. 
Resolves #4775 

Catch error that could cause LeaderScheduler thread to crash

---

data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/SqsWorker.java

The change fixes the visibility timeout errors by creating acknowledgement sets for all the messages from a SQS ReceiveMessage call before additional processing. 
Resolves #4812

Fix visibility timeout errors (#4812)

---

release/archives/build.gradle

Removes the `trace-analytics-sample-app` from release examples directory when creating the archive and Docker images that we release.
The motivation for removing this is that the samples pull in dependencies which often trigger CVE reports. It is not likely customers are trying to run this example from a Data Prepper deployment, especially since the example is not made to run from the installed version, but runs from Docker and runs using the latest 2.x version.
```
./gradlew --parallel clean :release:docker:docker
```
Then:
```
docker run opensearch-data-prepper:2.10.0-SNAPSHOT ls /usr/share/data-prepper/examples
```
```
adot
aws
certificates
config
data-prepper-config.yaml
demo
dev
jaeger-hotrod
log-ingestion
log-ingestion-ecs-firelens
log-ingestion-fluentd
log-ingestion-k8s …
```

Removes the trace-analytics-sample-app from release examples directory

---

build.gradle

The Hadoop project pulls in dnsjava 3.4.0. This has a CVE against it: CVE-2024-25638.
Updates to dnsjava 3.6.1
None, but fixes CVE-2024-25638.

Require dnsjava 3.6.1 to resolve CVE-2024-25638

---

build.gradle
settings.gradle

* Update Spring to 5.3.39 to fix CVE-2024-38808. 
* Require commons-configuration2 2.11.0 to fix CVE-2024-29131 and CVE-2024-29133. Hadoop pulls this dependency in.
None
Fixes CVEs:
* CVE-2024-38808
* CVE-2024-29131
* CVE-2024-29133

CVE fixes from Spring expression and commons-configuration2

---

data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamAcknowledgementManager.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/RdsService.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/RdsSource.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/RdsSourceConfig.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/coordination/state/StreamProgressState.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/export/DataFileLoader.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/export/DataFileScheduler.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/leader/LeaderScheduler.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/model/BinlogCoordinate.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/BinlogEventListener.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/ChangeEventStatus.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/RowChangeEventStatus.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/StreamCheckpointManager.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/StreamCheckpointer.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/StreamScheduler.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/StreamWorker.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/RdsServiceTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/RdsSourceTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/export/DataFileLoaderTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/export/DataFileSchedulerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/stream/BinlogEventListenerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/stream/StreamCheckpointManagerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/stream/StreamCheckpointerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/stream/StreamSchedulerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/stream/StreamWorkerTest.java

This PR adds:
- e2e acknowledgment to export processing
-  e2e acknowledgment and checkpointing to stream processing

Add e2e acknowledgment and checkpointing to RDS source

---

data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/RdsService.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/RdsSourceConfig.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/converter/StreamRecordConverter.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/model/ExportObjectKey.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/StreamScheduler.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/export/ExportSchedulerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/model/ExportObjectKeyTest.java

- Sets external origination time for stream events to enable end to end latency metric
- Adds a config to allow disabling primary stream node from doing S3 scan work
- Fixes a bug with parsing ExportObjectKey
- Fixes an NPE when getting TlsConfig
N/A

Minor updates and bug fixes for RDS source

---

data-prepper-plugin-schema/src/main/java/org/opensearch/dataprepper/schemas/JsonSchemaConverter.java
data-prepper-plugin-schema/src/test/java/org/opensearch/dataprepper/schemas/JsonSchemaConverterTest.java
data-prepper-plugins/grok-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/grok/GrokProcessorConfig.java

with this change, defaultValue in JsonProperty will be respected in result json schema as long as it is non-empty:
```
"timeout_millis" : {
"type" : "integer",
"description" : "The maximum amount of time during which matching occurs. Setting to `0` prevents any matching from occurring. Default is `30,000`.",
"default" : "30000"
},
```

ENH: respect JsonProperty defaultValue in JsonSchemaConverter

---

RELEASING.md
docs/developer_guide.md

This adds instructions for the release setup so that maintainers can have a consistent set of instructions to follow. Specifically, it adds steps for setting up the branch, updating version numbers, creating the release notes and change log.
Additionally, this fixes a broken fragment link to the Backporting section of the Developer Guide.
N/A

Updating the instructions for releasing a new version of Data Prepper.

---

.github/workflows/kafka-plugin-integration-tests.yml
data-prepper-plugins/kafka-plugins/src/integrationTest/java/org/opensearch/dataprepper/plugins/kafka/KafkaStartIT.java
data-prepper-plugins/kafka-plugins/src/integrationTest/java/org/opensearch/dataprepper/plugins/kafka/buffer/KafkaBufferIT.java
data-prepper-plugins/kafka-plugins/src/integrationTest/java/org/opensearch/dataprepper/plugins/kafka/buffer/KafkaBuffer_KmsIT.java
data-prepper-plugins/kafka-plugins/src/integrationTest/java/org/opensearch/dataprepper/plugins/kafka/buffer/ReadBufferHelper.java

The current tests for `KafkaBufferIT` and `KafkaBuffer_KmsIT` wait on the buffer in a single call. These tests are flaky with Kafka 2.8.1. I found that there are transient errors happening here. But, 10 seconds may not be enough time for these errors.
So I've updated these tests to use awaitility. The tests can wait up to 20 seconds, but each call only waits half a second, so the tests are little faster overall.
I'm seeing that the tests against 2.8.1 are working well now.
Contributes toward #4168
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTR …

Use awaitility to read data in Kafka buffer tests to fix flakiness

---

testing/aws-testing-cdk/bin/aws-testing-cdk.ts
testing/aws-testing-cdk/lib/s3/S3SinkStack.ts

The `S3SinkStack` was not in use and didn't quite work. This corrects it so that we can use it to automate the tests for the S3 sink in GitHub.
```
export AWS_REGION=us-east-2
cdk deploy --all --context dataPrepperOrganization=MYORG --context gitHubOidcProviderExists=true
```
Then test:
```
./gradlew :data-prepper-plugins:s3-sink:integrationTest -Dtests.s3sink.region=us-east-2 -Dtests.s3sink.bucket=s3sinkstack-s3sinkbucketUUID
```
N/A

Corrects the S3SinkStack for AWS testing

---

data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/configuration/StreamConfig.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/BinlogEventListener.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/stream/BinlogEventListenerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/stream/StreamSchedulerTest.java

Move event processing to separate threads and add event processing timer in RDS source. This will help with performance testing.
N/A

Move event processing to separate threads and add event processing timer in RDS source

---

data-prepper-plugins/http-source-common/src/main/java/org/opensearch/dataprepper/http/codec/Codec.java
data-prepper-plugins/http-source-common/src/main/java/org/opensearch/dataprepper/http/codec/JsonCodec.java
data-prepper-plugins/http-source-common/src/test/java/org/opensearch/dataprepper/http/codec/JsonCodecTest.java
data-prepper-plugins/http-source/src/main/java/org/opensearch/dataprepper/plugins/source/loghttp/LogHTTPService.java

This refactors the code by placing all logic for serializing the data into the Codec itself. In so doing, it allows for improved testing such as symmetric testing. It also decouples the serialization format from the HTTP server. This also uses the Jackson library for the serialization which yields more accurate JSON.
N/A

Updates to the code for HTTP chunking

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/source/coordinator/SourceCoordinator.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/sourcecoordination/LeaseBasedSourceCoordinator.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/sourcecoordination/LeaseBasedSourceCoordinatorTest.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/S3ObjectWorker.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/ScanObjectWorker.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/s3/S3ScanObjectWorkerTest.java

This change adds an asynchronous progressCheck ack callback to update the partition ownership for S3 scan source. 
This fixes an issue where circuit breaker or full buffer can cause the synchronous thread to be blocked that was previously updating the partition ownership timeout.
Tested by blocking the write to the buffer and confirming that the partition for an object had it's partition ownership updated every 2 minutes
Related to #4422 

Add progress check callback to update partition ownership in S3 scan source

---

data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/S3ScanPartitionCreationSupplier.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/configuration/S3ScanScanOptions.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/s3/S3ScanPartitionCreationSupplierTest.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/s3/configuration/S3ScanScanOptionsTest.java

This change adds support for start_time and range in scheduled s3 scan to filter on the first scan of the buckets based on the time. Previously scheduled scan would always process all objects on the first scan.
Tested with a pipeline to confirm that only objects within a given start_time and range are processed

Support start_time or range options for the first scan of scheduled s3 scan

---

examples/log-ingestion/docker-compose.yaml

Podman requires the registry url in order to pull out the image (for the first run)
By default if you don't have specified registries in /etc/containers/registries.conf, at the first run, podman-compose cannot get the image. You will get this following error message 
```bash
Error: short-name "fluent/fluent-bit" did not resolve to an alias and no unqualified-search registries are defined in "/etc/containers/registries.conf"
exit code: 125
```
By adding the registry such as `docker.io` to the `image` value like below:
```yaml
image: docker.io/fluent/fluent-bit
```
Podman will be able to pull the image
```bash
Trying to pull docker.io/fluent/fluent-bit:latest...
Getting image source signatures
Copying blob e8c73c638ae9 done
Copying blob fe5ca62666f0 done
...
Copying blob 35f5792110f6 done …
```

Podman compat: adding registry to image value in docker-compose.yaml

---

examples/jaeger-hotrod/README.md
examples/jaeger-hotrod/docker-compose.yml
examples/jaeger-hotrod/pipelines.yaml

- Fixes Jaeger Hotrod demo failure on OpenSearch 2.16.0. 
- Apparently, the old version of OpenSearch is using `admin` as the default password for the `admin` account, which is very dangerous. The new version of OpenSearch corrects this problem and requires the initial password to be greater than 8 digits.
- In Docker Compose 2.29.2, the `version` field is deprecated. The Compose Spec is now dynamically updated at https://github.com/compose-spec/compose-spec .
- The content of `../demo/root-ca.pem` is exactly the same as the content of `/usr/share/opensearch/config/root-ca.pem` of the OpenSearch master node. Whether in the new version or the old version, there is no point in manually writing `root-ca.pem`, which will only confuse users.
- IntelliJ IDEA …

Fixes Jaeger Hotrod demo failure on OpenSearch 2.16.0

---

data-prepper-plugins/csv-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/csv/CsvProcessor.java
data-prepper-plugins/csv-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/csv/CsvProcessorTest.java

The CSV Processor is creating CsvMapper and CsvSchema for every record processed which is expensive as it can have a negative impact on the performance. The internal data structures consume memory, so creating a new instance on every request can increase the overall memory footprint.
Move CsvMapper and Schema creation to constructor.

Move CsvMapper and Schema creation to constructor

---

data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaCustomConsumer.java

The `kafka` buffer pauses reading from Kafka when the circuit breaker is tripped. It was pausing for 10 seconds which is quite a long time. This PR reduces the pause to 1 second.
N/A

Decrease the sleep when pausing the Kafka consumer on circuit breaker

---

data-prepper-pipeline-parser/src/main/java/org/opensearch/dataprepper/pipeline/parser/transformer/DynamicConfigTransformer.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/ClientFactory.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/RdsService.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/RdsSource.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/RdsSourceConfig.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/configuration/ExportConfig.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/configuration/StreamConfig.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/converter/ExportRecordConverter.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/converter/RecordConverter.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/converter/StreamRecordConverter.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/export/DataFileLoader.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/export/DataFileScheduler.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/leader/LeaderScheduler.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/model/ExportObjectKey.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/BinlogEventListener.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/StreamScheduler.java
data-prepper-plugins/rds-source/src/main/resources/org/opensearch/dataprepper/transforms/rules/rds-rule.yaml
data-prepper-plugins/rds-source/src/main/resources/org/opensearch/dataprepper/transforms/templates/rds-template.yaml
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/RdsServiceTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/converter/ExportRecordConverterTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/converter/StreamRecordConverterTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/export/DataFileLoaderTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/export/DataFileSchedulerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/leader/LeaderSchedulerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/model/ExportObjectKeyTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/stream/BinlogEventListenerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/stream/StreamSchedulerTest.java

This PR adds config transformation template for RDS source:
- Slightly updates RDS source config: moves partition_count to top level; adds role arn for export config
- For the S3 bucket, on top of user provided s3 prefix, add source coordinator prefix as subpath to distinguish between different pipelines. Under the subpath, further splits into two prefixes: `rds-export` for RDS exported data and `buffer` for pipeline generated data. 
- Refactors `ExportRecordConverter` and `StreamRecordConverter` to extract common code
- Adds rule and template for config transformation. The template is mostly adopted from documentdb ([link](https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-plugins/mongodb/src/main/resources/org/opensearch/dataprepper/transforms/templates/documentdb- …

Adds config transformation template for RDS source

---

data-prepper-plugins/mutate-string-processors/README.md
data-prepper-plugins/mutate-string-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutatestring/ReplaceStringProcessor.java
data-prepper-plugins/mutate-string-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutatestring/ReplaceStringProcessorConfig.java
data-prepper-plugins/mutate-string-processors/src/test/java/org/opensearch/dataprepper/plugins/processor/mutatestring/ReplaceStringProcessorTests.java

Add ReplaceStringProcessor for simple string substitution that doesn't involve regex
Add ReplaceStringProcessor for simple string substitution that doesn't involve regex. It uses java String.replace() method that is highly optimized for simple string replacements
Resolves #[[4953](https://github.com/opensearch-project/data-prepper/issues/4953)]

Add ReplaceStringProcessor for simple string substitution that doesn't involve regex

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/logging/DataPrepperMarkers.java
data-prepper-plugins/common/src/main/java/org/opensearch/dataprepper/plugins/processor/DelayProcessor.java
data-prepper-plugins/common/src/main/java/org/opensearch/dataprepper/plugins/processor/StringProcessor.java
data-prepper-plugins/csv-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/csv/CsvProcessor.java
data-prepper-plugins/date-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/date/DateProcessor.java
data-prepper-plugins/dissect-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/dissect/DissectProcessor.java
data-prepper-plugins/flatten-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/flatten/FlattenProcessor.java
data-prepper-plugins/geoip-processor/src/main/java/org/opensearch/dataprepper/plugins/geoip/processor/GeoIPProcessor.java
data-prepper-plugins/grok-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/grok/GrokProcessor.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/AddEntryProcessor.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/ConvertEntryTypeProcessor.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/CopyValueProcessor.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/DeleteEntryProcessor.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/ListToMapProcessor.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/MapToListProcessor.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/RenameKeyProcessor.java
data-prepper-plugins/mutate-string-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutatestring/AbstractStringProcessor.java
data-prepper-plugins/obfuscate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/obfuscation/ObfuscationProcessor.java
data-prepper-plugins/translate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/translate/TranslateProcessor.java
data-prepper-plugins/truncate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/truncate/TruncateProcessor.java
data-prepper-plugins/write-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/write_json/WriteJsonProcessor.java

Add noisy marker to logs that occur repeatedly.
Notes: 
setCause(e) is specifically for logging an exception with its full stack trace.
addArgument(e) treats the exception as a regular argument, and typically logs only the exception’s message (or whatever toString() provides).
Resolves #4927

Improve logging for exceptions

---

data-prepper-plugins/s3-sink/build.gradle
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/ClientFactory.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/S3SinkConfig.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/configuration/ClientOptions.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/s3/ClientFactoryTest.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/s3/S3SinkConfigTest.java

Adds max_connections and acquire_timeout options to s3 sink client.
Example:
```
...
sink:
- s3:
client:
max_connections: 100
acquire_timeout: 10s
...
```
Resolves #4949 

Add s3 sink client options

---

data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/BinlogEventListener.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/stream/BinlogEventListenerTest.java

Fix a bug by deregistering event listener when binlog client is disconnected.
When receiving negative acknowledgment, RDS source plugin will disconnect binlog client and reconnect with latest checkpoint. When reconnected, however, the client cannot process events any more with this error:
`java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@56c0293[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@33d53db2[Wrapped task = org.opensearch.dataprepper.plugins.source.rds.stream.BinlogEventListener$$Lambda$3144/0x000000080161d578@db0faf8]] rejected from java.util.concurrent.ThreadPoolExecutor@53e18682[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 12717915]`
This is because the old event listener is still …

Fix a bug with event listener in RDS source

---

data-prepper-plugins/rds-source/src/main/resources/org/opensearch/dataprepper/transforms/templates/rds-template.yaml

Update rds template with new s3 sink client options from #4959 . This is supposed to help resolve the error mentioned in #4949 in RDS source performance testing.
Default is 50 for `max_connections` and 10s for `acquire_timeout`. Doubling both here.
N/A

Update rds template with new s3 sink client options

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/annotations/DataPrepperPlugin.java
data-prepper-plugin-framework/src/main/java/org/opensearch/dataprepper/plugin/ClasspathPluginProvider.java
data-prepper-plugin-framework/src/test/java/org/opensearch/dataprepper/plugin/ClasspathPluginProviderTest.java
data-prepper-plugin-framework/src/test/java/org/opensearch/dataprepper/plugin/DefaultPluginFactoryTest.java
data-prepper-plugin-framework/src/test/java/org/opensearch/dataprepper/plugins/test/TestSink.java
data-prepper-plugin-framework/src/test/java/org/opensearch/dataprepper/plugins/test/TestSource.java

Add alternate name for Plugin

---

data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/documentdb/DocumentDBSource.java
data-prepper-plugins/mongodb/src/main/resources/org/opensearch/dataprepper/transforms/rules/mongodb-rule.yaml
data-prepper-plugins/mongodb/src/main/resources/org/opensearch/dataprepper/transforms/templates/mongodb-template.yaml

Add mongodb as alternate source name for documentdb source

Add mongodb as alternate source name for documentdb source

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/DataPrepper.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/DataPrepperShutdownOptions.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/Pipeline.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/PipelineShutdown.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/ProcessWorker.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/server/ShutdownHandler.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/DataPrepperShutdownOptionsTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/DataPrepperTests.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/PipelineShutdownTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/PipelineTests.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/server/ShutdownHandlerTest.java
data-prepper-pipeline-parser/src/main/java/org/opensearch/dataprepper/pipeline/parser/DataPrepperDurationDeserializer.java
data-prepper-pipeline-parser/src/main/java/org/opensearch/dataprepper/pipeline/parser/DataPrepperDurationParser.java
data-prepper-pipeline-parser/src/test/java/org/opensearch/dataprepper/pipeline/parser/DataPrepperDurationParserTest.java

Adds two new parameters to the shutdown API. The first is bufferReadTimeout which controls the amount of time to wait for the buffer to be empty. The second is bufferDrainTimeout which controls the overall wait time for the process worker threads to complete.
To support Data Prepper durations in HTTP query parameters, I extracted the parsing logic for durations out of DataPrepperDurationDeserializer and into a new DataPrepperDurationParser class.
Resolves #4966.

Variable drain timeouts when shutting down over HTTP shutdown.

---

data-prepper-plugins/kinesis-source/build.gradle
data-prepper-plugins/kinesis-source/src/integrationTest/java/org/opensearch/dataprepper/plugins/kinesis/source/KinesisSourceIT.java
data-prepper-plugins/kinesis-source/src/integrationTest/java/org/opensearch/dataprepper/plugins/kinesis/source/ingester/KinesisIngester.java
data-prepper-plugins/kinesis-source/src/integrationTest/java/org/opensearch/dataprepper/plugins/kinesis/source/util/TestIDGenerator.java
data-prepper-plugins/kinesis-source/src/main/java/org/opensearch/dataprepper/plugins/kinesis/source/processor/KinesisRecordProcessor.java
testing/aws-testing-cdk/bin/aws-testing-cdk.ts
testing/aws-testing-cdk/lib/kinesis/KinesisSourceStack.ts

This PR is to add an integration test for Kinesis source. As part of the integration test, it will perform the following actions:
- create a new Kinesis stream in a test account
- create a lease table for holding the shard specific lease coordination information 
- send a set of records (count = 20) to the stream using `putRecord` API
- wait for a period and validate whether source has been able to write 20 records to the buffer.
Resolves #[1082]
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CO …

Add integration test for Kinesis source

---

data-prepper-expression/src/main/antlr/DataPrepperExpression.g4
data-prepper-expression/src/main/java/org/opensearch/dataprepper/expression/LiteralTypeConversionsConfiguration.java
data-prepper-expression/src/main/java/org/opensearch/dataprepper/expression/ParseTreeCoercionService.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/ParseTreeCoercionServiceTest.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/TypeOfOperatorTest.java

Support BigDecimal data type in expressions
Resolves #4817 

Support BigDecimal data type in expressions

---

data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/ConvertEntryTypeProcessor.java
data-prepper-plugins/mutate-event-processors/src/test/java/org/opensearch/dataprepper/plugins/processor/mutateevent/ConvertEntryTypeProcessorTests.java

Support convert entry type on arrays. Each array element is converted to target type.

Support convert entry type on arrays

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/Pipeline.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/PipelineShutdown.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/PipelineShutdownTest.java

When shutting down a pipeline, it is hard to know what the shutdown timing will be. This PR adds additional logging.
N/A

Additional logging when shutting down the pipeline.

---

data-prepper-plugins/common/src/main/java/org/opensearch/dataprepper/plugins/processor/DelayProcessor.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/ConvertEntryTypeProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/RenameKeyProcessorConfig.java

Update required fields and property descriptions in rename key, convert entry type, and delay processors according to the documentation on the Opensearch website.

MAINT: update required properties and property descriptions in some processors

---

data-prepper-plugins/common/src/main/java/org/opensearch/dataprepper/plugins/processor/DelayProcessor.java
data-prepper-plugins/trace-peer-forwarder-processor/build.gradle
data-prepper-plugins/trace-peer-forwarder-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/TracePeerForwarderProcessor.java
data-prepper-plugins/trace-peer-forwarder-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/TracePeerForwarderProcessorConfig.java

Despite no settings, the config model class for trace peerforwarder for schema generation purpose. 

Add: trace peerforwarder config

---

examples/metrics-ingestion-otel/README.md
examples/metrics-ingestion-otel/docker-compose.yaml
examples/metrics-ingestion-otel/metric_pipeline.yaml
examples/metrics-ingestion-otel/otel-collector-config.yml

Provides a small Docker Compose setup to show metrics ingestion with Data Prepper. This example is similar to the traces and logs examples. It also shows the metrics Data Prepper emits on its metrics endpoint.
no issue known

Add OpenTelemetry Metrics example

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/DataType.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/event/DataTypeTest.java
data-prepper-plugin-schema-cli/src/main/java/org/opensearch/dataprepper/schemas/DataPrepperPluginSchemaExecute.java
data-prepper-plugin-schema/src/main/java/org/opensearch/dataprepper/schemas/JsonSchemaConverter.java
data-prepper-plugin-schema/src/test/java/org/opensearch/dataprepper/schemas/JsonSchemaConverterTest.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/AddEntryProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/ConvertEntryTypeProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/CopyValueProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/DeleteEntryProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/ListToMapProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/MapToListProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/RenameKeyProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/SelectEntriesProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/TargetType.java
data-prepper-plugins/mutate-event-processors/src/test/java/org/opensearch/dataprepper/plugins/processor/mutateevent/TargetTypeTest.java
data-prepper-plugins/mutate-string-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutatestring/LowercaseStringProcessor.java
data-prepper-plugins/mutate-string-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutatestring/LowercaseStringProcessorConfig.java
data-prepper-plugins/mutate-string-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutatestring/ReplaceStringProcessorConfig.java
data-prepper-plugins/mutate-string-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutatestring/SplitStringProcessorConfig.java
data-prepper-plugins/mutate-string-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutatestring/SubstituteStringProcessorConfig.java
data-prepper-plugins/mutate-string-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutatestring/TrimStringProcessor.java
data-prepper-plugins/mutate-string-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutatestring/TrimStringProcessorConfig.java
data-prepper-plugins/mutate-string-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutatestring/UppercaseStringProcessorConfig.java
data-prepper-plugins/mutate-string-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutatestring/WithKeysConfig.java

Support `@JsonValue` for determining enumeration values in the JSON Schema. Provide a JSON schema type of string for `EventKey` objects. Documentation wording improvements to the mutate event and mutate string processors.
N/A

Updates to JSON schema and Data Prepper documentation.

---

data-prepper-plugins/trace-peer-forwarder-processor/README.md
docs/configuration.md
docs/core_apis.md
docs/peer_forwarder.md
docs/trace_analytics.md
examples/config/example-pipelines.yaml
examples/dev/data-prepper-emf-monitoring/data-prepper-emf-demo-cfn.yaml
examples/dev/data-prepper-emf-monitoring/pipelines-raw-trace-stdout.yaml
examples/dev/k8s/data-prepper.yaml
examples/dev/trace-analytics-sample-app/resources/pipelines.yaml
examples/jaeger-hotrod/pipelines.yaml
examples/trace_analytics.yml
examples/trace_analytics_no_ssl.yml
examples/trace_analytics_no_ssl_2x.yml

- Remove references to deprecated processor names `otel_trace_raw` and `service_map_stateful`.
- This is explained in the JavaDoc for `org.opensearch.dataprepper.plugins.processor.ServiceMapStatefulProcessor` and `org.opensearch.dataprepper.plugins.processor.oteltrace.OTelTraceRawProcessor`.、
-  https://github.com/opensearch-project/data-prepper/blob/2.9.0/data-prepper-plugins/service-map-stateful/src/main/java/org/opensearch/dataprepper/plugins/processor/ServiceMapStatefulProcessor.java#L45
- https://github.com/opensearch-project/data-prepper/blob/2.9.0/data-prepper-plugins/otel-trace-raw-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/oteltrace/OTelTraceRawProcessor.java#L39
Resolves #[Issue number to be closed when this PR is …

Remove references to deprecated processor names `otel_trace_raw` and `service_map_stateful`

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/annotations/DataPrepperPlugin.java
data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/plugin/DefaultPluginFactoryIT.java
data-prepper-plugin-framework/src/main/java/org/opensearch/dataprepper/plugin/DefaultPluginFactory.java
data-prepper-plugin-framework/src/main/java/org/opensearch/dataprepper/plugin/PluginBeanFactoryProvider.java
data-prepper-plugin-framework/src/test/java/org/opensearch/dataprepper/plugin/DefaultPluginFactoryTest.java
data-prepper-plugin-framework/src/test/java/org/opensearch/dataprepper/plugin/PluginBeanFactoryProviderTest.java
data-prepper-plugin-framework/src/test/java/org/opensearch/dataprepper/plugins/test/TestComponent.java
data-prepper-plugin-framework/src/test/java/org/opensearch/dataprepper/plugins/test/TestDISource.java

Optional feature for the plugins to use Spring Dependency Injection in its own isolated context. 
How does it work?
- DataPrepper plugin annotation is enhanced to accept the marker classes to indicate the packages that these marker classes belong are the root for the plugin classes to be considered under its isolated spring context
- Plugin can pass more than one marker class to combine its spring context along with other code
- This is an optional entry. If not provided, everything will work as it was before.
- When given, the framework will initialize Spring DI over plugin classes and also inject any required beans to the plugin constructor while it gets instantiated.
Resolves #929 
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …

Providing an option for the plugins to use Spring DI

---

build.gradle

The current output of failures shows where the assertion failed. But, it does not show what was wrong with the assertion.
For example, we see logs like this:
```
AbstractSinkTest > testSinkNotReady() FAILED
org.opentest4j.AssertionFailedError at AbstractSinkTest.java:84
```
This change outputs the actual cause without adding the whole stack trace either.
Here is some sample code:
```
public class ForceFail {
@Test
void always_fails() {
assertThat(true, equalTo(false));
}
}
```
The logging includes:
```
> Task :data-prepper-api:test
ForceFail > always_fails() FAILED
java.lang.AssertionError:
Expected: <false>
but: was <true>
1133 tests completed, 1 failed, 2 skipped
```
N/A …

Update the test logging to include the failed assertion

---

data-prepper-plugins/mongodb/src/main/resources/org/opensearch/dataprepper/transforms/templates/documentdb-template.yaml
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/ScanObjectWorker.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/configuration/S3ScanScanOptions.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/s3/S3ScanObjectWorkerTest.java

If there is some reason that causes partition for s3 scan to not be given up, or if the acknowledgment is never received for a partition, s3 scan defaults to a 2 hour acknowledgment wait before reprocessing. For mongodb pipelines, this can cause high delay for some records, and these pipelines are meant to be low latency.
This change adds an `acknowledgment_timeout` parameter to S3 scan, and sets it to 10 minutes in the DocumentDB L2 transform.

Make acknowledgment_timeout configurable for s3 scan source, configure timeout to 10 minutes for MongoDB L2 transform

---

data-prepper-plugins/s3-sink/src/integrationTest/java/org/opensearch/dataprepper/plugins/sink/s3/JsonOutputScenario.java
data-prepper-plugins/s3-sink/src/integrationTest/java/org/opensearch/dataprepper/plugins/sink/s3/NdjsonOutputScenario.java
data-prepper-plugins/s3-sink/src/integrationTest/java/org/opensearch/dataprepper/plugins/sink/s3/OutputScenario.java
data-prepper-plugins/s3-sink/src/integrationTest/java/org/opensearch/dataprepper/plugins/sink/s3/ParquetOutputScenario.java
data-prepper-plugins/s3-sink/src/integrationTest/java/org/opensearch/dataprepper/plugins/sink/s3/S3SinkIT.java

Adds an integration test for the json codec which was previously failing before this change (https://github.com/opensearch-project/data-prepper/pull/4410)

Add integration test for Json codec in S3 sink

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/configuration/ConditionalRoute.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/HandleFailedEventsOption.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/event/HandleFailedEventsOptionTest.java
data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateProcessorConfig.java
data-prepper-plugins/common/src/main/java/org/opensearch/dataprepper/plugins/processor/DelayProcessor.java
data-prepper-plugins/common/src/main/java/org/opensearch/dataprepper/plugins/processor/StringProcessor.java
data-prepper-plugins/date-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/date/DateProcessorConfig.java
data-prepper-plugins/decompress-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/decompress/DecompressProcessorConfig.java
data-prepper-plugins/decompress-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/decompress/DecompressionType.java
data-prepper-plugins/decompress-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/decompress/DecompressionTypeTest.java
data-prepper-plugins/dissect-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/dissect/DissectProcessorConfig.java
data-prepper-plugins/drop-events-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/drop/DropEventProcessorConfig.java
data-prepper-plugins/geoip-processor/src/main/java/org/opensearch/dataprepper/plugins/geoip/processor/EntryConfig.java
data-prepper-plugins/geoip-processor/src/main/java/org/opensearch/dataprepper/plugins/geoip/processor/GeoIPProcessorConfig.java
data-prepper-plugins/grok-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/grok/GrokProcessorConfig.java
data-prepper-plugins/obfuscate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/obfuscation/ObfuscationProcessorConfig.java
data-prepper-plugins/obfuscate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/obfuscation/action/OneWayHashActionConfig.java
data-prepper-plugins/otel-metrics-raw-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/otelmetrics/OtelMetricsRawProcessorConfig.java
data-prepper-plugins/otel-trace-raw-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/oteltrace/OtelTraceRawProcessorConfig.java
data-prepper-plugins/service-map-stateful/src/main/java/org/opensearch/dataprepper/plugins/processor/ServiceMapProcessorConfig.java
data-prepper-plugins/split-event-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/splitevent/SplitEventProcessorConfig.java
data-prepper-plugins/trace-peer-forwarder-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/TracePeerForwarderProcessorConfig.java
data-prepper-plugins/truncate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/truncate/TruncateProcessorConfig.java
data-prepper-plugins/user-agent-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/useragent/UserAgentProcessorConfig.java
data-prepper-plugins/write-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/write_json/WriteJsonProcessorConfig.java

Updates some enumerations used in processors to support the `@JsonValue` annotation. Corrects `@JsonClassDescription` to use HTML rather than Markdown. Various unit test improvements for modified unit tests.
This follows on other PRs such as:
* #5019
* #4985
In particular, for #4985, I missed the `@JsonClassDescription` headers.
None

Documentation improvements for a number of Data Prepper processors.

---

data-prepper-plugins/date-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/date/DateProcessorConfig.java
data-prepper-plugins/decompress-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/decompress/DecompressProcessorConfig.java
data-prepper-plugins/flatten-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/flatten/FlattenProcessorConfig.java
data-prepper-plugins/geoip-processor/src/main/java/org/opensearch/dataprepper/plugins/geoip/processor/EntryConfig.java
data-prepper-plugins/geoip-processor/src/main/java/org/opensearch/dataprepper/plugins/geoip/processor/GeoIPProcessorConfig.java
data-prepper-plugins/grok-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/grok/GrokProcessorConfig.java
data-prepper-plugins/key-value-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/keyvalue/KeyValueProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/AddEntryProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/ConvertEntryTypeProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/CopyValueProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/ListToMapProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/MapToListProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/RenameKeyProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/test/java/org/opensearch/dataprepper/plugins/processor/mutateevent/ListToMapProcessorConfig_FlattenedElementTest.java
data-prepper-plugins/mutate-string-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutatestring/ReplaceStringProcessorConfig.java
data-prepper-plugins/mutate-string-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutatestring/SplitStringProcessorConfig.java
data-prepper-plugins/mutate-string-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutatestring/SubstituteStringProcessorConfig.java
data-prepper-plugins/obfuscate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/obfuscation/ObfuscationProcessorConfig.java
data-prepper-plugins/obfuscate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/obfuscation/action/MaskActionConfig.java
data-prepper-plugins/obfuscate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/obfuscation/action/OneWayHashActionConfig.java
data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parse/ion/ParseIonProcessorConfig.java
data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parse/json/ParseJsonProcessorConfig.java
data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parse/xml/ParseXmlProcessorConfig.java
data-prepper-plugins/split-event-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/splitevent/SplitEventProcessorConfig.java

This fixes many property orders.
First by adding missing `@JsonPropertyOrder` annotations. Second, by re-ordering many properties. The approach I took is to move the most important configurations up front. Then I also grouped others logically. For character vs. regex, I put character configurations first. I moved tags and when statements toward the bottom.
Added some other missing documentation. Also, added a missing enum.
N/A

Doc improvements: re-ordering; missing annotations; missed enums

---

data-prepper-plugins/kinesis-source/build.gradle

This PR is to fix the build break for `kinesis-source` plugin.
```
> Task :data-prepper-plugins:kinesis-source:compileTestJava FAILED
/Users/dlv/Documents/Development/opensearch/data-prepper/data-prepper-plugins/kinesis-source/src/test/java/org/opensearch/dataprepper/plugins/kinesis/extension/KinesisLeaseConfigTest.java:43: error: cannot access EventConfigurationContainer
final DataPrepperConfiguration dataPrepperConfiguration = OBJECT_MAPPER.readValue(configurationFile, DataPrepperConfiguration.class);
^
class file for org.opensearch.dataprepper.core.event.EventConfigurationContainer not found
Note: Some input files use or override a deprecated API.
```
Resolves #1082
For …

Fix the build break for kinesis source

---

data-prepper-plugins/kinesis-source/src/main/java/org/opensearch/dataprepper/plugins/kinesis/source/converter/KinesisRecordConverter.java
data-prepper-plugins/kinesis-source/src/main/java/org/opensearch/dataprepper/plugins/kinesis/source/converter/MetadataKeyAttributes.java
data-prepper-plugins/kinesis-source/src/test/java/org/opensearch/dataprepper/plugins/kinesis/source/converter/KinesisRecordConverterTest.java

This PR is to add a metadata attribute `sequence_number` such that a combination of the `partition_key` and `sequence_number` can be used as the `document_id` for each record. 

Adding a metadata attribute for sequence number of record

---

data-prepper-plugins/service-map-stateful/src/main/java/org/opensearch/dataprepper/plugins/processor/ServiceMapProcessorConfig.java
data-prepper-plugins/service-map-stateful/src/main/java/org/opensearch/dataprepper/plugins/processor/ServiceMapStatefulProcessor.java
data-prepper-plugins/service-map-stateful/src/test/java/org/opensearch/dataprepper/plugins/processor/ServiceMapProcessorConfigTest.java

Change default DB path for service map to be under /tmp since it is only used for off-heap memory

MAINT: use tmp folder for default db path for service-map

---

data-prepper-plugins/grok-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/grok/GrokProcessorConfig.java

The grok `match` field is currently not validated as required. However, if this parameter is not set, then the grok processor will not do anything, and that is not clear. The `match` field should be required.

Add NotEmpty annotation to grok match parameter

---

data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/RdsService.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/RdsSource.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/BinlogClientFactory.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/BinlogEventListener.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/StreamScheduler.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/StreamWorker.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/StreamWorkerTaskRefresher.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/RdsServiceTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/RdsSourceTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/stream/BinlogClientFactoryTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/stream/StreamSchedulerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/stream/StreamWorkerTaskRefresherTest.java

RDS source uses credentials stored in Secret Manager to connect to the database during stream (CDC). Data Prepper checks the credentials regularly through the Secret Manager extension in case they change. The PR adds a StreamWorkerTaskRefresher to the source plugin to update the stream connection when credentials change is detected.

Support secret rotation in RDS source

---

data-prepper-plugins/service-map-stateful/src/test/java/org/opensearch/dataprepper/plugins/processor/ServiceMapStatefulProcessorTest.java

This fixes the build that is currently failing with:
```
ServiceMapStatefulProcessorTest > testDataPrepperConstructor() FAILED
java.lang.NullPointerException
ServiceMapStatefulProcessorTest > testGetIdentificationKeys() FAILED
java.lang.NullPointerException
```
Testing: `./gradlew :data-prepper-plugins:service-map-stateful:test` is passing after the change.
N/A

Fix service map tests

---

data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/converter/MetadataKeyAttributes.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/converter/RecordConverter.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/converter/StreamRecordConverter.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/converter/StreamRecordConverterTest.java

This change allows users to identify the source of a REMOVE event from DynamoDB streams,  if it was a manual delete or a TTL delete.
Resolves #4560 

Adding ttl_delete parameter to metadata for DynamoDB

---

data-prepper-plugins/kinesis-source/README.md

This PR adds a README for Kinesis source.

Adding Kinesis README

---

data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/ConvertEntryTypeProcessor.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/ConvertEntryTypeProcessorConfig.java

This PR renames `convert_entry_type` to `convert_type`. It also retains `convert_entry_type` as a deprecated name.
N/A

Rename convert_entry_type to convert_type

---

data-prepper-plugins/kinesis-source/src/main/java/org/opensearch/dataprepper/plugins/kinesis/source/configuration/KinesisStreamConfig.java
data-prepper-plugins/kinesis-source/src/main/java/org/opensearch/dataprepper/plugins/kinesis/source/converter/KinesisRecordConverter.java
data-prepper-plugins/kinesis-source/src/main/java/org/opensearch/dataprepper/plugins/kinesis/source/processor/KinesisRecordProcessor.java
data-prepper-plugins/kinesis-source/src/test/java/org/opensearch/dataprepper/plugins/kinesis/source/configuration/KinesisSourceConfigTest.java
data-prepper-plugins/kinesis-source/src/test/java/org/opensearch/dataprepper/plugins/kinesis/source/converter/KinesisRecordConverterTest.java
data-prepper-plugins/kinesis-source/src/test/java/org/opensearch/dataprepper/plugins/kinesis/source/processor/KinesisRecordProcessorTest.java
data-prepper-plugins/kinesis-source/src/test/resources/pipeline_with_checkpoint_enabled.yaml

This PR is to add support for compression type per stream. For records added by CloudWatch, customers should have an option to enable this configuration which will enable to decompress the records and allow to parse. 

Adding support for compression config per KDS stream.

---

data-prepper-plugins/kinesis-source/src/main/java/org/opensearch/dataprepper/plugins/kinesis/source/KinesisService.java
data-prepper-plugins/kinesis-source/src/main/java/org/opensearch/dataprepper/plugins/kinesis/source/configuration/KinesisSourceConfig.java
data-prepper-plugins/kinesis-source/src/test/java/org/opensearch/dataprepper/plugins/kinesis/source/KinesisServiceTest.java
data-prepper-plugins/kinesis-source/src/test/java/org/opensearch/dataprepper/plugins/kinesis/source/configuration/KinesisSourceConfigTest.java

It has been observed that If the pipeline role is missing Kinesis permissions, the source throws an exception resulting in a shutdown of the pipeline.
The fix is to add retry based on 2 configurations in KinesisSource:
- max_initialization_attempts - to allow the customer to continue retry to initialize the source 
- initialization_backoff_time - wait between retry calls 
This should help to make sure that the pipeline is not terminated when permissions are missing. With updated permissions, the pipeline should continue to initialize and function properly.
For more information on following Developer Certificate of Origin and signing off your commits, please …

Add retry to make sure source is not shutdown when exceptions are thrown on the main thread

---

data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parse/AbstractParseProcessor.java
data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parse/CommonParseConfig.java
data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parse/ion/ParseIonProcessor.java
data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parse/ion/ParseIonProcessorConfig.java
data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parse/json/ParseJsonProcessor.java
data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parse/json/ParseJsonProcessorConfig.java
data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parse/xml/ParseXmlProcessor.java
data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parse/xml/ParseXmlProcessorConfig.java
data-prepper-plugins/parse-json-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/parse/json/ParseJsonProcessorTest.java

parse_json: add ability to only parse upto a user-configured depth with the larger depth values are stored as strings.
With this change an input like
```
"key":"{\"a\": 1, \"b\": {\"c\": 3, \"d\" : {\"e\": \"s5\"}}}"
```
with source as `key` and destination as `key` 
with `depth: 1` would parse the json as
```
{
"key": {
"a": 1,
"b": "{\"c\":3,\"d\":{\"e\":\"s5\"}}"
}
}
```
with `depth: 2` would parse the json as
```
{
"key":  {
"a": 1,
"b": {
"c": 3,
"d": "{\"e\":\"s5\"}"
}
}
}
```
and with `depth:0` (which is default) would parse it as
```
{
"key": {
"a": 1,
"b": {
"c": 3,
"d": {
"e": "s5"
}
}
}
}
```
Resolves #4695
- [X ] New functionality has javadoc added
By submitting this pull request, …

Add support to parse upto certain depth in parse_json processor 

---

data-prepper-plugins/otel-metrics-raw-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/otelmetrics/OtelMetricsRawProcessorConfig.java
data-prepper-plugins/otel-trace-raw-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/oteltrace/OtelTraceRawProcessorConfig.java
data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parse/ion/ParseIonProcessorConfig.java
data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parse/json/ParseJsonProcessorConfig.java
data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parse/xml/ParseXmlProcessorConfig.java

This PR covers:
* parse_json
* parse_ion
* parse_xml
* otel_metrics
* otel_trace

FIX: annotation and documentation gap in processors

---

data-prepper-api/src/test/java/org/opensearch/dataprepper/model/sink/AbstractSinkTest.java

Reworked the tests to be somewhat faster. Reworked one flaky test such that it appears to be passing consistently now by using finer-grained control on the timing. Finished one test by making it actually verify the metrics, which is what it was apparently intended to do in the first place.
None

Fixes and improvements for AbstractSinkTest

---

data-prepper-plugins/dissect-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/dissect/DissectProcessorConfig.java
data-prepper-plugins/key-value-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/keyvalue/KeyValueProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/ListToMapProcessorConfig.java

1. Added an embed into `map` field of the `dissect` processor. It previously had the whole link not hyperlinked.
2. Added missing spaces into the `whitespace` and `strict_grouping` fields of the key-value processor.
3. Added the specification of default value being `false` in the `flatten` field description of the `list to map` processor.
4. Reordered `use_source_key` and `key` fields of the `list to map` processor to be next to each other since they are associated. …

ENH: add missing spaces in descriptions, reorder fields

---

data-prepper-pipeline-parser/src/main/java/org/opensearch/dataprepper/validation/PluginError.java
data-prepper-pipeline-parser/src/test/java/org/opensearch/dataprepper/validation/PluginErrorTest.java
data-prepper-plugin-framework/build.gradle
data-prepper-plugin-framework/src/main/java/org/opensearch/dataprepper/plugin/PluginConfigurationConverter.java
data-prepper-plugin-framework/src/main/java/org/opensearch/dataprepper/plugin/PluginConfigurationErrorHandler.java
data-prepper-plugin-framework/src/main/java/org/opensearch/dataprepper/plugin/PluginCreator.java
data-prepper-plugin-framework/src/main/java/org/opensearch/dataprepper/plugin/ValidatorConfiguration.java
data-prepper-plugin-framework/src/test/java/org/opensearch/dataprepper/plugin/PluginConfigurationConverterTest.java
data-prepper-plugin-framework/src/test/java/org/opensearch/dataprepper/plugin/PluginConfigurationErrorHandlerTest.java

This change improves the error messaging for unknown plugin properties and json mapping exceptions
Old error for unknown property
```
entry-pipeline.processor.parse_json: caused by: Unrecognized field "destiatio" (class org.opensearch.dataprepper.plugins.processor.parse.json.ParseJsonProcessorConfig), not marked as ignorable (8 known properties: "tags_on_failure", "handle_failed_events", "parse_when", "source", "pointer", "destination", "delete_source", "overwrite_if_destination_exists"]) at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: org.opensearch.dataprepper.plugins.processor.parse.json.ParseJsonProcessorConfig["destiatio"]) caused by: Unrecognized field "destiatio" (class org.opensearch.dataprepper.plugins.processor.parse.json.ParseJsonProcessorConfig), not …
```

Improve validation error messages for unknown property and json mapping exceptions

---

data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/ObjectMetadata.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/ObjectMetadataConfig.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/S3SinkConfig.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/grouping/S3GroupIdentifier.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/grouping/S3GroupIdentifierFactory.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/s3/ObjectMetadataConfigTest.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/s3/ObjectMetadataTest.java

Renaming S3 sink config options

Rename s3 sink object metadata config options

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/codec/JsonDecoder.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/codec/JsonDecoderTest.java
data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/codec/json/JsonInputCodec.java
data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/codec/json/JsonInputCodecConfig.java
data-prepper-plugins/parse-json-processor/src/test/java/org/opensearch/dataprepper/plugins/codec/json/JsonCodecsIT.java
data-prepper-plugins/parse-json-processor/src/test/java/org/opensearch/dataprepper/plugins/codec/json/JsonInputCodecConfigTest.java
data-prepper-plugins/parse-json-processor/src/test/java/org/opensearch/dataprepper/plugins/codec/json/JsonInputCodecTest.java
data-prepper-plugins/s3-source/src/integrationTest/java/org/opensearch/dataprepper/plugins/source/s3/JsonRecordsGenerator.java

This PR is to add support for additional configuration entries in the `JsonInputCodec` so that CloudWatch logs from subscription filters could be decoded in Data Prepper. [CloudWatch Subscription Filter](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/SubscriptionFilters.html)
For the input message from CloudWatch
```
{
"owner": "111111111111",
"logGroup": "CloudTrail/logs",
"logStream": "111111111111_CloudTrail/logs_us-east-1",
"subscriptionFilters": [
"Destination"
],
"messageType": "DATA_MESSAGE",
"logEvents": [
{
"id": "31953106606966983378809025079804211143289615424298221568",
"timestamp": 1432826855000,
"message": "{\"eventVersion\":\"1.03\",\"userIdentity\":{\"type\":\"Root\"}"
},
{
"id": "31953106606966983378809025079804211143289615424298221569",
"timestamp": …
```

Json codec changes with specific json input codec config

---

data-prepper-plugin-schema-cli/src/main/java/org/opensearch/dataprepper/schemas/DataPrepperPluginSchemaExecute.java
data-prepper-plugin-schema/src/main/java/org/opensearch/dataprepper/schemas/module/DataPrepperJakartaValidationModule.java
data-prepper-plugin-schema/src/main/java/org/opensearch/dataprepper/schemas/module/DataPrepperModules.java
data-prepper-plugin-schema/src/test/java/org/opensearch/dataprepper/schemas/module/DataPrepperJakartaValidationModuleTest.java
data-prepper-plugins/key-value-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/keyvalue/KeyValueProcessor.java
data-prepper-plugins/key-value-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/keyvalue/KeyValueProcessorConfig.java
data-prepper-plugins/key-value-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/keyvalue/TransformOption.java
data-prepper-plugins/key-value-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/keyvalue/KeyValueProcessorTests.java
data-prepper-plugins/key-value-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/keyvalue/TransformOptionTest.java

This adds a none option to the whitespace enum while still supporting empty string. It includes default values to prevent fields from displaying that they are required. It also provides a solution for the schema generation which removes any property with a defaultValue from the list of required fields.
N/A

Improvements to the schema for the key_value processor.

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/parser/PipelineTransformer.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/parser/config/PipelineParserConfiguration.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/parser/PipelineTransformerTests.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/parser/config/PipelineParserConfigurationTest.java
data-prepper-pipeline-parser/src/main/java/org/opensearch/dataprepper/validation/PluginError.java
data-prepper-plugin-framework/src/main/java/org/opensearch/dataprepper/plugin/PluginConfigurationConverter.java
data-prepper-plugin-framework/src/main/java/org/opensearch/dataprepper/plugin/PluginConfigurationErrorHandler.java
data-prepper-plugin-framework/src/test/java/org/opensearch/dataprepper/plugin/PluginConfigurationConverterTest.java
data-prepper-plugins/csv-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/csv/CsvProcessorConfig.java

This adds a couple of improvements to the validations in Data Prepper
1. Validate the expression in `routes` follows the Data Prepper expression syntax grammar. This validation previously only happened at runtime
2. Remove the method name from the `AssertTrue` validations in the error message

Add validations on route expressions, clean up assertTrue validation messages

---

data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateProcessorConfig.java
data-prepper-plugins/csv-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/csv/CsvProcessorConfig.java
data-prepper-plugins/grok-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/grok/GrokProcessorConfig.java
data-prepper-plugins/key-value-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/keyvalue/KeyValueProcessorConfig.java
data-prepper-plugins/mutate-string-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutatestring/SubstituteStringProcessorConfig.java
data-prepper-plugins/truncate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/truncate/TruncateProcessorConfig.java

- Fix some description errors in Aggregate, Substitute String, and Truncate processors
- Add default boolean values = `true` in Grok and Key-Value processors
- Denote `source` property in CSV processor as `@NotBlank`. Following the pattern in the Parse ION/JSON/XML processors. Reason is to clarify some issues when users don't pass the source and then they don't know why it's working because they don't have a "message" field.

Schema edits and enhancements

---

data-prepper-plugins/date-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/date/DateProcessorConfig.java

Follow up to #5072 - fix build break by adding missing plus sign.

Fix build break

---

data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateProcessor.java
data-prepper-plugins/date-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/date/DateProcessor.java
data-prepper-plugins/dissect-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/dissect/DissectProcessor.java
data-prepper-plugins/flatten-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/flatten/FlattenProcessor.java
data-prepper-plugins/geoip-processor/src/main/java/org/opensearch/dataprepper/plugins/geoip/processor/GeoIPProcessor.java
data-prepper-plugins/grok-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/grok/GrokProcessor.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/IndexConfiguration.java

Clean up expression error messages

---

build.gradle
data-prepper-plugins/kinesis-source/src/main/java/org/opensearch/dataprepper/plugins/kinesis/source/KinesisService.java
data-prepper-plugins/s3-sink/build.gradle

This PR is to address the dependency conflict in Kinesis Source plugin. It looks there is a conflict of AWS Sdk Kinesls Client dependency which was breaking the plugin functionality. 
Resolves #5084 

Fix AWS Sdk dependency conflict

---

data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateProcessorConfig.java
data-prepper-plugins/decompress-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/decompress/DecompressProcessorConfig.java
data-prepper-plugins/dissect-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/dissect/DissectProcessorConfig.java
data-prepper-plugins/drop-events-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/drop/DropEventProcessorConfig.java
data-prepper-plugins/geoip-processor/src/main/java/org/opensearch/dataprepper/plugins/geoip/processor/GeoIPProcessorConfig.java
data-prepper-plugins/grok-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/grok/GrokProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/AddEntryProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/CopyValueProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/ListToMapProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/MapToListProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/RenameKeyProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/SelectEntriesProcessorConfig.java
data-prepper-plugins/obfuscate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/obfuscation/ObfuscationProcessorConfig.java
data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parse/ion/ParseIonProcessorConfig.java

- Remove single quotes from field descriptions
- Change descriptions for `from_list` and `to_list` fields in `copy_value` processor. Context is [here](https://github.com/oeyh/documentation-website/blob/data_prepper_copy_lists/_data-prepper/pipelines/configuration/processors/copy-values.md).

Modify descriptions of processor schemas

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/annotations/AlsoRequired.java
data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateProcessorConfig.java
data-prepper-plugins/date-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/date/DateProcessorConfig.java
data-prepper-plugins/flatten-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/flatten/FlattenProcessorConfig.java
data-prepper-plugins/key-value-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/keyvalue/KeyValueProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/AddEntryProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/ConvertEntryTypeProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/CopyValueProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/ListToMapProcessorConfig.java
data-prepper-plugins/mutate-string-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutatestring/SplitStringProcessorConfig.java
data-prepper-plugins/split-event-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/splitevent/SplitEventProcessorConfig.java
data-prepper-plugins/translate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/translate/TargetsParameterConfig.java

This PR backfills @AlsoRequired annotation to processor attributes for schema generation purpose:
aggregate:
flatten:
key_value:
add_entry:
convert_entry:
copy_value
split string:
split event:
Example schema after this change:
```
{
"$schema" : "https://json-schema.org/draft/2020-12/schema",
"type" : "object",
"properties" : {
"entries" : {
"description" : "A list of entries to add to the event.",
"minItems" : 1,
"type" : "array",
"items" : {
"type" : "object",
"properties" : {
"key" : {
"type" : "string",
"description" : "The key of the new entry to be added. Some examples of keys include <code>my_key</code>, <code>myKey</code>, and <code>object/sub_Key</code>. The key can also be a format expression, for example, <code>${/key1}</code> to use the value of field <code>key1</code> as the …
```

ENH: backfill @AlsoRequired annotation to processor attributes

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/acknowledgements/AcknowledgementSet.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/AggregateEventHandle.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/DefaultEventHandle.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/InternalEventHandle.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/acknowledgements/AcknowledgementSetTests.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/event/AggregateEventHandleTests.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/event/DefaultEventHandleTests.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/core/acknowledgements/DefaultAcknowledgementSet.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/core/pipeline/router/RouterCopyRecordStrategy.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/core/acknowledgements/DefaultAcknowledgementSetTests.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/core/pipeline/router/RouterCopyRecordStrategyTests.java
data-prepper-plugins/kinesis-source/src/test/java/org/opensearch/dataprepper/plugins/kinesis/source/processor/KinesisRecordProcessorTest.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/NoSearchContextWorkerTest.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/PitWorkerTest.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/ScrollWorkerTest.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/s3/S3ObjectWorkerTest.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/s3/S3SelectObjectWorkerTest.java
data-prepper-plugins/split-event-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/splitevent/SplitEventProcessor.java
data-prepper-plugins/split-event-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/splitevent/SplitEventProcessorTest.java

Modify AcknowledgementSet add API to accept EventHandle instead of Event.
This is part of supporting acknowledgements in aggregate processor (local mode).

Modify AcknowledgementSet add API to accept EventHandle instead of Event

---

release/release-notes/data-prepper.change-log-2.10.1.md

This PR Is to add change log for 2.10.1 patch release.
```
git fetch upstream
git switch 2.10
git pull
git-release-notes 2.10.0..HEAD markdown > release/release-notes/data-prepper.change-log-2.10.1.md
git switch main
```

Changelog 2.10.1

---

data-prepper-plugins/aws-plugin-api/src/main/java/org/opensearch/dataprepper/aws/api/AwsCredentialsOptions.java
data-prepper-plugins/aws-plugin-api/src/test/java/org/opensearch/dataprepper/aws/api/AwsCredentialsOptionsTest.java
data-prepper-plugins/aws-plugin/src/main/java/org/opensearch/dataprepper/plugins/aws/CredentialsProviderFactory.java
data-prepper-plugins/aws-plugin/src/test/java/org/opensearch/dataprepper/plugins/aws/AwsPluginIT.java
data-prepper-plugins/kinesis-source/src/main/java/org/opensearch/dataprepper/plugins/kinesis/source/KinesisClientFactory.java

This PR is to fix the credentials required for Lease Coordination table access. The fix is to use the default credentials instead of the pipeline role when Data Prepper would access the dynamoDb table.
Resolves #1082

Fix the lease coordination table permissions

---

.github/CODEOWNERS

Include Souvik Bose (sb2k16) in the CODEOWNERS file.
N/A

Include Souvik Bose (sb2k16) in the CODEOWNERS file.

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/annotations/ExampleValues.java
data-prepper-plugin-schema/src/main/java/org/opensearch/dataprepper/schemas/ExampleValuesInstanceAttributeOverride.java
data-prepper-plugin-schema/src/main/java/org/opensearch/dataprepper/schemas/JsonSchemaConverter.java
data-prepper-plugin-schema/src/test/java/org/opensearch/dataprepper/schemas/ExampleValuesInstanceAttributeOverrideTest.java
data-prepper-plugin-schema/src/test/java/org/opensearch/dataprepper/schemas/JsonSchemaConverterIT.java
data-prepper-plugins/date-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/date/DateProcessorConfig.java

Introduces `@ExampleValues` annotation for schema and documentation generation.
* Adds a new annotation `@ExampleValues`. 
* Updates the schema generation with an `InstanceAttributeOverride` to add the examples to the schemas. 
* Adds `@ExampleValues` annotations to the date processor.
Resolves #5077

ExampleValues annotation for schema generation along with date examples

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/types/ByteCount.java
data-prepper-pipeline-parser/src/main/java/org/opensearch/dataprepper/pipeline/parser/ByteCountDeserializer.java
data-prepper-pipeline-parser/src/main/java/org/opensearch/dataprepper/pipeline/parser/EnumDeserializer.java
data-prepper-pipeline-parser/src/test/java/org/opensearch/dataprepper/pipeline/parser/ByteCountDeserializerTest.java
data-prepper-pipeline-parser/src/test/java/org/opensearch/dataprepper/pipeline/parser/EnumDeserializerTest.java
data-prepper-plugin-framework/src/main/java/org/opensearch/dataprepper/plugin/ObjectMapperConfiguration.java
data-prepper-plugin-framework/src/test/java/org/opensearch/dataprepper/plugin/ObjectMapperConfigurationTest.java
data-prepper-plugins/drop-events-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/drop/DropEventsProcessor.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/configuration/ThresholdOptions.java

Currently when enums are deserialized with an invalid value the error will say that the value must not be null, because the enums we use have a @JsonCreator that looks up the options in the map and returns null.
This adds a custom enum deserializer that will give a clearer message and provide the valid options to the user.
Also, the ByteCount error messages were improved to provide valid options and show which field is invalid.
New error message for invalid enum values
1. entry-pipeline.processor.parse_json: caused by: Parameter "handle_failed_events" for plugin "parse_json" is invalid: Invalid value "skip_silentl". Valid options include [drop, drop_silently, skip, skip_silently].
By submitting this pull request, I confirm that …

Add custom enum deserializer to improve error messaging, improve byte count error mesages

---

release/release-notes/data-prepper.change-log-2.10.1.md

Add change log for 2.10 patch release
Signed-off-by: Souvik Bose <souvbose@amazon.com>
(cherry picked from commit c7877c5a084b6cc3e39afe41cda0f6c011fc46f6)
This PR is to backport to 2.10 manually following the process [here](https://github.com/opensearch-project/data-prepper/pull/5090)

Changelog 2.10.1 (#5090)

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/JacksonEvent.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/metric/JacksonExponentialHistogram.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/metric/JacksonGauge.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/metric/JacksonHistogram.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/metric/JacksonMetric.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/metric/JacksonSum.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/metric/JacksonSummary.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/event/JacksonEventTest.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/metric/JacksonExponentialHistogramTest.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/metric/JacksonGaugeTest.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/metric/JacksonHistogramTest.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/metric/JacksonSumTest.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/metric/JacksonSummaryTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/core/peerforwarder/codec/PeerForwarderCodecAppConfig_SerializationFilterIT.java
data-prepper-event/src/main/java/org/opensearch/dataprepper/core/event/DefaultBaseEventBuilder.java

Added `withEventHandle` API to JacksonEvent.Builder.
This is part of supporting acknowledgements to events generated by aggregate processor

Event with handle

---

data-prepper-plugins/kinesis-source/src/main/java/org/opensearch/dataprepper/plugins/kinesis/source/KinesisService.java

This PR is to catch KCL known exceptions to reduce noisy log statements.
Resolves #1082

Catch KCL known exceptions to reduce noisy log statements

---

data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/integration/PipelinesWithAcksIT.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/core/parser/PipelineTransformer.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/core/parser/PipelineTransformerTests.java
data-prepper-pipeline-parser/src/main/java/org/opensearch/dataprepper/pipeline/parser/EnumDeserializer.java
data-prepper-pipeline-parser/src/test/java/org/opensearch/dataprepper/pipeline/parser/EnumDeserializerTest.java
data-prepper-plugin-framework/src/main/java/org/opensearch/dataprepper/plugin/ObjectMapperConfiguration.java

The new EnumDeserializer defaults to checking for the lower case enum value when there is no `@JsonCreator` on the enum class, and this broke basic enums like
```
enum MyEnum {
ENUM_ONE,
ENUM_TWO
}
```
Since we don't have consistency in enums as lower case we have to default to checking both for lowercase and uppercase values.
New behavior for deserializing enums
1. Check for JsonCreator and compare using that
2. Check for JsonValue and compare using that
3. Compare to the enum.name()  …

Add jsonValue check on Enum deserializer, default to checking name() function of enum

---

data-prepper-plugins/dissect-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/dissect/DissectProcessorConfig.java
data-prepper-plugins/dissect-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/dissect/DissectProcessorConfigTest.java
data-prepper-plugins/geoip-processor/src/main/java/org/opensearch/dataprepper/plugins/geoip/processor/EntryConfig.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/TargetType.java

The geoip and dissect processors contained a `Collection<Enum>` and a `Map<String, Enum>` that the new enum deserializer was getting called for, and it does not deserialize on the types. 
As a short term fix, add @JsonIgnore annotation the geoip enum getter method, and modify the dissect processor to use Map<String, String> with a custom AssertTrue validation and conversion of the target type from string to enum

Fix enum deserialization for geoip and dissect processors

---

data-prepper-plugins/dissect-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/dissect/DissectProcessorConfig.java

Default target types map to empty map to avoid null pointer exception

Default target types to empty map to avoid NPE

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/annotations/ConditionalRequired.java
data-prepper-plugin-schema/src/main/java/org/opensearch/dataprepper/schemas/JsonSchemaConverter.java
data-prepper-plugin-schema/src/test/java/org/opensearch/dataprepper/schemas/JsonSchemaConverterTest.java
data-prepper-plugins/date-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/date/DateProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/AddEntryProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/ConvertEntryTypeProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/ListToMapProcessorConfig.java
data-prepper-plugins/mutate-string-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutatestring/SplitStringProcessorConfig.java
data-prepper-plugins/split-event-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/splitevent/SplitEventProcessorConfig.java

This PR 
* introduces @ConditionalRequired annotation to express conditional required attribute in schema
* modify json schema generator to generate the if-then-else schema based off @ConditionalRequired annotation (Ref: https://github.com/victools/jsonschema-generator/blob/7a5cb07f81f446f149483bcf4b1ba7e2831e6868/jsonschema-examples/src/main/java/com/github/victools/jsonschema/examples/IfThenElseExample.java)
* backfill 

ENH: conditional required annotation for schema

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/source/coordinator/enhanced/EnhancedSourcePartition.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/source/coordinator/enhanced/EnhancedSourcePartitionTest.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/source/coordinator/enhanced/TestInstantTypeProgressState.java

Adding Java Time module to jackson Object mapper to enable Java Time specific object types to be serializable and deserializable. 

Adding Java Time module to jackson Object mapper

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/JacksonEventKey.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/event/JacksonEventKeyTest.java

Json pointer uses ~ character as the escape sequence in some places. For example, a literal / in the key name will be escaped with ~1, but Data Prepper JacksonEventKey is blocking this by not allowing ~ character
Resolves #5101 

Allow ~ in keys for escaped json pointer characters

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/JacksonEventKey.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/event/JacksonEventTest.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/RenameKeyProcessor.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/RenameKeyProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/test/java/org/opensearch/dataprepper/plugins/processor/mutateevent/RenameKeyProcessorTests.java

It includes support for dynamic renaming of keys in rename processor where the user can now give a regex pattern to match the keys that needs to be replaced.
Resolves #4849 

Support for dynamic renaming of keys

---

README.md
RELEASING.md
TRIAGING.md
docs/developer_guide.md

This PR updates a few key files to call the project OpenSearch Data Prepper over Data Prepper.
See #4309.

Renames the project to OpenSearch Data Prepper.

---

data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/processor/LambdaProcessor.java
data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/processor/LambdaProcessorConfig.java
data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/processor/ResponseCardinality.java
data-prepper-plugins/aws-lambda/src/test/java/org/opensearch/dataprepper/plugins/lambda/processor/LambdaProcessorTest.java

Change response_cardinality config for lambda processor to response_events_match.
response_events_match = False will be the default and will use AggregateResponseEventHandling Strategy.
When true, it will use Strict Strategy.
Contributes towards  #5031 

Change response_cardinality config for lambda processor to response_events_match

---

data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/S3InputFile.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/S3ObjectWorker.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/s3/S3ObjectWorkerTest.java

Adds external origination time for events created from S3 Object. This applies to events created by both S3 SQS and S3Scan sources

Add external origination time for events created from S3 Object

---

data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/schema/SchemaManager.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/schema/SchemaManagerTest.java

Add getColumnDataTypes method to SchemaManager to get datatype for table columns.

Add getColumnDataTypes method to SchemaManager to get datatype for table columns

---

data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/model/DbMetadata.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/model/DbTableMetadata.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/model/DbMetadataTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/model/DbTableMetadataTest.java

Add model for table column metadata for Global state. The model will be stored in global state and will be available for export and bin log worker to fetch table column metadata such as data type.

Add model for table column metadata for Global state

---

data-prepper-plugins/kinesis-source/src/main/java/org/opensearch/dataprepper/plugins/kinesis/source/KinesisSource.java

This PR is to add an alternate name for the KDS source plugin `kinesis-data-streams` in data prepper. 

Add an alternate name for the KDS source plugin to "kinesis-data-streams"

---

data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaCustomConsumer.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/util/KafkaTopicConsumerMetrics.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaCustomConsumerTest.java

Pipeline latency is showing up as negative value some times. This fix makes sure that the time received from Kafka consumer record is valid. If it's not valid, it is replaced with last valid value. If last valid value is not present, current time is used.

Kafka time stamp fix

---

data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/source/KafkaSource.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/source/KafkaSourceTest.java

Fix Kafka source to override areAcknowlegementsEnabled. All sources supporting acknowledgements must override this interface to reflect the configured value.

Fix Kafka source to override areAcknowlegementsEnabled

---

data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/datatype/DataTypeHandler.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/datatype/DataTypeHelper.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/datatype/MySQLDataType.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/datatype/impl/BinaryTypeHandler.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/datatype/impl/JsonTypeHandler.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/datatype/impl/NumericTypeHandler.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/datatype/impl/SpatialTypeHandler.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/datatype/impl/StringTypeHandler.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/datatype/impl/TemporalTypeHandler.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/model/TableMetadata.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/datatype/impl/BinaryTypeHandlerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/datatype/impl/JsonTypeHandlerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/datatype/impl/NumericTypeHandlerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/datatype/impl/SpatialTypeHandlerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/datatype/impl/StringTypeHandlerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/datatype/impl/TemporalTypeHandlerTest.java

This PR introduces a DataType handling system to properly transform MySQL data types from binary format to their corresponding string representations. This is essential for both change stream processing and parquet file export processing where data from events may be encoded in bytes.
Some handler implementation are stubbed. Will add follow up PR when they are tested with correct implementation.
Contributes to #4561

Add MySQL DataType handler to transform datatype value

---

data-prepper-plugins/dissect-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/dissect/DissectProcessorConfig.java
data-prepper-plugins/drop-events-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/drop/DropEventProcessorConfig.java
data-prepper-plugins/flatten-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/flatten/FlattenProcessorConfig.java
data-prepper-plugins/geoip-processor/src/main/java/org/opensearch/dataprepper/plugins/geoip/processor/EntryConfig.java
data-prepper-plugins/geoip-processor/src/main/java/org/opensearch/dataprepper/plugins/geoip/processor/GeoIPProcessorConfig.java
data-prepper-plugins/grok-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/grok/GrokProcessorConfig.java
data-prepper-plugins/key-value-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/keyvalue/KeyValueProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/ListToMapProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/MapToListProcessorConfig.java
data-prepper-plugins/obfuscate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/obfuscation/ObfuscationProcessorConfig.java
data-prepper-plugins/obfuscate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/obfuscation/action/MaskActionConfig.java

Add examples into the following processors:
1. Dissect
2. Drop events
3. Flatten
4. Geoip
5. Grok
6. Key value
7. List to map
8. Lowercase string
9. Map to list
10. Obfuscate

Add examples into processor configs

---

data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/RenameKeyProcessorConfig.java
data-prepper-plugins/mutate-string-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutatestring/SplitStringProcessorConfig.java
data-prepper-plugins/mutate-string-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutatestring/SubstituteStringProcessorConfig.java
data-prepper-plugins/truncate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/truncate/TruncateProcessorConfig.java

Adds example values to `rename_keys`, `split_string`, `substitute_string`, and `truncate` processors.
N/A

Example values for rename_keys, split_string, substitute_string, truncate

---

data-prepper-plugins/kinesis-source/src/main/java/org/opensearch/dataprepper/plugins/kinesis/extension/KinesisLeaseConfig.java
data-prepper-plugins/kinesis-source/src/main/java/org/opensearch/dataprepper/plugins/kinesis/source/KinesisService.java
data-prepper-plugins/kinesis-source/src/test/java/org/opensearch/dataprepper/plugins/kinesis/extension/KinesisLeaseConfigSupplierTest.java
data-prepper-plugins/kinesis-source/src/test/java/org/opensearch/dataprepper/plugins/kinesis/extension/KinesisLeaseConfigTest.java
data-prepper-plugins/kinesis-source/src/test/java/org/opensearch/dataprepper/plugins/kinesis/source/KinesisServiceTest.java
data-prepper-plugins/kinesis-source/src/test/java/org/opensearch/dataprepper/plugins/kinesis/source/KinesisSourceTest.java
data-prepper-plugins/kinesis-source/src/test/resources/simple_pipeline_with_extensions.yaml

This PR is to add a `pipeline_identifier` to the data prepper config to ensure that the multiple pipelines can subscribe to the same KDS stream when using enhanced fan-out strategy. This is optional and by default would use the pipeline name as the identifier for the active subscription.

Pass the pipeline identifier as part of the data prepper config.

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/core/peerforwarder/PeerForwardingProcessorDecorator.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/core/peerforwarder/PeerForwardingProcessingDecoratorTest.java

Fix PeerForwardingProcessorDecorator to process records locally when exclude identification keys is set.
The changes in PR 5127 missed a step in execute() which is supposed to process records locally if peer forwarding is disabled for a processor

Fix PeerForwardingProcessorDecorator to process records locally when exclude identification keys is set

---

data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/RenameKeyProcessor.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/RenameKeyProcessorConfig.java

Signed-off-by: Divyansh Bokadia <dbokadia@amazon.com>
Dynamic renaming of keys bug fix

Dynamic renaming of keys bug fix

---

data-prepper-plugins/rds-source/build.gradle
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/coordination/PartitionFactory.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/coordination/partition/ResyncPartition.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/coordination/state/ResyncProgressState.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/coordination/state/StreamProgressState.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/export/DataFileLoader.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/leader/LeaderScheduler.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/model/ForeignKeyAction.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/model/ForeignKeyRelation.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/model/ParentTable.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/model/TableMetadata.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/resync/CascadingActionDetector.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/schema/SchemaManager.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/BinlogEventListener.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/StreamWorkerTaskRefresher.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/coordination/PartitionFactoryTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/resync/CascadingActionDetectorTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/schema/SchemaManagerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/stream/BinlogEventListenerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/stream/StreamWorkerTaskRefresherTest.java

When a foreign key with cascading action defined, the cascading changes in the child tables won't appear in binlog. The rds source plugin will try to detect cascading changes and generate pipeline events for them. This PR covers the first part to detect cascades and save the information in the coordination store (as resync partitions). Next PR (#5171) will cover the processing of those partitions.

Detect cascading actions in RDS source

---

data-prepper-plugin-schema/src/main/java/org/opensearch/dataprepper/schemas/PluginConfigsJsonSchemaConverter.java
data-prepper-plugin-schema/src/test/java/org/opensearch/dataprepper/schemas/PluginConfigsJsonSchemaConverterTest.java

Plugin names are formatted like `plugin_name` but opensearch.org documentation links format plugin names like `plugin-name`. This PR adds the conversion behavior to generate valid documentation links in the schemas.

Replace underscores in plugin names with dashes for correct doc link

---

data-prepper-plugins/kinesis-source/src/main/java/org/opensearch/dataprepper/plugins/kinesis/source/KinesisSource.java

This PR is to add an alternate name for the KDS source plugin kinesis-data-streams in data prepper.

Change name of Kinesis source plugin

---

data-prepper-plugin-schema-cli/README.md
data-prepper-plugin-schema-cli/build.gradle
data-prepper-plugin-schema-cli/src/main/java/org/opensearch/dataprepper/schemas/DataPrepperPluginSchemaExecute.java
data-prepper-plugin-schema-cli/src/main/resources/example-primary-fields-override.yaml
data-prepper-plugin-schema/src/main/java/org/opensearch/dataprepper/schemas/PluginConfigsJsonSchemaConverter.java
data-prepper-plugin-schema/src/main/java/org/opensearch/dataprepper/schemas/PrimaryFieldsOverride.java
data-prepper-plugin-schema/src/test/java/org/opensearch/dataprepper/schemas/PluginConfigsJsonSchemaConverterIT.java
data-prepper-plugin-schema/src/test/java/org/opensearch/dataprepper/schemas/PluginConfigsJsonSchemaConverterTest.java

This PR introduces custom primary fields into plugin JSON schemas.

ENH: introduce primary fields in plugin schemas

---

data-prepper-plugins/opensearch/README.md

Updated the readme with example for opensearch plugin to use date processor in combination with openaearch sink to ingest into indices based on the timestamp from a field of the incoming record.
https://github.com/opensearch-project/data-prepper/issues/4832

Updated the readme for opensearch plugin to use date processor in combination with Opensearch sink

---

e2e-test/build.gradle
release/archives/build.gradle
release/docker/build.gradle

Fix deprecation warning
```
The AbstractArchiveTask.archivePath property has been deprecated. This is
scheduled to be removed in Gradle 9.0. Please use the archiveFile property
instead. For more information, please refer to
https://docs.gradle.org/8.8/dsl/org.gradle.api.tasks.bundling.AbstractArchiveTask.html#org.gradle.api.tasks.bundling.AbstractArchiveTask:archivePath
in the Gradle documentation.
```
`.archivePath` has been deprecated and will be removed in Gradle 9.0. Use `.archiveFile.get().asFile` instead.
Resolves #[Issue number to be closed when this PR is merged] - **did not find a related issue**, consider this to be a minor improvement
For more information on …

Replace deprecated archivePath

---

data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/datatype/impl/SpatialTypeHandler.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/datatype/impl/SpatialTypeHandlerTest.java

Add MySQL to OpenSearch Geometry data type transformation
- Implement SpatialTypeHandler transformation for processing geometric shapes
- Support WKT formats (Point, LineString, Polygon, MultiPoint, MultiLineString, MultiPolygon)

Add MySQL to OpenSearch Geometry data type transformation

---

data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateProcessorConfig.java
data-prepper-plugins/anomaly-detector-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/anomalydetector/AnomalyDetectorProcessorConfig.java
data-prepper-plugins/common/src/main/java/org/opensearch/dataprepper/plugins/processor/DelayProcessor.java
data-prepper-plugins/csv-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/csv/CsvProcessorConfig.java
data-prepper-plugins/decompress-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/decompress/DecompressProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/AddEntryProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/ConvertEntryTypeProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/CopyValueProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/DeleteEntryProcessorConfig.java

Adds examples annotations for the following processors
* add_entries
* copy_values
* convert_entry_type
* aggregate
* anomaly_detector
* delay
* csv
* decompress

Adds example annotations to a handful of processors

---

data-prepper-plugins/parquet-codecs/src/main/java/org/opensearch/dataprepper/plugins/codec/parquet/GenericRecordJsonEncoder.java
data-prepper-plugins/parquet-codecs/src/test/java/org/opensearch/dataprepper/plugins/codec/parquet/GenericRecordJsonEncoderTest.java

Currently, the parquet reader is handling bytes values by always adding a key-value pair of { "bytes": "escaped-json-string" } to the Event. 
When there is a decimal value, it still writes this bytes key-value pair, even though it can be converted to decimal and can be added as a raw value in the Event.
This change just checks the decoded String of the bytes to see if they can be converted to big decimal, and if so they will be added as a raw decimal value to the Event. Otherwise the same behavior as before is kept.
Tested this on a sample parquet file that was previously getting "bytes" key-value for decimal values
For more information on following Developer Certificate of …

Fix parquet decimal bytes values

---

data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/BinlogEventListener.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/stream/BinlogEventListenerTest.java

It's possible that value of a primary key is changed in MySQL update statement. When this happens, we need to generate two events - one for indexing the updated record (with the new primary key value), and another one for deleting the old record. This PR add changes to handle it.
Tested against an Aurora MySQL table and verified that the two expected events were generated.

Handle primary key change events in RDS source

---

data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/datatype/impl/TemporalTypeHandler.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/BinlogClientFactory.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/datatype/impl/TemporalTypeHandlerTest.java

Add support for MySQL Date/Time/TimeStamp/DateTime date type transformation between binlog and S3 export formats to OpenSearch.
MySQL binlog represents temporal types as follows:
- DATE: long value representing milliseconds since epoch (1970-01-01)
- TIME: long value representing milliseconds since epoch (1970-01-01 00:00:00)
- DATETIME: long value representing microseconds since epoch (1970-01-01 00:00:00)
- YEAR: 4-digit year value (Example: 2024)
S3 export formats:
- DATE: "yyyy-MM-dd" (Example: "2024-01-15")
- TIME: "HH:mm:ss" (Example: "14:30:00") 
- DATETIME: "yyyy-MM-dd HH:mm:ss[.SSSSSS]" (Example: "2024-01-15 14:30:00.123456")
Note: Fractional seconds are optional for DATETIME
- YEAR: "yyyy" (Example: "2024")
Contributes to #4561
By submitting this pull request, I confirm that my …

Add support for MySQL Date/Time/TimeStamp/DateTime date type transformation

---

data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/datatype/impl/TemporalTypeHandler.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/datatype/impl/TemporalTypeHandlerTest.java

Handle microseconds in datetime/timestamp and time MySQL data type. Also handle date special case.
Contributes to https://github.com/opensearch-project/data-prepper/issues/4561

Handle microseconds in datetime/timestamp and time MySQL data type

---

data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/common/LambdaCommonHandler.java
data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/processor/LambdaProcessor.java
data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/sink/LambdaSink.java
data-prepper-plugins/aws-lambda/src/test/java/org/opensearch/dataprepper/plugins/lambda/common/LambdaCommonHandlerTest.java
data-prepper-plugins/aws-lambda/src/test/java/org/opensearch/dataprepper/plugins/lambda/common/accumulator/InMemoryBufferTest.java
data-prepper-plugins/aws-lambda/src/test/java/org/opensearch/dataprepper/plugins/lambda/processor/LambdaProcessorTest.java
data-prepper-plugins/aws-lambda/src/test/java/org/opensearch/dataprepper/plugins/lambda/utils/LambdaTestSetupUtil.java
data-prepper-plugins/aws-lambda/src/test/resources/lambda-processor-success-config.yaml

Simplified the flow by removing the approach to pass the call-back methods. This helps with code readability and unit testing.

refactored to remove handlers passing

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/metrics/PluginMetrics.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/processor/AbstractProcessor.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/metrics/PluginMetricsTest.java
data-prepper-plugins/aws-lambda/src/integrationTest/java/org/opensearch/dataprepper/plugins/lambda/LambdaProcessorSinkIT.java
data-prepper-plugins/aws-lambda/src/integrationTest/java/org/opensearch/dataprepper/plugins/lambda/processor/LambdaProcessorIT.java
data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/processor/LambdaProcessor.java
data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/sink/LambdaSink.java
data-prepper-plugins/aws-lambda/src/test/java/org/opensearch/dataprepper/plugins/lambda/processor/LambdaProcessorTest.java

Fix lambda metrics. 
1. Fix PluginMetrics to allow changing name
2. Add request and response payload metrics in the processor

Fix lambda metrics

---

data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/StreamScheduler.java

There is currently a scenario where a DynamoDB stream shard can be continuously reprocessed, and after looking into the code it appears that this is due to an exception that results in the shard being given up, but Data Prpeper is not logging this exception anywhere

Add log for exceptions when processing DynamoDB shards

---

data-prepper-plugins/csv-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/csv/CsvProcessorConfig.java
data-prepper-plugins/date-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/date/DateProcessorConfig.java
data-prepper-plugins/decompress-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/decompress/DecompressProcessorConfig.java
data-prepper-plugins/grok-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/grok/GrokProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/AddEntryProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/ConvertEntryTypeProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/CopyValueProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/ListToMapProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/MapToListProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/RenameKeyProcessorConfig.java
data-prepper-plugins/obfuscate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/obfuscation/ObfuscationProcessorConfig.java
data-prepper-plugins/obfuscate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/obfuscation/action/MaskActionConfig.java
data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parse/ion/ParseIonProcessorConfig.java
data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parse/json/ParseJsonProcessorConfig.java
data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parse/xml/ParseXmlProcessorConfig.java

Add some missing examples and reorder processor configurations so "when" conditions are always at the bottom of the generated schema.

Add examples and reorder some processor configurations in schemas

---

data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/schema/ConnectionManager.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/schema/ConnectionManagerTest.java

TINYINT(1) columns show up as BIT type when we query the column types, which results in error:
```
2024-11-25T14:06:41,668 [rds-source-binlog-processor-1] ERROR org.opensearch.dataprepper.plugins.source.rds.stream.BinlogEventListener - Failed to process change event of type EXT_WRITE_ROWS
java.lang.IllegalArgumentException: Unsupported value type. The value is of type: class java.lang.Integer
at org.opensearch.dataprepper.plugins.source.rds.datatype.impl.NumericTypeHandler.handleBit(NumericTypeHandler.java:63) ~[rds-source-2.11.0-SNAPSHOT.jar:?]
at org.opensearch.dataprepper.plugins.source.rds.datatype.impl.NumericTypeHandler.handleNumericType(NumericTypeHandler.java:38) ~[rds-source-2.11.0-SNAPSHOT.jar:?]
at org.opensearch.dataprepper.plugins.source.rds.datatype.impl.NumericTypeHandler.ha …
```

Fix TINYINT(1) data type mapping in rds source

---

release/staging-resources-cdk/package-lock.json
release/staging-resources-cdk/package.json

MAINT: resolve CVEs by bumping up jest

---

.github/workflows/kinesis-source-integration-tests.yml

Add a github workflow action for running Kinesis integration tests
Resolves #[1082]

Add a github workflow action for running Kinesis integration tests

---

data-prepper-plugins/http-source/src/main/java/org/opensearch/dataprepper/plugins/source/loghttp/HTTPSource.java
data-prepper-plugins/http-source/src/test/java/org/opensearch/dataprepper/plugins/source/loghttp/HTTPSourceTest.java
data-prepper-plugins/otel-logs-source/src/test/java/org/opensearch/dataprepper/plugins/source/otellogs/OTelLogsSourceTest.java

Adding additional test coverage for http source and otel logs source

Http source otel logs source test coverage

---

data-prepper-plugins/otel-metrics-source/src/test/java/org/opensearch/dataprepper/plugins/source/otelmetrics/OTelMetricsSourceTest.java
data-prepper-plugins/otel-trace-source/src/test/java/org/opensearch/dataprepper/plugins/source/oteltrace/OTelTraceSourceTest.java

Adding additional test coverage for otel trace source and otel metrics source. Tests are for authentication handling and SSL/TLS validation

otel trace source and otel metrics source test coverage

---

release/release-notes/data-prepper.release-notes-2.10.2.md

This updates the 2.10.2 release notes with links to the CVE/GHSA published.
https://github.com/opensearch-project/data-prepper/security/advisories/GHSA-725p-63vv-v948
N/A

Updates Data Prepper 2.10.2 release notes with CVE

---

data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamAcknowledgementManager.java
data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamScheduler.java
data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamAcknowledgementManagerTest.java
data-prepper-plugins/otel-metrics-source/src/test/java/org/opensearch/dataprepper/plugins/source/otelmetrics/OTelMetricsSourceTest.java

There appears to be an issue with the DocumentDB source plugin in DataPrepper where, if the host is restarted, the pipeline is unable to continue consuming stream data. Upon further investigation, this occurs because the stream lease in the source coordination store is removed, preventing the pipeline from ingesting the affected stream partition.
To address this, we need metrics to monitor the cadence of checkpoints, acknowledgments, and lease extensions, providing better visibility into stream acknowledgment behavior.
This PR introduces additional metrics to the Stream Acknowledgment Manager, enabling improved visibility into checkpointing cadence, tracking both positive and negative acknowledgments, and monitoring when the lease for the current DataPrepper instance is extended.
By …

Add metrics to stream acknowledgement manager

---

data-prepper-plugins/dynamodb-source-coordination-store/src/main/java/org/opensearch/dataprepper/plugins/sourcecoordinator/dynamodb/DynamoDbClientWrapper.java
data-prepper-plugins/dynamodb-source-coordination-store/src/main/java/org/opensearch/dataprepper/plugins/sourcecoordinator/dynamodb/DynamoDbSourceCoordinationStore.java
data-prepper-plugins/dynamodb-source-coordination-store/src/test/java/org/opensearch/dataprepper/plugins/sourcecoordinator/dynamodb/DynamoDbClientWrapperTest.java
data-prepper-plugins/dynamodb-source-coordination-store/src/test/java/org/opensearch/dataprepper/plugins/sourcecoordinator/dynamodb/DynamoDbSourceCoordinationStoreTest.java

Data Prepper is not updating the expiration time on the source coordination table item when it tries to update the source partition to `ASSIGNED`. This PR is to add an expiration time on the item based on the ttl. 

Update expiration time based on ttl on the source coordinator item.

---

data-prepper-plugins/kinesis-source/src/integrationTest/java/org/opensearch/dataprepper/plugins/kinesis/source/KinesisSourceIT.java
data-prepper-plugins/kinesis-source/src/main/java/org/opensearch/dataprepper/plugins/kinesis/source/converter/KinesisRecordConverter.java
data-prepper-plugins/kinesis-source/src/main/java/org/opensearch/dataprepper/plugins/kinesis/source/processor/KinesisInputOutputRecord.java
data-prepper-plugins/kinesis-source/src/main/java/org/opensearch/dataprepper/plugins/kinesis/source/processor/KinesisRecordProcessor.java
data-prepper-plugins/kinesis-source/src/test/java/org/opensearch/dataprepper/plugins/kinesis/source/KinesisInputOutputRecordTest.java
data-prepper-plugins/kinesis-source/src/test/java/org/opensearch/dataprepper/plugins/kinesis/source/converter/KinesisRecordConverterTest.java
data-prepper-plugins/kinesis-source/src/test/java/org/opensearch/dataprepper/plugins/kinesis/source/processor/KinesisRecordProcessorTest.java

This PR is to add two new metrics for KDS source plugin named `bytesReceived` and `bytesProcessed` to track the size of throughput being ingested from Kinesis Data Streams.
Resolves #1082

Add new metrics for tracking bytes received and processed by KDS

---

data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamAcknowledgementManager.java

Remove NOISY log from Mongo StreamAcknowledgementManager. We have metric to capture when this condition occurs, so removing logs as they are noisy

Remove NOISY log from Mongo StreamAcknowledgementManager

---

data-prepper-plugins/opensearch/README.md
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/ConnectionConfiguration.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/ConnectionConfigurationTests.java

This PR flips the precedence between `cert` and `insecure` config options so that `insecure: true` overrides the presence of `cert`.
Resolves #5267

bug(opensearch-sink) Setting 'insecure' should override 'cert'

---

build.gradle
release/docker/Dockerfile
release/smoke-tests/data-prepper-tar/Dockerfile

In Dockerfile, run under the `nobody` user instead of root. Also chown some directories.
Resolves #5311

[Docker] Do not run container as root

---

data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/leader/LeaderScheduler.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/utils/TableUtil.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/leader/LeaderSchedulerTest.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/utils/TableUtilTest.java

Update requests to DynamoDB to provide the table ARN instead of the table name. This allows Data Prepper to use the new cross-account and resource policy changes available in DynamoDB.
This works for DynamoDB streams only. DynamoDB's export APIs do not support cross-account presently.
Sample from working pipeline that I tested.
```
source:
dynamodb:
tables:
- table_arn: arn:aws:dynamodb:us-west-2:123456789012:table/SampleCrossAccount
stream:
start_position: LATEST
aws:
sts_role_arn: arn:aws:iam::999999999999:role/DynamoDB-DataPrepper-CrossAccount
region: us-west-2
```
Resolves #4424 …

Support cross account DynamoDB tables for streams.

---

data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/export/DataFileSchedulerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/export/ExportSchedulerTest.java

Adds sleep time before verifying to reduce flakiness of the shutdown tests. I wasn't able to reproduce the error or verify the fix but adding sleep time helped previously with [another shutdown test](https://github.com/opensearch-project/data-prepper/blob/2f3a2804a456805107699721734d246be105405a/data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/stream/StreamSchedulerTest.java#L125).
https://github.com/opensearch-project/data-prepper/issues/3481#issuecomment-2581524346
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blo …

Fix flaky unit tests in Rds source

---

data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/SqsWorker.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/s3/SqsWorkerTest.java

When there are no messages pulled from the queue, the sqsMessageDelay metric is not being reported. When there are no messages pulled from the queue, that means the queue is empty and this can be reported as a delay of 0. 
Additionally, the sqsMessageDelay metric is currently reported at the time the S3 object is processed. This means that with `maximum_messages` at 10, for example, the 10th message will report high delay because it may take a long time for the previous 9 objects to be processed.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRI …

Report SQS message delay immediately after message is received, and as 0 when there are no messages found in queue

---

.github/CODEOWNERS
MAINTAINERS.md

Welcoming Santhosh Gandhe ([san81](https://github.com/san81)) to the Data Prepper maintainers.
Santhosh has contributed [15 merged PRs](https://github.com/opensearch-project/data-prepper/pulls?q=is%3Apr+author%3Asan81+is%3Aclosed). A few of these to highlight:
* He created a PR that allows plugins to have their own application context so that they can use dependency injection ([#5012](https://github.com/opensearch-project/data-prepper/pull/5012)) which also required a refactoring to Data Prepper core to use different packages ([#5056](https://github.com/opensearch-project/data-prepper/pull/5056)).
* Several PRs to improve the AWS Lambda processor/sink: ([#5204](https://github.com/opensearch-project/data-prepper/pull/5204), [#5211](https://github.com/opensearch-project/data-prepper/pull/521 …

Welcoming Santhosh Gandhe (san81) to the Data Prepper maintainers.

---

.github/workflows/gradle.yml
.github/workflows/kafka-plugin-integration-tests.yml
.github/workflows/kinesis-source-integration-tests.yml
.github/workflows/opensearch-sink-opendistro-integration-tests.yml
.github/workflows/opensearch-sink-opensearch-integration-tests.yml

Github has deprecated actions/upload-artifact@v3 and actions/download-artifact@v3.
Updating integration tests for kafka and kineses to version4.
OpenSearchSink and gradle.yml integration tests are updated again in PR #5273 , might cause merge conflicts

github actions/ artifacts v3 to v4

---

data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/MapToListProcessor.java
data-prepper-plugins/mutate-event-processors/src/test/java/org/opensearch/dataprepper/plugins/processor/mutateevent/MapToListProcessorTest.java

Get rid of the use of List.of and Map.of to allow for null values in input map for map_to_list processor
Resolves #5341 

Fix NPE in map to list processor

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/plugin/PluginConfigVariable.java
data-prepper-plugin-framework/src/test/java/org/opensearch/dataprepper/plugin/VariableExpanderTest.java
data-prepper-plugins/aws-plugin/src/main/java/org/opensearch/dataprepper/plugins/aws/AwsPluginConfigVariable.java
data-prepper-plugins/aws-plugin/src/test/java/org/opensearch/dataprepper/plugins/aws/AwsPluginConfigVariableTest.java
data-prepper-plugins/saas-source-plugins/jira-source/src/main/java/org/opensearch/dataprepper/plugins/source/jira/rest/auth/JiraOauthConfig.java
data-prepper-plugins/saas-source-plugins/jira-source/src/test/java/org/opensearch/dataprepper/plugins/source/jira/rest/auth/JiraOauthConfigTest.java
data-prepper-plugins/saas-source-plugins/jira-source/src/test/java/org/opensearch/dataprepper/plugins/source/jira/utils/MockPluginConfigVariableImpl.java

There is already scheduled refresh feature for AWS secrets but with the new enhancement of updating the secret, we need on demand refresh of the secrets to minimize the delay in getting new secrets into the OCUs that are holding up to the old secrets. The fix here is to provide an option to trigger on demand refresh of the secrets.

Refreshing AWS Secret values on demand

---

data-prepper-plugins/kinesis-source/src/main/java/org/opensearch/dataprepper/plugins/kinesis/source/KinesisService.java
data-prepper-plugins/kinesis-source/src/test/java/org/opensearch/dataprepper/plugins/kinesis/source/KinesisServiceTest.java

Polling retrieval config is passed to creation of KCL scheduler instead of new default retrieval config if consumer strategy is declared as polling
Resolves #5269 

Fixed kinesis retrieval config argument passing to KCL scheduler

---

data-prepper-plugins/saas-source-plugins/jira-source/src/main/java/org/opensearch/dataprepper/plugins/source/jira/JiraClient.java
data-prepper-plugins/saas-source-plugins/jira-source/src/main/java/org/opensearch/dataprepper/plugins/source/jira/JiraSourceConfig.java
data-prepper-plugins/saas-source-plugins/jira-source/src/main/java/org/opensearch/dataprepper/plugins/source/jira/rest/auth/JiraOauthConfig.java
data-prepper-plugins/saas-source-plugins/jira-source/src/test/java/org/opensearch/dataprepper/plugins/source/jira/JiraClientTest.java
data-prepper-plugins/saas-source-plugins/source-crawler/src/main/java/org/opensearch/dataprepper/plugins/source/source_crawler/base/Crawler.java
data-prepper-plugins/saas-source-plugins/source-crawler/src/main/java/org/opensearch/dataprepper/plugins/source/source_crawler/base/CrawlerClient.java
data-prepper-plugins/saas-source-plugins/source-crawler/src/main/java/org/opensearch/dataprepper/plugins/source/source_crawler/base/CrawlerSourceConfig.java
data-prepper-plugins/saas-source-plugins/source-crawler/src/main/java/org/opensearch/dataprepper/plugins/source/source_crawler/base/CrawlerSourcePlugin.java
data-prepper-plugins/saas-source-plugins/source-crawler/src/main/java/org/opensearch/dataprepper/plugins/source/source_crawler/coordination/scheduler/WorkerScheduler.java
data-prepper-plugins/saas-source-plugins/source-crawler/src/test/java/org/opensearch/dataprepper/plugins/source/source_crawler/base/CrawlerTest.java
data-prepper-plugins/saas-source-plugins/source-crawler/src/test/java/org/opensearch/dataprepper/plugins/source/source_crawler/coordination/scheduler/WorkerSchedulerTest.java

Adding the end to end Acknowledgment handling in the common code i.e. source-crawler (instead of just in Jira source) so that it will be available for any future sources that we add.
This PR also has some minor clean up on the OAuthConfig class.

Handling end to end acknowledgement in Jira Source

---

data-prepper-plugins/saas-source-plugins/jira-source/src/main/java/org/opensearch/dataprepper/plugins/source/jira/JiraSource.java
data-prepper-plugins/saas-source-plugins/jira-source/src/main/java/org/opensearch/dataprepper/plugins/source/jira/JiraSourceConfig.java
data-prepper-plugins/saas-source-plugins/jira-source/src/test/java/org/opensearch/dataprepper/plugins/source/jira/JiraSourceConfigTest.java
data-prepper-plugins/saas-source-plugins/source-crawler/src/main/java/org/opensearch/dataprepper/plugins/source/source_crawler/base/Crawler.java
data-prepper-plugins/saas-source-plugins/source-crawler/src/main/java/org/opensearch/dataprepper/plugins/source/source_crawler/base/CrawlerSourceConfig.java
data-prepper-plugins/saas-source-plugins/source-crawler/src/main/java/org/opensearch/dataprepper/plugins/source/source_crawler/base/CrawlerSourcePlugin.java
data-prepper-plugins/saas-source-plugins/source-crawler/src/main/java/org/opensearch/dataprepper/plugins/source/source_crawler/coordination/scheduler/LeaderScheduler.java
data-prepper-plugins/saas-source-plugins/source-crawler/src/test/java/org/opensearch/dataprepper/plugins/source/source_crawler/base/CrawlerSourcePluginTest.java
data-prepper-plugins/saas-source-plugins/source-crawler/src/test/java/org/opensearch/dataprepper/plugins/source/source_crawler/base/CrawlerTest.java
data-prepper-plugins/saas-source-plugins/source-crawler/src/test/java/org/opensearch/dataprepper/plugins/source/source_crawler/coordination/scheduler/LeaderSchedulerTest.java

Allow user to specify batch_size field in jira source. 
Also works for all future saas_crawler sources.
Default value is 50 in jira source
cleanup unnecessary config fields

add batch size field for jira source

---

data-prepper-plugins/otel-trace-raw-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/oteltrace/OTelTraceRawProcessorTest.java

Caffeine cache evictions happen in async mode that leaves no control to a test method to guarantee the max size limit is enforced. If we have to enforce max size then we need to ask Caffeine to do evictions synchronously. But setting the max cache size to zero disables the cache and gives more consistent behavior.  Read more here https://www.javadoc.io/doc/com.github.ben-manes.caffeine/caffeine/2.0.3/com/github/benmanes/caffeine/cache/Caffeine.html#maximumSize-long-
To fix this flaky test, I suggest to set the max size to zero. Basically, disable the cache instead of setting the max size to 1. 
For more information …

Fix for the flaky OTel log test - to give it a consistent behavior 

---

data-prepper-plugins/buffer-common/src/main/java/org/opensearch/dataprepper/buffer/common/BufferAccumulator.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaCustomConsumer.java

Adds debug logs for kafka consumers to debug why they are intermittently pausing

Add debug logs for Kafka consumer

---

data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/buffer/BufferTopicConfig.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/buffer/KafkaBuffer.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaCustomConsumerFactory.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/util/KafkaTopicConsumerMetrics.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/buffer/KafkaBufferTest.java

When data prepper scales horizontally and removes data prepper instances, this can cause instability due to using the RangeAssignor, since the behavior for RangeAssignor is 
```
When a rebalance occurs, all consumers drop all their partitions and get reassigned (a full rebalance).
```
CoopeartiveStickyAssignor will gradually release partitions instead of dropping them all at once and reassigning when a consumer leave the group
Additionally, the `fetch.max.wait.ms` at 500 ms and `fetch.min.bytes` as 1 will lead to many more calls to consume and return smaller number of records. Changing this to 1000 ms and 2 kb will lead to less calls to consume and more records being returned in each poll call, which will also lower the utilization on the kafka cluster.
Lastly, the Kafka buffer consumers …

Change Kafka Buffer defaults for fetch.max.wait.ms, fetch.min.bytes, partition.assignment.strategy, close consumer on shutdown

---

data-prepper-plugins/saas-source-plugins/jira-source/src/main/java/org/opensearch/dataprepper/plugins/source/jira/JiraService.java
data-prepper-plugins/saas-source-plugins/jira-source/src/main/java/org/opensearch/dataprepper/plugins/source/jira/JiraSourceConfig.java
data-prepper-plugins/saas-source-plugins/jira-source/src/main/java/org/opensearch/dataprepper/plugins/source/jira/rest/JiraRestClient.java
data-prepper-plugins/saas-source-plugins/jira-source/src/main/java/org/opensearch/dataprepper/plugins/source/jira/rest/auth/JiraOauthConfig.java
data-prepper-plugins/saas-source-plugins/jira-source/src/main/java/org/opensearch/dataprepper/plugins/source/jira/utils/AddressValidation.java
data-prepper-plugins/saas-source-plugins/source-crawler/src/main/java/org/opensearch/dataprepper/plugins/source/source_crawler/coordination/partition/LeaderPartition.java
data-prepper-plugins/saas-source-plugins/source-crawler/src/main/java/org/opensearch/dataprepper/plugins/source/source_crawler/coordination/scheduler/WorkerScheduler.java

prevent over logging stack traces in jira source

Improve Jira logging

---

data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/plugin/DefaultPluginFactoryIT.java
data-prepper-plugin-framework/src/main/java/org/opensearch/dataprepper/plugin/DefaultPluginFactory.java
data-prepper-plugin-framework/src/main/java/org/opensearch/dataprepper/plugin/PluginBeanFactoryProvider.java
data-prepper-plugin-framework/src/test/java/org/opensearch/dataprepper/plugin/DefaultPluginFactoryTest.java
data-prepper-plugin-framework/src/test/java/org/opensearch/dataprepper/plugin/PluginBeanFactoryProviderTest.java
data-prepper-plugin-framework/src/test/java/org/opensearch/dataprepper/plugins/configtest/TestComponentWithConfigInject.java
data-prepper-plugins/otel-trace-raw-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/oteltrace/OTelTraceRawProcessorTest.java
data-prepper-plugins/saas-source-plugins/jira-source/src/main/java/org/opensearch/dataprepper/plugins/source/jira/JiraService.java
data-prepper-plugins/saas-source-plugins/jira-source/src/main/java/org/opensearch/dataprepper/plugins/source/jira/rest/JiraRestClient.java
data-prepper-plugins/saas-source-plugins/jira-source/src/test/java/org/opensearch/dataprepper/plugins/source/jira/JiraIteratorTest.java
data-prepper-plugins/saas-source-plugins/jira-source/src/test/java/org/opensearch/dataprepper/plugins/source/jira/JiraServiceTest.java
data-prepper-plugins/saas-source-plugins/jira-source/src/test/java/org/opensearch/dataprepper/plugins/source/jira/rest/JiraRestClientTest.java
data-prepper-plugins/saas-source-plugins/source-crawler/src/main/java/org/opensearch/dataprepper/plugins/source/source_crawler/base/Crawler.java
data-prepper-plugins/saas-source-plugins/source-crawler/src/main/java/org/opensearch/dataprepper/plugins/source/source_crawler/coordination/scheduler/WorkerScheduler.java
data-prepper-plugins/saas-source-plugins/source-crawler/src/test/java/org/opensearch/dataprepper/plugins/source/source_crawler/base/CrawlerTest.java

Making the PluginMetrics as an injectable bean so that we can simply inject this bean in any other spring bean.
Also, clean up some unused variables in Jira source.
Fixed a flaky test in Otel trace processor

Plugin metrics injection

---

data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateProcessorConfig.java
data-prepper-plugins/anomaly-detector-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/anomalydetector/AnomalyDetectorProcessorConfig.java
data-prepper-plugins/anomaly-detector-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/anomalydetector/modes/RandomCutForestModeConfig.java
data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/processor/LambdaProcessorConfig.java
data-prepper-plugins/date-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/date/DateProcessorConfig.java
data-prepper-plugins/drop-events-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/drop/DropEventProcessorConfig.java
data-prepper-plugins/flatten-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/flatten/FlattenProcessorConfig.java
data-prepper-plugins/key-value-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/keyvalue/KeyValueProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/AddEntryProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/ConvertEntryTypeProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/CopyValueProcessorConfig.java
data-prepper-plugins/obfuscate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/obfuscation/ObfuscationProcessorConfig.java

Updated some processor schema descriptions based on internal review and aliased a handful of processor configuration names. Built successfully locally.

schema revisions, add json aliases

---

data-prepper-plugins/rds-source/build.gradle
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/resync/CascadingActionDetector.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/BinlogEventListener.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/ChangeEventStatus.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/LogicalReplicationClient.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/LogicalReplicationEventProcessor.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/StreamCheckpointManager.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/StreamCheckpointer.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/StreamWorkerTaskRefresher.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/export/DataFileLoaderTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/stream/LogicalReplicationClientTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/stream/LogicalReplicationEventProcessorTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/stream/StreamCheckpointManagerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/stream/StreamCheckpointerTest.java

Add e2e ack, checkpointing and metrics to Postgres stream processing. 
This is very similar to MySQL stream processing - binlogCoordinate in MySQL vs logSequenceNumber in Postgres. This PR refactors `StreamCheckpointer` and `StreamCheckpointManager` to support both binlog coordinates and log sequence numbers.
Contributes to #5309 

Add e2e ack, checkpointing and metrics to Postgres stream processing

---

MAINTAINERS.md

We previously removed `asifsmohammed` from the CODEOWNERS because of an error. See #4800. This PR keeps these two files in sync.
N/A

Moves asifsmohammed to the Emeritus section.

---

data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/SqsWorker.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/configuration/SqsOptions.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/parser/ParsedMessage.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/s3/SqsWorkerTest.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/s3/parser/ParsedMessageTest.java

Adds an option `max_receive_count` to the sqs configuration to allow for deletion of messages that have been received more than X times. This is not enabled by default
* When ApproximateReceiveCount is greater than 1, do not record the sqsMessageDelay metric

Add max_receive_count configuration option in S3-SQS source to delete messages that have been received many times

---

release/archives/linux/data-prepper-jdk-x64.sh
release/archives/linux/data-prepper-x64.sh

Sets the JVM default encoding to UTF-8 by including `-Dfile.encoding=UTF-8` in the JVM arguments. With this, we use UTF-8 by default. I found that this fixes writing to S3 with Unicode data.
Some data I got out of S3 with this fix.
```
{"test":"😀!!ああ😀!!ああ","id":"abc11"}
{"test":"😀!!ああ😀!!ああ😀!!ああ","id":"😀3"}
```
Resolves #5238.

Set the JVM file encoding to UTF-8. 

---

data-prepper-plugins/aws-lambda/src/integrationTest/java/org/opensearch/dataprepper/plugins/lambda/sink/LambdaSinkIT.java
data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/common/LambdaCommonHandler.java
data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/common/accumlator/InMemoryBuffer.java
data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/common/accumlator/InMemoryBufferSynchronized.java
data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/common/client/LambdaClientFactory.java
data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/common/util/ThresholdCheck.java
data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/sink/LambdaSink.java
data-prepper-plugins/aws-lambda/src/test/java/org/opensearch/dataprepper/plugins/lambda/common/accumulator/InMemoryBufferSynchronizedTest.java
data-prepper-plugins/aws-lambda/src/test/java/org/opensearch/dataprepper/plugins/lambda/sink/LambdaSinkTest.java

Add Stateful Buffering to LambdaSink
Resolves #5353

Add stateful buffer for lambda sink

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/acknowledgements/AcknowledgementSet.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/core/acknowledgements/DefaultAcknowledgementSet.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/core/acknowledgements/DefaultProgressCheck.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/core/acknowledgements/DefaultAcknowledgementSetTests.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/DynamoDBSourceConfig.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/export/DataFileCheckpointer.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/export/DataFileLoader.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/export/DataFileLoaderFactory.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/ShardConsumer.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/StreamCheckpointer.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/export/DataFileLoaderFactoryTest.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/export/DataFileLoaderTest.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/ShardConsumerTest.java

Fixes acknowledgment sets expiring from Dynamo streams by increasing expiry timeout in progress check
* Increase default s3_data_file_acknowledgment_timeout from 5 minutes to 15 minutes. This default is too low and causes issues for users when they have high buffer usage.
* Fixes another issue where shard partitions would time out on ownership while waiting for export by increasing the interval between checkpoints and increasing the ownership timeout increase for checkpoints on shards.
Tested by running a Dynamo pipeline and verified that no acknowledgments were expiring.
Resolves #5412  …

Add support to increase acknowledgment expiry and use in progress check for Dynamo source

---

data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSink.java

Add NOISY marker to opensearch sink failure logs

Add NOISY marker to opensearch sink failure logs

---

data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/converter/MetadataKeyAttributes.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/converter/RecordConverter.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/coordination/state/DataFileProgressState.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/export/DataFileLoader.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/export/ExportScheduler.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/model/TableMetadata.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/resync/MySQLResyncWorker.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/schema/PostgresSchemaManager.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/BinlogEventListener.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/LogicalReplicationEventProcessor.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/converter/ExportRecordConverterTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/converter/StreamRecordConverterTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/datatype/mysql/handler/BinaryTypeHandlerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/export/DataFileLoaderTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/export/ExportSchedulerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/resync/MySQLResyncWorkerTest.java

Postgres tables are specified as `database.schema.table`, while MySQL tables are specified as `database.table`. This PR fixes an issue that the metadata in Postgres export and stream are not consistent. 
In summary, we use `databaseName`, `schemaName` and `tableName` across the rds source plugin. `schemaName` is specific for Postgres, but for MySQL, we also fill this field with the same value as `databaseName`.
Also refactors `TableMetadata` to use builder pattern. A lot of its usages in test code were updated.
Contributes to #5309  …

Postgres schema name fix

---

data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/converter/StreamRecordConverter.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/converter/StreamRecordConverterTest.java

Manually Parse DDB Records
- Tested by adding control characters to test_writeSingleRecordToBuffer_with_other_data in StreamRecordConveterTest
- Tested by running DynamoDB source pipeline on local and ingesting records with control characters successfully.
- Tested by running DynamoDB source pipeline on local and ingesting records with more complex data structures like lists, maps, lists and maps in lists, and lists and maps in maps as well as every other ddb data type.  Compared output to output of unchanged dataprepper.
Resolves #5027 .  Bug ingesting control characters from dynamo db …

Deal with Control Characters in DynamoDB

---

settings.gradle

Updates the opensearch-java client from `2.8.1` to `2.20.0` version. This is needed to support `flat_object`object field type in index template of data prepper. Data-Prepper uses opensearch-java client `2.8.1` version which doesn't have support for `flat_object`, to fix this we need to upgrade opensearch-java client to atleast `2.8.2` or greater version. https://github.com/opensearch-project/opensearch-java/commit/c7abca3697154b08da5e634b3635348f2236e598#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edL7
Resolves #5425  …

Upgrade opensearch-java client to 2.20.0 version.

---

data-prepper-plugins/saas-source-plugins/confluence-source/src/main/java/org/opensearch/dataprepper/plugins/source/confluence/ConfluenceService.java
data-prepper-plugins/saas-source-plugins/confluence-source/src/main/java/org/opensearch/dataprepper/plugins/source/confluence/ConfluenceSourceConfig.java
data-prepper-plugins/saas-source-plugins/confluence-source/src/main/java/org/opensearch/dataprepper/plugins/source/confluence/models/ConfluencePaginationLinks.java
data-prepper-plugins/saas-source-plugins/confluence-source/src/main/java/org/opensearch/dataprepper/plugins/source/confluence/models/ConfluenceSearchResults.java
data-prepper-plugins/saas-source-plugins/confluence-source/src/main/java/org/opensearch/dataprepper/plugins/source/confluence/rest/ConfluenceRestClient.java
data-prepper-plugins/saas-source-plugins/confluence-source/src/test/java/org/opensearch/dataprepper/plugins/source/confluence/ConfluenceIteratorTest.java
data-prepper-plugins/saas-source-plugins/confluence-source/src/test/java/org/opensearch/dataprepper/plugins/source/confluence/ConfluenceServiceTest.java
data-prepper-plugins/saas-source-plugins/confluence-source/src/test/java/org/opensearch/dataprepper/plugins/source/confluence/rest/ConfluenceRestClientTest.java

With each search call, Confluence API returns the cursors for the next page that we should use to navigate through the search results. Enhanced the code to follow through these cursor based navigation

Confluence pagination handling

---

data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/RdsService.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/datatype/postgres/ColumnType.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/datatype/postgres/PostgresDataType.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/datatype/postgres/PostgresDataTypeHandler.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/datatype/postgres/handler/BinaryTypeHandler.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/datatype/postgres/handler/BooleanTypeHandler.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/export/DataFileLoader.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/schema/MySqlSchemaManager.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/schema/PostgresSchemaManager.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/schema/SchemaManager.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/utils/BytesHexConverter.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/datatype/postgres/handler/BinaryTypeHandlerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/datatype/postgres/handler/BooleanTypeHandlerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/schema/MySqlSchemaManagerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/schema/PostgresSchemaManagerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/utils/BytesHexConverterTest.java

Data type mapping for postgres export
- Added support for data type mapping for postgres export. 
- Added conversion to hexadecimal representation for binary data type for uniformity between rds stream and export. 
- Refactored the numeric and boolean data type names in postgres to represent its internal names.
Contributes to https://github.com/opensearch-project/data-prepper/issues/5309

Data type mapping for postgres export

---

data-prepper-plugins/saas-source-plugins/atlassian-commons/src/test/java/org/opensearch/dataprepper/plugins/source/atlassian/rest/auth/AtlassianOauthConfigTest.java

Using awaitability instead of Thread.sleep. A better approach that avoids any possibility of an infinite loop.

Using awaitability instead of Thread.sleep

---

build.gradle

After updating opensearch-java to 2.20 in #5426, we start to see this error in opensearch sink when writing to AWS OpenSearch domain:
```
org.opensearch.dataprepper.core.pipeline.common.FutureHelper - FutureTask failed due to: 
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'software.amazon.awssdk.http.ContentStreamProvider software.amazon.awssdk.http.ContentStreamProvider.fromByteArrayUnsafe(byte[])'
...
Caused by: java.lang.NoSuchMethodError: 'software.amazon.awssdk.http.ContentStreamProvider software.amazon.awssdk.http.ContentStreamProvider.fromByteArrayUnsafe(byte[])'
at org.opensearch.client.transport.aws.AwsSdk2Transport.prepareRequest(AwsSdk2Transport.java:347) ~[opensearch-java-2.20.0.jar:?]
at org.opensearch.client.transport.aws.AwsSdk2Transport.performReque …
```

Fix opensearch sink

---

data-prepper-plugins/saas-source-plugins/confluence-source/src/main/java/org/opensearch/dataprepper/plugins/source/confluence/rest/ConfluenceRestClient.java
data-prepper-plugins/saas-source-plugins/confluence-source/src/test/java/org/opensearch/dataprepper/plugins/source/confluence/rest/ConfluenceRestClientTest.java

When pagination in the OAuth2 flow, confluence host name should be constructed based on the OAuth2 cloud-id

Confluence oauth2 pagination fix

---

data-prepper-plugins/saas-source-plugins/confluence-source/src/main/java/org/opensearch/dataprepper/plugins/source/confluence/ConfluenceService.java
data-prepper-plugins/saas-source-plugins/confluence-source/src/main/java/org/opensearch/dataprepper/plugins/source/confluence/configuration/NameConfig.java
data-prepper-plugins/saas-source-plugins/confluence-source/src/test/java/org/opensearch/dataprepper/plugins/source/confluence/configuration/NameConfigTest.java
data-prepper-plugins/saas-source-plugins/jira-source/src/main/java/org/opensearch/dataprepper/plugins/source/jira/JiraService.java
data-prepper-plugins/saas-source-plugins/jira-source/src/main/java/org/opensearch/dataprepper/plugins/source/jira/configuration/NameConfig.java
data-prepper-plugins/saas-source-plugins/jira-source/src/test/java/org/opensearch/dataprepper/plugins/source/jira/configuration/NameConfigTest.java

Currently, we have some of these validations in the plugin service class but it is too late to validate. Pushing some of those validations to happen early on using our validation service checks
Also, Atlassian Jira doesn't allow more than 100 projects in an account so adjusted the validation accordingly. Put in a similar check for the Confluence as well.

Validations based on the validation service checks instead of plugin service checks

---

data-prepper-plugins/kinesis-source/src/main/java/org/opensearch/dataprepper/plugins/kinesis/source/exceptions/KinesisStreamNotFoundException.java
data-prepper-plugins/kinesis-source/src/main/java/org/opensearch/dataprepper/plugins/kinesis/source/processor/KinesisRecordProcessor.java
data-prepper-plugins/kinesis-source/src/test/java/org/opensearch/dataprepper/plugins/kinesis/source/processor/KinesisRecordProcessorTest.java

This PR is to add exception handling when stream information loaded from the lease table is not available. Currently, the error message is hard to understand and needs clarification about the exact issue which would help customers to understand the issue.

Modify the exception handling to be more descriptive when stream is not available

---

data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/plugin/DefaultPluginFactoryIT.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/core/parser/PipelineTransformerTests.java
data-prepper-pipeline-parser/build.gradle
data-prepper-pipeline-parser/src/main/java/org/opensearch/dataprepper/pipeline/parser/DataPrepperDeserializationProblemHandler.java
data-prepper-pipeline-parser/src/main/java/org/opensearch/dataprepper/pipeline/parser/DataPrepperDurationParser.java
data-prepper-pipeline-parser/src/main/java/org/opensearch/dataprepper/pipeline/parser/PipelinesDataflowModelParser.java
data-prepper-pipeline-parser/src/test/java/org/opensearch/dataprepper/pipeline/parser/DataPrepperDeserializationProblemHandlerTest.java
data-prepper-pipeline-parser/src/test/java/org/opensearch/dataprepper/pipeline/parser/DataPrepperDurationParserTest.java
data-prepper-plugin-framework/src/main/java/org/opensearch/dataprepper/plugin/ObjectMapperConfiguration.java
data-prepper-plugin-framework/src/test/java/org/opensearch/dataprepper/plugin/ExtensionPluginConfigurationConverterTest.java
data-prepper-plugin-framework/src/test/java/org/opensearch/dataprepper/plugin/ObjectMapperConfigurationTest.java
data-prepper-plugin-framework/src/test/java/org/opensearch/dataprepper/plugin/VariableExpanderTest.java

This PR enhances the error message in pipeline and plugin deserialization.
* fix null value handling in DataPrepperDurationParser
before
```
waf-access-log-pipeline.source.s3: caused by: Parameter "sqs.visibility_timeout" for plugin "s3" is invalid: text
```
after
```
waf-access-log-pipeline.source.s3: caused by: Parameter "sqs.visibility_timeout" for plugin "s3" is invalid: Durations must use either ISO 8601 notation or simple notations for seconds (60s) or milliseconds (100ms). Whitespace is ignored.
```
* simplify pipeline and plugin deserialization error message from Jackson by adding DataPrepperDeserializationProblemHandler
1. handleWeirdStringValue
before:
```
waf-access-log-pipeline.source.s3: caused by: Parameter "sqs.visibility_duplication_protection" for plugin "s3" is invalid: …
```

ENH: error message in pipeline and plugin deserialization

---

data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/coordination/state/PostgresStreamState.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/datatype/postgres/ColumnType.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/datatype/postgres/PostgresDataType.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/datatype/postgres/PostgresDataTypeHelper.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/datatype/postgres/handler/RangeTypeHandler.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/leader/LeaderScheduler.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/model/MessageType.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/schema/MySqlSchemaManager.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/schema/PostgresSchemaManager.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/LogicalReplicationEventProcessor.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/datatype/postgres/handler/RangeTypeHandlerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/schema/PostgresSchemaManagerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/stream/LogicalReplicationEventProcessorTest.java

- Adding enum and range datatype support for Postgres. 
- As enum does not have a fixed type_id, the enum columns are first fetched from the database and stored in Postgres Stream State and then the data type mapping is done. The enum type is not stored as user-defined enum type, instead we overwrite it to `enum` while storing.
- Range datatype has been added without including numeric range data type and multirange. Opensource does not support the high precision and scale of numeric postgres data type hence the mapping cannot be done here. 
- No corresponding multirange data type is supported in Opensource.
Contributes to https://github.com/opensearch-project/data-prepper/issues/5309
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …

Adding enum and range datatype support for postgres

---

data-prepper-plugins/saas-source-plugins/atlassian-commons/src/main/java/org/opensearch/dataprepper/plugins/source/atlassian/rest/AtlassianRestClient.java
data-prepper-plugins/saas-source-plugins/confluence-source/build.gradle
data-prepper-plugins/saas-source-plugins/confluence-source/src/main/java/org/opensearch/dataprepper/plugins/source/confluence/ConfluenceService.java
data-prepper-plugins/saas-source-plugins/confluence-source/src/main/java/org/opensearch/dataprepper/plugins/source/confluence/models/ConfluenceItem.java
data-prepper-plugins/saas-source-plugins/confluence-source/src/main/java/org/opensearch/dataprepper/plugins/source/confluence/models/ContentHistory.java
data-prepper-plugins/saas-source-plugins/confluence-source/src/main/java/org/opensearch/dataprepper/plugins/source/confluence/rest/ConfluenceRestClient.java
data-prepper-plugins/saas-source-plugins/confluence-source/src/main/java/org/opensearch/dataprepper/plugins/source/confluence/utils/ConfluenceNextLinkValidator.java
data-prepper-plugins/saas-source-plugins/confluence-source/src/main/java/org/opensearch/dataprepper/plugins/source/confluence/utils/CqlConstants.java
data-prepper-plugins/saas-source-plugins/confluence-source/src/test/java/org/opensearch/dataprepper/plugins/source/confluence/configuration/ContentHistoryTest.java
data-prepper-plugins/saas-source-plugins/confluence-source/src/test/java/org/opensearch/dataprepper/plugins/source/confluence/configuration/NameConfigTest.java
data-prepper-plugins/saas-source-plugins/confluence-source/src/test/java/org/opensearch/dataprepper/plugins/source/confluence/models/ContentHistoryTest.java
data-prepper-plugins/saas-source-plugins/confluence-source/src/test/java/org/opensearch/dataprepper/plugins/source/confluence/rest/ConfluenceRestClientTest.java
data-prepper-plugins/saas-source-plugins/confluence-source/src/test/java/org/opensearch/dataprepper/plugins/source/confluence/utils/ConfluenceNextLinkValidatorTest.java
data-prepper-plugins/saas-source-plugins/jira-source/src/main/java/org/opensearch/dataprepper/plugins/source/jira/JiraService.java
data-prepper-plugins/saas-source-plugins/jira-source/src/main/java/org/opensearch/dataprepper/plugins/source/jira/utils/JqlConstants.java
data-prepper-plugins/saas-source-plugins/source-crawler/src/main/java/org/opensearch/dataprepper/plugins/source/source_crawler/base/Crawler.java
data-prepper-plugins/saas-source-plugins/source-crawler/src/test/java/org/opensearch/dataprepper/plugins/source/source_crawler/model/ItemInfoTest.java
data-prepper-plugins/saas-source-plugins/source-crawler/src/test/java/org/opensearch/dataprepper/plugins/source/source_crawler/model/TestItemInfo.java

Extracting Confluence page history in the pagination API for checking pointing the date and time navigated so far.

Extracting Confluence page history

---

data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/parser/ParsedMessage.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/s3/parser/ParsedMessageTest.java

This PR fixes a NullPointerException that occurs when processing non S3-create events such as S3-delete due to the absence of an object size in the event notification. The `getSizeAsLong()` method can return null for delete events, which caused the application to throw an error.
Resolves #5448

S3-Source Bug Fix: Handle null object size for non S3-Create Events

---

data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/SqsWorker.java

S3-SQS delete objects on read adds an S3 object to the batch waiting for deletion unecessarily if the sqs message was not properly processed. While it is still only deleted if all SQS messages were deleted successfully (https://github.com/opensearch-project/data-prepper/blob/837d1a9a4bee8d1cb05e1f539bb41fa37c6fc070/data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/SqsWorker.java#L272), it should still not be marked for deletion at all

Only add s3 object to be deleted if optional is present for sqs message

---

data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/client/BsonHelper.java
data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/client/BsonHelperTest.java

We have identified an issue in the way we are handling MongoDB binary values for UUID_STANDARD type (4). 
The current implementation doesn't properly handle base64 encoding for UUID values when constructing queries.
Current Behavior:
- UUID values are not properly encoded when constructing queries
- Results in incorrect query conditions for UUID_STANDARD binary types
- Affects document retrieval when querying by UUID fields
- OpenSearch DocumentIDs are always base64 encoded for binary types
Root Cause:
- Binary type 4 (UUID_STANDARD) requires special handling
- Current code doesn't convert UUID to proper 16-byte format
- Missing base64 encoding step for UUID binary values
Fix:
- Add proper UUID to binary conversion
- Implement base64 encoding for UUID values
- Update query construction …

Handle Mongo Binary data type when subtype is UUID_STANDARD (value 4).

---

.github/workflows/data-prepper-trace-analytics-raw-span-e2e-tests.yml
data-prepper-plugins/otel-proto-common/src/main/java/org/opensearch/dataprepper/plugins/otel/codec/OTelProtoCodec.java
data-prepper-plugins/otel-proto-common/src/test/java/org/opensearch/dataprepper/plugins/otel/codec/OTelLogsProtoBufDecoderTest.java
data-prepper-plugins/otel-proto-common/src/test/java/org/opensearch/dataprepper/plugins/otel/codec/OTelProtoCodecTest.java
data-prepper-plugins/otel-proto-common/src/test/resources/test-gauge-metrics.json
data-prepper-plugins/otel-proto-common/src/test/resources/test-histogram-metrics-no-explicit-bounds.json
data-prepper-plugins/otel-proto-common/src/test/resources/test-histogram-metrics.json
data-prepper-plugins/otel-proto-common/src/test/resources/test-request-log.json
data-prepper-plugins/otel-proto-common/src/test/resources/test-request.json
data-prepper-plugins/otel-proto-common/src/test/resources/test-sum-metrics.json

Add support for Scope metrics. 
New OTEL version adds attributes in Scope and OTEL logs/traces/metrics is updated to support that.
Also, modified e2e test to use previous version 0.16.0-alpha 

Add support for Scope metrics

---

data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/model/MessageType.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/LogicalReplicationClient.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/LogicalReplicationEventProcessor.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/ReplicationLogClientFactory.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/StreamWorker.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/StreamWorkerTaskRefresher.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/stream/LogicalReplicationClientTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/stream/LogicalReplicationEventProcessorTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/stream/StreamWorkerTest.java

This PR fixes secrets rotation handling in Rds source. Before this PR, the credentials were not refreshed correctly and the stream was not closed properly to allow for reconnection.
Also updated the replication message type model and do not throw exception when unknown or unsupported types are received.
Contributes to #5309 

Fix secrets rotation handling in Rds source

---

data-prepper-plugins/dissect-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/dissect/DissectProcessor.java

Dissect processor is not thread safe. Added "@SingleThread" annotation
Resolves #5462 

Add @SingleThread annotation to dissect processor

---

data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamAcknowledgementManager.java
data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamAcknowledgementManagerTest.java

Give up partition when there is no Ack to avoid partition expiring. When there is no ACK, there is a code flow where partition checkpoint is not updated.

Give up partition when there is no Ack

---

data-prepper-plugins/aws-plugin/src/main/java/org/opensearch/dataprepper/plugins/aws/AwsSecretManagerConfiguration.java
data-prepper-plugins/aws-plugin/src/test/java/org/opensearch/dataprepper/plugins/aws/AwsSecretManagerConfigurationTest.java
data-prepper-plugins/aws-plugin/src/test/resources/test-aws-secret-manager-configuration-with-sts-headers.yaml

This PR allows sts_header_overrides to be configured in aws secret config
Resolves #5475 

FIX: sts headers override in AWS secret extension

---

data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/datatype/postgres/ColumnType.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/datatype/postgres/PostgresDataType.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/datatype/postgres/handler/BinaryTypeHandler.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/datatype/postgres/handler/BitStringTypeHandler.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/datatype/postgres/handler/BooleanTypeHandler.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/datatype/postgres/handler/JsonTypeHandler.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/datatype/postgres/handler/NetworkAddressTypeHandler.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/datatype/postgres/handler/NumericTypeHandler.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/datatype/postgres/handler/RangeTypeHandler.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/datatype/postgres/handler/SpatialTypeHandler.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/datatype/postgres/handler/SpecialTypeHandler.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/datatype/postgres/handler/StringTypeHandler.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/datatype/postgres/handler/TemporalTypeHandler.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/LogicalReplicationEventProcessor.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/utils/PgArrayParser.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/datatype/postgres/handler/BinaryTypeHandlerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/datatype/postgres/handler/BitStringTypeHandlerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/datatype/postgres/handler/BooleanTypeHandlerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/datatype/postgres/handler/JsonTypeHandlerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/datatype/postgres/handler/NetworkAddressTypeHandlerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/datatype/postgres/handler/NumericTypeHandlerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/datatype/postgres/handler/RangeTypeHandlerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/datatype/postgres/handler/SpatialTypeHandlerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/datatype/postgres/handler/SpecialTypeHandlerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/datatype/postgres/handler/StringTypeHandlerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/datatype/postgres/handler/TemporalTypeHandlerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/utils/PgArrayParserTest.java

- Added a parser to parse array types using `,` as delimiter for built-in array data types and `;` for box array type which are default delimiters. 
- Added support for all built-in array types
- Utilised the Pg library to get the OIDs of built-in data types. 
- No mapping for multirange array types and custom array types, data is returned as-is which is in text format.
- Returning the value as-is which is in text format for data types which are not supported.
Contributes to #5309

Adding array data types for rds

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/core/parser/PipelineTransformer.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/core/pipeline/Pipeline.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/core/pipeline/PipelineRunner.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/core/pipeline/PipelineRunnerImpl.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/core/pipeline/ProcessWorker.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/core/pipeline/exceptions/InvalidEventHandleException.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/core/pipeline/PipelineRunnerTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/core/pipeline/PipelineTests.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/core/pipeline/ProcessWorkerTest.java
data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateProcessorITWithAcks.java

At Present, the functionalities of running a pipeline is encapsulated inside [Process Worker](https://github.com/opensearch-project/data-prepper/issues/data-prepper-core/src/main/java/org/opensearch/dataprepper/core/pipeline/ProcessWorker.java). While this provides encapsulation, it does not provide a way for a given thread such as in the case of https://github.com/opensearch-project/data-prepper/pull/5416 to execute processors and publish to sinks in a synchronous way without having an instance of Process Worker itself which contains additional responsibilities such as shutting down process for pipeline.
Implemented a concrete class for [Pipeline Runner](data-prepper-core/src/main/java/org/opensearch/dataprepper/core/pipeline/PipelineRunner.java) by moving and refactoring the …

Pipeline Runner Implementation and Tests

---

data-prepper-plugins/saas-source-plugins/confluence-source/src/test/java/org/opensearch/dataprepper/plugins/source/confluence/utils/TimezoneHelperTest.java

Timezone offset comparison was already considering DST changes but there is a typo in the comparison variable. Fixing that typo in this pr

Typo fix to correct the timezone issue

---

data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/BinlogEventListener.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/LogicalReplicationEventProcessor.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/StreamCheckpointManager.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/StreamCheckpointer.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/stream/BinlogEventListenerTest.java

- Remove a duplicate metric for counting the number of checkpoints
- Add a missing event processing error counter in `BinlogEventListener`. 
N/A

Fixes for metrics in Rds Source

---

data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/common/LambdaCommonHandler.java
data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/common/util/ThresholdCheck.java
data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/processor/LambdaProcessor.java
data-prepper-plugins/aws-lambda/src/test/java/org/opensearch/dataprepper/plugins/lambda/common/ThresholdCheckTest.java

Fix lambda plugin threshold to avoid empty buffer and fix flaky test
Resolves #5522 

Fix lambda plugin threshold and flaky test

---

data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/configuration/ActionConfiguration.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSinkConfigurationTests.java

This PR fixes the data type of type in ActionConfiguration to allow data prepper expression. It also adds jakarta annotation.

FIX: data type of type in actions

---

data-prepper-plugins/s3-source/src/integrationTest/java/org/opensearch/dataprepper/plugins/source/s3/S3ScanObjectWorkerIT.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/S3ScanPartitionCreationSupplier.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/ScanObjectWorker.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/s3/S3ScanObjectWorkerTest.java

Fixes issue 5531.
Root causes for the bug -
1. The newly added metadata_only option only maps S3DataSelection to a bucket, which means there can only one data selection for a given bucket
2. The existing s3 scan code does not handle if the same bucket is specified twice because the scan time for the bucket is updated first time, making the second scan not possible
This change fixes both issues.
Resolves #5531 
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/m …

Fix for Issue 5531

---

data-prepper-plugins/kafka-plugins/src/integrationTest/java/org/opensearch/dataprepper/plugins/kafka/source/ConfluentKafkaProducerConsumerIT.java
data-prepper-plugins/kafka-plugins/src/integrationTest/java/org/opensearch/dataprepper/plugins/kafka/source/ConfluentKafkaProducerConsumerWithSchemaRegistryIT.java
data-prepper-plugins/kafka-plugins/src/integrationTest/java/org/opensearch/dataprepper/plugins/kafka/source/KafkaSourceJsonTypeIT.java
data-prepper-plugins/kafka-plugins/src/integrationTest/java/org/opensearch/dataprepper/plugins/kafka/source/KafkaSourceMultipleAuthTypeIT.java
data-prepper-plugins/kafka-plugins/src/integrationTest/java/org/opensearch/dataprepper/plugins/kafka/source/KafkaSourceSaslPlainTextIT.java
data-prepper-plugins/kafka-plugins/src/integrationTest/java/org/opensearch/dataprepper/plugins/kafka/source/KafkaSourceSaslScramIT.java
data-prepper-plugins/kafka-plugins/src/integrationTest/java/org/opensearch/dataprepper/plugins/kafka/source/MskGlueRegistryMultiTypeIT.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaCustomConsumerFactory.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/source/KafkaSource.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/util/KafkaSecurityConfigurer.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/source/KafkaSourceTest.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/util/KafkaSecurityConfigurerTest.java

This PR allows credential provider in extension to be applied to AWS glue registry.
Note: 
* The kafka integration test failure on encryption is due to other root causes
* I have run some smoke test as well as MskGlueRegistryMultiTypeIT locally to make sure the default credential is used for AWS glue registry.

ENH: use default credentials for aws glue registry in kafka source

---

data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/integration/Connected_SingleExtraSinkIT.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/core/parser/PipelineTransformer.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/core/pipeline/PipelineRunnerImpl.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/core/pipeline/ProcessWorker.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/core/pipeline/PipelineRunnerTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/core/pipeline/ProcessWorkerTest.java
data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateProcessorITWithAcks.java

Fixes an issue where `@SingleThread`-annotated processors are called multiple times. The recent addition of the `PipelineRunner` was getting the full list of processors from the `Pipeline` class. This includes multiple instances of processors, which caused them to be invoked multiple times. The solution is to use the list of `Processor`s provided to any given `PipelineRunnerImpl` instance. For now, this also disables the support for `SupportsPipelineRunner` buffers in order to get the fix out now. 
Additionally, this improves the timing of the `Connected_SingleExtraSinkIT` test since this appears to be flaky locally for me.
N/A …

Fixes an issue where processors are executing multiple times for an event

---

data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/common/accumlator/Buffer.java
data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/common/accumlator/InMemoryBuffer.java
data-prepper-plugins/aws-lambda/src/test/java/org/opensearch/dataprepper/plugins/lambda/common/accumulator/InMemoryBufferTest.java

Improves the AWS Lambda processor's memory usage by creating fewer byte arrays when creating the request for the Lambda function. This uses the "unsafe" methods on SdkBytes. However, these are fine here because the byte[] is not accessible anywhere else for modification. This additionally adds some new unit tests to verify the actual behavior of the InMemoryBuffer as well.
Additionally, I removed the `getPayload()` method from the buffer because it was not used.
I also increased the initial byte buffer size to 32kb since this is probably going to be at least this large.
I also ran the code formatter to clean it up some to match existing files.
N/A
For more information on …

Reduces byte array copies in AWS Lambda processor when making the request

---

data-prepper-pipeline-parser/build.gradle
data-prepper-plugin-schema-cli/build.gradle
data-prepper-plugin-schema/build.gradle
data-prepper-plugins/aws-lambda/build.gradle

Several new projects have re-declared their dependencies which may lead to inconsistent dependencies in testing than runtime. This updates these to use the dependencies as used by the project-at-large.
N/A

Fixes a few dependency versions by using consistent versions

---

performance-test/README.md
performance-test/build.gradle

Build an uber-jar for the Data Prepper performance-test project that can be deployed with all the necessary Gatling dependencies and run stand-alone.
See the updates in the `README.md` for what this produces and how I ran it to verify that it works.
N/A

Stand-alone uber-jar for performance-test

---

data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/codec/parquet/ParquetOutputCodec.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/codec/parquet/ParquetOutputCodecTest.java

While working on a customer issue, noticed that if auto schema generation fails with exception, it will cause NPE and shutdown the pipeline. 
The error was something like this:
```
java.lang.NullPointerException: Cannot invoke "org.apache.parquet.hadoop.ParquetWriter.close()" because "this.writer" is null
at org.opensearch.dataprepper.plugins.codec.parquet.ParquetOutputCodec.complete(ParquetOutputCodec.java:119)
```
This PR tries to fix the NPE.
N/A

Fix an NullPointerException in S3 sink

---

data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkOperationWrapper.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkRetryStrategy.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSink.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/configuration/OpenSearchSinkConfig.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/ExistingDocumentQueryManager.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/IndexConfiguration.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/model/QueryForExistingDocumentConfiguration.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/model/QueryManagerBulkOperation.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkRetryStrategyTests.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/ExistingDocumentQueryManagerTest.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/IndexConfigurationTests.java

This change adds the option to deduplicate in the OpenSearch sink by querying before writing based on a condition, or by querying if there are errors sending to OpenSearch that could result in partial success, like SocketTimeoutException or 500 internal server error
```
query_lookup:
query_when: 'getMetadata("potential_duplicate") == true' // condition that will qualify a document coming into the sink for querying before indexing
query_term: 'key' // the unique field of the document that will be queried for
query_on_bulk_errors: true // whether to send errors like 500 or socket timeout for querying rather than immediate retry
query_duration: PT5M // duration to query for a given document before indexing it
async_limit: 5000 // number of documents that will be queried at one time before …
```

Implement querying for existing documents to handle duplicates on condition or bulk request/operation failures

---

data-prepper-plugins/saas-source-plugins/confluence-source/src/test/java/org/opensearch/dataprepper/plugins/source/confluence/utils/TimezoneHelperTest.java

Hours difference compared with UTC will change every 6 months when timezones start or end their Day Light Savings. To account for that delta, the comparison made as a range comparison instead of a fixed difference. Previously this range was not set for all the timezones thinking that they don't follow DST but it looks like they all do. So adjusting their assertions to be range check as well.

Comparing an hour difference range for all the timezones to account for Daylight savings

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/failures/DlqObject.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/failures/DlqObjectTest.java
data-prepper-plugins/cloudwatch-logs/build.gradle
data-prepper-plugins/cloudwatch-logs/src/integrationTest/java/org/opensearch/dataprepper/plugins/sink/cloudwatch_logs/CloudWatchLogsIT.java
data-prepper-plugins/cloudwatch-logs/src/main/java/org/opensearch/dataprepper/plugins/sink/cloudwatch_logs/CloudWatchLogsSink.java
data-prepper-plugins/cloudwatch-logs/src/main/java/org/opensearch/dataprepper/plugins/sink/cloudwatch_logs/buffer/Buffer.java
data-prepper-plugins/cloudwatch-logs/src/main/java/org/opensearch/dataprepper/plugins/sink/cloudwatch_logs/buffer/InMemoryBuffer.java
data-prepper-plugins/cloudwatch-logs/src/main/java/org/opensearch/dataprepper/plugins/sink/cloudwatch_logs/client/CloudWatchLogsClientFactory.java
data-prepper-plugins/cloudwatch-logs/src/main/java/org/opensearch/dataprepper/plugins/sink/cloudwatch_logs/client/CloudWatchLogsDispatcher.java
data-prepper-plugins/cloudwatch-logs/src/main/java/org/opensearch/dataprepper/plugins/sink/cloudwatch_logs/client/CloudWatchLogsMetrics.java
data-prepper-plugins/cloudwatch-logs/src/main/java/org/opensearch/dataprepper/plugins/sink/cloudwatch_logs/client/CloudWatchLogsService.java
data-prepper-plugins/cloudwatch-logs/src/main/java/org/opensearch/dataprepper/plugins/sink/cloudwatch_logs/config/CloudWatchLogsSinkConfig.java
data-prepper-plugins/cloudwatch-logs/src/main/java/org/opensearch/dataprepper/plugins/sink/cloudwatch_logs/dlq/CloudWatchLogsSinkDlqData.java
data-prepper-plugins/cloudwatch-logs/src/main/java/org/opensearch/dataprepper/plugins/sink/cloudwatch_logs/utils/CloudWatchLogsLimits.java
data-prepper-plugins/cloudwatch-logs/src/main/java/org/opensearch/dataprepper/plugins/sink/cloudwatch_logs/utils/CloudWatchLogsSinkUtils.java
data-prepper-plugins/cloudwatch-logs/src/test/java/org/opensearch/dataprepper/plugins/sink/cloudwatch_logs/CloudWatchLogsSinkTest.java
data-prepper-plugins/cloudwatch-logs/src/test/java/org/opensearch/dataprepper/plugins/sink/cloudwatch_logs/buffer/InMemoryBufferTest.java
data-prepper-plugins/cloudwatch-logs/src/test/java/org/opensearch/dataprepper/plugins/sink/cloudwatch_logs/client/CloudWatchLogsClientFactoryTest.java
data-prepper-plugins/cloudwatch-logs/src/test/java/org/opensearch/dataprepper/plugins/sink/cloudwatch_logs/client/CloudWatchLogsDispatcherTest.java
data-prepper-plugins/cloudwatch-logs/src/test/java/org/opensearch/dataprepper/plugins/sink/cloudwatch_logs/client/CloudWatchLogsServiceTest.java
data-prepper-plugins/cloudwatch-logs/src/test/java/org/opensearch/dataprepper/plugins/sink/cloudwatch_logs/client/UploaderTest.java
data-prepper-plugins/failures-common/src/main/java/org/opensearch/dataprepper/plugins/dlq/DlqPushHandler.java
data-prepper-plugins/failures-common/src/test/java/org/opensearch/dataprepper/plugins/dlq/DlqPushHandlerTest.java

Add DLQ support to CloudWatchLogs sink
- Added common DLQ push handler to failure common package
- Added DLQ support to cloudwatch using the common DLQ

Add DLQ support to CloudWatchLogs sink

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/trace/JacksonSpan.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/trace/Span.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/trace/JacksonSpanTest.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/trace/JacksonStandardSpanTest.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/IndexConfiguration.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/IndexConstants.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/IndexManagerFactory.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/IndexType.java
data-prepper-plugins/opensearch/src/main/resources/index-template/logs-otel-v1-index-standard-template.json
data-prepper-plugins/opensearch/src/main/resources/index-template/metrics-otel-v1-index-standard-template.json
data-prepper-plugins/opensearch/src/main/resources/index-template/metrics-otel-v1-index-template.json
data-prepper-plugins/opensearch/src/main/resources/index-template/otel-v1-apm-span-index-standard-template.json
data-prepper-plugins/opensearch/src/main/resources/logs-otel-v1-index-standard-template.json
data-prepper-plugins/opensearch/src/main/resources/metrics-otel-v1-index-standard-template.json
data-prepper-plugins/opensearch/src/main/resources/otel-v1-apm-span-index-standard-template.json
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/IndexTypeTests.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/TraceAnalyticsRawIndexManagerTests.java
data-prepper-plugins/otel-logs-source/src/test/resources/testjson/test-standard-log.json
data-prepper-plugins/otel-metrics-source/src/test/resources/testjson/test-standard-metrics.json
data-prepper-plugins/otel-proto-common/src/main/java/org/opensearch/dataprepper/plugins/otel/codec/OTelProtoCommonUtils.java
data-prepper-plugins/otel-proto-common/src/main/java/org/opensearch/dataprepper/plugins/otel/codec/OTelProtoOpensearchCodec.java
data-prepper-plugins/otel-proto-common/src/main/java/org/opensearch/dataprepper/plugins/otel/codec/OTelProtoStandardCodec.java
data-prepper-plugins/otel-proto-common/src/test/java/org/opensearch/dataprepper/plugins/otel/codec/OTelProtoCommonUtilsTest.java
data-prepper-plugins/otel-proto-common/src/test/java/org/opensearch/dataprepper/plugins/otel/codec/OTelProtoOpensearchCodecTest.java
data-prepper-plugins/otel-proto-common/src/test/java/org/opensearch/dataprepper/plugins/otel/codec/OTelProtoStandardCodecTest.java
data-prepper-plugins/otel-trace-raw-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/oteltrace/OTelTraceRawProcessor.java
data-prepper-plugins/otel-trace-source/src/test/resources/testjson/test-standard-trace.json

1. Support OTEL trace groups and trace group fields in standaed OTEL proto codec
2. Cleanup and address comments from https://github.com/opensearch-project/data-prepper/pull/5524
3. Add template mappings for using standard OTEL log/trace/metrics in opensearch sink
Resolves #5259 

Support trace groups in standard otel proto codec

---

data-prepper-plugins/saas-source-plugins/jira-source/src/main/java/org/opensearch/dataprepper/plugins/source/jira/models/IssueBean.java
data-prepper-plugins/saas-source-plugins/jira-source/src/test/java/org/opensearch/dataprepper/plugins/source/jira/models/IssueBeanTest.java

Fixing the issue while converting a ticket updated datetime to milliseconds.

Fix a bug in converting Jira ticket updated time to milliseconds

---

data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/IndexConfiguration.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/IndexConstants.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/IndexManagerFactory.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/IndexType.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/IndexTypeTests.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/TraceAnalyticsRawIndexManagerTests.java

Rename OTEL standard logs/metrics/traces mapping template index-type
from 
`trace-analytics-standard-raw` to `trace-analytics-plain-raw`
`log-analytics-standard` to `log-analytics-plain`
`metric-analytics-standard` to `metric-analytics-plain`.

Rename OTEL standard template mappings index-types

---

settings.gradle

Updates Apache Parquet to 1.15.1.
N/A
Fixes CVE-2025-30065.

Updates Apache Parquet to 1.15.1 to resolve CVE-2025-30065.

---

data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/RdsService.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/configuration/ExportConfig.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/converter/RecordConverter.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/export/DataFileLoader.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/leader/LeaderScheduler.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/model/StreamEventType.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/BinlogEventListener.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/LogicalReplicationEventProcessor.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/converter/StreamRecordConverterTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/stream/BinlogEventListenerTest.java

This PR fixes a few things in Rds source plugin:
- Populate correct stream event type (insert/update/delete) in event metadata
- Name export role more explicitly
- Add NOISY markers to a few more places
- Fixes an issue with empty s3 prefix causing invalidate prefix error in RDS export (prefix cannot start with "/")
N/A

Fix EventType in Rds source

---

data-prepper-plugins/saas-source-plugins/confluence-source/src/main/java/org/opensearch/dataprepper/plugins/source/confluence/ConfluenceClient.java
data-prepper-plugins/saas-source-plugins/confluence-source/src/main/java/org/opensearch/dataprepper/plugins/source/confluence/ConfluenceService.java
data-prepper-plugins/saas-source-plugins/confluence-source/src/main/java/org/opensearch/dataprepper/plugins/source/confluence/configuration/NameConfig.java
data-prepper-plugins/saas-source-plugins/confluence-source/src/main/java/org/opensearch/dataprepper/plugins/source/confluence/configuration/PageTypeConfig.java
data-prepper-plugins/saas-source-plugins/confluence-source/src/main/java/org/opensearch/dataprepper/plugins/source/confluence/utils/ConfluenceContentType.java
data-prepper-plugins/saas-source-plugins/confluence-source/src/main/java/org/opensearch/dataprepper/plugins/source/confluence/utils/ConfluenceNextLinkValidator.java
data-prepper-plugins/saas-source-plugins/confluence-source/src/test/java/org/opensearch/dataprepper/plugins/source/confluence/ConfluenceClientTest.java
data-prepper-plugins/saas-source-plugins/confluence-source/src/test/java/org/opensearch/dataprepper/plugins/source/confluence/ConfluenceServiceTest.java
data-prepper-plugins/saas-source-plugins/confluence-source/src/test/java/org/opensearch/dataprepper/plugins/source/confluence/configuration/NameConfigTest.java
data-prepper-plugins/saas-source-plugins/confluence-source/src/test/java/org/opensearch/dataprepper/plugins/source/confluence/configuration/PageTypeConfigTest.java
data-prepper-plugins/saas-source-plugins/confluence-source/src/test/java/org/opensearch/dataprepper/plugins/source/confluence/utils/ConfluenceContentTypeTest.java
data-prepper-plugins/saas-source-plugins/confluence-source/src/test/java/org/opensearch/dataprepper/plugins/source/confluence/utils/ConfluenceNextLinkValidatorTest.java
data-prepper-plugins/saas-source-plugins/jira-source/src/main/java/org/opensearch/dataprepper/plugins/source/jira/JiraClient.java

- Some validations are currently at the service level, which is too late. Adding the corresponding validation annotation on the config yaml objects to that they are caught early on
- Fix for a regex to allow multiple filter values under page type for Confluence when the url is sanitized
- Fix for sending event meta data to use in dynamic index name construction

Atlassian Jira Gameday fixes

---

release/release-notes/data-prepper.change-log-2.10.3.md

Adds the change log for 2.10.3.
```
git fetch upstream
git switch 2.10
git pull
git-release-notes 2.10.2..HEAD markdown > release/release-notes/data-prepper.change-log-2.10.3.md
```
N/A

Change log for 2.10.3

---

data-prepper-plugins/saas-source-plugins/atlassian-commons/src/main/java/org/opensearch/dataprepper/plugins/source/atlassian/AtlassianSourceConfig.java
data-prepper-plugins/saas-source-plugins/confluence-source/src/main/java/org/opensearch/dataprepper/plugins/source/confluence/ConfluenceSource.java
data-prepper-plugins/saas-source-plugins/confluence-source/src/main/java/org/opensearch/dataprepper/plugins/source/confluence/ConfluenceSourceConfig.java
data-prepper-plugins/saas-source-plugins/confluence-source/src/main/java/org/opensearch/dataprepper/plugins/source/confluence/configuration/PageTypeConfig.java
data-prepper-plugins/saas-source-plugins/confluence-source/src/test/java/org/opensearch/dataprepper/plugins/source/confluence/ConfluenceSourceTest.java
data-prepper-plugins/saas-source-plugins/confluence-source/src/test/java/org/opensearch/dataprepper/plugins/source/confluence/configuration/PageTypeConfigTest.java
data-prepper-plugins/saas-source-plugins/jira-source/src/main/java/org/opensearch/dataprepper/plugins/source/jira/JiraSource.java
data-prepper-plugins/saas-source-plugins/jira-source/src/main/java/org/opensearch/dataprepper/plugins/source/jira/JiraSourceConfig.java
data-prepper-plugins/saas-source-plugins/jira-source/src/test/java/org/opensearch/dataprepper/plugins/source/jira/JiraSourceTest.java
data-prepper-plugins/saas-source-plugins/source-crawler/src/main/java/org/opensearch/dataprepper/plugins/source/source_crawler/base/Crawler.java
data-prepper-plugins/saas-source-plugins/source-crawler/src/main/java/org/opensearch/dataprepper/plugins/source/source_crawler/base/CrawlerSourceConfig.java
data-prepper-plugins/saas-source-plugins/source-crawler/src/main/java/org/opensearch/dataprepper/plugins/source/source_crawler/base/CrawlerSourcePlugin.java
data-prepper-plugins/saas-source-plugins/source-crawler/src/main/java/org/opensearch/dataprepper/plugins/source/source_crawler/base/PaginationCrawler.java
data-prepper-plugins/saas-source-plugins/source-crawler/src/main/java/org/opensearch/dataprepper/plugins/source/source_crawler/coordination/scheduler/LeaderScheduler.java
data-prepper-plugins/saas-source-plugins/source-crawler/src/main/java/org/opensearch/dataprepper/plugins/source/source_crawler/coordination/scheduler/WorkerScheduler.java
data-prepper-plugins/saas-source-plugins/source-crawler/src/test/java/org/opensearch/dataprepper/plugins/source/source_crawler/base/CrawlerTest.java
data-prepper-plugins/saas-source-plugins/source-crawler/src/test/java/org/opensearch/dataprepper/plugins/source/source_crawler/base/PaginationCrawlerTest.java
data-prepper-plugins/saas-source-plugins/source-crawler/src/test/java/org/opensearch/dataprepper/plugins/source/source_crawler/coordination/scheduler/LeaderSchedulerTest.java

- Based on the Gameday feedback, `batch_size` parameter is confusing to expose to the user. Removed this attribute from the config and made it default constant value of 50
- Made the Crawler as an interface to provide an extensibility of implementing different crawlers. CrowdStrike saas source needs a different kind of crawling strategy. This will help them implement their own version of crawling.

Removing batch_size attribute and made the Crawler extensible

---

data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/route/three-route-with-default-route.yaml
data-prepper-pipeline-parser/src/main/java/org/opensearch/dataprepper/pipeline/parser/InvalidPipelineConfigurationException.java
data-prepper-pipeline-parser/src/main/java/org/opensearch/dataprepper/pipeline/parser/PipelineConfigurationValidator.java
data-prepper-pipeline-parser/src/test/java/org/opensearch/dataprepper/pipeline/parser/PipelineConfigurationValidatorIT.java
data-prepper-pipeline-parser/src/test/java/org/opensearch/dataprepper/pipeline/parser/PipelineConfigurationValidatorTest.java

* Added validation for sink routes in PipelineConfigurationValidator
* Added unit tests in PipelineConfigurationValidatorTest
* Added integration tests in PipelineConfigurationValidatorIT
* Routes now properly validate against defined conditional routes
Resolves #5106

Fix issue 5106

---

data-prepper-plugins/cloudwatch-logs/build.gradle
data-prepper-plugins/cloudwatch-logs/src/integrationTest/java/org/opensearch/dataprepper/plugins/sink/cloudwatch_logs/CloudWatchLogsIT.java
data-prepper-plugins/cloudwatch-logs/src/main/java/org/opensearch/dataprepper/plugins/sink/cloudwatch_logs/CloudWatchLogsSink.java
data-prepper-plugins/cloudwatch-logs/src/main/java/org/opensearch/dataprepper/plugins/sink/cloudwatch_logs/client/CloudWatchLogsDispatcher.java
data-prepper-plugins/cloudwatch-logs/src/main/java/org/opensearch/dataprepper/plugins/sink/cloudwatch_logs/config/CloudWatchLogsSinkConfig.java
data-prepper-plugins/cloudwatch-logs/src/main/java/org/opensearch/dataprepper/plugins/sink/cloudwatch_logs/config/ThresholdConfig.java
data-prepper-plugins/cloudwatch-logs/src/test/java/org/opensearch/dataprepper/plugins/sink/cloudwatch_logs/CloudWatchLogsSinkTest.java
data-prepper-plugins/cloudwatch-logs/src/test/java/org/opensearch/dataprepper/plugins/sink/cloudwatch_logs/client/CloudWatchLogsDispatcherTest.java
data-prepper-plugins/cloudwatch-logs/src/test/java/org/opensearch/dataprepper/plugins/sink/cloudwatch_logs/client/UploaderTest.java
data-prepper-plugins/cloudwatch-logs/src/test/java/org/opensearch/dataprepper/plugins/sink/cloudwatch_logs/config/CloudWatchLogsSinkConfigTest.java
data-prepper-plugins/cloudwatch-logs/src/test/java/org/opensearch/dataprepper/plugins/sink/cloudwatch_logs/config/ThresholdConfigTest.java

Fix cloudwatch logs sink config
Removed `backoff_time`
Moved `retry_count` to top level and renamed it `max_retries`
Removed `buffer_type`
Added `Experimental` tag

Fix cloudwatch logs sink config

---

data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/schema/MySqlSchemaManager.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/BinlogClientLifecycleListener.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/BinlogClientWrapper.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/BinlogEventListener.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/LogicalReplicationClient.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/StreamScheduler.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/StreamWorker.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/StreamWorkerTaskRefresher.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/stream/StreamWorkerTaskRefresherTest.java

- Fixes source plugin shutdown by adding missed resource cleanup code in a few places
- Fixes Aurora failover handing by not shutting down stream worker on disconnect. Rather, let the client to restore connection by itself (in MySQL case) or let it throw exception and cause stream partition to be re-acquired (in Postgres case)
- Adds more logging for information and for troubleshooting
N/A

Fix shutdown and failover handling in RDS source plugin

---

data-prepper-plugins/saas-source-plugins/crowdstrike-source/build.gradle
data-prepper-plugins/saas-source-plugins/crowdstrike-source/src/main/java/org/opensearch/dataprepper/plugins/source/crowdstrike/CrowdStrikeClient.java
data-prepper-plugins/saas-source-plugins/crowdstrike-source/src/main/java/org/opensearch/dataprepper/plugins/source/crowdstrike/CrowdStrikeSource.java
data-prepper-plugins/saas-source-plugins/crowdstrike-source/src/main/java/org/opensearch/dataprepper/plugins/source/crowdstrike/CrowdStrikeSourceConfig.java
data-prepper-plugins/saas-source-plugins/crowdstrike-source/src/main/java/org/opensearch/dataprepper/plugins/source/crowdstrike/configuration/AuthenticationConfig.java
data-prepper-plugins/saas-source-plugins/crowdstrike-source/src/main/java/org/opensearch/dataprepper/plugins/source/crowdstrike/rest/CrowdStrikeAuthClient.java
data-prepper-plugins/saas-source-plugins/crowdstrike-source/src/main/java/org/opensearch/dataprepper/plugins/source/crowdstrike/utils/Constants.java
data-prepper-plugins/saas-source-plugins/crowdstrike-source/src/test/java/org/opensearch/dataprepper/plugins/source/crowdstrike/CrowdStrikeClientTest.java
data-prepper-plugins/saas-source-plugins/crowdstrike-source/src/test/java/org/opensearch/dataprepper/plugins/source/crowdstrike/CrowdStrikeSourceConfigTest.java
data-prepper-plugins/saas-source-plugins/crowdstrike-source/src/test/java/org/opensearch/dataprepper/plugins/source/crowdstrike/CrowdStrikeSourceTest.java
data-prepper-plugins/saas-source-plugins/crowdstrike-source/src/test/java/org/opensearch/dataprepper/plugins/source/crowdstrike/configuration/AuthenticationConfigTest.java
data-prepper-plugins/saas-source-plugins/crowdstrike-source/src/test/java/org/opensearch/dataprepper/plugins/source/crowdstrike/rest/CrowdStrikeAuthClientTest.java
settings.gradle

[Introducing new saas crawler for CrowdStrike Falcon API]
- [Y] New functionality includes testing.
- [N] New functionality has a documentation issue. Please link to it in this PR.
- [Y] New functionality has javadoc added
- [Y] Commits are signed with a real name per the DCO

Initial commit for CrowdStrike source crawler

---

data-prepper-plugins/saas-source-plugins/confluence-source/src/main/java/org/opensearch/dataprepper/plugins/source/confluence/ConfluenceService.java
data-prepper-plugins/saas-source-plugins/confluence-source/src/main/java/org/opensearch/dataprepper/plugins/source/confluence/utils/CqlConstants.java
data-prepper-plugins/saas-source-plugins/confluence-source/src/test/java/org/opensearch/dataprepper/plugins/source/confluence/ConfluenceServiceTest.java

Fixing Confluence polling time to include the last polling time so that we don't miss any content created at the exact same second but was not part of the last polling call. This issue wouldn't have happened (or much less problematic) if this time polling timestamp `lastModified>"2025-03-31 16:20"` also considered milliseconds but unfortunately, confluence polling time is only considering up to seconds. 

Making Confluence polling to include the last polling time

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/metric/JacksonMetric.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/metric/Metric.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/trace/JacksonSpan.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/trace/Span.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/metric/JacksonGaugeTest.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/trace/JacksonSpanTest.java
data-prepper-plugins/otel-proto-common/src/main/java/org/opensearch/dataprepper/plugins/otel/codec/OTelProtoStandardCodec.java
data-prepper-plugins/otel-proto-common/src/test/java/org/opensearch/dataprepper/plugins/otel/codec/OTelProtoOpensearchCodecTest.java
data-prepper-plugins/otel-proto-common/src/test/java/org/opensearch/dataprepper/plugins/otel/codec/OTelProtoStandardCodecTest.java
data-prepper-plugins/otel-proto-common/src/test/resources/test-gauge-metrics.json
data-prepper-plugins/otel-proto-common/src/test/resources/test-histogram-metrics-no-explicit-bounds.json
data-prepper-plugins/otel-proto-common/src/test/resources/test-histogram-metrics.json
data-prepper-plugins/otel-proto-common/src/test/resources/test-request-both-span-types.json
data-prepper-plugins/otel-proto-common/src/test/resources/test-request-log.json
data-prepper-plugins/otel-proto-common/src/test/resources/test-request-multiple-traces.json
data-prepper-plugins/otel-proto-common/src/test/resources/test-request-no-spans.json
data-prepper-plugins/otel-proto-common/src/test/resources/test-request.json
data-prepper-plugins/otel-proto-common/src/test/resources/test-sum-metrics.json

Added missing OTEL standard fields
1. Added metadata field to all metrics
2. Added min/max to historgram metrics, added zero threshold to exponential histogram metrics
3. Added resource level schema url to all logs, traces and metrics
Resolves #4137 

Add missing OTEL standard fields

---

data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/configuration/ServerlessOptions.java

This PR tightens the constraint on network policy name as well as collection name to keep them aligned with AWS documentation: https://docs.aws.amazon.com/opensearch-service/latest/ServerlessAPIReference/API_CreateCollection.html

FIX: opensearch serverless parameter constraint

---

gradle.properties

Updates the Data Prepper version to 2.11. Removes the SNAPSHOT.
Commands:
```
git fetch upstream
git switch 2.11
git pull
git switch --create 2.11-version
(edit file)
git add gradle.properties
git commit -m "Set version for 2.11"
git push origin 2.11-version
```
N/A

Set version for 2.11

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/source/coordinator/SourceCoordinator.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/core/sourcecoordination/LeaseBasedSourceCoordinator.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/ScanObjectWorker.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/s3/S3ScanObjectWorkerTest.java

Adding retries and backoff to handle delayed sync between GSI and primary table when DDB is used as Source Coordination Store 
Resolves #5468 

Handle delayed sync between GSI and primary table when DDB is used as Source Coordination Store

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/codec/JsonDecoder.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/codec/JsonDecoderTest.java

This PR fixes the NPE on parsing json array when key_name is specified
Resolves #5658 

FIX: NPE in JsonCodec with keyName

---

release/release-notes/data-prepper.release-notes-2.11.0.md

This adds release notes for Data Prepper 2.11.
I generated the initial notes using the script:
```
./generate-initial-release-notes.sh v2.11
```
Then I made manual updates.
N/A

Release notes for Data Prepper 2.11

---

data-prepper-plugins/saas-source-plugins/atlassian-commons/src/main/java/org/opensearch/dataprepper/plugins/source/atlassian/AtlassianSourceConfig.java
data-prepper-plugins/saas-source-plugins/crowdstrike-source/src/main/java/org/opensearch/dataprepper/plugins/source/crowdstrike/CrowdStrikeService.java
data-prepper-plugins/saas-source-plugins/crowdstrike-source/src/main/java/org/opensearch/dataprepper/plugins/source/crowdstrike/CrowdStrikeSourceConfig.java
data-prepper-plugins/saas-source-plugins/crowdstrike-source/src/main/java/org/opensearch/dataprepper/plugins/source/crowdstrike/models/CrowdStrikeApiResponse.java
data-prepper-plugins/saas-source-plugins/crowdstrike-source/src/main/java/org/opensearch/dataprepper/plugins/source/crowdstrike/models/CrowdStrikeIndicatorResult.java
data-prepper-plugins/saas-source-plugins/crowdstrike-source/src/main/java/org/opensearch/dataprepper/plugins/source/crowdstrike/models/CrowdStrikeThreatIntelApiResponse.java
data-prepper-plugins/saas-source-plugins/crowdstrike-source/src/main/java/org/opensearch/dataprepper/plugins/source/crowdstrike/models/ThreatIndicator.java
data-prepper-plugins/saas-source-plugins/crowdstrike-source/src/main/java/org/opensearch/dataprepper/plugins/source/crowdstrike/rest/CrowdStrikeAuthClient.java
data-prepper-plugins/saas-source-plugins/crowdstrike-source/src/main/java/org/opensearch/dataprepper/plugins/source/crowdstrike/rest/CrowdStrikeRestClient.java
data-prepper-plugins/saas-source-plugins/crowdstrike-source/src/main/java/org/opensearch/dataprepper/plugins/source/crowdstrike/utils/Constants.java
data-prepper-plugins/saas-source-plugins/crowdstrike-source/src/main/java/org/opensearch/dataprepper/plugins/source/crowdstrike/utils/CrowdStrikeNextLinkValidator.java
data-prepper-plugins/saas-source-plugins/crowdstrike-source/src/test/java/org/opensearch/dataprepper/plugins/source/crowdstrike/CrowdStrikeNextLinkValidatorTest.java
data-prepper-plugins/saas-source-plugins/crowdstrike-source/src/test/java/org/opensearch/dataprepper/plugins/source/crowdstrike/CrowdStrikeServiceTest.java
data-prepper-plugins/saas-source-plugins/crowdstrike-source/src/test/java/org/opensearch/dataprepper/plugins/source/crowdstrike/CrowdStrikeSourceConfigTest.java
data-prepper-plugins/saas-source-plugins/crowdstrike-source/src/test/java/org/opensearch/dataprepper/plugins/source/crowdstrike/models/CrowdStrikeApiResponseTest.java
data-prepper-plugins/saas-source-plugins/crowdstrike-source/src/test/java/org/opensearch/dataprepper/plugins/source/crowdstrike/models/CrowdStrikeIndicatorResultTest.java
data-prepper-plugins/saas-source-plugins/crowdstrike-source/src/test/java/org/opensearch/dataprepper/plugins/source/crowdstrike/models/CrowdStrikeThreatIntelApiResponseTest.java
data-prepper-plugins/saas-source-plugins/crowdstrike-source/src/test/java/org/opensearch/dataprepper/plugins/source/crowdstrike/models/ThreatIndicatorTest.java
data-prepper-plugins/saas-source-plugins/crowdstrike-source/src/test/java/org/opensearch/dataprepper/plugins/source/crowdstrike/rest/CrowdStrikeAuthClientTest.java
data-prepper-plugins/saas-source-plugins/crowdstrike-source/src/test/java/org/opensearch/dataprepper/plugins/source/crowdstrike/rest/CrowdStrikeRestClientTest.java
data-prepper-plugins/saas-source-plugins/source-crawler/src/main/java/org/opensearch/dataprepper/plugins/source/source_crawler/base/CrawlerSourceConfig.java
data-prepper-plugins/saas-source-plugins/source-crawler/src/main/java/org/opensearch/dataprepper/plugins/source/source_crawler/base/CrawlerSourcePlugin.java
data-prepper-plugins/saas-source-plugins/source-crawler/src/test/java/org/opensearch/dataprepper/plugins/source/source_crawler/base/CrawlerSourcePluginTest.java

- Interactions with CrowdStrike Falcon Threat Intel API
- Token Refresh mechanism
- Validation for paginationLink sent by  CrowdStrike Falcon API
- [Y] New functionality includes testing.
- [N] New functionality has a documentation issue. Please link to it in this PR.
- [Y] New functionality has javadoc added
- [Y] Commits are signed with a real name per the DCO

CrowdStrike API call and retry mechanism

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/core/parser/config/DisableMetricsFilter.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/core/parser/config/MetricsConfig.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/core/parser/model/DataPrepperConfiguration.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/core/parser/config/DisableMetricsFilterTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/core/parser/config/MetricsConfigTest.java

This PR introduces the ability to disable specific metrics via the `data-prepper-config.yaml` configuration file.
To use this feature, add a new section to your configuration:
```
disabled_metrics:
- "jvm.gc.max.data.size"
- "jvm.gc.**"
- "**.http.successRequests"
```
**Known Limitations**
Pattern matching is based on the raw Meter ID name, not what is displayed in CloudWatch (e.g., .sum, .count, .max).
- For example, disabling `jvm.gc.max.data.size.value` **won't work**, because the base ID is only `jvm.gc.max.data.size`.
Only:
```
disabled_metrics:
- "jvm.gc.max.data.size"
```
works.
-  Disabling '**.BlockingBuffer.readLatency.count' won't work, because the base ID is 'your-pipeline-name.BlockingBuffer.readLatency'.
Only:
```
disabled_metrics:
- "**.BlockingBuffer.readLatency"
``` …

Allow disabling metrics with data-prepper-config.yaml

---

data-prepper-plugins/opensearch/src/main/resources/index-template/metrics-otel-v1-index-template.json

Introduces keyword mappings for string fields. This was the default for all fields before the latest change in #5539.
Fix for regression introduced by #5539.

Add OTel Metrics String Attributes to Index Template

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/buffer/Buffer.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/plugin/PluginComponentType.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/processor/Processor.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/sink/Sink.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/source/Source.java
data-prepper-plugin-framework/src/main/java/org/opensearch/dataprepper/plugin/DefaultPluginFactory.java
data-prepper-plugin-framework/src/main/java/org/opensearch/dataprepper/plugin/DefinedPlugin.java
data-prepper-plugin-framework/src/main/java/org/opensearch/dataprepper/plugin/ExperimentalConfiguration.java
data-prepper-plugin-framework/src/main/java/org/opensearch/dataprepper/plugin/ExperimentalPluginValidator.java
data-prepper-plugin-framework/src/test/java/org/opensearch/dataprepper/plugin/DefaultPluginFactoryTest.java
data-prepper-plugin-framework/src/test/java/org/opensearch/dataprepper/plugin/ExperimentalConfigurationTest.java
data-prepper-plugin-framework/src/test/java/org/opensearch/dataprepper/plugin/ExperimentalPluginValidatorTest.java

Support enabling experimental plugins specifically by plugin type and name. 
This also includes a change to the core plugin classes to allow them to define themselves as a plugin component type along with a name that is used to create the mapping in the YAML file.
Resolves #5675

Enabling experimental plugins specifically by plugin type and name

---

data-prepper-plugins/truncate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/truncate/TruncateProcessorConfigTests.java

I noticed a test failure in `TruncateProcessorConfigTests`. I suspect this is because the random value can be zero. Then we make that `-0` which is `0` which is valid.
Additionally, there are really two tests in this one test. So I split these. This way we know what actually fails when failures occur.
N/A

Fixes an uncommon test failure in TruncateProcessorConfigTests by not using zero

---

data-prepper-plugins/http-common/src/main/java/org/opensearch/dataprepper/plugins/server/CreateServer.java

The log warning message point to http source in the common create server http interfaces. This can be misleading the users to debug errors hence, changing this warning to point to the `sourceName` similar to how it is done for the GRPC server.,
https://github.com/opensearch-project/data-prepper/pull/5677#discussion_r2076054058

Fix log warnings for HTTP server with source name

---

data-prepper-expression/src/main/antlr/DataPrepperExpression.g4
data-prepper-expression/src/main/java/org/opensearch/dataprepper/expression/GetEventTypeExpressionFunction.java
data-prepper-expression/src/main/java/org/opensearch/dataprepper/expression/ParseTreeCoercionService.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/GenericExpressionEvaluator_ConditionalIT.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/GenericExpressionEvaluator_MultiTypeIT.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/GetEventTypeExpressionFunctionTest.java
docs/expression_syntax.md

Today DataPrepper have a great event metadata structure that users can use to route between sub-pipelines. We already have functions supported in the expression language to help users route these events: 
1. `getMetaData`- Function to fetch the value of attribute keys from the event
2. `hasTags` - Function to validate existence of tags in an event
This PR adds a third metadata related function to help users route based on event Type. `getEventType`: New function to fetch the event type. 
Example Usage of the new function, the example will be more helpful in the upcoming `OTLP source`:
```
otel-logs-pipelines:
source:
otel_logs_source:
ssl: false
proto_reflection_service: true
route:
- logs: "getEventType() == \"LOG\""
sink:
- pipeline:
name: "logs-pipeline"
routes:
- "logs"
logs-pipeline: …
```

Add `getEventType()` expression function

---

data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/integration/ProcessorValidationIT.java
data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/plugins/BaseEventsTrackingProcessor.java
data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/plugins/BasicEventsTrackingTestProcessor.java
data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/plugins/SingleThreadEventsTrackingTestProcessor.java
data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/basic-processor-pipeline.yaml
data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/multi-processor-pipeline.yaml
data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/single-thread-processor-pipeline.yaml
e2e-test/log/src/integrationTest/java/org/opensearch/dataprepper/integration/log/EndToEndBasicLogTest.java
e2e-test/log/src/integrationTest/resources/basic-grok-e2e-pipeline.yml

Added integration tests to verify that each event is processed only once by a processor in a pipeline. The tests cover pipelines with single and multiple processors, including with more than one worker thread configuration
Added two test processors:
- `BasicEventsTrackingTestProcessor`
- `SingleThreadEventsTrackingTestProcessor` (@SingleThread annotated)
Also added additional validation to the `EndToEndBasicLogTest`
- #5690 
Note to Reviewers :
Performed tests to ensure that all the tests containing the `SingleThreadEventsTrackingTestProcessor` fail without the fix introduced in [#5545](https://github.com/opensearch-project/data-prepper/pull/5545), which resolves the issue of processors executing multiple times for the same event.
Manual Test Run results without the changes in PR :
1. …

Added integration tests for validating that events are processed exactly once

---

data-prepper-plugins/sqs-sink/build.gradle
data-prepper-plugins/sqs-sink/src/integrationTest/java/org/opensearch/dataprepper/plugins/sink/sqs/SqsSinkIT.java
data-prepper-plugins/sqs-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/sqs/SqsSink.java
data-prepper-plugins/sqs-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/sqs/SqsSinkBatch.java
data-prepper-plugins/sqs-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/sqs/SqsSinkBatchEntry.java
data-prepper-plugins/sqs-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/sqs/SqsSinkExecutor.java
data-prepper-plugins/sqs-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/sqs/SqsSinkMetrics.java
data-prepper-plugins/sqs-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/sqs/SqsSinkService.java
data-prepper-plugins/sqs-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/sqs/SqsSinkBatchEntryTest.java
data-prepper-plugins/sqs-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/sqs/SqsSinkBatchTest.java
data-prepper-plugins/sqs-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/sqs/SqsSinkDlqDataTest.java
data-prepper-plugins/sqs-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/sqs/SqsSinkServiceTest.java
data-prepper-plugins/sqs-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/sqs/SqsSinkTest.java

Added tests to increase sqs sink test coverage to 0.99.
Added distribution summary metrics to capture request latency and request size
Fixed bugs

Increase Sqs sink test coverage. Add more metrics

---

data-prepper-plugin-framework/src/main/java/org/opensearch/dataprepper/plugin/VariableExpander.java
data-prepper-plugin-framework/src/test/java/org/opensearch/dataprepper/plugin/VariableExpanderTest.java

Current logic is expecting the rawSecret value to be of a certain format to be able to convert to PluginConfigVariable type. But then the requested type is PluginConfigVariable but raw value is not passing the expression format check filter criteria, we are currently failing to serialize the value into the object type. This fix is to still return an instance of a requested type without any attached functionality. We will be avoiding the serialization issue with this fix.

Serialization fix when the expected type is PluginConfigVariable

---

data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/RdsService.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/RdsSource.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/leader/LeaderScheduler.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/schema/PostgresSchemaManager.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/RdsServiceTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/RdsSourceTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/leader/LeaderSchedulerTest.java

Change replication slot naming in RDS source to include pipeline name so it's easier to identify the pipeline it associates with.
The replication slot name used to look like this: `data_prepper_xxxxxx`. 
With this change, it will be: `data_prepper_pipeline_name_xxxxxx`. 
Similar change was done for publication name. 
N/A

Change replication slot naming in RDS source

---

data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/RdsService.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/export/ExportTaskManager.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/BinlogClientWrapper.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/LogicalReplicationClient.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/ReplicationLogClientFactory.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/utils/RdsSourceAggregateMetrics.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/export/ExportTaskManagerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/stream/BinlogClientWrapperTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/stream/LogicalReplicationClientTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/stream/ReplicationLogClientFactoryTest.java

- Adding aggregated metrics for RDS source, similar to this one for DocumentDB source: #4531 
N/A

Add aggregate metrics for rds source

---

data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/ScrollWorker.java

The default scroll time of 1 minute is too low, and can cause the scroll to expire if it takes longer than a minute to write a batch to the buffer (which can happen in full buffer or circuit breaker situations). To handle this, the default is being increased to 10 minutes.
Resolves #5679 

Increase default scroll time per batch from 1m to 10m

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/core/parser/PipelineTransformer.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/TestDataProvider.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/core/parser/PipelineTransformerTests.java
data-prepper-core/src/test/resources/invalid_zero_buffer_multiple_threads.yml
data-prepper-core/src/test/resources/invalid_zero_buffer_multiple_threads_no_single_thread_processors.yml
data-prepper-core/src/test/resources/invalid_zero_buffer_with_single_thread_processor.yml
data-prepper-core/src/test/resources/valid_zero_buffer_single_thread.yml

At present zero-buffer is disabled due to the issue https://github.com/opensearch-project/data-prepper/pull/5545. 
Enable Zero Buffer under the following constraints:
1. Number of workers is equal to 1
2. Only allow pipelines which do not use @SingleThread processors.
If a pipeline configuration does not meet the above requirements and still uses zero-buffer, then throw an exception to indicate the constraints.
- https://github.com/opensearch-project/data-prepper/pull/5691

Enable ZeroBuffer

---

data-prepper-plugins/cloudwatch-logs/src/integrationTest/java/org/opensearch/dataprepper/plugins/sink/cloudwatch_logs/CloudWatchLogsIT.java
data-prepper-plugins/cloudwatch-logs/src/main/java/org/opensearch/dataprepper/plugins/sink/cloudwatch_logs/CloudWatchLogsSink.java
data-prepper-plugins/cloudwatch-logs/src/main/java/org/opensearch/dataprepper/plugins/sink/cloudwatch_logs/config/CloudWatchLogsSinkConfig.java
data-prepper-plugins/cloudwatch-logs/src/main/java/org/opensearch/dataprepper/plugins/sink/cloudwatch_logs/config/ThresholdConfig.java
data-prepper-plugins/cloudwatch-logs/src/test/java/org/opensearch/dataprepper/plugins/sink/cloudwatch_logs/client/CloudWatchLogsServiceTest.java
data-prepper-plugins/cloudwatch-logs/src/test/java/org/opensearch/dataprepper/plugins/sink/cloudwatch_logs/config/ThresholdConfigTest.java
data-prepper-plugins/cloudwatch-logs/src/test/java/org/opensearch/dataprepper/plugins/sink/cloudwatch_logs/utils/CloudWatchLogsLimitsTest.java
data-prepper-plugins/sqs-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/sqs/SqsThresholdConfig.java

Fix CloudwatchLogs sink and sqs sink config to use correct Jakarta annotations.
Also renamed cloudwatch_logs `log_send_interval` config option to be `flush_interval`

Fix CloudwatchLogs and Sqs sink config to use correct Jakarta annotations

---

data-prepper-plugins/saas-source-plugins/confluence-source/src/main/java/org/opensearch/dataprepper/plugins/source/confluence/ConfluenceClient.java
data-prepper-plugins/saas-source-plugins/confluence-source/src/main/java/org/opensearch/dataprepper/plugins/source/confluence/ConfluenceSource.java
data-prepper-plugins/saas-source-plugins/confluence-source/src/test/java/org/opensearch/dataprepper/plugins/source/confluence/ConfluenceClientTest.java
data-prepper-plugins/saas-source-plugins/jira-source/src/main/java/org/opensearch/dataprepper/plugins/source/jira/JiraClient.java
data-prepper-plugins/saas-source-plugins/jira-source/src/main/java/org/opensearch/dataprepper/plugins/source/jira/JiraSource.java
data-prepper-plugins/saas-source-plugins/jira-source/src/test/java/org/opensearch/dataprepper/plugins/source/jira/JiraClientTest.java
data-prepper-plugins/saas-source-plugins/source-crawler/src/main/java/org/opensearch/dataprepper/plugins/source/source_crawler/base/LeaderProgressState.java
data-prepper-plugins/saas-source-plugins/source-crawler/src/main/java/org/opensearch/dataprepper/plugins/source/source_crawler/base/PaginationCrawler.java
data-prepper-plugins/saas-source-plugins/source-crawler/src/main/java/org/opensearch/dataprepper/plugins/source/source_crawler/base/SaasWorkerProgressState.java
data-prepper-plugins/saas-source-plugins/source-crawler/src/main/java/org/opensearch/dataprepper/plugins/source/source_crawler/coordination/state/PaginationCrawlerLeaderProgressState.java
data-prepper-plugins/saas-source-plugins/source-crawler/src/main/java/org/opensearch/dataprepper/plugins/source/source_crawler/coordination/state/PaginationCrawlerWorkerProgressState.java
data-prepper-plugins/saas-source-plugins/source-crawler/src/test/java/org/opensearch/dataprepper/plugins/source/source_crawler/base/PaginationCrawlerTest.java
data-prepper-plugins/saas-source-plugins/source-crawler/src/test/java/org/opensearch/dataprepper/plugins/source/source_crawler/coordination/PartitionFactoryTest.java
data-prepper-plugins/saas-source-plugins/source-crawler/src/test/java/org/opensearch/dataprepper/plugins/source/source_crawler/coordination/scheduler/LeaderSchedulerTest.java
data-prepper-plugins/saas-source-plugins/source-crawler/src/test/java/org/opensearch/dataprepper/plugins/source/source_crawler/coordination/scheduler/WorkerSchedulerTest.java
data-prepper-plugins/saas-source-plugins/source-crawler/src/test/java/org/opensearch/dataprepper/plugins/source/source_crawler/coordination/state/PaginationCrawlerLeaderProgressStateTest.java
data-prepper-plugins/saas-source-plugins/source-crawler/src/test/java/org/opensearch/dataprepper/plugins/source/source_crawler/coordination/state/PaginationCrawlerWorkerProgressStateTest.java

Signed-off-by: Alekhya Parisha <aparisha@amazon.com>
This PR only includes renaming the existing state objects to be more generic and reuse the same for Atlassian as well as Office365
Renamed AtlassianLeaderProgressState to PaginationCrawlerLeaderProgressState
Renamed AtlassianWorkerProgressState to PaginationCrawlerWorkerProgressState

Rename Atlassian state classes to PaginationCrawler

---

data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/StreamWorker.java
data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/utils/ServerIdGenerator.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/stream/StreamWorkerTest.java
data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/utils/ServerIdGeneratorTest.java

Set a custom server id for MySQL binlog client before making connection to the MySQL database. 
Before this CR, server id is always 65535 by default and can result in server id conflict when two Data Prepper pipelines try to connect to the same MySQL database's binary log stream.
N/A

Set server id for MySQL binlog client

---

data-prepper-plugin-schema/build.gradle
data-prepper-plugins/build.gradle
data-prepper-plugins/saas-source-plugins/build.gradle

This PR helps improve our Maven artifacts to prepare to publish Data Prepper plugins to Maven Central:
* Prepend the `data-prepper-` prefix to jar names, though they aren't used in the Maven coordinates. 
* Move some projects into `.plugins` or `.core` groupIds
Resolves #4931
Contributes toward: #5710 

Improvements to artifacts to support Maven artifacts for plugins.

---

e2e-test/README.md
e2e-test/build.gradle
e2e-test/log/build.gradle
e2e-test/trace/build.gradle

This PR adds new parameters to run the end-to-end tests against defined Docker images. This is part of a goal to deprecate the failing smoke tests in favor of a single end-to-end test suite.
See the included README.md changes for details on usage.
Related changes
* Renamed the existing `pullDataPrepperDockerImage` to `pullLatestDataPrepperDockerImage` since this PR adds a new task with the same name.
* Rely only on the `compileJava` rather than full `build` to reduce build times.
Resolves #3567
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBU …

Support running the end-to-end tests against defined Docker images.

---

data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/configuration/SchemaConfig.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/util/KafkaSecurityConfigurer.java
data-prepper-plugins/kafka-plugins/src/test/resources/kafka-pipeline-bootstrap-servers-glue-override-endpoint.yaml

Fix kafka source with glue registry.
Kafka source with glue registry default behavior is broken with PR #5502. This change keeps the old and new behavior by adding a new flag under `schema:`. To get the behavior specified in the issue #5377, new `override_endpoint:` option must be specified under `schema:`

Fix kafka source with glue registry

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/JacksonEvent.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/event/JacksonEventTest.java
data-prepper-plugins/mutate-event-processors/src/test/java/org/opensearch/dataprepper/plugins/processor/mutateevent/ConvertEntryTypeProcessorTests.java

Fixes an issue where updating Jackson Event with json pointer paths to array like
```
/list-key/0/nested-key
```
failed with a ClassCastException to ObjectNode (since it is ArrayNode)
```
2025-06-10T14:51:24,907 [test-pipeline-processor-worker-1-thread-1] ERROR
java.lang.ClassCastException: class com.fasterxml.jackson.databind.node.ArrayNode cannot be cast to class com.fasterxml.jackson.databind.node.ObjectNode (com.fasterxml.jackson.databind.node.ArrayNode and com.fasterxml.jackson.databind.node.ObjectNode are in unnamed module of loader 'app')
at org.opensearch.dataprepper.model.event.JacksonEvent.getOrCreateNode(JacksonEvent.java:198) ~[data-prepper-api-2.11.0-SNAPSHOT.jar:?]
at org.opensearch.dataprepper.model.event.JacksonEvent.put(JacksonEvent.java:161) …
```

Add support for updating JacksonEvent array elements

---

data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/AddEntryProcessor.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/AddEntryProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/DeleteEntryProcessor.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/DeleteEntryProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/test/java/org/opensearch/dataprepper/plugins/processor/mutateevent/AddEntryProcessorTests.java
data-prepper-plugins/mutate-event-processors/src/test/java/org/opensearch/dataprepper/plugins/processor/mutateevent/DeleteEntryProcessorTests.java

Completes this unfinished PR (https://github.com/opensearch-project/data-prepper/pull/5620) by rebasing and fixing merge conflicts
Also manually tested 
```
- add_entries:
entries:
- iterate_on: "list-key"
key: "new-key"
value_expression: '/add_value'
- delete_entries:
with_keys: [ "delete-key" ]
iterate_on: "list-key"
```
Resolves #2853 

Iterate on support for add_entries and delete_entries processors

---

data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/ConvertEntryTypeProcessor.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/ConvertEntryTypeProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/test/java/org/opensearch/dataprepper/plugins/processor/mutateevent/ConvertEntryTypeProcessorTests.java

Adds iterate_on parameter for convert_type processor.
Given this event
```
{
"list-key": [{
"some-key": 2,
"key-to-convert": 10.0
}, {
"some-key": 2,
"key-to-convert": 20.0
}]
}
```
and this configuration
```
processor:
- convert_type:
iterate_on: "list-key"
key: "key-to-convert"
type: "long"
```
The result of the Event will convert the decimals to long 
```
{
"list-key": [{
"some-key": 2,
"key-to-convert": 10
}, {
"some-key": 2,
"key-to-convert": 20
}]
}
``` …

Add iterate_on support for convert_type processors to iterate over array of objects and convert within each element

---

data-prepper-plugins/ml-inference-processor/src/main/java/org/opensearch/dataprepper/plugins/ml_inference/processor/MLProcessor.java
data-prepper-plugins/ml-inference-processor/src/main/java/org/opensearch/dataprepper/plugins/ml_inference/processor/MLProcessorConfig.java
data-prepper-plugins/ml-inference-processor/src/main/java/org/opensearch/dataprepper/plugins/ml_inference/processor/common/MLBatchJobCreator.java
data-prepper-plugins/ml-inference-processor/src/main/java/org/opensearch/dataprepper/plugins/ml_inference/processor/common/SageMakerBatchJobCreator.java
data-prepper-plugins/ml-inference-processor/src/test/java/org/opensearch/dataprepper/plugins/ml_inference/processor/MLProcessorTest.java
data-prepper-plugins/ml-inference-processor/src/test/java/org/opensearch/dataprepper/plugins/ml_inference/processor/common/SageMakerBatchJobCreatorTest.java

This PR enhances batch job creation by implementing thread-safe record collection across multiple processor worker threads. 
Currently when processing multiple S3 files (e.g., an S3 source with 7 files), records are randomly distributed across worker threads. For example, worker-1 might process files 2,4,6 while worker-2 processes 1,3,5,7, resulting in two separate, potentially undersized batch jobs. Ideally we should only create 1 batch job to process all the files with best efficiency. 
Rather than having each worker thread independently create separate ML batch jobs, all worker threads now contribute records to a shared, thread-safe buffer in the ml processor. The system creates a single consolidated ML batch job when either of these conditions is met:
1. The accumulated records in the …

add internal batching of the records for Sagemaker job creator

---

data-prepper-plugins/csv-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/csv/CsvProcessor.java
data-prepper-plugins/csv-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/csv/CsvProcessorConfig.java
data-prepper-plugins/csv-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/csv/CsvProcessorConfigTest.java
data-prepper-plugins/csv-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/csv/CsvProcessorIT.java
data-prepper-plugins/csv-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/csv/CsvProcessorTest.java

Add multi-line csv support. When the `multi_line` config option is used, the input in the source key is expected to contain multiple lines of CSV format with first line containing column names.
Resolves #5783

Add multi-line csv support

---

.github/workflows/release.yml
build.gradle
buildSrc/src/main/groovy/data-prepper.publish.gradle

This is the first PR for Gradle build support for publishing Maven snapshots.
It adds a new Maven snapshot repository to publish to. I also updated the `release.yml` to publish only the Maven release artifacts. This will prevent publishing snapshots during the release build. Also updates a related usage to a non-deprecated Gradle API.
A second PR will come to add the actual GitHub Actions CI.
Contributes toward #5796.

Gradle build support for publishing Maven snapshots.

---

data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/integration/PipelinesWithAcksIT.java
data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/integration/ProcessorSwapPipelineIT.java
data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/test/framework/DataPrepperTestRunner.java
data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/processor-swap/source/processor-swap-pipeline.yaml
data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/processor-swap/target/processor-swap-pipeline.yaml
data-prepper-core/src/main/java/org/opensearch/dataprepper/core/DataPrepper.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/core/parser/PipelineTransformer.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/core/pipeline/Pipeline.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/core/pipeline/PipelineRunnerImpl.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/core/pipeline/ProcessWorker.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/core/pipeline/ProcessorProvider.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/core/pipeline/ProcessorRegistry.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/core/pipeline/PipelineRunnerTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/core/pipeline/ProcessWorkerTest.java
data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateProcessorITWithAcks.java

To support Dynamic swapping of Processor instances, these code changes helps keep the Processor instances at one place so that we can hot swap the processor instances as an atomic operation.
#5327 

Adding Processor Registry to provision Atomic swapping of Processor instances

---

data-prepper-plugins/opensearch/src/integrationTest/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSinkIT.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/IndexConfiguration.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/IndexConfigurationTests.java
data-prepper-plugins/opensearch/src/test/resources/raw-span-2-same-id-as-1.json

OpenTelemetry spans are currently indexed using the spanId as documentId. This can lead to collisions where spans are not indexed or overwrite each other.
This change adds the traceId to the documentId. OpenTelemetry assumes the combination of traceId and spanId to be unique. If there is still a collision it is safe to assume, that it occurs because of a resending of a previously indexed span.
Resolves #5370 

Add traceId to documentId used for spans

---

data-prepper-plugins/common/src/main/java/org/opensearch/dataprepper/common/TransformOption.java
data-prepper-plugins/common/src/test/java/org/opensearch/dataprepper/common/TransformOptionTest.java
data-prepper-plugins/key-value-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/keyvalue/KeyValueProcessor.java
data-prepper-plugins/key-value-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/keyvalue/KeyValueProcessorConfig.java
data-prepper-plugins/key-value-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/keyvalue/KeyValueProcessorTests.java
data-prepper-plugins/mutate-event-processors/build.gradle
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/RenameKeyProcessor.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/RenameKeyProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/test/java/org/opensearch/dataprepper/plugins/processor/mutateevent/RenameKeyProcessorTests.java

Add support for convering keys to lowercase/uppercase in RenameKeyProcessor.
Reused existing TransformOption in KeyValue processor in RenameKeyProcessor.
Addresses part of the issue #5757 

Add support for convering keys to lowercase/uppercase in RenameKeyProcessor

---

jenkins/release.jenkinsFile

This PR adds the change to download maven artifacts dynamically. I can confirm that related permissions have been added to jenkins. See the [diff](https://github.com/opensearch-project/opensearch-ci/issues/598#issuecomment-3005841573) of deployment stack. 
related https://github.com/opensearch-project/opensearch-build/issues/5586

Refactor maven downloading logic to be dynamic

---

data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/buffer/KafkaBuffer.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/buffer/KafkaBufferTest.java

Fixes null pointer issue that is causing pipeline creation failure when producer properties exists and the CompressionOption is null.
Resolves #5841

Add check for null compression option

---

.github/workflows/maven-publish-snapshot.yml
buildSrc/src/main/groovy/data-prepper.publish.gradle

Adds a nightly build to produce Maven `SNAPSHOT` artifacts to the OpenSearch Maven snapshot repo. This runs every weekday at 5:00 UTC.
This PR requires new permissions from the @opensearch-project/engineering-effectiveness team.
Resolves #5796

Adds a nightly build to produce Maven SNAPSHOT artifacts

---

RELEASING.md

Adds some additional instructions for checking Maven artifacts and moves the further details section to the bottom.
N/A

Adds some additional instructions for checking Maven artifacts

---

data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/integration/ProcessorSwapPipelineIT.java
data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/integration/ProcessorValidationIT.java
data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/plugins/BaseEventsTrackingProcessor.java
data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/plugins/BasicEventsTrackingTestProcessor.java
data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/plugins/SingleThreadEventsTrackingTestProcessor.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/core/parser/PipelineTransformer.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/core/pipeline/Pipeline.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/core/pipeline/PipelineRunnerImpl.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/core/pipeline/ProcessWorker.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/core/pipeline/PipelineRunnerTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/core/pipeline/ProcessWorkerTest.java
data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateProcessorITWithAcks.java

This reworks the recent code for the `ProcessorProvider` to create a provider per processor thread. 
With this fix, the processor swaps will not work correctly, but this is not complete anyway.
**New integration test**
This includes an integration test which fails on `main`.
The test exactly shows what I expected to see, which is that the last processor instance is used by all threads.
```
Expected: <1>
but: was <0>
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
at org.opensearch.dataprepper.integration.ProcessorValidationIT.lambda$verifySingleThreadUsage$4(ProcessorValidationIT.java:217)
at org.junit.jupiter.api.AssertAll.lambda$assertAll$0(AssertAll.java:68)
at …
```

Fixes a regression in core where @SingleThread annotated processors are only running the last instance.

---

.github/workflows/release.yml
e2e-test/build.gradle
release/smoke-tests/README.md
release/smoke-tests/run-smoke-tests.sh

The Data Prepper smoke tests have been failing during release for a long time. This PR is the last step in #3524 to update the smoke tests to run the `e2e-tests`. This gives consistency across tests.
With this change, the smoke tests run three select end-to-end tests.
* `:e2e-test:log:basicLogEndToEndTest`
* `:e2e-test:trace:rawSpanPeerForwarderEndToEndTest`
* `:e2e-test:trace:serviceMapPeerForwarderEndToEndTest`
I tested this by pushing to the `main` branch of my fork and running the Release workflow.
You can see the results here:
https://github.com/dlvenable/data-prepper/actions/runs/16525916962
Note that the Promote job fails for unrelated reasons.
Resolves #3568
For more …

Updated the smoke tests scripts to use the end-to-end tests

---

data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/S3ScanPartitionCreationSupplier.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/s3/S3ScanPartitionCreationSupplierTest.java

Previously, it was possible for subsequent s3 scans to ignore the start_time or range during scheduled scan so that old objects could be processed. This change just checks start time in all scan cases to ensure no older objects are discovered on subsequent scans

S3 scheduled scan should consider start time on subsequent scans

---

data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/configuration/IsolationLevel.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/configuration/KafkaIsolationLevelConfig.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaCustomConsumerFactory.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/source/SourceTopicConfig.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/configuration/IsolationLevelTest.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/source/KafkaSourceConfigTest.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/source/SourceTopicConfigTest.java
data-prepper-plugins/kafka-plugins/src/test/resources/sample-pipelines.yaml

This pull request adds support for the `isolation.level` Kafka consumer configuration in Data Prepper.
The following changes were made:
- Introduced a new method `getIsolationLevel()` in the `TopicConsumerConfig` interface.
- Implemented the new property `isolation_level` with a default value of `"read_uncommitted"` in both:
- `SourceTopicConfig` (Kafka source plugin)
- `BufferTopicConfig` (Kafka buffer plugin)
- Ensured backward compatibility by setting sensible defaults and integrating with existing configuration parsing logic.
- This allows users to configure Data Prepper to read only committed messages by setting `isolation_level: read_committed` in their pipeline YAML file.
This is especially useful when working with transactional Kafka producers and ensures message consistency in …

Support isolation.level config for Kafka consumer

---

data-prepper-plugins/otlp-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/otlp/metrics/OtlpSinkMetrics.java
data-prepper-plugins/otlp-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/otlp/metrics/OtlpSinkMetricsTest.java

This PR updates the OTLP sink metrics to use dot notation (.) instead of underscore (_) in metric names.
This aligns with the convention used across other Data Prepper plugins and improves consistency and compatibility with metric backends that treat dot-separated tokens as hierarchy.
N/A

fixes OTLP sink metric names to use dot notation instead of underscores

---

release/release-notes/data-prepper.change-log-2.12.1.md

Changelog for Data Prepper 2.12.1
```
git fetch upstream
git switch 2.12
git pull
git-release-notes 2.12.0..HEAD markdown > release/release-notes/data-prepper.change-log-2.12.1.md
git switch main
```
N/A

Changelog for Data Prepper 2.12.1

---

release/release-notes/data-prepper.release-notes-2.12.1.md

Adds the release notes for Data Prepper 2.12.1
N/A

Release notes for Data Prepper 2.12.1

---

jenkins/release.jenkinsFile

Updates the Jenkins library to 10.2.2 to fix Maven publication.
This matches the version from `opensearch-protobufs`:
https://github.com/opensearch-project/opensearch-protobufs/blob/abd05755f5deef237e1fe27ebe8527df68ebd004/jenkins/release.jenkinsFile#L1
The most recent build failed on Maven publication:
https://build.ci.opensearch.org/job/release-data-prepper/21/
N/A

Updates the Jenkins library to 10.2.2 to fix Maven publication.

---

data-prepper-plugins/cloudwatch-logs/README.md
data-prepper-plugins/cloudwatch-logs/src/integrationTest/java/org/opensearch/dataprepper/plugins/sink/cloudwatch_logs/CloudWatchLogsIT.java
data-prepper-plugins/cloudwatch-logs/src/main/java/org/opensearch/dataprepper/plugins/sink/cloudwatch_logs/CloudWatchLogsSink.java
data-prepper-plugins/cloudwatch-logs/src/main/java/org/opensearch/dataprepper/plugins/sink/cloudwatch_logs/client/CloudWatchLogsClientFactory.java
data-prepper-plugins/cloudwatch-logs/src/main/java/org/opensearch/dataprepper/plugins/sink/cloudwatch_logs/config/CloudWatchLogsSinkConfig.java
data-prepper-plugins/cloudwatch-logs/src/test/java/org/opensearch/dataprepper/plugins/sink/cloudwatch_logs/CloudWatchLogsSinkTest.java
data-prepper-plugins/cloudwatch-logs/src/test/java/org/opensearch/dataprepper/plugins/sink/cloudwatch_logs/client/CloudWatchLogsClientFactoryTest.java
data-prepper-plugins/cloudwatch-logs/src/test/java/org/opensearch/dataprepper/plugins/sink/cloudwatch_logs/config/CloudWatchLogsSinkConfigTest.java

Adds optional `endpoint` configuration property to CloudWatch Logs sink plugin to allow overriding the default CloudWatch Logs service endpoint.
N/A

Add endpoint override support to CloudWatch Logs sink

---

data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/configuration/StreamConfig.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/ShardConsumerFactory.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/ShardConsumerFactoryTest.java

This change adds a `disable_checkpointing` flag to the stream configuration for the DDB source. When enabled, the source will start processing shards from the TRIM_HORIZON whenever they are acquired regardless of checkpoint.

Add disable_checkpointing flag for ddb source stream

---

data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkRetryStrategy.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkRetryStrategyTests.java

feat(sink/opensearch): Retry DELETE operations on 404 status
Enhances the `BulkRetryStrategy` to retry DELETE operations that initially fail with a 404 (Not Found) status. This addresses race conditions where a delete might be processed before its corresponding create in the same bulk request due to eventual consistency.
- Modified `canRetry` and `createBulkRequestForRetry` to identify and allow retries specifically for `DELETE + 404`.
- Added unit tests verifying the new retry behavior for `DELETE + 404` and ensuring other 404s are retried.
Resolves #5521 …

feat(sink/opensearch): Retry DELETE operations on 404 status

---

data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSink.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSinkTest.java

Currently, writing to a DLQ with an empty message leads to an error as seen in #5974. Ideally we find out the cause of this missing data, but writing with an empty message is better than having pipeline worker crash
Resolves #5974

Convert null message to empty string in DLQ to avoid NPE

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/JacksonEventKey.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/event/JacksonEventKeyTest.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/event/JacksonEventTest.java
data-prepper-plugins/csv-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/csv/CsvProcessorTest.java
data-prepper-plugins/key-value-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/keyvalue/KeyValueProcessorTests.java
data-prepper-plugins/parse-json-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/parse/json/ParseJsonProcessorTest.java

Signed-off-by: Alekhya Parisha <aparisha@amazon.com>
- Updated isValidKey method to allow spaces and dollar signs in keys
- Modified tests to reflect new valid characters
- ddresses GitHub issue #[5978](https://github.com/opensearch-project/data-prepper/issues/5978): Add support for additional characters in JackonEventKey
Resolves #5978 

Add support for spaces and dollar signs in JacksonEventKey

---

build.gradle

Updates Netty to 4.1.124 to fix CVE-2025-55163.
N/A
Fixes CVE-2025-55163.

Update Netty to 4.1.124 to fix CVE-2025-55163.

---

data-prepper-plugins/dynamodb-source/build.gradle
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/DynamoDBSourceConfig.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/coordination/partition/StreamPartition.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/model/ShardCheckpointStatus.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/ShardAcknowledgementManager.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/ShardConsumer.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/ShardConsumerFactory.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/StreamCheckpointer.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/StreamScheduler.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/coordination/partition/StreamPartitionTest.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/model/ShardCheckpointStatusTest.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/ShardAcknowledgementManagerTest.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/ShardConsumerFactoryTest.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/ShardConsumerTest.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/StreamSchedulerTest.java

This change reverts a previous commit that removed the changes to checkpoint acknowledgments for streams in the dynamodb source. It then adds some changes that locally have fixed the issues that were seen during acknowledgment checkpointing with data loss and acknowledgment timeouts
Resolves #4764 

Add acknowledgment checkpointing with fixes to previous issues

---

data-prepper-plugins/saas-source-plugins/microsoft-office365-source/src/main/java/org/opensearch/dataprepper/plugins/source/microsoft_office365/utils/Constants.java

**What?**
This commit changes microsoft office365 plugin name from microsoft-office365 to microsoft_office365.
**Why?**
Following the OSI naming convention to use underscore
Signed-off-by: Wenjie Yao <wjyao@amazon.com>
- [N/A] New functionality includes testing.
- [N/A ] New functionality has a documentation issue. Please link to it in this PR.
- [N/A ] New functionality has javadoc added

Update microsoft office365 plugin name to follow OSI naming convention

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/trace/DefaultTraceGroupFields.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/trace/JacksonSpan.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/trace/DefaultTraceGroupFieldsTest.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/trace/JacksonSpanTest.java

Add json serialization for DefaultTraceGroupFields so that serialization/deserialization occurs properly for the metadata stored when OTEL output_format is used.
Resolves #5930 

Add json serialization for DefaultTraceGroupFields

---

data-prepper-plugin-framework/src/main/java/org/opensearch/dataprepper/plugin/ExtensionsApplier.java
data-prepper-plugins/aws-plugin/src/main/java/org/opensearch/dataprepper/plugins/aws/AwsSecretsSupplier.java
data-prepper-plugins/aws-plugin/src/test/java/org/opensearch/dataprepper/plugins/aws/AwsSecretsSupplierTest.java

Adds error log that is swallowed for when secret can't be retrieved.

Add logging for when secret is unable to be retrieved

---

data-prepper-plugin-framework/src/main/java/org/opensearch/dataprepper/plugin/ExtensionLoader.java
data-prepper-plugin-framework/src/main/java/org/opensearch/dataprepper/plugin/ExtensionsApplier.java
data-prepper-plugin-framework/src/main/java/org/opensearch/dataprepper/plugin/PluginCreatorContext.java
data-prepper-plugin-framework/src/test/java/org/opensearch/dataprepper/plugin/ExtensionsApplierTest.java
data-prepper-plugin-framework/src/test/java/org/opensearch/dataprepper/plugin/PluginCreatorContextTest.java
data-prepper-plugins/aws-plugin/src/test/java/org/opensearch/dataprepper/plugins/aws/AwsSecretsSupplierTest.java

Improve extension loading by prioritizing dependencies rather than prioritizing configured plugins. collect extension plugin errors on apply

Improve extension loading by prioritizing dependencies, collect extension plugin errors on apply

---

buildSrc/build.gradle
buildSrc/src/main/groovy/data-prepper.jmh.gradle
data-prepper-expression/build.gradle
data-prepper-expression/src/jmh/java/org/opensearch/dataprepper/expression/ConditionalExpressionEvaluationMeasure.java
data-prepper-plugins/http-source/build.gradle

This PR does two things:
1. Makes a Gradle convention plugin for JMH. Use this in the existing JMH measurement.
2. Adds a new JMH measurement for Data Prepper expressions.
N/A

JMH measurement for Data Prepper Expressions and a Gradle convention plugin

---

data-prepper-plugins/aws-lambda/build.gradle
data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/common/LambdaCommonHandler.java
data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/common/ResponseEventHandlingStrategy.java
data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/common/accumlator/InMemoryBuffer.java
data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/common/accumlator/InMemoryBufferSynchronized.java
data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/common/config/LambdaCommonConfig.java
data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/processor/AggregateResponseEventHandlingStrategy.java
data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/processor/LambdaCacheKey.java
data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/processor/LambdaProcessor.java
data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/processor/LambdaProcessorConfig.java
data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/processor/LambdaResponseMode.java
data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/processor/StrictResponseEventHandlingStrategy.java
data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/sink/LambdaSink.java
data-prepper-plugins/aws-lambda/src/test/java/org/opensearch/dataprepper/plugins/lambda/processor/AggregateResponseEventHandlingStrategyTest.java
data-prepper-plugins/aws-lambda/src/test/java/org/opensearch/dataprepper/plugins/lambda/processor/LambdaCacheKeyTest.java
data-prepper-plugins/aws-lambda/src/test/java/org/opensearch/dataprepper/plugins/lambda/processor/LambdaProcessorTest.java
data-prepper-plugins/aws-lambda/src/test/java/org/opensearch/dataprepper/plugins/lambda/processor/StrictResponseEventHandlingStrategyTest.java
data-prepper-plugins/aws-lambda/src/test/java/org/opensearch/dataprepper/plugins/lambda/utils/LambdaTestSetupUtil.java
data-prepper-plugins/aws-lambda/src/test/resources/lambda-processor-cache-multiple-type-keys-small-ttl.yaml
data-prepper-plugins/aws-lambda/src/test/resources/lambda-processor-cache-multiple-type-keys.yaml
data-prepper-plugins/aws-lambda/src/test/resources/lambda-processor-cache-nested-key.yaml
data-prepper-plugins/aws-lambda/src/test/resources/lambda-processor-cache-string-key.yaml
data-prepper-plugins/aws-lambda/src/test/resources/lambda-processor-success-config-with-keys-merge-mode.yaml
data-prepper-plugins/aws-lambda/src/test/resources/lambda-processor-success-config-with-keys.yaml

Add caching support to `aws_lambda` processor.
The cache config can be added to existing lambda config as follows:
```
aws_lambda:
<existing options>
cache:
ttl: <ttl in seconds>
max_size: <maximum_size_in_bytes>
```
In addition, caching requires a set of keys whose values are used as cache keys. A new `keys` is added to the config at the top level so that even lambda processors without caching can used this option to send only a partial list of keys to the lambda function. The result from the lambda function can be either "merged" with the original Event contents or replace the original event contents. New config for this is 
```
aws_lambda:
<existing options>
keys: ["key1", "key2"]
response_mode: "replace" (default) or "merge"
```
`keys` field is mandatory when using caching.
Resolves …

Add caching support to AWS lambda processor

---

performance-test/README.md
performance-test/build.gradle

This updates Gatline to 3.13 in the `performance-test` project. This version no longer has the zinc compiler and we don't use Scala anyway. It also uses `--simulation` instead of different Gradle task names. So I've updated the `README.md` file.
N/A

Updates to Gatling 3.13 in the performance-test project

---

data-prepper-plugins/sqs-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/sqs/SqsSinkBatch.java
data-prepper-plugins/sqs-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/sqs/SqsSinkService.java
data-prepper-plugins/sqs-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/sqs/SqsThresholdConfig.java
data-prepper-plugins/sqs-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/sqs/SqsSinkServiceTest.java

This PR enables immediate flushing in the SQS sink by allowing a flush interval of 0 seconds and improving timing precision from seconds to milliseconds. Added unit test coverage to verifies that events are marked for immediate flushing when interval is 0.
N/A

Allow flush interval to be 0 for immediate flush in sqs sink

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/metrics/PluginMetrics.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/metrics/PluginMetricsTest.java
data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/integration/PipelinesWithAcksIT.java
data-prepper-plugins/otel-logs-source/src/main/java/org/opensearch/dataprepper/plugins/source/otellogs/OTelLogsGrpcService.java
data-prepper-plugins/otel-logs-source/src/main/java/org/opensearch/dataprepper/plugins/source/otellogs/OTelLogsSource.java
data-prepper-plugins/otel-logs-source/src/test/java/org/opensearch/dataprepper/plugins/source/otellogs/OTelLogsGrpcServiceTest.java
data-prepper-plugins/otel-metrics-source/src/main/java/org/opensearch/dataprepper/plugins/source/otelmetrics/OTelMetricsGrpcService.java
data-prepper-plugins/otel-metrics-source/src/main/java/org/opensearch/dataprepper/plugins/source/otelmetrics/OTelMetricsSource.java
data-prepper-plugins/otel-metrics-source/src/test/java/org/opensearch/dataprepper/plugins/source/otelmetrics/OTelMetricsGrpcServiceTest.java
data-prepper-plugins/otel-trace-source/src/main/java/org/opensearch/dataprepper/plugins/source/oteltrace/OTelTraceGrpcService.java
data-prepper-plugins/otel-trace-source/src/main/java/org/opensearch/dataprepper/plugins/source/oteltrace/OTelTraceSource.java
data-prepper-plugins/otel-trace-source/src/test/java/org/opensearch/dataprepper/plugins/source/oteltrace/OTelTraceGrpcServiceTest.java
data-prepper-plugins/otlp-source/src/main/java/org/opensearch/dataprepper/plugins/source/otlp/OTLPSource.java

This change adds logic for some plugin metrics to take in a metrics prefix. This helps the user to differentiate between the OTLP source and sink metrics, as well as different traces/metrics/logs received from the source. Some example output metric names:
- `otlp.metrics.payloadSize.sum`
- `otlp.metrics.requestProcessDuration.count`
- `otlp.traces.successRequests.count`
- `otlp.traces.requestProcessDuration.sum`
- `otlp.traces.requestProcessDuration.count`
- `otlp.logs.payloadSize.count`
- `otlp.logs.payloadSize.sum`
Also verified that the individual OTel logs, metrics, and traces sources had their metrics unchanged.
For more information on following Developer Certificate of …

Add metrics prefix to OTLP source

---

data-prepper-plugins/cloudwatch-logs/src/main/java/org/opensearch/dataprepper/plugins/sink/cloudwatch_logs/client/CloudWatchLogsDispatcher.java
data-prepper-plugins/cloudwatch-logs/src/test/java/org/opensearch/dataprepper/plugins/sink/cloudwatch_logs/client/CloudWatchLogsDispatcherTest.java

This change fixes an issue with acknowledgments not happening correctly in the cloudwatch sink, as the event handles are not released after sending to cloudwatch. Also adds more unit tests

Fix issue where event handles are not released for cloudwatch logs sink, add more tests

---

data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/S3ClientBuilderFactory.java

Enables cross-region support for the `s3` source, both for SQS and scan. This is enabled by enabling the `crossRegionAccessEnabled` flag on the S3 client.
Resolves #4470
Resolves #4811

Support cross-region reads from S3 via S3 client

---

buildSrc/src/main/groovy/data-prepper.publish.gradle

This PR updates the Gradle build files to fix compatibility with Gradle 9.
The current syntax using `$System.env.VARIABLE_NAME` for accessing environment variables is not compatible with Gradle 9.
This format is used in this repository for Sonatype credentials for SNAPSHOT publication. This fails with under Gradle 9.
```gradle
credentials {
username = "$System.env.SONATYPE_USERNAME"
password = "$System.env.SONATYPE_PASSWORD"
}
```
See [example failed workflow here](https://github.com/opensearch-project/opensearch-remote-metadata-sdk/actions/runs/17023398832/job/48255946880#step:5:74).
Update to use the `System.getenv()` method instead:
```gradle
credentials {
username = System.getenv("SONATYPE_USERNAME")
password = System.getenv("SONATYPE_PASSWORD")
}
```
Example fix which restored …

fix: Update System.env syntax for Gradle 9 compatibility

---

data-prepper-plugins/saas-source-plugins/microsoft-office365-source/src/main/java/org/opensearch/dataprepper/plugins/source/microsoft_office365/Office365Source.java
data-prepper-plugins/saas-source-plugins/microsoft-office365-source/src/main/java/org/opensearch/dataprepper/plugins/source/microsoft_office365/Office365SourceConfig.java
data-prepper-plugins/saas-source-plugins/microsoft-office365-source/src/test/java/org/opensearch/dataprepper/plugins/source/microsoft_office365/Office365SourceConfigTest.java

This commit makes two changes.
1. Change m365 connector default lookback days to 0 per requested. There will be next change to make it configureable soon.
2. Change number of worker threads based on performance test. During performance test we observe the avg m365 api latency is 235ms. With 7 threads, assuming all threads are busy the TPM would be around 1800 request per minute. It would optimize the throughput while not breach 2000 TPM API limit.

Change m365 lookback days to 0 and number of worker threads to 7

---

data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/KeyGenerator.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/accumulator/ObjectKey.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/s3/KeyGeneratorTest.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/s3/accumulator/ObjectKeyTest.java

`object_key` and `path_prefix` configuration options under S3 sink are optional. If not provided, S3 sink should write to the root of the bucket, but in the current state, it is failing. This code change fixes it.
Resolves #6090

S3 sink without path_prefix provided should write to bucket root

---

data-prepper-plugins/saas-source-plugins/microsoft-office365-source/src/main/java/org/opensearch/dataprepper/plugins/source/microsoft_office365/Office365SourceConfig.java
data-prepper-plugins/saas-source-plugins/microsoft-office365-source/src/test/java/org/opensearch/dataprepper/plugins/source/microsoft_office365/Office365SourceConfigTest.java

This commit reduces the m365 worker thread count from 7 to 2. This is because the worker thread is per host and we need to ensure there are not too many threads in total to avoid api throttling.
The suggestion is to estimate based on 2 ~ 4 OCU. Original 7 is the estimated based on total threads. Changing to 2 would fit for 4 OCU.

Reduce m365 worker thread count from 7 to 2

---

data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/SearchAccessorStrategy.java

From Nov 19, 2024, Amazon OpenSearch Serverless supports Point in Time (PIT).
https://aws.amazon.com/about-aws/whats-new/2024/11/amazon-opensearch-serverless-pit-search/?nc1=h_ls
So we can enable Point in time for Amazon OpenSearch Serverless
https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/SearchAccessorStrategy.java#L152
Resolves #[#5493](https://github.com/opensearch-project/data-prepper/issues/5493)
[https://docs.opensearch.org/latest/data-prepper/pipelines/configuration/sources/opensearch/#default-search-behavior](https://docs.opensearch.org/latest/data-prepper/pipelines/configuration/sources/opensearch/#default-search-behavior)
```　
For Amazon OpenSearch …
```

Enable Point in time for Amazon OpenSearch Serverless

---

data-prepper-plugins/cloudwatch-logs/src/integrationTest/java/org/opensearch/dataprepper/plugins/sink/cloudwatch_logs/CloudWatchLogsIT.java

Add check for event handle releases in integration tests

Add check for event handle releases in integration tests

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/configuration/SinkForwardConfig.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/configuration/SinkModel.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/sink/SinkContext.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/sink/SinkForwardRecordsContext.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/configuration/SinkForwardConfigTest.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/configuration/SinkModelTest.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/sink/SinkContextTest.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/sink/SinkForwardRecordsContextTest.java
data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/integration/DLQHeadlessPipelinesIT.java
data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/integration/ForwardingHeadlessPipelinesIT.java
data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/integration/HeadlessPipelinesIT.java
data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/plugins/InMemorySink.java
data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/plugins/SimpleProcessor.java
data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/plugins/SimpleProcessorConfig.java
data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/forward-pipeline.yaml
data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/pipeline-dlq.yaml
data-prepper-core/src/main/java/org/opensearch/dataprepper/core/parser/PipelineTransformer.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/core/pipeline/PipelineRunnerImpl.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/core/parser/PipelineTransformerTests.java
data-prepper-core/src/test/resources/missing_source_multiple_pipeline_configuration.yml
data-prepper-pipeline-parser/src/main/java/org/opensearch/dataprepper/pipeline/parser/model/PipelineConfiguration.java
data-prepper-plugins/common/src/main/java/org/opensearch/dataprepper/plugins/sink/FileSink.java

Add support for forwarding successful records from sinks using SinkContext.
A new config option is added to all sinks
```
forward_to: 
pipelines: [ <list of sub-pipepine names> ]
with_data:
key: value
with_metadata:
key: value
```
Resolves #5985 

Add support for forwarding successful records from sinks using SinkContext

---

data-prepper-test/plugin-test-framework/src/main/java/org/opensearch/dataprepper/test/plugins/DataPrepperPluginTest.java
data-prepper-test/plugin-test-framework/src/main/java/org/opensearch/dataprepper/test/plugins/junit/BaseDataPrepperPluginStandardTestSuite.java
data-prepper-test/plugin-test-framework/src/main/java/org/opensearch/dataprepper/test/plugins/junit/DataPrepperPluginTestContextParameterResolver.java
data-prepper-test/plugin-test-framework/src/main/java/org/opensearch/dataprepper/test/plugins/junit/DataPrepperPluginTestFramework.java
data-prepper-test/plugin-test-framework/src/main/java/org/opensearch/dataprepper/test/plugins/junit/DataPrepperPluginTestFrameworkExtension.java
data-prepper-test/plugin-test-framework/src/main/java/org/opensearch/dataprepper/test/plugins/junit/PluginProviderParameterResolver.java
data-prepper-test/plugin-test-framework/src/test/java/org/opensearch/dataprepper/plugins/test/TestPluggableInterface.java
data-prepper-test/plugin-test-framework/src/test/java/org/opensearch/dataprepper/plugins/test/TestPlugin.java
data-prepper-test/plugin-test-framework/src/test/java/org/opensearch/dataprepper/plugins/test/TestPluginConfiguration.java
data-prepper-test/plugin-test-framework/src/test/java/org/opensearch/dataprepper/test/plugins/DataPrepperPluginIT.java
data-prepper-test/plugin-test-framework/src/test/java/org/opensearch/dataprepper/test/plugins/junit/DataPrepperPluginTestContextParameterResolverTest.java
data-prepper-test/plugin-test-framework/src/test/java/org/opensearch/dataprepper/test/plugins/junit/PluginProviderParameterResolverTest.java

Updated the approach to the plugin framework test to use only the `@DataPrepperPluginTest` annotation. This way we don't need to use `@ExtendWith(DataPrepperPluginTestFrameworkExtension.class)` as well. Deprecate the `DataPrepperPluginTestFrameworkExtension`.
This change also makes it easier to extend and I have some other upcoming changes that would make use of it.
I also added an integration test that runs the test framework for a test plugin.
N/A

Updates plugin framework test to use @DataPrepperPluginTest instead of extension

---

data-prepper-plugins/sqs-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/sqs/SqsSinkBatch.java

The SQS sink is giving no indication in the logs when it fails to write to SQS. This leaves pipeline authors at a loss of what to do.
N/A

Log the error message from SQS when failing to send a message

---

data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateActionSynchronizer.java

The `aggregate` processor logs errors at the `DEBUG` level. This PR logs them at the `ERROR` level.
N/A

Update the aggregate processor to log errors at the error level.
