.github/workflows/data-prepper-trace-analytics-e2e-tests.yml
.github/workflows/gradle.yml
build-resources.gradle
data-prepper-core/integrationTest.gradle
data-prepper-plugins/elasticsearch/build.gradle
data-prepper-plugins/otel-trace-group-prepper/build.gradle
research/zipkin-elastic-to-otel/build.gradle

This PR re-enables CI by publish locally built OpenSearch artifacts to maven, which remains as a temporary solution until we have public maven.
Note: `data-prepper-plugins:elasticsearch:integTest` is disabled due to 
```
Execution failed for task ':data-prepper-plugins:elasticsearch:integTest'.
> Could not resolve all files for configuration ':data-prepper-plugins:elasticsearch:opensearch_distro_extracted_testclusters-data-prepper-plugins-elasticsearch-integTest-0-1.0.0-SNAPSHOT-'.
> Could not resolve opensearch-distribution-snapshot:opensearch:1.0.0-SNAPSHOT.
Required by:
project :data-prepper-plugins:elasticsearch
> Could not resolve opensearch-distribution-snapshot:opensearch:1.0.0-SNAPSHOT.
> Could not get resource 'https://snapshots-no-kpi.opensearch.org/downloads/opensearch/opensearc …
```

MAINT: enable CI by building local OpenSearch dependencies

---

.github/workflows/data-prepper-trace-analytics-e2e-tests.yml
.github/workflows/gradle.yml
build-resources.gradle
data-prepper-core/integrationTest.gradle
data-prepper-plugins/opensearch/build.gradle
data-prepper-plugins/otel-trace-group-prepper/build.gradle
examples/dev/trace-analytics-sample-app/Dockerfile
research/zipkin-elastic-to-otel/build.gradle

Signed-off-by: qchea <qchea@amazon.com>
This PR
(1) Nail down local build of OS version to 1.0.0-alpha1
(2) re-enable integTest
(3) bumped the ODFE docker version used in github workflow

MAINT: re-enable integTest task in OpenSearch sink plugin

---

build-resources.gradle
data-prepper-core/integrationTest.gradle
data-prepper-core/src/integrationTest/java/com/amazon/dataprepper/integration/EndToEndRawSpanTest.java
data-prepper-core/src/integrationTest/java/com/amazon/dataprepper/integration/EndToEndServiceMapTest.java
data-prepper-plugins/blocking-buffer/README.md
data-prepper-plugins/opensearch/README.md
data-prepper-plugins/opensearch/build.gradle
data-prepper-plugins/opensearch/odfe_security.md
data-prepper-plugins/opensearch/security.md
data-prepper-plugins/opensearch/src/main/java/com/amazon/dataprepper/plugins/sink/opensearch/OpenSearchSink.java
data-prepper-plugins/otel-trace-group-prepper/README.md
data-prepper-plugins/otel-trace-group-prepper/build.gradle
data-prepper-plugins/otel-trace-raw-prepper/README.md
data-prepper-plugins/otel-trace-source/README.md
data-prepper-plugins/peer-forwarder/README.md
data-prepper-plugins/service-map-stateful/README.md
deployment-template/k8s/README.md
docs/dev/trace-analytics-rfc.md
docs/readme/project_setup.md
docs/readme/trace_overview.md
docs/readme/trace_setup.md
research/zipkin-elastic-to-otel/build.gradle

This PR
1. renames es version to opensearch version
2. fixes hyperlinks to redirect to opensearch-project
3. rename elasticsearch into opensearch wherever proper in .md

MAINT: renaming elasticsearch to opensearch -- second pass

---

.github/workflows/opensearch-sink-odfe-before-1_13_0-integration-tests.yml
.github/workflows/opensearch-sink-odfe-since-1_13_0-integration-tests.yml
.github/workflows/opensearch-sink-os-integration-tests.yml
data-prepper-core/integrationTest.gradle
data-prepper-core/src/integrationTest/java/com/amazon/dataprepper/integration/EndToEndServiceMapTest.java
data-prepper-plugins/opensearch/build.gradle
data-prepper-plugins/opensearch/src/main/java/com/amazon/dataprepper/plugins/sink/opensearch/IndexStateManagement.java
data-prepper-plugins/opensearch/src/test/java/com/amazon/dataprepper/plugins/sink/opensearch/OpenSearchSinkIT.java
data-prepper-plugins/opensearch/src/test/java/com/amazon/dataprepper/plugins/sink/opensearch/OpenSearchTests.java

This PR
(1) Replaces ODFE docker image with OS staging docker image for tests including
- opensearch sink integration tests
- service map e2e tests
(2) Replaces class and variable names including ODFE with OpenSearch
Note: items remain to be replaced
(1) ODFE REST APIs: e.g. _opendistro/..
(2) ODFE image in examples
(3) ODFE or opendistro in docs

MAINT: use OpenSearch 1.0.0-beta1 docker image for testing

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/workflows/data-prepper-trace-analytics-e2e-tests.yml
.github/workflows/gradle.yml
.github/workflows/opensearch-sink-odfe-before-1_13_0-integration-tests.yml
.github/workflows/opensearch-sink-odfe-since-1_13_0-integration-tests.yml
.github/workflows/opensearch-sink-os-integration-tests.yml
build-resources.gradle
build.gradle
data-prepper-core/integrationTest.gradle
data-prepper-core/src/integrationTest/java/com/amazon/dataprepper/integration/EndToEndServiceMapTest.java
data-prepper-plugins/opensearch/build.gradle
data-prepper-plugins/opensearch/src/main/java/com/amazon/dataprepper/plugins/sink/opensearch/IndexStateManagement.java
data-prepper-plugins/opensearch/src/main/resources/otel-v1-apm-span-index-template.json
data-prepper-plugins/opensearch/src/test/java/com/amazon/dataprepper/plugins/sink/opensearch/OpenSearchSinkIT.java
data-prepper-plugins/opensearch/src/test/java/com/amazon/dataprepper/plugins/sink/opensearch/OpenSearchTests.java
data-prepper-plugins/otel-trace-raw-prepper/src/main/java/com/amazon/dataprepper/plugins/prepper/oteltrace/model/RawSpan.java
data-prepper-plugins/otel-trace-raw-prepper/src/main/java/com/amazon/dataprepper/plugins/prepper/oteltrace/model/TraceGroup.java
data-prepper-plugins/otel-trace-raw-prepper/src/test/java/com/amazon/dataprepper/plugins/prepper/oteltrace/OTelTraceRawPrepperTest.java
examples/dev/trace-analytics-sample-app/Dockerfile

Also merged stuff from main branch about Opensearch integration tests
Note: I keep the old ISM API for testing with ODFE and also maintain applicability to AES. But the index setting name has to be new in OpenSearch backend. Thus I have to check both `index.plugins.index_state_management.policy_id` and `index.opendistro.index_state_management.policy_id`

MAINT: bump to OS 1.0 and data prepper 1.0.0.0-rc1

---

build-resources.gradle
build.gradle
data-prepper-benchmarks/service-map-stateful-benchmarks/build.gradle
data-prepper-core/build.gradle
data-prepper-core/integrationTest.gradle
data-prepper-plugins/blocking-buffer/build.gradle
data-prepper-plugins/common/build.gradle
data-prepper-plugins/opensearch/build.gradle
data-prepper-plugins/otel-trace-group-prepper/build.gradle
data-prepper-plugins/otel-trace-raw-prepper/build.gradle
data-prepper-plugins/otel-trace-source/build.gradle
data-prepper-plugins/peer-forwarder/build.gradle
data-prepper-plugins/service-map-stateful/build.gradle
research/zipkin-elastic-to-otel/build.gradle

This PR updates the entire project to use JUnit Jupiter as the test framework. No tests have been updated, but the JUnit Vintage Engine will allow the old JUnit 4 tests to continue to run. Over time as developers work on different tests, we can update those tests to JUnit 5 without having to make build changes.
Additionally, I made some stylistic improvements:
* Build files are Groovy, where camelCase should be used rather than snake_case. So I updated the versionMap accordingly.
* Groovy's double quoted strings are GStrings, which are interpolated. Where that interpolation was not necessary, I converted these to standard strings which have a single quote.
N/A
- [  ] New functionality includes testing.
- [ X ] All tests pass
- [ X ] Commits are signed per the DCO using --signoff 
By …

Use JUnit Jupiter for all projects and added Mockito to all projects

---

.github/workflows/data-prepper-trace-analytics-raw-span-compatibility-e2e-tests.yml
.github/workflows/data-prepper-trace-analytics-raw-span-e2e-tests.yml
.github/workflows/data-prepper-trace-analytics-service-map-e2e-tests.yml
.github/workflows/gradle.yml
.github/workflows/opensearch-sink-odfe-before-1_13_0-integration-tests.yml
.github/workflows/opensearch-sink-odfe-since-1_13_0-integration-tests.yml
.github/workflows/opensearch-sink-os-integration-tests.yml
build-resources.gradle
build.gradle
data-prepper-core/integrationTest.gradle
data-prepper-plugins/opensearch/build.gradle
data-prepper-plugins/opensearch/src/test/java/com/amazon/dataprepper/plugins/sink/opensearch/OpenSearchSinkIT.java
data-prepper-plugins/opensearch/src/test/java/com/amazon/dataprepper/plugins/sink/opensearch/OpenSearchTests.java
data-prepper-plugins/otel-trace-group-prepper/build.gradle
examples/dev/k8s/sample-project-applications.yaml
examples/dev/trace-analytics-sample-app/Dockerfile
examples/dev/trace-analytics-sample-app/docker-compose.yml
research/zipkin-elastic-to-otel/build.gradle

This PR updates Data Prepper to use OpenSearch 1.0.0 (release version). It is using the OpenSearch artifacts from Maven Central. The integration tests run against OpenSearch 1.0.1 due to backward compatibility limitations in 1.0.0.
* Added the AWS Sonatype Maven repository
* Updated to OpenSearch 1.0.0
* Change to support both OpenSearch 1.0.0 and ODFE in the integration tests
* GitHub build simplifications
* Docker changes
None

Updated the build to use OpenSearch 1.0.0.

---

.github/dependabot.yml
build.gradle
data-prepper-api/build.gradle
data-prepper-core/build.gradle
data-prepper-core/integrationTest.gradle
data-prepper-plugins/common/build.gradle
data-prepper-plugins/opensearch/build.gradle
data-prepper-plugins/otel-trace-group-prepper/build.gradle
data-prepper-plugins/otel-trace-raw-prepper/build.gradle
data-prepper-plugins/otel-trace-source/build.gradle
data-prepper-plugins/peer-forwarder/build.gradle
data-prepper-plugins/service-map-stateful/build.gradle
research/zipkin-elastic-to-otel/build.gradle

Our dependency versions are not always in sync across projects and dependabot merges can take a very long time because many versions are repeated. This commit consolidates some of the common dependencies which are used in different projects. The root project now includes new BOM files in all projects except `data-prepper-api`. Even though adding it to `data-prepper-api` would likely not be problematic, I wanted to avoid making any appearance of extra dependencies since this project could be used by plugins.
The follow dependencies now have BOM files:
* Micrometer
* Jackson
* AWS Java SDK v2
* AWS Java SDK v1
Additionally, I noticed that dependabot is not configured for the root Gradle project. I added this as well. 
N/A
By submitting this pull request, I confirm that my contribution is …

Gradle & dependabot improvements

---

build.gradle
data-prepper-plugins/opensearch/build.gradle

Signed-off-by: qchea <qchea@amazon.com>
This PR refactors the specification on JUnit Platform from coreProjects into all subprojects.
Note: we have to force useJUnit() in opensearch plugin due to the incompatibility of opensearch gradle plugins with JunitPlatform
None

MAINT: specifies JUnit 5 in subprojects

---

data-prepper-api/src/main/java/com/amazon/dataprepper/model/configuration/PluginSetting.java
data-prepper-plugins/grok-prepper/README.md
data-prepper-plugins/grok-prepper/build.gradle
data-prepper-plugins/grok-prepper/src/main/java/com/amazon/dataprepper/plugins/prepper/grok/GrokPrepper.java
data-prepper-plugins/grok-prepper/src/test/java/com/amazon/dataprepper/plugins/prepper/grok/GrokPrepperIT.java
data-prepper-plugins/grok-prepper/src/test/java/com/amazon/dataprepper/plugins/prepper/grok/GrokPrepperTests.java

Signed-off-by: graytaylor0 33740195+graytaylor0@users.noreply.github.com
* Grok matching functionality (single/mutli field, single/multi pattern)
* Support for named_captures_only
* Support for keep_empty_captures
* Unit tests for Grok Prepper and Integration tests using java-grok library
#304 

Grok Prepper Matching Functionality

---

data-prepper-plugins/opensearch/build.gradle
data-prepper-plugins/opensearch/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker

Problem: Unable to mock many final classes the Opensearch Sink plugin depend on, so our ability to write unit tests was extremely limited. 
Root cause of the problem: The setup remove dependency on Mockito (3.x) in favor of Elastic Search Securemock (v1.2 which wraps Mockito 1.x). However, Mockito 1.x doesn't allow mocking final classes. 
Solution: 
1. excluding securemock 
2. enable mocking of final classes with vanilla Mockito 
This is to enable me to continue unit-testing changes proposed in https://github.com/opensearch-project/data-prepper/issues/310
- [ x] Commits are signed per the DCO using --signoff 
For more information on following Developer Certificate of Origin …

Use Mockito 3.* instead of Securemock 1.2 in order to be able to mock final classes

---

examples/jaeger-hotrod/docker-compose.yml

This change uses the latest version of opensearch and opensearch dashboards images instead of elasticsearch with opendistro plugins.
The sample with opendistro for elasticsearch images have conflict with latest data-prepper plugins. 

updated to use latest opensearch instead of opendistro for elasticsearch

---

data-prepper-plugins/http-source/src/main/java/com/amazon/dataprepper/plugins/source/loghttp/HTTPSource.java
data-prepper-plugins/http-source/src/main/java/com/amazon/dataprepper/plugins/source/loghttp/HTTPSourceConfig.java
data-prepper-plugins/http-source/src/main/java/com/amazon/dataprepper/plugins/source/loghttp/LogHTTPService.java
data-prepper-plugins/http-source/src/test/java/com/amazon/dataprepper/plugins/source/loghttp/HTTPSourceTest.java

This PR 
- Registers ThrottlingService with strategy and reject handler.
- Add test case on throttling based off max_pending_requests.
#323 

ENH: add throttling service

---

data-prepper-core/integrationTest.gradle

Signed-off-by: qchea <qchea@amazon.com>
This PR syncs the Opensearch backend version used in end-to-end tests with that in `build-resources.gradle` in an attempt to resolve the flaky tests.
Note: root cause for e2e flaky failure: For some reason, opensearch:1.0.0 docker container failed to run in CI as follows:
```
> Task :data-prepper-core:createOpenSearchDockerContainer
Created container with ID 'node-0.example.com'.
> Task :data-prepper-core:startOpenSearchDockerContainer
Starting container with ID 'd13be9c57160894ca5b24f738a841aa133d1ad8f0f8e257d664eb9ea3e1c758f'.
> Task :data-prepper-core:logOpenSearchDockerContainer
Logs for container with ID 'd13be9c57160894ca5b24f738a841aa133d1ad8f0f8e257d664eb9ea3e1c758f'.
Killing opensearch process 12
Killing performance analyzer process 13
``` …

MAINT: sync opensearch version in e2e

---

THIRD-PARTY
build.gradle
data-prepper-plugins/opensearch/build.gradle
data-prepper-plugins/opensearch/src/main/java/com/amazon/dataprepper/plugins/sink/opensearch/ConnectionConfiguration.java
data-prepper-plugins/opensearch/src/test/java/com/amazon/dataprepper/plugins/sink/opensearch/ConnectionConfigurationTests.java
data-prepper-plugins/otel-trace-raw-prepper/build.gradle
data-prepper-plugins/otel-trace-source/src/main/java/com/amazon/dataprepper/plugins/certificate/acm/ACMCertificateProvider.java
data-prepper-plugins/peer-forwarder/src/main/java/com/amazon/dataprepper/plugins/prepper/peerforwarder/certificate/CertificateProviderConfig.java
gradle.properties

This PR pulls in a squashed commit of changes in the ODFE repository since the v.1.1.0 release notes where added.
This is targeting the `v1.1.x` branch, from which we will release Data Prepper v.1.1.0.
From the ODFE repository: `git rebase 142bfd3d`, squash commits.
Cherry-pick that single commit. Manually merge.

Merged in ODFE changes

---

data-prepper-plugins/opensearch/src/main/java/com/amazon/dataprepper/plugins/sink/opensearch/index/IndexConfiguration.java

The IndexConfiguration.Builder should set correct settings based on argument. This fixes that.
None

Fix IndexConfiguration.Builder replicas number

---

data-prepper-core/src/test/java/com/amazon/dataprepper/plugin/ClasspathPluginProviderTest.java
data-prepper-core/src/test/java/com/amazon/dataprepper/plugins/TestSink.java
data-prepper-core/src/test/java/com/amazon/dataprepper/plugins/TestSinkDeprecatedApproach.java
data-prepper-core/src/test/java/com/amazon/dataprepper/plugins/TestSource.java
data-prepper-plugins/blocking-buffer/src/main/java/com/amazon/dataprepper/plugins/buffer/blockingbuffer/BlockingBuffer.java
data-prepper-plugins/common/src/main/java/com/amazon/dataprepper/plugins/PluginRepository.java
data-prepper-plugins/common/src/main/java/com/amazon/dataprepper/plugins/prepper/NoOpPrepper.java
data-prepper-plugins/common/src/main/java/com/amazon/dataprepper/plugins/prepper/StringPrepper.java
data-prepper-plugins/common/src/main/java/com/amazon/dataprepper/plugins/sink/FileSink.java
data-prepper-plugins/common/src/main/java/com/amazon/dataprepper/plugins/sink/StdOutSink.java
data-prepper-plugins/common/src/main/java/com/amazon/dataprepper/plugins/source/FileSource.java
data-prepper-plugins/common/src/main/java/com/amazon/dataprepper/plugins/source/RandomStringSource.java
data-prepper-plugins/common/src/main/java/com/amazon/dataprepper/plugins/source/StdInSource.java
data-prepper-plugins/common/src/test/java/com/amazon/dataprepper/plugins/ConstructorLessComponent.java
data-prepper-plugins/common/src/test/java/com/amazon/dataprepper/plugins/buffer/TestBuffer.java
data-prepper-plugins/common/src/test/java/com/amazon/dataprepper/plugins/prepper/TestPrepper.java
data-prepper-plugins/common/src/test/java/com/amazon/dataprepper/plugins/sink/TestSink.java
data-prepper-plugins/common/src/test/java/com/amazon/dataprepper/plugins/source/TestSource.java
data-prepper-plugins/grok-prepper/src/main/java/com/amazon/dataprepper/plugins/prepper/grok/GrokPrepper.java
data-prepper-plugins/http-source/src/main/java/com/amazon/dataprepper/plugins/source/loghttp/HTTPSource.java
data-prepper-plugins/opensearch/src/main/java/com/amazon/dataprepper/plugins/sink/opensearch/OpenSearchSink.java
data-prepper-plugins/otel-trace-group-prepper/src/main/java/com/amazon/dataprepper/plugins/prepper/oteltracegroup/OTelTraceGroupPrepper.java
data-prepper-plugins/otel-trace-raw-prepper/src/main/java/com/amazon/dataprepper/plugins/prepper/oteltrace/OTelTraceRawPrepper.java
data-prepper-plugins/otel-trace-source/src/main/java/com/amazon/dataprepper/plugins/source/oteltrace/OTelTraceSource.java
data-prepper-plugins/peer-forwarder/src/main/java/com/amazon/dataprepper/plugins/prepper/peerforwarder/PeerForwarder.java
data-prepper-plugins/service-map-stateful/src/main/java/com/amazon/dataprepper/plugins/prepper/ServiceMapStatefulPrepper.java

This commit updates existing plugins to use the new `pluginType` property rather than the deprecated `type`.
Resolves #322.

Update plugins for new plugin framework

---

MAINTAINERS.md

Updated the maintainers list to be current as of Nov 1, 2021.
None

Updated Maintainers list

---

README.md

This adds a small "Project Resources" section to the README. I based it on the OpenSearch README. One of the main links I wanted to get in was the link to the Data Prepper forum so that people visiting the project can find the forum easily.

Added Project Resources to the README.md

---

data-prepper-api/src/main/java/com/amazon/dataprepper/model/event/Event.java
data-prepper-api/src/main/java/com/amazon/dataprepper/model/event/JacksonEvent.java
data-prepper-api/src/main/java/com/amazon/dataprepper/model/trace/DefaultLink.java
data-prepper-api/src/main/java/com/amazon/dataprepper/model/trace/DefaultSpanEvent.java
data-prepper-api/src/main/java/com/amazon/dataprepper/model/trace/DefaultTraceGroupFields.java
data-prepper-api/src/main/java/com/amazon/dataprepper/model/trace/JacksonSpan.java
data-prepper-api/src/main/java/com/amazon/dataprepper/model/trace/Span.java
data-prepper-api/src/test/java/com/amazon/dataprepper/model/event/JacksonEventTest.java
data-prepper-api/src/test/java/com/amazon/dataprepper/model/trace/DefaultLinkTest.java
data-prepper-api/src/test/java/com/amazon/dataprepper/model/trace/DefaultSpanEventTest.java
data-prepper-api/src/test/java/com/amazon/dataprepper/model/trace/DefaultTraceGroupFieldsTest.java
data-prepper-api/src/test/java/com/amazon/dataprepper/model/trace/JacksonSpanTest.java

- Implements all trace models
- Extends event interface to eliminate unchecked casting of ArrayNode elements.
- Updated Trace interface
resolves #472 

implementing trace models and extending event implementation

---

data-prepper-core/src/main/java/com/amazon/dataprepper/pipeline/server/DataPrepperServer.java
data-prepper-plugins/http-source/README.md
data-prepper-plugins/http-source/src/main/java/com/amazon/dataprepper/plugins/source/loghttp/HTTPSource.java
data-prepper-plugins/otel-trace-source/README.md
data-prepper-plugins/otel-trace-source/src/main/java/com/amazon/dataprepper/plugins/source/oteltrace/OTelTraceSource.java
docs/core_apis.md

Warnings added if SSL is disabled for data prepper server, otel-trace-source, or http source. These warnings contain links to documentation that provides example guidance for users to set up ssl for themselves for each of these three servers.
Closes #521 

Warning for disabled SSL with http/otel trace source, document setting up SSL

---

data-prepper-logstash-configuration/build.gradle
data-prepper-logstash-configuration/src/main/java/org/opensearch/dataprepper/logstash/mapping/LogstashMappingModel.java
data-prepper-logstash-configuration/src/main/java/org/opensearch/dataprepper/logstash/mapping/LogstashPluginMapper.java

* Adds Mapping file model to map Plugins and attributes from Logstash to Data Prepper.
* Adds `LogstashPluginMapper` interface to map Plugin to PluginModel
#466 

Added Mapping Model class and supporting Mapping framework

---

data-prepper-api/src/main/java/com/amazon/dataprepper/model/event/Event.java
data-prepper-api/src/main/java/com/amazon/dataprepper/model/event/JacksonEvent.java
data-prepper-api/src/test/java/com/amazon/dataprepper/model/event/JacksonEventTest.java
data-prepper-plugins/grok-prepper/src/main/java/com/amazon/dataprepper/plugins/prepper/grok/GrokPrepper.java
data-prepper-plugins/grok-prepper/src/test/java/com/amazon/dataprepper/plugins/prepper/grok/GrokPrepperIT.java
data-prepper-plugins/grok-prepper/src/test/java/com/amazon/dataprepper/plugins/prepper/grok/GrokPrepperTests.java
data-prepper-plugins/http-source/src/main/java/com/amazon/dataprepper/plugins/source/loghttp/HTTPSource.java
data-prepper-plugins/http-source/src/main/java/com/amazon/dataprepper/plugins/source/loghttp/LogHTTPService.java
data-prepper-plugins/http-source/src/test/java/com/amazon/dataprepper/plugins/source/loghttp/HTTPSourceTest.java
data-prepper-plugins/http-source/src/test/java/com/amazon/dataprepper/plugins/source/loghttp/LogHTTPServiceTest.java
data-prepper-plugins/opensearch/src/main/java/com/amazon/dataprepper/plugins/sink/opensearch/OpenSearchSink.java
data-prepper-plugins/opensearch/src/test/java/com/amazon/dataprepper/plugins/sink/opensearch/OpenSearchSinkIT.java

integrating event model into log ingestion plugins, updated sink to support both string and event type. I apologize for the large PR. Unfortunately, doing this in smaller chunks is impossible without breaking the pipeline support.
- Introduced a `containsKey` and `isValueAList` to the event interface for calling functions to validate the contents of the event.
- Updated JacksonEvent constructor to support Json string.
- Updated HTTP Source plugin to use new log model as a `Record<Log>`
- Updated Grok Prepper to use `Event` model to support grepping on any structure as a `Record<Event>`
- Updated OpenSearch sink to support String and Event data types as a `Record<Object>`. I selected objects to be generic. enough to …

integrating event model into log ingestion plugins, updated sink to support both string and event type

---

data-prepper-core/src/main/java/com/amazon/dataprepper/DataPrepper.java
data-prepper-core/src/main/java/com/amazon/dataprepper/parser/model/DataPrepperConfiguration.java
data-prepper-core/src/main/java/com/amazon/dataprepper/pipeline/server/DataPrepperCoreAuthenticationProvider.java
data-prepper-core/src/main/java/com/amazon/dataprepper/pipeline/server/DataPrepperServer.java
data-prepper-core/src/main/java/com/amazon/dataprepper/pipeline/server/HttpBasicAuthenticationConfig.java
data-prepper-core/src/main/java/com/amazon/dataprepper/plugins/HttpBasicDataPrepperCoreAuthenticationProvider.java
data-prepper-core/src/main/java/com/amazon/dataprepper/plugins/UnauthenticatedDataPrepperCoreAuthenticationProvider.java
data-prepper-core/src/test/java/com/amazon/dataprepper/TestDataProvider.java
data-prepper-core/src/test/java/com/amazon/dataprepper/parser/model/DataPrepperConfigurationTests.java
data-prepper-core/src/test/java/com/amazon/dataprepper/plugins/HttpBasicDataPrepperCoreAuthenticationProviderTest.java
data-prepper-core/src/test/java/com/amazon/dataprepper/plugins/UnauthenticatedDataPrepperCoreAuthenticationProviderTest.java
data-prepper-core/src/test/java/com/amazon/dataprepper/server/DataPrepperServerTest.java
data-prepper-core/src/test/resources/valid_data_prepper_config_with_basic_authentication.yml
docs/core_apis.md

This adds pluggable support for authenticating Data Prepper core APIs. It currently uses HTTP Basic authentication only.
This does not include secure-by-default. The solution for that will be to update the default configuration file - not to include constants in code. I will create a follow-on PR for that.
#312

Support HTTP Basic authentication on the core Data Prepper APIs

---

data-prepper-plugins/opensearch/README.md
data-prepper-plugins/opensearch/src/main/java/com/amazon/dataprepper/plugins/sink/opensearch/index/IndexConfiguration.java
data-prepper-plugins/opensearch/src/main/java/com/amazon/dataprepper/plugins/sink/opensearch/index/IndexType.java
data-prepper-plugins/opensearch/src/test/java/com/amazon/dataprepper/plugins/sink/opensearch/index/IndexConfigurationTests.java
data-prepper-plugins/opensearch/src/test/java/com/amazon/dataprepper/plugins/sink/opensearch/index/IndexTypeTests.java

Signed-off-by: Han Jiang <jianghan@amazon.com>
We are adding the following parameter support to OpenSearch Sink plugin configuration: 
Parameter | Required | Description | Additional Comments
-- | -- | -- | --
index_type | No | Default: custom <br>One string value from the index types that Data Prepper supports: trace-analytics-raw, trace-analytics-service-map, custom | We consider two parameters, "trace_analytics_raw" and "trace_analytics_service_map", as deprecated.  If customers are using  "trace_analytics_raw" and "trace_analytics_service_map", we will show a warning on console notifying customers that they are using a parameter which will be removed and that they should use index_type instead. We will remove the two deprecated parameters in a future major version release of Data …

Support index-type parameter

---

release/docker/README.md
release/docker/config/default-data-prepper-config.yaml

The Docker distribution is now configured to include a username of `admin` and password of `admin` by default.
Resolves #312 

Authentication of core APIs by default

---

data-prepper-logstash-configuration/src/main/java/org/opensearch/dataprepper/logstash/mapping/AttributesMapperCreator.java
data-prepper-logstash-configuration/src/main/java/org/opensearch/dataprepper/logstash/mapping/AttributesMapperProvider.java
data-prepper-logstash-configuration/src/main/java/org/opensearch/dataprepper/logstash/mapping/DefaultLogstashPluginAttributesMapper.java
data-prepper-logstash-configuration/src/main/java/org/opensearch/dataprepper/logstash/mapping/DefaultPluginMapper.java
data-prepper-logstash-configuration/src/main/java/org/opensearch/dataprepper/logstash/mapping/LogstashAttributesMappings.java
data-prepper-logstash-configuration/src/main/java/org/opensearch/dataprepper/logstash/mapping/LogstashMappingModel.java
data-prepper-logstash-configuration/src/main/java/org/opensearch/dataprepper/logstash/mapping/LogstashPluginAttributesMapper.java
data-prepper-logstash-configuration/src/test/java/org/opensearch/dataprepper/logstash/mapping/AttributesMapperCreatorTest.java
data-prepper-logstash-configuration/src/test/java/org/opensearch/dataprepper/logstash/mapping/AttributesMapperProviderTest.java
data-prepper-logstash-configuration/src/test/java/org/opensearch/dataprepper/logstash/mapping/DefaultLogstashPluginAttributesMapperTest.java
data-prepper-logstash-configuration/src/test/java/org/opensearch/dataprepper/logstash/mapping/DefaultPluginMapperTest.java
data-prepper-logstash-configuration/src/test/java/org/opensearch/dataprepper/logstash/mapping/LogstashMappingModelTest.java
data-prepper-logstash-configuration/src/test/resources/org/opensearch/dataprepper/logstash/mapping/sample.mapping.yaml

I split the behavior of `DefaultPluginMapper` so that it loads the plugin mapping file and then delegates the attribute mapping to an instance of `LogstashPluginAttributesMapper`. There is a default implementation named `DefaultLogstashPluginAttributesMapper`. But, any plugin can configure the class by setting the `attributesMapperClass` property in the mapping YAML file.
I would like to provide a customizable base class for `LogstashPluginAttributesMapper`, but will do that in a separate PR after this one has been nailed down. …

Added LogstashPluginAttributesMapper for custom mapping

---

data-prepper-core/src/main/java/com/amazon/dataprepper/pipeline/server/SslUtil.java
data-prepper-plugins/common/src/main/java/com/amazon/dataprepper/plugins/certificate/file/FileCertificateProvider.java
data-prepper-plugins/http-source/src/main/java/com/amazon/dataprepper/plugins/source/loghttp/HTTPSourceConfig.java
data-prepper-plugins/peer-forwarder/src/main/java/com/amazon/dataprepper/plugins/prepper/peerforwarder/certificate/file/FileCertificateProvider.java

Fix Java 1.8 compatibility bug by removing Path.of calls

---

data-prepper-logstash-configuration/src/main/java/org/opensearch/dataprepper/logstash/mapping/DefaultLogstashPluginAttributesMapper.java
data-prepper-logstash-configuration/src/main/java/org/opensearch/dataprepper/logstash/mapping/LogstashAttributesMappings.java
data-prepper-logstash-configuration/src/main/java/org/opensearch/dataprepper/logstash/mapping/LogstashMappingModel.java
data-prepper-logstash-configuration/src/test/java/org/opensearch/dataprepper/logstash/mapping/DefaultLogstashPluginAttributesMapperTest.java
data-prepper-logstash-configuration/src/test/java/org/opensearch/dataprepper/logstash/mapping/LogstashMappingModelTest.java
data-prepper-logstash-configuration/src/test/resources/org/opensearch/dataprepper/logstash/mapping/sample-with-nulls.mapping.yaml

Corrected some null issues from the refactoring.
Part of #568

NPE bug fixes in the DefaultLogstashPluginAttributesMapper

---

data-prepper-logstash-configuration/src/main/java/org/opensearch/dataprepper/logstash/mapping/LogstashMappingModel.java
data-prepper-logstash-configuration/src/test/java/org/opensearch/dataprepper/logstash/mapping/LogstashMappingModelTest.java
data-prepper-logstash-configuration/src/test/resources/org/opensearch/dataprepper/logstash/mapping/sample-with-empty-maps.mapping.yaml

This is related to #574. Jackson was not setting the value when not present, so the maps were still empty. The previous PR only handled the situation where the maps were explicitly null.

Support maps which are not present in the YAML

---

data-prepper-api/src/main/java/com/amazon/dataprepper/model/configuration/PipelineModel.java
data-prepper-api/src/test/java/com/amazon/dataprepper/model/configuration/PipelineModelTest.java

Fixes serialization in `PipelineModel`

Update PipelineModel to fix serialization

---

data-prepper-logstash-configuration/src/main/java/org/opensearch/dataprepper/logstash/parser/LogstashVisitor.java
data-prepper-logstash-configuration/src/test/java/org/opensearch/dataprepper/logstash/parser/LogstashVisitorTest.java

Some Logstash Configurations are parsing with an `LogstashParser.AttributeContext` without a value. This PR returns a null attribute in such cases and also filters these out.

Fixed a NPE in LogstashVisitor for attributes without value

---

data-prepper-logstash-configuration/build.gradle

Removes configurations which come from parent project.
Uses Gradle strings instead of GStrings.

Minor Gradle improvements to the Logstash configuration project

---

data-prepper-logstash-configuration/src/main/java/org/opensearch/dataprepper/logstash/mapping/GrokLogstashPluginAttributesMapper.java
data-prepper-logstash-configuration/src/main/java/org/opensearch/dataprepper/logstash/mapping/GrokNamedCapturesUtil.java
data-prepper-logstash-configuration/src/test/java/org/opensearch/dataprepper/logstash/mapping/GrokLogstashPluginAttributesMapperTest.java

Signed-off-by: qchea <qchea@amazon.com>
This PR enhanced `GrokLogstashPluginAttributesMapper` with named captures by integrating GrokNamedCapturesUtil.
#466 

ENH: integrate named captures into grok logstash mapper

---

data-prepper-logstash-configuration/src/main/java/org/opensearch/dataprepper/logstash/parser/LogstashVisitor.java
data-prepper-logstash-configuration/src/test/java/org/opensearch/dataprepper/logstash/parser/LogstashVisitorTest.java

Normalizes strings by removing quotes which should not be present.

Fix issues with extra quotes in Logstash converted YAML files.

---

data-prepper-core/build.gradle
data-prepper-core/src/main/java/com/amazon/dataprepper/DataPrepperExecute.java
data-prepper-logstash-configuration/src/main/java/org/opensearch/dataprepper/logstash/LogstashConfigConverter.java
data-prepper-logstash-configuration/src/main/java/org/opensearch/dataprepper/logstash/parser/ModelConvertingLogstashVisitor.java
data-prepper-logstash-configuration/src/test/java/org/opensearch/dataprepper/logstash/parser/ModelConvertingLogstashVisitorTest.java

- Integrated Logstash converter into Data Prepper core
- Updated LogstashVisitor class name

Integrated logstash converter into Data Prepper core

---

data-prepper-api/src/main/java/com/amazon/dataprepper/model/configuration/PipelinesDataFlowModel.java
data-prepper-api/src/test/java/com/amazon/dataprepper/model/configuration/PipelinesDataFlowModelTest.java
data-prepper-logstash-configuration/src/test/java/org/opensearch/dataprepper/logstash/LogstashConfigConverterIT.java
data-prepper-logstash-configuration/src/test/resources/org/opensearch/dataprepper/logstash/empty.conf
data-prepper-logstash-configuration/src/test/resources/org/opensearch/dataprepper/logstash/empty.expected.yaml
data-prepper-logstash-configuration/src/test/resources/org/opensearch/dataprepper/logstash/http-to-opensearch.conf
data-prepper-logstash-configuration/src/test/resources/org/opensearch/dataprepper/logstash/http-to-opensearch.expected.yaml
data-prepper-logstash-configuration/src/test/resources/org/opensearch/dataprepper/logstash/log-ingest-multiple-preppers-sinks.conf
data-prepper-logstash-configuration/src/test/resources/org/opensearch/dataprepper/logstash/log-ingest-multiple-preppers-sinks.expected.yaml
data-prepper-logstash-configuration/src/test/resources/org/opensearch/dataprepper/logstash/log-ingest-to-amazon-opensearch.conf
data-prepper-logstash-configuration/src/test/resources/org/opensearch/dataprepper/logstash/log-ingest-to-amazon-opensearch.expected.yaml
data-prepper-logstash-configuration/src/test/resources/org/opensearch/dataprepper/logstash/log-ingest-to-opensearch-named-captures.conf
data-prepper-logstash-configuration/src/test/resources/org/opensearch/dataprepper/logstash/log-ingest-to-opensearch.conf
data-prepper-logstash-configuration/src/test/resources/org/opensearch/dataprepper/logstash/log-ingest-to-opensearch.expected.yaml

* Added an integration test which converts Logstash configuration files and compares against the PipelineDataFlowModel.
* Added an integration test which converts Logstash configuration files and compares them against expected YAML files.
* Updated the PipelineDataFlowModel to deserialize correctly, and added Javadocs

Added integration tests for the Logstash Configuration Converter

---

data-prepper-plugins/opensearch/README.md
data-prepper-plugins/opensearch/src/main/java/com/amazon/dataprepper/plugins/sink/opensearch/OpenSearchSink.java
data-prepper-plugins/opensearch/src/test/java/com/amazon/dataprepper/plugins/sink/opensearch/OpenSearchSinkIT.java

Signed-off-by: Han Jiang <jianghan@amazon.com>
Having the OpenSearch Sink emit a metric, bulkRequestSizeBytes, right before the request sending the batch to OpenSearch.
https://github.com/opensearch-project/data-prepper/issues/571

Add a new metric for OpenSearch Sink plugin: bulkRequestSizeBytes

---

build-resources.gradle
build.gradle
data-prepper-api/build.gradle
docs/plugin_development.md

* Support unsigned Maven publication
* Configured the Maven POM to meet Sonatype requirements, based on OpenSearch values
* Changed the group Id to `org.opensearch.dataprepper`.
Supports #421 

Support unsigned Maven publication. Set groupId to org.opensearch.dataprepper

---

data-prepper-logstash-configuration/src/main/java/org/opensearch/dataprepper/logstash/mapping/AbstractLogstashPluginAttributesMapper.java
data-prepper-logstash-configuration/src/main/java/org/opensearch/dataprepper/logstash/mapping/DefaultLogstashPluginAttributesMapper.java
data-prepper-logstash-configuration/src/main/java/org/opensearch/dataprepper/logstash/mapping/GrokLogstashPluginAttributesMapper.java
data-prepper-logstash-configuration/src/test/java/org/opensearch/dataprepper/logstash/mapping/AbstractLogstashPluginAttributesMapperTest.java
data-prepper-logstash-configuration/src/test/java/org/opensearch/dataprepper/logstash/parser/ModelConvertingLogstashVisitorTest.java

Added AbstractLogstashPluginAttributesMapper which leverages template pattern
Cleaned ModelConvertingLogstashVisitorTest class

Updated Logstash attributes mapper to use template pattern

---

data-prepper-plugins/peer-forwarder/src/main/java/com/amazon/dataprepper/plugins/prepper/peerforwarder/PeerForwarder.java

Simplifying peer forwarder local client assignment to improve readability.

codifying peer forwarder local client

---

data-prepper-plugins/common/src/main/java/com/amazon/dataprepper/plugins/prepper/NoOpPrepper.java
data-prepper-plugins/common/src/test/java/com/amazon/dataprepper/plugins/prepper/PrepperFactoryTests.java

Moves the No-op prepper from using generics to consuming Record<Event>
#607 

Update No-op prepper

---

data-prepper-plugins/opensearch/README.md
data-prepper-plugins/opensearch/opensearch_security.md
data-prepper-plugins/opensearch/security.md
data-prepper-plugins/otel-trace-group-prepper/README.md
deployment-template/ec2/README.md
deployment-template/ec2/data-prepper-ec2-deployment-cfn.yaml
deployment-template/k8s/README.md
docs/dev/trace-analytics-rfc.md
docs/schemas/trace-analytics/readme.md
examples/dev/k8s/README.md

Updated the documentation to use OpenSearch, OpenSearch Dashboard, and Amazon OpenSearch Service.
Some scripts, Docker compose files, and other automation is still not updated to use OpenSearch. For these scenarios, I left the OpenDistro text in place.
Resolves #638 

Consistent OpenSearch, OpenSearch Dashboards, and Amazon OpenSearch Service Usage

---

docker/ci/build-image.sh
release/docker/ci/build-image.sh

Added helper script `build-image.sh` to generate, tag, and push docker images to remote repository.
closed #634

Added docker helper script for publishing to container registries

---

build.gradle

Adds support for publishing to maven local with checksum files by running `./gradlew publish`
closes #421

Add maven local to publish repos

---

THIRD-PARTY
build.gradle

Fixes two CVEs which are in the currently used version of Netty.
See https://netty.io/news/2021/09/09/4-1-68-Final.html
N/A

Use Netty 4.1.68 which fixes CVE-2021-37136 and CVE-2021-37137

---

examples/config/example-pipelines.yaml
examples/dev/k8s/data-prepper.yaml
examples/dev/trace-analytics-sample-app/resources/pipelines.yaml
examples/trace_analytics.yml
examples/trace_analytics_no_ssl.yml

DP v1.2 is scheduled for release in a week. However a previous change migrated all example pipelines
to use processors. Reverting the change to keep our existing examples working as they are all dependent on
the latest published version of DP. This commit can be reverted once DP v1.2 is released.
- caused by #655 
- related to #311 

reverting pipeline yamls use of processor to prepper.

---

docs/configuration.md

Preppers were renamed to processor starting in version 1.3.0. I have updated the documentation to correctly note this.

Corrected the starting version for the Processor renaming to 1.3.0

---

data-prepper-plugins/grok-prepper/src/main/java/com/amazon/dataprepper/plugins/prepper/grok/GrokPrepper.java

Each `GrokPrepper` creates a single-thread executor for running code with a timeout (`Executors.newSingleThreadExecutor()`). Multiple `grok` preppers in a pipeline will each get their own instance. However, a single `grok` prepper with multiple worker threads will have each thread share this. This can cause contention when using the `time_out` property.
The PR attempts to remove that contention. It adds the `@SingleThread` annotation to `GrokPrepper`. This instructs Data Prepper Core to create one `GrokPrepper` instance per worker thread. Now, there will be a spare thread per worker.
I believe there is a better long-term solution available since multiple grok preppers could share a single `Executor` per worker thread. However, this is a change to Data Prepper Core and somewhat involved. …

Create GrokPrepper instance for each worker thread via @SingleThread

---

examples/log-ingestion-ecs-firelens/README.md
examples/log-ingestion-ecs-firelens/example_log_pipeline.yaml
examples/log-ingestion-ecs-firelens/task-definition.json

This PR adds a nginx example to demo the integration of data-prepper service with [ECS FireLens](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_firelens.html).
#705 

Example: ECS FireLens integration

---

data-prepper-api/src/main/java/com/amazon/dataprepper/model/event/JacksonEvent.java
data-prepper-plugins/common/src/main/java/com/amazon/dataprepper/plugins/source/RandomStringSource.java
data-prepper-plugins/common/src/test/java/com/amazon/dataprepper/plugins/sink/StdOutSinkTests.java
data-prepper-plugins/common/src/test/java/com/amazon/dataprepper/plugins/source/RandomStringSourceTests.java

* The checkKey function of JacksonEvent no longer compiles the regex pattern containing valid key characters. This compilation is now done one time at first instantiation of JacksonEvent.
* Removed String.format from checkKey. This String.format call was actually accounting for .2% of the entire Data Prepper execution (which is more than the grok matching itself), as it is called every time no matter what. We could consider another way to let the user know which key is invalid, but I think we want to put performance first here
* Test for RandomStringSource failed after the Event change, because the test was timing out before it could add a string to the buffer (because it makes an Event, and since it was the first …

Refactored event checkKey to use pre-compiled regex pattern. refactored RandomStringSource

---

THIRD-PARTY
build.gradle
data-prepper-plugins/opensearch/build.gradle

Upgrades log4j from vulnerable version to protected version

Upgrade log4j to 2.15.0

---

release/docker/Dockerfile

[backport 1.1] Add yum update to data prepper to consume all pkg updates
#716

[backport 1.1] Add yum update to data prepper to consume all pkg updates

---

release/docker/Dockerfile

[backport 1.2] Add yum update to data prepper to consume all pkg updates
#716

[backport 1.2] Add yum update to data prepper to consume all pkg updates

---

build.gradle

Additional Gradle constraint to ensure log4j-core 2.15.0. This fixes CVE-2021-44228.

Added a Gradle constraint to require that log4j-core version 2.15.0.

---

data-prepper-api/build.gradle
data-prepper-api/src/main/java/com/amazon/dataprepper/model/event/JacksonEvent.java
data-prepper-api/src/test/java/com/amazon/dataprepper/model/event/JacksonEventTest.java
data-prepper-plugins/common/src/test/java/com/amazon/dataprepper/plugins/sink/StdOutSinkTests.java
data-prepper-plugins/common/src/test/java/com/amazon/dataprepper/plugins/source/RandomStringSourceTests.java

Cherry picked commits for custom key validation in Event and StringUtils.isNumeric

Performance improvements for custom key validation in Event, and replacement with StringUtils.isNumeric

---

build.gradle
data-prepper-core/build.gradle
data-prepper-plugins/opensearch/build.gradle
data-prepper-plugins/otel-trace-group-prepper/build.gradle

Updates to log4j-core 2.15.0. This includes a Gradle constraint to use this version.
Note: This PR has no updates to the `THIRD-PARTY` file.
N/A

Updated to log4j-core 2.15.0

---

data-prepper-core/build.gradle
data-prepper-plugins/opensearch/build.gradle

Log4j 2.16.0 disables JNDI lookups by default. This will prevent security issues similar to CVE-2021-44228.
N/A

Updated to log4j-core 2.16.0

---

build.gradle
data-prepper-core/build.gradle
data-prepper-plugins/opensearch/build.gradle
data-prepper-plugins/otel-trace-group-prepper/build.gradle

Backport of Log4j 2.16.0 update and required version of 2.15.0 into Data Prepper 1.2.0.
Cherry picks `8b7eddd4` and `b689b0f5`.
N/A

Log4j 2.16.0 backport to Data Prepper 1.2.0

---

release/release-notes/data-prepper.release-notes-1.1.1.md

Adding release notes for Data Prepper 1.1.1. Cherry picks `204d0f91` from the `v1.1.x` branch.
N/A

Added release notes for Data Prepper 1.1.1 (#724)

---

data-prepper-plugins/otel-trace-source/src/main/java/com/amazon/dataprepper/plugins/source/oteltrace/OTelTraceSource.java
data-prepper-plugins/otel-trace-source/src/test/java/com/amazon/dataprepper/plugins/source/oteltrace/OTelTraceSourceTest.java

Despite the Armeria server is configured with blockingExecutor, the grpc service has never used it in otel-trace-source. This is a mis that could impair trace ingestion performance as blocking tasks are always executed on the single eventLoop thread(https://armeria.dev/docs/server-grpc/#blocking-service-implementation). This PR fixes the issue.
Resolves #316 

FIX: useBlockingExecutor in otel-trace-source

---

release/archives/build.gradle

Added the version to the key prefix for S3 archives to bring some organization to the S3 bucket.
Below is a screenshot showing the ultimate result in a test S3 bucket:
N/A

Prepend the version to the S3 key prefix for archives

---

examples/log-ingestion/log_ingestion_demo_guide.md

No longer gives instructions to build the docker image locally since the 1.2 release is out.
closes #690 

Update log ingestion demo guide with newly released Docker image

---

data-prepper-plugins/common/src/main/java/com/amazon/dataprepper/plugins/prepper/StringPrepper.java
data-prepper-plugins/common/src/test/java/com/amazon/dataprepper/plugins/prepper/StringPrepperTests.java

This PR migrates StringPrepper to use Event model.
Resolves #608 

MAINT: StringPrepper use Event model

---

data-prepper-plugins/common/src/main/java/com/amazon/dataprepper/plugins/sink/FileSink.java
data-prepper-plugins/common/src/test/java/com/amazon/dataprepper/plugins/sink/FileSinkTests.java

This PR modifies FileSink to support Event model while maintaining backward compatibility until we fully migrated all plugins to Event model.
Resolves #606 

MAINT: file sink to support Event model

---

build.gradle
data-prepper-core/build.gradle
data-prepper-plugins/opensearch/build.gradle

Updates log4j to 2.17.0
Resolves #759 

Updated to log4j 2.17.0 which fixes CVE-2021-45105. Resolves #759

---

build.gradle
data-prepper-core/build.gradle
data-prepper-plugins/opensearch/build.gradle

Updates log4j to 2.17.0
Resolves #759 

Upgrade to log4j 1.17, fixes CVE-2021-45105

---

data-prepper-logstash-configuration/src/main/java/org/opensearch/dataprepper/logstash/parser/ModelConvertingLogstashVisitor.java
data-prepper-logstash-configuration/src/test/java/org/opensearch/dataprepper/logstash/parser/ModelConvertingLogstashVisitorTest.java
data-prepper-logstash-configuration/src/test/java/org/opensearch/dataprepper/logstash/parser/TestDataProvider.java
data-prepper-logstash-configuration/src/test/resources/org/opensearch/dataprepper/logstash/log-ingest-to-opensearch.conf
data-prepper-logstash-configuration/src/test/resources/org/opensearch/dataprepper/logstash/log-ingest-to-opensearch.expected.yaml

Fix boolean conversion and integer conversion bug for Logstash configuration converter attributes
Cherry picked commit from main

Fix boolean conversion and integer conversion bug for Logstash configuration converter attributes (#766)

---

data-prepper-api/src/main/java/com/amazon/dataprepper/model/processor/AbstractProcessor.java
data-prepper-api/src/test/java/com/amazon/dataprepper/model/processor/AbstractProcessorTest.java

* This constructor takes a PluginMetrics, and makes AbstractProcessor compatible with `@DataPrepperPluginConstructor` processors that do not use a PluginSetting. It allows for the PluginMetrics passed to the `@DataPrepperPluginConstructor` to be used to create a Processor.

Add AbstractProcessor constructor that takes a PluginMetrics

---

data-prepper-api/src/main/java/com/amazon/dataprepper/model/trace/JacksonSpan.java
data-prepper-api/src/test/java/com/amazon/dataprepper/model/trace/JacksonSpanTest.java

This PR removes traceGroup and traceGroupFields from required in JacksonSpan as they will not always be populated at first place when ExportTraceServiceRequest is converted into our Span model.
Contributes to #546 

MAINT: remove traceGroup keys from required in JacksonSpan

---

data-prepper-logstash-configuration/src/main/java/org/opensearch/dataprepper/logstash/mapping/AbstractLogstashPluginAttributesMapper.java
data-prepper-logstash-configuration/src/main/resources/org/opensearch/dataprepper/logstash/mapping/opensearch.mapping.yaml
data-prepper-logstash-configuration/src/test/java/org/opensearch/dataprepper/logstash/mapping/DefaultLogstashPluginAttributesMapperTest.java
data-prepper-logstash-configuration/src/test/resources/org/opensearch/dataprepper/logstash/log-ingest-to-logstash-opensearch-insecure.expected.yaml
data-prepper-logstash-configuration/src/test/resources/org/opensearch/dataprepper/logstash/log-ingest-to-logstash-opensearch.conf
data-prepper-logstash-configuration/src/test/resources/org/opensearch/dataprepper/logstash/log-ingest-to-logstash-opensearch.expected.yaml
data-prepper-logstash-configuration/src/test/resources/org/opensearch/dataprepper/logstash/log-ingest-to-logtstash-opensearch-insecure.conf

- Added Logstash OpenSearch output plugin mapping to converter
- Added support for negation of boolean Logstash attribute values.
Resolves #710 
Resolves #746 

Added Logstash OpenSearch output plugin mapping to converter

---

data-prepper-plugins/service-map-stateful/src/main/java/com/amazon/dataprepper/plugins/prepper/ServiceMapRelationship.java
data-prepper-plugins/service-map-stateful/src/test/java/com/amazon/dataprepper/plugins/prepper/ServiceMapRelationshipTest.java

Java 8 provides a `Base64` class. I updated `ServiceMapRelationship` to use it.
Additionally, I created a unit test to get the value for static values to ensure it is consistent with the old Base64.
N/A

Use Java8's Base64 in ServiceMapRelationship.

---

data-prepper-api/src/main/java/com/amazon/dataprepper/model/plugin/InvalidPluginConfigurationException.java
data-prepper-api/src/test/java/com/amazon/dataprepper/model/plugin/InvalidPluginConfigurationExceptionTest.java
data-prepper-core/build.gradle
data-prepper-core/src/main/java/com/amazon/dataprepper/plugin/PluginConfigurationConverter.java
data-prepper-core/src/test/java/com/amazon/dataprepper/plugin/DefaultPluginFactoryIT.java
data-prepper-core/src/test/java/com/amazon/dataprepper/plugin/PluginConfigurationConverterTest.java
data-prepper-core/src/test/java/com/amazon/dataprepper/plugin/TestPluggableInterface.java
data-prepper-core/src/test/java/com/amazon/dataprepper/plugin/TestPluginConfiguration.java
data-prepper-core/src/test/java/com/amazon/dataprepper/plugins/TestPlugin.java

This change validates plugin configuration objects using JSR-303 bean validation. It only supports the `jakarta.validation` package which supersedes the `javax.validation` package.
The implementation uses Hibernate Validator which is the primary reference implementation.
Additionally, I added an integration test for the plugin framework to test the components together, including one which validates actual plugin configurations.
Resolves #709

Validate plugin configuration objects using JSR-303 validation

---

data-prepper-api/src/main/java/com/amazon/dataprepper/model/configuration/PipelineDescription.java
data-prepper-api/src/main/java/com/amazon/dataprepper/model/configuration/PluginSetting.java
data-prepper-core/src/main/java/com/amazon/dataprepper/plugin/DefaultPluginFactory.java
data-prepper-core/src/main/java/com/amazon/dataprepper/plugin/PluginArgumentsContext.java
data-prepper-core/src/test/java/com/amazon/dataprepper/plugin/PluginArgumentsContextTest.java

* Adds `PipelineDescription` interface to allow passing of pipeline details to the plugins that belong to that pipeline
* Only `PluginSetting` implements this interface. A DefaultPipelineDescription could be created in the future to isolate the PipelineDescription information (i.e. with the configuration settings in `PluginSetting`).
* `PipelineDescription` is now an optional parameter to use with the `@DataPrepperPluginConstructor`
closes #771 …

Add PipelineDescription object to be passed to @DataPrepperPluginConstructor

---

build.gradle
data-prepper-core/build.gradle
data-prepper-plugins/http-source/src/main/java/com/amazon/dataprepper/plugins/source/loghttp/HTTPSource.java
data-prepper-plugins/http-source/src/main/java/com/amazon/dataprepper/plugins/source/loghttp/HTTPSourceConfig.java
data-prepper-plugins/http-source/src/test/java/com/amazon/dataprepper/plugins/source/loghttp/HTTPSourceConfigTest.java

The primary change is updating `HTTPSourceConfig` to use JSR-380 validation instead of using a validate method. Along with this, I added the `jakarta.validation` package to all projects other than `data-prepper-api`.
A second change is that I removed the `javax.validation` dependency from data-prepper-core.
N/A

Updated HTTPSourceConfig to use JSR-380 validation

---

.github/workflows/gradle.yml
data-prepper-plugins/http-source/src/main/java/com/amazon/dataprepper/plugins/source/loghttp/codec/JsonCodec.java

Releasing to Maven requires generating Javadocs.
This PR fixes the last Javadoc errors and adds the javadoc step the GitHub workflow to ensure that Javadocs remain stable.
N/A

Fix Javadoc errors and add a Javadoc step to CI

---

data-prepper-api/src/main/java/com/amazon/dataprepper/model/event/Event.java
data-prepper-api/src/main/java/com/amazon/dataprepper/model/event/JacksonEvent.java
data-prepper-api/src/test/java/com/amazon/dataprepper/model/event/JacksonEventTest.java

* Adds a function `getAsMap()` to the Event interface
* Implements this function in JacksonEvent and returns the Event as a `Map<Object, Object>` using  ObjectMapper

Add Event.getAsMap() function to return the Event as a Map<Object, Object>

---

data-prepper-logstash-configuration/src/main/resources/org/opensearch/dataprepper/logstash/mapping/drop.mapping.yaml
data-prepper-logstash-configuration/src/test/resources/org/opensearch/dataprepper/logstash/log-ingest-to-opensearch.conf
data-prepper-logstash-configuration/src/test/resources/org/opensearch/dataprepper/logstash/log-ingest-to-opensearch.expected.yaml

Creates a mapping between Logstash's Drop filter and Data Prepper's DropEventProcessor

Add Drop Mapping

---

build.gradle
data-prepper-plugins/opensearch/build.gradle
e2e-test/build.gradle
settings.gradle

Gradle attempts to resolve plugin dependencies against the Gradle Plugin portal repository by default. This change attempts to resolve against Maven Central first. Then it uses the Gradle Plugin portal.
In addition, it fixes an issue with the Gradle-License-Report plugin where the .module file is being used rather than the POM file.
Resolves #858 

Resolve plugins from Maven Central before Gradle Plugins portal

---

examples/log-ingestion/log_pipeline.yaml

Our examples should use `prepper`. They work with both 1.2 and 1.3. Now that 1.2 is out, most users will end up running against that version.
N/A

Bring the log-ingest example pipeline back to using prepper. 

---

MAINTAINERS.md

Updating maintainers list to reflect active group.
- none

updating maintainers list

---

MAINTAINERS.md

Adding treddeni-amazon to list of maintainers
none

adding treddeni-amazon to maintainers

---

.github/dependabot.yml

adding dependabot configs for all the new processors. None of the preppers (processors) release for 1.2 had dependabot configs. Ideally, I would like to simplify this config to capture our dependencies through a wildcard but that feature is not supported at this time: https://github.com/dependabot/dependabot-core/issues/2178
none

adding dependabot configs for all the new processors

---

data-prepper-core/src/main/java/com/amazon/dataprepper/plugin/DefaultPluginFactory.java
data-prepper-core/src/main/java/com/amazon/dataprepper/plugin/PluginApplicationContext.java
data-prepper-core/src/main/java/com/amazon/dataprepper/plugin/PluginConfigurationConverter.java
data-prepper-core/src/main/java/com/amazon/dataprepper/plugin/PluginCreator.java
data-prepper-core/src/main/java/com/amazon/dataprepper/plugin/PluginProviderLoader.java
data-prepper-core/src/test/java/com/amazon/dataprepper/parser/PipelineParserTests.java
data-prepper-core/src/test/java/com/amazon/dataprepper/plugin/DefaultPluginFactoryIT.java
data-prepper-core/src/test/java/com/amazon/dataprepper/plugin/PluginConfigurationConverterTest.java

This change adds dependency injection to the plugin framework's internal objects. In addition, the integration test for the plugins uses the application context for building the whole object.
I recommended starting by reviewing the `DefaultPluginFactory` changes. Most everything flows from that.
N/A

Updated the plugin framework to use dependency injection for internal class

---

data-prepper-logstash-configuration/src/main/resources/org/opensearch/dataprepper/logstash/mapping/kv.mapping.yaml
data-prepper-logstash-configuration/src/test/resources/org/opensearch/dataprepper/logstash/log-ingest-to-opensearch.conf
data-prepper-logstash-configuration/src/test/resources/org/opensearch/dataprepper/logstash/log-ingest-to-opensearch.expected.yaml
data-prepper-plugins/key-value-processor/README.md
data-prepper-plugins/key-value-processor/src/main/java/com/amazon/dataprepper/plugins/processor/keyvalue/KeyValueProcessor.java
data-prepper-plugins/key-value-processor/src/main/java/com/amazon/dataprepper/plugins/processor/keyvalue/KeyValueProcessorConfig.java
data-prepper-plugins/key-value-processor/src/test/java/com/amazon/dataprepper/plugins/processor/keyvalue/KeyValueProcessorTests.java

Adds logstash conversion support for KeyValueProcessor as well as a few new tests

Create mapping yaml for KeyValueProcessor. Add in a few more tests

---

data-prepper-plugins/aggregate-processor/src/main/java/com/amazon/dataprepper/plugins/processor/aggregate/AggregateAction.java
data-prepper-plugins/aggregate-processor/src/main/java/com/amazon/dataprepper/plugins/processor/aggregate/AggregateActionInput.java
data-prepper-plugins/aggregate-processor/src/main/java/com/amazon/dataprepper/plugins/processor/aggregate/AggregateGroup.java
data-prepper-plugins/aggregate-processor/src/main/java/com/amazon/dataprepper/plugins/processor/aggregate/AggregateProcessor.java
data-prepper-plugins/aggregate-processor/src/main/java/com/amazon/dataprepper/plugins/processor/aggregate/DefaultGroupState.java
data-prepper-plugins/aggregate-processor/src/main/java/com/amazon/dataprepper/plugins/processor/aggregate/GroupState.java
data-prepper-plugins/aggregate-processor/src/main/java/com/amazon/dataprepper/plugins/processor/aggregate/actions/CombineAggregateAction.java
data-prepper-plugins/aggregate-processor/src/main/java/com/amazon/dataprepper/plugins/processor/aggregate/actions/RemoveDuplicatesAggregateAction.java
data-prepper-plugins/aggregate-processor/src/test/java/com/amazon/dataprepper/plugins/processor/aggregate/AggregateActionTestUtils.java
data-prepper-plugins/aggregate-processor/src/test/java/com/amazon/dataprepper/plugins/processor/aggregate/AggregateProcessorTest.java
data-prepper-plugins/aggregate-processor/src/test/java/com/amazon/dataprepper/plugins/processor/aggregate/actions/CombineAggregateActionTest.java
data-prepper-plugins/aggregate-processor/src/test/java/com/amazon/dataprepper/plugins/processor/aggregate/actions/RemoveDuplicatesAggregateActionTest.java

* Creates an interface `AggregateActionInput`, which is passed to the `AggregateAction` functions `handleEvent` and `concludeGroup`. This will give the option to provide more than just a `GroupState` to `AggregateAction` creators if the need arises. `AggregateActionInput` is implemented by `AggregateGroup`. The implemented methods are public for use in AggregateActions. Methods of `AggregateGroup` that will not be exposed to AggregateActions will be made package private.
* Creates an interface `GroupState`, which is exposed by the `AggregateActionInput.getGroupState()` method. This interface extends `Map<Object, Object>`, so as to not lock in `AggregateActions` to a single `Map` type.
* Creates a class …

Refactored by creating AggregateActionInput and GroupState interfaces, and class DefaultGroupState

---

data-prepper-core/src/main/java/com/amazon/dataprepper/plugin/ClasspathPluginProvider.java
data-prepper-core/src/main/java/com/amazon/dataprepper/plugin/PluginPackagesSupplier.java
data-prepper-core/src/main/resources/META-INF/data-prepper.plugins.properties
data-prepper-core/src/test/java/com/amazon/dataprepper/plugin/PluginPackagesSupplierTest.java

This PR allows Data Prepper to support plugins in packages other than `com.amazon.dataprepper.plugins`.
Data Prepper reads all resources (files embedded in jars) of `META-INF/data-prepper.plugins.properties`. It then looks for a property `org.opensearch.dataprepper.plugin.packages` from each one. The value of this property is a comma-delimited list of packages.
Data Prepper will scan all of these packages for plugins.
Note that because of the uber-jar, Data Prepper can only have one file for all packages. However, plugin authors can create their own jar files with this file. As long as it is on the classpath, their custom plugin will be available.
It may be worthwhile to move some plugins in future PRs.
#379 
By submitting this pull request, I confirm that my contribution is made under …

Support loading plugins from multiple packages.

---

data-prepper-api/src/test/java/com/amazon/dataprepper/model/buffer/AbstractBufferTest.java
data-prepper-api/src/test/java/com/amazon/dataprepper/model/configuration/PipelinesDataFlowModelTest.java
data-prepper-api/src/test/java/com/amazon/dataprepper/model/configuration/PluginModelTests.java
data-prepper-api/src/test/java/com/amazon/dataprepper/model/event/DefaultEventMetadataTest.java
data-prepper-api/src/test/java/com/amazon/dataprepper/model/event/JacksonEventTest.java
data-prepper-core/src/test/java/com/amazon/dataprepper/parser/config/DataPrepperArgsTest.java
data-prepper-logstash-configuration/src/main/java/org/opensearch/dataprepper/logstash/LogstashConfigConverter.java
data-prepper-plugins/http-source/src/test/java/com/amazon/dataprepper/plugins/source/loghttp/HTTPSourceTest.java

There are a handful of unit tests that fail when running on Windows. This PR fixes some of them. The reasons for failing tests include:
1. Instant comparison is too strict and varies based on CPU
2. YAMLGenerator needs to enable `USE_PLATFORM_LINE_BREAKS`  to not always default to Unix `\n` (Windows standard is `\r\n`
3. Test paths are created with `/`, while windows uses `\`

[BUG] Fixed some failing unit tests on Windows

---

CONTRIBUTING.md

Use `--signoff` in the CONTRIBUTING.md file instead of `- - signoff`.
None

Minor correction to the --signoff parameter in the CONTRIBUTING.md file.

---

data-prepper-plugins/aggregate-processor/src/main/java/com/amazon/dataprepper/plugins/processor/aggregate/AggregateActionSynchronizer.java
data-prepper-plugins/aggregate-processor/src/main/java/com/amazon/dataprepper/plugins/processor/aggregate/AggregateGroup.java
data-prepper-plugins/aggregate-processor/src/main/java/com/amazon/dataprepper/plugins/processor/aggregate/AggregateGroupManager.java
data-prepper-plugins/aggregate-processor/src/main/java/com/amazon/dataprepper/plugins/processor/aggregate/AggregateIdentificationKeysHasher.java
data-prepper-plugins/aggregate-processor/src/main/java/com/amazon/dataprepper/plugins/processor/aggregate/AggregateProcessor.java
data-prepper-plugins/aggregate-processor/src/test/java/com/amazon/dataprepper/plugins/processor/aggregate/AggregateActionSynchronizerTest.java
data-prepper-plugins/aggregate-processor/src/test/java/com/amazon/dataprepper/plugins/processor/aggregate/AggregateGroupManagerTest.java
data-prepper-plugins/aggregate-processor/src/test/java/com/amazon/dataprepper/plugins/processor/aggregate/AggregateGroupTest.java
data-prepper-plugins/aggregate-processor/src/test/java/com/amazon/dataprepper/plugins/processor/aggregate/AggregateIdentificationKeysHasherTest.java
data-prepper-plugins/aggregate-processor/src/test/java/com/amazon/dataprepper/plugins/processor/aggregate/AggregateProcessorConfigTest.java
data-prepper-plugins/aggregate-processor/src/test/java/com/amazon/dataprepper/plugins/processor/aggregate/AggregateProcessorTest.java

* Adds logic of concluding a group to the `AggregateProcessor`. It will get the groups to conclude from the `AggregateGroupManager` and call `AggregateActionSynchronizer.concludeGroup()` on each of these.
* The `AggregateActionSynchronizer` class keeps threads from modifying the same `AggregateGroup` at the same time, and wraps the `AggregateAction` function calls for the `AggregateProcessor`. 
Closes #938 

Added concludeGroup logic to AggregateProcessor, added AggregateActionSynchronizer class to synchronize groupConcluding and eventHandling

---

data-prepper-plugins/aggregate-processor/src/main/java/com/amazon/dataprepper/plugins/processor/aggregate/actions/PutAllAggregateAction.java
data-prepper-plugins/aggregate-processor/src/test/java/com/amazon/dataprepper/plugins/processor/aggregate/actions/PutAllAggregateActionTest.java

* Change the name of the `CombineAggregateAction` to `PutAllAggregateAction`. This name more accurately reflects what the AggregateAction is doing, and will make it easier to distinguish AggregateActions as new ones are created. For example, another action named `append` could be created in the future that deals with key conflicts by appending a value rather than just putting or overwriting like the `put_all` action does. See #855 for more context. …

Change CombineAggregateAction name to PutAllAggregateAction

---

build.gradle
data-prepper-plugins/opensearch/build.gradle
performance-test/build.gradle

Update Jackson to 2.13.1 in the BOM file.
Force Jackson 2.13.1 in the opensearch build
Removed unnecessary version specification in performance-test project
Resolves #991

Updated Jackson to 2.13.1

---

build.gradle
data-prepper-plugins/otel-trace-raw-prepper/build.gradle
data-prepper-plugins/otel-trace-source/build.gradle
e2e-test/trace/build.gradle

Require that `gson` version 2.8.9 or higher be used.
The `gson` dependency is a transitive dependency of `protobuf-java-util`, so I also updated all occurrences to the latest version of 3.19.4.
Resolves #989

Updated Gson to 2.8.9 and protobuf-java-util to 3.19.4

---

data-prepper-core/src/main/java/com/amazon/dataprepper/parser/config/MetricsConfig.java

* The Data Prepper Server was unable to find the PrometheusMeterRegistry Bean, which resulted in the metrics core api endpoints being unavailable.

Fixed issue where Spring was unable to find the PrometheusMeterRegistry Bean

---

data-prepper-plugins/aggregate-processor/README.md
data-prepper-plugins/aggregate-processor/build.gradle
data-prepper-plugins/aggregate-processor/src/main/java/com/amazon/dataprepper/plugins/processor/aggregate/AggregateActionSynchronizer.java
data-prepper-plugins/aggregate-processor/src/main/java/com/amazon/dataprepper/plugins/processor/aggregate/AggregateGroupManager.java
data-prepper-plugins/aggregate-processor/src/main/java/com/amazon/dataprepper/plugins/processor/aggregate/AggregateProcessor.java
data-prepper-plugins/aggregate-processor/src/main/java/com/amazon/dataprepper/plugins/processor/aggregate/AggregateProcessorConfig.java
data-prepper-plugins/aggregate-processor/src/test/java/com/amazon/dataprepper/plugins/processor/aggregate/AggregateActionSynchronizerTest.java
data-prepper-plugins/aggregate-processor/src/test/java/com/amazon/dataprepper/plugins/processor/aggregate/AggregateProcessorConfigTest.java
data-prepper-plugins/aggregate-processor/src/test/java/com/amazon/dataprepper/plugins/processor/aggregate/AggregateProcessorTest.java

Introduces the following metrics to the Aggregate Processor:
**Counter**
* `actionHandleEventsOut`: The number of Events that have been returned from the `handleEvent` call to the [action]() configured
* `actionHandleEventsDropped`: The number of Events that have not been returned from the `handleEvent` call to the [action]() configured.
* `actionHandleEventsProcessingErrors`: The number of calls made to `handleEvent` for the [action]() configured that resulted in an error.
* `actionConcludeGroupEventsOut`: The number of Events that have been returned from the `concludeGroup` call to the [action]() configured.
* `actionConcludeGroupEventsDropped`: The number of Events that have not been returned from the `condludeGroup` call to the [action]() …

Added metrics for the Aggregate Processor

---

data-prepper-plugins/aggregate-processor/README.md
data-prepper-plugins/aggregate-processor/src/main/java/com/amazon/dataprepper/plugins/processor/aggregate/AggregateGroupManager.java
data-prepper-plugins/aggregate-processor/src/main/java/com/amazon/dataprepper/plugins/processor/aggregate/AggregateProcessor.java
data-prepper-plugins/aggregate-processor/src/main/java/com/amazon/dataprepper/plugins/processor/aggregate/AggregateProcessorConfig.java
data-prepper-plugins/aggregate-processor/src/test/java/com/amazon/dataprepper/plugins/processor/aggregate/AggregateGroupManagerTest.java
data-prepper-plugins/aggregate-processor/src/test/java/com/amazon/dataprepper/plugins/processor/aggregate/AggregateProcessorConfigTest.java

* Add README documentation for `AggregateProcessor`
* Rename `window_duration` configuration option to `group_duration`, as the `AggregateProcessor` does not have windows, but groups.

Add documentation for the AggregateProcessor, change window_duration to group_duration

---

.github/workflows/release.yml

This PR adds a new GitHub Action for building all artifacts. This PR currently performs the release builds and keeps all artifacts locally. It is a starting point for further work.
This action requires a user manually start it. It is not triggered automatically.
This is only part of #977.

Initial GitHub Action to build all artifacts

---

data-prepper-api/src/main/java/com/amazon/dataprepper/model/trace/JacksonSpan.java

String.format turns out to suck up most of the time spent on JacksonSpan.Builder::validateParameters which also takes a non-trivial portion in OTelTraceRawPrepper::processSpan:
* Before:
* After:
Contributes to #939 

ENH: remove string format in JacksonSpan.Builder::validateParameters

---

data-prepper-plugins/otel-trace-raw-prepper/src/main/java/com/amazon/dataprepper/plugins/prepper/oteltrace/OTelTraceRawPrepper.java

getTraceId is an expensive call. This change could yield minor enhancement on performance
Contributes to #939 

MAINT: cache getTraceId result in OTelTraceRawPrepper

---

data-prepper-plugins/aggregate-processor/src/test/java/com/amazon/dataprepper/plugins/processor/aggregate/AggregateProcessorIT.java

* Two integration tests were created for the AggregateProcessor:
The first test calls `doExecute` with a batch of Events 100 times (1 for each thread) and verifies that the aggregated result of recordsOut only contains the unique Events (as the `RemoveDuplicatesAggregateAction` is being used for testing. The `groupDuration` for this test is set to the default of `180`, which guarantees that no groups will be concluded.
The second test starts by calling `doExecute` with the batch of Events a single time (in order to create all the `AggregateGroups` beforehand). After this, a `Thread.sleep(2000)` is called to let all the groups qualify for conclusion. The `groupDuration` is set to 2 seconds, which is short enough to not have the tests take …

Add simple integration tests for AggregateProcessor

---

data-prepper-plugins/date-processor/build.gradle
data-prepper-plugins/date-processor/src/main/java/com/amazon/dataprepper/plugins/processor/date/DateProcessor.java
data-prepper-plugins/date-processor/src/main/java/com/amazon/dataprepper/plugins/processor/date/DateProcessorConfig.java
data-prepper-plugins/date-processor/src/test/java/com/amazon/dataprepper/plugins/processor/date/DateProcessorConfigTest.java
data-prepper-plugins/date-processor/src/test/java/com/amazon/dataprepper/plugins/processor/date/DateProcessorTests.java

- Added `dateProcessingMatchSuccessCounter` and `dateProcessingMatchFailureCounter` metrics
- Added a new configuration option `destination_timezone`which let's user define the timezone of output that'll be stored in event data.
- Updated the default source timezone to be system default instead of `UTC`.

Added metrics and destination timezone configuration option.

---

data-prepper-expression/src/main/antlr/DataPrepperExpression.g4

Limited Regex operator argument types
Allow not operator to apply to any expression
Update grammar to match syntax defined in #1005 

updated grammar

---

data-prepper-api/src/main/java/com/amazon/dataprepper/model/event/JacksonEvent.java
data-prepper-plugins/common/src/main/java/com/amazon/dataprepper/plugins/source/RandomStringSource.java
data-prepper-plugins/common/src/main/java/com/amazon/dataprepper/plugins/source/StdInSource.java
data-prepper-plugins/common/src/test/java/com/amazon/dataprepper/plugins/source/StdInSourceTests.java

* Changes access modifier of `fromMessage` API to public to leverage in `Sources`
* Updates usage in `RandomStringSource` and `StdInSource`
Resolves #646 

Update fromMessage API in data-prepper-common Sources

---

data-prepper-api/src/main/java/com/amazon/dataprepper/model/trace/JacksonSpan.java
data-prepper-api/src/test/java/com/amazon/dataprepper/model/event/JacksonEventTest.java

* As synced with @cmanning09 offline, this PR refactors checkAndSetDefaultValues from JacksonSpan into JacksonSpan.Builder in order to avoid get calls with JsonPointers which is time consuming in the JacksonSpan constructor:
* Also added a test case on JacksonEvent as the coverage is a little shy.

ENH: refactor checkAndSetDefaultValues into JacksonSpan.Builder

---

.github/workflows/release.yml

This commit adds the following changes to the nascent GitHub Actions release build:
* Adds a new step to publish to Maven (local only, as with the Archives and Docker steps)
* Improved the step names
* Build all archive files. Now that macOS is no longer part of the Gradle build, this only builds Linux as it should.
Part of #977

Publish to Maven as part of the release build

---

data-prepper-logstash-configuration/src/main/java/org/opensearch/dataprepper/logstash/mapping/OpenSearchPluginAttributesMapper.java
data-prepper-logstash-configuration/src/main/resources/org/opensearch/dataprepper/logstash/mapping/amazon_es.mapping.yaml
data-prepper-logstash-configuration/src/main/resources/org/opensearch/dataprepper/logstash/mapping/elasticsearch.mapping.yaml
data-prepper-logstash-configuration/src/main/resources/org/opensearch/dataprepper/logstash/mapping/opensearch.mapping.yaml
data-prepper-logstash-configuration/src/test/java/org/opensearch/dataprepper/logstash/mapping/OpenSearchPluginAttributesMapperTest.java
data-prepper-logstash-configuration/src/test/resources/org/opensearch/dataprepper/logstash/log-ingest-to-logstash-opensearch.expected.yaml

* Adds a custom AttributeMapper to converts `year`, `year-of-era`, `week-year` patterns in index from [Joda](https://www.joda.org/joda-time/key_format.html) to [Java-time](https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html):
* Removes `+` from DateTime patterns in Logstash config
* Adds test cases
Resolves #854 

OpenSearch Index DateTime Pattern conversion

---

data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/util/ParseRuleContextExceptionMatcher.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/util/ParseRuleContextExceptionMatcherTest.java

Added matcher for parse rule exceptions
- [x[ New functionality has been documented.

Added ParseRuleContextExceptionMatcherTest

---

data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/util/ErrorListener.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/util/ErrorListenerTest.java

Added error lsitener, an implementation of ANTLRErrorListener and DataPrepperExpressionListener that tracks if any error events have been published
n/a

Added ErrorListener

---

data-prepper-logstash-configuration/src/main/resources/org/opensearch/dataprepper/logstash/mapping/kv.mapping.yaml
data-prepper-logstash-configuration/src/test/resources/org/opensearch/dataprepper/logstash/log-ingest-to-opensearch.conf
data-prepper-logstash-configuration/src/test/resources/org/opensearch/dataprepper/logstash/log-ingest-to-opensearch.expected.yaml

Added `source` to mapping file

Fix: added missing configuration in kv yaml mapping

---

data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/util/ContextMatcher.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/util/RuleClassOrderedList.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/util/RuleClassOrderedListTest.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/util/SimpleExpressionMatcher.java

SimpleExpressionMatcher as an abstract base matcher for creating grammar matcher classes

Added SimpleExpressionMatcher

---

data-prepper-core/src/main/java/com/amazon/dataprepper/plugin/PluginConfigurationConverter.java
data-prepper-core/src/main/java/com/amazon/dataprepper/plugin/PluginDurationDeserializer.java
data-prepper-core/src/test/java/com/amazon/dataprepper/plugin/PluginDurationDeserializerTest.java
data-prepper-plugins/aggregate-processor/README.md
data-prepper-plugins/aggregate-processor/src/main/java/com/amazon/dataprepper/plugins/processor/aggregate/AggregateGroupManager.java
data-prepper-plugins/aggregate-processor/src/main/java/com/amazon/dataprepper/plugins/processor/aggregate/AggregateProcessorConfig.java
data-prepper-plugins/aggregate-processor/src/test/java/com/amazon/dataprepper/plugins/processor/aggregate/AggregateGroupManagerTest.java
data-prepper-plugins/aggregate-processor/src/test/java/com/amazon/dataprepper/plugins/processor/aggregate/AggregateProcessorConfigTest.java
data-prepper-plugins/aggregate-processor/src/test/java/com/amazon/dataprepper/plugins/processor/aggregate/AggregateProcessorIT.java

* A Duration deserializer has been added to the `PluginConfigurationConverter` `ObjectMapper`. 
* This deserializer supports strings in ISO_8601 notation, as well as a simple notation for durations with seconds or milliseconds
* The `group_duration` option in the `AggregateProcessor` now uses this deserializer.
closes #1079 

Added standard duration string deserializer for Data Prepper plugin, refactored the AggregateProcessor group_duration to use this deserializer

---

data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/util/LiteralMatcher.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/util/LiteralMatcherTest.java

Added LiteralMatcher

---

data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/ParseTreeTest.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/ParserTest.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/util/ContextMatcher.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/util/GrammarTest.java

Adds Data Prepper Expression parsers tests that assert full expression parsing
Missing test coverage

Added ParseTreeTest

---

data-prepper-plugins/mapdb-prepper-state/build.gradle
data-prepper-plugins/otel-trace-raw-prepper/build.gradle

Updated Gradle projects to use the string notation for dependencies. This helps with quick find all commands and is consistent across projects.
N/A

Updated Gradle projects to use the dependency string notation

---

release/archives/build.gradle

Changes the release archive S3 path to include the build number.
This yields paths like the following:
```
/
{version}/
{buildNumber}/
archive/
opensearch-data-prepper-1.3.0-linux-x64.tar.gz
opensearch-data-prepper-jdk-1.3.0-linux-x64.tar.gz
```
Part of #977

Upload release archive files to a unique key path per build

---

release/staging-resources-cdk/README.md
release/staging-resources-cdk/bin/staging-resources-cdk.ts
release/staging-resources-cdk/lib/GitHubActionsReleaseAccessStack.ts
release/staging-resources-cdk/lib/StagingResourcesStack.ts
release/staging-resources-cdk/test/GitHubActionsReleaseAccessStack.test.ts
release/staging-resources-cdk/test/StagingResourcesStack.test.ts

Updated the staging resources CDK with a CloudFront distribution and the IAM role for GitHub Actions to assume to perform the release process. This includes the necessary S3 bucket policy for the CloudFront origin access identity. Updated the README.md with instructions on build and deployment.
Part of #977

Staging resources CDK: Include CloudFront distribution and release IAM role

---

data-prepper-plugins/otel-proto-common/src/main/java/com/amazon/dataprepper/plugins/otel/codec/OTelProtoCodec.java

Minor improvement on repeated span.getAttributes call that introduces jsonNode overhead.
Contributes to #546 

MAINT: reduce getAttributes calls

---

build.gradle

Updated Netty to 4.1.74, the current latest on the 4.1 series. It includes a fix for CVE-2021-43797.
Resolves #995

Netty 4.1.74, which fixes CVE-2021-43797.

---

data-prepper-core/build.gradle
data-prepper-core/src/main/java/com/amazon/dataprepper/plugin/PluginApplicationContext.java

Using Hibernate's ParameterMessageInterpolator allows us to remove the Jakara EL library and its licenses.
N/A

Use Hibernate's ParameterMessageInterpolator

---

THIRD-PARTY

This PR includes another update to the `THIRD-PARTY` file. Now that #1127 is merged in, the Jakarta EL project is no longer a third-party dependency.
N/A

Updated the THIRD-PARTY file with the removal of Jakarta EL.

---

.github/workflows/opensearch-sink-os-integration-tests.yml

Adds a verification workflow against OpenSearch 1.2.4. These run in parallel, so the GitHub Actions should not be any slower.
N/A

Verify against OpenSearch 1.2.4 during the CI integration tests.

---

data-prepper-logstash-configuration/src/main/java/org/opensearch/dataprepper/logstash/mapping/AbstractLogstashPluginAttributesMapper.java
data-prepper-logstash-configuration/src/main/java/org/opensearch/dataprepper/logstash/mapping/LogstashAttributesMappings.java
data-prepper-logstash-configuration/src/main/java/org/opensearch/dataprepper/logstash/mapping/LogstashMappingModel.java
data-prepper-logstash-configuration/src/main/java/org/opensearch/dataprepper/logstash/mapping/OpenSearchPluginAttributesMapper.java
data-prepper-logstash-configuration/src/main/resources/org/opensearch/dataprepper/logstash/mapping/amazon_es.mapping.yaml
data-prepper-logstash-configuration/src/main/resources/org/opensearch/dataprepper/logstash/mapping/elasticsearch.mapping.yaml
data-prepper-logstash-configuration/src/main/resources/org/opensearch/dataprepper/logstash/mapping/opensearch.mapping.yaml
data-prepper-logstash-configuration/src/test/java/org/opensearch/dataprepper/logstash/mapping/AbstractLogstashPluginAttributesMapperTest.java
data-prepper-logstash-configuration/src/test/java/org/opensearch/dataprepper/logstash/mapping/OpenSearchPluginAttributesMapperTest.java

Adds `defaultSettings` property to the Logstash Mapping YAML files setting the default Data Prepper attribute values.
Resolves #1080 

Support default values for attributes

---

data-prepper-expression/src/main/antlr/DataPrepperExpression.g4
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/ParseTreeExpressionTest.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/util/GrammarTest.java

Update the types the not operator will accept.
```
unaryNotOperatorExpression
: unaryOperator parenthesesExpression
| unaryOperator primary
;
```
Previously not operator accepted any conditional statement. The order of operations parsed did not match the order defined in #1005 

Fix not bug

---

data-prepper-plugins/mutate-string-processors/src/main/java/com/amazon/dataprepper/plugins/processor/mutatestring/LowercaseStringProcessor.java
data-prepper-plugins/mutate-string-processors/src/main/java/com/amazon/dataprepper/plugins/processor/mutatestring/TrimStringProcessor.java
data-prepper-plugins/mutate-string-processors/src/main/java/com/amazon/dataprepper/plugins/processor/mutatestring/UppercaseStringProcessor.java
data-prepper-plugins/mutate-string-processors/src/main/java/com/amazon/dataprepper/plugins/processor/mutatestring/WithKeysConfig.java
data-prepper-plugins/mutate-string-processors/src/test/java/com/amazon/dataprepper/plugins/processor/mutatestring/LowercaseStringProcessorTests.java
data-prepper-plugins/mutate-string-processors/src/test/java/com/amazon/dataprepper/plugins/processor/mutatestring/TrimStringProcessorTests.java
data-prepper-plugins/mutate-string-processors/src/test/java/com/amazon/dataprepper/plugins/processor/mutatestring/UppercaseStringProcessorTests.java

I recently took out WithKeysConfig. That was a mistake. This PR reintroduces it.

Reintroduce `WithKeysConfig`

---

.github/workflows/backport.yml
.github/workflows/delete_backport_branch.yml

Updated the existing Backport workflow per the latest working configuration. Added the workflow to delete backport branches.
Copied from:
* https://github.com/opensearch-project/OpenSearch/blob/044f53630a08b0021097e422c9f31f15fb98219d/.github/workflows/backport.yml
* https://github.com/opensearch-project/OpenSearch/blob/044f53630a08b0021097e422c9f31f15fb98219d/.github/workflows/delete_backport_branch.yml
Related to #692.

Updated the Backport workflow and added delete backport workflow

---

.github/workflows/release.yml

This updates the new "Build Release Artifacts" job to also:
* Upload archive files (tar.gz) to a staging S3 bucket
* Push the Docker image to the staging ECR repository
This is currently a draft because the GitHub Secrets are not yet present.
Resolves #1149 

Updated the release build to push the Docker image and upload archives

---

build-resources.gradle
data-prepper-expression/build.gradle

Added data-prepper-expression to test coverage report
Missing test coverage report

Added data-prepper-expression to test coverage report

---

data-prepper-expression/src/main/java/org/opensearch/dataprepper/expression/AndOperator.java
data-prepper-expression/src/main/java/org/opensearch/dataprepper/expression/GenericEqualOperator.java
data-prepper-expression/src/main/java/org/opensearch/dataprepper/expression/GenericInSetOperator.java
data-prepper-expression/src/main/java/org/opensearch/dataprepper/expression/GenericRegexMatchOperator.java
data-prepper-expression/src/main/java/org/opensearch/dataprepper/expression/NotOperator.java
data-prepper-expression/src/main/java/org/opensearch/dataprepper/expression/NumericCompareOperator.java
data-prepper-expression/src/main/java/org/opensearch/dataprepper/expression/Operator.java
data-prepper-expression/src/main/java/org/opensearch/dataprepper/expression/OperatorProvider.java
data-prepper-expression/src/main/java/org/opensearch/dataprepper/expression/OrOperator.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/AndOperatorTest.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/EqualOperatorTest.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/GreaterThanOperatorTest.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/GreaterThanOrEqualOperatorTest.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/InSetOperatorTest.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/LessThanOperatorTest.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/LessThanOrEqualOperatorTest.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/NotEqualOperatorTest.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/NotInSetOperatorTest.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/NotOperatorTest.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/OperatorProviderTest.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/OrOperatorTest.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/RegexEqualOperatorTest.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/RegexNotEqualOperatorTest.java

As a breakdown of #1145 , this PR 
* adds rule index into Operator interface
* adds OperatorProvider to encapsulate the lookup and retrieval of operator.
They will be used in ParseTreeEvaluatorListener.
Contributes to #1003 

ENH: rule index in operators and OperatorProvider

---

data-prepper-expression/build.gradle
data-prepper-expression/src/main/antlr/DataPrepperExpression.g4
data-prepper-expression/src/main/java/org/opensearch/dataprepper/expression/NotOperator.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/GrammarLexerTest.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/NotOperatorTest.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/ParseTreeCoercionServiceTest.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/ParseTreeCompositeExceptionTest.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/ParseTreeExpressionTest.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/ParseTreeTest.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/ParserTest.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/util/GrammarTest.java

Added subtract unary operator to support negative values. Ex: `-5` or `-/status_code`
Missing support for negative numbers

Negative value support with unary subtract operator

---

data-prepper-plugins/drop-events-processor/README.md
docs/expression_syntax.md

Updated `drop_events` readme to include `drop_when` and `handle_failed_events` options
Added documentation on Data Prepper Expression syntax.

Add drop_events.drop_when documentation

---

.github/workflows/release.yml

Two changes to the GitHub Actions release workflow:
* Renamed to "Release Artifacts" to shorten name and make it stand out in the Actions list
* Run a new job (on a different worker) which runs a smoke test of the Docker image built in the release process.
You can see how this build worked in my fork: https://github.com/dlvenable/data-prepper/actions/runs/1965528744
N/A

Release GitHub Actions workflow to perform Docker smoke test

---

data-prepper-expression/src/main/java/org/opensearch/dataprepper/expression/LiteralTypeConversionsConfiguration.java
data-prepper-expression/src/main/java/org/opensearch/dataprepper/expression/ParseTreeCoercionService.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/ParseTreeCoercionServiceTest.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/ParseTreeEvaluatorListenerTest.java

This PR fixes coercion on corner cases in jsonpointer value, especially
* Double value -> convert to float
* non literal value -> exception
Resolves #1003 

FIX: coercion on json pointer values

---

.github/workflows/release.yml
build.gradle
release/archives/build.gradle
release/build.gradle
release/maven/build.gradle
settings.gradle

The goal of this PR is to upload Maven artifacts to the staging S3 bucket and make them available for download.
* Created a Gradle task (and project) for uploading Maven artifacts
* Changed the Maven publish task to use a local build directory (to keep artifacts clean from other Maven artifacts)
* Fixed the root `clean` task which was not deleting the `build/` directory
* Updated the Release GitHub Action to upload Maven artifacts
* Moved all uploading GitHub Actions steps to occur after all the local build parts
* Refactored the archives Gradle project to share some common conventions with the new Maven project
Resolves #1180 …

Upload Maven artifacts as part of Release build

---

e2e-test/log/build.gradle

Force snakeyaml to version 1.29
`:e2e-test:log:basicLogEndToEndTest` failing
```
* What went wrong:
Execution failed for task ':e2e-test:log:basicLogEndToEndTest'.
> Could not resolve all files for configuration ':e2e-test:log:integrationTestRuntimeClasspath'.
> Could not find snakeyaml-1.30-android.jar (org.yaml:snakeyaml:1.30).
Searched in the following locations:
https://repo.maven.apache.org/maven2/org/yaml/snakeyaml/1.30/snakeyaml-1.30-android.jar
```
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/mai …

Force snakeyaml to version 1.29

---

data-prepper-plugins/common/src/main/java/com/amazon/dataprepper/plugins/sink/FileSink.java
data-prepper-plugins/common/src/main/java/com/amazon/dataprepper/plugins/sink/StdOutSink.java
data-prepper-plugins/common/src/test/java/com/amazon/dataprepper/plugins/sink/FileSinkTests.java
data-prepper-plugins/common/src/test/java/com/amazon/dataprepper/plugins/sink/StdOutSinkTests.java

This is a temporary fix on #1075 since we cannot get permanent fix #546 merged in for the upcoming release.
Resolves #1075 

FIX: temporarily allow output generic object type

---

data-prepper-expression/src/main/java/org/opensearch/dataprepper/expression/ParseTreeCoercionService.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/ConditionalExpressionEvaluatorIT.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/ParseTreeCoercionServiceTest.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/ParseTreeEvaluatorListenerTest.java

This PR fixes the extra quote introduced by antlr grammar in string literal value when doing expression evaluation.

FIX: remove extra quotes in string literal

---

data-prepper-plugins/key-value-processor/README.md

* key-value documentation is incorrect in the default values for `key_value_delimiter_regex` and `value_split_characters`

Fix incorrect key-value documentation

---

data-prepper-plugins/aggregate-processor/src/main/java/com/amazon/dataprepper/plugins/processor/aggregate/AggregateActionSynchronizer.java
data-prepper-plugins/aggregate-processor/src/main/java/com/amazon/dataprepper/plugins/processor/aggregate/AggregateGroup.java
data-prepper-plugins/aggregate-processor/src/main/java/com/amazon/dataprepper/plugins/processor/aggregate/AggregateGroupManager.java
data-prepper-plugins/aggregate-processor/src/main/java/com/amazon/dataprepper/plugins/processor/aggregate/AggregateProcessor.java
data-prepper-plugins/aggregate-processor/src/test/java/com/amazon/dataprepper/plugins/processor/aggregate/AggregateActionSynchronizerTest.java
data-prepper-plugins/aggregate-processor/src/test/java/com/amazon/dataprepper/plugins/processor/aggregate/AggregateGroupManagerTest.java
data-prepper-plugins/aggregate-processor/src/test/java/com/amazon/dataprepper/plugins/processor/aggregate/AggregateGroupTest.java
data-prepper-plugins/aggregate-processor/src/test/java/com/amazon/dataprepper/plugins/processor/aggregate/AggregateProcessorIT.java

* This fixes a bug where a thread is able to grab a concluded group right before another thread concludes that group, then the thread that concludes the group unlocks the `concludeGroupLock`, so the group is concluded twice

Fix bug where a group can be concluded twice in the Aggregate Processor

---

.github/workflows/opensearch-sink-os-integration-tests.yml

Added OpenSearch 1.3.0 to the list of OpenSearch versions Data Prepper tests against.
N/A

Add an integration test which tests against OpenSearch 1.3.0.

---

data-prepper-benchmarks/service-map-stateful-benchmarks/src/jmh/java/com/amazon/dataprepper/benchmarks/prepper/ServiceMapStatefulPrepperBenchmarks.java
data-prepper-plugins/service-map-stateful/build.gradle
data-prepper-plugins/service-map-stateful/src/main/java/com/amazon/dataprepper/plugins/prepper/OTelHelper.java
data-prepper-plugins/service-map-stateful/src/main/java/com/amazon/dataprepper/plugins/prepper/ServiceMapStatefulPrepper.java
data-prepper-plugins/service-map-stateful/src/test/java/com/amazon/dataprepper/plugins/prepper/ServiceMapStatefulPrepperTest.java
data-prepper-plugins/service-map-stateful/src/test/java/com/amazon/dataprepper/plugins/prepper/ServiceMapTestUtils.java

This PR "merges" the change from service-map-stateful in https://github.com/opensearch-project/data-prepper/tree/maint/546-migrate-trace-analytics-to-event-model into main branch with the following adaption:
* ServiceMapStatefulPrepper extends the AbstractProcessor interface
* ServiceMapStatefulPrepper input record data type supports either ExportTraceServiceRequest or Event
* ServiceMapStatefulPrepperTests::testTraceGroups splits into testTraceGroupsWithEventRecordData() and testTraceGroupsWithExportTraceServiceRequestRecordData() with the caveat that the latter will be removed in 2.0
* ServiceMapStatefulPrepperTests::testPrepareForShutdown splits into testPrepareForShutdownWithEventRecordData() and testPrepareForShutdownWithExportTraceServiceRequestRecordData() with the caveat that the …

MAINT: migrate service map stateful to accept both Event and ExportTraceServiceRequest as record data type

---

data-prepper-plugins/otel-trace-source/README.md
data-prepper-plugins/otel-trace-source/build.gradle
data-prepper-plugins/otel-trace-source/src/main/java/com/amazon/dataprepper/plugins/source/oteltrace/OTelTraceGrpcService.java
data-prepper-plugins/otel-trace-source/src/main/java/com/amazon/dataprepper/plugins/source/oteltrace/OTelTraceSource.java
data-prepper-plugins/otel-trace-source/src/main/java/com/amazon/dataprepper/plugins/source/oteltrace/OTelTraceSourceConfig.java
data-prepper-plugins/otel-trace-source/src/main/java/com/amazon/dataprepper/plugins/source/oteltrace/RecordType.java
data-prepper-plugins/otel-trace-source/src/test/java/com/amazon/dataprepper/plugins/source/oteltrace/OTelTraceGrpcServiceTest.java
data-prepper-plugins/otel-trace-source/src/test/java/com/amazon/dataprepper/plugins/source/oteltrace/OTelTraceSourceTest.java
data-prepper-plugins/otel-trace-source/src/test/java/com/amazon/dataprepper/plugins/source/oteltrace/OtelTraceSourceConfigTests.java
research/zipkin-opensearch-to-otel/src/main/java/com/amazon/dataprepper/research/zipkin/ZipkinOpenSearchToOtel.java

This PR "merges" otel-trace-source from https://github.com/opensearch-project/data-prepper/tree/maint/546-migrate-trace-analytics-to-event-model with the following adjustment:
* expose `record_type` as an additional otel-trace-source config parameter
* accepts either ExportTraceServiceRequest or Event as record data type in the buffer.
* make sure test cases cover both record data type.
Contributes to #1158 

MAINT: adjust otel-trace-source from trace event migration branch

---

data-prepper-plugins/peer-forwarder/build.gradle
data-prepper-plugins/peer-forwarder/src/main/java/com/amazon/dataprepper/plugins/prepper/peerforwarder/PeerForwarder.java
data-prepper-plugins/peer-forwarder/src/main/java/com/amazon/dataprepper/plugins/prepper/peerforwarder/PeerForwarderUtils.java
data-prepper-plugins/peer-forwarder/src/test/java/com/amazon/dataprepper/plugins/prepper/peerforwarder/PeerForwarderTest.java

This PR "merges" peer-forwarder from https://github.com/opensearch-project/data-prepper/tree/maint/546-migrate-trace-analytics-to-event-model with the following adjustment:
* change the peer-forwarder interface to AbstractProcessor<Record<Object>, Record<Object>>
* input and output record data types are the same but can be either ExportTraceServiceRequest or Event. 
* make sure test cases cover both record data type.
Contributes to #1158 

MAINT: peer forwarder from trace event migration branch

---

data-prepper-plugins/otel-trace-source/README.md

Signed-off-by: Qi Chen <19492223+chenqi0805@users.noreply.github.com>
This PR adds the custom metrics introduced in #1241 into README of otel_trace_source
#1158 

MAINT: add custom metrics in otel-trace-source README

---

data-prepper-plugins/opensearch/build.gradle
data-prepper-plugins/otel-trace-group-prepper/build.gradle
data-prepper-plugins/otel-trace-group-processor/build.gradle

* Use the correct convention for Gradle variables for OpenSearch constants - `opensearchVersion`
* Removed the outdated ability to configure the OpenSearch groupId. This is not needed and simplifies the build file.
N/A

Minor clean-up to OpenSearch-related build files.

---

data-prepper-plugins/opensearch/src/test/java/com/amazon/dataprepper/plugins/sink/opensearch/OpenSearchIntegrationHelper.java
data-prepper-plugins/opensearch/src/test/java/com/amazon/dataprepper/plugins/sink/opensearch/OpenSearchSinkIT.java

The `OpenSearchSinkIT` file currently inherits from `OpenSearchRestTestCase`. This class comes from the OpenSearch Core test framework. It brings in a number of requirements and assumptions, including some validations internal to OpenSearch. Our integration tests should treat OpenSearch as a black box, but that inheritance treats it as a white box.
This change copies some methods from `OpenSearchRestTestCase` into a new class `OpenSearchIntegrationHelper`. By doing this, `OpenSearchSinkIT` no longer needs to inherit from `OpenSearchRestTestCase` and I have removed that inheritance. 
There may be future approaches to simplify this even more. But, this was a minimally intrusive solution.
Contributes to #593 by moving the `opensearch` plugin toward being able to remove the OpenSearch …

Decoupled OpenSearchSinkIT from the OpenSearch Core test cases

---

.github/workflows/opensearch-sink-opendistro-integration-tests.yml
.github/workflows/opensearch-sink-os-integration-tests.yml
data-prepper-plugins/opensearch/build.gradle
data-prepper-plugins/opensearch/src/integrationTest/java/com/amazon/dataprepper/plugins/sink/opensearch/OpenSearchIT.java
data-prepper-plugins/opensearch/src/integrationTest/java/com/amazon/dataprepper/plugins/sink/opensearch/OpenSearchIntegrationHelper.java
data-prepper-plugins/opensearch/src/integrationTest/java/com/amazon/dataprepper/plugins/sink/opensearch/OpenSearchSinkIT.java
data-prepper-plugins/opensearch/src/main/java/com/amazon/dataprepper/plugins/sink/opensearch/ConnectionConfiguration.java
data-prepper-plugins/opensearch/src/main/java/com/amazon/dataprepper/plugins/sink/opensearch/index/IndexManager.java
data-prepper-plugins/opensearch/src/test/java/com/amazon/dataprepper/plugins/sink/opensearch/index/IsmPolicyManagementTests.java
e2e-test/log/build.gradle
e2e-test/trace/build.gradle
research/zipkin-opensearch-to-otel/build.gradle

This change extracts the OpenSearch `build-tools` plugin and testing framework from the `opensearch` plugin in Data Prepper. The `build-tools` plugin is really designed for OpenSearch plugins and is not appropriate for Data Prepper. It has imposed several restrictions on our build (e.g. JUnit versions, Mockito versions) and has made it difficult to update this project. Additionally, it has been blocking updating to Gradle 7.
This change has one important implication: Running the Gradle build will not perform integration tests against OpenSearch. The GitHub Actions already run these tests against different versions of OpenSearch and OpenDistro. So we will catch errors in PRs. However, developers will have to run similar commands if they wish to test locally. I believe we can eventually …

Removed the OpenSearch build-tools Gradle plugin from the OpenSearch plugin

---

data-prepper-plugins/opensearch/build.gradle
data-prepper-plugins/opensearch/src/test/java/com/amazon/dataprepper/plugins/sink/opensearch/index/DefaultIndexManagerTests.java
data-prepper-plugins/opensearch/src/test/java/com/amazon/dataprepper/plugins/sink/opensearch/index/TraceAnalyticsRawIndexManagerTests.java
data-prepper-plugins/opensearch/src/test/java/com/amazon/dataprepper/plugins/sink/opensearch/index/TraceAnalyticsServiceMapIndexManagerTests.java

The `opensearch` plugin was using some Mockito methods which were removed in later versions. These changes are needed to support updating the OpenSearch version to the 2.x series.
N/A

Updated Mockito in the opensearch plugin

---

.github/workflows/gradle.yml
.github/workflows/opensearch-sink-opendistro-integration-tests.yml
.github/workflows/opensearch-sink-os-integration-tests.yml
docs/developer_guide.md

Upload and publish the JUnit test reports for the Gradle build and OpenSearch sink integration tests. This allows us to download test reports in order to track down issues. Additionally, build the Gradle GitHub Action for all pushes since this is the core build for the project. Renamed the Gradle build to be more compact and easier to find in the list of runs. Upload and publish JUnit reports for OpenSearch sink integration tests.
N/A

Upload and publish the JUnit test reports for some tests

---

.github/workflows/opensearch-sink-opendistro-integration-tests.yml
data-prepper-plugins/opensearch/src/integrationTest/java/com/amazon/dataprepper/plugins/sink/opensearch/OpenSearchSinkIT.java

Data Prepper has an integration test for the OpenSearch sink. It currently runs against two OpenDistro versions. This PR adds support for testing against four additional versions. With this PR, Data Prepper integration tests verify from OpenDistro 1.6.0 / Elasticsearch 7.6.1 and beyond. Additionally, it tests against OpenDistro 1.13.3 instead of 1.13.2 since this addresses a security vulnerability.
In order to support this range of versions, the code to wipe indices between tests now uses the Get Indices API instead of the `_cat/indices` API.
For reference:
https://opendistro.github.io/for-elasticsearch-docs/version-history/
N/A …

Run OpenSearch sink integration tests against more versions of OpenDistro

---

build-resources.gradle
data-prepper-plugins/opensearch/build.gradle
data-prepper-plugins/opensearch/src/integrationTest/java/com/amazon/dataprepper/plugins/sink/opensearch/OpenSearchSinkIT.java
data-prepper-plugins/opensearch/src/main/java/com/amazon/dataprepper/plugins/sink/opensearch/BulkRetryStrategy.java
data-prepper-plugins/opensearch/src/main/java/com/amazon/dataprepper/plugins/sink/opensearch/ErrorCauseStringCreator.java
data-prepper-plugins/opensearch/src/main/java/com/amazon/dataprepper/plugins/sink/opensearch/OpenSearchSink.java
data-prepper-plugins/opensearch/src/main/java/com/amazon/dataprepper/plugins/sink/opensearch/bulk/AccumulatingBulkRequest.java
data-prepper-plugins/opensearch/src/main/java/com/amazon/dataprepper/plugins/sink/opensearch/bulk/BulkOperationWriter.java
data-prepper-plugins/opensearch/src/main/java/com/amazon/dataprepper/plugins/sink/opensearch/bulk/JavaClientAccumulatingBulkRequest.java
data-prepper-plugins/opensearch/src/main/java/com/amazon/dataprepper/plugins/sink/opensearch/bulk/SizedJsonData.java
data-prepper-plugins/opensearch/src/main/java/com/amazon/dataprepper/plugins/sink/opensearch/bulk/SizedJsonDataImpl.java
data-prepper-plugins/opensearch/src/test/java/com/amazon/dataprepper/plugins/sink/opensearch/BulkRetryStrategyTests.java
data-prepper-plugins/opensearch/src/test/java/com/amazon/dataprepper/plugins/sink/opensearch/ErrorCauseStringCreatorTest.java
data-prepper-plugins/opensearch/src/test/java/com/amazon/dataprepper/plugins/sink/opensearch/bulk/JavaClientAccumulatingBulkRequestTest.java
data-prepper-plugins/opensearch/src/test/java/com/amazon/dataprepper/plugins/sink/opensearch/bulk/SizedJsonDataImplTest.java

This PR updates Data Prepper to use the opensearch-java client for _bulk requests to OpenSearch. It does not update all interactions to the opensearch-java client. Others can come in subsequent PRs.
With this change, Data Prepper also runs against OpenSearch 2.0.0-rc1.
Related changes included in this PR include:
* Updated the OpenSearchSinkIT tests to test against both the `Record<String>` and `Record<Event>` models. Previously these tests only ran against `Record<Sink>`.
* Updated the OpenSearch client to 1.3.2, which is the current latest for the 1.x series.
Resolves #1347
For more information on following Developer Certificate of Origin and signing off your commits, …

Migrated Data Prepper to use the opensearch-java client for bulk requests

---

.github/workflows/release.yml

During the GitHub Actions release process, the smoke tests sometimes run on indefinitely. This PR introduces a timeout so that the job doesn't run on indefinitely.
I chose 30 minutes for each job. The main build and Docker smoke tests tend to complete around 10 minutes and tar.gz smoke tests tend to complete around 14-15 minutes. The 30 minute timeout should leave plenty of extra time for a slow-running test.
N/A

Sets a 30 minute timeout on each job in the GitHub Actions release process

---

.github/workflows/data-prepper-log-analytics-basic-grok-e2e-tests.yml
.github/workflows/data-prepper-performance-test-compile-check.yml
.github/workflows/data-prepper-trace-analytics-raw-span-compatibility-e2e-tests.yml
.github/workflows/data-prepper-trace-analytics-raw-span-e2e-tests.yml
.github/workflows/data-prepper-trace-analytics-service-map-e2e-tests.yml
.github/workflows/gradle.yml
.github/workflows/opensearch-sink-opendistro-integration-tests.yml
.github/workflows/opensearch-sink-os-integration-tests.yml
.github/workflows/release.yml
build.gradle
data-prepper-benchmarks/mapdb-benchmarks/build.gradle
data-prepper-benchmarks/service-map-stateful-benchmarks/build.gradle
data-prepper-plugins/mapdb-prepper-state/build.gradle
data-prepper-plugins/opensearch/build.gradle
data-prepper-plugins/service-map-stateful/build.gradle
docs/developer_guide.md
e2e-test/build.gradle
e2e-test/log/build.gradle
e2e-test/trace/build.gradle
research/zipkin-opensearch-to-otel/build.gradle

At a high-level, this PR adds a JDK 8 toolchain for compiling the Data Prepper main source code. It updates our GitHub Actions to build using Java 11.
Details:
* Added the JDK 8 toolchain to the Data Prepper builds.
* Use the JDK 11 toolchain for Data Prepper test code.
* Updated GitHub Actions jobs to build using JDK 11 (Gradle runs in this JVM)
* Use Tamarin/AdoptJDK as the base Docker image for end-to-end tests
* Allow running Data Prepper in different JVM versions in end-to-end tests. Gradle still run in JDK 11, but Data Prepper will on a other JDKs.
* Use a matrix to test Data Prepper logs end-to-end against JDK 8, 11, and 17.
* Use a matrix to test Data Prepper logs end-to-end against JDK 11 and 17. It appears that the Traces fail on JDK 8, which is probably not a result of this PR. …

Build on Java 11 with Java 8 as the compilation toolchain

---

data-prepper-core/src/main/java/com/amazon/dataprepper/parser/config/MetricsConfig.java
data-prepper-core/src/main/java/com/amazon/dataprepper/parser/model/DataPrepperConfiguration.java
data-prepper-core/src/test/java/com/amazon/dataprepper/TestDataProvider.java
data-prepper-core/src/test/java/com/amazon/dataprepper/parser/config/MetricsConfigTest.java
data-prepper-core/src/test/java/com/amazon/dataprepper/parser/model/DataPrepperConfigurationTests.java
data-prepper-core/src/test/resources/invalid_data_prepper_config_with_tags.yml
data-prepper-core/src/test/resources/valid_data_prepper_config_with_tags.yml
docs/configuration.md

This PR 
* adds support for custom metric tags in data-prepper-config.yml. The number of custom metric tags is limited to 3.
* for reserved tag key serviceName, the value configured in YAML will overwrite the value set from env variable
Resolves #1415 

ENH: support custom metric tags

---

.github/workflows/data-prepper-performance-test-compile-check.yml
.github/workflows/gradle.yml
build.gradle
docs/developer_guide.md
gradle.properties

Building Data Prepper on JDK 17 failed with an error from Spotless. This PR resolves this by [providing a workaround](https://github.com/diffplug/spotless/issues/834#issuecomment-819118761) suggested by the Spotless team.
Additionally, update to the latest version of the Spotless Gradle plugin. Older versions prevented the `clean` task from working correctly for the root build directory. With this update, we can clean up an unnecessary `clean` task.
Spotless fix:
https://github.com/diffplug/spotless/pull/1179
N/A …

Support building on JDK 17

---

data-prepper-plugins/s3-source/src/main/java/com/amazon/dataprepper/plugins/source/BufferAccumulator.java
data-prepper-plugins/s3-source/src/main/java/com/amazon/dataprepper/plugins/source/S3ObjectReference.java
data-prepper-plugins/s3-source/src/main/java/com/amazon/dataprepper/plugins/source/S3ObjectWorker.java
data-prepper-plugins/s3-source/src/main/java/com/amazon/dataprepper/plugins/source/codec/Codec.java
data-prepper-plugins/s3-source/src/main/java/com/amazon/dataprepper/plugins/source/codec/NewlineDelimitedCodec.java
data-prepper-plugins/s3-source/src/main/java/com/amazon/dataprepper/plugins/source/codec/NewlineDelimitedConfig.java
data-prepper-plugins/s3-source/src/test/java/com/amazon/dataprepper/plugins/source/BufferAccumulatorTest.java
data-prepper-plugins/s3-source/src/test/java/com/amazon/dataprepper/plugins/source/S3ObjectReferenceTest.java
data-prepper-plugins/s3-source/src/test/java/com/amazon/dataprepper/plugins/source/S3ObjectWorkerTest.java
data-prepper-plugins/s3-source/src/test/java/com/amazon/dataprepper/plugins/source/codec/NewlineDelimitedCodecTest.java
data-prepper-plugins/s3-source/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker

This PR adds initial support for getting uncompressed S3 objects, parsing them with the supplied Codec, and writing Events to the Buffer. It includes the `newline-delimited` Codec.
The code which is reading from SQS will call the `S3ObjectWorker::parseS3Object` on any S3 object which should be parsed. This should happen after the S3 Event filtering. The `S3ObjectWorker` and related classes will take responsibility from here to get the Event into the Buffer, which concludes the the flow of data for the source.
Some of the error handling has been deferred and will be worked in #1464 where the source will produce metrics for S3 errors.
Resolves #1434 
Resolves #1461 
For more …

Get S3 objects and support newline-delimited parsing in the S3 Source

---

.github/workflows/opensearch-sink-os-integration-tests.yml

Now that OpenSearch 2.0.0 is released, run a GHA to verify that Data Prepper runs against OpenSearch 2.0.0. Also bumped 1.3.0 to 1.3.1 which is the current latest in that series.
N/A

Run a GHA against OpenSearch 2.0.0

---

build.gradle
data-prepper-plugins/common/build.gradle
data-prepper-plugins/common/src/main/java/com/amazon/dataprepper/plugins/certificate/acm/ACMCertificateProvider.java
data-prepper-plugins/common/src/main/java/com/amazon/dataprepper/plugins/certificate/s3/S3CertificateProvider.java
data-prepper-plugins/common/src/test/java/com/amazon/dataprepper/plugins/certificate/acm/ACMCertificateProviderTest.java
data-prepper-plugins/common/src/test/java/com/amazon/dataprepper/plugins/certificate/s3/S3CertificateProviderTest.java
data-prepper-plugins/otel-metrics-source/build.gradle
data-prepper-plugins/otel-metrics-source/src/main/java/com/amazon/dataprepper/plugins/source/otelmetrics/certificate/CertificateProviderFactory.java
data-prepper-plugins/otel-trace-source/build.gradle
data-prepper-plugins/otel-trace-source/src/main/java/com/amazon/dataprepper/plugins/source/oteltrace/certificate/CertificateProviderFactory.java
data-prepper-plugins/peer-forwarder/build.gradle
data-prepper-plugins/peer-forwarder/src/main/java/com/amazon/dataprepper/plugins/prepper/peerforwarder/certificate/CertificateProviderConfig.java
data-prepper-plugins/peer-forwarder/src/main/java/com/amazon/dataprepper/plugins/prepper/peerforwarder/certificate/CertificateProviderFactory.java
data-prepper-plugins/peer-forwarder/src/main/java/com/amazon/dataprepper/plugins/prepper/peerforwarder/certificate/acm/ACMCertificateProvider.java
data-prepper-plugins/peer-forwarder/src/main/java/com/amazon/dataprepper/plugins/prepper/peerforwarder/certificate/s3/S3CertificateProvider.java
data-prepper-plugins/peer-forwarder/src/test/java/com/amazon/dataprepper/plugins/prepper/peerforwarder/certificate/acm/ACMCertificateProviderTest.java
data-prepper-plugins/peer-forwarder/src/test/java/com/amazon/dataprepper/plugins/prepper/peerforwarder/certificate/s3/S3CertificateProviderTest.java

Signed-off-by: jzonthemtn <jzemerick@opensourceconnections.com>
Removes the AWS SDK v1 dependency. Updates the code using it to use AWS SDK v2 instead.
This pull request adds no new functionality. 
#818 

#818: Moving to AWS SDK v2.

---

data-prepper-plugins/s3-source/README.md
data-prepper-plugins/s3-source/build.gradle
data-prepper-plugins/s3-source/src/integrationTest/java/com/amazon/dataprepper/plugins/source/NewlineDelimitedRecordsGenerator.java
data-prepper-plugins/s3-source/src/integrationTest/java/com/amazon/dataprepper/plugins/source/RecordsGenerator.java
data-prepper-plugins/s3-source/src/integrationTest/java/com/amazon/dataprepper/plugins/source/S3ObjectGenerator.java
data-prepper-plugins/s3-source/src/integrationTest/java/com/amazon/dataprepper/plugins/source/S3ObjectWorkerIT.java

Adds a new integration test to the S3 source. This does not build as part of the standard build because we don't want to require having AWS resources to contribute to and build Data Prepper.
When run, it will create log files in S3 and then run part of the S3 source on these to verify that the S3 source is able to correctly load a file from S3 and write to the buffer.
N/A

Integration test to verify that the S3 source can load S3 objects

---

data-prepper-plugins/common/src/main/java/com/amazon/dataprepper/plugins/certificate/file/FileCertificateProvider.java
data-prepper-plugins/http-source/src/test/java/com/amazon/dataprepper/plugins/source/loghttp/HTTPSourceTest.java
data-prepper-plugins/opensearch/src/main/java/com/amazon/dataprepper/plugins/sink/opensearch/ConnectionConfiguration.java
data-prepper-plugins/peer-forwarder/src/main/java/com/amazon/dataprepper/plugins/prepper/peerforwarder/certificate/file/FileCertificateProvider.java
data-prepper-plugins/peer-forwarder/src/test/java/com/amazon/dataprepper/plugins/prepper/peerforwarder/PeerClientPoolTest.java
data-prepper-plugins/peer-forwarder/src/test/java/com/amazon/dataprepper/plugins/prepper/peerforwarder/PeerForwarderConfigTest.java
data-prepper-plugins/peer-forwarder/src/test/java/com/amazon/dataprepper/plugins/prepper/peerforwarder/certificate/file/FileCertificateProviderTest.java

Signed-off-by: jzonthemtn <jzemerick@opensourceconnections.com>
Fixes OS-specific paths by changing from `Path.of` to `File.toPath`. No new functionality.
#970 

#970: Fixing OS dependent paths related to / in path.

---

build.gradle
data-prepper-api/build.gradle
data-prepper-expression/build.gradle
data-prepper-plugins/drop-events-processor/build.gradle
data-prepper-plugins/opensearch/build.gradle

This PR consolidates the Jackson and Micrometer versions to the same version. The root project includes the BOM files for both projects, and sub-projects no longer need to define the specific version. Additionally, it updates both dependencies to the current latest in Maven Central.
N/A

Consolidate the Jackson and Micrometer versions

---

data-prepper-plugins/s3-source/build.gradle
data-prepper-plugins/s3-source/src/integrationTest/java/com/amazon/dataprepper/plugins/source/S3ObjectWorkerIT.java
data-prepper-plugins/s3-source/src/main/java/com/amazon/dataprepper/plugins/source/S3ObjectWorker.java
data-prepper-plugins/s3-source/src/test/java/com/amazon/dataprepper/plugins/source/S3ObjectWorkerTest.java

When the S3 source fails to load an S3 object, or the codec throws an exception during parsing, add a metric indicating that the object was in failure.
Part of #1464.

Added a counter metric for when the S3 Source fails to load or parse an object

---

build.gradle
data-prepper-api/build.gradle
data-prepper-core/build.gradle
data-prepper-logstash-configuration/build.gradle
data-prepper-plugins/aggregate-processor/build.gradle
data-prepper-plugins/common/build.gradle
data-prepper-plugins/date-processor/build.gradle
data-prepper-plugins/grok-prepper/build.gradle
data-prepper-plugins/http-source/build.gradle
data-prepper-plugins/mapdb-prepper-state/build.gradle
data-prepper-plugins/opensearch/build.gradle
data-prepper-plugins/otel-metrics-raw-processor/build.gradle
data-prepper-plugins/otel-metrics-source/build.gradle
data-prepper-plugins/otel-proto-common/build.gradle
data-prepper-plugins/otel-trace-raw-prepper/build.gradle
data-prepper-plugins/otel-trace-raw-processor/build.gradle
data-prepper-plugins/otel-trace-source/build.gradle
data-prepper-plugins/peer-forwarder/build.gradle
data-prepper-plugins/s3-source/build.gradle
data-prepper-plugins/service-map-stateful/build.gradle

Moved two common test dependencies of ours into the root project so that they need only be defined in one location for most tests. I did not change the end-to-end tests.
N/A

Moved Hamcrest and Awaitility dependencies to the root project

---

build.gradle
gradle.properties

Spotless 6.7.1 fixes an issue which made it incompatible with JDK 17. There was previously a work-around (which was applied in Data Prepper). This PR updates to the latest version of Spotless for Gradle and removes that old work-around.
https://github.com/diffplug/spotless/issues/834#issuecomment-1152635256
For reference, the previous PR which added the work-around was #1430.
N/A

Updated to Spotless 6.7.1 and removed JDK 17 work-around.

---

build.gradle

Updates the AWS SDK v2 to 2.17.209. Previously, Data Prepper was not able to update this version due to a conflict with Netty and Armeria.
Resolves #924 

Updated the AWS SDK v2 to 2.17.209

---

data-prepper-plugins/s3-source/src/main/java/com/amazon/dataprepper/plugins/source/S3SourceConfig.java
data-prepper-plugins/s3-source/src/main/java/com/amazon/dataprepper/plugins/source/SqsWorker.java
data-prepper-plugins/s3-source/src/main/java/com/amazon/dataprepper/plugins/source/configuration/OnErrorOption.java
data-prepper-plugins/s3-source/src/test/java/com/amazon/dataprepper/plugins/source/SqsWorkerTest.java
data-prepper-plugins/s3-source/src/test/java/com/amazon/dataprepper/plugins/source/configuration/OnErrorOptionTest.java

- Added support to delete processed SQS messages
- Added on_error configuration which will be used to look for DLQ if enabled and not delete failed messages
Resolves #1425 

Added delete SQS messages feature to SqsWorker

---

.github/workflows/performance-test-compile.yml

These tests run on all PRs, but they really are needed often. I added a path filter which only runs when either: 1) The performance-test directory changes, or 2) the overall Gradle project changes.
Also, this PR shortens the name somewhat since our current names have some noise in them. If this looks good, I'd probably want to change the end-to-end tests as well.
N/A

Performance Test compile GitHub Actions workflow clean-up

---

data-prepper-plugins/s3-source/src/integrationTest/java/com/amazon/dataprepper/plugins/source/S3ObjectWorkerIT.java
data-prepper-plugins/s3-source/src/main/java/com/amazon/dataprepper/plugins/source/S3ObjectReference.java
data-prepper-plugins/s3-source/src/main/java/com/amazon/dataprepper/plugins/source/S3ObjectWorker.java
data-prepper-plugins/s3-source/src/main/java/com/amazon/dataprepper/plugins/source/SqsWorker.java
data-prepper-plugins/s3-source/src/test/java/com/amazon/dataprepper/plugins/source/S3ObjectReferenceTest.java
data-prepper-plugins/s3-source/src/test/java/com/amazon/dataprepper/plugins/source/S3ObjectWorkerTest.java

When performing a request to GetObject in the S3 source, add the bucket owner from the S3 Event in the `x-amz-expected-bucket-owner` header. S3 will reject the request with a 403 Forbidden if the bucket is not owned by the expected account.
This is a draft currently because it will need to be merged with other upcoming PRs. But, I want to get any early feedback on the overall approach.
Resolves #1463 

Validate bucket ownership when loading an object from S3

---

data-prepper-plugins/s3-source/src/main/java/com/amazon/dataprepper/plugins/source/S3Service.java
data-prepper-plugins/s3-source/src/main/java/com/amazon/dataprepper/plugins/source/S3Source.java
data-prepper-plugins/s3-source/src/main/java/com/amazon/dataprepper/plugins/source/S3SourceConfig.java
data-prepper-plugins/s3-source/src/main/java/com/amazon/dataprepper/plugins/source/SqsService.java
data-prepper-plugins/s3-source/src/main/java/com/amazon/dataprepper/plugins/source/configuration/CompressionOption.java
data-prepper-plugins/s3-source/src/test/java/com/amazon/dataprepper/plugins/source/S3SourceConfigTest.java
data-prepper-plugins/s3-source/src/test/java/com/amazon/dataprepper/plugins/source/SqsWorkerTest.java
data-prepper-plugins/s3-source/src/test/java/com/amazon/dataprepper/plugins/source/configuration/CompressionOptionTest.java

- Update call to S3ObjectWorker from S3Service to connect SQS and S3 workers
- Added configuration for `request_timeout` and `records_to_accumulate`

Updated call to s3 object worker

---

data-prepper-plugins/s3-source/src/integrationTest/java/com/amazon/dataprepper/plugins/source/S3ObjectWorkerIT.java
data-prepper-plugins/s3-source/src/main/java/com/amazon/dataprepper/plugins/source/S3ObjectWorker.java
data-prepper-plugins/s3-source/src/test/java/com/amazon/dataprepper/plugins/source/S3ObjectWorkerTest.java

Two new metrics for the S3 Source:
* `s3ObjectsSucceeded` - Counter for each S3 Object which is successfully parsed.
* `s3ObjectReadTimeElapsed` - A timer to track how long reading S3 objects takes.
These are the last metrics I expect to add to the S3 Source related to S3 itself. There is another issue - #1501 - to track metrics more directly related to SQS.
Resolves #1464 

New metrics on the S3 source - Succeeded Count and Read Time Elapsed

---

data-prepper-core/src/main/java/com/amazon/dataprepper/plugin/PluginConfigurationConverter.java
data-prepper-core/src/test/java/com/amazon/dataprepper/plugin/PluginConfigurationConverterTest.java

When creating a plugin configuration with an empty plug-in settings, make that configuration non-null. This fixes a bug where the call to `validate()` was provided a null pointer. Additionally, plugins should expect that their configurations are non-null.
N/A

Fix exception when plugin settings are empty

---

data-prepper-plugins/s3-source/build.gradle
data-prepper-plugins/s3-source/src/integrationTest/java/com/amazon/dataprepper/plugins/source/S3ObjectWorkerIT.java
data-prepper-plugins/s3-source/src/main/java/com/amazon/dataprepper/plugins/source/S3ObjectWorker.java
data-prepper-plugins/s3-source/src/main/java/com/amazon/dataprepper/plugins/source/S3Service.java
data-prepper-plugins/s3-source/src/main/java/com/amazon/dataprepper/plugins/source/S3Source.java
data-prepper-plugins/s3-source/src/main/java/com/amazon/dataprepper/plugins/source/S3SourceConfig.java
data-prepper-plugins/s3-source/src/main/java/com/amazon/dataprepper/plugins/source/SqsQueueUrl.java
data-prepper-plugins/s3-source/src/main/java/com/amazon/dataprepper/plugins/source/SqsWorker.java
data-prepper-plugins/s3-source/src/main/java/com/amazon/dataprepper/plugins/source/ownership/BucketOwnerProvider.java
data-prepper-plugins/s3-source/src/main/java/com/amazon/dataprepper/plugins/source/ownership/ConfigBucketOwnerProviderFactory.java
data-prepper-plugins/s3-source/src/main/java/com/amazon/dataprepper/plugins/source/ownership/NoOwnershipBucketOwnerProvider.java
data-prepper-plugins/s3-source/src/main/java/com/amazon/dataprepper/plugins/source/ownership/StaticBucketOwnerProvider.java
data-prepper-plugins/s3-source/src/test/java/com/amazon/dataprepper/plugins/source/S3ObjectWorkerTest.java
data-prepper-plugins/s3-source/src/test/java/com/amazon/dataprepper/plugins/source/SqsQueueUrlTest.java
data-prepper-plugins/s3-source/src/test/java/com/amazon/dataprepper/plugins/source/ownership/ConfigBucketOwnerProviderFactoryTest.java
data-prepper-plugins/s3-source/src/test/java/com/amazon/dataprepper/plugins/source/ownership/NoOwnershipBucketOwnerProviderTest.java
data-prepper-plugins/s3-source/src/test/java/com/amazon/dataprepper/plugins/source/ownership/StaticBucketOwnerProviderTest.java

The owner identity as provided by S3 Events is not actually a valid AWS accountId which can be used to validate that the object is owned by the expected account.
This changes the approach to use the accountId of the SQS URL to determine the expected account Id. Pipeline authors can disable the validate altogether if the bucket is in a different account than the SQS queue.
We can expand this later with a map of bucket names to expected accountIds.  …

Use the SQS Queue URL account Id to get the bucket ownership

---

data-prepper-plugins/armeria-common/src/main/java/com/amazon/dataprepper/armeria/authentication/GrpcAuthenticationProvider.java
data-prepper-plugins/armeria-common/src/test/java/com/amazon/dataprepper/plugins/GrpcAuthenticationProviderTest.java
data-prepper-plugins/otel-metrics-source/src/main/java/com/amazon/dataprepper/plugins/source/otelmetrics/OTelMetricsSource.java
data-prepper-plugins/otel-metrics-source/src/test/java/com/amazon/dataprepper/plugins/source/otelmetrics/OTelMetricsSourceTest.java
data-prepper-plugins/otel-trace-source/src/main/java/com/amazon/dataprepper/plugins/source/oteltrace/OTelTraceSource.java
data-prepper-plugins/otel-trace-source/src/test/java/com/amazon/dataprepper/plugins/source/oteltrace/OTelTraceSourceTest.java

Create an optional plugin to get an HTTP Auth service for the GRPC Auth Provider

Add in getHttpAuthenticationService to GrpcAuthenticationProvider

---

data-prepper-plugins/s3-source/README.md
data-prepper-plugins/s3-source/src/integrationTest/java/com/amazon/dataprepper/plugins/source/SqsWorkerIT.java

* Fix an NPE by mocking micrometer classes in `SqsWorkerIT`
* Updated the README.md with updated instructions
N/A

Fixes a bug in the SqsWorkerIT where an NPE occurs and README.md update

---

gradle.properties

The `main` branch is now working toward Data Prepper 2.0.0, so updated the version to `2.0.0-SNAPSHOT`.
N/A

Version bump to 2.0.0-SNAPSHOT on the main branch.

---

data-prepper-plugins/otel-metrics-source/README.md
data-prepper-plugins/otel-metrics-source/src/main/java/com/amazon/dataprepper/plugins/source/otelmetrics/OTelMetricsSource.java
data-prepper-plugins/otel-metrics-source/src/main/java/com/amazon/dataprepper/plugins/source/otelmetrics/OTelMetricsSourceConfig.java
data-prepper-plugins/otel-metrics-source/src/test/java/com/amazon/dataprepper/plugins/source/otelmetrics/OTelMetricsSourceTest.java
data-prepper-plugins/otel-metrics-source/src/test/java/com/amazon/dataprepper/plugins/source/otelmetrics/OtelMetricsSourceConfigTests.java
data-prepper-plugins/otel-trace-source/README.md
data-prepper-plugins/otel-trace-source/src/main/java/com/amazon/dataprepper/plugins/source/oteltrace/OTelTraceSource.java
data-prepper-plugins/otel-trace-source/src/main/java/com/amazon/dataprepper/plugins/source/oteltrace/OTelTraceSourceConfig.java
data-prepper-plugins/otel-trace-source/src/test/java/com/amazon/dataprepper/plugins/source/oteltrace/OTelTraceSourceTest.java
data-prepper-plugins/otel-trace-source/src/test/java/com/amazon/dataprepper/plugins/source/oteltrace/OtelTraceSourceConfigTests.java

Signed-off-by: Dinu John <dinujohn@amazon.com>
Enable HTTP Health Check for OTelTraceSource and OTelMetricsSource
[1546](https://github.com/opensearch-project/data-prepper/issues/1546)

Enable HTTP Health Check for OTelTraceSource and OTelMetricsSource.

---

examples/jaeger-hotrod/docker-compose.yml
examples/jaeger-hotrod/otel-collector-config.yml

Updates the OTel Collector in the Jaeger HotRod sample to 0.54.0. The configure for disabling TLS changed along the way, so this includes the necessary configuration update.
N/A

Updated the sample OTel Collector to the current latest version: 0.54.0.

---

data-prepper-plugins/peer-forwarder/README.md
data-prepper-plugins/peer-forwarder/src/main/java/com/amazon/dataprepper/plugins/prepper/peerforwarder/PeerForwarderConfig.java
data-prepper-plugins/peer-forwarder/src/main/java/com/amazon/dataprepper/plugins/prepper/peerforwarder/discovery/AwsCloudMapPeerListProvider.java
data-prepper-plugins/peer-forwarder/src/test/java/com/amazon/dataprepper/plugins/prepper/peerforwarder/discovery/AwsCloudMapPeerListProviderTest.java
data-prepper-plugins/peer-forwarder/src/test/java/com/amazon/dataprepper/plugins/prepper/peerforwarder/discovery/AwsCloudMapPeerListProvider_CreateTest.java

This PR adds `awsCloudMapQueryParameters` as an optional setting when using AWS CloudMap for peer discovery. The implementation accepts a `Map<String, String>` which is passed directly to the `queryParameters` field of the `DiscoverInstancesRequest`.
Documentation on this field: https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/servicediscovery/model/DiscoverInstancesRequest.Builder.html#queryParameters-java.util.Map-
AWS CloudMap service contents:
```
aws servicediscovery --region eu-west-1 discover-instances --namespace serv-disc --service serv-disc
{
"Instances": [
{
"InstanceId": "a2ae948ed1244897bf8dfa404fc9593c",
"NamespaceName": "serv-disc",
"ServiceName": "serv-disc",
"HealthStatus": "HEALTHY",
"Attributes": {
"AWS_INSTANCE_IPV4": "<redacted>",
"REGION": …
```

Add QueryParameters option to AWS CloudMap-based peer discovery

---

data-prepper-plugins/s3-source/build.gradle
data-prepper-plugins/s3-source/src/main/java/com/amazon/dataprepper/plugins/source/codec/NewlineDelimitedCodec.java
data-prepper-plugins/s3-source/src/main/java/com/amazon/dataprepper/plugins/source/compression/GZipCompressionEngine.java
data-prepper-plugins/s3-source/src/test/java/com/amazon/dataprepper/plugins/source/compression/GZipCompressionEngineTest.java

This fixes the bug where all the log files are not coming through when logs are new line delimited with GZip compression.
Using apache-commons compress library to fix this by replacing `GZIPInputStream` with `GzipCompressorInputStream`.
➡️  There will be a separate PR for Integration Testing.
Resolves #1568

Fix: Updated GZipCompressionEngine to use GzipCompressorInputStream

---

THIRD-PARTY

Version 1.5.1 adds Apache commons-compress to the dependencies list. Re-generated the `THIRD-PARTY` file.
N/A

Updated the THIRD-PARTY file for 1.5.1

---

release/release-notes/data-prepper.change-log-1.5.1.md

Adds the `CHANGELOG` for 1.5.1.
```
git checkout 1.5
git-release-notes 1.5.0..HEAD markdown > release/release-notes/data-prepper.change-log-1.5.1.md
```
N/A

Added the CHANGELOG for 1.5.1

---

data-prepper-plugins/log-generator-source/build.gradle
data-prepper-plugins/log-generator-source/src/main/java/com/amazon/dataprepper/plugins/source/loggenerator/LogGeneratorSourceConfig.java
data-prepper-plugins/log-generator-source/src/test/java/com/amazon/dataprepper/plugins/source/loggenerator/LogGeneratorSourceConfigTest.java
data-prepper-plugins/log-generator-source/src/test/java/com/amazon/dataprepper/plugins/source/loggenerator/LogGeneratorSourceTest.java

Signed-off-by: Finn Roblin <finnrobl@amazon.com>
This PR adds unit tests for the Log Generator Source plugin.
#1548, Create Log Generator Source with common apache log type
* Documentation and javadoc are still needed.
Because the log generator uses a `ScheduledExecutor` with minimum interval length of 1 second, each `LogGeneratorSourceTest` test uses at least one > 1 second `Thread.sleep` call. To prioritize speed, I test several behaviors with each Thread.sleep call. Happy to switch if there’s a better alternative.  …

Wrote unit tests for LogGeneratorSource, updated gradle.build dependencies

---

data-prepper-plugins/s3-source/src/integrationTest/java/com/amazon/dataprepper/plugins/source/S3ObjectGenerator.java
data-prepper-plugins/s3-source/src/integrationTest/java/com/amazon/dataprepper/plugins/source/S3ObjectWorkerIT.java
data-prepper-plugins/s3-source/src/integrationTest/java/com/amazon/dataprepper/plugins/source/SqsWorkerIT.java

- Updated `S3ObjectWorkerIT` to use `GZipCompressionEngine` for compressed files
- Updated `S3ObjectGenerator` to write `.gz` files using `GZIPOutputStream`
This PR doesn't include testing concatenated gzip files.

Updated integration tests with GZIP compression tests

---

data-prepper-api/src/main/java/com/amazon/dataprepper/model/configuration/PipelineModel.java
data-prepper-api/src/test/java/com/amazon/dataprepper/model/configuration/PipelineModelTest.java
data-prepper-logstash-configuration/src/main/java/org/opensearch/dataprepper/logstash/mapping/LogstashMapper.java
data-prepper-logstash-configuration/src/test/java/org/opensearch/dataprepper/logstash/mapping/LogstashMapperTest.java
data-prepper-logstash-configuration/src/test/java/org/opensearch/dataprepper/logstash/mapping/TestDataProvider.java
data-prepper-logstash-configuration/src/test/resources/org/opensearch/dataprepper/logstash/empty.conf
data-prepper-logstash-configuration/src/test/resources/org/opensearch/dataprepper/logstash/empty.expected.yaml
data-prepper-plugins/log-generator-source/src/test/java/com/amazon/dataprepper/plugins/source/loggenerator/LogGeneratorSourceTest.java

* Add buffer `PluginModel` as optional parameter in `PipelineModel`
* Require a non-null source and at least one sink in `PipelineModel`
* Logstash conversion throws `LogstashMappingException` if no `input` or `output` plugins are provided

Add buffer PluginModel to PipelineModel, require 1 source and at least 1 sink

---

data-prepper-plugins/opensearch/build.gradle
data-prepper-plugins/opensearch/src/integrationTest/java/com/amazon/dataprepper/plugins/sink/opensearch/OpenSearchSinkIT.java
data-prepper-plugins/opensearch/src/main/java/com/amazon/dataprepper/plugins/sink/opensearch/OpenSearchSink.java
data-prepper-plugins/opensearch/src/main/java/com/amazon/dataprepper/plugins/sink/opensearch/bulk/BulkAction.java
data-prepper-plugins/opensearch/src/main/java/com/amazon/dataprepper/plugins/sink/opensearch/bulk/JavaClientAccumulatingBulkRequest.java
data-prepper-plugins/opensearch/src/main/java/com/amazon/dataprepper/plugins/sink/opensearch/index/IndexConfiguration.java
data-prepper-plugins/opensearch/src/test/java/com/amazon/dataprepper/plugins/sink/opensearch/OpenSearchSinkConfigurationTests.java
data-prepper-plugins/opensearch/src/test/java/com/amazon/dataprepper/plugins/sink/opensearch/bulk/BulkActionTest.java

Adds support for bulk create option
#1457 Create-only actions in OpenSearch bulk requests

Adds support for bulk create option

---

data-prepper-api/src/main/java/com/amazon/dataprepper/model/configuration/PipelineModel.java
data-prepper-api/src/test/java/com/amazon/dataprepper/model/configuration/PipelinesDataFlowModelTest.java
data-prepper-api/src/test/resources/pipelines_data_flow_serialized.yaml

* This change serializes the `PipelineModel` with value `delay`, rather than the variable name of `readBatchDelay`, which is not a valid parameter in Data Prepper

Add @JsonProperty to workers and readBatchDelay in PipelineModel

---

data-prepper-core/src/main/java/com/amazon/dataprepper/peerforwarder/PeerForwarderReceiveBuffer.java
data-prepper-core/src/test/java/com/amazon/dataprepper/peerforwarder/PeerForwarderReceiveBufferTest.java

- Implemented `PeerForwarderReceiveBuffer` which is similar to `BlockingBuffer`. 
Resolves #1603 

Added buffer for core peer forwarder

---

data-prepper-plugins/s3-source/build.gradle
data-prepper-plugins/s3-source/src/main/java/com/amazon/dataprepper/plugins/source/DateTimeJsonSerializer.java
data-prepper-plugins/s3-source/src/main/java/com/amazon/dataprepper/plugins/source/S3EventNotification.java
data-prepper-plugins/s3-source/src/main/java/com/amazon/dataprepper/plugins/source/SqsWorker.java
data-prepper-plugins/s3-source/src/main/java/com/amazon/dataprepper/plugins/source/filter/ObjectCreatedFilter.java
data-prepper-plugins/s3-source/src/main/java/com/amazon/dataprepper/plugins/source/filter/S3EventFilter.java
data-prepper-plugins/s3-source/src/test/java/com/amazon/dataprepper/plugins/source/filter/ObjectCreatedFilterTest.java

This PR removes the dependency on the AWS S3 SDKv1. It does not include any new functionality and hopefully should not affect current functionality.
#1562 

Remove dependency on AWS S3 SDKv1

---

data-prepper-core/src/main/java/com/amazon/dataprepper/plugin/PluginPackagesSupplier.java
data-prepper-core/src/main/resources/META-INF/data-prepper.plugins.properties
data-prepper-core/src/test/java/com/amazon/dataprepper/plugin/PluginPackagesSupplierTest.java

Updates the plugin framework and plugin configuration to load plugins from the `org.opensearch.dataprepper.plugins` package in addition to the old `com.amazon.dataprepper.plugins` package.
None directly, but will help with #344 by allowing us to migrate over time rather than in one large PR.

Support loading plugins from org.opensearch.dataprepper

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/Pipeline.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/PipelineTests.java

Updated `Pipeline` somewhat, including making `publishToSinks` package protected.
Added unit tests for `publishToSinks`. This important class had no tests. This will be the basis of testing changes for conditional routing.
N/A

Clean-up Pipeline and added unit tests to for publishToSinks

---

data-prepper-plugins/http-source/build.gradle
data-prepper-plugins/http-source/src/main/java/com/amazon/dataprepper/plugins/source/loghttp/HTTPSourceConfig.java
data-prepper-plugins/http-source/src/main/java/com/amazon/dataprepper/plugins/source/loghttp/certificate/CertificateProviderFactory.java
data-prepper-plugins/http-source/src/test/java/com/amazon/dataprepper/plugins/source/loghttp/HTTPSourceConfigTest.java
data-prepper-plugins/http-source/src/test/java/com/amazon/dataprepper/plugins/source/loghttp/certificate/CertificateProviderFactoryTest.java

- Added support to read cert files from s3
- Added support for ACM
- Removed unused `ssl_key_password` configuration
- Updating documentation / readme isn't part of this PR. Might need to track it separately.
Resolves #1670 
Resolves #365

Added ACM and S3 certificate support for HTTP source

---

data-prepper-plugins/common/src/main/java/com/amazon/dataprepper/plugins/prepper/NoOpPrepper.java
data-prepper-plugins/common/src/main/java/com/amazon/dataprepper/plugins/prepper/StringPrepper.java
data-prepper-plugins/grok-prepper/src/main/java/com/amazon/dataprepper/plugins/prepper/grok/GrokPrepper.java
data-prepper-plugins/otel-trace-group-prepper/src/main/java/com/amazon/dataprepper/plugins/prepper/oteltracegroup/OTelTraceGroupPrepper.java
data-prepper-plugins/otel-trace-raw-prepper/README.md
data-prepper-plugins/otel-trace-raw-prepper/src/main/java/com/amazon/dataprepper/plugins/prepper/oteltrace/OTelTraceRawPrepper.java
data-prepper-plugins/service-map-stateful/README.md

This change updates plugins that still implement `Prepper` to use `Processor` instead. The plugins affected are `StringPrepper`, `GrokPrepper`, `NoOpPrepper`, `OTelTraceRawPrepper`, and `OTelTraceGroupPrepper`.
Resolves #647 

Update Prepper plugins to use Processor

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/parser/PipelineParser.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/parser/model/PipelineConfiguration.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/TestDataProvider.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/parser/model/PipelineConfigurationTests.java

Prior to this PR, Data Prepper had split approaches for serializing configuration YAML from deserializing YAML. The `PipelineDataFlowModel` is currently being used for serialization. And deserialization is handled by the `PipelineParser` and `PipelineConfiguration` classes. This PR fixes this split-brain issue. Deserialization now uses `PipelineDataFlowModel` as well. This helps ensure that deserialization is consistent with serialization.
This change also starts to remove the legacy `prepper:` configuration in YAML. I wasn't intending to do this, but it would be harder to keep that behavior and we plan to remove it in #619.
This change is important for supporting conditional routing of sinks.
None, but contributes toward #619 and #1337 
By submitting this pull request, I confirm that my …

Refactored the PipelineParser/PipelineConfiguration to use the PipelineDataFlowModel

---

release/archives/linux/data-prepper-jdk-x64.sh
release/archives/linux/data-prepper-x64.sh
release/smoke-tests/data-prepper-tar/Dockerfile
release/smoke-tests/data-prepper-tar/build.sh
release/smoke-tests/run-tarball-files-smoke-tests.sh

Recent changes to the Data Prepper distribution were not working with the `.tar.gz` smoke tests. This PR fixes these along with a few other changes:
* Move the `bin/data-prepper` back to using `#!/bin/bash` from `#!/bin/sh`. This script does require bash.
* Use the `bin/data-prepper` script in the tar smoke tests
* Changed the tar smoke tests to use its own Docker image. This was to help add clarity when debugging it.
N/A
```
./gradlew clean assemble :release:docker:docker -Prelease
```
```
./release/smoke-tests/run-tarball-files-smoke-tests.sh -v 2.0.0-SNAPSHOT -d release/archives/linux/build/distributions/
```
Some output from the smoke test command:
```
Image created: "opensearch-data-prepper-smoke-test:2.0.0-SNAPSHOT"
Will smoke test image …
```

Fix for the data-prepper script and running tar smoke tests

---

data-prepper-plugins/opensearch/README.md
data-prepper-plugins/opensearch/src/integrationTest/java/com/amazon/dataprepper/plugins/sink/opensearch/OpenSearchSinkIT.java
data-prepper-plugins/opensearch/src/main/java/com/amazon/dataprepper/plugins/sink/opensearch/index/IndexConfiguration.java
data-prepper-plugins/opensearch/src/test/java/com/amazon/dataprepper/plugins/sink/opensearch/OpenSearchSinkConfigurationTests.java
data-prepper-plugins/opensearch/src/test/java/com/amazon/dataprepper/plugins/sink/opensearch/index/IndexConfigurationTests.java

This change removes the deprecated `trace_analytics_raw` and `trace_analytics_service_map` fields from OpenSearch sink and updates related tests and the README file.
Contributes to #1648 

Remove deprecated configurations for OpenSearch sink

---

data-prepper-core/build.gradle
data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/server/ListPipelinesHandler.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/server/PrometheusMetricsHandler.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/server/ShutdownHandler.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/server/ListPipelinesHandlerTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/server/PrometheusMetricsHandlerTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/server/ShutdownHandlerTest.java
docs/core_apis.md

This PR updates data prepper server handlers to support proper HTTP methods specified in #313. Unit tests and docs are updated accordingly.
Resolves #313 

Allow specific HTTP methods for core API endpoints

---

build.gradle
performance-test/build.gradle

CVE-2020-36518:  `jackson-databind-2.13.1` from `gatling-charts-highcharts-3.7.4`
CVE-2022-24823: `netty-common-4.1.74.Final` from `bom-2.17.209`

Fix: CVE-2020-36518, CVE-2022-24823

---

e2e-test/log/build.gradle
e2e-test/log/src/integrationTest/java/org/opensearch/dataprepper/integration/log/EndToEndBasicLogTest.java
e2e-test/trace/build.gradle
e2e-test/trace/src/integrationTest/java/org/opensearch/dataprepper/integration/trace/EndToEndRawSpanTest.java
e2e-test/trace/src/integrationTest/java/org/opensearch/dataprepper/integration/trace/EndToEndServiceMapTest.java
e2e-test/trace/src/integrationTest/java/org/opensearch/dataprepper/integration/trace/EndToEndTestSpan.java

Updates the end-to-tests to use the `org.opensearch.dataprepper` package name.
Partially resolves #344

Update the e2e test to the org.opensearch package name

---

data-prepper-plugins/http-source/src/main/java/com/amazon/dataprepper/plugins/source/loghttp/HTTPSourceConfig.java
data-prepper-plugins/http-source/src/test/java/com/amazon/dataprepper/plugins/source/loghttp/HTTPSourceConfigTest.java

`ACMCertificatProvider` generates a passphrase if not provided.
https://github.com/opensearch-project/data-prepper/blob/caebb1964233c0d400ef40c8c7c24353ee3091ff/data-prepper-plugins/common/src/main/java/com/amazon/dataprepper/plugins/certificate/acm/ACMCertificateProvider.java#L82

Acm private key password is nullable

---

.github/workflows/opensearch-sink-opendistro-integration-tests.yml
.github/workflows/opensearch-sink-os-integration-tests.yml

Each PR we create runs the OpenSearch sink integration tests. This creates a lot of jobs. And sometimes they queue up when we make multiple pushes. This PR updates the OpenSearch integration tests to run only when the sink plugin itself is changed. it also will run if the root Gradle project changes.
None

Run OpenSearch sink integration tests only when the plugin changes

---

data-prepper-api/src/main/java/com/amazon/dataprepper/model/configuration/PipelineModel.java
data-prepper-api/src/test/java/com/amazon/dataprepper/model/configuration/PipelineModelTest.java
data-prepper-api/src/test/java/com/amazon/dataprepper/model/configuration/PipelinesDataFlowModelTest.java
data-prepper-api/src/test/resources/pipelines_data_flow_route.yaml

Updates the `PipelineModel` to use `route:` instead of `router:`. Additionally, this add some additional testing for serializing/deserializing routes.
Part of #1007. Specifically addresses this comment from the RFC: https://github.com/opensearch-project/data-prepper/issues/1007#issuecomment-1235832817

Renamed router to route in the PipelineModel

---

examples/dev/data-prepper-emf-monitoring/Dockerfile
examples/dev/data-prepper-emf-monitoring/docker-compose.yml
examples/dev/trace-analytics-sample-app/Dockerfile
examples/dev/trace-analytics-sample-app/docker-compose.yml
examples/dev/trace-analytics-sample-app/resources/data-prepper-wait-for-os-and-start.sh
release/build-resources.gradle
release/build.gradle
release/docker/Dockerfile
release/docker/README.md

This PR updates the Data Prepper Docker images in release and examples directory to use `eclipse-temurin:17-jdk-alpine` as base image; also updates the JDK in the tar.gz archive file to Temurin 17.
Resolves #694 

Update Docker images to use JDK 17

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/PeerForwarderAppConfig.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/server/NoOpPeerForwarderServer.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/server/PeerForwarderServer.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/server/PeerForwarderServerProxy.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/server/RemotePeerForwarderServer.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/server/NoOpPeerForwarderServerTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/server/PeerForwarderServerProxyTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/server/RemotePeerForwarderServerTest.java

This PR adds a `PeerForwarderServerProxy` which determines whether to use `RemotePeerForwarderServer` or `NoOpPeerForwarderServer`. 
- `RemotePeerForwarderServer` will be started if peers are configured
- `NoOpPeerForwarderServer` doesn't use any server as no peers are configured

Added server proxy for Peer Forwarder Server

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/plugin/PluginArgumentsContext.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/plugin/PluginArgumentsContextTest.java

The plugin framework cannot correctly load classes which inherit from `PluginSetting`. This is something we will need to support conditional routing.
None

Support inherited classes from PluginSetting

---

data-prepper-main/src/main/java/org/opensearch/dataprepper/ContextManager.java
data-prepper-main/src/main/java/org/opensearch/dataprepper/DataPrepperExecute.java
e2e-test/log/build.gradle
e2e-test/trace/build.gradle
release/archives/build.gradle
release/archives/linux/data-prepper-jdk-x64.sh
release/archives/linux/data-prepper-x64.sh

This change adds the support to load configurations files from home directory, so one can run data prepper without additional arguments after those files are put in place.
The previous method of specifying paths to both pipeline and server config files as command line arguments is no longer supported.
Resolves #1728, also contributes to #1736
This PR can be tested by building the archives first:
```shell
./gradlew clean :release:archives:buildArchives -Prelease
```
Then go to `release/archives/linux/build/distributions` directory, you can see the tarball files built, one with jdk, the other without. 
Extract one of them, e.g., the one without jdk assuming jdk is installed locally already, and go to the extracted directory and run data prepper:
```shell
bin/data-prepper
```
It will load …

Load data prepper configurations from home directory

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/PeerClientPool.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/RemotePeerForwarder.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/client/PeerForwarderClient.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/PeerClientPoolTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/PeerForwarder_ClientServerIT.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/RemotePeerForwarderTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/client/PeerForwarderClientTest.java

I created a new integration test, `PeerForwarder_ClientServerIT`, which focuses on client-server interactions. While working on this, I found some bugs and fixed them. Also, some of the errors that Data Prepper was returning on the client were highly misleading. They were all returned as status codes, even when the connection was refused or unable to communicate over SSL. I changed the error handling related to this to make issues clearer.
None. Part of #700.

Peer Forwarder client-server integration testing and related fixes

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/LocalPeerForwarder.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/PeerForwarder.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/PeerForwarderProvider.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/PeerForwardingProcessorDecorator.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/RemotePeerForwarder.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/server/PeerForwarderHttpService.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/LocalPeerForwarderTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/PeerForwarderProviderTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/PeerForwarder_ClientServerIT.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/PeerForwardingProcessingDecoratorTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/RemotePeerForwarderTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/server/PeerForwarderHttpServiceTest.java

Added receive record which reads the records from buffer forwarded by other peers, and sends them to process locally.

Added receive records to peer forwarder

---

data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/PeerForwardingProcessingDecoratorTest.java

One of our tests is broken.
Sample failure:
https://github.com/opensearch-project/data-prepper/actions/runs/3069628849/jobs/4958500535
N/A

Fix broken PeerForwardingProcessingDecoratorTest by casting object

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/parser/PipelineParser.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/TestDataProvider.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/parser/PipelineParserTests.java
data-prepper-core/src/test/resources/multi-pipelines/valid_multiple_pipeline_configuration1.yml
data-prepper-core/src/test/resources/multi-pipelines/valid_multiple_pipeline_configuration2.yml
data-prepper-core/src/test/resources/multi-pipelines/valid_multiple_pipeline_configuration3.yml
data-prepper-core/src/test/resources/no-pipelines/should-not-be-parsed.txt
data-prepper-core/src/test/resources/single-pipeline/valid_multiple_pipeline_configuration.yml
data-prepper-main/src/main/java/org/opensearch/dataprepper/DataPrepperExecute.java
docs/configuration.md
docs/getting_started.md
release/archives/linux/data-prepper-jdk-x64.sh
release/archives/linux/data-prepper-x64.sh
release/docker/Dockerfile
release/docker/README.md
release/docker/build.gradle
release/smoke-tests/data-prepper-tar/Dockerfile
release/smoke-tests/docker-compose.yml
shared-config/log4j2-rolling.properties

With this change, data prepper loads pipeline configurations from `pipelines/` folder under data prepper home directory. The configurations can be specified in one yaml file or in multiple yaml files as specified in #305. 
Smoke tests were also updated.
Resolves #1736  

Load pipeline configurations from directory

---

data-prepper-core/src/test/java/org/opensearch/dataprepper/parser/PipelineParserTests.java
release/archives/README.md
release/archives/build.gradle
release/build.gradle
settings.gradle

This PR improves the `assemble` gradle task. It now calls an additional [install task](https://docs.gradle.org/current/userguide/distribution_plugin.html#sec:distribution_tasks) provided by the `distribution` plugin to create a runnable distribution. With this change, we can build and run data prepper by:
1. Run `./gradlew assemble`
2. Go to `release/archives/linux/build/install/opensearch-data-prepper-{VERSION}-linux-x64` and run `bin/data-prepper`
Resolves #1762 
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/ma …

Create a runnable distribution from assemble task

---

README.md

You can see what it will look like here:
https://github.com/dlvenable/data-prepper/tree/data-prepper-icon-readme
N/A

Adds the Data Prepper icon to the start of the README.md file.

---

docs/trace_analytics.md

Signed-off-by: Bryan Aguilar <bryaag@amazon.com>
The OTEL example contained an incorrect configuration. I have updated the configuration to use the proper syntax that can be found [here](https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/otlpexporter). 
n/a
- [x ] Commits are signed with a real name per the DCO

Fix otel config

---

data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateActionSynchronizer.java
data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateGroupManager.java
data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateProcessor.java
data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateActionSynchronizerTest.java
data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateGroupManagerTest.java
data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateProcessorTest.java

This PR implements shutdown behavior for the stateful AggregateProcessor by concluding all groups after `prepareForShutdown` is called and modifying `isReadyForShutdown` to check if the groups size is 0.
Partially #1770 

Implement AggregateProcessor shutdown behavior

---

docs/core_apis.md
docs/peer_forwarder.md

Adds core peer forwarder documentation.
resolves #1772 

Added documentation for core peer forwarder

---

data-prepper-plugins/s3-source/README.md
data-prepper-plugins/s3-source/src/integrationTest/java/com/amazon/dataprepper/plugins/source/JsonRecordsGenerator.java
data-prepper-plugins/s3-source/src/integrationTest/java/com/amazon/dataprepper/plugins/source/S3ObjectWorkerIT.java
data-prepper-plugins/s3-source/src/main/java/com/amazon/dataprepper/plugins/source/EventMetadataModifier.java
data-prepper-plugins/s3-source/src/main/java/com/amazon/dataprepper/plugins/source/S3ObjectWorker.java
data-prepper-plugins/s3-source/src/main/java/com/amazon/dataprepper/plugins/source/S3Service.java
data-prepper-plugins/s3-source/src/main/java/com/amazon/dataprepper/plugins/source/S3SourceConfig.java
data-prepper-plugins/s3-source/src/main/java/com/amazon/dataprepper/plugins/source/codec/JsonCodec.java
data-prepper-plugins/s3-source/src/test/java/com/amazon/dataprepper/plugins/source/EventMetadataModifierTest.java
data-prepper-plugins/s3-source/src/test/java/com/amazon/dataprepper/plugins/source/S3ObjectWorkerTest.java
data-prepper-plugins/s3-source/src/test/java/com/amazon/dataprepper/plugins/source/codec/JsonCodecTest.java

This makes a few end-user changes related to the S3 source:
* Moves the `key` and `bucket` keys into a metadata key that starts with `s3/` by default.
* Adds the `metadata_root_key` S3 source config which allows modifying the key specified above.
* Changes the JSON codec to populate the root Event rather than the `message` key.
Along with this change, I did some refactoring to decouple the metadata population from the S3 object processing.
Resolves #1687

S3 Event Consistency via metadata and JSON changes

---

data-prepper-plugins/parse-json-processor/README.md
data-prepper-plugins/parse-json-processor/build.gradle
data-prepper-plugins/parse-json-processor/src/main/java/com/amazon/dataprepper/plugins/processor/parsejson/ParseJsonProcessor.java
data-prepper-plugins/parse-json-processor/src/main/java/com/amazon/dataprepper/plugins/processor/parsejson/ParseJsonProcessorConfig.java
data-prepper-plugins/parse-json-processor/src/test/java/com/amazon/dataprepper/plugins/processor/parsejson/ParseJsonProcessorConfigTest.java
data-prepper-plugins/parse-json-processor/src/test/java/com/amazon/dataprepper/plugins/processor/parsejson/ParseJsonProcessorTest.java

Signed-off-by: Finn Roblin <finnrobl@amazon.com>
Adds documentation and support for JSON Pointers to the `parse_json` processor
Resolves #831 

Parse JSON Processor: README, more testing, support for JSON Pointer

---

data-prepper-plugins/csv-processor/src/test/java/com/amazon/dataprepper/plugins/processor/csv/CsvProcessorIT.java
data-prepper-plugins/parse-json-processor/src/test/java/com/amazon/dataprepper/plugins/processor/parsejson/ParseJsonProcessorConfigTest.java
data-prepper-plugins/s3-source/src/integrationTest/java/com/amazon/dataprepper/plugins/source/CsvRecordsGenerator.java
data-prepper-test-common/src/main/java/org/opensearch/dataprepper/test/helper/ReflectivelySetField.java
data-prepper-test-common/src/test/java/org/opensearch/dataprepper/test/helper/ReflectivelySetFieldTest.java
data-prepper-test-common/src/test/java/org/opensearch/dataprepper/test/helper/ReflectivelySetFieldTestHelper.java

Updates the `data-prepper-test-common` project to use `org.opensearch.dataprepper` as the package for all classes.
Partially resolves #344 

Updated the package for data-prepper-test-common project

---

data-prepper-plugins/http-source/README.md
data-prepper-plugins/http-source/src/main/java/org/opensearch/dataprepper/plugins/source/loghttp/HTTPSource.java
data-prepper-plugins/http-source/src/main/java/org/opensearch/dataprepper/plugins/source/loghttp/HTTPSourceConfig.java
data-prepper-plugins/http-source/src/test/java/org/opensearch/dataprepper/plugins/source/loghttp/HTTPSourceConfigTest.java
data-prepper-plugins/http-source/src/test/java/org/opensearch/dataprepper/plugins/source/loghttp/HTTPSourceTest.java

This PR made the change to use `request_timeout` as is instead of doubling it, and use 0.8 * `request_timeout` as the buffer write timeout.
Resolves #975

Make HTTP source request timeout transparent

---

release/archives/linux/data-prepper-x64.sh

This PR makes a small change to the jdk version parser to handle cases that contain more than 3 numbers in version spec.
Before this PR, a version like "17.0.4.1" would be parsed as "17.0.4" and causing a `(standard_in) 1: syntax error` during comparison with minimum required version. With the change, "17.0.4.1" will be parsed as "17.0" so it can be compared numerically.
N/A
Issue was mentioned here: https://forum.opensearch.org/t/latest-data-prepper-not-working/11055
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob …

Fix jdk version check in script

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/PeerClientPool.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/PeerForwarderClientFactory.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/PeerForwarderConfiguration.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/exception/CertificateFingerprintParsingException.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/PeerForwarderClientFactoryTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/PeerForwarderConfigurationTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/PeerForwarder_ClientServerIT.java
data-prepper-core/src/test/resources/valid_peer_forwarder_config_with_fingerprint.yml
data-prepper-plugins/common/src/main/java/org/opensearch/dataprepper/plugins/certificate/exception/CertificateFingerprintParsingException.java
data-prepper-plugins/common/src/main/java/org/opensearch/dataprepper/plugins/certificate/model/Certificate.java
data-prepper-plugins/common/src/test/java/org/opensearch/dataprepper/plugins/certificate/model/CertificateTest.java
docs/peer_forwarder.md

~Still need to add testing, but shows the proposed approach for a fingerprint-based SSL verification.~
Adds a new flag to PeerForwarderConfiguration to verify only the fingerprint of the server's certificate through a FingerprintTrustManagerFactory implementation. 

Add sslVerifyFingerprintOnly flag to PeerForwarderConfiguration

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/parser/PipelineParser.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/PeerForwardingProcessorDecorator.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/PeerForwardingProcessingDecoratorTest.java

This PR fixes the bug for service map stateful processor with core peer forwarding. 
Service map stateful is annotated with SingleThread which creates multiple instances(equal to number of process workers) of this processor. As peer forwarder only supports one unique plugin type per pipeline this will result in an exception.

Fix: Peer forwarder exception with single thread annotated processors

---

release/docker/Dockerfile

This changes the CMD instruction in Data Prepper Dockerfile from "shell" form to "exec" form to fix the issue that the container won't exit through Ctrl+C. 
The "exec" form allows shutdown signal to be forwarded to the data prepper process properly. The different behavior between 2.0 and previous versions is likely due to the change of using the new data-prepper script to run the app.
Closes #1816

Fix Data Prepper Docker container shutdown 

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/PeerForwarderConfiguration.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/PeerClientPoolTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/PeerForwarderAppConfigIT.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/PeerForwarderConfigurationTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/PeerForwarder_ClientServerIT.java
data-prepper-core/src/test/resources/valid_data_prepper_config_wth_peer_forwarder_config.yml
data-prepper-plugins/peer-forwarder/src/test/java/com/amazon/dataprepper/plugins/prepper/peerforwarder/PeerClientPoolTest.java
docs/peer_forwarder.md

Updated port from 21890 to 4994
resolves #1811 

Updated default peer forwarder port

---

data-prepper-api/src/main/java/com/amazon/dataprepper/model/configuration/PipelineModel.java
data-prepper-api/src/main/java/com/amazon/dataprepper/model/configuration/SinkModel.java
data-prepper-api/src/test/java/com/amazon/dataprepper/model/configuration/PipelineModelTest.java
data-prepper-api/src/test/java/com/amazon/dataprepper/model/configuration/PipelinesDataFlowModelTest.java
data-prepper-api/src/test/java/com/amazon/dataprepper/model/configuration/SinkModelTest.java
data-prepper-api/src/test/resources/pipelines_data_flow_route.yaml
data-prepper-core/src/main/java/org/opensearch/dataprepper/parser/PipelineConfigurationValidator.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/parser/PipelineParser.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/parser/model/PipelineConfiguration.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/parser/model/RoutedPluginSetting.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/Pipeline.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/ProcessWorker.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/TestDataProvider.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/parser/model/PipelineConfigurationTests.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/parser/model/RoutedPluginSettingTest.java
data-prepper-logstash-configuration/src/main/java/org/opensearch/dataprepper/logstash/mapping/LogstashMapper.java
data-prepper-logstash-configuration/src/test/java/org/opensearch/dataprepper/logstash/mapping/LogstashMapperTest.java
data-prepper-logstash-configuration/src/test/java/org/opensearch/dataprepper/logstash/mapping/TestDataProvider.java

The primary goal of this PR is to build up the changes that propagate routes from the `PipelineModel` from the API level to the `PipelineConfiguration` in data-prepper-core. This is accomplished mainly through two changes.
1. Updated `PipelineModel` to return `SinkModel` for the sinks. This is an API change.
2. Added `RoutedPluginSettings` within data-prepper-core to support propagation of this information.
Contributes toward #1337 .

Updated the PipelineModel to return a SinkModel for sinks

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/parser/PipelineParser.java

- Fixes a bug where `IdentifiedComponent` is used instead of `Processor` to check if it's an instance of `RequiresPeerForwarding`

Bug fix: peer forwarder not decorating processors

---

data-prepper-api/src/main/java/com/amazon/dataprepper/model/configuration/PipelineModel.java
data-prepper-api/src/test/resources/pipelines_data_flow_route.yaml

The previous approach was using setter injection rather than via the constructor. This makes this consistent and more correct.
N/A - This was a bug found from previous Conditional Routing PRs.

Corrected the way that PipelineModel deserializes the route property

---

build-resources.gradle
data-prepper-plugins/armeria-common/build.gradle

Updates Armeria to 1.19.0 which is the current latest version of Armeria.
Resolves #1806

Update Armeria to 1.19.0 from 1.16.0

---

data-prepper-expression/src/main/java/org/opensearch/dataprepper/expression/ConditionalExpressionEvaluator.java
data-prepper-expression/src/main/java/org/opensearch/dataprepper/expression/MultiThreadParser.java
data-prepper-expression/src/main/java/org/opensearch/dataprepper/expression/ParseTreeParser.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/ConditionalExpressionEvaluatorIT.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/MultiThreadParserTest.java

This PR allows multiple threads to use the same `Parser<ParseTree>`. It does this by adding a `MultiThreadParser` which uses a `ThreadLocal`. Each thread will get is own `ParseTreeParser`.
One implication of this is that each thread will get its own expression cache. I believe there may be other solutions which can improve the performance here. But, the number of threads is mostly decided upon Data Prepper start-up.
Resolves #1189 

Support evaluating conditional expressions in multiple threads

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/RemotePeerForwarder.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/RemotePeerForwarderTest.java

Added `recordsSuccessfullyForwarded` and `requestsSuccessful` metrics
resolves #1609 

Added additional metrics to peer forwarder

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/plugin/DefaultPluginFactory.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/plugins/TestPlugin.java
docs/logstash_migration_guide.md
docs/plugin_development.md
docs/simple_pipelines.md
examples/log-ingestion/README.md
release/smoke-tests/README.md
shared-config/log4j.properties
shared-config/log4j2.properties

* Updates log4j configurations to use `org.opensearch.dataprepper`.
* Updates our documentation to show the `org.opensearch.dataprepper` package to help clarify expectations for users.
Contributes toward #344.

Updates log4j configurations and documentation for org.opensearch.dataprepper

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/trace/JacksonSpan.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/trace/JacksonSpanTest.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/server/PeerForwarderHttpService.java

- Fixed the `ClassCastException` Exception related o trace pipeline as Peer Forwarder server is writing `JacksonEvent` objects to the buffer and trace processors are trying to cast `JacksonEvent` to `Span` objects.
- Added `withJsonData()` and `withEventMetadata()` methods to `JacksonSpan` Builder.

BUG FIX: Core peer forwarder trace pipeline bug

---

release/archives/linux/data-prepper-jdk-x64.sh
release/archives/linux/data-prepper-x64.sh

Use `exec` command to run application so that data prepper is run on the container's primary process (PID 1) and be able to respond to Ctrl+c.
On 2.0, data prepper is launched through a bash script, `/bin/bash` takes PID 1 in the container and it doesn't forward shutdown signals to data prepper, which is on a child process. 
With `exec`, data prepper will replace `/bin/bash` process and runs on PID 1 so it is able to receive signal and respond to Ctrl+c.
Closes #1816 
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob …

Fix docker container shutdown issue

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/PeerForwarderAppConfig.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/PeerForwarderConfiguration.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/server/PeerForwarderServerProxy.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/TestDataProvider.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/PeerForwarderAppConfigIT.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/PeerForwarderConfigurationTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/server/PeerForwarderServerProxyTest.java
data-prepper-core/src/test/resources/invalid_peer_forwarder_with_ssl.yml
data-prepper-core/src/test/resources/invalid_peer_forwarder_with_ssl_config.yml
docs/peer_forwarder.md

- Server creation is moved from Spring configuration file to `PeerForwarderServerProxy`, so we don't need cert files for bean creation.
- Now demo certificates added by this [PR](https://github.com/opensearch-project/data-prepper/pull/1813) can be used while running Data Prepper with Peer Forwarder.
- Peer forwarder can be started without configuring `ssl`, `ssl_certificate_file`, `ssl_key_file` and will use default certificates.
- Manually tested it locally to verify if the default certificates are working.
resolves #1699 
For more information on following Developer Certificate of Origin and signing off your commits, …

Updated ssl to true by default for core peer forwarder

---

build.gradle
data-prepper-main/src/main/java/org/opensearch/dataprepper/DataPrepperExecute.java

This PR fixes a bug where Data Prepper cannot connect to an Amazon OpenSearch Service domain. It uses the AWS Apache client exclusively.
Resolves #1876

Use Apache AWS client exclusively to fix AWS Java SDK

---

release/archives/linux/data-prepper-jdk-x64.sh
release/archives/linux/data-prepper-x64.sh

The current Data Prepper `bin/data-prepper` script uses `realpath` to determine the path from where the script runs. This requires installing `coreutils` on some systems including macOS.
This PR updates Data Prepper to use `readlink -f` instead of `realpath`. This is available by default on more operation systems, including macOS.
N/A

Updates the bin/data-prepper script to use "readlink -f"

---

data-prepper-core/src/test/resources/valid_multiple_processors.yml
data-prepper-core/src/test/resources/valid_multiple_sinks.yml
data-prepper-plugins/common/src/main/java/org/opensearch/dataprepper/plugins/sink/FileSink.java
data-prepper-plugins/common/src/test/java/org/opensearch/dataprepper/plugins/sink/FileSinkTests.java

The `file` sink was not working with multiple processor threads. Each thread would re-open the file without append, which prevented it from working as expected. Now, it keeps a Writer open as long as it is running. It will flush on each output() call.
Resolves #1843 

Fixes file sink to work with multiple threads

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/parser/DataFlowComponent.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/parser/PipelineParser.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/parser/config/PipelineParserConfiguration.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/parser/model/PipelineConfiguration.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/Pipeline.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/router/DataFlowComponentRouter.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/router/RouteEventEvaluator.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/router/Router.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/router/RouterAppConfig.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/router/RouterFactory.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/parser/DataFlowComponentTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/parser/PipelineParserTests.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/parser/config/PipelineParserConfigurationTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/PipelineTests.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/router/DataFlowComponentRouterTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/router/RouteEventEvaluatorTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/router/RouterFactoryTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/router/RouterTest.java
data-prepper-core/src/test/resources/valid_multiple_sinks_with_routes.yml

This PR implements conditional routing.
I've rebased this PR to include #1840 and now it works with multiple processor threads. ~Note that this only works for single-threaded pipelines due to #1189.~
Resolves #1337 
Sample Pipeline:
```
simple-test-pipeline:
workers: 1
delay: "5000"
source:
file:
path: /usr/share/data-prepper-file-source/test-in.txt
record_type: event
format: json
route:
- alpha: '/value == "a"'
- beta: '/value == "b"'
- sigma: '/value == "s"'
sink:
- file:
path: /usr/share/data-prepper-file-source/out-alpha.txt
routes:
- alpha
- file:
path: /usr/share/data-prepper-file-source/out-beta.txt
routes:
- beta
- file:
path: /usr/share/data-prepper-file-source/out-should-be-empty.txt
routes:
- sigma
- file:
path: /usr/share/data-prepper-file-source/out-alpha-beta.txt
routes:
- …
```

Implementation of conditional routing of sinks

---

data-prepper-core/src/test/resources/valid_multiple_sinks_with_routes.yml

This fixes a problem introduced by two independent PRs: #1832 and #1842. It uses `stdout` as the sink to avoid failures with an inaccessible path.
N/A

Fix build failure in PipelineParser from conditional routing

---

data-prepper-plugins/otel-trace-source/README.md
docs/trace_analytics.md

Updates documentation to set the `record_type: event` property. Also includes a short migration guide to 2.0 for Trace pipelines.
Resolves #1735 

Updates Trace Analytics documentation for Data Prepper 2.0

---

data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSink.java

The current logging of failures in OpenSearch only includes the top-level message. This is not very helpful with unexpected errors. This PR logs the full exception using SLF4J.
N/A

Adds a stack-trace to failures from OpenSearch

---

data-prepper-plugins/blocking-buffer/src/main/java/org/opensearch/dataprepper/plugins/buffer/blockingbuffer/BlockingBuffer.java

This PR increased the default configurations for `bounding_buffer`. It increases both the `buffer_size` and `batch_size` by 25 to 12,800 and 200, respectively.
These may not be the most ideal values. But, they are better than the current defaults. This change should be considered a breaking change since it would change any pipeline which does not configure these values. So I'd rather have some improvement in 2.0 than no improvement on these values.
For the old defaults:
```
Simulation org.opensearch.dataprepper.test.performance.TargetRpsSimulation completed in 130 seconds
Parsing log file(s)...
Parsing log file(s) done
Generating reports...
================================================================================
---- Global Information …
```

Increase the default buffer configurations by 25

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/parser/DataPrepperDurationDeserializer.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/parser/DataPrepperDurationDeserializerTest.java

Supports `0s` or `0ms` simple duration values

Simple duration regex did not allow for 0s or 0ms

---

.github/workflows/data-prepper-log-analytics-basic-grok-e2e-tests.yml
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/trace/JacksonSpan.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/trace/JacksonSpanTest.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/PipelineConnector.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/PipelineConnectorTest.java
data-prepper-plugins/mutate-string-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutatestring/AbstractStringProcessor.java
e2e-test/log/build.gradle
e2e-test/log/src/integrationTest/java/org/opensearch/dataprepper/integration/log/ParallelGrokStringSubstituteLogTest.java
e2e-test/log/src/integrationTest/resources/parallel-grok-substitute-e2e-pipeline.yml

This fix resolves the issue reported in the bug https://github.com/opensearch-project/data-prepper/issues/1886. This bug is about some pipeline processors not duplicating the events before modifying them. And that was causing wrong behavior when a pipeline is split into two parallel pipelines.
When pipeline1 has two sinks pipeline2 and pipeline3 and pipeline2 is just doing grok match and pipeline3 is doing string substitution, both the pipelines will see the string substitution because same event is used in both cases. 
Fix is to make a copy of the event whenever an event is modified.
Added a new end-to-end test case that was failing without the fix and verified that the test case is passing with the fix.
Resolves #1886
By submitting this pull request, I confirm that my contribution is …

Fix PipelineConnector to duplicate the events

---

build.gradle

Updates `jackson-databind` to 2.13.4.2 which has a fix for CVE-2022-42003.
```
./gradlew -p data-prepper-main dependencies | grep jackson-databind | head -n 10
|    +--- com.fasterxml.jackson.core:jackson-databind:2.13.4 -> 2.13.4.2 (c)
|    |    +--- com.fasterxml.jackson.core:jackson-databind -> 2.13.4.2
|    |    |    +--- com.fasterxml.jackson.core:jackson-databind:2.13.4 -> 2.13.4.2 (*)
|    |    +--- com.fasterxml.jackson.core:jackson-databind:2.13.4.2 (c)
|    |    +--- com.fasterxml.jackson.core:jackson-databind:2.13.4.2 (c)
|    |    +--- com.fasterxml.jackson.core:jackson-databind:2.13.4.2 (c)
|    |    +--- com.fasterxml.jackson.core:jackson-databind -> 2.13.4.2 (*)
|    |    |    +--- com.fasterxml.jackson.core:jackson-databind:2.13.4 -> 2.13.4.2 (*)
|    |    +--- …
```

Jackson 2.13.4.2

---

data-prepper-plugins/s3-source/src/integrationTest/java/org/opensearch/dataprepper/plugins/source/SqsWorkerIT.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/SqsWorker.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/SqsWorkerTest.java

This PR fixes the bug in S3 source where keys with spaces are not decoded correctly. 
I tested it locally with and without the code change. Also made changes to `SqsWorkerIT` to have space in the key. Tested the IT also with and without the changes to verify.
```
./gradlew :data-prepper-plugins:s3-source:integrationTest --tests "org.opensearch.dataprepper.plugins.source.SqsWorkerIT" -Dtests.s3source.region=us-east-1 -Dtests.s3source.bucket=<bucket-name> -Dtests.s3source.queue.url=<queue-url>
```
resolves #1923  …

Bug Fix: S3 source key 

---

build.gradle

Require `protobuf-java-util` 3.21.7. This is the version that Data Prepper is actually use as it inherits it from Armeria.
Resolves #1891 
```
./gradlew -p data-prepper-main dependencies | grep protobuf-java-util | head -n 10
|    |    +--- com.google.protobuf:protobuf-java-util:3.21.7 (c)
|    |    +--- com.google.protobuf:protobuf-java-util:3.21.7 (c)
|    |    +--- com.google.protobuf:protobuf-java-util:3.21.7 (c)
|    |    +--- com.google.protobuf:protobuf-java-util:3.21.7 (c)
|    |    |    |    +--- com.google.protobuf:protobuf-java-util:3.21.7 (c)
|    |    |    +--- com.google.protobuf:protobuf-java-util:3.21.7 (c)
|    |    +--- com.google.protobuf:protobuf-java-util:3.21.7 (c)
|    |    |    +--- com.google.protobuf:protobuf-java-util:3.21.1 -> 3.21.7
|    |    |    +--- …
```

Require protobuf-java-util 3.21.7 to fix #1891

---

deployment-template/k8s/data-prepper-k8s.yaml

Due to Data Prepper version 2, breaking changes were introduced that impact the functioning of the current k8s reference manifest.
In this PR, the paths of the configuration file and pipelines were changed, the new processor names were used, the peer forwarding was moved to the base configuration file and added the data-prepper namespace to avoid using the default namespace.

Updated k8s manifest to suit Data Prepper 2.0

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/server/DataPrepperServer.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/server/CloudWatchMeterRegistryProviderTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/server/DataPrepperServerTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/server/SslUtilTest.java

This PR adds an ExecutorService to the DataPrepperServer with a fixed thread pool size of 3. This allows the DataPrepperServer to serve multiple requests in parallel
N/A

Add ExecutorService to DataPrepperServer

---

THIRD-PARTY

Updates the THIRD-PARTY file for 2.0.1.
Generated via:
```
git checkout 2.0
./gradlew generateThirdPartyReport
```
N/A

Updated the THIRD-PARTY for 2.0.1

---

data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/SqsWorker.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/SqsWorkerTest.java

Detects SQS messages for the `s3:TestEvent`. When found, log that it was found and delete it from the SQS queue.
Resolves #1924.
###
Validated by seeing one occurrence of:
```
2022-10-19T02:40:18,760 [Thread-1] INFO  org.opensearch.dataprepper.plugins.source.SqsWorker - Found s3:TestEvent message. Deleting from SQS queue.
```

Delete s3:TestEvent objects and log them

---

release/smoke-tests/otel-span-exporter/requirements.txt

Our current smoke tests take over 6 minutes to setup the Python test runner locally. These are also somewhat flaky on GitHub and end up taking a long time even if they will fail.
This PR uses `grpcio` 1.50.0 which takes far less time to install. Now the Python test runner takes 10 seconds.
Before the change:
```
./release/smoke-tests/run-smoke-tests.sh -v 2.0.0 -i opensearchproject/data-prepper
Will smoke test image "opensearchproject/data-prepper:2.0.0"
Creating network "smoke-tests_default" with the default driver
Building otel-span-exporter
[+] Building 381.9s (11/11) FINISHED
```
After the change:
```
docker rmi smoke-tests_otel-span-exporter
docker images prune
/release/smoke-tests/run-smoke-tests.sh -v 2.0.0 -i opensearchproject/data-prepper
Will smoke test image …
```

Use Python grpcio 1.50.0 in smoke tests to reduce time to run.

---

release/smoke-tests/run-smoke-tests.sh

The smoke tests currently run against OpenSearch 1.0.1. This updates to 1.3.6. Perhaps we should use the latest 2.x in the future, but I'd like to get this in for the 2.0.1 release and backport for 1.5.2 if it works.
N/A

Run smoke tests against OpenSearch 1.3.6.

---

data-prepper-plugins/common/src/test/java/org/opensearch/dataprepper/plugins/source/RandomStringSourceTests.java

I've seen the `RandomStringSourceTests` fail a few times in GitHub Actions. I updated the test to use Awaitility rather than a simple sleep and increased the maximum time.
While I was here, I noticed the test is testing two things, so I split it. And I updated to JUnit 5.

Attempt to reduce flakiness in RandomStringSourceTests

---

.github/workflows/release.yml

Depends on #1954 
Reduces the smoke test time to 8 minutes from 30 minutes.
With the changes from #1954, the successful smoke tests are passing within 3 minutes in my personal GitHub branch. So this leaves quite a bit of buffer time. It helps speed up retrying failures from flaky tests.
N/A

Reduce smoke test timeout to 8 minutes from 30 minutes

---

data-prepper-core/build.gradle
data-prepper-expression/build.gradle

Updates Spring to 5.3.23.
This was probably updated via dependabot and thus not backported. That is why this targets `1.5` directly.
N/A

Updates Spring to 5.3.23 on the 1.5 branch

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/server/PeerForwarderHttpService.java
data-prepper-plugins/http-source/src/main/java/org/opensearch/dataprepper/plugins/source/loghttp/LogHTTPService.java
data-prepper-plugins/otel-trace-source/src/main/java/org/opensearch/dataprepper/plugins/source/oteltrace/OTelTraceGrpcService.java

…es into the DataPrepper logs on failure. Logging the request sizes instead, to avoid customer data being logged
Signed-off-by: Deep Datta <deedatta@amazon.com>
Some of the logging in http, otel-trace and peer-forwarder were writing the actual customer logs/traces into DataPrepper logs on failure. Updating the code to not write the message contents into the logs

Update a few logs that were logging customer data on error.

---

MAINTAINERS.md

Adding @oeyh to the Data Prepper maintainers as voted by the existing maintainers.
Hai has [contributed 19 PRs](https://github.com/opensearch-project/data-prepper/pulls?q=is:pr+is:closed+author:oeyh) and has provided PR feedback on quite a number of PRs. Here are a handful of his significant and involved PRs:
* #1760
* #1737
* #1727
* #1697
* #1814

Adding Hai Yan to the maintainers

---

data-prepper-core/build.gradle
data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/integration/MinimalPipelineIT.java
data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/plugins/InMemoryConfig.java
data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/plugins/InMemorySink.java
data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/plugins/InMemorySinkAccessor.java
data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/plugins/InMemorySource.java
data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/plugins/InMemorySourceAccessor.java
data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/test/framework/DataPrepperTestRunner.java
data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/configuration/data-prepper-config.yaml
data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/minimal-pipeline.yaml

This PR creates a new `integrationTest` source set for Data Prepper. It also has a small framework for running Data Prepper within test suites so that developers can easily write integration tests which tests core Data Prepper functionality. This does not attempt to test any Data Prepper plugins and only focuses on features from `data-prepper-core` and other core projects (e.g. `data-prepper-expression`).
This includes one small test to verify a minimal pipeline.
I plan to follow on with this PR with an integration test for conditional routing.
N/A …

Data Prepper Core integration tests

---

data-prepper-plugins/aggregate-processor/README.md
data-prepper-plugins/aggregate-processor/build.gradle
data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateProcessor.java
data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateProcessorConfig.java
data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateProcessorIT.java
data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateProcessorTest.java

Add support to conditionally aggregate based on user configured condition.
Added "when:" configuration option to aggregate processor. 
With this change, the aggregate processor configuration could look like the following to do the aggregation only when the sourceIp is "10.10.10.10"
```
- aggregate:
identification_keys: ["sourceIp", "destinationIp", "port"]
action:
remove_duplicates:
when: "/sourceIp == 10.10.10.10"
```
This addresses part of issue #2015
For more information on …

Add when condition to aggregate processor

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/plugin/DefaultPluginFactory.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/plugin/DefaultPluginFactoryTest.java
data-prepper-plugins/http-source/src/main/java/org/opensearch/dataprepper/plugins/source/loghttp/HTTPSource.java
data-prepper-plugins/http-source/src/test/java/org/opensearch/dataprepper/plugins/source/loghttp/HTTPSourceTest.java
data-prepper-plugins/otel-metrics-source/src/main/java/org/opensearch/dataprepper/plugins/source/otelmetrics/OTelMetricsSource.java
data-prepper-plugins/otel-metrics-source/src/test/java/org/opensearch/dataprepper/plugins/source/otelmetrics/OTelMetricsSourceTest.java
data-prepper-plugins/otel-trace-source/src/main/java/org/opensearch/dataprepper/plugins/source/oteltrace/OTelTraceSource.java
data-prepper-plugins/otel-trace-source/src/test/java/org/opensearch/dataprepper/plugins/source/oteltrace/OTelTraceSourceTest.java

Signed-off-by: Dinu John <86094133+dinujoh@users.noreply.github.com>
Add PluginMetrics in the Auth Plugin for Http, OTel and Metrics Source. Any Auth plugin used in Http, OTel and Metrics Source should be able to emit metrics.
https://github.com/opensearch-project/data-prepper/issues/2007
- [ x] New functionality includes testing.
- [x ] New functionality has been documented.
- [x ] New functionality has javadoc added
- [ x] Commits are signed with a real name per the DCO

Add PluginMetrics in the Auth Plugin for Http, OTel and Metrics Source

---

data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/compression/AutomaticCompressionEngine.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/compression/AutomaticCompressionEngineTest.java

Use the same compression engines for GZIP and NONE in the AUTOMATIC compression engine. This will fix #2026 by using the correct GZip input stream from Apache Commons and help prevent similar issues where changes to the GZip engine are not applied to the automatic compression engine.
Resolves #2026.

Update the S3 source automatic compression option to use the same code for GZIP and NONE.

---

data-prepper-plugins/s3-source/README.md
data-prepper-plugins/s3-source/src/integrationTest/java/org/opensearch/dataprepper/plugins/source/S3ObjectWorkerIT.java
data-prepper-plugins/s3-source/src/integrationTest/java/org/opensearch/dataprepper/plugins/source/SqsWorkerIT.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/BufferAccumulator.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3ObjectWorker.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/BufferAccumulatorTest.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/S3ObjectWorkerTest.java

Adds five new metrics for the S3 source. These are all related to the S3 download portion of the source.
Resolves #2025

Implemented additional metrics for the S3 source. 

---

.github/workflows/opensearch-sink-opensearch-integration-tests.yml
build-resources.gradle

* Updated to the OpenSearch libraries for 1.3.6.
* Run integration tests against 1.3.6 instead of 1.3.5
Resolves #2022

OpenSearch 1.3.6

---

data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/integration/Router_SingleRouteIT.java
data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/integration/Router_ThreeRoutesIT.java
data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/route/single-route.yaml
data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/route/three-route.yaml

This PR introduces integration tests for the new router features introduced in Data Prepper 2.0.
This builds on the integration testing support merged in #1949.  Using those tools, this can test pipelines with multiple routes as an integration test using all the Data Prepper core components.
N/A

Pipeline router tests

---

data-prepper-plugins/aggregate-processor/README.md
data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/CountAggregateAction.java
data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/CountAggregateActionTest.java

Fix aggregation temporality of the metric generated by Count aggregation. As per the  open telemetry definition of SUM metric, https://opentelemetry.io/docs/reference/specification/metrics/data-model/#sums, the aggregation temporality in this case should be DELTA and not CUMULATIVE. …

Count Aggregate Action - fix aggregation temporality

---

data-prepper-plugins/parse-json-processor/README.md

Rename JSON processor from `json` to `parse_json` in documentation. I will work with docentation team to update it in OpenSearch documentation as well.
Resolves #2066 

Fix: Updated parse json processor documentation

---

data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/ConnectionConfiguration.java

Adds a retry strategy to the StsClient used to call AssumeRole when sending sigv4 signed request to OpenSearch sinks
- [N/A] New functionality includes testing.

Add retry strategy to StsClient used for sigv4 auth against OpenSearch sinks

---

build.gradle

- Updates all jackson dependencies to latest version `2.14.1`
- Doesn't fix any CVE's related to snakeyaml 1.30, 1.31 and 1.32 but updates it to 1.33 which still has `CVE-2022-41854`.
#2060 

Updated jackson bom dependency

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/metric/Histogram.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/metric/JacksonHistogram.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/metric/JacksonHistogramTest.java
data-prepper-plugins/aggregate-processor/README.md
data-prepper-plugins/aggregate-processor/build.gradle
data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateProcessor.java
data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/HistogramAggregateAction.java
data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/HistogramAggregateActionConfig.java
data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateProcessorIT.java
data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/HistogramAggregateActionConfigTests.java
data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/HistogramAggregateActionTests.java

This change adds support to specify histogram as an aggregate action to generate a histogram of a key in the events over aggregation period
Histogram data model of open telemetry can be found at https://opentelemetry.io/docs/reference/specification/metrics/data-model/
Configuration for histogram is based on the information from https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md
This change is part of issue #2015
#2015 
For more information on following Developer Certificate of Origin …

Histogram aggregate action

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/certificate/CertificateProviderFactory.java
data-prepper-plugins/http-source/src/main/java/org/opensearch/dataprepper/plugins/source/loghttp/certificate/CertificateProviderFactory.java
data-prepper-plugins/otel-metrics-source/src/main/java/org/opensearch/dataprepper/plugins/source/otelmetrics/certificate/CertificateProviderFactory.java
data-prepper-plugins/otel-trace-source/src/main/java/org/opensearch/dataprepper/plugins/source/oteltrace/certificate/CertificateProviderFactory.java

Adds a more robust retry strategy to the AcmClients
- [N/A] New functionality includes testing.

Add robust retry strategy to AcmClients

---

build.gradle
data-prepper-plugins/otel-trace-raw-prepper/build.gradle

Fixes 3 CVE's in `io.netty` and 10 Data Prepper vulnerabilities

Fix CVE-2022-41881, CVE-2021-21290 and CVE-2022-41915

---

data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/HistogramAggregateAction.java
data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/HistogramAggregateActionConfig.java
data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/HistogramAggregateActionTests.java

Added duration of the aggregated output as one of the attributes in the aggregated event. 
Fixed end time value.

Histogram Aggregate Action - Added duration and fixed end time in the aggregated output

---

data-prepper-plugins/s3-source/README.md

Updating documentation. I noticed a gap in the codec's supported in the documentation
none

updating S3 source documentation to include all codecs

---

.github/workflows/third-party-generate.yml

Creates a new GitHub Action which can be run on a given branch to update the `THIRD-PARTY` file for that branch. This should help simplify one aspect of the release workflow.
Here is a sample PR generated by the action on my fork:
https://github.com/dlvenable/data-prepper/pull/247
N/A

Created a GitHub Action to generate the Third Party report.

---

data-prepper-plugins/otel-proto-common/src/main/java/org/opensearch/dataprepper/plugins/otel/codec/OTelProtoCodec.java
data-prepper-plugins/otel-proto-common/src/test/java/org/opensearch/dataprepper/plugins/otel/codec/OTelProtoCodecTest.java
data-prepper-plugins/otel-proto-common/src/test/resources/test-request-both-span-types.json
data-prepper-plugins/otel-proto-common/src/test/resources/test-request-instrumentation-library.json
data-prepper-plugins/otel-proto-common/src/test/resources/test-request-no-spans.json

The InstrumentationLibrary model was renamed to InstrumentationScope as part of this PR: https://github.com/open-telemetry/opentelemetry-proto/pull/362
This PR updates the `OTelProtoDecoder` and `OTelProtoEncoder` to use the new `InstrumentationScope` model while continuing to support incoming requests using `InstrumentationLibrary` per the specification defined in the above PR.

Update OTelProtoCodec for InstrumentationLibrary to InstrumentationScope rename

---

build-resources.gradle
build.gradle

Fix all CVE's related to protobuf-java, snakeyaml, netty.
Created to handle all failed backport PR's.
https://advisories.aws.barahmand.com/vulnerabilities/Data%20Prepper/origin/2.0

2.0 branch CVE cleanup

---

data-prepper-plugins/service-map-stateful/README.md
data-prepper-plugins/service-map-stateful/src/main/java/org/opensearch/dataprepper/plugins/processor/ServiceMapStatefulProcessor.java
data-prepper-plugins/service-map-stateful/src/test/java/org/opensearch/dataprepper/plugins/processor/ServiceMapStatefulProcessorTest.java

The `service_map_stateful` processor currently has two size metrics. These return 0 since Data Prepper is not using a file.
This PR adds three new metrics.
* `spansDbCount` - The count of items in both windows for spans.
* `traceGroupDbCount` - The count of items in both windows for trace groups.
* `relationshipCount` - The count of items in the static relationship map.
N/A

Adds count metrics to the service_map_stateful processor

---

e2e-test/peerforwarder/build.gradle
e2e-test/peerforwarder/src/integrationTest/java/org/opensearch/dataprepper/integration/peerforwarder/EndToEndLogMetricsTest.java
e2e-test/peerforwarder/src/integrationTest/resources/log-metrics-pipeline.yml

Added e2e test for testing log metrics functionality.
#2126 

Add e2etest for testing log metrics

---

data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/integration/Router_ThreeRoutesIT.java

This is a follow-on PR for #1988. It makes the following changes:
* Combines two tests as discussed in the following conversation: https://github.com/opensearch-project/data-prepper/pull/1988#discussion_r1036425172
* Fixes an issue with one of the tests where data was sent to the wrong source.
N/A

Combined two integration tests for conditional routes into one. Fixed a test bug

---

data-prepper-plugins/rss-source/build.gradle
data-prepper-plugins/rss-source/src/main/java/org/opensearch/dataprepper/plugins/source/rss/RSSSource.java
data-prepper-plugins/rss-source/src/main/java/org/opensearch/dataprepper/plugins/source/rss/RssReaderTask.java
data-prepper-plugins/rss-source/src/test/java/org/opensearch/dataprepper/plugins/source/rss/RSSSourceTest.java
data-prepper-plugins/rss-source/src/test/java/org/opensearch/dataprepper/plugins/source/rss/RssReaderTaskTest.java

- This PR adds the Java `ScheduledExecutorService` to schedule reading the RSS Feed URL every 5 minutes. It is a draft to gather any feedback about using the Executor service.
- Currently, the unit test is reading from a real RSS feed URL because storing the URL in local files under `test/resources` directory resulted in `Invalid URI scheme file` errors. Finding the fix for this is still underway.
- DCO is failing, working on amending the commit messages.
#2081 

Adds ScheduledExecutorService for Polling the RSS feed

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/RemotePeerForwarder.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/RemotePeerForwarderTest.java

Fix for null pointer exception in remote peer forwarding
#2123 

Fix for null pointer exception in remote peer forwarding (fix for issue 2123)

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/PeerForwarderConfiguration.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/PeerForwarderProvider.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/RemotePeerForwarder.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/PeerForwarder_ClientServerIT.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/RemotePeerForwarderTest.java

This change makes batch delay in Core Peer Forwarder configurable 
resolves #2158 

Added batch delay to CPF configuration

---

.github/workflows/data-prepper-trace-analytics-raw-span-e2e-tests.yml
e2e-test/build.gradle
e2e-test/trace/build.gradle

Added e2e test workflows with different otel client library versions for testing with older opentelemetry client version and newer version.
Resolves #1963 

Test against multiple OTel version - Issue #1963

---

data-prepper-plugins/aggregate-processor/README.md
data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/PercentSamplerAggregateAction.java
data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/PercentSamplerAggregateActionConfig.java
data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateProcessorIT.java
data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/PercentSamplerAggregateActionConfigTests.java
data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/PercentSamplerAggregateActionTests.java

Added new aggregate action to sample the number of events by allowing only the specified percent number of events during the aggregation window.
Resolves the issue #2094 
Provide a new actionpercent_sampler that would limit the number of events to the specified percent in the configuration. Only percent number of events are allowed out of every 100 events.
```
processor:
aggregate:
identification_keys:
- # ... Identification keys for the metric ...
action:
percent_sampler: 
percent: 60
```
The above config would allow only 6 out of every 10 events received during the aggregation window.
#2094 
By submitting this pull request, I confirm that my …

New aggregate action - percent sampler

---

data-prepper-plugins/opensearch/README.md
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/ConnectionConfiguration.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/ConnectionConfigurationTests.java
data-prepper-plugins/otel-trace-group-processor/README.md
data-prepper-plugins/s3-source/README.md
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/configuration/AwsAuthenticationOptions.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/configuration/AwsAuthenticationOptionsTest.java

Adds the ability to override the AWS STS headers when using AWS STS for Amazon OpenSearch Service or Amazon S3.
Also updates `ConnectionConfigurationTests` to use JUnit 5.
Resolves #1888

Added AWS STS header override configurations for OpenSearch sink/S3 source

---

data-prepper-plugins/aggregate-processor/README.md
data-prepper-plugins/blocking-buffer/README.md
data-prepper-plugins/csv-processor/README.md
data-prepper-plugins/http-source/README.md
data-prepper-plugins/opensearch/README.md
data-prepper-plugins/otel-metrics-raw-processor/README.md
data-prepper-plugins/otel-trace-group-processor/README.md
data-prepper-plugins/otel-trace-source/README.md
data-prepper-plugins/service-map-stateful/README.md
docs/plugin_development.md
docs/trace_analytics.md

This fixes broken links which have the `com/amazon/dataprepper` path. This PR updates most to use `org/opensearch/dataprepper`. It leaves out the trace-raw since that is resolved in another PR.
N/A

Fixes links to use org/opensearch from com/amazon

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/logging/DataPrepperMarkers.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/logging/DataPrepperMarkersTest.java
data-prepper-plugins/common/src/main/java/org/opensearch/dataprepper/plugins/processor/StringProcessor.java
data-prepper-plugins/common/src/main/java/org/opensearch/dataprepper/plugins/source/file/FileSource.java
data-prepper-plugins/csv-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/csv/CsvProcessor.java
data-prepper-plugins/drop-events-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/drop/HandleFailedEventsOption.java
data-prepper-plugins/grok-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/grok/GrokProcessor.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSink.java
data-prepper-plugins/otel-trace-group-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/oteltracegroup/OTelTraceGroupProcessor.java
data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parsejson/ParseJsonProcessor.java

Signed-off-by: George Chen <qchea@amazon.com>
This PR 
- adds SENSITIVE and EVENT marker in data-prepper-api, where SENSITIVE is a child of EVENT
- populates markers where applicable throughout the project
smoke tested with DataPrepperExecute::main entrypoint. 
The following filter will filter out both SENSITIVE and EVENT.
```
appender.console.markerFilter1.type = MarkerFilter
appender.console.markerFilter1.marker = SENSITIVE
appender.console.markerFilter1.onMatch = DENY
appender.console.markerFilter1.onMismatch = NEUTRAL
```
The following filter will only filter out EVENT.
```
appender.console.markerFilter2.type = MarkerFilter
appender.console.markerFilter2.marker = EVENT
appender.console.markerFilter2.onMatch = DENY
appender.console.markerFilter2.onMismatch = NEUTRAL
```
Resolves #1990 …

ENH: add and populate markers

---

data-prepper-plugins/otel-trace-raw-processor/README.md
data-prepper-plugins/otel-trace-raw-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/oteltrace/OTelTraceRawProcessor.java
data-prepper-plugins/otel-trace-raw-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/oteltrace/OtelTraceRawProcessorConfig.java
data-prepper-plugins/otel-trace-raw-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/oteltrace/OTelTraceRawProcessorTest.java

This PR adds two new features to `otel_trace_raw`:
* New configuration options: `trace_id_ttl` and `max_trace_id_cache_size`
* Two new metrics: `traceGroupCacheCount` and `spanSetCount`
Resolves #2165
Resolves #2166 

Add configurations and metrics to OTelTraceRawProcessor

---

data-prepper-plugins/otel-metrics-raw-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/otelmetrics/OTelMetricsRawProcessor.java
data-prepper-plugins/otel-metrics-raw-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/otelmetrics/MetricsPluginSumTest.java

Fix Data Prepper to not terminate on invalid open telemetry metric data. When invalid data is received by metric or trace data source, the metric/trace is ignored and bad request counter is incremented.
Resolves #2089 

Fix Data Prepper to not terminate on invalid open telemetry metric/trace data

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/parser/model/PipelineConfiguration.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/PeerForwarderConfiguration.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/PeerForwarderReceiveBuffer.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/parser/model/PipelineConfigurationTests.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/PeerForwarderReceiveBufferTest.java
data-prepper-plugins/blocking-buffer/src/main/java/org/opensearch/dataprepper/plugins/buffer/blockingbuffer/BlockingBuffer.java
data-prepper-plugins/blocking-buffer/src/test/java/org/opensearch/dataprepper/plugins/buffer/blockingbuffer/BlockingBufferTests.java

Optimizes the buffer read logic by removing the poll before drainTo. A read delay of 0 is now valid as well, which makes only a single call to drainTo when reading. 

Optimize buffer reads, allow delay to be 0

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/parser/PipelineParser.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/PeerForwarderAppConfig.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/PeerForwarderConfiguration.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/PeerForwarderProvider.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/PeerForwardingProcessorDecorator.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/RemotePeerForwarder.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/PeerForwarderConfigurationTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/PeerForwarderProviderTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/PeerForwarder_ClientServerIT.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/PeerForwardingProcessingDecoratorTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/RemotePeerForwarderTest.java
data-prepper-core/src/test/resources/valid_peer_forwarder_config.yml

Adds implementation for batching the content of requests sent to a peer. This is aimed at reducing the number of network calls needed by the CPF.

Implement batching for peer forwarder request documents

---

data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/IsmPolicyManagement.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/s3/InvalidS3URIException.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/s3/S3FileReader.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/IndexConfigurationTests.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/IsmPolicyManagementTests.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/s3/S3FileReaderTest.java

This PR removes use of `getObjectAttributes` API and checks content length from `response().contentLength();`
resolves #2177 
resolves #2178 

Removed getObjectAttributes API call to check object size

---

data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSink.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/DynamicIndexManager.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/DynamicIndexManagerTests.java

DynamicIndexTemplate can cause NPE that shuts down pipeline.
The dynamic index feature that extracts the index name from the events is not handling the events that do not have the field that is used in the index name. 
Fix is to skip the event if it does not contain the field required to make the index name by throwing an exception.
Resolves #2210 
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRI …

DynamicIndexTemplate can cause NPE that shuts down pipeline - Issue #2210

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/sink/AbstractSink.java

In the code changes made to support retries of Sink initialization, retry thread is being created every time initialization failed.
This changes fixes it checking to make sure retry thread is not already created before creating it.

Abstract sink should not create a new retry thread everytime initialization fails

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/record/RecordMetadata.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/record/RecordMetadataTest.java

Each time a source creates a new Record, it also creates a new `RecordMetadata`. Most of these are also using the default. This class is immutable so the default value can be re-used across `Record` objects. This PR uses a private static shared default that is re-used.
N/A

Re-use the default RecordMetadata

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/DefaultEventMetadata.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/event/DefaultEventMetadataTest.java

From looking at the code, I see that most Events do not have metadata attributes. Each of these calls was creating a new `ImmutableMap`. This PR calls `ImmutableMap.of()` which will use a shared empty map. This should help reduce the object churn for Events.
N/A

Use ImmutableMap.of() in DefaultEventMetadata

---

data-prepper-plugins/blocking-buffer/README.md
docs/trace_analytics.md

Signed-off-by: Jannik Brand <jannik.brand@sap.com>
This PR updates the default buffer values (`buffer_size`, `batch_size`) in the documentation. There are new default values due to #1906 (since version [2.0.0](https://github.com/opensearch-project/data-prepper/releases/tag/2.0.0)). The default `buffer_size` (previously: 512) and default `batch_size` (previously: 8) were increased by the factor 25. The new default values are: `buffer_size`: 12800 and `batch_size`: 200.
Within the `trace_analytics.md` file an example for a possible trace pipeline setup is given. I increased the new default values by a factor of 2, so that it will match the 3200 spans each raw-pipeline worker thread could process before.
Resolves #1983 (in combination with …

Update default values in buffer documentation

---

data-prepper-plugins/otel-trace-source/src/main/java/org/opensearch/dataprepper/plugins/source/oteltrace/OTelTraceSource.java

This PR makes a few changes to the OTel Trace Source:
* Use Armeria's `BlockingTaskExecutor` class which wraps a ScheduledThreadPool.
* Give each OTel Trace thread a name which uses the pipeline name and "-otel_trace" to make tracking threads easier.
* Improved constructor use for maintainability
N/A

Use Armeria's BlockingTaskExecutor to configure thread names

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/DefaultEventMetadata.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/JacksonEvent.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/trace/JacksonSpan.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/event/DefaultEventMetadataTest.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/event/JacksonEventTest.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/trace/JacksonSpanTest.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/PipelineConnector.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/PipelineConnectorTest.java

The previous method of copying took a few steps: 1) Create a new `Map`; 2) Create a new `JsonNode`; 3) Perform a `convertValue` to get the data back into the `JsonNode` from the `Map`.
This PR adds a static method in `JacksonEvent` and `JacksonSpan` which performs a copy. If the incoming `Event`/`Span` is a Jackson-based one, then it performs a `deepCopy()` on the `JsonNode`. Otherwise, it performs the slower version above. That second is a fallback as all `Event` objects by default are the Jackson kind.
In some local and isolated testing, I found that this reduces the time to perform `PipelineConnector.output` is reduced by about one-third.
Also, some of these files had bad formatting so I ran IntelliJ's format on them to clean them up some.
n.b. I believe #1915 will be a better …

Improved PipelineConnector copy using JsonNode.deepCopy

---

release/archives/build.gradle
release/build.gradle

This change reduces some of the task dependencies when building tar.gz distributions. It doesn't need to run the data-prepper-main tests, just assemble. And it uses the correct configuration for downloading OpenJDK.
N/A

Reduce task dependencies in :release:archives:linux:linuxTar build

---

data-prepper-plugins/opensearch/README.md
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/ConnectionConfiguration.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/ConnectionConfigurationTests.java

Added `aws:` option to specify AWS specific configuration under `opensearch` sink configuration. This is an alternate (and more consistent way) of providing aws configuration.
Resolves #2184 

Consistent AWS Pipeline Configurations - #2184

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/sink/AbstractSink.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/sink/SinkThread.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/sink/AbstractSinkTest.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/sink/SinkThreadTest.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSink.java

Abstract sink initialize() catches all exceptions from doInitialize and ignores them. Abstract sink should let individual sinks to decide what exceptions to catch and what exceptions to throw.
Modified the code to remove exception catching from both Abstract sink `initialize` and SinkThread's `run` methods. OpenSearch sink is modified to log failure message in all cases. …

Sink doInitialize() should be able throw exception to stop execution

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/RemotePeerForwarder.java

Streams are less efficient than ordinary collection methods. Since `forwardBatchedRecords` is executed many times, the slight optimization of using ordinary collection methods makes a non-negligible difference in CPU utilization

Refactor to remove stream in RemotePeerForwarder as micro optimization

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/DataPrepper.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSink.java

OpenSearchSink should close open files before retrying initialization. Failing to close files would result in failure in retry due reaching file descriptor limit.
Tested manually to make sure open file descriptor limit is not reached with the fix.

OpenSearchSink should close open files before retrying initialization

---

build-resources.gradle
build.gradle
data-prepper-core/build.gradle
data-prepper-logstash-configuration/build.gradle
data-prepper-plugins/aggregate-processor/build.gradle
data-prepper-plugins/armeria-common/build.gradle
data-prepper-plugins/common/build.gradle
data-prepper-plugins/grok-processor/build.gradle
data-prepper-plugins/http-source/build.gradle
data-prepper-plugins/opensearch/build.gradle
data-prepper-plugins/otel-logs-source/build.gradle
data-prepper-plugins/otel-metrics-raw-processor/build.gradle
data-prepper-plugins/otel-metrics-source/build.gradle
data-prepper-plugins/otel-proto-common/build.gradle
data-prepper-plugins/otel-trace-group-processor/build.gradle
data-prepper-plugins/otel-trace-raw-processor/build.gradle
data-prepper-plugins/otel-trace-source/build.gradle
data-prepper-plugins/peer-forwarder/build.gradle
data-prepper-plugins/service-map-stateful/build.gradle
e2e-test/build.gradle
e2e-test/log/build.gradle
e2e-test/peerforwarder/build.gradle
e2e-test/trace/build.gradle
settings.gradle

This introduces a Gradle version catalog. So far it only goes so far as adding enough to replace the old `ext.versionMap`.
I think we can expand our use of these catalogs in future PRs, but to start I was just removing the `ext.versionMap`.
N/A

Use the Gradle version catalog for common software versions

---

data-prepper-plugins/opensearch/README.md

The index_type `management-disabled` in code is actually `management_disabled`. It uses an `_` instead of `-`. Fixing the same in README.
Verified from here: https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/IndexType.java#L18
We might update the all the index types with the same naming convention.
N/A

[Bug] Fixes index_type convention

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/meter/JvmMemoryAggregateMetrics.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/parser/config/MetricsConfig.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/meter/JvmMemoryAggregateMetricsTest.java

By default, the Micrometer memory metrics break the memory metrics into pools. This PR uses the aggregate heap and non-heap usage for a clearer view.
N/A

Created a metric for the overall JVM memory usage - both heap and non-heap

---

data-prepper-plugins/service-map-stateful/src/main/java/org/opensearch/dataprepper/plugins/processor/ServiceMapRelationship.java
data-prepper-plugins/service-map-stateful/src/test/java/org/opensearch/dataprepper/plugins/processor/ServiceMapRelationshipTest.java

This is more of a hygiene PR. ServiceMapRelationship had some public setters which made it seem it might be mutable. That is not the case, so I removed them. I also add some unit test cases to cover existing behaviors.
N/A

Clean-up and testing for ServiceMapRelationship

---

settings.gradle

Updates to Armeria 1.22.1. This includes fixes (one from 1.22.0 and another from 1.22.1) for #2206.
Resolves #2206

Update to Armeria 1.22.1 which fixes #2206

---

data-prepper-plugins/otel-trace-source/build.gradle
data-prepper-plugins/otel-trace-source/src/main/java/org/opensearch/dataprepper/plugins/source/oteltrace/OTelTraceGrpcService.java
data-prepper-plugins/otel-trace-source/src/test/java/org/opensearch/dataprepper/plugins/source/oteltrace/OTelTraceSourceTest.java

Changes to OTel Trace Source
Logging improvements when traces fail to parse. These are related to #2185.
* Logs only the exception message. The whole stack trace is not necessary since this is not a bug in Data Prepper.
* Include the Trace in the message.
* Adds the SENSITIVE marker so that this logging can be disabled.
* Move to WARN from ERROR. Again, this is not a bug in Data Prepper.
Adds new integration tests. The test for this did not actually verify correct behavior for gRPC calls. This adds a few new tests to verify this behavior.
Related to #2185. …

OTel Trace Source: Logging and integration tests

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/PeerForwarderProvider.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/PeerForwarderReceiveBuffer.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/PeerForwarderReceiveBufferTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/RemotePeerForwarderTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/server/PeerForwarderHttpServiceTest.java

Refactor the PeerForwarderReceiveBuffer to extend `AbstractBuffer`. This allows the CPF buffers to leverage the metrics implementation from `AbstractBuffer`. Metrics for the CPF buffers are of the format `core.peerForwarder.<pipelineName>.<pluginName>.<metricName>` i.e. `core.peerForwarder.raw-pipeline.otel_trace_raw.usage`

Refactor PeerForwarderReceiveBuffer to extend AbstractBuffer to pick up metric logic

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/server/DataPrepperServer.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/server/HttpServerProvider.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/server/config/DataPrepperServerConfiguration.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/server/DataPrepperServerTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/server/config/DataPrepperServerConfigurationTest.java

This PR moves the DataPrepper server creation to the DataPrepperServer class rather than creating the server through injection. This allows the pipeline initialization logic to happen before the server port is opened. 

Create DataPrepper server after pipeline initialization

---

data-prepper-plugins/otel-trace-raw-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/oteltrace/OTelTraceRawProcessor.java
data-prepper-plugins/otel-trace-raw-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/oteltrace/model/TraceGroup.java
data-prepper-plugins/otel-trace-raw-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/oteltrace/model/TraceGroupTest.java

The `otel_trace_raw` processor was using a builder pattern to create a `TraceGroup` object for each parent span. This is used rather rigidly, so we can replace it with a factory method. This is a small optimization to reduce object creation (specifically removes the call to create a new builder object).
N/A

Use a factory method in trace raw processor

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/configuration/DataPrepperVersion.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/configuration/PipelinesDataFlowModel.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/configuration/DataPrepperVersionTest.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/configuration/PipelinesDataFlowModelTest.java
data-prepper-api/src/test/resources/pipeline_with_short_hand_version.yaml
data-prepper-api/src/test/resources/pipeline_with_version.yaml
data-prepper-core/src/main/java/org/opensearch/dataprepper/parser/PipelineParser.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/TestDataProvider.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/parser/PipelineParserTests.java
data-prepper-core/src/test/resources/compatible_version.yml
data-prepper-core/src/test/resources/incompatible_version.yml
docs/configuration.md
gradle.properties

Adding data prepper version as part of the pipeline configuration file. This PR creates a new `DataPrepperVersion` model in the API that is used in the `PipelinesDataFlowModel`. Added support for validating the current version is compatible with the current version of data prepper. Updated the documentation.
- resolves #2263 

[2263] adding versioning property to pipeline yaml configuration

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/configuration/DataPrepperVersion.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/configuration/DataPrepperVersionTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/parser/PipelineParserTests.java
data-prepper-core/src/test/resources/incompatible_version.yml
docs/configuration.md

This is a follow on of #2292
Adds backward compatibility support to version check. In any major version, we should have migration fields to help with migrations. So a pipeline created for 1.5 could be compatible for 2.0. But, not always. This change will make it easier for migrating between major versions.
None

adding backwards compatibility support in versioning check

---

data-prepper-api/src/test/java/org/opensearch/dataprepper/model/configuration/DataPrepperVersionTest.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSink.java

Fix error message printed when OpenSearch Sink fails to initialize.
Currently, when an exception is caused during initialization, the getCause() may be null. If it is null, we should print the entire exception.

Fix error message printed when OpenSearch Sink fails to initialize

---

data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/SqsWorker.java

The S3 source performs its shutdown work by [interrupting the SqsWorker thread](https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/SqsService.java#L51). Sometimes this works as intended, but it often fails to stop the SqsWorker. This PR changes the while loop in the SqsWorker's run method to be conditional on interruption instead of looping infinitely.

Loop until interrupted in SqsWorker

---

e2e-test/build.gradle

- Removes use of alpine image to run e2e tests on ARM architecture
Contributes towards #640 

Updated Data Prepper base image for e2e tests

---

data-prepper-plugins/http-source/README.md
data-prepper-plugins/http-source/src/main/java/org/opensearch/dataprepper/plugins/source/loghttp/HTTPSource.java
data-prepper-plugins/http-source/src/main/java/org/opensearch/dataprepper/plugins/source/loghttp/HTTPSourceConfig.java
data-prepper-plugins/http-source/src/test/java/org/opensearch/dataprepper/plugins/source/loghttp/HTTPSourceConfigTest.java
data-prepper-plugins/http-source/src/test/java/org/opensearch/dataprepper/plugins/source/loghttp/HTTPSourceTest.java
e2e-test/log/src/integrationTest/java/org/opensearch/dataprepper/integration/log/EndToEndBasicLogTest.java
e2e-test/log/src/integrationTest/resources/basic-grok-e2e-pipeline.yml

- Adds `path` option to HTTP source
- Updated grok e2e to verify the change
Resolves #2258 

Added path support for HTTP source

---

data-prepper-plugins/grok-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/grok/GrokProcessor.java

Grok processor's `doExecute()` is unnecessarily creating a new record. Modified the code to return the existing records instead of creating new records.

Fix grok processor to not create a new record

---

data-prepper-plugins/otel-logs-source/README.md
data-prepper-plugins/otel-logs-source/src/main/java/com/amazon/dataprepper/plugins/source/otellogs/OTelLogsSource.java
data-prepper-plugins/otel-logs-source/src/main/java/com/amazon/dataprepper/plugins/source/otellogs/OTelLogsSourceConfig.java
data-prepper-plugins/otel-logs-source/src/test/java/com/amazon/dataprepper/plugins/source/otellogs/OTelLogsSourceTest.java
data-prepper-plugins/otel-logs-source/src/test/java/com/amazon/dataprepper/plugins/source/otellogs/OtelLogsSourceConfigTests.java
data-prepper-plugins/otel-metrics-source/README.md
data-prepper-plugins/otel-metrics-source/src/main/java/org/opensearch/dataprepper/plugins/source/otelmetrics/OTelMetricsSource.java
data-prepper-plugins/otel-metrics-source/src/main/java/org/opensearch/dataprepper/plugins/source/otelmetrics/OTelMetricsSourceConfig.java
data-prepper-plugins/otel-metrics-source/src/test/java/org/opensearch/dataprepper/plugins/source/otelmetrics/OTelMetricsSourceTest.java
data-prepper-plugins/otel-metrics-source/src/test/java/org/opensearch/dataprepper/plugins/source/otelmetrics/OtelMetricsSourceConfigTests.java
data-prepper-plugins/otel-trace-source/README.md
data-prepper-plugins/otel-trace-source/src/main/java/org/opensearch/dataprepper/plugins/source/oteltrace/OTelTraceSource.java
data-prepper-plugins/otel-trace-source/src/main/java/org/opensearch/dataprepper/plugins/source/oteltrace/OTelTraceSourceConfig.java
data-prepper-plugins/otel-trace-source/src/test/java/org/opensearch/dataprepper/plugins/source/oteltrace/OTelTraceSourceTest.java
data-prepper-plugins/otel-trace-source/src/test/java/org/opensearch/dataprepper/plugins/source/oteltrace/OtelTraceSourceConfigTests.java

Adds path to oTel source. With this change the following are possible
gRPC, HTTP - `/opentelemetry.proto.collector.trace.v1.TraceService/Export`
HTTP - `<path>`
Partially resolves #2257 

Support for path in OTel sources

---

release/staging-resources-cdk/lib/GitHubAccessStack.ts
release/staging-resources-cdk/package-lock.json
release/staging-resources-cdk/package.json

Use the GitHub thumbprint as specified here: https://github.blog/changelog/2022-01-13-github-actions-update-on-oidc-based-deployments-to-aws/
Also updated the AWS CDK to the latest version.
Resolves #2343 

Explicitly set the GitHub Actions thumbprint in the release CDK stack

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/codec/PeerForwarderCodecAppConfig.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/codec/PeerForwarderCodecAppConfig_SerializationFilterIT.java

This PR replaces the `java.util.*` with known collections classes used commonly in Data Prepper.
None. This is a follow-on to #2311.

Replace the java.util.* in the ObjectInputFilter with tighter access

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/trace/DefaultLink.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/trace/DefaultLinkTest.java

If we run https://opentelemetry.io/docs/demo/docker-deployment/ as upstream service, there will be the following error log in data-prepper:
```
2023-03-03T19:52:36,429 [entry-pipeline-otel_trace-4-122] WARN  org.opensearch.dataprepper.plugins.source.oteltrace.OTelTraceGrpcService - Failed to parse request with error 'traceState cannot be an empty String'.
```
This is due to `traceState` is required in Link. This PR makes it not required

FIX: traceState not required in Link

---

data-prepper-plugins/otel-logs-source/src/main/java/com/amazon/dataprepper/plugins/source/otellogs/OTelLogsSource.java
data-prepper-plugins/otel-metrics-source/src/main/java/org/opensearch/dataprepper/plugins/source/otelmetrics/OTelMetricsSource.java
data-prepper-plugins/otel-trace-source/src/main/java/org/opensearch/dataprepper/plugins/source/oteltrace/OTelTraceSource.java

- Reverted some of the changes made in https://github.com/opensearch-project/data-prepper/pull/2297 which is passing  null Plugin Name
resolves #2368 

Fix: Fixed IllegalArgumentException in PluginMetrics 

---

build.gradle

Removed old constraints on Netty which were resulting in pulling in older version of Netty. Our dependencies (Armeria and AWS SDK Java client) are pulling in newer versions so these old configurations are not necessary anymore.
Sample of dependencies:
```
./gradlew -p data-prepper-main dependencies | grep netty | head -n 10
|    +--- software.amazon.awssdk:netty-nio-client:2.17.264 -> 2.17.271 (c)
|    |    |    \--- software.amazon.awssdk:netty-nio-client:2.17.264 -> 2.17.271
|    |    |         +--- io.netty:netty-codec-http:4.1.77.Final -> 4.1.79.Final
|    |    |         |    +--- io.netty:netty-common:4.1.79.Final
|    |    |         |    +--- io.netty:netty-buffer:4.1.79.Final
|    |    |         |    |    \--- io.netty:netty-common:4.1.79.Final
|    |    |         |    +--- …
```

Use Netty version supplied by dependencies

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/codec/PeerForwarderCodecAppConfig.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/codec/PeerForwarderCodecAppConfig_SerializationFilterIT.java

The wildcard on the Jackson `com.fasterxml.jackson.databind.node` package was overly broad. There are really only two classes that are likely to be used: `NodeSerialization` and `ObjectNode`. I also added support for `ArrayNode` in case some Event objects have an array as the top-level.
This PR removes those wildcards to use only the specific known classes. Additionally, this adds testing with different Event data structures to ensure that different sub-nodes work.
Part of the reason this works is that `JsonNode` (including `ObjectNode` and `ArrayNode`) actually serialize to JSON internally. So double, int, boolean, string are all in JSON.
N/A
For more information on …

Updated the Java serialization allowlist to have specific classes for JsonNode

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/BaseEventBuilder.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/Event.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/EventBuilder.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/EventFactory.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/EventHandle.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/JacksonEvent.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/LogEventBuilder.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/event/JacksonEventTest.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/event/DefaultBaseEventBuilder.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/event/DefaultEventBuilder.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/event/DefaultEventFactory.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/event/DefaultEventHandle.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/event/DefaultLogEventBuilder.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/event/DefaultBaseEventBuilderTests.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/event/DefaultEventBuilderTests.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/event/DefaultEventFactoryTests.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/event/DefaultLogEventBuilderTests.java

This change adds new mechanism to create events from event factory and the necessary framework.
The framework components
1. Event Handle - This will be used for end-to-end acknowledgement of each individual events
2. BaseEventBuilder - Base Event Builder interface that allows setting event metadata and data that can be used to create different types of event
The framework components are implemented as interfaces in the `data-prepper-api` and the corresponding implementations in the `data-prepper-core`
For more information on following Developer Certificate of Origin and signing …

Add Event Factory and generic event builder infrastructure

---

docs/developer_guide.md

Updated part of the developer guide to show users that Data Prepper documentation should be part of the main opensearch.org documentation.
N/A

Developer Guide links Data Prepper documentation

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/acknowledgements/AcknowledgementSet.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/acknowledgements/AcknowledgementSetManager.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/acknowledgements/AcknowledgementSetMonitor.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/acknowledgements/DefaultAcknowledgementSet.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/acknowledgements/DefaultAcknowledgementSetManager.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/event/DefaultEventBuilder.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/event/DefaultEventHandle.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/acknowledgements/AcknowledgementSetMonitorTests.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/acknowledgements/DefaultAcknowledgementSetManagerTests.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/acknowledgements/DefaultAcknowledgementSetTests.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/event/DefaultEventHandleTests.java

Add acknowledgment framework.
This change includes -
1. AcknowledgementSetManager, an instance of which is created to be used by all components of DataPrepper
2. It is used to create an acknowledgement set by a source plugin
3. The source then adds a batch of events to the acknowledgement set and expects the callback provided to be invoked when all the events in the batch are acknowledged
4. The AcknowledgementSetManager creates a AcknowledgementSetMonitor thread which monitors all acknowledgement sets for completion (happens when all events in an acknowledgement set acknowledge their completion) or expiration (when at least one of the events in an acknowledgement set does not acknowledge their completion before the expected expiration time or if the callback has not completed by the …

Add acknowledgementSet and acknowledgementSetManager - End-to-End Ack Support

---

data-prepper-plugins/opensearch/src/integrationTest/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSinkIT.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSink.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSinkConfiguration.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/RetryConfiguration.java

Adds support for providing a plugin loader to OpenSearch sink. This will be used once #2392 is merged.
part of #2298

updating opensearch sink constructor to support loading dlq plugins

---

data-prepper-plugins/grok-processor/README.md

Replace broken grok debugger link
Resolves #2423 

MAINT: replace grok debugger in README

---

data-prepper-plugins/s3-source/README.md
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3ObjectWorker.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/SqsWorker.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/SqsWorkerTest.java

This adds a new metric for when SQS messages fail to delete - `sqsMessagesDeleteFailed`. Additionally, it also detects failed message deletes from successful API calls.
Also adds an `INFO` log when reading from S3 so that users can better observe and debug their pipeline.
Resolves #2449

Count SQS message delete failures in the S3 source

---

data-prepper-plugins/failures-common/src/main/java/org/opensearch/dataprepper/plugins/dlq/README.md
data-prepper-plugins/failures-common/src/main/java/org/opensearch/dataprepper/plugins/dlq/s3/KeyPathGenerator.java
data-prepper-plugins/failures-common/src/main/java/org/opensearch/dataprepper/plugins/dlq/s3/S3DlqWriter.java
data-prepper-plugins/failures-common/src/test/java/org/opensearch/dataprepper/plugins/dlq/s3/KeyPathGeneratorTest.java
data-prepper-plugins/opensearch/README.md
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSink.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/AbstractIndexManager.java

1. adding data-time patterns to key-path-prefix and creating readme for s3 dlq.
2. adding detailed README for S3 DLQ Plugin
- resolves #2298

adding data-time patterns to key-path-prefix and creating readme for S3 DLQ

---

data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/ListToMapProcessor.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/ListToMapProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/test/java/org/opensearch/dataprepper/plugins/processor/mutateevent/ListToMapProcessorTest.java

This PR adds a new `list_to_map` processor that converts an array of objects in an event to a map.
Resolves #2410 

Add list_to_map processor

---

data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkRetryStrategy.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3ClientBuilderFactory.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3ObjectRequest.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3SelectObjectWorker.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3SelectResponseHandlerFactory.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3Source.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/S3ObjectRequestTest.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/S3SelectObjectWorkerTest.java

* This change retries the flushing of the buffer for the S3Source when it receives a TimeoutException from the buffer
* Refactors the `S3SelectWorkerObjectTest` 

Retry flushing of buffer on buffer TimeoutException

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/JacksonEvent.java
data-prepper-plugins/mutate-event-processors/README.md
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/AddEntryProcessor.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/AddEntryProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/CopyValueProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/RenameKeyProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/test/java/org/opensearch/dataprepper/plugins/processor/mutateevent/AddEntryProcessorTests.java

Add an option in `add_entries` processor to add entries with format strings that can inject other event keys.
A sample config is like this
```
processor:
- add_entries:
entries:
- key: "date-time"
format: "${date} ${time}"
```
If both `format` and `value` options are provided, it takes `format` over `value`.
Resolves #2424 

Add format string option to add_entries processor

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/meter/EMFLoggingMeterRegistry.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/meter/EMFLoggingMeterRegistryTest.java

The current implementation of EMFLoggingMeterRegistry leads to occasional missing data points in metrics when using fluent-bit as sidecar to receive metrics through TCP and output to cloudwatch. See pic:
This PR mitigates the issue by batching metrics in the snapshot that shares the same dimensions (tags).
with the change in-place the missing data issue is at-least mitigated:
#2469 

ENH: batching metrics with same tags in EMFLoggingMeterRegistry

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/EventHandle.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/failures/DlqObject.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/event/JacksonEventTest.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/failures/DlqObjectTest.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/event/DefaultEventHandle.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/event/DefaultEventHandleTests.java
data-prepper-plugins/opensearch/README.md
data-prepper-plugins/opensearch/src/integrationTest/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSinkIT.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkOperationWithHandle.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkOperationWrapper.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkRetryStrategy.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSink.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/bulk/JavaClientAccumulatingBulkRequest.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/dlq/FailedBulkOperation.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/dlq/FailedBulkOperationConverter.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/dlq/FailedDlqData.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkOperationWithHandleTests.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkOperationWrapperTests.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkRetryStrategyTests.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/bulk/JavaClientAccumulatingBulkRequestTest.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/dlq/FailedBulkOperationConverterTest.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/dlq/FailedBulkOperationTest.java

This change adds support for sending end-to-end acknowledgements in the OpenSearchSink.
Each event's event handle is captured along with the BulkOperation created for the event. When the BulkOperation is successfully sent to OpenSearchSink or Successfully written to configured DLQ, then a positive acknowledgement is sent by invoking `acknowledgementSetManager.releaseEventReference(handle, true)`. If it fails to do either of them, then negative acknowledgement is sent by invoking `acknowledgementSetManager.releaseEventReference(handle, false)`.
The `BulkOperation` used to keep track of the individual requests to OpenSearch is now wrapped in a new Object `BulkOperationWithHandle` which contains the original bulkOperation and the new event handle that keeps track of the specific event's …

OpenSearchSink: add support for sending end-to-end acknowledgements

---

examples/trace-analytics-sample-app/sample-app/requirements.txt

The python protobuf library of Trace Analytics Sample App with a bug. So that the sample app can not be started.
Bump the version of it to fix this issue.
#2477

Fix cannot start databaseService.py with Trace Analytics Sample App (#2477)

---

data-prepper-plugins/s3-source/src/integrationTest/java/org/opensearch/dataprepper/plugins/source/S3ObjectWorkerIT.java
data-prepper-plugins/s3-source/src/integrationTest/java/org/opensearch/dataprepper/plugins/source/SqsWorkerIT.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3ObjectHandler.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3ObjectWorker.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3SelectObjectWorker.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3Service.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3Source.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3SourceConfig.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/SqsService.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/SqsWorker.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/S3ObjectWorkerTest.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/S3SelectObjectWorkerTest.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/S3SourceConfigTest.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/S3SourceTest.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/SqsWorkerTest.java

Add End to End acknowledgement support for S3 source.
This change includes - 
1. Adding an optional configuration parameter `end_to_end_acknowledgements: true` for s3 source to enable end to end acknowledgements
2. Creates an acknowledgement set and adds the created records to the set so that when all the records are pushed to the sinks, the callback can be invoked.
3. Modifies S3 codecs to use EventFactory to creates events. …

Add End to End acknowledgement support for S3 source

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/acknowledgements/AcknowledgementAppConfig.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/acknowledgements/AcknowledgementSetMonitor.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/acknowledgements/AcknowledgementSetMonitorThread.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/acknowledgements/CallbackTheadFactory.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/acknowledgements/DefaultAcknowledgementSet.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/acknowledgements/DefaultAcknowledgementSetManager.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/acknowledgements/AcknowledgementSetMonitorThreadTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/acknowledgements/CallbackTheadFactoryTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/acknowledgements/DefaultAcknowledgementSetManagerTests.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/acknowledgements/DefaultAcknowledgementSetTests.java

In recent testing I found that Data Prepper was not shutting down properly on errors. It turns out that the end-to-end acknowledgements were preventing this. The scheduled thread pool was creating a new thread regularly and increasing the overall thread count. Additionally, these are user threads so they are not allowing Data Prepper to close.
This PR includes a few changes:
* Split the threads for end-to-end acknowledgement callbacks from the thread for monitoring.
* Name the threads to help with debugging.
* Make the monitoring thread a daemon. (I did not do the same with the callback threads as these are processing data).
* Create the `ExecutorService` as a Spring Bean in the application context. Spring should call `shutdown()` on this automatically.
* Use Awaitility when waiting in …

Fixes an issue where end-to-end acknowledgements prevent shutdown

---

data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSink.java

Fix warning message when Open Search Sink fails to initialize

Fix warning message when Open Search Sink fails to initialize

---

data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/BufferAccumulator.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3SelectObjectWorker.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/BufferAccumulatorTest.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/S3SelectObjectWorkerTest.java

Moves the backoff and retry logic to the BufferAccumulator so both of the S3 sources can take advantage of it.

Move backoff strategy to BufferAccumulator

---

data-prepper-plugins/common/src/main/java/org/opensearch/dataprepper/plugins/sink/FileSink.java
data-prepper-plugins/common/src/main/java/org/opensearch/dataprepper/plugins/sink/FileSinkConfig.java
data-prepper-plugins/common/src/test/java/org/opensearch/dataprepper/plugins/sink/FileSinkTests.java

Removes an unnecessary call to initialize() in the FileSink constructor. Updates FileSink to use a FileSinkConfig. Updates FileSink tests.
N/A

FileSink updates: Remove call to initialize(), adds FileSinkConfig, test updates

---

data-prepper-plugins/anomaly-detector-processor/build.gradle

Updated maven repository version for RCF. It has couple of fixes that are needed for proper functioning of anomaly detector processor.

Update RCF  maven repository to latest

---

data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/plugins/InMemoryConfig.java
data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/plugins/InMemorySource.java
data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/acknowledgements/one-pipeline-ack-expiry-test.yaml
data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/acknowledgements/one-pipeline-three-sinks.yaml
data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/acknowledgements/simple-test.yaml
data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/acknowledgements/three-pipeline-route-test.yaml
data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/acknowledgements/three-pipelines-test-multi-sink.yaml
data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/acknowledgements/three-pipelines-test.yaml
data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/acknowledgements/two-parallel-pipelines-test.yaml
data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/acknowledgements/two-pipelines-test.yaml
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSink.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3Source.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3SourceConfig.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/SqsWorker.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/S3SourceConfigTest.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/SqsWorkerTest.java

Change `end_to_end_acknowledgements` option in sources to `acknowledgements` and also support alias `acknowledgments`

end_to_end_acknowledgements option name change

---

data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/codec/CsvCodec.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/codec/CsvCodecTest.java

This propagates exceptions from the CSV codec to provide clearer issues to users when CSV fails to process.
Resolves #2512

Change the behavior of the CSV codec in the S3 source to fail fast

---

data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/test/framework/DataPrepperTestRunner.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/AbstractContextManager.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/DataPrepper.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/DataPrepperShutdownListener.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/Pipeline.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/PipelineObserver.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/PipelinesProvider.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/server/ListPipelinesHandler.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/server/ShutdownHandler.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/server/config/DataPrepperServerConfiguration.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/AbstractContextManagerTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/DataPrepperTests.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/PipelineTests.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/server/ListPipelinesHandlerTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/server/ShutdownHandlerTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/server/config/DataPrepperServerConfigurationTest.java
data-prepper-main/src/main/java/org/opensearch/dataprepper/ContextManager.java

When a Data Prepper pipeline shuts down, Data Prepper continues to run. If this is the last pipeline, Data Prepper will remain running.
This PR shuts down Data Prepper when the last pipeline fails.
I plan to follow this on with a configuration to allow Data Prepper to fail if any pipeline has shutdown.
Resolves #2441

Shut down Data Prepper after all pipelines have shutdown.

---

data-prepper-plugins/failures-common/src/main/java/org/opensearch/dataprepper/plugins/dlq/README.md
data-prepper-plugins/failures-common/src/main/java/org/opensearch/dataprepper/plugins/dlq/s3/S3DlqWriter.java
data-prepper-plugins/failures-common/src/test/java/org/opensearch/dataprepper/plugins/dlq/s3/S3DlqWriterTest.java

The following PR addresses a few issues with the DLQ. 1) it provides a json file extension for the data stored in S3. 2) it creates a higher level object to wrap all failed events. This will give us flexibility to add other metadata in the future. 3) Improves readme configuration details and corrects an error in the documentation.
N/A

adding wrapper dlq object, dlq file extensions and improving dlq README

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/Event.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/JacksonEvent.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/event/JacksonEventTest.java
data-prepper-plugins/opensearch/README.md
data-prepper-plugins/opensearch/src/integrationTest/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSinkIT.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSink.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/DocumentBuilder.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/IndexConfiguration.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/DocumentBuilderTest.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/IndexConfigurationTests.java

Adding support for a `document_root_key`. This would allow users to specify the object written to the document in the opensearch sink
#2511

[2511] adding support for document_root_key

---

data-prepper-plugins/failures-common/src/main/java/org/opensearch/dataprepper/plugins/dlq/DlqProvider.java
data-prepper-plugins/failures-common/src/main/java/org/opensearch/dataprepper/plugins/dlq/s3/S3DlqProvider.java
data-prepper-plugins/failures-common/src/test/java/org/opensearch/dataprepper/plugins/dlq/s3/S3DlqProviderTest.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSink.java

S3 DLQ metrics were appearing in the wrong scope. This follow change requires the scope be passed in as part of fetching the dlq writer. I added some unit tests and verified the format is correct by checking the metrics on `/metrics/sys`. For example:
```
apache_log_pipeline_opensearch_s3_dlqS3RequestFailed_total{serviceName="dataprepper",} 0.0
```
- none

addressing metrics publishing bug for DLQ

---

data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/plugins/InMemoryConfig.java
data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/acknowledgements/one-pipeline-ack-expiry-test.yaml
data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/acknowledgements/one-pipeline-three-sinks.yaml
data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/acknowledgements/three-pipeline-route-test.yaml
data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/acknowledgements/three-pipelines-test-multi-sink.yaml
data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/acknowledgements/three-pipelines-test.yaml
data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/acknowledgements/two-parallel-pipelines-test.yaml
data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/acknowledgements/two-pipelines-test.yaml
data-prepper-plugins/s3-source/README.md
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3SourceConfig.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/S3SourceConfigTest.java

Document acknowledgements option to s3 source. Added `acknowledgements` option to s3 source README file.

Document acknowledgements option to s3 source

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/DataPrepper.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/parser/model/DataPrepperConfiguration.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/PipelineShutdownAppConfig.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/PipelineShutdownOption.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/DataPrepperTests.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/parser/model/DataPrepperConfigurationTests.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/PipelineShutdownAppConfigTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/PipelineShutdownOptionTest.java
data-prepper-core/src/test/resources/valid_data_prepper_config_with_pipeline_shutdown.yml

This PR makes two changes to Data Prepper:
1. By default, if any pipeline fails, Data Prepper shuts down.
2. Adds a new configuration in `data-prepper-config.yaml` to allow Data Prepper to run until the last pipeline fails.
Resolves #2441

Configurable pipeline shutdown behavior

---

data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3SelectObjectWorker.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3Source.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/S3SelectObjectWorkerTest.java

ScanRange is only supported for some S3 select queries. This PR branches based on supported vs not supported.
Functionally tested the following configurations:
JSON document -> no batching
JSON lines -> yes batching
JSON document GZIP -> no batching
JSON lines GZIP -> no batching
JSON document BZIP2 -> no batching
JSON lines BZIP2 -> no batching
CSV no quote escape no comment -> yes batching
CSV quote, no comment -> no batching
CSV no quote, comment -> no batching
CSV quote, comment -> no batching
CSV no quote escape no comment GZIP -> no batching
CSV no quote escape no comment BZIP2 -> no batching 
Parquet -> yes batching …

Adds branching on supported configurations for ScanRange

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/configuration/PipelineModel.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/configuration/PipelinesDataFlowModelTest.java
data-prepper-api/src/test/resources/pipelines_data_flow_routes.yaml
docs/overview.md

- Add `routes` as an alias to `route` 
resolves https://github.com/opensearch-project/data-prepper/issues/2520

Added routes as an alias to route

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/acknowledgements/DefaultAcknowledgementSet.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/acknowledgements/DefaultAcknowledgementSetManager.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/acknowledgements/DefaultAcknowledgementSetMetrics.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/acknowledgements/DefaultAcknowledgementSetMetricsTests.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/acknowledgements/DefaultAcknowledgementSetTests.java

Adds Metrics to end-to-end acknowledgement core framework
The following metrics are added
1. Number of acknowledgement sets created
2. Number of acknowledgement sets completed successfully
3. Number of acknowledgement sets expired
4. Number of invalid acquires done
5. Number of invalid releases done

Add Metrics to end-to-end acknowledgement core framework

---

data-prepper-plugins/opensearch/README.md
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/ConnectionConfiguration.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/IndexConfiguration.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/ConnectionConfigurationTests.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/IndexConfigurationTests.java

- Removed `aws_serverless` option and serverless can only be enabled by `aws` option.
- Updated documentation

Opensearch serverless change

---

build.gradle
data-prepper-plugins/s3-source/build.gradle
settings.gradle

Update dependency versions to fix CVEs. See details below:
- Fixes #2492 through spring version `5.3.27`
- Fixes #2418 through `wiremock:3.0.0-beta-7`, which uses `json-smart 2.4.10`
- Fixes #1428 through `httpclient:4.5.14`

Update dependency versions to fix CVEs

---

.github/CODEOWNERS
MAINTAINERS.md

Baselines the MAINTAINERS.md and CODEOWNERS files.
Adds the Emeritus section with previous maintainers.
Resolves #2275

Baselines the MAINTAINERS.md and CODEOWNERS files per #2275

---

data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSink.java

In the cases where the OpenSearch sink fails to initialize, we log that it failed to start and then throw a RuntimeException, which is not as easy to track down in the logs since it bubbles up to "No pipeline available for execution".
This change logs the full error with the "Failed to initialize OpenSearch sink" error log

Log full errors when the OpenSearch sink fails to start

---

data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/SqsService.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/SqsWorker.java

When this thread throws errors, it will repeat quite a bit which results in somewhat excessive AWS calls and excess logging.
This put the retry in the range of 20 seconds to 5 minutes.
I also added an INFO log about the sleep. Since the delay can be a while I think this will help anybody monitoring the logs.
Fixes #2568.

Increase the backoff delays in the S3 source polling thread

---

examples/log-ingestion/README.md

Updates the log-ingestion example:
* Explicit use of Data Prepper 2.x.
* Use `${PWD}` to support copy-and-paste for many users.
* Remove Data Prepper 1.x entirely.
N/A

Updates to the log-ingestion example

---

data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkRetryStrategy.java

This change is meant to prevent a NullPointerException from occurring when the value pulled from the `retryCountMap` is null

Add null check for bulkRetryCountMap in opensearch sink to prevent NullPointerException

---

data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/integration/PipelinesWithAcksIT.java
data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/plugins/InMemorySource.java

Increase timeout values in in-memory source PipelinesWithAcksIT to fix occasional test failures
Resolves #2551 
#2551 

Increase timeout values in in-memory source PipelinesWithAcksIT to fix occasional test failures

---

.github/CODEOWNERS
MAINTAINERS.md

Adding @kkondaka as a maintainer as voted upon by the existing Data Prepper maintainers.
He has contributed [49 PRs](https://github.com/opensearch-project/data-prepper/pulls?q=is:pr+is:closed+author:kkondaka). Some of these include significant new features.
* [End-to-end acknowledgements](https://github.com/opensearch-project/data-prepper/issues/2496#issuecomment-1509169592) for the S3 source.
* [Anomaly detector](https://github.com/opensearch-project/data-prepper/pull/2058)
* [Dynamic Index Name in OpenSearch sink](https://github.com/opensearch-project/data-prepper/pull/1999)
* [Type conversion / cast processor](https://github.com/opensearch-project/data-prepper/pull/2020)
* [Fix PipelineConnector to duplicate events](https://github.com/opensearch-project/data-prepper/pull/1897)
By …

Adding Krishna Kondaka (kkondaka) as a maintainer

---

data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkRetryStrategy.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSink.java

Log clear messages when OpenSearch Sink fails to push. Modify retries to be iterative instead of recursive.
Logs failure messages after every 5 retries and also after last retry.
Modified retry logic to be iterative instead of recursive.
Resolves #2597 
#2597 

Log clear messages when OpenSearch Sink fails to push. Modify retries to be iterative instead of recursive

---

data-prepper-plugins/avro-codecs/build.gradle

Update json-java to address CVE-2022-45688
Fixes #2615 

Update json-java to address CVE-2022-45688

---

examples/trace-analytics-sample-app/sample-app/analytics-service/build.gradle

This updates the example Spring Boot application.
* Spring Boot 2.7.11 from 2.7.3
* Spring Dependency plugin 1.1.0 from 1.0.9
* Java 11 from Java 8
This should resolve CVE-2023-20863, CVE-2022-45143.
Some dependency updates:
```
\--- org.springframework.boot:spring-boot-starter-web -> 2.7.11
+--- org.springframework.boot:spring-boot-starter:2.7.11
|    +--- org.springframework.boot:spring-boot:2.7.11
|    |    +--- org.springframework:spring-core:5.3.27
```
```
+--- org.springframework.boot:spring-boot-starter-tomcat:2.7.11
|    +--- jakarta.annotation:jakarta.annotation-api:1.3.5
|    +--- org.apache.tomcat.embed:tomcat-embed-core:9.0.74
|    +--- org.apache.tomcat.embed:tomcat-embed-el:9.0.74
|    \--- org.apache.tomcat.embed:tomcat-embed-websocket:9.0.74
|         \--- …
```

 Updates the example Spring Boot application to Spring Boot 2.7.11

---

data-prepper-plugins/s3-source/build.gradle

Require using Jetty 11.0.14 in the `s3-source` plugin.
Update to use wiremock 3.0.0-beta-8 in the `s3-source` plugin.
Jetty 11.0.4 resolves CVE-2023-26048.
Relevant dependency output:
```
+--- com.github.tomakehurst:wiremock:3.0.0-beta-8
|    +--- org.slf4j:slf4j-api:1.7.36 -> 2.0.7
|    +--- org.eclipse.jetty:jetty-bom:11.0.12 -> 11.0.14
|    |    +--- org.eclipse.jetty:jetty-alpn-client:11.0.14 (c)
|    |    +--- org.eclipse.jetty:jetty-alpn-java-client:11.0.14 (c)
|    |    +--- org.eclipse.jetty:jetty-alpn-java-server:11.0.14 (c)
|    |    +--- org.eclipse.jetty:jetty-alpn-server:11.0.14 (c)
|    |    +--- org.eclipse.jetty.http2:http2-server:11.0.14 (c)
|    |    +--- org.eclipse.jetty:jetty-proxy:11.0.14 (c)
|    |    +--- org.eclipse.jetty:jetty-server:11.0.14 (c)
|    |    +--- …
```

Update to use Jetty 11.0.14 in the s3-source project to fix 

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/DefaultEventMetadata.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/Event.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/EventMetadata.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/JacksonEvent.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/event/DefaultEventMetadataTest.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/event/JacksonEventTest.java

Added support to add tags to events.
Tags can be added at the time of creation of a event or after creating it. The tags are added to event meta data as per the discussion in issue #629.
Resolves #629 
#629 

Tagging Events in Data Prepper. Issue #629

---

data-prepper-plugins/s3-source/src/integrationTest/java/org/opensearch/dataprepper/plugins/source/SqsWorkerIT.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3EventMessageParser.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3EventNotification.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/SqsService.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/SqsWorker.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/S3EventMessageParserTest.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/SqsWorkerTest.java

Adds a new class for parsing for S3 Event notifications. Detect if the message was wrapped by SNS to SQS by checking for the presence of a `Message` key. Then parse that as a string.
Resolves #2604 

Support reading S3 Event messages from SNS fan-out

---

examples/trace-analytics-sample-app/sample-app/analytics-service/build.gradle

Fixes CVE-2022-1471 and CVE-2022-41854 in the Trace Analytics sample app by using Snakeyaml 2.0.
For some reason, using a Gradle dependency constraint was not working. It may be due to the way Spring Boot chooses its dependency versions. But, changing the dependency resolution did fix this.
Verification:
```
/gradlew dependencies | grep snakeyaml
```
```
|    \--- org.yaml:snakeyaml:1.30 -> 2.0
|    \--- org.yaml:snakeyaml:1.30 -> 2.0
|    \--- org.yaml:snakeyaml:1.30 -> 2.0
|    |    \--- org.yaml:snakeyaml:1.30 -> 2.0
|    |    \--- org.yaml:snakeyaml:1.30 -> 2.0
```
N/A
For more information on following Developer Certificate of Origin and signing off your commits, please …

Update to Snakeyaml 2.0 in the Trace Analytics sample app.

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/Event.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/JacksonEvent.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/event/JacksonEventTest.java

Change JsonStringBuilder in JacksonEvent to be non static for ease-of-use.
Changes 
`JacksonEvent.jsonBuilder().withEvent(event).includeTags("tags").toJsonString()`
to
`event.jsonBuilder().includeTags("tags").toJsonString()`
Resolves #2665 
Resolves #2665 

Change JsonStringBuilder in JacksonEvent to be non static for ease-of-use

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/DefaultEventMetadata.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/EventMetadata.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/event/DefaultEventMetadataTest.java
data-prepper-expression/src/main/java/org/opensearch/dataprepper/expression/HasTagsExpressionFunction.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/ConditionalExpressionEvaluatorIT.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/HasTagsExpressionFunctionTest.java
docs/expression_syntax.md

Add hasTags() function to dataprepper expressions.
Data Prepper expressions can now check about presence of tags in the event.
For example an expression may look like 
`hasTag("tag1") and /status_code == 200` 
which returns true if the event has a tag with name "tag1" and status_code value is 200.
Resolves #629 
#629 

Add hasTags() function to dataprepper expressions

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/source/SourceCoordinationStore.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/source/coordinator/SourceCoordinator.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/source/coordinator/exceptions/UninitializedSourceCoordinatorException.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/sourcecoordination/LeaseBasedSourceCoordinator.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/sourcecoordination/SourceCoordinatorFactory.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/sourcecoordination/LeaseBasedSourceCoordinatorTest.java
data-prepper-plugins/dynamodb-source-coordination-store/build.gradle
data-prepper-plugins/dynamodb-source-coordination-store/src/main/java/org/opensearch/dataprepper/plugins/sourcecoordinator/dynamodb/DdbClientCustomRetryCondition.java
data-prepper-plugins/dynamodb-source-coordination-store/src/main/java/org/opensearch/dataprepper/plugins/sourcecoordinator/dynamodb/DynamoDbClientFactory.java
data-prepper-plugins/dynamodb-source-coordination-store/src/main/java/org/opensearch/dataprepper/plugins/sourcecoordinator/dynamodb/DynamoDbClientWrapper.java
data-prepper-plugins/dynamodb-source-coordination-store/src/main/java/org/opensearch/dataprepper/plugins/sourcecoordinator/dynamodb/DynamoDbSourceCoordinationStore.java
data-prepper-plugins/dynamodb-source-coordination-store/src/main/java/org/opensearch/dataprepper/plugins/sourcecoordinator/dynamodb/DynamoDbSourcePartitionItem.java
data-prepper-plugins/dynamodb-source-coordination-store/src/main/java/org/opensearch/dataprepper/plugins/sourcecoordinator/dynamodb/DynamoStoreSettings.java
data-prepper-plugins/dynamodb-source-coordination-store/src/test/java/org/opensearch/dataprepper/plugins/sourcecoordinator/dynamodb/DdbClientCustomRetryConditionTest.java
data-prepper-plugins/dynamodb-source-coordination-store/src/test/java/org/opensearch/dataprepper/plugins/sourcecoordinator/dynamodb/DynamoDbClientFactoryTest.java
data-prepper-plugins/dynamodb-source-coordination-store/src/test/java/org/opensearch/dataprepper/plugins/sourcecoordinator/dynamodb/DynamoDbClientWrapperTest.java
data-prepper-plugins/dynamodb-source-coordination-store/src/test/java/org/opensearch/dataprepper/plugins/sourcecoordinator/dynamodb/DynamoDbSourceCoordinationStoreTest.java

This change implements the dynamo db source coordination store, which can be configured in the data-prepper-config.yaml with the following config
```
source_coordination:
store:
dynamodb:
table_name: "TestSourceCoordinationDemo"
sts_role_arn: "arn:aws:iam::123456789012:role/source-coordination-ddb-role"
```
Related to #2412 

Implement dynamo db source coordination store

---

data-prepper-expression/src/main/antlr/DataPrepperExpression.g4
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/ConditionalExpressionEvaluatorIT.java

Currently, the function expression allows spaces between 1st and 2nd arguments but not between 2nd and 3rd arguments or beyond. For example, `hasTags("tag1", "tag2")` would be OK, but `hasTags("tag1", "tag2", "tag3")` would result in the follow error:
```
line 1:0 token recognition error at: 'hasTags("tag1", "tag2",'
line 1:30 extraneous input ')' expecting <EOF>
2023-05-12T16:38:41,571 [...] ERROR org.opensearch.dataprepper.pipeline.ProcessWorker - Encountered exception during pipeline simple-pipeline processing
org.opensearch.dataprepper.expression.ExpressionEvaluationException: Unable to evaluate statement "hasTags("tag1", "tag2", "tag3")"
...
```
This CR tries to fix the issue by adding spaces in `FunctionArgs` rule.
N/A
By submitting this pull request, I confirm that my contribution …

Fix spaces between function args

---

data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkRetryStrategy.java

There is a log line in the opensearch sink that was introduced from #2643 that used a log line from the S3 Source [SQS Worker](https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/SqsWorker.java#L163)
None

addressing copy and paste error

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/sourcecoordination/LeaseBasedSourceCoordinator.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/sourcecoordination/LeaseBasedSourceCoordinatorTest.java
data-prepper-plugins/s3-source/src/integrationTest/java/org/opensearch/dataprepper/plugins/source/S3ScanObjectWorkerIT.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3ObjectHandler.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3ScanPartitionCreationSupplier.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3ScanService.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3Source.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3SourceProgressState.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/ScanObjectWorker.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/S3ScanObjectWorkerTest.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/S3ScanPartitionCreationSupplierTest.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/S3ScanServiceTest.java

This change implements S3 scan using the SourceCoordinator. This is the simplest use of the source coordinator, where it is used to manage and assign objects to work on getting objects with `getNextPartition`, and marks partitions as processed with `completePartition`.
The next PR will wire the source coordinator in for use with `S3ObjectHandler`, which is necessary to make calls to `saveState` for processing large objects. With the current implementation in this PR (without calls to `saveState`),duplicate processing can occur for objects that take greater than 10 minutes to process, since the `partitionOwnershipTimeout` will expire after 10 minutes without calls to `saveState` (which will renew the partition ownership timeout).
This change was tested in both single and multi-node …

S3 scan with source coordination

---

data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/S3Sink.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/accumulator/BufferTypeOptions.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/accumulator/LocalFileBuffer.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/accumulator/LocalFileBufferFactory.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/accumulator/LocalFileBufferFactoryTest.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/accumulator/LocalFileBufferTest.java

- Implementation of s3-sink local-file buffer functionality.
GitHub-issue #1048 

Github-issue#1048 : s3-sink with local-file buffer implementation.

---

data-prepper-plugins/armeria-common/src/main/java/org/opensearch/dataprepper/compression/CompressionOption.java
data-prepper-plugins/armeria-common/src/test/java/org/opensearch/dataprepper/compression/CompressionOptionTest.java
data-prepper-plugins/http-source/README.md
data-prepper-plugins/http-source/src/main/java/org/opensearch/dataprepper/plugins/source/loghttp/HTTPSource.java
data-prepper-plugins/http-source/src/main/java/org/opensearch/dataprepper/plugins/source/loghttp/HTTPSourceConfig.java
data-prepper-plugins/http-source/src/test/java/org/opensearch/dataprepper/plugins/source/loghttp/HTTPSourceConfigTest.java
data-prepper-plugins/http-source/src/test/java/org/opensearch/dataprepper/plugins/source/loghttp/HTTPSourceTest.java
data-prepper-plugins/otel-logs-source/README.md
data-prepper-plugins/otel-logs-source/src/main/java/org/opensearch/dataprepper/plugins/source/otellogs/OTelLogsSource.java
data-prepper-plugins/otel-logs-source/src/main/java/org/opensearch/dataprepper/plugins/source/otellogs/OTelLogsSourceConfig.java
data-prepper-plugins/otel-logs-source/src/test/java/org/opensearch/dataprepper/plugins/source/otellogs/OTelLogsSourceTest.java
data-prepper-plugins/otel-logs-source/src/test/java/org/opensearch/dataprepper/plugins/source/otellogs/OtelLogsSourceConfigTests.java
data-prepper-plugins/otel-metrics-source/README.md
data-prepper-plugins/otel-metrics-source/src/main/java/org/opensearch/dataprepper/plugins/source/otelmetrics/OTelMetricsSource.java
data-prepper-plugins/otel-metrics-source/src/main/java/org/opensearch/dataprepper/plugins/source/otelmetrics/OTelMetricsSourceConfig.java
data-prepper-plugins/otel-metrics-source/src/test/java/org/opensearch/dataprepper/plugins/source/otelmetrics/OTelMetricsSourceTest.java
data-prepper-plugins/otel-metrics-source/src/test/java/org/opensearch/dataprepper/plugins/source/otelmetrics/OtelMetricsSourceConfigTests.java
data-prepper-plugins/otel-trace-source/README.md
data-prepper-plugins/otel-trace-source/src/main/java/org/opensearch/dataprepper/plugins/source/oteltrace/OTelTraceSource.java
data-prepper-plugins/otel-trace-source/src/main/java/org/opensearch/dataprepper/plugins/source/oteltrace/OTelTraceSourceConfig.java
data-prepper-plugins/otel-trace-source/src/test/java/org/opensearch/dataprepper/plugins/source/oteltrace/OTelTraceSourceTest.java
data-prepper-plugins/otel-trace-source/src/test/java/org/opensearch/dataprepper/plugins/source/oteltrace/OtelTraceSourceConfigTests.java

This PR supports gzip as compression type in push based sources
* http
* otel-trace
* otel-logs
* otel-metrics
Resolves #1399 
Resolves #1176 

ENH: support gzip compression for armeria sources

---

data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/BufferAccumulator.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/BufferAccumulatorTest.java

The BufferAccumulator has a subtle bug when an exception is thrown during the buffer write:
1. Buffer accumulator reaches accumulation limit on `add` call and attempts to flush
2. An exception is thrown when writing to the buffer during the flush (either CB tripped or buffer full)
3. The flush fails and the exception is [swallowed](https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3ObjectWorker.java#L99-L101)
4. The next iteration of `add` now has more records accumulated than the limit so the == evaluates to false
5. The buffer accumulator continues accepting data until OOM or until the object is fully processed and [flush is manually …

Add backoff when flushing on add and change condition to >=

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/DefaultEventMetadata.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/EventMetadata.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/event/DefaultEventMetadataTest.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/event/DefaultBaseEventBuilder.java
data-prepper-plugins/mutate-event-processors/README.md
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/AddEntryProcessor.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/AddEntryProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/test/java/org/opensearch/dataprepper/plugins/processor/mutateevent/AddEntryProcessorTests.java

Adds support for adding metadata entries to the Add Entries processor.
A new configuration option `metadata_key:` may be specified to set an attribute in the metadata. Only of the `metadata_key` or `key` can be specified. Value options are same as existing value options.
Resolves #2687 
Resolves #2687 

Add support for adding metadata entries

---

data-prepper-plugins/mutate-event-processors/src/test/java/org/opensearch/dataprepper/plugins/processor/mutateevent/AddEntryProcessorTests.java

PR to fix a recent build failure caused by:
```
AddEntryProcessorTests > testMetadataKeyIsNotAdded_when_addWhen_condition_is_false() FAILED
org.mockito.exceptions.misusing.UnnecessaryStubbingException at MockitoExtension.java:186
```
N/A

Fix build failure

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/plugin/ClasspathPluginProvider.java

Adds a new DEBUG log which logs detected plugin classes. This can help when debugging issues loading plugins.
N/A

Log all plugin classes found when DEBUG logging is enabled.

---

data-prepper-expression/build.gradle
data-prepper-expression/src/main/java/org/opensearch/dataprepper/expression/CidrExpressionFunction.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/CidrExpressionFunctionTest.java
data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/GenericExpressionEvaluator_ConditionalIT.java
docs/expression_syntax.md

Adds a function to check if an IP address is in the range of given CIDR blocks. For example: `isIpInCidr(/sourceIp,"192.0.2.0/24","10.0.1.0/16")` evaluates to true if the event has `sourceIp` field with value "192.0.2.5"
Resolves #2625 

Add isIpInCidr function

---

data-prepper-plugins/parse-json-processor/README.md
data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parsejson/ParseJsonProcessor.java
data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parsejson/ParseJsonProcessorConfig.java
data-prepper-plugins/parse-json-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/parsejson/ParseJsonProcessorConfigTest.java
data-prepper-plugins/parse-json-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/parsejson/ParseJsonProcessorTest.java

Add support to tag events when parse_json fails to parse.
Resolves #2744
Adds `tags_on_failure` new option to parse_json processor. An example, parse_json processor config would be
```
processor:                                                                                                                                              
- parse_json:                                                                                                                                        
source: "log"                                                                                                                                     
tags_on_failure: ["json_parse_fail", "tag2"]   
```
Resolves #2744 
- [X ] Commits are signed with a real name per the …

Add support to tag events when parse_json fails to parse

---

data-prepper-plugins/s3-sink/README.md
data-prepper-plugins/s3-sink/src/integrationTest/java/org/opensearch/dataprepper/plugins/sink/S3SinkServiceIT.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/S3SinkService.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/S3SinkServiceTest.java

The main change in this PR is to update the metrics in the `s3` sink to use the same names as similar metrics in the `s3` source. Additionally, it corrects a bug where the byte size was not recorded correctly.
I also updated the README.md with development instructions. And I did some slight refactoring to a unit test.
N/A

Updates to the S3 sink: metric names, README

---

release/archives/linux/data-prepper-jdk-x64.sh
release/archives/linux/data-prepper-x64.sh

Include the `JAVA_OPTS` after `DATA_PREPPER_JAVA_OPTS` in order to allow Data Prepper admins to override any value provided there. This is currently the Log4j configuration value.
I've opted to keep the `DATA_PREPPER_HOME_OPTS` at the end because I'm not trying to allow that configuration. That is something we could consider in another issue or PR.
Resolves #2720.

Sets JAVA_OPTS after DATA_PREPPER_JAVA_OPTS to allow overrides

---

data-prepper-core/build.gradle

Configurations the `data-prepper-core` `integrationTest` tests to use the same Log4j configuration as used by `test`. This puts the unit test and integration test logging in sync. It also enables DEBUG logging for the integration tests.
N/A

Use the same Log4j configuration for integration tests as used for unit testing

---

data-prepper-plugins/failures-common/src/main/java/org/opensearch/dataprepper/plugins/dlq/README.md
data-prepper-plugins/failures-common/src/main/java/org/opensearch/dataprepper/plugins/dlq/s3/S3DlqWriter.java
data-prepper-plugins/failures-common/src/test/java/org/opensearch/dataprepper/plugins/dlq/s3/S3DlqWriterTest.java

Eliminating extra slash in determining s3 key for DLQ. Updated documentation as well.
- resolves #2581

eliminates in built slash in s3 dlq key and resolves 2581

---

data-prepper-plugins/aws-plugin-api/README.md
data-prepper-plugins/aws-plugin-api/build.gradle
data-prepper-plugins/aws-plugin-api/src/main/java/org/opensearch/dataprepper/aws/api/AwsCredentialsOptions.java
data-prepper-plugins/aws-plugin-api/src/main/java/org/opensearch/dataprepper/aws/api/AwsCredentialsSupplier.java
data-prepper-plugins/aws-plugin-api/src/test/java/org/opensearch/dataprepper/aws/api/AwsCredentialsOptionsTest.java
data-prepper-plugins/aws-plugin/README.md
data-prepper-plugins/aws-plugin/build.gradle
data-prepper-plugins/aws-plugin/src/main/java/org/opensearch/dataprepper/plugins/aws/AwsExtensionProvider.java
data-prepper-plugins/aws-plugin/src/main/java/org/opensearch/dataprepper/plugins/aws/AwsPlugin.java
data-prepper-plugins/aws-plugin/src/main/java/org/opensearch/dataprepper/plugins/aws/CredentialsCache.java
data-prepper-plugins/aws-plugin/src/main/java/org/opensearch/dataprepper/plugins/aws/CredentialsIdentifier.java
data-prepper-plugins/aws-plugin/src/main/java/org/opensearch/dataprepper/plugins/aws/CredentialsProviderFactory.java
data-prepper-plugins/aws-plugin/src/main/java/org/opensearch/dataprepper/plugins/aws/DefaultAwsCredentialsSupplier.java
data-prepper-plugins/aws-plugin/src/test/java/org/opensearch/dataprepper/plugins/aws/AwsExtensionProviderTest.java
data-prepper-plugins/aws-plugin/src/test/java/org/opensearch/dataprepper/plugins/aws/AwsPluginIT.java
data-prepper-plugins/aws-plugin/src/test/java/org/opensearch/dataprepper/plugins/aws/AwsPluginTest.java
data-prepper-plugins/aws-plugin/src/test/java/org/opensearch/dataprepper/plugins/aws/CredentialsCacheTest.java
data-prepper-plugins/aws-plugin/src/test/java/org/opensearch/dataprepper/plugins/aws/CredentialsIdentifierTest.java
data-prepper-plugins/aws-plugin/src/test/java/org/opensearch/dataprepper/plugins/aws/CredentialsProviderFactoryTest.java
data-prepper-plugins/aws-plugin/src/test/java/org/opensearch/dataprepper/plugins/aws/DefaultAwsCredentialsSupplierTest.java
data-prepper-plugins/aws-plugin/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
settings.gradle

This creates a new AWS Extension Plugin. With this initial PR, this plugin supports a standard approach to AWS credentials management.
To try to keep this PR from being too large, I only included the new plugin. You can see #2731 to get a sense of how this will be used in other plugins. I'll create follow-on PRs to incorporate this into the other plugins accordingly.
Resolves #2751

Adds the new AWS Extension Plugin for Data Prepper

---

examples/log-ingestion/README.md

Updated the data prepper log ingestion demo guide documentation to account for the lack of logging when data prepper processes data. Also updates the instructions for creating an index pattern and viewing the processed logs on the open search dashboard.
Resolves #2756 

Updated the data prepper log ingestion demo guide documentation (opensearch-project#2756)

---

data-prepper-plugins/date-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/date/DateProcessor.java
data-prepper-plugins/date-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/date/DateProcessorConfig.java
data-prepper-plugins/date-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/date/DateProcessorTests.java

Adds date_when parameter to date processor to conditionally run the date processor based on conditional expressions

Add date_when option to date processor

---

data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3ObjectPluginMetrics.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3ObjectWorker.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/S3ObjectWorkerTest.java

This PR adds a new metric (`s3ObjectNoRecordsFound`) when the codec parse an S3 Object but does not capture any records from the object. A warning message is also logged at this time as well.
resolves #2699

adding metric and logs in the event an S3 object does not contain records or no records were parsed from the object

---

data-prepper-plugins/aggregate-processor/README.md
data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/TailSamplerAggregateAction.java
data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/TailSamplerAggregateActionConfig.java
data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateProcessorIT.java
data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/TailSamplerAggregateActionConfigTests.java
data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/TailSamplerAggregateActionTests.java

Tail Sampler action in Aggregate processor broken. The core logic that does the tail sampling was got dropped while uploading one of the revisions in the PR #2497 
Resolves #2760 
Resolves #2760 

Tail Sampler action in Aggregate processor broken

---

build.gradle
data-prepper-plugins/dynamodb-source-coordination-store/src/main/java/org/opensearch/dataprepper/plugins/sourcecoordinator/dynamodb/DynamoDbClientFactory.java
data-prepper-plugins/dynamodb-source-coordination-store/src/main/java/org/opensearch/dataprepper/plugins/sourcecoordinator/dynamodb/DynamoDbClientWrapper.java
data-prepper-plugins/dynamodb-source-coordination-store/src/main/java/org/opensearch/dataprepper/plugins/sourcecoordinator/dynamodb/DynamoDbSourceCoordinationStore.java
data-prepper-plugins/dynamodb-source-coordination-store/src/main/java/org/opensearch/dataprepper/plugins/sourcecoordinator/dynamodb/DynamoDbSourcePartitionItem.java
data-prepper-plugins/dynamodb-source-coordination-store/src/main/java/org/opensearch/dataprepper/plugins/sourcecoordinator/dynamodb/DynamoStoreSettings.java
data-prepper-plugins/dynamodb-source-coordination-store/src/test/java/org/opensearch/dataprepper/plugins/sourcecoordinator/dynamodb/DynamoDbClientFactoryTest.java
data-prepper-plugins/dynamodb-source-coordination-store/src/test/java/org/opensearch/dataprepper/plugins/sourcecoordinator/dynamodb/DynamoDbClientWrapperTest.java
data-prepper-plugins/dynamodb-source-coordination-store/src/test/java/org/opensearch/dataprepper/plugins/sourcecoordinator/dynamodb/DynamoDbSourceCoordinationStoreTest.java
data-prepper-plugins/opensearch/build.gradle

This adds an an optional TTL for COMPLETED partitions in the ddb source coordination store. 
If TTL is set in the `data-prepper-config`
```
source_coordination:
store:
dynamodb:
ttl: "PT5D"
``` 
the store will be created with ttl on the `expirationTime` field of the item. 
the dynamo store now has an option `skip_table_creation`, which will skip the step that attempts to create the table and enable time to live on the table. This defaults to false.
```
source_coordination:
store:
dynamodb:
ttl: "PT5D"
skip_table_creation: true
```
Related to #2412  …

Enable TTL for the ddb source coordination store, add option to skip store creation to source coordination config

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/source/coordinator/PartitionIdentifier.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/source/coordinator/SourceCoordinator.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/source/coordinator/SourcePartition.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/source/coordinator/exceptions/PartitionNotFoundException.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/source/coordinator/exceptions/PartitionNotOwnedException.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/source/coordinator/SourcePartitionTest.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/sourcecoordination/LeaseBasedSourceCoordinator.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/sourcecoordination/LeaseBasedSourceCoordinatorTest.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3ScanPartitionCreationSupplier.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3SourceProgressState.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/ScanObjectWorker.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/S3ScanObjectWorkerTest.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/S3ScanPartitionCreationSupplierTest.java

This includes a new type of item to store for source coordination. Partitions returned in the Partition supplier from the source will be created with the sourceIdentifier as the suffix `|PARTITION`.
Global state items will be created with a sourceIdentifier with the suffix `|GLOBAL_STATE`. 
In `getNextPartition`, if no partition is acquired on the first attempt, the partition creation supplier is run. However, now the source coordinator will attempt to acquire (assign ownership to itself) the item for global state for partition creation. If this item is not available, that means that another instance of Data Prepper already owns it, and is handling the partition creation, and the instance will move on and retry. If the item is acquired, then the globalStateMap will be pulled from …

Acquire Global State Item to create partitions, pass globalStateMap to partition creation supplier function

---

data-prepper-plugins/s3-sink/build.gradle
data-prepper-plugins/s3-sink/src/integrationTest/java/org/opensearch/dataprepper/plugins/sink/S3SinkServiceIT.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/ClientFactory.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/S3Sink.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/S3SinkService.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/configuration/AwsAuthenticationOptions.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/ClientFactoryTest.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/S3SinkServiceTest.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/S3SinkTest.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/configuration/AwsAuthenticationOptionsTest.java

Updates the `s3` sink to use the AWS Plugin. This now provides the AWS credentials for this sink. This includes some related refactoring including fixing a bug where the S3 client was created anew for every object write.
Resolves #2767

Updates the S3 sink to use the AWS Plugin for loading AWS credentials

---

settings.gradle

Bump the dependency on opensearch-java new release version so that the log message from the client will be more helpful. With this change, we do not have to explicitly catch the exception with ambiguous message and infer the root cause in data-prepper.
Resolves #2655 
Resolves #2657 

FIX: bump opensearch-java version to fix unhelpful log message

---

data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/S3SinkService.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/S3SinkServiceTest.java

Fixes a bug in the `s3` sink for null Event handles.
```
2023-06-02T22:22:12,052 [performance-alb-pipeline-sink-worker-2-thread-3] ERROR org.opensearch.dataprepper.plugins.sink.S3SinkService - Exception while write event into buffer :
java.lang.NullPointerException: Cannot invoke "org.opensearch.dataprepper.model.event.EventHandle.release(boolean)" because "eventHandle" is null
at org.opensearch.dataprepper.plugins.sink.S3SinkService.releaseEventHandles(S3SinkService.java:139) ~[s3-sink-2.3.0-SNAPSHOT.jar:?]
at org.opensearch.dataprepper.plugins.sink.S3SinkService.output(S3SinkService.java:120) ~[s3-sink-2.3.0-SNAPSHOT.jar:?]
at org.opensearch.dataprepper.plugins.sink.S3Sink.doOutput(S3Sink.java:106) ~[s3-sink-2.3.0-SNAPSHOT.jar:?]
at …
```

Fixes a bug in the S3 sink where events without handles throw NPE

---

data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3InputStream.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/S3InputStreamTest.java

Fix bug where s3 input stream was closing too frequently
parquet files from s3 not reading correctly.

Fix bug where s3 stream was closing too early.

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/configuration/DataPrepperVersion.java
gradle.properties

Now that the `2.3` branch is available, this PR updates `main` to target Data Prepper 2.4.0.
N/A

Updates main to Data Prepper 2.4.

---

data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/OpenSearchService.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/OpenSearchSource.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/OpenSearchSourceConfiguration.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/OpenSearchIndexPartitionCreationSupplier.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/PitWorker.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/ScrollWorker.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/ClusterClientFactory.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/ElasticsearchAccessor.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/OpenSearchAccessor.java
data-prepper-plugins/opensearch-source/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/OpenSearchServiceTest.java
data-prepper-plugins/opensearch-source/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/OpenSearchIndexPartitionCreationSupplierTest.java
data-prepper-plugins/opensearch-source/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/PitWorkerTest.java

Implements the `OpenSearchIndexPartitionSupplier`, which will list all indices of the source cluster and filter them by the include and exclude regex patterns.
Also starts implementation for PitWorker to use the scheduling configuration with source coordinator without processing the object. When calling `getNextPartition` returns empty, the PitWorker will back off and retry in a fixed 30 seconds. The code added for PitWorker here would be essentially the same for ScrollWorker (the interactions with source coordinator will be very similar.
`OpenSearchService` now uses a scheduled executor service instead of spawning new threads directly. This allows scheduling to start at the `start_time`. The `stop` method will let the `SearchWorker` future know to not grab another partition, and will get …

Implement opensearch index partition creation supplier and PitWorker without processing indices

---

data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/ConvertEntryTypeProcessor.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/ConvertEntryTypeProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/test/java/org/opensearch/dataprepper/plugins/processor/mutateevent/ConvertEntryTypeProcessor_NullValueTests.java
data-prepper-plugins/mutate-event-processors/src/test/java/org/opensearch/dataprepper/plugins/processor/mutateevent/NullValuesTests.java

Add null_values feature
Resolve #2822 

GitHub-issue#2822: Define null characters in convert processor

---

data-prepper-plugins/opensearch-source/build.gradle

Removes the dependency on `org.codehaus.plexus`, which is a dependency of `maven-artifact`, and has a CVE
Dependency graph before
```
cat deps.os.out | grep "org.codehaus"
|    \--- org.codehaus.plexus:plexus-utils:2.0.6
|    \--- org.codehaus.plexus:plexus-utils:2.0.6
|    \--- org.codehaus.plexus:plexus-utils:2.0.6
|    \--- org.codehaus.plexus:plexus-utils:2.0.6
```
Dependency graph after
```
cat deps.os.out | grep "org.codehaus"
```
Resolves #2816 
Resolves #2820 
Resolves #2818 
Resolves #2819 
Resolves #2817  …

Fix CVE in maven-artifact by excluding that dependency

---

data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/OpenSearchService.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/BufferAccumulator.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/PitWorker.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/ScrollWorker.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/OpenSearchAccessor.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/model/MetadataKeyAttributes.java
data-prepper-plugins/opensearch-source/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/OpenSearchServiceTest.java
data-prepper-plugins/opensearch-source/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/BufferAccumulatorTest.java
data-prepper-plugins/opensearch-source/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/PitWorkerTest.java
data-prepper-plugins/opensearch-source/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/OpenSearchAccessorTest.java

This change uses the `BufferAccumulator` class from the s3 source to write and flush documents to the buffer with backoff and retry.
The `records_to_accumulate` is currently the same as the `batch_size` (pagination size) for searching.
Waiting on #2847 before rebasing and pushing non-draft PR

Os source buffer backoff retry

---

data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/plugins/InMemorySink.java
data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/acknowledgements/one-pipeline-ack-expiry-test.yaml
data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/acknowledgements/one-pipeline-three-sinks.yaml
data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/acknowledgements/simple-test.yaml
data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/acknowledgements/three-pipeline-route-test.yaml
data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/acknowledgements/three-pipelines-test-multi-sink.yaml
data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/acknowledgements/three-pipelines-test.yaml
data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/acknowledgements/two-parallel-pipelines-test.yaml
data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/acknowledgements/two-pipelines-test.yaml
data-prepper-plugins/common/src/main/java/org/opensearch/dataprepper/plugins/sink/FileSink.java
data-prepper-plugins/common/src/main/java/org/opensearch/dataprepper/plugins/sink/StdOutSink.java

Add end-to-end acknowledgement support to Stdout and File Sinks.
Stdout and File sinks are currently not acknowledging e2e acks. This change adds the support to acknowledge e2e acks.
Resolves #2859 
Resolves #2859 

Add end-to-end acknowledgement support to Stdout and File Sinks

---

data-prepper-plugins/common/src/main/java/org/opensearch/dataprepper/plugins/codec/GZipDecompressionEngine.java
data-prepper-plugins/common/src/test/java/org/opensearch/dataprepper/plugins/codec/GZipDecompressionEngineTest.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/S3ObjectWorkerTest.java

Throw exception when gzip is specified but the data is not specified.
Exception not being thrown when gzip encoding specified but files are not gzip.

Throw exception when Gzip encoding specified but file does not contain gzip header.

---

data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/OpenSearchService.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/configuration/SearchConfiguration.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/NoSearchContextWorker.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/ElasticsearchAccessor.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/OpenSearchAccessor.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/SearchAccessor.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/SearchAccessorStrategy.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/model/NoSearchContextSearchRequest.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/model/SearchContextType.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/model/SearchWithSearchAfterResults.java
data-prepper-plugins/opensearch-source/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/OpenSearchServiceTest.java
data-prepper-plugins/opensearch-source/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/NoSearchContextWorkerTest.java
data-prepper-plugins/opensearch-source/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/PitWorkerTest.java
data-prepper-plugins/opensearch-source/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/OpenSearchAccessorTest.java
data-prepper-plugins/opensearch-source/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/SearchAccessStrategyTest.java

* Implements `NoSearchContextWorker`, which will process indices using sort and search_after without creating search contexts via scroll or point in time
* Adds a new parameter to `search_options`, the `search_context_type`. 
The `search_context_type` can be set to `none`, `point_in_time`, or `scroll`. By default, point in time will be used for versions that can support it, and scroll will be used for versions that don't support point in time. 
However, there is a consideration to make the default just be `none`, and just use the version lookup to validate that point in time can be used if the `search_context_type` is set to `point_in_time`.
For more …

Implement NoSearchContextWorker to search with search_after and not use pit or scroll, allow override with search_context_type parameter

---

data-prepper-plugins/s3-sink/README.md
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/S3SinkService.java

Rename s3 sink metrics because of naming conflict with S3 source
Resolves #2887

Updated s3 sink metrics

---

data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSink.java

Change the error message for index name format exception to not be sensitive

Change log for index name format failure in opensearch sink

---

data-prepper-plugins/parquet-codecs/src/test/java/org/opensearch/dataprepper/plugins/codec/parquet/ParquetInputCodecTest.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3InputFile.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3InputStream.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3ObjectWorker.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/SqsWorker.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/S3InputFileTest.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/S3InputStreamTest.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/S3ObjectWorkerTest.java

Do not suppress logs when there is an exception when reading from S3

Do not suppress logs when there are exception in s3 source.

---

docs/end_to_end_acknowledgements.md

Change the title to be consistent with configuration.
End-to-end acknowledgments configuration use the spelling "acknowledgment". This change makes it consistent spelling.

Change the title to be consistent with configuration

---

data-prepper-plugins/opensearch-source/build.gradle
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/OpenSearchSource.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/NoSearchContextWorker.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/OpenSearchIndexPartitionCreationSupplier.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/PitWorker.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/ElasticsearchAccessor.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/OpenSearchClientFactory.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/SearchAccessorStrategy.java
data-prepper-plugins/opensearch-source/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/OpenSearchSourceTest.java
data-prepper-plugins/opensearch-source/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/ElasticsearchAccessorTest.java
data-prepper-plugins/opensearch-source/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/OpenSearchClientFactoryTest.java
data-prepper-plugins/opensearch-source/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/OpenSearchIndexPartitionCreationSupplierTest.java
data-prepper-plugins/opensearch-source/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/SearchAccessStrategyTest.java

This change adds support for Elasticsearch clusters by creating an Elasticsearch client when the opensearch client is unable to lookup cluster info. 
This change also implements processing indices with point in time or no search context. 
During testing, I found that es clusters with `build-flavor` of oss do not support point in time, while a `build-flavor` of `default` does. So the current requirements to use point in time is that the es cluster has to be greater than 7.10.0, and must have `build-flavor` that is not `oss`. 
This was tested on 2 different es clusters with version 7.10.2, one with `oss` and one with `default` build-flavor.
The code is very similar to that for opensearch, just with different classes from the elasticsearch client. 
By submitting this pull …

Elasticsearch client implementation with pit and no context search

---

data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/PitWorker.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/ScrollWorker.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/OpenSearchAccessor.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/model/CreateScrollRequest.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/model/CreateScrollResponse.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/model/DeleteScrollRequest.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/model/SearchScrollRequest.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/model/SearchScrollResponse.java
data-prepper-plugins/opensearch-source/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/ScrollWorkerTest.java
data-prepper-plugins/opensearch-source/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/OpenSearchAccessorTest.java

This change implements searching with `scroll` for OpenSearch clusters. This will be the default behavior for OpenSearch clusters with version less than 2.5.0. It can also be explicitly used by setting `search_context_type` to `scroll`

Implement searching with scroll contexts for OpenSearch

---

data-prepper-plugins/s3-source/README.md
data-prepper-plugins/s3-source/src/integrationTest/java/org/opensearch/dataprepper/plugins/source/S3ScanObjectWorkerIT.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3ScanPartitionCreationSupplier.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3ScanService.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3SourceConfig.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/ScanOptions.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/configuration/S3ScanBucketOption.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/configuration/S3ScanScanOptions.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/S3ScanPartitionCreationSupplierTest.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/S3ScanServiceTest.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/ScanOptionsTest.java

This PR made the following changes:
- Makes time range settings optional (start_time, end_time, range). When they are not set, scan all objects
- Allows setting time range on specific bucket, and it will override top-level time range settings
Resolves #2737 
Resolves #2735 

S3 Scan time range improvements

---

data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkRetryStrategy.java

Fix DLQ writer writing empty list.
DQL writer is writing empty list like this sometimes. Upon investigation, found that bulkOperation is being tried even the operations count is zero. This is resulting in writing empty DLQ List when the bulk operation fails.

Fix DLQ writer writing empty list

---

data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/ElasticsearchAccessor.java
data-prepper-plugins/opensearch-source/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/ElasticsearchAccessorTest.java

This change follows from the work done in #2923 by implementing for Elasticsearch with scroll instead of just OpenSearch.

Implement scroll apis for ElasticSearch Accessor

---

data-prepper-plugins/geoip-processor/build.gradle

Temporarily reduce coverage minimum value
Currently build is failing due to the coverage minimum for geo-ip processor without the test cases in place.

Temporarily reduce coverage minimum value

---

data-prepper-plugins/opensearch-source/README.md

Adds documentation for opensearch source

Add basic opensearch source documentation for config

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/JacksonEvent.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/event/JacksonEventTest.java
data-prepper-plugins/opensearch-source/README.md
data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parsejson/ParseJsonProcessor.java
data-prepper-plugins/parse-json-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/parsejson/ParseJsonProcessorTest.java

Messed up my git history so following up on #2936 

Remove validation that made keys starting or ending with . - or _ invalid, catch all exceptions in the parse json processor

---

data-prepper-plugins/opensearch-source/README.md
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/OpenSearchSource.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/OpenSearchSourceConfiguration.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/OpenSearchClientFactory.java
data-prepper-plugins/opensearch-source/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/OpenSearchSourceConfigurationTest.java
data-prepper-plugins/opensearch-source/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/OpenSearchClientFactoryTest.java

Adds a `disable_authentication` flag to the OpenSearch source, which allows auth to be skipped if desired. Defaults to false.
Resolves #2939 

Add disable_authentication flag to the opensearch source

---

data-prepper-plugins/translate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/translate/RegexParameterConfiguration.java
data-prepper-plugins/translate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/translate/TranslateProcessor.java
data-prepper-plugins/translate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/translate/TranslateProcessorConfig.java
data-prepper-plugins/translate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/translate/RegexParameterConfigurationTest.java
data-prepper-plugins/translate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/translate/TranslateProcessorConfigTest.java
data-prepper-plugins/translate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/translate/TranslateProcessorTest.java

Implemented the functionality for Iterate_on option along with default and exact options. source option can now take either string or list of strings. Addressed previous PR comments. Added testcases for all the options implemented.

Translate Plugin - Added functionality for iterate_on, default, exact options

---

data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3InputStream.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/S3InputStreamTest.java

Correctly abort stream and handle internal counters correctly when end of file is reached

Fix S3 errors around end of file behavior.

---

data-prepper-plugins/translate-processor/build.gradle
data-prepper-plugins/translate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/translate/RegexParameterConfiguration.java
data-prepper-plugins/translate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/translate/TranslateProcessor.java
data-prepper-plugins/translate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/translate/TranslateProcessorConfig.java
data-prepper-plugins/translate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/translate/TranslateProcessorConfigTest.java
data-prepper-plugins/translate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/translate/TranslateProcessorTest.java

Implemented target_type option in translate processor. Added necessary test cases.

Translate Plugin - Target Type implementation

---

data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/SqsWorker.java

Fix SqsWorker error messages.
1. SQSWorker tries to delete empty list of objects which results in error message that's misleading. This fix avoids that by check for empty message list before invoking delete
2. SQS worker message when deletion fails has is constructed incorrectly. Fixed it by constructing the error message correctly.

Fix SqsWorker error messages

---

data-prepper-plugins/parquet-codecs/src/main/java/org/opensearch/dataprepper/plugins/codec/parquet/ParquetInputCodec.java
data-prepper-plugins/s3-source/build.gradle
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3InputFile.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3InputStream.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/S3InputStreamTest.java

S3 will reset the conenction on their end frequently. To not lose data, data prepper should retry all socket exceptions by attempting to re-open the stream.
Retries all socket exceptions
S3 socket exceptions causing records to get dropped

Retry s3 reads on socket exceptions.

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/acknowledgements/AcknowledgementSet.java
data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/plugins/InMemorySource.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/acknowledgements/DefaultAcknowledgementSet.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/acknowledgements/DefaultAcknowledgementSetManagerTests.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/acknowledgements/DefaultAcknowledgementSetTests.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaSourceCustomConsumer.java
data-prepper-plugins/s3-source/src/integrationTest/java/org/opensearch/dataprepper/plugins/source/SqsWorkerIT.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/SqsWorker.java

Fix race condition in SqsWorker when acknowledgements are enabled
When E2E acknowledgements are enabled, S3 Source need to synchronize between the callback thread and the main thread because main thread may not have got chance to fully populate the waitingForAcknowledgements list
Resolves #3000 
#3000 

Fix race condition in SqsWorker when acknowledgements are enabled

---

data-prepper-plugins/opensearch/README.md
data-prepper-plugins/opensearch/src/integrationTest/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSinkIT.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/ConnectionConfiguration.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSink.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/bulk/JavaClientAccumulatingCompressedBulkRequest.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/bulk/JavaClientAccumulatingUncompressedBulkRequest.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/IndexConfiguration.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkRetryStrategyTests.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/bulk/JavaClientAccumulatingCompressedBulkRequestTest.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/bulk/JavaClientAccumulatingUncompressedBulkRequestTest.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/IndexConfigurationTests.java

This PR introduces 2 implementations of the JavaClientAccumulatingBulkRequest, 1 to measure the uncompressed size of the bulk request, and a second to measure the compressed size of the bulk request. It also restores the default behavior to measure the uncompressed size.
The compressed sizing implementation is tweaked to use a logarithmic algorithm for measuring the compressed bulk size to increase the accuracy of the measurement.
As part of this change, 3 new settings are exposed:
1. `enable_request_compression` - controls whether request compression is enabled at the TransportClient level
2. `estimate_bulk_size_using_compression` - controls which of the two implementations above are used
3. `max_local_compressions_for_estimation` - a lever for trading between accuracy and performance …

Introduce option to measure bulk sizes with or without compression

---

data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3InputFile.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3InputStream.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3ObjectWorker.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/S3InputFileTest.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/S3InputStreamTest.java

Fixes bucket ownership validation in the `s3` source.
Resolves #3005

Fix bucket ownership validation in S3 source

---

release/release-notes/data-prepper.change-log-2.3.2.md

Adds the change log file for Data Prepper 2.3.2.
Generated via:
```
git-release-notes 2.3.1..2.3.2 markdown > release/release-notes/data-prepper.change-log-2.3.2.md
```
N/A

Adds the Data Prepper 2.3.2 change log.

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/ProcessWorker.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaSourceCustomConsumer.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3ObjectWorker.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3SelectObjectWorker.java
data-prepper-plugins/sqs-source/src/main/java/org/opensearch/dataprepper/plugins/source/sqssource/handler/RawSqsMessageHandler.java

Fix race condition in data prepper sources using e2e acknowledgements.
There is a race condition in DataPrepper sources using e2e acks. This change fixes the race condition by changing the order in which events are added to acknowledgement set and buffer. The events must be added to acknowledgement set before they are added to the buffer.
Resolves #3038 
#3038 

Fix race condition in data prepper sources using e2e acknowledgements

---

data-prepper-plugins/kafka-plugins/build.gradle
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/configuration/AwsConfig.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/configuration/KafkaSourceConfig.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/configuration/TopicConfig.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/source/KafkaSource.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/configuration/KafkaSourceConfigTest.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/source/KafkaSourceTest.java

Kafka Source - Cleanup and Enhancements for MSK
1. Added functionality to get bootstrap servers from MSK cluster if MSK with IAM is used
2. Added validation to Kafka configurations

Kafka Source - Cleanup and Enhancements for MSK

---

data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkOperationWrapper.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/bulk/BulkOperationWriter.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/bulk/JavaClientAccumulatingCompressedBulkRequest.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/bulk/JavaClientAccumulatingUncompressedBulkRequest.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/dlq/FailedBulkOperationConverter.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkOperationWrapperTests.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/dlq/FailedBulkOperationConverterTest.java

With the addition of the create action, there is need to branch when extracting data from a BulkOperation. This adds helper methods to BulkOperationWrapper to consolidate this logic in a single place. It also resolves a bug with the create action and writing to a DLQ
#3040 

Consolidate logic related to extracting data from a BulkOperation

---

data-prepper-plugins/translate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/translate/FilePathParser.java
data-prepper-plugins/translate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/translate/MappingsParameterConfig.java
data-prepper-plugins/translate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/translate/TargetsParameterConfig.java
data-prepper-plugins/translate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/translate/TranslateProcessor.java
data-prepper-plugins/translate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/translate/TranslateProcessorConfig.java
data-prepper-plugins/translate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/translate/MappingsParameterConfigTest.java
data-prepper-plugins/translate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/translate/TranslateProcessorConfigTest.java
data-prepper-plugins/translate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/translate/TranslateProcessorTest.java

Added implementation for `file_path` option for local files. Fixed some bugs. Changed `target_type` to `type`. Test cases for added features.

Translate Processor -  Added file_path functionality for local files

---

data-prepper-plugins/kafka-plugins/README.md
data-prepper-plugins/kafka-plugins/build.gradle
data-prepper-plugins/kafka-plugins/src/integrationTest/java/org/opensearch/dataprepper/plugins/kafka/source/KafkaSourceMultipleAuthTypeIT.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/configuration/AuthConfig.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/source/InsecureSslEngineFactory.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/source/KafkaSource.java

Add Support for Auth/NoAuth with/without Encryption in Kafka with integration tests
The following authentication and encryption combinations are supported. Integration Tests are added to test all 4 combinations
1. No Auth, No Encryption (default Kafka)
2. Username/Password Auth, No Encryption
3. No Auth, with Encryption enabled
4. Username/Password Auth, with Encryption enabled. …

Add Support for Auth/NoAuth with/without Encryption in Kafka with integration tests

---

data-prepper-plugins/kafka-plugins/build.gradle
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/configuration/KafkaSourceConfig.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/configuration/OAuthConfig.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/configuration/PlainTextAuthConfig.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/configuration/SchemaConfig.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/configuration/TopicConfig.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaSourceCustomConsumer.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/source/KafkaSource.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/util/ClientDNSLookupType.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/util/KafkaSourceSecurityConfigurer.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/configuration/SchemaConfigTest.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/configuration/TopicConfigTest.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/source/KafkaSourceTest.java
data-prepper-plugins/kafka-plugins/src/test/resources/sample-pipelines.yaml

- Implemented PLAIN and OAUTHBEARER authentication mechanisms
- Kafka source will be able to connect to the Local schema registry as well as the Confluent Cloud schema registry with authentication mechanisms.
- Implemented the Confluent cloud cluster connectivity
- Supported security protocols as follows
PLAINTEXT - Un-authenticated, non-encrypted channel.
SASL_PLAINTEXT - SASL authenticated, non-encrypted channel.
SASL_SSL - SASL authenticated, SSL channel.
- Github issue https://github.com/opensearch-project/data-prepper/issues/254 …

Kafka source Confluent schema registry connectivity and OAuth implementation

---

data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/bulk/Es6BulkApiWrapper.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/bulk/Es6BulkApiWrapperTest.java

This fix is a follow up of #3045 . It tackles the generic missing index in bulk request by extracting index value from the first bulk operation.
Bug
```
2023-07-24T16:51:57,655 [log-pipeline-sink-worker-2-thread-1] WARN  org.opensearch.dataprepper.plugins.sink.opensearch.OpenSearchSink - Document [FailedDlqData{index='test-bulk', indexId='null', status='0', message='Bulk request index cannot be missing', document={log=test log, @timestamp=2023-07-24T16:51:36.582-05:00}}] has failure. DLQ not configured
java.lang.IllegalArgumentException: Bulk request index cannot be missing
```
For more information on following Developer Certificate of …

FIX: missing request index

---

data-prepper-api/src/test/java/org/opensearch/dataprepper/model/sink/AbstractSinkTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/acknowledgements/AcknowledgementSetMonitorTests.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/PipelineTests.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/plugins/TestSink.java
data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateProcessorIT.java
data-prepper-plugins/log-generator-source/src/test/java/org/opensearch/dataprepper/plugins/source/loggenerator/LogGeneratorSourceTest.java
data-prepper-plugins/rss-source/src/main/java/org/opensearch/dataprepper/plugins/source/rss/RSSSource.java
data-prepper-plugins/rss-source/src/test/java/org/opensearch/dataprepper/plugins/source/rss/RSSSourceTest.java

This PR includes some attempts to improve our test times.
* Adds use of Awaitility instead of Thread.sleep in some locations.
* Reduces repeated tests in AggregateProcessorIT, which is a particularly slow test.
* Reduces some delays/timeouts.
N/A

Work to reduce test time by reducing some repeated tests, using Awaitility, and reducing delays

---

data-prepper-api/src/test/java/org/opensearch/dataprepper/model/sink/SinkThreadTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/acknowledgements/DefaultAcknowledgementSetManagerTests.java

This PR aims to knock out a few more slow tests in data-prepper-core. These are the highest time tests in data-prepper-core aside from the tests already being covered in #3019 and #3020.
N/A

Improves some of the test timing in Data Prepper core tests

---

data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/PeerForwarderReceiveBufferTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/PeerForwarder_ClientServerIT.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/RemotePeerForwarderTest.java

This PR reduces some of the timeouts and waits which are part of the peer-forwarder tests to reduce testing time. The changes to `PeerForwarderReceiveBufferTest` in particular were quite significant in my testing, knocking a minute from the build time.
N/A

Improves timeouts for the peer forwarder tests to reduce test time

---

data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3SourceConfig.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/ownership/ConfigBucketOwnerProviderFactory.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/ownership/MappedBucketOwnerProvider.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/ownership/ConfigBucketOwnerProviderFactoryTest.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/ownership/MappedBucketOwnerProviderTest.java

This adds two new configurations to allow users to define bucket ownership:
* `bucket_owners` - A map of bucket names to expected account Ids
* `default_bucket_owner` - An account Id to use for buckets by default. This effectively overrides the existing default which is to use the SQS queue account.
Resolves #2012

New configurations in the S3 source to configure bucket ownership

---

data-prepper-plugins/translate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/translate/TranslateProcessor.java
data-prepper-plugins/translate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/translate/TranslateProcessorTest.java

Previously when `exact` option is `false`, if there is a non-exact match, the `target` field will be populated with mapped value. This logic has been changed to:
If there is a non-exact match, the mapped value will be replaced in the source value in all occurences and placed in the target field.
For the following config:
```yaml
translate - 
mappings:
- source: status
targets:
- target: result
regex:
exact: false
patterns:
foo: bar
- source: status2
targets:
- target: result2
regex:
exact: false
patterns:
foo: bar
```
Log:
```json
{ 
"status" : "footer", 
"status2" : "foofoo"
}
```
Will be translated to: 
```json
{ 
"status" : "footer", 
"status2" : "foofoo",
"result" : "barter", 
"result2" : "barbar"
}
```
By submitting this …

Translate Processor: Changed non-exact matching logic

---

data-prepper-plugins/translate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/translate/JsonExtractor.java
data-prepper-plugins/translate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/translate/MappingsParameterConfig.java
data-prepper-plugins/translate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/translate/TranslateProcessor.java
data-prepper-plugins/translate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/translate/MappingsParameterConfigTest.java
data-prepper-plugins/translate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/translate/TranslateProcessorTest.java

Removed the iterateOn option. Now the iterateOn functionality will be taken care by source option with the help of full path to the source.
* The source provided can be full path to the field in the log that requires translation.  
* If the source path is something like `field1/field2/source`, all the objects that satisfy the path will be translated based on the provided mappings and the targets fields will be placed in the object along the path `field1/field2/target`.  
* The fields (`field1`, `field2`) leading up to the source field in the path must be JSON arrays or JSON objects. It is important to note that other JSON data types cannot be iterated in this context.
* The `translate_when` expression if configured will only be applied for the JSON objects with reference to the path …

Translate Plugin - Added functionality to provide full path to the source field

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/configuration/SinkModel.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/Event.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/JacksonEvent.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/sink/SinkContext.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/configuration/PipelinesDataFlowModelTest.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/configuration/SinkModelTest.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/event/JacksonEventTest.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/sink/SinkContextTest.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/parser/model/PipelineConfiguration.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSink.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/DocumentBuilder.java

Add include_keys and exclude_keys options to sink 
Resolve #2975 

Add include_keys and exclude_keys options to sink

---

data-prepper-plugins/kafka-plugins/src/integrationTest/java/org/opensearch/dataprepper/plugins/kafka/source/KafkaSourceJsonTypeIT.java
data-prepper-plugins/kafka-plugins/src/integrationTest/java/org/opensearch/dataprepper/plugins/kafka/source/MskGlueRegistryMultiTypeIT.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/configuration/AuthConfig.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/configuration/KafkaKeyMode.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/configuration/KafkaSourceConfig.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/configuration/TopicConfig.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaSourceCustomConsumer.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/source/KafkaSource.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/util/KafkaSourceSecurityConfigurer.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/configuration/KafkaSourceConfigTest.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaSourceCustomConsumerTest.java
data-prepper-plugins/kafka-plugins/src/test/resources/sample-pipelines.yaml

1. Added topic level config option to capture kafka key into the event. Support the following three options
- discard
- include_as_field
- include_as_metadata
2. Changed Schema Registry option from "glue" -> "aws_glue"
3. Changed SASL auth option from "aws_iam" -> "aws_msk_iam"
4. Added integrated test that tests different kafka key options

Support for adding different modes to put kafka key in the event and Other Config changes

---

.github/workflows/data-prepper-log-analytics-basic-grok-e2e-tests.yml
.github/workflows/data-prepper-peer-forwarder-local-node-e2e-tests.yml
.github/workflows/data-prepper-peer-forwarder-static-e2e-tests.yml
.github/workflows/data-prepper-trace-analytics-raw-span-compatibility-e2e-tests.yml
.github/workflows/data-prepper-trace-analytics-raw-span-e2e-tests.yml
.github/workflows/data-prepper-trace-analytics-raw-span-peer-forwarder-e2e-tests.yml
.github/workflows/data-prepper-trace-analytics-service-map-e2e-tests.yml
.github/workflows/gradle.yml
.github/workflows/opensearch-sink-opendistro-integration-tests.yml
.github/workflows/opensearch-sink-opensearch-integration-tests.yml
.github/workflows/performance-test-compile.yml
.github/workflows/release.yml
.github/workflows/staging-resources-cdk-check.yml
.github/workflows/third-party-generate.yml

Since this project is "Data Prepper" this renames the titles in our GitHub Action jobs to use "Data Prepper" instead of "Data-Prepper."
N/A

Updated GitHub Actions to use "Data Prepper" in the job titles

---

data-prepper-plugins/cloudwatch-logs/build.gradle
data-prepper-plugins/cloudwatch-logs/src/main/java/org/opensearch/dataprepper/plugins/sink/cloudwatch_logs/CloudWatchLogsSink.java
data-prepper-plugins/cloudwatch-logs/src/main/java/org/opensearch/dataprepper/plugins/sink/cloudwatch_logs/config/ThresholdConfig.java
data-prepper-plugins/cloudwatch-logs/src/main/java/org/opensearch/dataprepper/plugins/sink/cloudwatch_logs/utils/CloudWatchLogsLimits.java
data-prepper-plugins/cloudwatch-logs/src/test/java/org/opensearch/dataprepper/plugins/sink/cloudwatch_logs/client/CloudWatchLogsServiceTest.java
data-prepper-plugins/cloudwatch-logs/src/test/java/org/opensearch/dataprepper/plugins/sink/cloudwatch_logs/config/ThresholdConfigTest.java
data-prepper-plugins/cloudwatch-logs/src/test/java/org/opensearch/dataprepper/plugins/sink/cloudwatch_logs/utils/CloudWatchLogsLimitsTest.java

This change is meant to refactor the CloudWatch Logs sink config to use "Duration" and "ByteCount". It also includes the required changes to the tests.
This PR will work towards resolving CWL-Sink for Data-Prepper [Issue https://github.com/https://github.com/https://github.com/https://github.com/https://github.com/https://github.com/opensearch-project/data-prepper/issues/2778]
Link: https://github.com/opensearch-project/data-prepper/issues/2778#issue-1731228391

GitHub-Issue#2778: Refactored Config to include Duration and ByteCount types

---

data-prepper-plugins/cloudwatch-logs/README.md

This change introduces the README for the CloudWatch Logs Sink.
This PR will work towards resolving CWL-Sink for Data-Prepper [Issue https://github.com/https://github.com/https://github.com/https://github.com/https://github.com/https://github.com/https://github.com/opensearch-project/data-prepper/issues/2778]
Link: https://github.com/opensearch-project/data-prepper/issues/2778#issue-1731228391

GitHub-Issue#2778: Added README for CloudWatch Logs Sink

---

data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/configuration/TopicConfig.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/source/KafkaSource.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/configuration/TopicConfigTest.java
data-prepper-plugins/kafka-plugins/src/test/resources/sample-pipelines.yaml

Make max partition fetch bytes configurable. Added config option to set max partition fetch bytes.
Also fixed the code to honor configured values for fetch bytes min and max poll interval.
Also fixed code to get authentication config only once and not for every topic.

Make max partition fetch bytes configurable

---

data-prepper-plugins/armeria-common/src/main/java/org/opensearch/dataprepper/GrpcRequestExceptionHandler.java
data-prepper-plugins/armeria-common/src/main/java/org/opensearch/dataprepper/HttpRequestExceptionHandler.java
data-prepper-plugins/armeria-common/src/main/java/org/opensearch/dataprepper/exceptions/BadRequestException.java
data-prepper-plugins/armeria-common/src/main/java/org/opensearch/dataprepper/exceptions/BufferWriteException.java
data-prepper-plugins/armeria-common/src/main/java/org/opensearch/dataprepper/exceptions/RequestCancelledException.java
data-prepper-plugins/armeria-common/src/test/java/org/opensearch/dataprepper/GrpcRequestExceptionHandlerTest.java
data-prepper-plugins/armeria-common/src/test/java/org/opensearch/dataprepper/HttpRequestExceptionHandlerTest.java
data-prepper-plugins/http-source/src/main/java/org/opensearch/dataprepper/plugins/source/loghttp/HTTPSource.java
data-prepper-plugins/http-source/src/main/java/org/opensearch/dataprepper/plugins/source/loghttp/LogHTTPService.java
data-prepper-plugins/http-source/src/test/java/org/opensearch/dataprepper/plugins/source/loghttp/HTTPSourceTest.java
data-prepper-plugins/http-source/src/test/java/org/opensearch/dataprepper/plugins/source/loghttp/LogHTTPServiceTest.java
data-prepper-plugins/otel-logs-source/src/main/java/org/opensearch/dataprepper/plugins/source/otellogs/OTelLogsGrpcService.java
data-prepper-plugins/otel-logs-source/src/main/java/org/opensearch/dataprepper/plugins/source/otellogs/OTelLogsSource.java
data-prepper-plugins/otel-logs-source/src/test/java/org/opensearch/dataprepper/plugins/source/otellogs/OTelLogsGrpcServiceTest.java
data-prepper-plugins/otel-logs-source/src/test/java/org/opensearch/dataprepper/plugins/source/otellogs/OTelLogsSourceTest.java
data-prepper-plugins/otel-metrics-source/src/main/java/org/opensearch/dataprepper/plugins/source/otelmetrics/OTelMetricsGrpcService.java
data-prepper-plugins/otel-metrics-source/src/main/java/org/opensearch/dataprepper/plugins/source/otelmetrics/OTelMetricsSource.java
data-prepper-plugins/otel-metrics-source/src/test/java/org/opensearch/dataprepper/plugins/source/otelmetrics/OTelMetricsGrpcServiceTest.java
data-prepper-plugins/otel-metrics-source/src/test/java/org/opensearch/dataprepper/plugins/source/otelmetrics/OTelMetricsSourceTest.java
data-prepper-plugins/otel-trace-source/src/main/java/org/opensearch/dataprepper/plugins/source/oteltrace/OTelTraceGrpcService.java
data-prepper-plugins/otel-trace-source/src/main/java/org/opensearch/dataprepper/plugins/source/oteltrace/OTelTraceSource.java
data-prepper-plugins/otel-trace-source/src/test/java/org/opensearch/dataprepper/plugins/source/oteltrace/OTelTraceGrpcServiceTest.java
data-prepper-plugins/otel-trace-source/src/test/java/org/opensearch/dataprepper/plugins/source/oteltrace/OTelTraceSourceTest.java

When a request hits an Armeria server and cannot be processed within the request_timeout, a RequestTimeoutException occurs. Currently this case returns a 503 to the client. This PR fixes that by adding a custom exception handler to the push-based sources that properly handles RequestTimeoutExceptions.
As part of this work, I stumbled upon a couple other issues/quirks of the Armeria servers
* Requests that are queued in the backend service's BlockingTaskExecutor will still be executed even if the request has already timed out. This adds unnecessary load to the pipeline by trying to process requests that have already returned a 503 (now 408/429 depending on http vs grpc) to the client. Added a check that a request is not timed out before attempting to process it.
* The HTTP source gives 80% …

Centralize exception handling and fix behavior for RequestTimeoutException

---

data-prepper-plugins/key-value-processor/README.md
data-prepper-plugins/key-value-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/keyvalue/KeyValueProcessor.java
data-prepper-plugins/key-value-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/keyvalue/KeyValueProcessorConfig.java
data-prepper-plugins/key-value-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/keyvalue/KeyValueProcessorTests.java

A hash specifying the default keys and their values which should be added to the event in case these keys do not exist in the source field being parsed.
#891 

Default keys

---

data-prepper-plugins/dynamodb-source-coordination-store/src/main/java/org/opensearch/dataprepper/plugins/sourcecoordinator/dynamodb/DynamoDbSourceCoordinationStore.java
data-prepper-plugins/dynamodb-source-coordination-store/src/test/java/org/opensearch/dataprepper/plugins/sourcecoordinator/dynamodb/DynamoDbSourceCoordinationStoreTest.java

Previously, if TTL was enabled on the dynamo db store for source coordination, only COMPLETED partitions would get a TTL and expire after the duration specified in the config.
This change makes it so that the TTL is set on every item in the store on item creation and extended when the item is updated, not just the COMPLETED partitions.

Add ttl to all dynamo source coordination store items on creation, not just when they are COMPLETED

---

data-prepper-plugins/cloudwatch-logs/src/main/java/org/opensearch/dataprepper/plugins/sink/cloudwatch_logs/client/CloudWatchLogsDispatcher.java
data-prepper-plugins/cloudwatch-logs/src/test/java/org/opensearch/dataprepper/plugins/sink/cloudwatch_logs/client/UploaderTest.java

This change aims to fix the problem with updating metric counters in the CloudWatch Logs Sink when no event handles are present. It removes the dependency on the counters to increment by the number of events passed in instead of event handles passed in.
This will resolve the issue found in [BUG] CloudWatch Logs Sink not generating LogEventSuccessMetrics #3113

Fixed issue with CloudWatchLogMetrics not updating counters when no event handles are present.

---

data-prepper-api/build.gradle
data-prepper-core/build.gradle
data-prepper-expression/build.gradle
data-prepper-logstash-configuration/build.gradle
data-prepper-plugins/aggregate-processor/build.gradle
data-prepper-plugins/anomaly-detector-processor/build.gradle
data-prepper-plugins/cloudwatch-logs/build.gradle
data-prepper-plugins/common/build.gradle
data-prepper-plugins/date-processor/build.gradle
data-prepper-plugins/failures-common/build.gradle
data-prepper-plugins/geoip-processor/build.gradle
data-prepper-plugins/http-sink/build.gradle
data-prepper-plugins/kafka-plugins/build.gradle
data-prepper-plugins/log-generator-source/build.gradle
data-prepper-plugins/opensearch-source/build.gradle
data-prepper-plugins/opensearch/build.gradle
data-prepper-plugins/otel-logs-source/build.gradle
data-prepper-plugins/otel-metrics-raw-processor/build.gradle
data-prepper-plugins/otel-metrics-source/build.gradle
data-prepper-plugins/otel-proto-common/build.gradle
data-prepper-plugins/otel-trace-source/build.gradle
data-prepper-plugins/prometheus-sink/build.gradle
data-prepper-plugins/rss-source/build.gradle
data-prepper-plugins/s3-sink/build.gradle
data-prepper-plugins/s3-source/build.gradle
data-prepper-plugins/sns-sink/build.gradle
data-prepper-plugins/translate-processor/build.gradle
settings.gradle

We have a number of dependabot PRs to update commons-lang3. This PR should help reduce that to using only one version.
* Adds Apache `commons-lang3` to the Gradle version catalog
* Updates `commons-lang3` to use 3.13.0
N/A

Adds Apache commons-lang3 to Gradle version catalog

---

.github/workflows/opensearch-sink-opendistro-integration-tests.yml
data-prepper-plugins/opensearch/src/integrationTest/java/org/opensearch/dataprepper/plugins/sink/opensearch/DeclaredOpenSearchVersion.java
data-prepper-plugins/opensearch/src/integrationTest/java/org/opensearch/dataprepper/plugins/sink/opensearch/DeclaredOpenSearchVersionTest.java
data-prepper-plugins/opensearch/src/integrationTest/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSinkIT.java

This PR 
* adds integ test coverage on opensearch sink for ODFE 0.10.0 backend (ES 6.8 engine)
* properly disable test cases that does not apply under ES 6
Resolves #3126 

MAINT: add integ test coverage for ODFE 0.10.0

---

data-prepper-plugins/avro-codecs/README.md

This PR shows a cleaner way to set the Avro schema using YAML. It also shows a working example for AWS VPC Flow Logs.
N/A

Updates Avro documentation with improved YAML and VPC Flow Log example

---

data-prepper-plugins/avro-codecs/src/main/java/org/opensearch/dataprepper/plugins/codec/avro/AvroOutputCodec.java
data-prepper-plugins/avro-codecs/src/main/java/org/opensearch/dataprepper/plugins/codec/avro/AvroSchemaParser.java
data-prepper-plugins/avro-codecs/src/main/java/org/opensearch/dataprepper/plugins/codec/avro/AvroSchemaParserFromS3.java
data-prepper-plugins/avro-codecs/src/test/java/org/opensearch/dataprepper/plugins/codec/avro/AvroOutputCodecTest.java

This PR has two major updates:
* When starting Data Prepper, validate the provided schema. Prior to this PR it was happening only when an event is received.
* When a field does not exist in the Avro schema return an explicit exception. Prior to this PR, it was some vague message that was not possible to track down.
Additionally, this PR includes some code clean-up.
N/A

Improved Avro error reporting related to schemas

---

data-prepper-plugins/kafka-plugins/src/integrationTest/java/org/opensearch/dataprepper/plugins/kafka/source/KafkaSourceJsonTypeIT.java
data-prepper-plugins/kafka-plugins/src/integrationTest/java/org/opensearch/dataprepper/plugins/kafka/source/KafkaSourceMultipleAuthTypeIT.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/configuration/KafkaSourceConfig.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaSourceCustomConsumer.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/TopicPartitionCommitTracker.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/source/KafkaSource.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/util/KafkaSourceSecurityConfigurer.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/util/KafkaTopicMetrics.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaSourceCustomConsumerTest.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/consumer/TopicPartitionCommitTrackerTest.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/util/KafkaTopicMetricsTests.java

Add metrics to Kafka.
1. Each thread maintains a local copy of counters which are put in a topic level common data structure every 60 seconds.
2. These metrics are aggregated across different threads of a topic, every 60 seconds and are exported to PluginMetrics
Resolves #3112 
#3112 

Add metrics to Kafka Source

---

data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateActionSynchronizer.java
data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateGroupManager.java
data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateIdentificationKeysHasher.java
data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateProcessor.java
data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateActionSynchronizerTest.java
data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateGroupManagerTest.java
data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateProcessorTest.java
data-prepper-plugins/anomaly-detector-processor/build.gradle
data-prepper-plugins/anomaly-detector-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/anomalydetector/AnomalyDetectorMode.java
data-prepper-plugins/anomaly-detector-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/anomalydetector/AnomalyDetectorProcessor.java
data-prepper-plugins/anomaly-detector-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/anomalydetector/AnomalyDetectorProcessorConfig.java
data-prepper-plugins/anomaly-detector-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/anomalydetector/modes/RandomCutForestMode.java
data-prepper-plugins/anomaly-detector-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/anomalydetector/AnomalyDetectorProcessorTests.java
data-prepper-plugins/anomaly-detector-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/anomalydetector/modes/RandomCutForestModeTests.java
data-prepper-plugins/common/src/main/java/org/opensearch/dataprepper/plugins/hasher/IdentificationKeysHasher.java
data-prepper-plugins/common/src/test/java/org/opensearch/dataprepper/plugins/hasher/IdentificationKeysHasherTest.java

Anomaly Detector plugin will now take an optional value identification_keys. This value will act the same as it does in the aggregate processor, and will cause the plugin to create a different forest model for each unique value/combination of identification_keys.

Adding cardinality key support for AD processor

---

data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3ScanPartitionCreationSupplier.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/ScanObjectWorker.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/configuration/S3ScanBucketOption.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/configuration/S3ScanScanOptions.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/configuration/S3ScanSchedulingOptions.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/S3ScanPartitionCreationSupplierTest.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/configuration/S3ScanScanOptionsTest.java

This change adds scheduled scan support to s3 scan.
The default behavior, with no scheduling configured, is to scan the buckets one time, and then to stop scanning after that
When `scheduling` is configured, the buckets will be scanned continuously at a minimum rate specified by `interval`, up to the `count` number of times.  To handle deduplication for multiple scans without utilizing source coordination entirely, the lastModifiedAt timestamp of the most recent object that was scanned in a previous scan will be stored in the global state to filter out objects with lastModifiedAt times before this time.
For more information on following Developer Certificate of Origin and …

Add support for scheduled scan to s3 scan

---

data-prepper-plugins/anomaly-detector-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/anomalydetector/AnomalyDetectorProcessorConfig.java

I made the mistake of not testing previous changes without omitting the `identification_keys` value from config. When I tried that I got a NPE since there no default is set. This causes a breaking change to anyone currently using the plugin.
This change adds that default value.

Add default value to cardinality keys

---

data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/configuration/TopicConfig.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaSourceCustomConsumer.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/source/KafkaSource.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/util/KafkaSourceSecurityConfigurer.java

This change contains
1. Glue registry fixes to create Deserializer with credentials so that service account can access user account's GLUE registries
2. Fixed a bug in `getBootStrapServersForMsk()` which is looping when there is no error.

Glue registry fixes. Fixed a bug in getMSKBootstrapServers

---

data-prepper-plugins/anomaly-detector-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/anomalydetector/AnomalyDetectorProcessor.java
data-prepper-plugins/anomaly-detector-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/anomalydetector/AnomalyDetectorProcessorTests.java
data-prepper-plugins/anomaly-detector-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/anomalydetector/modes/RandomCutForestModeTests.java

Inherent variability in the RCF algorithm was causing intermittent failures in a test that expected exactly one anomaly. That has been changed to an expected range of 1-3, which all values fell between over 100+ runs of the unit test.
RCFInstances metric changed from counter to gauge, to better monitor current cardinality. Name simplified.

Fix flakey test caused by RCF variance. Update metric for RCF Instances

---

data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/plugins/InMemorySinkAccessor.java

The integration tests were sometimes throwing a ConcurrentModificationException on the list provided by `InMemorySinkAccessor`. Wrap that in a new list so that it won't be modified when checking it.
Resolves #3139

Fix flaky integration test in conditional routing integration tests

---

data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/ParseTreeEvaluatorListenerTest.java
data-prepper-plugins/otel-logs-source/src/test/java/org/opensearch/dataprepper/plugins/source/otellogs/OTelLogsSourceTest.java

* ParseTreeEvaluatorListenerTest appears to be using negative values sometimes, which seems to be unsupported. 
```
org.opensearch.dataprepper.expression.ExpressionCoercionException: Unsupported terminal node type symbol string: '-'
at app//org.opensearch.dataprepper.expression.ParseTreeCoercionService.coercePrimaryTerminalNode(ParseTreeCoercionService.java:86)
at app//org.opensearch.dataprepper.expression.ParseTreeEvaluatorListener.visitTerminal(ParseTreeEvaluatorListener.java:69)
at app//org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:29)
at app//org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
at app//org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
at app//org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.ja …
```

Fixes two flaky unit tests that have failed recently

---

data-prepper-plugins/failures-common/src/main/java/org/opensearch/dataprepper/plugins/dlq/s3/S3DlqWriterConfig.java
data-prepper-plugins/failures-common/src/test/java/org/opensearch/dataprepper/plugins/dlq/s3/S3DlqWriterConfigTest.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/S3SinkConfig.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/s3/S3SinkConfigTest.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/configuration/S3ScanBucketOption.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/ScanOptionsTest.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/configuration/S3ScanBucketOptionTest.java

Support `s3://` prefix in s3 bucket name
resolves #2143

Support s3:// prefix

---

data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/compression/CompressionOption.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/compression/NoneCompressionEngine.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/compression/SnappyCompressionEngine.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/s3/compression/CompressionOptionTest.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/s3/compression/SnappyCompressionEngineTest.java

Support Snappy compression when writing data in the S3 sink.
Additionally:
* Adds a missing unit test for `CompressionOption`
* Makes other compression engine classes package private
Resolves #3154

Snappy as a compression option in the S3 sink

---

data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/S3SinkService.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/s3/S3SinkServiceTest.java

Fixes a bug where the S3 sink tries to write to a closed stream if data is flushed mid batch.
Resolves #3160 
- [N/A] New functionality has a documentation issue. Please link to it in this PR.

Fix S3 sink writing to closed stream exception

---

data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/configuration/ObjectKeyOptions.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/s3/configuration/ObjectKeyOptionsTest.java

Use `HH` instead of `hh` in the default format to get the 24 hour rather than 12 hour timestamp. Also add `Z` to denote UTC
Partially #3158 
- [N/A] New functionality has a documentation issue. Please link to it in this PR.

Fix timestamp to use 24 hour instead of 12 hour

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/breaker/HeapCircuitBreaker.java

Rewords the log message to be more clear that the circuit breaker has not been tripped, but is configured with a certain heap limit

Reword circuit breaker configuration log message

---

data-prepper-plugins/kafka-plugins/src/integrationTest/java/org/opensearch/dataprepper/plugins/kafka/source/KafkaSourceJsonTypeIT.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/configuration/AuthConfig.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/configuration/TopicConfig.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaSourceCustomConsumer.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/util/MessageFormat.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/configuration/TopicConfigTest.java
data-prepper-plugins/kafka-plugins/src/test/resources/sample-pipelines-1.yaml
data-prepper-plugins/kafka-plugins/src/test/resources/sample-pipelines.yaml

This change contains the following fixes
1. Change Message Format types to lowercase "JSON" -> "json", "AVRO" -> "avro", "PLAINTEXT" -> "plaintext"
2. Fix  Max poll interval from 300000 seconds to 300000 milliseconds.
3. Fix "kafka_partition" attribute value stored in the event metadata to be string. 
4. Introduce 10 second delay when an exception is encountered during consumer poll …

Minor fixes to Kafka Source

---

data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3ScanPartitionCreationSupplier.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/ScanOptions.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/configuration/S3ScanBucketOptions.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/ScanOptionsTest.java

- All objects will be included if none of the `start_time`, `end_time` and `range` are configured
- all objects after `start_time` are included if only `start_time` is configured
- all objects before `end_time` are included if only `end_time` is configured
- all objects are included i only `range` is included, as it's not possible to build a time range without start or end time. 
If any of the following combinations is configured
1. `start_time`, `range` at global level and `end_time` at bucket level, only end_time is considered and all objects before end_time will be included in scan
2. `end_time`, `range` at global level and `start_time` at bucket level, only `start_time` is considered and all objects after `start_time` will be included in scan
3. `start_time`, `end_time` at global …

Support other scan time configs= combinations

---

data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3ScanPartitionCreationSupplier.java

Track when single scan is complete to only log once when the scan has already been completed

Only log that the scan is complete one time for s3 scan

---

data-prepper-plugins/anomaly-detector-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/anomalydetector/AnomalyDetectorProcessor.java
data-prepper-plugins/anomaly-detector-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/anomalydetector/AnomalyDetectorProcessorConfig.java
data-prepper-plugins/anomaly-detector-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/anomalydetector/AnomalyDetectorProcessorTests.java

Added a configurable `cardinality_limit` to set the max number of RCF instances a node can produce. Created a metric to track overflow, or number of RCF instances that could not be created due to this limit.

Add limit to cardinality key, and metric for cardinality overflow

---

data-prepper-plugins/aggregate-processor/README.md
data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/CountAggregateAction.java
data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/HistogramAggregateAction.java
data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/CountAggregateActionTest.java
data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/HistogramAggregateActionTests.java

Add Exemplars to metrics generated in aggregate processor
Resolves #3164 
Resolves #3164 

Add Exemplars to metrics generated in aggregate processor

---

data-prepper-plugins/kafka-plugins/README.md
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/configuration/TopicConfig.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaSourceCustomConsumer.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/source/KafkaSource.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/configuration/TopicConfigTest.java
data-prepper-plugins/kafka-plugins/src/test/resources/sample-pipelines.yaml

Update Kafka source/sink to use ByteCount
Modified Kafka Topic Configuration to use ByteCount for bytes related configuration.
Resolves #3116 
Resolves #3116 

Update Kafka source/sink to use ByteCount

---

data-prepper-plugins/kafka-plugins/src/integrationTest/java/org/opensearch/dataprepper/plugins/kafka/source/KafkaSourceJsonTypeIT.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaSourceCustomConsumer.java

Retry without seeking incase of AWSSchemaRegistryException
When reading records from MSK, if a RecordDeserializationException occurs with cause AWSSchemaRegistryException, we should retry with a delay instead of seeking past the record.

Retry without seeking incase of AWSSchemaRegistryException

---

data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/S3Sink.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/S3SinkService.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/s3/S3SinkServiceTest.java

Any data left in the S3 sink buffer after traffic stops won't be flushed to S3 sink the threshold check is never reached again. This PR changes the behavior to continue calling `S3SinkService::output` even if the current processing batch is empty to check if the previously buffered data should now be flushed.
- [N/a] New functionality has a documentation issue. Please link to it in this PR.
- [N/a] New functionality has javadoc added

Continue calling S3SinkService::output even if records is empty to flush stale batches

---

.github/workflows/release.yml

Automatically promote releases by creating a draft release of the build with release metadata. This will trigger a Jenkins job on https://build.ci.opensearch.org/ to promote. Performing this build will require the approval of two maintainers of the project.
Resolves #2122.

Automatically promote releases after approving issue

---

data-prepper-plugins/opensearch/README.md
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/ConnectionConfiguration.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/ConnectionConfigurationTests.java

Elasticsearch 6 engine does not enable compression by default. See https://docs.aws.amazon.com/opensearch-service/latest/developerguide/gzip.html
This PR sets the default value of enable_request_compression according to the value of distribution_version.

FIX: default value for enable_request_compression when ES6 is used in opensearch sink

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/configuration/SinkModel.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/configuration/SinkModelTest.java
data-prepper-plugins/opensearch/README.md

- Remove adding `/` at start of key and removing `/` at end of key.
- Adds validations to not support `/` in keys
partially resolves #3163

Added validations in include and exclude keys

---

data-prepper-plugins/avro-codecs/src/main/java/org/opensearch/dataprepper/avro/AvroAutoSchemaGenerator.java
data-prepper-plugins/avro-codecs/src/main/java/org/opensearch/dataprepper/avro/AvroEventConverter.java
data-prepper-plugins/avro-codecs/src/main/java/org/opensearch/dataprepper/avro/SchemaChooser.java
data-prepper-plugins/avro-codecs/src/main/java/org/opensearch/dataprepper/avro/SchemaGenerationException.java
data-prepper-plugins/avro-codecs/src/main/java/org/opensearch/dataprepper/plugins/codec/avro/AvroOutputCodec.java
data-prepper-plugins/avro-codecs/src/test/java/org/opensearch/dataprepper/avro/AvroAutoSchemaGeneratorTest.java
data-prepper-plugins/avro-codecs/src/test/java/org/opensearch/dataprepper/avro/AvroEventConverterTest.java
data-prepper-plugins/avro-codecs/src/test/java/org/opensearch/dataprepper/avro/PrimitiveClassesToTypesArgumentsProvider.java
data-prepper-plugins/avro-codecs/src/test/java/org/opensearch/dataprepper/avro/SchemaChooserTest.java
data-prepper-plugins/avro-codecs/src/test/java/org/opensearch/dataprepper/plugins/codec/avro/AvroOutputCodecTest.java
data-prepper-plugins/s3-sink/build.gradle
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/codec/parquet/ParquetOutputCodec.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/codec/parquet/S3OutputFile.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/codec/parquet/ParquetOutputCodecTest.java

This adds two conceptual changes:
* Both Avro and Parquet can provide `null` values when the schema is defined to allow nullable values. This is supported for primitive types, records, and arrays.
* When auto-generating an Avro schema, generate it to include nullable unions. This is true for primitive types, records, and arrays.
Internally, it refactors both the Avro and Parquet OutputCodecs to use a common set of classes for Avro schema generation and Avro record conversion. This is part of the `avro-codecs` project. Thus, the S3 sink depends on this project now. It also prefers using the Avro SDK for schema models instead of raw strings.
Resolves part of #3158.
For more …

Nullable values/schemas in Avro and Parquet output codecs

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/sink/OutputCodecContext.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/sink/OutputCodecContextTest.java
data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/codec/json/JsonOutputCodec.java
data-prepper-plugins/parse-json-processor/src/test/java/org/opensearch/dataprepper/plugins/codec/json/JsonOutputCodecTest.java

This fixes two problems with the `json` OutputCodec:
1. Serialize data correctly. Previously, it was serializing everything as text.
2. Support include/exclude keys correctly. Previously, only exclude was working
Additionally, this adds logic in OutputCodecContext to determine if a key can be used. This will be used in other codecs as well.
Resolves #3146

Corrects the JSON output codec - type support and include/exclude keys

---

release/build-resources.gradle

This PR updates to the latest current version of JDK 17 - `17.0.8+7`.
https://github.com/adoptium/temurin17-binaries/releases/tag/jdk-17.0.8%2B7
N/A

Updates the Data Prepper tar.gz artifact to include JDK 17.0.8+7

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/log/JacksonOtelLog.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/log/JacksonOtelLogTest.java
data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parsejson/ParseJsonProcessor.java
data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parsejson/ParseJsonProcessorConfig.java
data-prepper-plugins/parse-json-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/parsejson/ParseJsonProcessorConfigTest.java
data-prepper-plugins/parse-json-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/parsejson/ParseJsonProcessorTest.java

Fixes #3184 by:
- Catch ClassCastException in JacksonOtelLog.toJsonString()
- Add `overwrite_if_exists` option to parse-json processor. It defaults to true to avoid breaking change. Set it to false will prevent fields from being overwritten by the processor.
Resolves #3184

Fix uncaught exception causing pipeline shutdown 

---

data-prepper-plugins/s3-sink/src/integrationTest/java/org/opensearch/dataprepper/plugins/sink/s3/S3SinkServiceIT.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/ExtensionProvider.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/KeyGenerator.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/S3Sink.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/StandardExtensionProvider.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/compression/CompressionOption.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/s3/KeyGeneratorTest.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/s3/StandardExtensionProviderTest.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/s3/compression/CompressionOptionTest.java

Supports adding the compression extension for keys generated for the S3 sink. This also avoids adding the extension when the codec supports internal compression.
Resolves #3158

Correctly add compression extensions to the generated S3 sink keys

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/sink/OutputCodecContext.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/sink/OutputCodecContextTest.java
data-prepper-plugins/avro-codecs/src/main/java/org/opensearch/dataprepper/avro/AvroAutoSchemaGenerator.java
data-prepper-plugins/avro-codecs/src/main/java/org/opensearch/dataprepper/avro/AvroEventConverter.java
data-prepper-plugins/avro-codecs/src/test/java/org/opensearch/dataprepper/avro/AvroAutoSchemaGeneratorTest.java
data-prepper-plugins/avro-codecs/src/test/java/org/opensearch/dataprepper/avro/AvroEventConverterTest.java

Corrects include/exclude key behavior for Avro/Parquet codecs. This also adds a new method `shouldNotIncludeKey` to `OutputCodecContext`. This is helpful for unit testing because it requires less mocking.
N/A

Corrects the output codecs for Avro/Parquet to use the include/exclude keys

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/typeconverter/BooleanConverter.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/typeconverter/DoubleConverter.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/typeconverter/IntegerConverter.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/typeconverter/StringConverter.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/typeconverter/StringConverterTests.java
data-prepper-plugins/mutate-event-processors/README.md
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/ConvertEntryTypeProcessor.java
data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/ConvertEntryTypeProcessorConfig.java
data-prepper-plugins/mutate-event-processors/src/test/java/org/opensearch/dataprepper/plugins/processor/mutateevent/ConvertEntryTypeProcessorTests.java

Fix IllegalArgumentException and return object.toString
Resolves #3135 

Fix: IllegalArgument Exception in String converter

---

data-prepper-plugins/s3-sink/src/integrationTest/java/org/opensearch/dataprepper/plugins/sink/s3/S3SinkServiceIT.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/S3Sink.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/S3SinkService.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/ThresholdCheck.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/accumulator/Buffer.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/accumulator/CompressionBuffer.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/accumulator/InMemoryBuffer.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/accumulator/LocalFileBuffer.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/accumulator/MultipartBuffer.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/s3/S3SinkServiceTest.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/s3/ThresholdCheckTest.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/s3/accumulator/CompressionBufferTest.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/s3/accumulator/InMemoryBufferTest.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/s3/accumulator/LocalFileBufferTest.java

This PR includes changes which reduce the total time to build the `s3-sink` project from over 2minutes to about 15 seconds on my machine.
* Use the Duration class instead of a nebulous long to send duration times around. This can allow for millisecond resolution.
* Inject the retry sleep time into `S3SinkService` so that unit test can take much less time.
* Using mocking in `ThresholdCheckTest` to avoid unnecessary sleeps.
N/A

Updates to the S3 sink to speed up the unit test/build time

---

.github/workflows/release.yml
jenkins/release.jenkinsFile

This PR adds below changes:
- Add input type as boolean to GHA release workflow
- Add permissions required by the token to create a draft release
- Add refactored jenkins workflow file to this repository. See old workflow file [here](https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/data-prepper/release-data-prepper-all-artifacts.jenkinsfile)
Once this PR is merged I'll take care of adding the necessary webhook token.
Resolves https://github.com/opensearch-project/opensearch-build/issues/3842 …

Add jenkins release workflow and refactor GHA workflow

---

data-prepper-plugins/avro-codecs/src/main/java/org/opensearch/dataprepper/plugins/codec/avro/AvroOutputCodecConfig.java
data-prepper-plugins/avro-codecs/src/test/java/org/opensearch/dataprepper/plugins/codec/avro/AvroOutputCodecConfigTest.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/codec/parquet/ParquetOutputCodecConfig.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/codec/parquet/ParquetOutputCodecConfigTest.java

The current design of the auto-schema generation for the Avro/Parquet codecs will make the default behavior automatically generate a schema. Users may not be aware that this is happening.
This PR adds a new field `auto_schema` to enable the feature.
Thus, the user can configure a codec as such:
```
s3:
codec:
parquet:
auto_schema: true
```
N/A

Adds an auto_schema flag to Avro/Parquet codecs

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/JacksonEvent.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/event/JacksonEventTest.java

This fixes the `ndjson` output codec to work correctly with include/exclude keys.
N/A

Normalize the include/exclude keys in the JacksonEvent implementation

---

data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/S3SinkService.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/s3/S3SinkServiceTest.java

Currently, failures in the S3 sink may cause the entire pipeline to crash. This PR resolves that by catching exceptions for each event and dropping that event only.
Resolves #3202

Catch exceptions when writing to the output codec and drop the event.

---

data-prepper-plugins/avro-codecs/README.md
data-prepper-plugins/s3-sink/README.md

Cleans out the README.md for the Avro README and S3 sink by pointing to the documentation.
Resolves #3162

Updates documentation for the Avro codec and S3 sink. 

---

data-prepper-plugins/s3-sink/src/integrationTest/java/org/opensearch/dataprepper/plugins/sink/s3/InMemoryBufferScenario.java
data-prepper-plugins/s3-sink/src/integrationTest/java/org/opensearch/dataprepper/plugins/sink/s3/LocalFileBufferScenario.java
data-prepper-plugins/s3-sink/src/integrationTest/java/org/opensearch/dataprepper/plugins/sink/s3/MultiPartBufferScenario.java
data-prepper-plugins/s3-sink/src/integrationTest/java/org/opensearch/dataprepper/plugins/sink/s3/S3SinkIT.java
data-prepper-plugins/s3-sink/src/integrationTest/java/org/opensearch/dataprepper/plugins/sink/s3/SizeCombination.java

This PR makes improvements to the S3 sink tests. It reduces sample size, removes some tests which would often cause the JVM to run out of memory, and removes redundant tests. It also sets up a combination for codecs which will not cause the scenarios to grow out of hand.
N/A

Improve the S3 sink integration tests combinations

---

.github/workflows/release.yml

* The conditional for the promotion job now fails if the build job fails.
* Increased the build timeout to 50 minutes since our builds take so long.
* Added permission to write GitHub issues.
* Documentation correction.
N/A - working toward release

Improvements in the release GitHub Action

---

.github/CODEOWNERS

The release build does not work because the user @cmanning09 doesn't have write access to the repository. This PR removes him from the CODEOWNERS to allow the release build to proceed.
Failure:
https://github.com/opensearch-project/data-prepper/actions/runs/5956094674/job/16156990189
N/A

Removes @cmanning09 from the CODEOWNERS file to allow release builds

---

data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaSourceCustomConsumer.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/TopicPartitionCommitTracker.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/source/KafkaSource.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaSourceCustomConsumerTest.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/consumer/TopicPartitionCommitTrackerTest.java

This PR fixes following issues:
- Commit offsets when a kafka partition's beginning offset is non-zero.
- Fix numRecordsCommitted metric.
- Fix shutdown sequence for all topics+workers.
Following tests were conducted with these changes:
> Ingest 10M records from a kafka topic + group membership mutations.
> Ingest 12 M records from 2 kafka topics in single pipeline.
> Ingest 10M records from 2 different topics in 2 different pipelines.
> 2 pipelines part of same consumer group ingesting 10 M records.
> Shutdown pipeline in the middle of ingestion and resume and make sure all data is ingested.
> Ingest data without acknowledgments enabled.
> Ingest data with auto_offset_reset=earliest/latest.
Resolves #3231 
By submitting this pull request, I confirm that my contribution is made under the …

Fix for kafka source not committing offsets issue #3231

---

data-prepper-plugins/avro-codecs/src/main/java/org/opensearch/dataprepper/avro/AbstractAvroEventConverterTemplate.java
data-prepper-plugins/avro-codecs/src/main/java/org/opensearch/dataprepper/avro/AvroEventConverter.java
data-prepper-plugins/avro-codecs/src/main/java/org/opensearch/dataprepper/avro/EventDefinedAvroEventConverter.java
data-prepper-plugins/avro-codecs/src/main/java/org/opensearch/dataprepper/avro/SchemaDefinedAvroEventConverter.java
data-prepper-plugins/avro-codecs/src/main/java/org/opensearch/dataprepper/plugins/codec/avro/AvroOutputCodec.java
data-prepper-plugins/avro-codecs/src/test/java/org/opensearch/dataprepper/avro/AvroEventConverterTest.java
data-prepper-plugins/avro-codecs/src/test/java/org/opensearch/dataprepper/avro/EventDefinedAvroEventConverterTest.java
data-prepper-plugins/avro-codecs/src/test/java/org/opensearch/dataprepper/avro/SchemaDefinedAvroEventConverterTest.java
data-prepper-plugins/avro-codecs/src/test/java/org/opensearch/dataprepper/plugins/codec/avro/AvroOutputCodecTest.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/codec/parquet/ParquetOutputCodec.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/codec/parquet/ParquetOutputCodecTest.java

This PR makes a fundamental change to how the Avro-based codecs (Avro and Parquet) handle mapping Events to Avro records.
There are now two cases which are handled differently:
1. If the pipeline author defines a schema, this takes precedence over the incoming data. Thus, extra fields will be ignored.
2. If the schema is auto-generated, then future events must match the schema. Thus, extra fields will drop the events.
N/A

Behavioral change to Avro codecs and schema handling

---

data-prepper-plugins/s3-sink/src/integrationTest/java/org/opensearch/dataprepper/plugins/sink/s3/InMemoryBufferScenario.java
data-prepper-plugins/s3-sink/src/integrationTest/java/org/opensearch/dataprepper/plugins/sink/s3/ParquetOutputScenario.java
data-prepper-plugins/s3-sink/src/integrationTest/java/org/opensearch/dataprepper/plugins/sink/s3/S3SinkIT.java
data-prepper-plugins/s3-sink/src/integrationTest/java/org/opensearch/dataprepper/plugins/sink/s3/SizeCombination.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/codec/parquet/ParquetOutputCodec.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/codec/parquet/S3OutputStream.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/S3Sink.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/S3SinkService.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/accumulator/ByteArrayPositionOutputStream.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/accumulator/CodecBuffer.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/accumulator/CodecBufferFactory.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/accumulator/InMemoryBuffer.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/codec/BufferedCodec.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/codec/parquet/ParquetOutputCodecTest.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/s3/accumulator/ByteArrayPositionOutputStreamTest.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/s3/accumulator/CodecBufferTest.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/s3/accumulator/InMemoryBufferTest.java
data-prepper-plugins/s3-sink/src/test/resources/simplelogger.properties

Fixes the `parquet` output codec's size determination. Previously, it was not providing the correct size calculation and thus the `threshold.maximum_size` was not working.
This codec is actually writing data into an in-memory buffer managed by the `ParquetWriter`. Only at the end does the `ParquetWriter` write data to the `OutputStream`. So relying on the size of the `OutputStream` was incorrect.
I solved this by adding a new interface `BufferedCodec` which indicates that the codec itself has a buffer. The new `CodecBuffer` class will use that buffer size instead.
Additionally, I found that since the `parquet` codec is writing in-memory and then flushing, it isn't really using the `multipart` buffer as expected. Thus, I changed the validations such that this codec can only be used with …

Fixes a bug with the S3 parquet output codec size calculation

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/codec/OutputCodec.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/codec/OutputCodecTest.java
data-prepper-plugins/avro-codecs/src/main/java/org/opensearch/dataprepper/plugins/codec/avro/AvroOutputCodec.java
data-prepper-plugins/avro-codecs/src/test/java/org/opensearch/dataprepper/plugins/codec/avro/AvroOutputCodecTest.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/codec/parquet/ParquetOutputCodec.java
data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/S3Sink.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/codec/parquet/ParquetOutputCodecTest.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/s3/S3SinkTest.java

Disallows adding an S3 sink with an Avro or Parquet codec which uses both a user-defined schema and include/exclude keys. Auto-schema may still use include/exclude keys.
Resolves #3253.

Disallow the combination of a user-defined schema and include/exclude keys

---

data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaSourceCustomConsumer.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/util/LogRateLimiter.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaSourceCustomConsumerTest.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/util/LogRateLimiterTest.java

- Fixed CommitTracker to track err offsets that failed to deserialize
-  Added ratelimiter for err logs to avoid flooding logs in case of unexpected err condition.
Resolves #3247

Fix for kafka source issue #3247 (offset commit stops on deserialization error)

---

data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaSourceCustomConsumer.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaSourceCustomConsumerTest.java

- Fixed Aws glue exception handling to retry only in case of AccessDenied exception.
- Reduced Thread.sleep() to 100ms from 10s in Unit Tests requiring acknowledgements.
Resolves #3264
- Added UT case
- Manually tested by removing glue permissions and verified poll() is retried as expected until permissions are added back.
- Manually injected plaintext records into Kafka topic with avro schema and verified they are skipped and stream processing is not blocked.

Fix for kafka source issue #3264 (aws glue excetion handling)

---

jenkins/release.jenkinsFile

The new and recent run for data-prepper release failed https://build.ci.opensearch.org/job/release-data-prepper/3/ in maven stage. This was due to downloadArtifacts method unable to find the VERSION variable. This change fixes it. Also since we already released on other platforms disabling those stages to avoid re-release. 
I'll be creating another PR after release to enable these stages back.

Fix jenkins maven publishing stage and disable other stages for now

---

release/release-notes/data-prepper.change-log-2.4.0.md

Generated changelog for Data Prepper 2.4.0.
Used this tool:
https://github.com/ariatemplates/git-release-notes
Commands:
```
git switch 2.4
git pull
git-release-notes 2.3.2..HEAD markdown > release/release-notes/data-prepper.change-log-2.4.0.md
git switch main
```
N/A

Adds Data Prepper 2.4.0 changelog.

---

build.gradle

Updates the Checkstyle tool version to 10.12.3 which is the current latest.
This may help with a Guava vulnerability as it uses Guava 32.0.1.
Snippet from `./gradlew dependencies`:
```
\--- com.puppycrawl.tools:checkstyle:10.12.3
+--- info.picocli:picocli:4.7.4
+--- org.antlr:antlr4-runtime:4.11.1
+--- commons-beanutils:commons-beanutils:1.9.4
|    \--- commons-collections:commons-collections:3.2.2
+--- com.google.guava:guava:32.0.1-jre
```
N/A

Checkstyle to to 10.12.3

---

data-prepper-api/build.gradle
data-prepper-plugins/avro-codecs/build.gradle
data-prepper-plugins/common/build.gradle
data-prepper-plugins/csv-processor/build.gradle
data-prepper-plugins/newline-codecs/build.gradle
data-prepper-plugins/parquet-codecs/build.gradle
data-prepper-plugins/parse-json-processor/build.gradle
data-prepper-plugins/s3-source/build.gradle

This PR removes Hadoop HDFS and YARN, neither of which are used. Map-reduce is needed when testing.
N/A

Removes some unnecessary dependencies in the S3 sink and Parquet codecs

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/log/JacksonOtelLog.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/log/OpenTelemetryLog.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/log/JacksonOtelLogTest.java
data-prepper-plugins/otel-proto-common/src/main/java/org/opensearch/dataprepper/plugins/otel/codec/OTelProtoCodec.java
data-prepper-plugins/otel-proto-common/src/test/java/org/opensearch/dataprepper/plugins/otel/codec/OTelProtoCodecTest.java
data-prepper-plugins/otel-proto-common/src/test/resources/test-request-log-is.json
data-prepper-plugins/otel-proto-common/src/test/resources/test-request-log.json

The OpenTelemetry Codec lacks support for the severity text. This oversight is corrected by extracting the field from the OTLP source data and copying it to a matching field in the JSON document. It tightly aligns with the already supported SeverityNumber field. This closes a gap in the OTLP logs data model mapping. Unit tests of codec and JSON mapping are adjusted for the added field.
The OpenTelemetry Codec lacks support for the severity text. This oversight is corrected by extracting the field from the OTLP source data and copying it to a matching field in the JSON document. It tightly aligns with the already supported `severityNumber` field. 
Resolves #3280 
For more …

Add Support for OTel Log SeverityText (#3280)

---

data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/OpenSearchService.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/OpenSearchSource.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/OpenSearchSourceConfiguration.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/NoSearchContextWorker.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/PitWorker.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/ScrollWorker.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/WorkerCommonUtils.java
data-prepper-plugins/opensearch-source/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/OpenSearchServiceTest.java
data-prepper-plugins/opensearch-source/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/OpenSearchSourceTest.java
data-prepper-plugins/opensearch-source/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/NoSearchContextWorkerTest.java
data-prepper-plugins/opensearch-source/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/PitWorkerTest.java
data-prepper-plugins/opensearch-source/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/ScrollWorkerTest.java

Adds acknowledgment support to the opensearch source

Add e2e acknowledgments support to opensearch source

---

data-prepper-plugins/opensearch-source/build.gradle
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/OpenSearchService.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/OpenSearchSource.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/metrics/OpenSearchSourcePluginMetrics.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/NoSearchContextWorker.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/PitWorker.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/ScrollWorker.java
data-prepper-plugins/opensearch-source/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/OpenSearchServiceTest.java
data-prepper-plugins/opensearch-source/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/OpenSearchSourceTest.java
data-prepper-plugins/opensearch-source/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/NoSearchContextWorkerTest.java
data-prepper-plugins/opensearch-source/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/PitWorkerTest.java
data-prepper-plugins/opensearch-source/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/ScrollWorkerTest.java

Adds the following metrics for the opensearch source
Counters
* documentsProcessed
* indicesProcessed
* processingErrors
Timer
* indexProcessingTime

Add metrics for the opensearch source

---

performance-test/build.gradle
performance-test/src/gatling/java/org/opensearch/dataprepper/test/performance/FixedClientSimulation.java
performance-test/src/gatling/java/org/opensearch/dataprepper/test/performance/HttpStaticLoadSimulation.java
performance-test/src/gatling/java/org/opensearch/dataprepper/test/performance/HttpsStaticLoadSimulation.java
performance-test/src/gatling/java/org/opensearch/dataprepper/test/performance/RampUpSimulation.java
performance-test/src/gatling/java/org/opensearch/dataprepper/test/performance/SingleRequestSimulation.java
performance-test/src/gatling/java/org/opensearch/dataprepper/test/performance/SlowBurnSimulation.java
performance-test/src/gatling/java/org/opensearch/dataprepper/test/performance/TargetRpsSimulation.java
performance-test/src/gatling/java/org/opensearch/dataprepper/test/performance/VariousGrokPatternsSimulation.java
performance-test/src/gatling/java/org/opensearch/dataprepper/test/performance/tools/AwsRequestSigner.java
performance-test/src/gatling/java/org/opensearch/dataprepper/test/performance/tools/Chain.java
performance-test/src/gatling/java/org/opensearch/dataprepper/test/performance/tools/PathTarget.java
performance-test/src/gatling/java/org/opensearch/dataprepper/test/performance/tools/Protocol.java
performance-test/src/gatling/java/org/opensearch/dataprepper/test/performance/tools/SignerProvider.java

This PR adds a few new capabilities to the Gatling performance test. It adds:
New configurations:
* Making requests over HTTPS instead of unencrypted HTTP - `-Dprotocol=https`.
* Modify the ingest path - `-Dpath=/my/path`.
* Sign requests with AWS SigV4 - `-Dauthentication=aws_sigv4 -Daws_region=us-east-2 -Daws_service=osis`.
This PR also includes some clean-up to the Gatling project.
Resolves #3308 
Resolves #3311 

Gatling performance test enhancements - HTTPS, path configuration, AWS SigV4

---

performance-test/src/gatling/java/org/opensearch/dataprepper/test/performance/tools/Templates.java
performance-test/src/gatling/resources/bodies/singleLog.json

The Gatling performance tests were sending a single digit for the day-of-month in the date format. This is incorrect and causing problems with typed Grok processing pipelines.
N/A

Need two digits for dates in the common Apache log format in Gatling

---

data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3ScanPartitionCreationSupplier.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/S3ScanPartitionCreationSupplierTest.java

Fixes a potential NPE in the s3 scan partition supplier
Resolves #3316 

Fix NPE in s3 scan partition supplier

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/sourcecoordination/LeaseBasedSourceCoordinator.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/sourcecoordination/LeaseBasedSourceCoordinatorTest.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/OpenSearchSource.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/OpenSearchIndexPartitionCreationSupplier.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3ScanPartitionCreationSupplier.java

Fixes a couple of issues related to the OpenSearch source
* The LeaseBasedSourceCoordinator is currently skipping the processing of new indices for the OpenSearch source because it returns instead of continues when being provided with a partition that already exists
* Potential NPE in `stop` method of the os source if it crashes before the OpenSearch service is initialized
* Add debug logs in the OpenSearch source supplier to log count of indices that are found from a cat/indices call

Fix issue of skipping new partitions/indices for the opensearch source

---

data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/NoSearchContextWorker.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/PitWorker.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/ScrollWorker.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/WorkerCommonUtils.java
data-prepper-plugins/opensearch-source/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/WorkerCommonUtilsTest.java

Adds exponential backoff and jitter for the opensearch source instead of waiting a standard 30 seconds when there are no indices to process, starting with 2.5 seconds and a max of 60 seconds.

Exponential backoff and jitter for opensearch source when no indices are available to process

---

CONTRIBUTING.md

Adds license headers to the `CONTRIBUTING.md` file. These were taken and slightly modified from:
https://github.com/opensearch-project/.github/blob/main/CONTRIBUTING.md#license-headers
N/A

Adds missing license headers section to the CONTRIBUTING.md file.

---

.github/workflows/gradle.yml
.github/workflows/release.yml

Runs the Gradle builds in parallel. This reduces the overall build time by about 5-8 minutes.
Running this on my machine the build only takes 3-4 minutes. However, it seems the GHA runners may not have have much extra CPU available to make better use of parallel testing.
Contributes some toward #925.

Run the Gradle builds in parallel to reduce the overall build time

---

build.gradle

This adds a new Gradle task to generate an aggregate test report.
```
./gradlew generateAggregateTestReport
```
This is not used by any automation. But, developers can use it to aggregate results locally.
N/A

Gradle task to generate an aggregate test report

---

MAINTAINERS.md

Moves a previous maintainer to the emeritus section. - cmanning09.
N/A

Moves cmanning09 to the emeritus section.

---

data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3ScanService.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/ScanObjectWorker.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/SqsService.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/SqsWorker.java

This changes fixes the issue where S3 source with SQS never stops polling when pipeline shutdown is called. This is because of `InterruptedException` which resets the interrupt status.

BUG: Stop S3 source on InterruptedException

---

performance-test/README.md
performance-test/src/gatling/java/org/opensearch/dataprepper/test/performance/tools/Protocol.java

This has two changes related to the Gatling performance tests.
* Allows the `host` property to take a comma-delimited list of host names for round-robin testing.
* Documentation for the new configurations.
N/A

Gatling performance - round-robin hosts and documentation

---

examples/trace-analytics-sample-app/sample-app/Dockerfile
examples/trace-analytics-sample-app/sample-app/analytics-service/Dockerfile
examples/trace-analytics-sample-app/sample-app/analytics-service/README.md
examples/trace-analytics-sample-app/sample-app/analytics-service/build.gradle

Updates the trace analytics sample app:
* Updates Spring Boot to 3.1.3
* Requires JDK 17 for the sample (this is a Spring Boot requirement)
* Use the Temurin images instead of OpenJDK as OpenJDK is deprecated
N/A
Resolves CVE-2016-1000027, CVE-2023-20883, and CVE-2023-34981 from the sample.

Updates trace analytics sample app dependencies

---

data-prepper-plugins/dynamodb-source-coordination-store/src/main/java/org/opensearch/dataprepper/plugins/sourcecoordinator/dynamodb/DynamoDbSourceCoordinationStore.java
data-prepper-plugins/dynamodb-source-coordination-store/src/test/java/org/opensearch/dataprepper/plugins/sourcecoordinator/dynamodb/DynamoDbSourceCoordinationStoreTest.java
data-prepper-plugins/in-memory-source-coordination-store/src/main/java/org/opensearch/dataprepper/plugins/sourcecoordinator/inmemory/InMemoryPartitionAccessor.java
data-prepper-plugins/in-memory-source-coordination-store/src/test/java/org/opensearch/dataprepper/plugins/sourcecoordinator/inmemory/InMemoryPartitionAccessorTest.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/configuration/SchedulingParameterConfiguration.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/configuration/SearchConfiguration.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/WorkerCommonUtils.java
data-prepper-plugins/opensearch-source/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/OpenSearchSourceConfigurationTest.java
data-prepper-plugins/opensearch-source/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/configuration/SchedulingParameterConfigurationTest.java
data-prepper-plugins/opensearch-source/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/configuration/SearchConfigurationTest.java
data-prepper-plugins/opensearch-source/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/NoSearchContextWorkerTest.java
data-prepper-plugins/opensearch-source/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/PitWorkerTest.java
data-prepper-plugins/opensearch-source/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/ScrollWorkerTest.java

* rename opensearch source scheduling `rate` and `job_count` to `interval` and `count`
* Change the order that source coordination stores acquire partitions to check for UNASSIGNED partitions before checking CLOSED. This has the following benefits 
1. Pipelines that do not use the CLOSED functionality (like s3 scan) will not waste a query to the store whenever a partition is acquired
2. CLOSED partitions will not starve UNASSIGNED partitions when the `reOpenAt` time is small, and instead will guarantee that all UNASSIGNED partitions are processed before CLOSED partitions
* Remove `query` from the OpenSearch source configuration, as it is unused in the code
For more …

Rename os source rate/job_count to interval/count, acquire UNASSIGNED partitions before CLOSED partitions

---

.github/workflows/examples-trace-analytics.yml
examples/trace-analytics-sample-app/sample-app/Dockerfile
examples/trace-analytics-sample-app/sample-app/analytics-service/Dockerfile
examples/trace-analytics-sample-app/sample-app/authenticationService.py
examples/trace-analytics-sample-app/sample-app/client.py
examples/trace-analytics-sample-app/sample-app/paymentService.py
examples/trace-analytics-sample-app/sample-app/recommendationService.py
examples/trace-analytics-sample-app/sample-app/requirements.txt
examples/trace-analytics-sample-app/sample-app/script.sh

Overall, this project gets the Trace Analytics sample application running again. I was able to run this sample successfully with these changes.
Specifically:
* Corrects the `Dockerfile` to use `apt-get` which was needed with #3343.
* Updates the Open Telemetry Java instrumentation library.
* Updates Python dependency versions.
* Adds a new GitHub Action to verify that this sample application continues to build. It doesn't verify behavior, but at lease can ensure the builds pass.
N/A

Updates Trace Analytics sample appliction to run again

---

build.gradle
data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/PeerForwarder_ClientServerIT.java
settings.gradle

Updates Armeria to 1.25.2. This also removes Gradle resolution strategies which fix some dependencies to specific versions. Instead, use dependency version requirements which allow for using newer versions.
Resolves #3069.

Armeria 1.25.2

---

data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/CountAggregateAction.java
data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/HistogramAggregateAction.java

ExemplarList generated for Count and Histogram aggregate actions is accumulating the exemplars across different aggregation periods. It should be reset every time new aggregation window starts. This fix resets and includes only new exemplar list whenever a new metric event is generated at the end of aggregation duration.

Fix exemplar list in Histogram and Count aggregations

---

data-prepper-api/build.gradle
data-prepper-plugins/common/build.gradle
data-prepper-plugins/geoip-processor/build.gradle
data-prepper-plugins/http-sink/build.gradle
data-prepper-plugins/http-source/build.gradle
data-prepper-plugins/opensearch/build.gradle
data-prepper-plugins/otel-logs-source/build.gradle
data-prepper-plugins/otel-metrics-raw-processor/build.gradle
data-prepper-plugins/otel-metrics-source/build.gradle
data-prepper-plugins/otel-proto-common/build.gradle
data-prepper-plugins/otel-trace-raw-processor/build.gradle
data-prepper-plugins/otel-trace-source/build.gradle
data-prepper-plugins/prometheus-sink/build.gradle
data-prepper-plugins/s3-sink/build.gradle
data-prepper-plugins/s3-source/build.gradle
data-prepper-plugins/service-map-stateful/build.gradle
settings.gradle

Updates commons-compress to 1.24.0 which fixes CVE-2023-42503. As part of this change, I updated the Apache commons projects to use the Gradle version catalog to keep versions in sync.
Resolves #3347.

Fixes CVE-2023-42503 by updating commons-compress

---

data-prepper-plugins/key-value-processor/README.md
data-prepper-plugins/key-value-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/keyvalue/KeyValueProcessor.java
data-prepper-plugins/key-value-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/keyvalue/KeyValueProcessorConfig.java
data-prepper-plugins/key-value-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/keyvalue/KeyValueProcessorTests.java

Tag the event with specified tags when key value processor runs into exception while processing the event.
Moved commits from #3255 by @shenkw1 and made a few tweaks.
Resolves #886 

Add tagging on failure for KeyValue processor

---

data-prepper-plugins/dissect-processor/README.md
data-prepper-plugins/dissect-processor/build.gradle
data-prepper-plugins/dissect-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/dissect/Delimiter.java
data-prepper-plugins/dissect-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/dissect/DissectProcessor.java
data-prepper-plugins/dissect-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/dissect/DissectProcessorConfig.java
data-prepper-plugins/dissect-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/dissect/Dissector.java
data-prepper-plugins/dissect-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/dissect/Fields/AppendField.java
data-prepper-plugins/dissect-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/dissect/Fields/Field.java
data-prepper-plugins/dissect-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/dissect/Fields/FieldHelper.java
data-prepper-plugins/dissect-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/dissect/Fields/IndirectField.java
data-prepper-plugins/dissect-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/dissect/Fields/NormalField.java
data-prepper-plugins/dissect-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/dissect/Fields/SkipField.java
data-prepper-plugins/dissect-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/dissect/DelimiterTest.java
data-prepper-plugins/dissect-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/dissect/DissectProcessorConfigTest.java
data-prepper-plugins/dissect-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/dissect/DissectProcessorTest.java
data-prepper-plugins/dissect-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/dissect/DissectorTest.java
data-prepper-plugins/dissect-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/dissect/Fields/FieldHelperTest.java
settings.gradle

Moved commits from #3090 by @vishalboin, rebased to resolve merge conflicts and made some small tweaks on tests and docs.
Resolves #3362

Add Dissect Processor

---

data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/configuration/SearchConfiguration.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/ElasticsearchAccessor.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/OpenSearchAccessor.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/model/SearchContextType.java
data-prepper-plugins/opensearch-source/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/configuration/SearchConfigurationTest.java

Searching with search_after solely based on `_doc` sort has a chance to skip documents, and the chance increases the smaller the `batch_size` is made. 
While Point-in-time is said to have built-in ways to handle this, it does not seem to add the `_shard_doc` parameter implicitly for PIT. In OS 2.4, `_shard_doc` was in documentation and 2.5+ it is not supported.
To workaround this, search_after and PIT will add a secondary sort key of `_id`, which is the document id. This guarantees a unique sort key that ensures no documents will be skipped with search_after. 
This is not the optimal setting performance wise, as the recommended approach is to have a unique field in the document itself. This could be an optimization that some users may want in the future. However, to prioritize user …

Add _id as additional sort key for point-in-time and search_after

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/configuration/PluginSetting.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/Event.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/source/coordinator/SourceCoordinator.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/sourcecoordination/LeaseBasedSourceCoordinator.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/sourcecoordination/LeaseBasedSourceCoordinatorTest.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/NoSearchContextWorker.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/PitWorker.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/ScrollWorker.java
data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/WorkerCommonUtils.java
data-prepper-plugins/opensearch-source/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/NoSearchContextWorkerTest.java
data-prepper-plugins/opensearch-source/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/PitWorkerTest.java
data-prepper-plugins/opensearch-source/src/test/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/ScrollWorkerTest.java
data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/ScanObjectWorker.java
data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/s3/S3ScanObjectWorkerTest.java

This changes adds a new function to the source coordinator interface
```
updatePartitionForAckWait(final String partitionKey, final Duration acknowledgmentTimeout)
```
This method will give ownership of `acknowledgmentTimeout` amount for the acknowledgment to be received. If the acknowledgment for the partition is not received in time, then another instance of Data Prepper will attempt to process it from the beginning. Calling the `updatePartitionForAckWait` is also necessary to allow the current node to pick up a new partition to process immediately. 
Also added a paramter `fromAcknowledgmentCallback` to `close/completePartition`. Only the callback functions should set this to true when the partition is closed or completed by the callback. 
* Implemented the use of this change in both s3 …

Add support for fully async acknowledgments in source coordination

---

data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/source/KafkaSource.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/source/KafkaSourceTest.java

Certain error was seen when Kafka Source was constructed using new MSK instance:
```
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:89) ~[kafka-clients-7.4.0-ccs.jar:?]
at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:48) ~[kafka-clients-7.4.0-ccs.jar:?]
at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:731) ~[kafka-clients-7.4.0-ccs.jar:?]
at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:665) ~[kafka-clients-7.4.0-ccs.jar:?]
at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:646) ~[kafka-clients-7.4.0-ccs.jar:?]
at …
```

Add retry to Kafka Consumer Create in source

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/configuration/DataPrepperVersion.java
gradle.properties

Set main version to 2.6 snapshot

Set main version to 2.6

---

data-prepper-core/src/main/java/org/opensearch/dataprepper/plugin/ObjectMapperConfiguration.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/plugin/ObjectMapperConfigurationTest.java

This change removed support for `Duration` and `Enum` in AWS secrets manager 
Resolves #3376 

Remove support for Enum and Duration values from secrets manager

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/configuration/PluginSetting.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/Event.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/JacksonEvent.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/configuration/PluginSettingsTests.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/event/JacksonEventTest.java
data-prepper-plugins/opensearch/README.md
data-prepper-plugins/opensearch/src/integrationTest/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSinkIT.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkOperationWrapper.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSink.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSinkConfiguration.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/bulk/BulkAction.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/bulk/JavaClientAccumulatingUncompressedBulkRequest.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/bulk/SerializedJson.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/bulk/SerializedJsonNode.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/IndexConfiguration.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkOperationWrapperTests.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSinkConfigurationTests.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/bulk/SerializedJsonNodeTest.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/bulk/SerializedJsonTest.java
data-prepper-plugins/opensearch/src/test/resources/test-bulk-template.json

Add support for Update/Upsert/Delete operations in OpenSearch Sink
Actions can be specified with type = Create/Index/Update/Upsert/Delete and with condition
Adds support for expressions in "action" or actions "type".
Resolves #3109
Resolves #3109 

Add support for Update/Upsert/Delete operations in OpenSearch Sink

---

data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/IndexConfiguration.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/IndexConfigurationTests.java

Adds a `template_content` parameter for inline index templates in the OpenSearch sink. This can be used as an alternative to `template_file`
Resolves #3365 

Add inline template_content support to the opensearch sink

---

data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/IndexConfiguration.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/IndexConfigurationTests.java

(cherry picked from commit e19ae8f2302b096363229abad77c1ab5a2042569)
Manual Backport for https://github.com/opensearch-project/data-prepper/pull/3431

[Backport 2.5] Add inline template_content support to the opensearch sink (#3431)

---

data-prepper-plugins/kafka-plugins/src/integrationTest/java/org/opensearch/dataprepper/plugins/kafka/source/MskGlueRegistryMultiTypeIT.java

Fix MSK integration test.
This integration test can be run on CLI with the following command
```
./gradlew     data-prepper-plugins:kafka-plugins:integrationTest -Dtests.kafka.bootstrap_servers="b-1-public.krishkdkmskprov1.ck2ag7.c12.kafka.us-west-2.amazonaws.com:9198" -Dtests.kafka.glue_registry_name="krishkdk-schreg-1" -Dtests.kafka.glue_avro_schema_name="testSchema1" -Dtests.kafka.glue_json_schema_name="test-json-schema1" -Dtests.msk.region="us-west-2" -Dtests.msk.arn="arn:aws:kafka:us-west-2:578844260082:cluster/krishkdk-msk-prov-1/fa11470a-d8bb-4b8f-a53a-26bbbee75198-12"  --tests "*MskGlueRegistryMultiTypeIT*"
```
make sure to have AWS credentials properly exported before executing the above command
- [X ] New functionality …

Fix MSK integration test fix

---

data-prepper-plugins/opensearch/README.md
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/AbstractIndexManager.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/IndexConfiguration.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/DefaultIndexManagerTests.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/IndexConfigurationTests.java

* ENH: support index template for serverless
Signed-off-by: George Chen <qchea@amazon.com>
(cherry picked from commit 73a80a12388faa6dd4285db2f8ea6e16fecf4a19)
Manual backport on serverless feature

[Backport] ENH: support index template for serverless (#3071)

---

data-prepper-plugins/kafka-plugins/src/integrationTest/java/org/opensearch/dataprepper/plugins/kafka/source/MskGlueRegistryMultiTypeIT.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/source/KafkaSource.java

This fixes a broken build.
Additionally, I deleted unused code in `KafkaSource`, made some fields final, and reformatted the file.
N/A

Fix broken build and clean up KafkaSource class.

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/buffer/Buffer.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/buffer/BufferTest.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/parser/CircuitBreakingBuffer.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/Pipeline.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/plugins/MultiBufferDecorator.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/parser/CircuitBreakingBufferTest.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/PipelineTests.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/plugins/MultiBufferDecoratorTest.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/buffer/KafkaBuffer.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/configuration/KafkaBufferConfig.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/buffer/KafkaBufferTest.java

Adds a shutdown method to the buffer interface and implements the method for the kafka and decorator buffers.

Shutdown kafka buffer

---

build.gradle
examples/trace-analytics-sample-app/sample-app/analytics-service/build.gradle

Resolve Netty to 4.1.100.Final, require Jetty 11.0.17 in Data Prepper. Use Tomcat 10.1.14 in the example project. These changes fix CVE-2023-44487 to protect against HTTP/2 reset floods. 
#3474

Fix CVE-2023-44487, HTTP/2 reset floods

---

data-prepper-api/src/test/java/org/opensearch/dataprepper/model/configuration/SinkModelTest.java
data-prepper-main/build.gradle
data-prepper-main/src/test/java/org/opensearch/dataprepper/DataPrepperArgsTest.java
data-prepper-plugins/date-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/date/DateProcessorTests.java
data-prepper-plugins/in-memory-source-coordination-store/src/test/java/org/opensearch/dataprepper/plugins/sourcecoordinator/inmemory/InMemorySourceCoordinationStoreTest.java
data-prepper-plugins/in-memory-source-coordination-store/src/test/java/org/opensearch/dataprepper/plugins/sourcecoordinator/inmemory/QueuedPartitionsItemTest.java
data-prepper-plugins/rss-source/build.gradle
data-prepper-plugins/rss-source/src/test/java/org/opensearch/dataprepper/plugins/source/rss/RSSSourceTest.java
data-prepper-plugins/rss-source/src/test/resources/rss.xml
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/codec/parquet/ParquetOutputCodecTest.java
data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/s3/accumulator/InMemoryBufferTest.java

1. SinkModelTest: Use system System.lineSeparator() instead of hardcode '\n'
2. DataPrepperArgsTest: Covert file path separators to the local system.
3. DateProcessorTests: Covert time to the same timezone before comparing.
4. InMemorySourceCoordinationStoreTest: Use greaterThanOrEqualTo to compare time since they may be the same.
5. QueuedPartitionsItemTest: Use sleep to get two different time instances.
6. RSSSourceTest: Use a mocker server to avoid an internet connection.
7. ParquetOutputCodecTest: Close all outputStream objects in the tests.
8. org.opensearch.dataprepper.plugins.sink.s3.accumulator.InMemoryBufferTest#getDuration_provides_duration_within_expected_range: No solution to fix. Disable it. Please see my comments in the test file.
Fix unstable or failed unit tests
Resolves …

Fix #3459 Unit tests fail on Windows machine

---

data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/integration/PipelinesWithAcksIT.java
data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/plugins/InMemorySource.java
data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/acknowledgements/one-pipeline-ack-expiry-test.yaml
data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/acknowledgements/one-pipeline-three-sinks.yaml
data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/acknowledgements/simple-test.yaml
data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/acknowledgements/three-pipeline-route-test.yaml
data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/acknowledgements/three-pipelines-test-multi-sink.yaml
data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/acknowledgements/three-pipelines-test.yaml
data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/acknowledgements/two-parallel-pipelines-test.yaml
data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/acknowledgements/two-pipelines-test.yaml

Fix flaky test in e2e acks integration test.
Modified the sleep time in InMemorySource to 50ms

Fix e2e acks test

---

release/release-notes/data-prepper.change-log-2.5.0.md

Adds the Data Prepper 2.5.0 changelog file.
```
git switch 2.5
git pull
git-release-notes 2.4.0..HEAD markdown > release/release-notes/data-prepper.change-log-2.5.0.md
git switch main
```
N/A

Data Prepper 2.5.0 change log

---

data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/common/key/KmsKeyProvider.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/configuration/KmsConfig.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/configuration/TopicConfig.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/common/key/KmsKeyProviderTest.java

This change supports using the KMS `encryption_context` in the Kafka buffer.
* Introduces a new `kms` configuration
* Adds `encryption_context` as an option in `kms`
* Moves `kms_key_id` into `kms` as `key_id`.
Resolves #3484

KMS encryption context in Kafka buffer

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/opensearch/OpenSearchBulkActions.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/opensearch/OpenSearchBulkActionsTest.java
data-prepper-plugins/dynamodb-source/README.md
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/DynamoDBService.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/configuration/StreamConfig.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/configuration/StreamStartPosition.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/converter/MetadataKeyAttributes.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/converter/RecordConverter.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/model/TableInfo.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/model/TableMetadata.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/DynamoDBServiceTest.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/DynamoDBSourceConfigTest.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/converter/StreamRecordConverterTest.java
data-prepper-plugins/opensearch/src/integrationTest/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSinkIT.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSink.java
data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/IndexConfiguration.java
data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSinkConfigurationTests.java

This change makes a couple of fixes / improvements to the dynamo db source
* Replaces `source` metadata key (which was corresponding to the table ARN), with `table_name` metadata key for DDB table name
* Adds separate metadata keys `partition_key` and `sort_key`, instead of just `_id` (which is combination of the two)
* Change stream `start_position` of BEGINNING to TRIM_HORIZON to align with DDB naming conventions. Refactor to use `StreamStartPosition` enum
* Map `op` metadata from DDB actions (`INSERT`, `MODIFY`, `REMOVE`) to the corresponding OpenSearch bulk actions. Refactor bulk actions enum from the OpenSearch sink to `data-prepper-api`
```
INSERT -> create
MODIFY -> upsert
REMOVE -> delete
```
By submitting this pull request, I confirm that my contribution is made under the terms …

Miscellaneous fixes/improvements to the DynamoDb source

---

data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/DynamoDBService.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/converter/ExportRecordConverter.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/converter/MetadataKeyAttributes.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/converter/RecordConverter.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/converter/StreamRecordConverter.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/export/DataFileScheduler.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/export/ExportScheduler.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/StreamScheduler.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/converter/ExportRecordConverterTest.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/converter/StreamRecordConverterTest.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/export/DataFileLoaderTest.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/export/DataFileSchedulerTest.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/export/ExportSchedulerTest.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/StreamSchedulerTest.java

* Renames some metrics for the ddb source
* Add metrics for `activeExportS3ObjectConsumers` and `activeChangeEventConsumers` to give indication of how many nodes are processing shards or export files at a time.
* Rename `_id` metadata key to `primary_key`
* Attempts to fix flaky tests for #3470, but did not work so disabled them for now

Ddb metrics changes

---

data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/common/aws/AwsContext.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/common/key/KmsKeyProvider.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/configuration/AwsConfig.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/configuration/AwsCredentialsConfig.java
data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/configuration/KmsConfig.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/common/aws/AwsContextTest.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/common/key/KmsKeyProviderTest.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/configuration/KmsConfigTest.java

Adds new AWS configurations for KMS encryption in the Kafka buffer. Now each topic's KMS configuration can have specific AWS configurations so that you can connect to an Amazon MSK with different configurations as the AWS credentials used to decrypt KMS keys.
Resolves #3516

Adds new AWS configurations for the KMS encryption. Resolves #3516.

---

data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/extension/DefaultKafkaClusterConfigSupplier.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/extension/DefaultKafkaClusterConfigSupplierTest.java

Fix broken DefaultKafkaClusterConfigSupplier get API
The API doesn't check for the kafkaClusterConfig to be null or not. Modified to check for null config.
Resolves #3528 
Resolves #3528 

Fix broken DefaultKafkaClusterConfigSupplier get API

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/JacksonEvent.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/event/JacksonEventTest.java

Any call to JacksonEvent `formatString` method with an expression evaluator would call `isValidExpressionStatement`. A call to `isValidExpressionStatement` that was false, such as the configurations for normal keys (such as `${some_key}`) resulted in the ANTLR parser logging something like 
```
line 1:0 token recognition error at: 'spanId'
line 1:6 mismatched input '' expecting {Function, Integer, Float, Boolean, 'null', JsonPointer, EscapedJsonPointer, VariableIdentifier, String, NOT, '-', '(', '{', OTHER}
``` 
every time this occurs, which is very often when the format is a dynamic index that is evaluated for every Event. This causes cpu spikes and a thread freeze from timeouts for the logger writing to console. 
This mitigation includes swapping the order of the evaluation of the …

Reorder formatString expression check for JacksonEvent

---

.github/workflows/data-prepper-log-analytics-basic-grok-e2e-tests.yml
.github/workflows/data-prepper-peer-forwarder-local-node-e2e-tests.yml
.github/workflows/data-prepper-peer-forwarder-static-e2e-tests.yml
.github/workflows/data-prepper-trace-analytics-raw-span-compatibility-e2e-tests.yml
.github/workflows/data-prepper-trace-analytics-raw-span-e2e-tests.yml
.github/workflows/data-prepper-trace-analytics-raw-span-peer-forwarder-e2e-tests.yml
.github/workflows/data-prepper-trace-analytics-service-map-e2e-tests.yml

Run our end-to-end tests using Java 21 when building in GitHub Actions. This is to help verify that Data Prepper does successfully run on Java 21 with the goal of making that our next target version.
Contributes toward #3329.

Run the end-to-end tests on Java 21 in the GitHub Actions.

---

release/docker/Dockerfile

Perform a full upgrade on the base Docker image when building the Data Prepper Docker image to get latest patches.
N/A

Perform a full upgrade on the base Docker image

---

.github/workflows/opensearch-sink-opensearch-integration-tests.yml

Test against newer versions of OpenSearch and use odd versions in the 2.x series to avoid testing against too many different versions. Updated to the latest 1.3 version.
N/A

Update OpenSearch versions in integration testing

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/record/Record.java
data-prepper-api/src/main/java/org/opensearch/dataprepper/model/record/RecordMetadata.java

Removes the deprecated annotation from Record and RecordMetadata as these are currently still necessary. 
Resolves #3536.

Removes the deprecated annotation from Record and RecordMetadata

---

data-prepper-plugins/obfuscate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/obfuscation/ObfuscationProcessor.java
data-prepper-plugins/obfuscate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/obfuscation/ObfuscationProcessorConfig.java
data-prepper-plugins/obfuscate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/obfuscation/ObfuscationProcessorTest.java

Add `obfuscate_when` parameter to obfuscate processor to support conditionally running obfuscate on Events
Add `tags_on_match_failure` parameter to tag events that don't obfuscate due to patterns not matching 

Add obfuscate_when parameter and tags_on_match failure to obfuscate processor

---

data-prepper-plugins/common/src/test/java/org/opensearch/dataprepper/plugins/accumulator/InMemoryBufferTest.java
data-prepper-plugins/common/src/test/java/org/opensearch/dataprepper/plugins/accumulator/LocalFileBufferTest.java

Add tests to InMemoryBufferTest and LocalFileBufferTest to fix broken test coverage issue

Add tests to InMemoryBufferTest and LocalFileBufferTest

---

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/buffer/Buffer.java
data-prepper-api/src/test/java/org/opensearch/dataprepper/model/buffer/BufferTest.java
data-prepper-core/src/main/java/org/opensearch/dataprepper/parser/CircuitBreakingBuffer.java
data-prepper-core/src/test/java/org/opensearch/dataprepper/parser/CircuitBreakingBufferTest.java

The `CircuitBreakingBuffer` did not implement the new methods on `Buffer` related to writing bytes. Thus, using this buffer with a circuit breaker applied would fail to write.
Also update the exception thrown by `Buffer` when `writeBytes` is called to be an `UnsupportedOperationException` with a clearer error.
N/A

Implement writeBytes and isByteBuffer in the CircuitBreakingBuffer

---

data-prepper-plugins/s3-source/build.gradle

Fix CVE error of the Jetty version by exclude the jetty in S3 source plugin.

Fix CVE error for Jetty version 11.0.12

---

data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/converter/RecordConverter.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/export/DataFileScheduler.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/export/ExportScheduler.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/StreamScheduler.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/converter/ExportRecordConverterTest.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/converter/StreamRecordConverterTest.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/export/DataFileSchedulerTest.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/export/ExportSchedulerTest.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/StreamSchedulerTest.java

The three Scheduler threads in the ddb source, `ExportScheduler`, `StreamScheduler`, and `DataFileScheduler`, may shutdown silently if an exception is thrown during processing.
* Catch and log exceptions before backing off and retrying in these scheduler threads
* Fix `primary_key` attribute to divide partition and sort key by `|` to avoid conflicts (since `|` is an invalid ddb character for partition and sort keys, and is valid as OpenSearch document id

Catch exceptions and backoff and retry ddb source threads instead of shutting down on exception

---

data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/common/serialization/EncryptionSerializer.java
data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/common/serialization/EncryptionSerializerTest.java

Using client-side encryption in the Kafka buffer with the `bytes` input was resulting in a null error.
```
2023-10-27T14:46:29,995 [pool-15-thread-1] ERROR org.opensearch.dataprepper.plugins.kafka.producer.KafkaCustomProducer - Error occurred while publishing Null input buffer
```
The existing `Serializer` implementations return `null` for `null` data. So this mimics this.
N/A

Fix for Kafka buffer encryption with byte data

---

data-prepper-plugins/dynamodb-source/build.gradle
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/export/DataFileLoader.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/export/DataFileLoaderFactory.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/export/DataFileScheduler.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/model/ExportSummary.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/model/LoadStatus.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/ShardConsumer.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/ShardConsumerFactory.java
data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/StreamCheckpointer.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/export/DataFileLoaderTest.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/export/ManifestFileReaderTest.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/ShardConsumerTest.java
data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/StreamSchedulerTest.java

Fix below bugs:
-  An issue with `out of range of int` for item counts
-  The lease of shard will expire when waiting for export to be completed for a long time.
-  Wait for export doesn't work if no change events in the shard.
Make below improvements:
- Optimize the factory and builder class for data file loader and shard consumer
- Other miscellaneous improvement.

Add bug fixes and improvements to DDB source
