data-prepper-plugins/mapdb-prepper-state/build.gradle
Signed-off-by: Jeff Wright <74204404+wrijeff@users.noreply.github.com>
* Updating depedencies
=> Updating dependencies.

README.md
=> ADD: descriptive paragraph on data-prepper README

release/release-notes/data-prepper.release-notes-1.1.0.md
Signed-off-by: Jeff Wright <74204404+wrijeff@users.noreply.github.com>
Added v1.1.0 release notes.
=> Added v1.1.0 release notes.

gradle.properties
Set the version to 1.2.0. We are releasing Data Prepper 1.1.0 from the ODFE repository. The next version from this repository will be 1.2.0.
N/A
=> Updated the version to 1.2.0

build.gradle, data-prepper-plugins/opensearch/build.gradle, data-prepper-plugins/otel-trace-raw-prepper/build.gradle
=> Dependabot upgrades

data-prepper-plugins/grok-prepper/README.md
Provide more robust documentation for grok. Provides a basic grok tutorial, and examples for how to use many of the features.
=> Complete Grok Documentation

docs/developer_guide.md
Adds coding guidance for the project into our existing Developer Documentation page.
=> Added Coding Guidance to the Developer Guide documentation.

data-prepper-api/src/main/java/com/amazon/dataprepper/prepper/state/PrepperState.java
Update PrepperState Javadoc to be consistent with class definition
Javadoc inconsistency on PrepperState class
=> Fix PrepperState javadoc

docs/developer_guide.md
This PR includes instructions for building and running a Docker image locally. I added this to the Developer Guide to raise the visibility of this documentation.
N/A
=> Added instructions to build and run the Docker image locally.

data-prepper-logstash-configuration/src/test/java/org/opensearch/dataprepper/logstash/mapping/LogstashMapperTest.java
=> Fixes the main branch from renaming

THIRD-PARTY, build.gradle
Removes bom dependencies from THIRD-PARTY
=> Removed bom dependencies from third party dependency report

data-prepper-logstash-configuration/src/test/java/org/opensearch/dataprepper/logstash/mapping/TestDataProvider.java
Some minor clean up for the Logstash configuration test data provider.
N/A
=> Some minor clean up for the Logstash configuration test data provider.

docs/getting_started.md, docs/logstash_migration_guide.md
* Simple guide to run Data Prepper with Logstash config using Docker
* Link to the doc in the `Getting Started`guide
=> Simple guide to run Data Prepper with Logstash config

data-prepper-plugins/peer-forwarder/src/test/java/com/amazon/dataprepper/plugins/prepper/peerforwarder/discovery/AwsCloudMapPeerListProviderTest.java
Reduce false test failures related to timeouts
AwsCloudMapPeerListProviderTest intermittently failing
=> Updated peer forwarder test timeout

data-prepper-plugins/http-source/src/main/java/com/amazon/dataprepper/plugins/source/loghttp/HTTPSource.java, data-prepper-plugins/http-source/src/test/java/com/amazon/dataprepper/plugins/source/loghttp/HTTPSourceTest.java, data-prepper-plugins/otel-trace-source/src/main/java/com/amazon/dataprepper/plugins/source/oteltrace/OTelTraceSource.java, data-prepper-plugins/otel-trace-source/src/test/java/com/amazon/dataprepper/plugins/source/oteltrace/OTelTraceSourceTest.java, data-prepper-plugins/peer-forwarder/src/test/java/com/amazon/dataprepper/plugins/prepper/peerforwarder/PeerClientPoolTest.java, e2e-test/log/src/integrationTest/java/com/amazon/dataprepper/integration/log/EndToEndBasicLogTest.java
Disables Armeria server header in HTTP responses. 
N/A
=> Disable armeria headers

release/docker/ci/build-image-single-arch.sh
Update data prepper build script with more setups
#623 
=> Update data prepper build script with more setups

gradle.properties
Set the version to Data Prepper 1.2.0
N/A
=> Data Prepper 1.2.0

gradle.properties
Updated the version to 1.3.0-SNAPSHOT in preparation for the the 1.3.0 release.
N/A
=> Set the next version to Data Prepper 1.3.0.

examples/log-ingestion/docker-compose.yaml, examples/log-ingestion/log_ingestion_demo_guide.md, examples/log-ingestion/log_pipeline.yaml
Simplifying login ingestion guide to use a single node opensearch cluster.
- related to: #690
=> simplifying log ingestion guide to use a single node cluster

examples/jaeger-hotrod/README.md
* Corrected the link for viewing Trace Analytics
* Added links in the README.md for convenience
* Use HotROD consistently
N/A
=> Updated the Jaeger HotROD demo with correct link

release/docker/Dockerfile
Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>
[main] Add yum update to data prepper to consume all pkg updates
#716
=> [main] Add yum update to data prepper to consume all pkg updates

release/docker/ci/build-image-single-arch.sh, release/docker/ci/build-image.sh
Automation for Docker deployments.
N/A
=> [Backport] Docker build script to build v1.1.x

gradle.properties
Updated the Data Prepper version to 1.1.1.
N/A
=> Data Prepper 1.1.1

release/release-notes/data-prepper.release-notes-1.1.1.md
Release notes for Data Prepper 1.1.1
N/A
=> Added release notes for Data Prepper 1.1.1

THIRD-PARTY
Updated THIRD-PARTY dependency file
=> Updated third party file

.github/workflows/backport.yml
Adds the `backport.yml` file to support backporting.
Related to #692.
I will follow-up with documentation.
=> Added backport GitHub workflow. #692

README.md
updates the readme to include log analytics/ingestion as a use case.
- related to: #624 
=> add log analytics to README.md

release/release-notes/data-prepper.release-notes-1.2.0.md
Added CVE-2021-45046  to the release notes.
N/A
=> Added CVE-2021-45046  to the 1.2.0 release notes.

build.gradle
Added log4j 2.16.0 to the Gradle contraints
N/A
=> Require log4j-2.16.0

examples/adot/docker-compose.yml
Updated the ADOT example to use OpenSearch Data Prepper, OpenSearch, and OpenSearch Dashboards.
Related to #639.
=> Updated the ADOT example to OpenSearch

data-prepper-plugins/mapdb-prepper-state/build.gradle
The dependabot PR #679 is not rebasing. So, here is a manual PR to update Kotlin.
=> Updated kotlin-stdlib-common to 1.6.0

data-prepper-api/src/main/java/com/amazon/dataprepper/model/trace/DefaultTraceGroupFields.java, data-prepper-api/src/main/java/com/amazon/dataprepper/model/trace/JacksonSpan.java, data-prepper-api/src/main/java/com/amazon/dataprepper/model/trace/Span.java, data-prepper-api/src/test/java/com/amazon/dataprepper/model/trace/DefaultTraceGroupFieldsTest.java, data-prepper-api/src/test/java/com/amazon/dataprepper/model/trace/JacksonSpanTest.java
This PR enhances the Span Event model in the following aspects:
* add serviceName attribute
* add equal method in DefaultTraceGroupFields
* add fromSpan API in JacksonSpan
Contributes to #546 
=> MAINT: span model enhancement

release/README.md, release/smoke-tests/docker-compose.yml, release/smoke-tests/run-smoke-tests.sh
Allow smoke test to be run against local images
=> Support smoke testing local docker images

release/release-notes/data-prepper.change-log-1.2.1.md, release/release-notes/data-prepper.release-notes-1.2.1.md
=> Added 1.2.1 release notes

NOTICE
Removed the year from the copyright so that we don't have to update every year.
See: https://github.com/opensearch-project/OpenSearch/blob/main/NOTICE.txt#L2
N/A
=> Removed the year from the copyright in the NOTICE file.

data-prepper-plugins/opensearch/src/main/java/com/amazon/dataprepper/plugins/sink/opensearch/OpenSearchSink.java, data-prepper-plugins/opensearch/src/main/java/com/amazon/dataprepper/plugins/sink/opensearch/index/IndexConfiguration.java, data-prepper-plugins/opensearch/src/main/java/com/amazon/dataprepper/plugins/sink/opensearch/index/IndexManager.java, data-prepper-plugins/opensearch/src/main/java/com/amazon/dataprepper/plugins/sink/opensearch/index/IndexManagerFactory.java, data-prepper-plugins/opensearch/src/test/java/com/amazon/dataprepper/plugins/sink/opensearch/index/DefaultIndexManagerTests.java, data-prepper-plugins/opensearch/src/test/java/com/amazon/dataprepper/plugins/sink/opensearch/index/IndexManagerFactoryTests.java, data-prepper-plugins/opensearch/src/test/java/com/amazon/dataprepper/plugins/sink/opensearch/index/TraceAnalyticsRawIndexManagerTests.java, data-prepper-plugins/opensearch/src/test/java/com/amazon/dataprepper/plugins/sink/opensearch/index/TraceAnalyticsServiceMapIndexManagerTests.java
Signed-off-by: Han Jiang <jianghan@amazon.com>
Support time pattern in index names. 
For details, see RFC: #755 
#767 
- [ x] New functionality includes testing.
- [ x] Commits are signed with a real name per the DCO
=> Support time pattern in index names.

data-prepper-plugins/drop-events-processor/README.md
=> Change 'prepper' to 'processor'

release/archives/linux/data-prepper-tar-install-with-jdk-x64.sh, release/archives/linux/data-prepper-tar-install-x64.sh, release/archives/macos/data-prepper-tar-install-with-jdk-x64.sh, release/archives/macos/data-prepper-tar-install-x64.sh, release/docker/ci/build-image-single-arch.sh, release/smoke-tests/run-smoke-tests.sh
I updated the copyright headers for a few shell scripts.
Resolves #189
=> Updated copyright headers in scripts. #189

data-prepper-api/src/main/java/com/amazon/dataprepper/model/record/Record.java, data-prepper-api/src/main/java/com/amazon/dataprepper/model/record/RecordMetadata.java
Signed-off-by: Mohit Saxena <mohit.saxena@knoldus.com>
Fixes #946 
=> Deprecating Record and RecordMetaData

data-prepper-plugins/date-processor/build.gradle, data-prepper-plugins/date-processor/src/main/java/com/amazon/dataprepper/plugins/processor/date/DateProcessor.java, data-prepper-plugins/date-processor/src/main/java/com/amazon/dataprepper/plugins/processor/date/DateProcessorConfig.java, data-prepper-plugins/date-processor/src/test/java/com/amazon/dataprepper/plugins/processor/date/DateProcessorConfigTest.java, settings.gradle
- Boilerplate for DateProcessor
- DateProcessorConfig
#509 
=> Added DateProcessor boilerplate and  DateProcessorconfig

data-prepper-expression/src/main/java/org/opensearch/dataprepper/expression/ConditionalExpressionEvaluator.java, data-prepper-expression/src/main/java/org/opensearch/dataprepper/expression/ExpressionEvaluator.java
Updated ConditionalExpressionEvaluator scope to package private
n/a
=> Updated ConditionalExpressionEvaluator scope to package private

data-prepper-plugins/mutate-event-processors/README.md
=> Fix README headers

docs/logstash_migration_guide.md, docs/migrating_from_opendistro.md
Updated docker image location.
=> Updated docker image location

data-prepper-plugins/aggregate-processor/README.md, data-prepper-plugins/blocking-buffer/README.md, data-prepper-plugins/drop-events-processor/README.md, data-prepper-plugins/grok-prepper/README.md, data-prepper-plugins/key-value-processor/README.md, data-prepper-plugins/mutate-event-processors/README.md, release/README.md
- Fix for broken link to monitoring page 
- Fix heading formats.
=> Minor fixes in documentation

data-prepper-logstash-configuration/build.gradle, data-prepper-logstash-configuration/src/main/java/org/opensearch/dataprepper/logstash/mapping/DateLogstashPluginAttributesMapper.java, data-prepper-logstash-configuration/src/main/resources/org/opensearch/dataprepper/logstash/mapping/date.mapping.yaml, data-prepper-logstash-configuration/src/test/java/org/opensearch/dataprepper/logstash/mapping/DateLogstashPluginAttributesMapperTest.java, data-prepper-logstash-configuration/src/test/resources/org/opensearch/dataprepper/logstash/log-ingest-to-logstash-opensearch.conf, data-prepper-logstash-configuration/src/test/resources/org/opensearch/dataprepper/logstash/log-ingest-to-logstash-opensearch.expected.yaml, data-prepper-plugins/date-processor/src/main/java/com/amazon/dataprepper/plugins/processor/date/DateProcessorConfig.java
- Logstash converter for date processor with custom mapper for match attribute
- Integration test for converter
=> Date processor logstash converter

data-prepper-expression/src/main/antlr/DataPrepperExpression.g4, data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/GrammarLexerTest.java, data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/ParserTest.java, data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/util/ErrorListenerTest.java
Added simple parser tests
Missing parser tests
=> Error parser tests

release/staging-resources-cdk/.eslintrc.js, release/staging-resources-cdk/.gitignore, release/staging-resources-cdk/.npmignore, release/staging-resources-cdk/README.md, release/staging-resources-cdk/bin/staging-resources-cdk.ts, release/staging-resources-cdk/cdk.json, release/staging-resources-cdk/jest.config.js, release/staging-resources-cdk/lib/GitHubAccessStack.ts, release/staging-resources-cdk/lib/StagingResourcesStack.ts, release/staging-resources-cdk/package-lock.json, release/staging-resources-cdk/package.json, release/staging-resources-cdk/test/GitHubAccessStack.test.ts, release/staging-resources-cdk/test/StagingResourcesStack.test.ts, release/staging-resources-cdk/tsconfig.json
This PR adds a CDK project to Data Prepper which will deploy a staging environment to be used in the release process.
In this PR, I've added the CDK project and created two stacks: `GitHubAccessStack` and `StagingResourcesStack`. I plan to add more resources in follow-on PRs. I stopped here to keep the PR at a more manageable size.
Most of the files are boilerplate which CDK generated. The most valuable files to review are:
* `bin/staging-resources-cdk`
* `lib/GitHubAccessStack.ts`
* `lib/StagingResourcesStack.ts`
* `test/GitHubAccessStack.test.ts`
* `test/StagingResourcesStack.test.ts`
For reference, I created the CDK project via:
```
cd release
mkdir staging-resources-cdk
cdk init app --language typescript
```
Part of #977
By submitting this pull request, I confirm that my contribution …
=> Created a CDK app to deploy staging resources for the release process

data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/util/JsonPointerMatcher.java, data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/util/JsonPointerMatcherTest.java, data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/util/SimpleExpressionMatcher.java
=> Added JsonPointerMatcher

.github/workflows/opensearch-sink-opendistro-integration-tests.yml, data-prepper-plugins/opensearch/README.md, deployment-template/ec2/data-prepper-ec2-deployment-cfn.yaml, deployment-template/k8s/data-prepper-k8s.yaml, examples/dev/k8s/sample-project-applications.yaml
Updates linux distribution of Data Prepper from odfe to OpenSearch Project and other usages.
Contributes to #639 
=> Update Open Distro usages to OpenSearch in scripts

build-resources.gradle
This is the latest version of JUnit Jupiter. It also includes JUnit 4.13.2 which has a CVE fix.
Resolves #977
=> Updated JUnit Jupiter to 5.8.2

THIRD-PARTY
=> Updated THIRD PARTY file for 1.3

data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/ParseTreeExpressionTest.java, data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/util/ContextMatcher.java, data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/util/ContextMatcherTest.java, data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/util/GrammarTest.java
Added Tests for complete expression parsing
Missing Data Prepper Expression test coverage
=> Added Tests for complete expression parsing

examples/kibana-trace-analytics/Dockerfile
Delete outdated Kibana trace analytics example since trace-analytics plugin is now part of OpenSearch Dashboards.
Resolves #639 
=> Delete outdated Kibana trace analytics example

data-prepper-expression/src/main/java/org/opensearch/dataprepper/expression/ConditionalExpressionEvaluator.java, data-prepper-expression/src/main/java/org/opensearch/dataprepper/expression/Evaluator.java, data-prepper-expression/src/main/java/org/opensearch/dataprepper/expression/ExceptionOverview.java, data-prepper-expression/src/main/java/org/opensearch/dataprepper/expression/ExpressionEvaluationException.java, data-prepper-expression/src/main/java/org/opensearch/dataprepper/expression/ExpressionEvaluator.java, data-prepper-expression/src/main/java/org/opensearch/dataprepper/expression/Parser.java, data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/ConditionalExpressionEvaluatorTest.java, data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/ParseTreeExpressionTest.java, data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/ParseTreeTest.java, data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/util/GrammarTest.java
Adds default implementation of ExpressionEvaluator usable by external packages
#976 
=> Implemented ConditionalExpressionEvaluator methods

release/archives/build.gradle
Updated gradle tasks which build and upload zip files
resolves #1129 
=> Updated gradle tasks to remove zip files

release/staging-resources-cdk/lib/GitHubActionsReleaseAccessStack.ts, release/staging-resources-cdk/test/GitHubActionsReleaseAccessStack.test.ts
Release builds will happen off of branches for different versions. e.g. `1.3`, `1.4`. Thus, the release process must be able to run from any branch.
N/A
=> Staging CDK: Allow releasing to the staging repository from any branch.

data-prepper-core/src/test/java/com/amazon/dataprepper/TestDataProvider.java, data-prepper-plugins/common/src/main/java/com/amazon/dataprepper/plugins/PluginRepository.java, data-prepper-plugins/common/src/main/java/com/amazon/dataprepper/plugins/prepper/NoOpPrepper.java, data-prepper-plugins/common/src/main/java/com/amazon/dataprepper/plugins/prepper/PrepperFactory.java, data-prepper-plugins/common/src/test/java/com/amazon/dataprepper/plugins/prepper/PrepperFactoryTests.java, data-prepper-plugins/common/src/test/java/com/amazon/dataprepper/plugins/prepper/TestPrepper.java
* Updates NoOpPrepper to implement Processor instead of Prepper
Contributes to #647 
=> Updates NoOpPrepper to implement Processor

data-prepper-expression/src/main/java/org/opensearch/dataprepper/expression/UnaryNumericOperator.java, data-prepper-expression/src/main/java/org/opensearch/dataprepper/expression/UnaryNumericOperatorConfiguration.java, data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/UnaryNumericOperatorConfigurationTest.java, data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/UnaryNumericOperatorTest.java
Add support for subtract unary operator
Missing support for negative numbers in data-prepper-expression syntax
=> New operators

data-prepper-logstash-configuration/src/main/java/org/opensearch/dataprepper/logstash/mapping/MutateMapper.java, data-prepper-logstash-configuration/src/test/resources/org/opensearch/dataprepper/logstash/log-ingest-to-opensearch.conf, data-prepper-logstash-configuration/src/test/resources/org/opensearch/dataprepper/logstash/log-ingest-to-opensearch.expected.yaml, data-prepper-plugins/mutate-string-processors/src/main/java/com/amazon/dataprepper/plugins/processor/mutatestring/SubstituteStringProcessor.java, data-prepper-plugins/mutate-string-processors/src/main/java/com/amazon/dataprepper/plugins/processor/mutatestring/SubstituteStringProcessorConfig.java, data-prepper-plugins/mutate-string-processors/src/test/java/com/amazon/dataprepper/plugins/processor/mutatestring/SubstituteStringProcessorTests.java
Add SubstituteStringProcessor and its associated tests
#697
=> Substitute processor

data-prepper-logstash-configuration/src/main/java/org/opensearch/dataprepper/logstash/mapping/MutateMapper.java, data-prepper-logstash-configuration/src/test/resources/org/opensearch/dataprepper/logstash/log-ingest-to-opensearch.conf, data-prepper-logstash-configuration/src/test/resources/org/opensearch/dataprepper/logstash/log-ingest-to-opensearch.expected.yaml, data-prepper-plugins/mutate-string-processors/src/main/java/com/amazon/dataprepper/plugins/processor/mutatestring/SplitStringProcessor.java, data-prepper-plugins/mutate-string-processors/src/main/java/com/amazon/dataprepper/plugins/processor/mutatestring/SplitStringProcessorConfig.java, data-prepper-plugins/mutate-string-processors/src/test/java/com/amazon/dataprepper/plugins/processor/mutatestring/SplitStringProcessorTests.java
Adds `SplitStringProcessor` classes and unit tests.
Contributes to #697 
=> Split String Processor

docs/developer_guide.md
This change documents our approach to branches and backports. I wrote it from the perspective of what a new contributor might want to know about the process.
Resolves #692 by documenting backporting.
=> Updated the Developer Guide with instructions for contributing code.

data-prepper-api/src/main/java/com/amazon/dataprepper/model/trace/JacksonSpan.java, data-prepper-api/src/test/java/com/amazon/dataprepper/model/event/JacksonEventTest.java
This PR cherry-picked some performance enhancement on JacksonSpan from #546 .
=> MAINT: JacksonSpan enhancement

data-prepper-plugins/mutate-string-processors/src/main/java/com/amazon/dataprepper/plugins/processor/mutatestring/SplitStringProcessor.java, data-prepper-plugins/mutate-string-processors/src/main/java/com/amazon/dataprepper/plugins/processor/mutatestring/SplitStringProcessorConfig.java, data-prepper-plugins/mutate-string-processors/src/test/java/com/amazon/dataprepper/plugins/processor/mutatestring/SplitStringProcessorTests.java
Fix Split Processor Constructor and tests
#697 
=> Fix Split Processor Constructor

data-prepper-plugins/mutate-string-processors/README.md
README for String Processors
#697
=> README for Mutate String Processors

gradle.properties
Updated gradle version to 1.3.0 for release process.
=> Updated gradle version to 1.3.0

data-prepper-plugins/mutate-string-processors/src/main/java/com/amazon/dataprepper/plugins/processor/mutatestring/SplitStringProcessor.java
=> Fix checkstyle error

data-prepper-plugins/drop-events-processor/README.md
Fixed broken links
https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-plugins/drop-events-processor/README.md?plain=1#L34
https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-plugins/drop-events-processor/README.md?plain=1#L49
=> Fixed broken links

gradle.properties
Updating Data Prepper to the next version: 1.4.0-SNAPSHOT
N/A
=> Next Data Prepper version: 1.4.0-SNAPSHOT

e2e-test/log/build.gradle, e2e-test/log/src/main/java/com/amazon/dataprepper/integration/log/ApacheLogFaker.java
Removed dependency on com.github.javafaker
Removed the need to force exclude org.yaml:snakeyaml:1.30 dependency.
=> Remove faker dependency

README.md
Signed-off-by: Kyle J. Davis <kyledvs@amazon.com>
Fixes link in README to NOTICE
=> fixes link to NOTICE file

data-prepper-plugins/otel-metrics-raw-processor/build.gradle, data-prepper-plugins/otel-metrics-raw-processor/src/main/java/com/amazon/dataprepper/plugins/processor/otelmetrics/OTelMetricsProtoHelper.java
Fast follow-on of fixes from #1154 
* Fix the Javadocs
* Use Armeria 1.9.1 to fix the failing end-to-end tests
N/A
=> OTel Metric fixes

.github/dependabot.yml
We have added some new projects to Data Prepper and they are not part of Dependabot. This PR adds them.
N/A
=> Updated the Dependabot configuration with some missing projects.

data-prepper-plugins/opensearch/src/test/java/com/amazon/dataprepper/plugins/sink/opensearch/OpenSearchSinkIT.java
The old assertions in this test rely upon the base class from an OpenSearch core test. This PR cleans up only the assertion dependencies to prepare to possibly remove that class entirely.
N/A
=> Use MatcherAssert.assertThat in OpenSearchSinkIT.

THIRD-PARTY
THIRD PARTY report for 1.4 release
Resolves #1396 
=> THIRD PARTY dependency report for 1.4 release

e2e-test/log/build.gradle, e2e-test/trace/build.gradle, e2e-test/trace/src/integrationTest/java/com/amazon/dataprepper/integration/trace/EndToEndRawSpanTest.java
Fixes flakiness of e2e tests(not completely).
=> Fix flaky e2e tests

release/release-notes/data-prepper.release-notes-1.4.0.md
=> Added release notes for 1.4.0

release/release-notes/data-prepper.change-log-1.4.0.md
Created change log by running below command
` git-release-notes 1.3.0..HEAD markdown > data-prepper.change-log-1.4.0.md`
Resolves #1393 
=> Added change log for 1.4.0

gradle.properties
Preparing for the 1.4.0 release.
N/A
=> Set the version to 1.4.0 release

gradle.properties
Prepares the main branch for 1.5.0.
N/A
=> Version bump to 1.5.0 on the main branch.

data-prepper-core/src/main/java/com/amazon/dataprepper/ContextManager.java
Makes ContextManager public so it is available outside of its package
=> Make ContextManager public

data-prepper-plugins/http-source/src/main/java/com/amazon/dataprepper/plugins/source/loghttp/HTTPSource.java, data-prepper-plugins/http-source/src/main/java/com/amazon/dataprepper/plugins/source/loghttp/HTTPSourceConfig.java, data-prepper-plugins/http-source/src/test/java/com/amazon/dataprepper/plugins/source/loghttp/HTTPSourceTest.java
The HTTP source now has an optional health check
=> Add health check to HTTP source

data-prepper-plugins/s3-source/src/main/java/com/amazon/dataprepper/plugins/source/codec/JsonCodec.java, data-prepper-plugins/s3-source/src/test/java/com/amazon/dataprepper/plugins/source/codec/JsonCodecTest.java
Added the `JsonCodec` class which parses JSON files and extracts Events from each JSON object in a JSON array.
Resolves #1462
=> Created the S3 Source JSON codec

data-prepper-core/build.gradle, data-prepper-expression/build.gradle
Updated to Spring 5.3.21
Resolves #1390
Resolves #1312
=> Updated to Spring 5.3.21

THIRD-PARTY
Updated the THIRD-PARTY file for 1.5.0
Updated via:
```
./gradlew generateThirdPartyReport
```
Resolves #1518
=> Updated the THIRD-PARTY file for 1.5.0

data-prepper-plugins/s3-source/src/integrationTest/java/com/amazon/dataprepper/plugins/source/SqsWorkerIT.java
=> Fixes a compiler error in SqsWorkerIT

data-prepper-plugins/s3-source/README.md
Added user documentation for the S3 Source.
You may find it easiest to preview at: https://github.com/dlvenable/data-prepper/tree/s3-source-readme/data-prepper-plugins/s3-source
Resolves #1515 
=> Updated the README.md for the S3 Source

release/release-notes/data-prepper.release-notes-1.5.0.md
Adds the release notes for Data Prepper 1.5.0
Resolves #1520 
=> Created release notes for Data Prepper 1.5.0

gradle.properties
Set the version to `1.5.0` in the `gradle.properties` file.
N/A
=> Updated the version to 1.5.0 for the release.

release/release-notes/data-prepper.change-log-1.5.0.md
```
git checkout 1.5
git-release-notes 1.4.0..HEAD markdown > data-prepper.change-log-1.5.0.md
```
Resolves #1521 
=> Added the auto-generated CHANGELOG for Data Prepper 1.5.0

gradle.properties
Update the version to 1.5.1 for the next release.
N/A
=> Updated to version 1.5.1

release/release-notes/data-prepper.release-notes-1.5.1.md
Adds release notes for Data Prepper 1.5.1
N/A
=> Added release notes for Data Prepper 1.5.1.

data-prepper-core/src/main/java/com/amazon/dataprepper/parser/PipelineParser.java, data-prepper-core/src/main/java/com/amazon/dataprepper/peerforwarder/PeerForwardingProcessorDecorator.java, data-prepper-core/src/test/java/com/amazon/dataprepper/peerforwarder/PeerForwardingProcessingDecoratorTest.java
Created decorated list of processors
Resolves #1597 
=> Updated PipelineParser to create decorator for stateful processors

data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/discovery/DnsPeerListProviderTest.java
I missed another import problem.
N/A
=> Fixes another incorrect package related to HashRing.

examples/trace-analytics-sample-app/sample-app/analytics-service/build.gradle
This change will fix [CVE-2022-22965](https://advisories.aws.barahmand.com/advisory/CVE-2022-22965) related to `2.3.1 RELEASE` version
=> Updated spring boot version in examples package

data-prepper-expression/build.gradle, data-prepper-logstash-configuration/build.gradle
Signed-off-by: jzonthemtn <jzemerick@opensourceconnections.com>
Updates Antlr dependency version.
#1513 
=> #1513: Updating antlr versions.

data-prepper-plugins/http-source/build.gradle, data-prepper-plugins/http-source/src/main/java/com/amazon/dataprepper/plugins/source/loghttp/certificate/CertificateProviderFactory.java
Added http client for creating ACM and S3 clients
Resolves #1729 
=> Added apache client for creating s3 and acm client

data-prepper-plugins/http-source/src/main/java/com/amazon/dataprepper/plugins/source/loghttp/HTTPSourceConfig.java
Updated validations which require to define certificate and key file when using ACM for ssl.
=> Update HTTP source ssl validations

build-resources.gradle
Updated rest-high-level-client version from 1.3.1 to 1.3.5
=> Updated Opensearch rest high-level client

data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/PeerForwarderConfiguration.java, data-prepper-core/src/test/java/org/opensearch/dataprepper/TestDataProvider.java, data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/PeerForwarderAppConfigIT.java, data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/PeerForwarderConfigurationTest.java, data-prepper-core/src/test/resources/invalid_peer_forwarder_with_ssl.yml, data-prepper-core/src/test/resources/valid_peer_forwarder_config_with_acm_ssl.yml
Updated validations on ssl certificate and key file.
=> Updated config defaults and validations for peer forwarder

.github/workflows/opensearch-sink-opensearch-integration-tests.yml
Renamed the GitHub action which runs OpenSearch integration tests. Added the latest patch versions for all minor versions currently in the 2.x series.
N/A
=> Integration testing against latest OpenSearch versions

data-prepper-core/build.gradle, data-prepper-core/src/main/java/org/opensearch/dataprepper/parser/config/MetricsConfig.java, data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/PeerForwarderAppConfig.java, data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/PeerForwarderAppConfigIT.java
Fix: Found an issue with peer forwarder server serialization and deserialization of `EventMetaData` with `Instant` type timeReceived.
=> Added Java time module to object mapper

data-prepper-plugins/grok-prepper/src/main/java/com/amazon/dataprepper/plugins/prepper/grok/GrokPrepper.java, data-prepper-plugins/grok-prepper/src/test/java/com/amazon/dataprepper/plugins/prepper/grok/GrokPrepperTests.java
This PR refactors the shutdown behavior of the GrokProcessor to allow the ExecutorService to continue running until the `shutdown` method is invoked. This prevents exceptions when draining the buffer on pipeline shutdown for GrokPrepper configurations with a timeout.
Partially #1770 
=> Refactor GrokPrepper shutdown behavior to prevent ExecutorService from terminating prematurely

performance-test/build.gradle, performance-test/src/gatling/java/org/opensearch/dataprepper/test/performance/TargetRpsSimulation.java
Excluded group `io.pebbletemplates`, module `pebble` from performance-test package
[Issue 1781](https://github.com/opensearch-project/data-prepper/issues/1781)
=> Removed io.pebbletemplates dependency

docs/developer_guide.md, docs/getting_started.md, docs/logs.md, docs/simple_pipelines.md
This PR updates documentation for recent directory structure change, including the new script to run data prepper and the changes to configuration file location. 
Resolves #1785 
=> Update docs to reflect recent changes on directory structure

THIRD-PARTY
=> Updated third party dependency file

examples/config/pipelines-readme.txt, release/archives/build.gradle
Removes example pipeline yaml from distribution and adds a README file.
Closes #1826 
=> Remove example pipeline yaml from distribution

data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/server/PeerForwarderHttpServerProvider.java
With fingerprint verification only and mTLS enabled, the client is not sending its certificate.
```
data-prepper-1  | javax.net.ssl|DEBUG|B1|armeria-common-worker-epoll-2-1|2022-09-30 18:26:37.146 GMT|CertificateMessage.java:1178|Consuming client Certificate handshake message (
data-prepper-1  | "Certificate": {
data-prepper-1  |   "certificate_request_context": "",
data-prepper-1  |   "certificate_list": [
data-prepper-1  | ]
data-prepper-1  | }
data-prepper-1  | )
data-prepper-1  | javax.net.ssl|ERROR|B1|armeria-common-worker-epoll-2-1|2022-09-30 18:26:37.149 GMT|TransportContext.java:363|Fatal (BAD_CERTIFICATE): Empty client certificate chain
```
This causes the SSL handshake to fail. This PR adds a `FingerprintTrustManagerFactory` …
=> Add fingerprint trust store implementation to PeerForwarderHttpServer

docs/peer_forwarder.md
=> Added documentation for core peer forwarder metrics

build.gradle, data-prepper-plugins/s3-source/build.gradle
Update to Jackson 2.13.4. Removed a specific version to keep all versions using the root BOM.
Resolves #1839
Resolves #1867
=> Jackson 2.13.4

data-prepper-plugins/http-source/README.md
- Updated HTTP source ssl documentation
=> Updated http source documentation

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/buffer/AbstractBuffer.java, data-prepper-plugins/blocking-buffer/README.md, data-prepper-plugins/blocking-buffer/build.gradle, data-prepper-plugins/blocking-buffer/src/main/java/org/opensearch/dataprepper/plugins/buffer/blockingbuffer/BlockingBuffer.java, data-prepper-plugins/blocking-buffer/src/test/java/org/opensearch/dataprepper/plugins/buffer/blockingbuffer/BlockingBufferTests.java, docs/monitoring.md
- Added bufferUsage to BlockingBuffer plugin
resolves #1817 
=> adding bufferUsage to BlockingBuffer plugin

data-prepper-plugins/grok-processor/README.md, data-prepper-plugins/grok-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/grok/GrokProcessor.java, data-prepper-plugins/grok-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/grok/GrokProcessorTests.java
Signed-off-by: Qi Chen <qchea@amazon.com>
Same as described in #1892 
Contributes to #1892 
=> MAINT: rename grok match metrics

build-resources.gradle, data-prepper-plugins/service-map-stateful/build.gradle
Fixes
- protobuf-java-3.19.4.jar
- protobuf-java-3.18.1.jar
Was not able to find the dependency for 
- protobuf-java-3.21.1.jar (I believe this is from armeria 1.19)
contributes towards CVE-2022-3171 
=> Updated protobuf dependency

gradle.properties
Set the version to 2.0.0 in the `gradle.properties` file.
N/A
=> Update version to 2.0.0 for release

release/release-notes/data-prepper.change-log-2.0.0.md
```
git-release-notes 1.5.1..HEAD markdown > release/release-notes/data-prepper.change-log-2.0.0.md
```
resolves #1845 
=> Added change log for 2.0.0

gradle.properties
Version bump to 2.1.0-SNAPSHOT on the main branch
N/A
=> Bump version to 2.1.0-SNAPSHOT

release/release-notes/data-prepper.change-log-2.0.0.md
Updates the change log for Data Prepper 2.0.0 with some of the most recent changes.
```
git checkout 2.0
```
```
git-release-notes 1.5.1..HEAD markdown > release/release-notes/data-prepper.change-log-2.0.0.md
```
N/A
=> Updated the change log for 2.0.0

release/release-notes/data-prepper.release-notes-2.0.0.md
Added one of the last changes to Data Prepper.
Also added a list of breaking changes to help pipeline authors and administrators know what to do.
N/A
=> Updated the release notes for 2.0.0

gradle.properties
Updated the version number to 1.5.2
N/A
=> Version bump: Data Prepper 1.5.2

THIRD-PARTY
Auto generated THIRD_PARTY file for 1.5.2
=> [Release] Updated third party for 1.5.2

release/release-notes/data-prepper.release-notes-1.5.2.md
=> Added release notes for 1.5.2

release/release-notes/data-prepper.release-notes-2.0.1.md
Adds release notes for Data Prepper 2.0.1
N/A
=> Created release notes for Data Prepper 2.0.1

release/release-notes/data-prepper.change-log-1.5.2.md, release/release-notes/data-prepper.release-notes-1.5.2.md
Updates release notes and change log
=> Updated release notes and change log with spring change

.gitignore
Add `.iml` to `.gitignore`.
N/A
=> Add IntelliJ's .iml file extension to the .gitignore

data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/SqsWorker.java
When running the S3 source, I see a lot of messages for reading from the buffer and writing to OpenSearch. This PR adds some additional logging.
* Log the number of messages received and the number to be processed at the `INFO` level.
* Log the total deletions at the `DEBUG` level.
N/A
=> Additional SQS logging for S3 source

config/checkstyle/checkstyle.xml, data-prepper-api/src/test/java/org/opensearch/dataprepper/metrics/PluginMetricsTest.java, data-prepper-expression/src/main/java/org/opensearch/dataprepper/expression/LiteralTypeConversionsConfiguration.java, data-prepper-expression/src/main/java/org/opensearch/dataprepper/expression/OperatorConfiguration.java, data-prepper-plugins/http-source/src/test/java/org/opensearch/dataprepper/plugins/source/loghttp/HTTPSourceTest.java, data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkRetryStrategyTests.java, data-prepper-plugins/otel-metrics-source/src/test/java/org/opensearch/dataprepper/plugins/source/otelmetrics/OTelMetricsSourceTest.java, data-prepper-plugins/otel-trace-group-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/oteltracegroup/OTelTraceGroupProcessorTests.java, data-prepper-plugins/otel-trace-raw-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/oteltrace/OTelTraceRawProcessorTest.java, data-prepper-plugins/otel-trace-source/src/test/java/org/opensearch/dataprepper/plugins/source/oteltrace/OTelTraceSourceTest.java, data-prepper-plugins/service-map-stateful/src/test/java/org/opensearch/dataprepper/plugins/processor/ServiceMapStatefulProcessorTest.java, e2e-test/log/src/integrationTest/java/org/opensearch/dataprepper/integration/log/EndToEndBasicLogTest.java, e2e-test/log/src/integrationTest/java/org/opensearch/dataprepper/integration/log/ParallelGrokStringSubstituteLogTest.java, e2e-test/trace/src/integrationTest/java/org/opensearch/dataprepper/integration/trace/EndToEndRawSpanTest.java
This removes existing usages of double brace initialization and adds a checkstyle to prevent it in the future.
https://checkstyle.org/apidocs/com/puppycrawl/tools/checkstyle/checks/coding/AvoidDoubleBraceInitializationCheck.html
I also updated some of the tests to JUnit 5 since where it was relatively easy.
N/A
=> No more double brace initializer

performance-test/build.gradle
Fixes scala CVE in Gatling plugin
https://advisories.aws.barahmand.com/advisory/CVE-2022-36944
=> Fix: CVE-2022-36944

data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/discovery/AwsCloudMapPeerListProvider.java, data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/ProcessWorker.java, data-prepper-plugins/common/src/main/java/org/opensearch/dataprepper/plugins/source/RandomStringSource.java, data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSink.java, data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/SqsWorker.java, data-prepper-plugins/service-map-stateful/src/main/java/org/opensearch/dataprepper/plugins/processor/ServiceMapStatefulProcessor.java
Updates the INFO level logs to DEBUG
=> Updated info logs to debug level

build-resources.gradle, build.gradle
=> Fix: CVE-2022-3509, CVE-2022-3510

docs/overview.md
Fix Documentation Overview
* Link
* Typo
For more information on the following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).
Signed-off-by:  Shanelle Marasigan
=> MOD: fix typos 

data-prepper-core/build.gradle, data-prepper-expression/build.gradle, data-prepper-plugins/opensearch/build.gradle
Fix logging by updating related packages for SLF4J 2.0.x
Fixes #2097
=> Fix logging

data-prepper-api/src/main/java/org/opensearch/dataprepper/metrics/MetricNames.java, data-prepper-api/src/main/java/org/opensearch/dataprepper/model/buffer/AbstractBuffer.java, data-prepper-api/src/test/java/org/opensearch/dataprepper/model/buffer/AbstractBufferTest.java, docs/monitoring.md
Added recordsOverflow metric as common metric in AbstractBuffer
Resolves #2167 
=> ENH: add buffer records overflow metrics

.github/workflows/opensearch-sink-opensearch-integration-tests.yml, build-resources.gradle
- Updated OpenSearch version to 1.3.7
- Adds 1.3.7 version to integration test
=> Updated OpenSearch version to 1.3.7

data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/integration/MultiWorkerPipelineIT.java, data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/plugins/ThreadInfoProcessor.java, data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/multi-worker.yaml
Adds an integration test to Data Prepper core which validates that multiple process workers functions correctly.
N/A
=> Integration test for a pipeline with multiple process workers

data-prepper-plugins/opensearch/README.md, data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkRetryStrategy.java
Add missing metrics for Opensearch 
Resolves #2168 
=> Add missing metrics for Opensearch Sink #2168

build.gradle, data-prepper-plugins/anomaly-detector-processor/build.gradle
These dependencies should not be in all projects. This PR moves them only into the Anomaly Detection processor project.
N/A
=> Moved Random Cut Forest libraries to the Anomaly Detection processor.

data-prepper-plugins/trace-peer-forwarder-processor/README.md
Adds trace peer forwarder readme
resolves #2141 
=> Added trace peer forwarder doc

.github/workflows/data-prepper-peer-forwarder-static-e2e-tests.yml, e2e-test/log/README.md, e2e-test/log/src/integrationTest/java/org/opensearch/dataprepper/integration/log/ParallelGrokStringSubstituteLogTest.java, e2e-test/peerforwarder/README.md, e2e-test/peerforwarder/build.gradle, e2e-test/peerforwarder/src/integrationTest/java/org/opensearch/dataprepper/integration/peerforwarder/EndToEndLogMetricsTest.java
- Fixed assertions in EndToEndLogMetricsTest test
- Added EndToEndLogMetricsTest test to workflows
- Cleaned up ParallelGrokStringSubstituteLogTest
- Added documentation for EndToEndLogMetricsTest, ParallelGrokStringSubstituteLogTest
=> Fix: e2e tests and added documentation

build.gradle, data-prepper-plugins/aggregate-processor/build.gradle, data-prepper-plugins/opensearch/build.gradle, data-prepper-plugins/otel-metrics-raw-processor/build.gradle, data-prepper-plugins/otel-trace-raw-processor/build.gradle, settings.gradle
Updates Guava dependency
Fixes CVE-2020-8908, CVE-2018-10237
=> CVE: updated guava version

settings.gradle
Update the opensearch dependencies to 1.3.8.
Resolves #2192
Resolves #2193
=> Update to opensearch 1.3.8

data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/PeerForwarderConfiguration.java, data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/PeerForwarderProvider.java, data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/RemotePeerForwarder.java, data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/PeerForwarderConfigurationTest.java, data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/PeerForwarder_ClientServerIT.java, data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/RemotePeerForwarderTest.java, data-prepper-core/src/test/resources/valid_peer_forwarder_config.yml, docs/peer_forwarder.md
* Make batching queue depth configurable
* Increase max batch size
* Add documentation for batching configurations
=> Make batching queue depth configurable, fill in some missing documentation around batching

data-prepper-plugins/otel-metrics-source/src/main/java/org/opensearch/dataprepper/plugins/source/otelmetrics/OTelMetricsGrpcService.java, data-prepper-plugins/otel-metrics-source/src/test/java/org/opensearch/dataprepper/plugins/source/otelmetrics/OTelMetricsGrpcServiceTest.java
Adds more metrics to OTEL metrics source to get closer to parity with OTEL trace source
#2282
=> Add more metrics to OTEL metrics source

data-prepper-plugins/opensearch/build.gradle
Updates the `opensearch-java` project to 2.2.0.
None, but will help toward #1881.
=> Updates to opensearch-java 2.2.0

examples/trace-analytics-sample-app/sample-app/requirements.txt
Updates opentelemetry dependencies to resolve CVEs
https://github.com/opensearch-project/data-prepper/issues/2279
https://github.com/opensearch-project/data-prepper/issues/2280
=> Updates opentelemetry dependencies

gradle.properties
Updated to 2.1.0 release version on 2.1 branch
=> Updated to 2.1.0 release version

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/configuration/DataPrepperVersion.java, gradle.properties
=> Updated version to 2.2 snapshot on main

release/release-notes/data-prepper.release-notes-2.1.0.md
Add release notes for 2.1.0 release
resolves #2172 
=> Add release notes for 2.1.0

release/release-notes/data-prepper.change-log-2.1.0.md
`git-release-notes 2.0.1..HEAD markdown > data-prepper.change-log-2.1.0.md`
resolves #2173 
=> Added 2.1 change log

gradle.properties
=> Updated version to 2.1.1

release/release-notes/data-prepper.release-notes-2.1.1.md
=> Added release notes for 2.1.1

data-prepper-plugins/service-map-stateful/src/main/java/org/opensearch/dataprepper/plugins/processor/ServiceMapRelationship.java, data-prepper-plugins/service-map-stateful/src/main/java/org/opensearch/dataprepper/plugins/processor/ServiceMapStatefulProcessor.java, data-prepper-plugins/service-map-stateful/src/test/java/org/opensearch/dataprepper/plugins/processor/ServiceMapRelationshipTest.java, data-prepper-plugins/service-map-stateful/src/test/java/org/opensearch/dataprepper/plugins/processor/ServiceMapStatefulProcessorTest.java
This PR fixes the isolated service not picked up by service-map relationship.
Resolves #628 
=> FIX: isolated service node

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/failures/DlqObject.java, data-prepper-api/src/test/java/org/opensearch/dataprepper/model/failures/DlqObjectTest.java, data-prepper-plugins/failures-common/build.gradle, data-prepper-plugins/failures-common/src/main/java/org/opensearch/dataprepper/dlq/DlqProvider.java, data-prepper-plugins/failures-common/src/main/java/org/opensearch/dataprepper/dlq/DlqWriter.java
The PR creates a few building blocks to begin building a generic S3 DLQ as part of #2298
None
=> adding dlqObject and dlqWriter interface to

data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/SqsWorker.java
Improves SQS logging including failure scenarios
=> Updated SQS logging

data-prepper-plugins/s3-source/README.md, data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3Source.java, data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/configuration/S3SelectOptions.java, data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/S3SelectObjectWorkerTest.java, data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/compression/SnappyCompressionEngineTest.java, data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/configuration/S3SelectOptionsTest.java
This is a continuation of #2437. 
=> Addresses S3 Select YAML code review suggestions

data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/PeerForwarderReceiveBuffer.java, data-prepper-plugins/blocking-buffer/src/main/java/org/opensearch/dataprepper/plugins/buffer/blockingbuffer/BlockingBuffer.java, data-prepper-plugins/common/src/main/java/org/opensearch/dataprepper/plugins/certificate/acm/ACMCertificateProvider.java, data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/ConnectionConfiguration.java, data-prepper-plugins/otel-trace-raw-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/oteltrace/OTelTraceRawProcessor.java, data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/codec/CsvCodec.java, data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/configuration/AwsAuthenticationOptions.java
This PR improves the logging messages of the CSV codec, as well as the exception logging when the role ARNs are invalid. It also changes some of the logging messages to debug so they don't fill the logs up with noise. Right now it is difficult for users to take action on some of the log messages as they aren't descriptive enough, and this PR improves this by making the logs more clear.
=> Logging improvements to the csv codec, role arn, and span messages

data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/AppendAggregateAction.java, data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/AppendAggregateActionTest.java
Fixes star imports from https://github.com/opensearch-project/data-prepper/pull/2230#pullrequestreview-1373053058
=> Fix imports for AppendAggregateAction

data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/integration/PipelinesWithAcksIT.java, data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/plugins/InMemoryConfig.java, data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/plugins/InMemorySink.java, data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/plugins/InMemorySinkAccessor.java, data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/plugins/InMemorySource.java, data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/plugins/InMemorySourceAccessor.java, data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/acknowledgements/one-pipeline-ack-expiry-test.yaml, data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/acknowledgements/one-pipeline-three-sinks.yaml, data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/acknowledgements/simple-test.yaml, data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/acknowledgements/three-pipeline-route-test.yaml, data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/acknowledgements/three-pipelines-test-multi-sink.yaml, data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/acknowledgements/three-pipelines-test.yaml, data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/acknowledgements/two-parallel-pipelines-test.yaml, data-prepper-core/src/integrationTest/resources/org/opensearch/dataprepper/pipeline/acknowledgements/two-pipelines-test.yaml
Added integration tests for end-to-end acknowledgements
=> Added integration tests for end-to-end acknowledgements

data-prepper-plugins/opensearch/src/integrationTest/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSinkIT.java
checkstyle is failing from #2516
none
=> address build failure in 2511

data-prepper-plugins/mutate-event-processors/README.md
This PR adds documentation for `list_to_map` processor
N/A
=> Add documentation for list_to_map processor

gradle.properties
Updates the Gradle version to `2.2.0` in preparation for the 2.2.0 release.
This targets the `2.2` branch.
N/A
=> Update the version to 2.2.0

release/release-notes/data-prepper.release-notes-2.2.0.md
=> Added 2.2 release notes

gradle.properties
Updates the `2.2` branch to the next Data Prepper version: `2.2.1`.
N/A
=> Next version: 2.2.1

gradle.properties
Updates `main` branch to `2.3.0-SNAPSHOT`
N/A
=> Updates main branch to 2.3.0-SNAPSHOT

data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateAction.java, data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateActionSynchronizer.java, data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateProcessor.java
Addressing comments made in PR 2497.
=> Followup to 2497. Addressing comments from PR 2497

release/release-notes/data-prepper.change-log-2.2.1.md
Change log for 2.2.1 release
`git-release-notes 2.2.0..HEAD markdown > data-prepper.change-log-2.2.1.md`
=> Added 2.2.1 change log

release/release-notes/data-prepper.release-notes-2.2.1.md
Added release notes for 2.2.1 release
N/A
=> Added 2.2.1 release notes

data-prepper-plugins/kafka-plugins/build.gradle
Use spring-test version from testLibs to fix CVEs
Resolves #2670 
Resolves #2671 
=> Fix CVEs discovered in Kafka plugins

data-prepper-core/src/main/java/org/opensearch/dataprepper/sourcecoordination/LeaseBasedSourceCoordinator.java, data-prepper-core/src/main/java/org/opensearch/dataprepper/sourcecoordination/SourceCoordinatorFactory.java, data-prepper-core/src/test/java/org/opensearch/dataprepper/sourcecoordination/LeaseBasedSourceCoordinatorTest.java
Instruments a number of metrics to give insight into progress tracking and failures in the source coordinator
Related to #2412 
=> Instrument metrics in LeaseBasedSourceCoordinator

data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/OpenSearchService.java, data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/OpenSearchSource.java, data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/PitWorker.java, data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/ScrollWorker.java, data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/SearchWorkerStrategy.java, data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/ElasticsearchAccessor.java, data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/OpenSearchAccessor.java, data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/SearchAccessor.java, data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/SearchAccessorStrategy.java, data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/model/CreatePitRequest.java, data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/model/CreatePitResponse.java, data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/model/CreateScrollRequest.java, data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/model/CreateScrollResponse.java, data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/model/DeletePitRequest.java, data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/model/DeleteScrollRequest.java, data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/model/SearchPitRequest.java, data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/model/SearchPitResponse.java, data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/model/SearchScrollRequest.java, data-prepper-plugins/opensearch-source/src/main/java/org/opensearch/dataprepper/plugins/source/opensearch/worker/client/model/SearchScrollResponse.java
Creating a high level class structure. The goal is to align on plugin structure and make it easier for multiple contributors to work on the plugin at once. This PR does not include unit tests as there are no methods implemented at this time.
This is the current proposal for the class design. This is a rough sketch I threw together. It captures the classes in this PR and helps demonstrate the relationships between them:
related to #1985 
=> creating boilerplate for OpenSearch Source

data-prepper-plugins/obfuscate-processor/README.md, data-prepper-plugins/obfuscate-processor/build.gradle, data-prepper-plugins/obfuscate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/obfuscation/CommonPattern.java, data-prepper-plugins/obfuscate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/obfuscation/ObfuscationProcessor.java, data-prepper-plugins/obfuscate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/obfuscation/ObfuscationProcessorConfig.java, data-prepper-plugins/obfuscate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/obfuscation/action/MaskAction.java, data-prepper-plugins/obfuscate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/obfuscation/action/MaskActionConfig.java, data-prepper-plugins/obfuscate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/obfuscation/action/ObfuscationAction.java, data-prepper-plugins/obfuscate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/obfuscation/ObfuscationProcessorTest.java, data-prepper-plugins/obfuscate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/obfuscation/action/MaskActionTest.java, settings.gradle
Add obfuscation processor
Resolve #1952 
=> Add obfuscation processor

data-prepper-plugins/anomaly-detector-processor/README.md, data-prepper-plugins/anomaly-detector-processor/build.gradle, data-prepper-plugins/anomaly-detector-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/anomalydetector/modes/RandomCutForestMode.java, data-prepper-plugins/anomaly-detector-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/anomalydetector/modes/RandomCutForestModeConfig.java, data-prepper-plugins/anomaly-detector-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/anomalydetector/AnomalyDetectorProcessorTests.java, data-prepper-plugins/anomaly-detector-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/anomalydetector/modes/RandomCutForestModeConfigTests.java, data-prepper-plugins/anomaly-detector-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/anomalydetector/modes/RandomCutForestModeTests.java
Updates RCF maven version to 3.7. This version of RCF has some fixes to reduce noise (low grade anomalies)
Resolves #2783 
#2783 
=> Update RCF Maven version to reduce noise

data-prepper-plugins/in-memory-source-coordination-store/src/main/java/org/opensearch/dataprepper/plugins/sourcecoordinator/inmemory/InMemoryPartitionAccessor.java, data-prepper-plugins/in-memory-source-coordination-store/src/test/java/org/opensearch/dataprepper/plugins/sourcecoordinator/inmemory/InMemoryPartitionAccessorTest.java
The in memory store was broken by this commit (https://github.com/opensearch-project/data-prepper/commit/723cc2bd56e06692a289944fe4d1d35475c6d589). There are a couple options for supporting this change (the in memory store does not technically need this global state since only a single node will be running. But the implementation in this PR is the simplest way to support it
Related to #2412 
=> Support global state items in the in memory source coordination store

data-prepper-plugins/s3-source/README.md
adding missing readme details on new metric
N/A
=> addressing missing metrics in README

docs/end_to_end_acknowledgements.md
Document describing the end to end acknowledgment support in Data Prepper
- [X ] New functionality has javadoc added
=> Add a doc for end to end acknowledgements

release/release-notes/data-prepper.release-notes-2.3.0.md
Adds the release notes for Data Prepper 2.3.0.
N/A
=> Adds release notes for Data Prepper 2.3.0

release/release-notes/data-prepper.change-log-2.3.0.md
`release-notes 2.2.1..HEAD markdown > data-prepper.change-log-2.3.0.md`
=> Added change log for 2.3

data-prepper-plugins/avro-codecs/src/main/java/org/opensearch/dataprepper/plugins/codec/avro/AvroOutputCodecConfig.java, data-prepper-plugins/csv-processor/src/main/java/org/opensearch/dataprepper/plugins/codec/csv/CsvOutputCodecConfig.java, data-prepper-plugins/parquet-codecs/src/main/java/org/opensearch/dataprepper/plugins/codec/parquet/ParquetOutputCodecConfig.java
Signed-off-by: omkarmmore95 <omkar.m.more95@gmail.com>
Configuration Classes for sink codecs 
1. `CsvOutputCodecConfig`
2. `ParquetOutputCodecConfig`
3. `AvroOutputCodecConfig`
Resolved #2403 
=> -Support for Sink Codecs

gradle.properties
=> Update to next version 2.3.1

data-prepper-plugins/aws-plugin/src/main/java/org/opensearch/dataprepper/plugins/aws/CredentialsCache.java
=> FIX: concurrentModification in CredentialsCache

data-prepper-plugins/s3-sink/README.md
The configuration in the S3 README was not correct. This PR fixes that 
NA
=> Update README.md for S3 sink

data-prepper-plugins/geoip-processor/build.gradle, data-prepper-plugins/geoip-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/GeoIPProcessor.java, data-prepper-plugins/geoip-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/GeoIPProcessorService.java, data-prepper-plugins/geoip-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/databasedownload/DBSource.java, data-prepper-plugins/geoip-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/databasedownload/DBSourceOptions.java, data-prepper-plugins/geoip-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/databasedownload/DatabaseReaderCreate.java, data-prepper-plugins/geoip-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/databasedownload/HttpDBDownloadService.java, data-prepper-plugins/geoip-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/databasedownload/LicenseTypeOptions.java, data-prepper-plugins/geoip-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/databasedownload/LocalDBDownloadService.java, data-prepper-plugins/geoip-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/databasedownload/S3DBService.java, data-prepper-plugins/geoip-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/databaseenrich/EnrichFailedException.java, data-prepper-plugins/geoip-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/databaseenrich/GetGeoData.java, data-prepper-plugins/geoip-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/databaseenrich/GetGeoIP2Data.java, data-prepper-plugins/geoip-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/databaseenrich/GetGeoLite2Data.java, data-prepper-plugins/geoip-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/utils/DbSourceIdentification.java, data-prepper-plugins/geoip-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/utils/IPValidationcheck.java, data-prepper-plugins/geoip-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/utils/LicenseTypeCheck.java
Implementation of GeoIP Plugin Code Structure
GitHub-issue #253
=> GitHub-issue#253 : Implementation of GeoIP Plugin Code Structure

release/release-notes/data-prepper.change-log-2.3.1.md
executed `git-release-notes 2.3.0..HEAD markdown > data-prepper.change-log-2.3.1.md` on 2.3 branch to get the change log.
=> Added 2.3.1 change log

release/release-notes/data-prepper.release-notes-2.3.1.md
Add release notes for 2.3.1 release
=> Added 2.3.1 release notes

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/DefaultEventMetadata.java, data-prepper-api/src/test/java/org/opensearch/dataprepper/model/event/DefaultEventMetadataTest.java
Fix addTags API in EventMetadata
=> Fix addTags API in EventMetadata

data-prepper-plugins/kafka-plugins/build.gradle, data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/configuration/AwsConfig.java, data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/configuration/KafkaSourceConfig.java, data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaSourceCustomConsumer.java, data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/TopicPartitionCommitTracker.java, data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/source/KafkaSource.java, data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/configuration/AwsConfigTest.java, data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/configuration/KafkaSourceConfigTest.java, data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaSourceCustomConsumerTest.java, data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/consumer/TopicPartitionCommitTrackerTest.java, data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/source/KafkaSourceTest.java
Added Kafka config to support acknowledgments and MSK arn
1. Added support for end-to-end acknowledgements.
* Added configuration for enabling acknowledgements and timeout
* Added TopicPartition commit tracker to address acknowledgements being received in different order of offsets and commit only if all the acks for all the previous offsets is received.
2. Added config for MSK ARN …
=> Added Kafka config to support acknowledgments and MSK arn

data-prepper-plugins/armeria-common/src/main/java/org/opensearch/dataprepper/armeria/authentication/ArmeriaHttpAuthenticationProvider.java, data-prepper-plugins/armeria-common/src/main/java/org/opensearch/dataprepper/armeria/authentication/GrpcAuthenticationProvider.java, data-prepper-plugins/common/src/main/java/org/opensearch/dataprepper/plugins/s3keyindex/S3ObjectIndexUtility.java, data-prepper-plugins/common/src/main/java/org/opensearch/dataprepper/plugins/sink/FileSink.java, data-prepper-plugins/common/src/main/java/org/opensearch/dataprepper/plugins/sink/StdOutSink.java
Fix Stdout and File sink.
Tags are not printed by Stdout. Added constructor annotation to fix it.
Cleaned up javadoc errors and warnings.
=> Fix Stdout and File sink

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/acknowledgements/AcknowledgementSet.java, data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/plugins/InMemorySource.java, data-prepper-core/src/main/java/org/opensearch/dataprepper/acknowledgements/DefaultAcknowledgementSet.java, data-prepper-core/src/test/java/org/opensearch/dataprepper/acknowledgements/DefaultAcknowledgementSetManagerTests.java, data-prepper-core/src/test/java/org/opensearch/dataprepper/acknowledgements/DefaultAcknowledgementSetTests.java, data-prepper-plugins/s3-source/src/integrationTest/java/org/opensearch/dataprepper/plugins/source/SqsWorkerIT.java, data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/SqsWorker.java
=> Backport/backport 3001 to 2.3

gradle.properties
Updates to Data Prepper 2.3.2
N/A
=> Updated to Data Prepper 2.3.2 for release.

release/release-notes/data-prepper.release-notes-2.3.2.md
Adds release notes for Data Prepper 2.3.2
N/A
=> Release notes for Data Prepper 2.3.2

data-prepper-plugins/translate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/translate/MappingsParameterConfig.java, data-prepper-plugins/translate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/translate/MappingsParser.java, data-prepper-plugins/translate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/translate/TargetsParameterConfig.java, data-prepper-plugins/translate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/translate/TranslateProcessor.java, data-prepper-plugins/translate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/translate/TranslateProcessorConfig.java, data-prepper-plugins/translate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/translate/MappingsParameterConfigTest.java, data-prepper-plugins/translate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/translate/TargetsParameterConfigTest.java, data-prepper-plugins/translate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/translate/TranslateProcessorConfigTest.java, data-prepper-plugins/translate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/translate/TranslateProcessorTest.java
Added functionality for multiple sources and multiple targets
=> Translate Plugin: Simplified Config. 

data-prepper-plugins/translate-processor/README.md
README.md file for Translate Processor
=> Translate Processor : Added Readme file

.github/pull_request_template.md, docs/developer_guide.md
I updated the documentation process in the `developer_guide.md` file. In a sense, this PR is also a proposal for this documentation process, so feel free to comment on the process. I also updated the PR template to fit this model.
Additionally, unrelated to documentation, I updated the section for `Issues Resolved` to encourage correct usage of the feature.
N/A
=> Updates the documentation process and instructions for it

data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/source/KafkaSource.java, data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/util/KafkaSourceSecurityConfigurer.java, data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/source/KafkaSourceTest.java
Fix Null pointer exception when schema registry not specified. PR 
=> Fix Null pointer exception when schema registry not specified

data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3ScanPartitionCreationSupplier.java, data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/ScanObjectWorker.java
Add catching and logging of exceptions for s3 scan worker
=> Add catching and logging of exceptions for s3 scan worker

gradle.properties
Update the version to 2.4 on 2.4 release branch
=> Set release version to 2.4

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/configuration/DataPrepperVersion.java, gradle.properties
Update main branch version to 2.5.0
=> Set main version to 2.5.0

release/release-notes/data-prepper.release-notes-2.4.0.md
=> Add 2.4 release notes

data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/ScanObjectWorker.java, data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/S3ScanObjectWorkerTest.java
If the order of operations for s3 scan is 
```
1. scan bucket for objects and create partitions
2. one of the objects is deleted in the bucket
3. this object is picked up from the store for processing
```
then a NoSuchKeyException is thrown, instead of this deleted object causing a cycle of retrying, which would essentially make that node useless, we log that the object could not be found, mark it as completed, and continue processing
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBU …
=> Catch when no object exists and mark as completed in s3 scan

data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/S3SinkService.java
When failures occur writing to the S3 sink, there are lots of logs. This PR reduces them somewhat by batch each call to `output()` to generate a single error line for all the failures.
N/A
=> Batch the errors writing to the S3 sink to reduce the number of errors

RELEASING.md, release/README.md
Adds a new file `RELEASING.md` which outlines release instructions. This has updated instructions for the new release process added in 2.4.0.
Resolves #3108
=> Adds a RELEASING.md file to the root of the project

release/README.md
Fixes a build failure introduced in #3251 with bad formatting on the new `RELEASING.md` file.
N/A
=> Fixes build broken by RELEASING.md spotless check

data-prepper-plugins/geoip-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/GeoIPProcessorServiceTest.java, data-prepper-plugins/geoip-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/databasedownload/HttpDBDownloadServiceTest.java, data-prepper-plugins/geoip-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/utils/DbSourceIdentificationTest.java
Removes Maxmind license keys which should not be present in code.
N/A
=> Removes Maxmind license keys from test URLs

data-prepper-plugins/blocking-buffer/src/test/java/org/opensearch/dataprepper/plugins/buffer/blockingbuffer/BlockingBufferTests.java
The `BlockingBufferTests` use read timeouts of 5 seconds. This reduces them to 0.5 seconds. The Gradle `test` task is now running at 5 seconds rather than 40 seconds.
N/A
=> Reduce sleep times in BlockingBufferTests to speed up unit tests.

data-prepper-plugins/sqs-source/src/test/java/org/opensearch/dataprepper/plugins/source/sqssource/SqsSourceTaskTest.java, data-prepper-plugins/sqs-source/src/test/java/org/opensearch/dataprepper/plugins/source/sqssource/handler/RawSqsMessageHandlerTest.java
Updates the SQS source tests to use mocking. These changes reduce the build time by almost one minute.
N/A
=> SQS Source test simplification and speed up

data-prepper-plugins/rss-source/README.md
Adds README for RSS Source plugin
Resolves #2349 
=> Adds README for the RSS Source plugin

e2e-test/build.gradle, e2e-test/log/build.gradle, e2e-test/peerforwarder/build.gradle, e2e-test/trace/build.gradle
Some refactoring to the end-to-end tests to consolidate tasks which are used in common.
N/A
=> Consolidate the end-to-end Gradle tasks

data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSink.java
There are logs in the OpenSearch sink that are censored, and not helpful for failure to write to opensearch or the dlq. 
Improves the logging of failure to write with error code and message
=> Improve logging for failed documents in the OpenSearch sink

build.gradle, data-prepper-plugins/parquet-codecs/build.gradle, data-prepper-plugins/s3-sink/build.gradle, data-prepper-plugins/s3-source/build.gradle, settings.gradle
* CVE fixes CVE-2022-36944, WS-2023-0116, CVE-2021-39194, CVE-2023-3635, CVE-2023-36479, CVE-2023-40167
* Fix WS-2023-0236
---------
(cherry picked from commit 5fdf95fa368cbf6a51aef44135e8e909d9fc58f9)
=> CVE fixes (#3385)

gradle.properties
Update to 2.4.1 release version
=> 2.4.1 version

release/release-notes/data-prepper.change-log-2.4.1.md
2.4.1 change log
` git-release-notes 2.4.0..HEAD markdown > data-prepper.change-log-2.4.1.md`
=> 2.4.1 change log

release/release-notes/data-prepper-release-notes-2.4.1.md
=> 2.4.1 release notes

build.gradle
=> Fix CVE-2022-45688, CVE-2023-43642

gradle.properties
=> Set 2.5 release version

data-prepper-plugins/kafka-plugins/src/integrationTest/java/org/opensearch/dataprepper/plugins/kafka/source/KafkaSourceJsonTypeIT.java
This PR makes internal improvements to the KafkaSourceJsonTypeIT. It uses Awaitility, fails faster, and has useful logging on errors. Additionally, it consolidates the setup and tear down work.
N/A
=> Use Awaitility in the KafkaSourceJsonTypeIT and consolidate setup/tear down

.github/workflows/kafka-plugin-integration-tests.yml, data-prepper-plugins/kafka-plugins/src/integrationTest/java/org/opensearch/dataprepper/plugins/kafka/buffer/KafkaBufferIT.java, data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/producer/KafkaCustomProducer.java, data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/sink/DLQSink.java, data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/util/SinkPropertyConfigurer.java
This PR accomplishes a couple of goals:
* Fixes the Kafka buffer to run correctly. There were issues in the producer/sink code which this PR fixes.
* Adds a Kafka buffer integration test and include it in the GitHub Actions.
Work toward #3322.
=> Kafka buffer/sink fixes and Kafka buffer integration tests

data-prepper-plugins/avro-codecs/build.gradle, data-prepper-plugins/kafka-plugins/build.gradle, data-prepper-plugins/parquet-codecs/build.gradle, data-prepper-plugins/s3-sink/build.gradle, data-prepper-plugins/s3-source/build.gradle, settings.gradle
Resolved CVE related to `avro`
=> Fix CVE-2023-39410

release/release-notes/data-prepper.release-notes-2.5.0.md
Add release-notes for 2.5.0 release. Please add comments if I missed anything.
=> Add release-notes for 2.5.0

gradle/wrapper/gradle-wrapper.properties, gradlew
Build with Gradle 8.4.
```
./gradlew wrapper --gradle-version 8.4
```
Resolves #3330
=> Gradle 8.4

data-prepper-plugins/kafka-plugins/README.md, data-prepper-plugins/kafka-plugins/build.gradle, data-prepper-plugins/kafka-plugins/src/integrationTest/java/org/opensearch/dataprepper/plugins/kafka/source/ConfluentKafkaProducerConsumerIT.java, data-prepper-plugins/kafka-plugins/src/integrationTest/java/org/opensearch/dataprepper/plugins/kafka/source/ConfluentKafkaProducerConsumerWithSchemaRegistryIT.java, data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/source/KafkaSource.java
Added integration tests for Confluent kafka
- [X ] New functionality has a documentation issue. Please link to it in this PR.
=> Integration tests for confluent kakfa

data-prepper-plugins/dynamodb-source/build.gradle, data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/DynamoDBService.java, data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/DynamoDBSource.java, data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/converter/ExportRecordConverter.java, data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/converter/MetadataKeyAttributes.java, data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/converter/RecordConverter.java, data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/converter/StreamRecordConverter.java, data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/export/DataFileLoaderFactory.java, data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/export/DataFileScheduler.java, data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/ShardConsumerFactory.java, data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/ShardManager.java, data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/converter/ExportRecordConverterTest.java, data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/converter/StreamRecordConverterTest.java, data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/export/DataFileLoaderFactoryTest.java, data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/ShardConsumerFactoryTest.java
Fix below bugs:
1. The Starting position is not working properly, always defaults to TRIM_HORIZATION even the value is "LATEST"
2. The delete event doesn't work. The parition key and sort key were extracted from 'New Image' of the event, however, for delete, 'New Image' is empty.
Make below improvements:
1.  Use bufferAccumulator for sending events to buffer. Currently there is no handling on back pressure from buffer, hence when buffer was close to write (circuit break), data will be lost.
2. Other miscellaneous improvement. …
=> Add bug fixes and improvements to DDB source

data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/buffer/KafkaBufferConfig.java
Enable acknowledgements for KafkaBuffer plugin
Enables acknowledgements for kafka buffer, which is currently disabled.
=> Enable acknowledgements for KafkaBuffer plugin

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/configuration/PluginSetting.java, data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/EventHandle.java, data-prepper-api/src/main/java/org/opensearch/dataprepper/model/plugin/PluginConfigObservable.java, data-prepper-api/src/main/java/org/opensearch/dataprepper/model/plugin/PluginConfigPublisher.java, data-prepper-api/src/main/java/org/opensearch/dataprepper/model/plugin/PluginFactory.java, data-prepper-api/src/main/java/org/opensearch/dataprepper/model/source/coordinator/enhanced/EnhancedSourcePartition.java
=> Javadoc fixes

data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/ShardConsumer.java
Optimize idle item between GetRecords call base on the delay.  
If the delay (the current date time - event creation date time) is larger than a threshold value (15 seconds here), then reduce the idle time.
N/A
=> Optimize idle item between GetRecords call

data-prepper-plugins/kafka-plugins/src/integrationTest/java/org/opensearch/dataprepper/plugins/kafka/sink/KafkaSinkAvroTypeIT.java, data-prepper-plugins/kafka-plugins/src/integrationTest/java/org/opensearch/dataprepper/plugins/kafka/sink/KafkaSinkJsonTypeIT.java, data-prepper-plugins/kafka-plugins/src/integrationTest/java/org/opensearch/dataprepper/plugins/kafka/sink/KafkaSinkPlainTextTypeIT.java, data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/buffer/KafkaBuffer.java, data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/buffer/KafkaBufferConfig.java, data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaCustomConsumer.java, data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaCustomConsumerFactory.java, data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/producer/KafkaCustomProducer.java, data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/producer/KafkaCustomProducerFactory.java, data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/sink/KafkaSink.java, data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/source/KafkaSource.java, data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/util/KafkaTopicConsumerMetrics.java, data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/util/KafkaTopicProducerMetrics.java, data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/buffer/KafkaBufferTest.java, data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaCustomConsumerTest.java, data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/producer/KafkaCustomProducerTest.java, data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/sink/KafkaSinkTest.java, data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/util/KafkaTopicConsumerMetricsTests.java, data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/util/KafkaTopicProducerMetricsTests.java
Add Kafka Producer Metrics and Kafka Buffer Metrics
=> Add Kafka Producer Metrics and Kafka Buffer Metrics

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/sink/SinkLatencyMetrics.java
=> Change Latency Metric names

data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/discovery/AwsCloudMapPeerListProvider.java, data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/discovery/AwsCloudMapPeerListProviderTest.java
This PR attempts to fix flaky tests in `AwsCloudMapPeerListProviderTest`.
* Uses `await()` rather than the `Awaitility`. This is more code hygiene. 
* Increase the wait for peers to 5 seconds from 2.
* Update the API to accept `Duration` instead of seconds for the refresh interval. Now the tests are using 200 milliseconds to refresh.
Note, but contributes toward #3481.
=> Attempting to fix the flaky tests in AwsCloudMapPeerListProviderTest

data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/leader/LeaderScheduler.java
This fix will retry initialization process every minutes until all issues (Such as permission, or PITR/stream is not enabled, etc) resolved by customers. There is no need to restart or recreate pipeline for these issues.
Resolves #3623 
=> Fix initialization issue in DynamoDB source

data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkRetryStrategy.java, data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkRetryStrategyTests.java
This adds a check for an empty list of failed documents. This could happen when a bulk request fails with all documents having the failure. For example, when there is no permission to write to a certain index, but there are permissions to write to a domain, all of the documents in that index will fail.
Resolves #3644
=> Do not send empty lists to the DLQ when all items share the same retryable failure

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/sink/SinkLatencyMetrics.java
Undo rename change done in PR 3656
=> Undo rename change done in PR 3656

data-prepper-plugins/armeria-common/src/main/java/org/opensearch/dataprepper/GrpcRequestExceptionHandler.java, data-prepper-plugins/armeria-common/src/main/java/org/opensearch/dataprepper/HttpRequestExceptionHandler.java
Improves exception handling logging for both gRPC and HTTP
Resolves #3621 
=> Update gRPC and HTTP logging

data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/leader/LeaderScheduler.java, data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/leader/ShardManager.java
Fix the leader partition time out issue when error occured.
Resolves #3665
=> Fix leader partition time out issue due to exception

testing/aws-testing-cdk/.eslintrc.js, testing/aws-testing-cdk/.gitignore, testing/aws-testing-cdk/.npmignore, testing/aws-testing-cdk/README.md, testing/aws-testing-cdk/bin/aws-testing-cdk.ts, testing/aws-testing-cdk/cdk.json, testing/aws-testing-cdk/jest.config.js, testing/aws-testing-cdk/lib/aws-secrets-manager/SecretsManagerStack.ts, testing/aws-testing-cdk/lib/common/GitHubAccessStack.ts, testing/aws-testing-cdk/lib/common/GitHubStack.ts, testing/aws-testing-cdk/package-lock.json, testing/aws-testing-cdk/package.json, testing/aws-testing-cdk/tsconfig.json
=> ADD: initial AWS testing resources CDK

data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/leader/LeaderScheduler.java, data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/leader/LeaderSchedulerTest.java
I found that the DynamoDB source sometimes throws an exception when there is no leader partition. This prevents the node from processing data.
The fix is to check if there is a leader partition before saving its state.
To facilitate with testing, I also allow for a smaller lease interval. This way the test does not need to wait for over 1 minute for the lease to continue.
N/A
=> Fix an NPE when the DynamoDB LeaderScheduler does not receive a leader partition

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/configuration/DataPrepperVersion.java, gradle.properties
Updates the next Data Prepper version to 2.7.0.
N/A
=> Updates the next Data Prepper version to 2.7.0

release/release-notes/data-prepper.release-notes-2.6.0.md
Adds release notes for Data Prepper 2.6.0.
N/A
=> Release notes for Data Prepper 2.6.0

release/release-notes/data-prepper.change-log-2.6.0.md
=> Add 2.6.0 change log

testing/aws-testing-cdk/lib/common/GitHubAccessStack.ts
=> FIX: aws credentials from pull request in github actions.

data-prepper-plugins/common/README.md, data-prepper-plugins/common/src/main/java/org/opensearch/dataprepper/plugins/sink/FileSink.java, data-prepper-plugins/common/src/main/java/org/opensearch/dataprepper/plugins/sink/FileSinkConfig.java, data-prepper-plugins/common/src/test/java/org/opensearch/dataprepper/plugins/sink/FileSinkTests.java
Add append mode option to `file:` sink
Resolves #3687 
Resolves #3687 
=> Support append mode to file sink

examples/trace-analytics-sample-app/sample-app/analytics-service/build.gradle
Spring Boot recently released a patch to fix a vulnerability. This PR updates the Spring Boot version to the one which mitigates the issue.
https://spring.io/security/cve-2023-34055
Also updates the Spring dependency management library to the latest version.
N/A
Resolves CVE-2023-34055.
=> Updates example analytics-service to Spring Boot 3.1.6 fixing CVE-2023-34055

gradle.properties
Updates the version number to 2.6.1 for a release.
N/A - Release task
=> Update to Data Prepper 2.6.1 for upcoming release.

release/release-notes/data-prepper.change-log-2.6.1.md
Adds change log for 2.6.1 release
=> Add 2.6.1 change log

data-prepper-plugins/mutate-string-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutatestring/AbstractStringProcessor.java
Fix substitute string processor to handle exceptions gracefully.
Catch exceptions and log error messages instead of partially shutting down.
Resolves #2956 
Resolves #2956 
=> Fix substitute string processor to handle exceptions gracefully

data-prepper-plugins/s3-source/src/integrationTest/java/org/opensearch/dataprepper/plugins/source/s3/AvroRecordsGenerator.java, data-prepper-plugins/s3-source/src/integrationTest/java/org/opensearch/dataprepper/plugins/source/s3/S3ObjectWorkerIT.java
Adds avro record generator and adds tests using avro files to S3 object Integration tests
=> Add Avro integration test to s3 source

gradle.properties
Updates the `2.6` branch for a 2.6.2 release.
N/A
=> Version bump to 2.6.2

data-prepper-plugins/truncate-processor/README.md
Fix typo in truncate processor documentation
- [ X] New functionality has a documentation issue. Please link to it in this PR.
=> Fix typo in truncate processor documentation

data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/SqsWorker.java
Change SQS visibility timeout change message log level to debug level.
Changed log level to DEBUG level from INFO level.
=> Change SQS visibility timeout change message log level to debug level

build.gradle, data-prepper-plugins/http-sink/build.gradle, data-prepper-plugins/translate-processor/build.gradle, data-prepper-plugins/translate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/translate/MappingsHandler.java
Updating the AWSSDK version1 to version2
Contribute to #4017
=> Changing version AWSSDK V1 to V2

data-prepper-plugins/date-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/date/DateProcessor.java, data-prepper-plugins/date-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/date/DateProcessorTests.java
This change makes it so the date processor hitting an exception does not shut down the pipeline, and instead catches the exception and continues on to the next Event, instead of skipping the remainder of the Events in a batch
Resolves #4107 
=> Catch exception instead of shutting down in date processor

release/release-notes/data-prepper.release-notes-2.6.2.md
The release notes for Data Prepper 2.6.2
N/A
=> Adds release notes for Data Prepper 2.6.2

data-prepper-plugins/otel-metrics-source/src/main/java/org/opensearch/dataprepper/plugins/source/otelmetrics/OTelMetricsGrpcService.java
Missed setting the default link in PR 4190 due to corrupt workspace.
=> Missed default setting in PR 4190

build.gradle
Fix CVE-2024-26308, CVE-2024-25710
Resolves #4163 
Resolves #4164 
=> Fix commons-compress CVE

data-prepper-plugins/geoip-processor/build.gradle, data-prepper-plugins/geoip-processor/src/main/java/org/opensearch/dataprepper/plugins/geoip/extension/MaxMindConfig.java, data-prepper-plugins/geoip-processor/src/main/java/org/opensearch/dataprepper/plugins/geoip/extension/databasedownload/GeoIPDatabaseManager.java, data-prepper-plugins/geoip-processor/src/main/java/org/opensearch/dataprepper/plugins/geoip/extension/databasedownload/ManifestDownloadService.java, data-prepper-plugins/geoip-processor/src/main/java/org/opensearch/dataprepper/plugins/geoip/processor/GeoIPProcessor.java, data-prepper-plugins/geoip-processor/src/test/java/org/opensearch/dataprepper/plugins/geoip/extension/GeoIpServiceConfigTest.java, data-prepper-plugins/geoip-processor/src/test/java/org/opensearch/dataprepper/plugins/geoip/extension/MaxMindConfigTest.java
This PR has a few fixes and improvments from my recent testing.
* Avoid DNS lookups on IP addresses by using Guava's method to get an `InetAddress`.
* Set the `User-Agent` to `Data Prepper`
* Use the correct value for `database_destination`.
* Removes an unused project
* Updates MaxMind dependencies to their latest versions
N/A
=> Various fixes/improvements to the geoip processor

build-resources.gradle, build.gradle, data-prepper-expression/build.gradle, data-prepper-logstash-configuration/build.gradle
Build all plugins an independent jars
=> Build all plugins as independent jars.

build-resources.gradle, data-prepper-test-event/build.gradle
Adds all subprojects as core projects so that the release task works correctly.
=> Add all subprojects as core projects.

examples/log-ingestion-fluentd/README.md, examples/log-ingestion-fluentd/docker-compose.yaml, examples/log-ingestion-fluentd/fluent.conf
This provides a new example which uses Fluentd for log ingestion into Data Prepper. It demonstrates how you can configure Fluentd to send data in a format which Data Prepper can accept. This is similar to the data coming from FluentBit.
N/A
=> Example of using Fluentd to send data from a file to Data Prepper

data-prepper-plugins/kafka-plugins/README.md
=> MNT: system property on confluent registry integration test

data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/coordination/PartitionFactory.java, data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/coordination/partition/DataQueryPartition.java, data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/coordination/partition/ExportPartition.java, data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/coordination/partition/GlobalState.java, data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/coordination/partition/LeaderPartition.java, data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/coordination/partition/StreamPartition.java, data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/coordination/state/DataQueryProgressState.java, data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/coordination/state/ExportProgressState.java, data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/coordination/state/LeaderProgressState.java, data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/coordination/state/StreamProgressState.java, data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/coordination/PartitionFactoryTest.java
Add source coordinator partition and partition state
=> Add source coordinator partition and partition state

data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/buffer/ExportRecordBufferWriter.java, data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/converter/RecordConverter.java, data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/coordination/state/DataQueryProgressState.java, data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/documentdb/DocumentDBService.java, data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/documentdb/DocumentDBSource.java, data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/export/ExportScheduler.java, data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/export/ExportWorker.java, data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/buffer/ExportRecordBufferWriterTest.java, data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/coordination/PartitionFactoryTest.java, data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/export/ExportSchedulerTest.java, data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/export/ExportWorkerTest.java
Add DocumentDB/MongoDB source for initial load
=> Add DocumentDB/MongoDB source for initial load

data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/converter/RecordConverter.java, data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/documentdb/DocumentDBSource.java, data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/export/ExportWorker.java, data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/leader/LeaderScheduler.java, data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/leader/LeaderSchedulerTest.java
Unit test fix for MongoDB LeaderScheduler
=> Unit test fix for MongoDB LeaderScheduler

data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/export/ExportPartitionWorkerTest.java
Fix flaky test in ExportPartitionWorkerTest
Resolves #[[4298](https://github.com/opensearch-project/data-prepper/issues/4298)]
=> Fix flaky test in ExportPartitionWorkerTest

gradle.properties
Updates the version to `2.7.0` for the release.
N/A
=> Updates to 2.7.0

release/release-notes/data-prepper.release-notes-2.7.0.md
This adds release notes for Data Prepper 2.7.0.
N/A
=> Adds the release notes for Data Prepper 2.7.0.

data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkRetryStrategy.java, data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkRetryStrategyTests.java
This adds two new metrics:
* The number of duplicate documents from OpenSearch; as determined by the `_seq_no`.
* Counters for all error status at the document level
Resolves #4343 
Resolves #4344
=> Adds new metrics to help debug errors connecting to OpenSearch.

data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/converter/MetadataKeyAttributes.java, data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/converter/RecordConverter.java, data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/coordination/partition/StreamPartition.java, data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/coordination/state/StreamProgressState.java, data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/documentdb/DocumentDBService.java, data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/export/ExportPartitionWorker.java, data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/export/ExportScheduler.java, data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/export/ExportWorker.java, data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/leader/LeaderScheduler.java, data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/model/ExportLoadStatus.java, data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/model/StreamLoadStatus.java, data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/stream/DataStreamPartitionCheckpoint.java, data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamScheduler.java, data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamWorker.java, data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/converter/RecordConverterTest.java, data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/export/ExportSchedulerTest.java, data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/stream/DataStreamPartitionCheckpointTest.java, data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamSchedulerTest.java, data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamWorkerTest.java
Add support for MongoDB/DocumentDB stream processing
=> Add support for MongoDB/DocumentDB stream processing

release/script/release-notes/README.md, release/script/release-notes/format-release-notes.py, release/script/release-notes/generate-initial-release-notes.sh, release/script/release-notes/release-notes-template.md
I created this script for some recent release notes for Data Prepper. It doesn't produce final results, but it has helped me get started. We could use this to help us craft release notes for future releases.
N/A
=> Simple script to help generate the release notes file as a starting point

data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/client/MongoDBConnection.java, data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/configuration/CollectionConfig.java, data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/configuration/MongoDBSourceConfig.java, data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/documentdb/DocumentDBService.java, data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/leader/LeaderScheduler.java, data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/client/MongoDBConnectionTest.java, data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/leader/LeaderSchedulerTest.java
Rename DocDB/MongoDB config parameters
=> Rename DocDB/MongoDB config parameters

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/source/coordinator/enhanced/EnhancedSourceCoordinator.java, data-prepper-core/src/main/java/org/opensearch/dataprepper/sourcecoordination/enhanced/EnhancedLeaseBasedSourceCoordinator.java, data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/client/MongoDBConnection.java, data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/configuration/AwsConfig.java, data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/configuration/CollectionConfig.java, data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/configuration/MongoDBSourceConfig.java, data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/converter/PartitionKeyRecordConverter.java, data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/documentdb/DocumentDBService.java, data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/documentdb/MongoTasksRefresher.java, data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/export/ExportWorker.java, data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/leader/LeaderScheduler.java, data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamScheduler.java, data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/client/MongoDBConnectionTest.java, data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/documentdb/MongoTasksRefresherTest.java, data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/leader/LeaderSchedulerTest.java
Update DocumentDB source pipeline config parameters 
=> Update DocumentDB source pipeline config parameters 

data-prepper-pipeline-parser/src/main/resources/templates/documentdb-template.yaml
=> Modify documentdb template

data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/documentdb/DocumentDBService.java, data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/documentdb/MongoTasksRefresher.java, data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/export/ExportWorker.java, data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/leader/LeaderScheduler.java, data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamScheduler.java, data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/documentdb/MongoTasksRefresherTest.java, data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/export/ExportWorkerTest.java, data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/leader/LeaderSchedulerTest.java, data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamSchedulerTest.java, data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamWorkerTest.java
Fix DocumentDB source S3PathPrefix null or empty
=> Fix DocumentDB source S3PathPrefix null or empty

data-prepper-expression/build.gradle, data-prepper-logstash-configuration/build.gradle
This PR adds two projects which were missing the new publication plugin. See #4421 for the original work where I missed these projects.
N/A
=> Publish expression and logstash-configuration to Maven

data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/s3partition/S3PartitionCreatorScheduler.java
Fix for S3PartitionCreatorScheduler ConcurrentModification Exception
=> Fix for S3PartitionCreatorScheduler ConcurrentModification Exception

data-prepper-pipeline-parser/src/main/java/org/opensearch/dataprepper/pipeline/parser/rule/RuleEvaluator.java, data-prepper-pipeline-parser/src/main/java/org/opensearch/dataprepper/pipeline/parser/transformer/DynamicConfigTransformer.java, data-prepper-pipeline-parser/src/main/java/org/opensearch/dataprepper/pipeline/parser/transformer/TransformersFactory.java, data-prepper-pipeline-parser/src/test/java/org/opensearch/dataprepper/pipeline/parser/transformer/DynamicConfigTransformerTest.java
- Fixed transient test failures for pipeline configuration transformation.
- Fixed null handling.
=> Fix transient test failure for subpipelines

data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/client/BsonHelper.java, data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/converter/PartitionKeyRecordConverter.java, data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/converter/RecordConverter.java, data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/export/ExportPartitionWorker.java, data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamWorker.java, data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/converter/RecordConverterTest.java, data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/export/ExportPartitionWorkerTest.java, data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamWorkerTest.java
Add BsonType of primary key to metadata
=> Add BsonType of primary key to metadata

data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamWorker.java, data-prepper-plugins/mongodb/src/test/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamWorkerTest.java
Adds bytesProcessed metric for stream. It was added to export but not for stream.
N/A
=> Add bytesProcessed metric for DocumentDB stream

data-prepper-plugins/write-json-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/write_json/WriteJsonProcessorTest.java
=> Fix write json basic test

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/configuration/DataPrepperVersion.java, gradle.properties
Updates the next Data Prepper version to 2.9
=> Updates the next Data Prepper version to 2.9

data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/configuration/CollectionConfig.java, data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/export/MongoDBExportPartitionSupplier.java, data-prepper-plugins/mongodb/src/main/java/org/opensearch/dataprepper/plugins/mongo/stream/StreamWorker.java
- Logging improvements for export and stream processing.
- Added validation in Collection Config
=> Logging update and config validation

gradle.properties
=> Change version for 2.8 release to be 2.8.0

release/release-notes/data-prepper.change-log-2.8.0.md
=> Release 28 changelog fix

data-prepper-plugins/kafka-plugins/build.gradle
=> MAINT: bump io.confluent:* packages to match org.apache.kafka.*

CODE_OF_CONDUCT.md
Updates the `CODE_OF_CONDUCT.md` file to match exactly what is found at:
https://github.com/opensearch-project/.github/blob/main/CODE_OF_CONDUCT.md
N/A
=> Updates to the CODE_OF_CONDUCT.md from opensearch-project

data-prepper-plugins/split-event-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/splitevent/SplitEventProcessorConfig.java
Adding schema gaps so that the JSON schema model for enhanced UI view can be auto-generated
=> doc strings for enhanced UI view auto-generation

data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/RdsService.java, data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/RdsSourceConfig.java, data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/configuration/TlsConfig.java, data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/converter/ExportRecordConverter.java, data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/converter/MetadataKeyAttributes.java, data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/converter/StreamRecordConverter.java, data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/coordination/state/DataFileProgressState.java, data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/coordination/state/ExportProgressState.java, data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/export/DataFileLoader.java, data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/export/ExportScheduler.java, data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/leader/LeaderScheduler.java, data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/BinlogClientFactory.java, data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/BinlogEventListener.java, data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/StreamWorker.java, data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/RdsServiceTest.java, data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/converter/ExportRecordConverterTest.java, data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/converter/StreamRecordConverterTest.java
A few improvements to rds source:
- Adds error logging to event handlers
- Adds TLS config and enable tls by default
- Adds more event metadata, e.g. original event name, event create time (uses snapshot time for export events), event version number.
=> A few improvements to rds source

gradle.properties
Updates to Data Prepper 2.8.1
N/A
=> Data Prepper 2.8.1

release/release-notes/data-prepper.release-notes-2.8.1.md
Release notes for Data Prepper 2.8.1
N/A
=> Release notes for Data Prepper 2.8.1

gradle.properties
Change release version in 2.9 branch to 2.9.0
=> Change release version in 2.9 branch to 2.9.0

release/release-notes/data-prepper.change-log-2.9.0.md
Changelog for release 2.9
Generated by the command
```
git-release-notes 2.8.1..HEAD markdown > /tmp/data-prepper.change-log-2.9.0.md
```
=> Changelog for release 2.9

data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/export/DataFileLoader.java
Add sensitive marker to logs to mask s3 object key
N/A
=> Add sensitive marker to logs

release/script/blog/README.md, release/script/blog/format-release-thank-you.py
Adds a script to help generate the Thank You text for the release blogs.
N/A
=> Adds a script to help generate the Thank You text for the release blogs.

build-resources.gradle
=> MAINT: add data prepper plugin schema module into build resource

data-prepper-plugins/common/src/main/java/org/opensearch/dataprepper/plugins/sink/NoopSink.java, data-prepper-plugins/common/src/test/java/org/opensearch/dataprepper/plugins/sink/NoopSinkTest.java
=> Release events for Noop Sink

data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/ScanObjectWorker.java, data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/s3/S3ScanObjectWorkerTest.java
This change follows from https://github.com/opensearch-project/data-prepper/pull/4918/commits/ce9bca0056ea45190f7494b44e697ecb41fdd11a, but adds the progress check for folder partitioning mode in s3 scan source, which was missed in the previous PR
Related to #4422 
=> Add acknowledgment progress check for s3 source with folder partitions

data-prepper-plugins/mutate-string-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutatestring/SplitStringProcessorConfig.java, data-prepper-plugins/mutate-string-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutatestring/SubstituteStringProcessorConfig.java, data-prepper-plugins/translate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/translate/MappingsParameterConfig.java
A split efforts following https://github.com/opensearch-project/data-prepper/pull/4989
* split string
* substitute string
* translate processor
=> FIX: missing required fields annotation

data-prepper-plugins/mutate-string-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutatestring/LowercaseStringProcessor.java, data-prepper-plugins/mutate-string-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutatestring/TrimStringProcessor.java, data-prepper-plugins/mutate-string-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutatestring/UppercaseStringProcessor.java, data-prepper-plugins/mutate-string-processors/src/test/java/org/opensearch/dataprepper/plugins/processor/mutatestring/LowercaseStringProcessorTests.java, data-prepper-plugins/mutate-string-processors/src/test/java/org/opensearch/dataprepper/plugins/processor/mutatestring/TrimStringProcessorTests.java, data-prepper-plugins/mutate-string-processors/src/test/java/org/opensearch/dataprepper/plugins/processor/mutatestring/UppercaseStringProcessorTests.java
This PR fixes the regression introduced by recent changes on mutate string processor config classes
=> FIX: mutate string processor configs

release/release-notes/data-prepper.change-log-2.10.0.md
This PR is to add the change log for Data Prepper 2.10.
Resolves #3371
=> Add change log for Data prepper 2.10

data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/S3SinkConfig.java, data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/s3/S3SinkConfigTest.java
Fixed s3 sink config validation
=> Fixed s3 sink config validation

gradle.properties
Version number fix to be ready for the release
=> Version number fix to be ready for the release

data-prepper-plugins/date-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/date/DateProcessorConfig.java, data-prepper-plugins/dissect-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/dissect/DissectProcessorConfig.java, data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/DeleteEntryProcessorConfig.java
Correct schema descriptions and embed links in Date, Dissect, and Delete Entry processors.
=> Fix embed links

gradle.properties
Updates to Data Prepper `2.10.1`.
N/A
=> Updates the version to 2.10.1.

MAINTAINERS.md
Welcomes Souvik Bose ([sb2k16](https://github.com/sb2k16)) as a maintainer on the project.
N/A
=> Welcomes Souvik Bose as a maintainer on the project.

release/release-notes/data-prepper.release-notes-2.10.1.md
This PR adds release notes for v2.10 patch release.
=> Add release notes for 2.10 patch release

data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/SelectEntriesProcessorConfig.java, data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parse/ion/ParseIonProcessorConfig.java, data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parse/json/ParseJsonProcessorConfig.java, data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parse/xml/ParseXmlProcessorConfig.java
Add example annotations to the below processors:
1. Select Entries
2. Parse ION
3. Parse JSON
4. Parse XML
=> add example annotations

data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/StreamWorker.java
Catch all exceptions during binlog client connect/disconnect to help troubleshooting connection issues.
N/A
=> Catch all exceptions during binlog client connect/disconnect

data-prepper-plugins/saas-source-plugins/jira-source/src/main/java/org/opensearch/dataprepper/plugins/source/jira/JiraIterator.java, data-prepper-plugins/saas-source-plugins/jira-source/src/main/java/org/opensearch/dataprepper/plugins/source/jira/JiraService.java, data-prepper-plugins/saas-source-plugins/jira-source/src/main/java/org/opensearch/dataprepper/plugins/source/jira/rest/JiraRestClient.java, data-prepper-plugins/saas-source-plugins/jira-source/src/main/java/org/opensearch/dataprepper/plugins/source/jira/rest/auth/JiraBasicAuthConfig.java, data-prepper-plugins/saas-source-plugins/jira-source/src/test/java/org/opensearch/dataprepper/plugins/source/jira/JiraIteratorTest.java, data-prepper-plugins/saas-source-plugins/jira-source/src/test/java/org/opensearch/dataprepper/plugins/source/jira/JiraServiceTest.java, data-prepper-plugins/saas-source-plugins/jira-source/src/test/java/org/opensearch/dataprepper/plugins/source/jira/rest/JiraRestClientTest.java, data-prepper-plugins/saas-source-plugins/jira-source/src/test/java/org/opensearch/dataprepper/plugins/source/jira/rest/auth/JiraAuthFactoryTest.java, data-prepper-plugins/saas-source-plugins/jira-source/src/test/java/org/opensearch/dataprepper/plugins/source/jira/rest/auth/JiraBasicAuthConfigTest.java
Changes to JiraSource
Switch some logs to trace
Removed JiraProjectCache and stop bringing projects into pipeline since some projects had a null pointer issue
fix issue that occurred when accountUrl didn't end with a slash
=> Jira source fixes

data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/RdsService.java, data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/datatype/DataTypeHandler.java, data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/datatype/MySQLDataType.java, data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/datatype/impl/BinaryTypeHandler.java, data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/datatype/impl/JsonTypeHandler.java, data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/datatype/impl/NumericTypeHandler.java, data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/datatype/impl/SpatialTypeHandler.java, data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/datatype/impl/StringTypeHandler.java, data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/export/DataFileLoader.java, data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/export/DataFileScheduler.java, data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/leader/LeaderScheduler.java, data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/model/DbTableMetadata.java, data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/BinlogEventListener.java, data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/StreamWorkerTaskRefresher.java, data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/datatype/impl/BinaryTypeHandlerTest.java, data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/datatype/impl/JsonTypeHandlerTest.java, data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/datatype/impl/NumericTypeHandlerTest.java, data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/datatype/impl/SpatialTypeHandlerTest.java, data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/export/DataFileLoaderTest.java, data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/export/DataFileSchedulerTest.java, data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/leader/LeaderSchedulerTest.java, data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/stream/BinlogEventListenerTest.java, data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/stream/StreamWorkerTaskRefresherTest.java
Support Data type Mapping transformation for MySQL export and stream processing
Resolves #[4561](https://github.com/opensearch-project/data-prepper/issues/4561)
=> Support Data type transformation for MySQL export and stream processing

data-prepper-plugins/aws-lambda/src/integrationTest/java/org/opensearch/dataprepper/plugins/lambda/LambdaProcessorSinkIT.java, data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/sink/LambdaSink.java, data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/sink/dlq/DlqPushHandler.java, data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/sink/dlq/LambdaSinkFailedDlqData.java, data-prepper-plugins/aws-lambda/src/test/java/org/opensearch/dataprepper/plugins/lambda/sink/LambdaSinkTest.java, data-prepper-plugins/aws-lambda/src/test/java/org/opensearch/dataprepper/plugins/lambda/sink/dlq/DlqPushHandlerTest.java, data-prepper-plugins/aws-lambda/src/test/java/org/opensearch/dataprepper/plugins/lambda/sink/dlq/LambdaSinkFailedDlqDataTest.java
Fix Lambda sink DLQ support. Followed same logic as opensearch sink DLQ
=> Fix Lambda sink DLQ support

data-prepper-plugins/otel-logs-source/src/main/java/org/opensearch/dataprepper/plugins/source/otellogs/OTelLogsSource.java
=> [Backport 2.10] Fix otel_logs_source server configuration for getHttpAuthenticationService

examples/trace-analytics-sample-app/sample-app/requirements.txt
Fix CVE vulnerability
Resolves #5122 
=> Fix CVE vulnerability

gradle.properties
Change dataprepper version 2.10.2
=> Change dataprepper version 2.10.2

release/release-notes/data-prepper.release-notes-2.10.2.md
=> Release notes for 2.10.2

data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateProcessorConfig.java, data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/processor/LambdaProcessorConfig.java, data-prepper-plugins/key-value-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/keyvalue/KeyValueProcessorConfig.java, data-prepper-plugins/otel-metrics-source/src/test/java/org/opensearch/dataprepper/plugins/source/otelmetrics/OTelMetricsSourceTest.java
- Fix capitalization in aggregate processor description
- Remove default values from include and exclude keys in key value processor
- Add descriptions to some AWS Lambda processor fields
- Remove unused import
=> Schema revisions

data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/AndOperatorTest.java, data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/EqualOperatorTest.java, data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/GenericNotOperatorTest.java, data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/GreaterThanOperatorTest.java, data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/GreaterThanOrEqualOperatorTest.java, data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/LessThanOperatorTest.java, data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/LessThanOrEqualOperatorTest.java, data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/NotInSetOperatorTest.java, data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/NotOperatorTest.java, data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/OrOperatorTest.java, data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/RegexEqualOperatorTest.java, data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/RegexNotEqualOperatorTest.java, data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/TypeOfOperatorTest.java
Fix failing data-prepper-expression code coverage verfication
=> Fix failing data-prepper-expression code coverage verfication

data-prepper-core/src/main/java/org/opensearch/dataprepper/core/parser/PipelineTransformer.java, data-prepper-core/src/test/java/org/opensearch/dataprepper/core/parser/PipelineTransformerTests.java
This PR includes routing validation errors into plugin error collector as a refactoring on top of https://github.com/opensearch-project/data-prepper/pull/5060/files
=> FIX: include route validation error into collector

CONTRIBUTING.md
Minor fix to the formatting of the license header. This corrects the whitespace.
N/A
=> Minor fix to the formatting of the license header.

.github/CODEOWNERS, MAINTAINERS.md
Welcoming Srikanth Govindarajan ([srikanthjg](https://github.com/srikanthjg)) to the Data Prepper maintainers.
Srikanth has contributed [19 merged PRs](https://github.com/opensearch-project/data-prepper/pulls?q=is%3Apr+author%3Asrikanthjg+is%3Aclosed) to the project. I’d like to highlight a couple of major features:
* Split event processor. ([#4166](https://github.com/opensearch-project/data-prepper/pull/4166))
* Dynamic pipeline transformations. ([#4446](https://github.com/opensearch-project/data-prepper/pull/4446), [#4601](https://github.com/opensearch-project/data-prepper/pull/4601))
* AWS Lambda as a processor and sink ([#4292](https://github.com/opensearch-project/data-prepper/pull/4292), [#4643](https://github.com/opensearch-project/data-prepper/pull/4643), …
=> Welcoming Srikanth Govindarajan (srikanthjg) to the Data Prepper maintainers

data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/configuration/EngineType.java, data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/coordination/state/DataFileProgressState.java, data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/coordination/state/ExportProgressState.java, data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/export/DataFileLoader.java, data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/export/ExportScheduler.java, data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/leader/LeaderScheduler.java, data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/model/ExportObjectKey.java, data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/LogicalReplicationClient.java, data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/LogicalReplicationEventProcessor.java, data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/stream/StreamWorker.java, data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/leader/LeaderSchedulerTest.java, data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/model/ExportObjectKeyTest.java, data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/stream/LogicalReplicationClientTest.java
Minor changes added to support RDS export. 
Also added some changes to throw exception when stream client connection fails and give up stream partition so it can be retried. 
Contributes to #5309 
=> Support export from Postgres in rds source

data-prepper-plugins/aws-lambda/src/integrationTest/java/org/opensearch/dataprepper/plugins/lambda/processor/LambdaProcessorIT.java, data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/common/LambdaCommonHandler.java, data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/common/util/ThresholdCheck.java, data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/processor/LambdaProcessor.java, data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/sink/LambdaSink.java, data-prepper-plugins/aws-lambda/src/test/java/org/opensearch/dataprepper/plugins/lambda/common/LambdaCommonHandlerTest.java, data-prepper-plugins/aws-lambda/src/test/java/org/opensearch/dataprepper/plugins/lambda/common/ThresholdCheckTest.java, data-prepper-plugins/aws-lambda/src/test/java/org/opensearch/dataprepper/plugins/lambda/processor/LambdaProcessorTest.java, data-prepper-plugins/aws-lambda/src/test/java/org/opensearch/dataprepper/plugins/lambda/sink/LambdaSinkTest.java, data-prepper-plugins/aws-lambda/src/test/resources/lambda-processor-large-payload.yaml, data-prepper-plugins/aws-lambda/src/test/resources/lambda-processor-payload-limit.yaml
Fix lambda processor batching
1. Fixed threshold check 
2. Fix futures handling
3. Refactor and fix lambda sink 
Resolves #5473 
=> Fix lambda processor batching

data-prepper-plugins/saas-source-plugins/confluence-source/src/main/java/org/opensearch/dataprepper/plugins/source/confluence/rest/ConfluenceRestClient.java, data-prepper-plugins/saas-source-plugins/confluence-source/src/test/java/org/opensearch/dataprepper/plugins/source/confluence/utils/TimezoneHelperTest.java, data-prepper-plugins/saas-source-plugins/jira-source/src/main/java/org/opensearch/dataprepper/plugins/source/jira/rest/JiraRestClient.java
Additional metrics for failure case added
=> Jira metrics fix

data-prepper-plugins/saas-source-plugins/atlassian-commons/src/main/java/org/opensearch/dataprepper/plugins/source/atlassian/rest/AtlassianRestClient.java, data-prepper-plugins/saas-source-plugins/atlassian-commons/src/test/java/org/opensearch/dataprepper/plugins/source/atlassian/rest/AtlassianRestClientTest.java, data-prepper-plugins/saas-source-plugins/confluence-source/src/main/java/org/opensearch/dataprepper/plugins/source/confluence/rest/ConfluenceRestClient.java, data-prepper-plugins/saas-source-plugins/confluence-source/src/test/java/org/opensearch/dataprepper/plugins/source/confluence/rest/ConfluenceRestClientTest.java, data-prepper-plugins/saas-source-plugins/jira-source/src/main/java/org/opensearch/dataprepper/plugins/source/jira/rest/JiraRestClient.java
One more additional metric and its corresponding test cases added. 
=> one more additional metric added

data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/configuration/ActionConfiguration.java
=> FIX: invalid Jakarta annotation on enum type in ActionConfiguration

data-prepper-plugins/aws-lambda/src/integrationTest/java/org/opensearch/dataprepper/plugins/lambda/LambdaProcessorSinkIT.java, data-prepper-plugins/aws-lambda/src/integrationTest/java/org/opensearch/dataprepper/plugins/lambda/processor/LambdaProcessorIT.java, data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/processor/LambdaProcessor.java, data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/processor/LambdaProcessorConfig.java, data-prepper-plugins/aws-lambda/src/test/java/org/opensearch/dataprepper/plugins/lambda/processor/LambdaProcessorConfigTest.java, data-prepper-plugins/aws-lambda/src/test/java/org/opensearch/dataprepper/plugins/lambda/processor/LambdaProcessorTest.java, data-prepper-plugins/aws-lambda/src/test/resources/lambda-processor-circuit-breaker-config.yaml
Add circuit breaker support for lambda processor
Resolves #5536 
- Made sure that the circuit breaker used is the one used globally
- Added approriate UTs
- Tests with IT
=> Add circuit breaker support for lambda processor

data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/processor/LambdaProcessor.java
Improves the AWS Lambda processor's memory usage by creating fewer byte arrays when handling the response from the Lambda function. This uses the existing `InputStream` from `SdkBytes.` It also converts the "null" string to UTF-8 once to perform `byte[]` comparison on the response.
N/A
=> Reduces byte array copies in AWS Lambda processor when handling the response

gradle.properties
Updates the Data Prepper version to 2.10.3
N/A
=> Data Prepper 2.10.3

data-prepper-plugins/saas-source-plugins/crowdstrike-source/src/main/java/org/opensearch/dataprepper/plugins/source/crowdstrike/CrowdStrikeSource.java
CrowdStrike plugin is under development. Marking it as experimental.
=> Marking CrowdStrike as Experimental

data-prepper-api/src/main/java/org/opensearch/dataprepper/model/configuration/DataPrepperVersion.java
Change version in DataPrepper Version class to 2.12
=> Change version in DataPrepper Version class to 2.12

gradle.properties
Change main branch version to 2.12.0-SNAPSHOT
=> Change main branch version to 2.12.0-SNAPSHOT

release/release-notes/data-prepper.change-log-2.11.0.md
=> Changelog-2.11.0

data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/ConnectionConfiguration.java, data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/configuration/AuthConfig.java, data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/configuration/OpenSearchSinkConfig.java
=> Add support for api token in config

settings.gradle
Updates Avro to 1.11.4
Fixes CVE-2024-47561
https://github.com/advisories/GHSA-r7pg-v2c8-mfg3
=> Avro 1.11.4

release/release-notes/data-prepper.release-notes-2.12.0.md
Release notes for Data Prepper 2.12.
N/A
=> Adds the release notes for Data Prepper 2.12.

release/script/blog/format-release-thank-you.py
Updates the format release note script to skip bot users.
N/A
=> Updates the format release note script to skip bot users.

data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/buffer/KafkaBufferTest.java
Remove unused import to fix build.
N/A
=> Remove unused import to fix build

data-prepper-plugins/aws-plugin/src/main/java/org/opensearch/dataprepper/plugins/aws/CredentialsProviderFactory.java
Make createStsClient protected
=> Make createStsClient protected

gradle.properties
Updates Data Prepper to 2.12.1.
N/A
=> Updates to Data Prepper 2.12.1

data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/ShardConsumer.java, data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/ShardConsumerTest.java
Fixes a bug in #5818 where shards would not be completed when getRecords returned no records and a null shardIterator
Resolves #4764
=> Ensure shards are completed when last getRecords call has no records and no shardIterator

data-prepper-plugins/dynamodb-source/build.gradle, data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/DynamoDBSourceConfig.java, data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/model/ShardCheckpointStatus.java, data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/ShardAcknowledgementManager.java, data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/ShardConsumer.java, data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/ShardConsumerFactory.java, data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/StreamCheckpointer.java, data-prepper-plugins/dynamodb-source/src/main/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/StreamScheduler.java, data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/ShardAcknowledgementManagerTest.java, data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/ShardConsumerFactoryTest.java, data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/ShardConsumerTest.java, data-prepper-plugins/dynamodb-source/src/test/java/org/opensearch/dataprepper/plugins/source/dynamodb/stream/StreamSchedulerTest.java
This reverts commit d04018185a593d88d6acc2b6adf498a1164813db.
=> Revert "Revert DDB checkpoint acknowledgment changes temporarily (#5967)"

data-prepper-plugins/ml-inference-processor/src/main/java/org/opensearch/dataprepper/plugins/ml_inference/processor/common/SageMakerBatchJobCreator.java, data-prepper-plugins/ml-inference-processor/src/test/java/org/opensearch/dataprepper/plugins/ml_inference/processor/common/SageMakerBatchJobCreatorTest.java
Add the multi-thread locker in the SageMakerBatchJobCreator to ensure batch jobs are always created by 1 single thread to avoid edge cases. 
=> Add multithread locker in the SageMaker Batchjob Creater
